BibleTime: BtSearchModuleChooserDialog Class Reference
BtSearchModuleChooserDialog Class Reference
#include <btsearchmodulechooserdialog.h>
Public Member Functions
BtSearchModuleChooserDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
BtConstModuleSet checkedModules () const
void setCheckedModules (BtConstModuleSet const &modules)
Protected Member Functions
void retranslateUi ()
Protected Member Functions inherited from BtModuleChooserDialog
BtBookshelfWidget * bookshelfWidget () const
BtModuleChooserDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
QDialogButtonBox * buttonBox () const
QLabel * label () const
void retranslateUi ()
Detailed Description
Definition at line 25 of file btsearchmodulechooserdialog.h.
Constructor & Destructor Documentation
BtSearchModuleChooserDialog()
BtSearchModuleChooserDialog::BtSearchModuleChooserDialog (QWidget * parent = nullptr, Qt::WindowFlags flags = Qt::WindowFlags())
Definition at line 32 of file btsearchmodulechooserdialog.cpp.
References BtModuleChooserDialog::bookshelfWidget(), BT_CONNECT, btConfig(), BtBookshelfTreeModel::groupingOrderChanged(), CSwordBackend::instance(), retranslateUi(), BtBookshelfTreeModel::Grouping::saveTo(), BtBookshelfWidget::setSourceModel(), BtBookshelfWidget::setTreeModel(), BtBookshelfWidget::showHideAction(), and BtBookshelfWidget::showHideButton().
Member Function Documentation
checkedModules()
BtConstModuleSet BtSearchModuleChooserDialog::checkedModules () const
Definition at line 57 of file btsearchmodulechooserdialog.cpp.
References BtModuleChooserDialog::bookshelfWidget(), BtBookshelfTreeModel::checkedModules(), and BtBookshelfWidget::treeModel().
Referenced by Search::BtSearchOptionsArea::chooseModules().
retranslateUi()
void BtSearchModuleChooserDialog::retranslateUi () protected
Definition at line 60 of file btsearchmodulechooserdialog.cpp.
References util::tool::initExplanationLabel(), and BtModuleChooserDialog::label().
Referenced by BtSearchModuleChooserDialog().
setCheckedModules()
void BtSearchModuleChooserDialog::setCheckedModules (BtConstModuleSet const & modules)
Definition at line 53 of file btsearchmodulechooserdialog.cpp.
References BtModuleChooserDialog::bookshelfWidget(), BtBookshelfTreeModel::setCheckedModules(), and BtBookshelfWidget::treeModel().
Referenced by Search::BtSearchOptionsArea::chooseModules().
The documentation for this class was generated from the following files:
btsearchmodulechooserdialog.h
btsearchmodulechooserdialog.cpp