BibleTime: BtShortcutsEditor Class Reference
BtShortcutsEditor Class Reference
#include <btshortcutseditor.h>
Signals
void keyChangeRequest (QString const &actionName, QKeySequence const &keys)
Public Member Functions
BtShortcutsEditor (BtActionCollection *collection, QWidget *parent)
void changeShortcutInDialog (QKeySequence const &keys)
void clearConflictWithKeys (QKeySequence const &keys)
void commitChanges ()
QString findConflictWithKeys (QKeySequence const &keys) const
Private Slots
void customButtonClicked (bool checked)
void defaultButtonClicked (bool checked)
void noneButtonClicked (bool checked)
void slotSelectionChanged ()
Private Attributes
int m_currentRow
QRadioButton * m_customButton
QPushButton * m_customPushButton
QRadioButton * m_defaultButton
QLabel * m_defaultLabelValue
BtShortcutsDialog * m_dlg
QRadioButton * m_noneButton
QGroupBox * m_shortcutChooser
QTableWidget * m_table
Detailed Description
Definition at line 31 of file btshortcutseditor.h.
Constructor & Destructor Documentation
BtShortcutsEditor()
BtShortcutsEditor::BtShortcutsEditor (BtActionCollection * collection, QWidget * parent)
Todo:
Remove this & hack and use Qt properties instead:
Definition at line 122 of file btshortcutseditor.cpp.
References BtActionCollection::actions(), BT_CONNECT, customButtonClicked(), defaultButtonClicked(), BtActionCollection::getDefaultShortcut(), BtShortcutsDialog::keyChangeRequest(), keyChangeRequest(), m_currentRow, m_customButton, m_customPushButton, m_defaultButton, m_defaultLabelValue, m_dlg, m_noneButton, m_shortcutChooser, m_table, noneButtonClicked(), and slotSelectionChanged().
Member Function Documentation
changeShortcutInDialog()
void BtShortcutsEditor::changeShortcutInDialog (QKeySequence const & keys)
Definition at line 352 of file btshortcutseditor.cpp.
References BtShortcutsDialog::changeSelectedShortcut(), and m_dlg.
clearConflictWithKeys()
void BtShortcutsEditor::clearConflictWithKeys (QKeySequence const & keys)
Definition at line 356 of file btshortcutseditor.cpp.
References m_table.
commitChanges()
void BtShortcutsEditor::commitChanges ()
Definition at line 262 of file btshortcutseditor.cpp.
References m_table.
customButtonClicked
void BtShortcutsEditor::customButtonClicked (bool checked) private slot
Todo:
Is this correct?
Definition at line 326 of file btshortcutseditor.cpp.
References BtShortcutsDialog::getFirstKeys(), BtShortcutsDialog::getSecondKeys(), m_currentRow, m_dlg, m_table, BtShortcutsDialog::setFirstKeys(), and BtShortcutsDialog::setSecondKeys().
Referenced by BtShortcutsEditor().
defaultButtonClicked
void BtShortcutsEditor::defaultButtonClicked (bool checked) private slot
Todo:
Is this correct?
Definition at line 311 of file btshortcutseditor.cpp.
References m_currentRow, m_customPushButton, and m_table.
Referenced by BtShortcutsEditor().
findConflictWithKeys()
QString BtShortcutsEditor::findConflictWithKeys (QKeySequence const & keys) const
Definition at line 373 of file btshortcutseditor.cpp.
References m_table.
keyChangeRequest
void BtShortcutsEditor::keyChangeRequest (QString const & actionName, QKeySequence const & keys) signal
Referenced by BtShortcutsEditor(), and CAcceleratorSettingsPage::CAcceleratorSettingsPage().
noneButtonClicked
void BtShortcutsEditor::noneButtonClicked (bool checked) private slot
Todo:
Is this correct?
Definition at line 297 of file btshortcutseditor.cpp.
References m_currentRow, m_customPushButton, and m_table.
Referenced by BtShortcutsEditor().
slotSelectionChanged
void BtShortcutsEditor::slotSelectionChanged () private slot
Definition at line 270 of file btshortcutseditor.cpp.
References m_currentRow, m_customButton, m_customPushButton, m_defaultButton, m_defaultLabelValue, m_noneButton, and m_table.
Referenced by BtShortcutsEditor().
Member Data Documentation
m_currentRow
int BtShortcutsEditor::m_currentRow private
Definition at line 78 of file btshortcutseditor.h.
Referenced by BtShortcutsEditor(), customButtonClicked(), defaultButtonClicked(), noneButtonClicked(), and slotSelectionChanged().
m_customButton
QRadioButton* BtShortcutsEditor::m_customButton private
Definition at line 75 of file btshortcutseditor.h.
Referenced by BtShortcutsEditor(), and slotSelectionChanged().
m_customPushButton
QPushButton* BtShortcutsEditor::m_customPushButton private
Definition at line 76 of file btshortcutseditor.h.
Referenced by BtShortcutsEditor(), defaultButtonClicked(), noneButtonClicked(), and slotSelectionChanged().
m_defaultButton
QRadioButton* BtShortcutsEditor::m_defaultButton private
Definition at line 74 of file btshortcutseditor.h.
Referenced by BtShortcutsEditor(), and slotSelectionChanged().
m_defaultLabelValue
QLabel* BtShortcutsEditor::m_defaultLabelValue private
Definition at line 77 of file btshortcutseditor.h.
Referenced by BtShortcutsEditor(), and slotSelectionChanged().
m_dlg
BtShortcutsDialog* BtShortcutsEditor::m_dlg private
Definition at line 70 of file btshortcutseditor.h.
Referenced by BtShortcutsEditor(), changeShortcutInDialog(), and customButtonClicked().
m_noneButton
QRadioButton* BtShortcutsEditor::m_noneButton private
Definition at line 73 of file btshortcutseditor.h.
Referenced by BtShortcutsEditor(), and slotSelectionChanged().
m_shortcutChooser
QGroupBox* BtShortcutsEditor::m_shortcutChooser private
Definition at line 72 of file btshortcutseditor.h.
Referenced by BtShortcutsEditor().
m_table
QTableWidget* BtShortcutsEditor::m_table private
Definition at line 71 of file btshortcutseditor.h.
Referenced by BtShortcutsEditor(), clearConflictWithKeys(), commitChanges(), customButtonClicked(), defaultButtonClicked(), findConflictWithKeys(), noneButtonClicked(), and slotSelectionChanged().
The documentation for this class was generated from the following files:
btshortcutseditor.h
btshortcutseditor.cpp