BibleTime: BibleTime Class Reference
BibleTime Class Reference
#include <bibletime.h>
Public Slots
void autoScrollStop ()
static void insertKeyboardActions (BtActionCollection *const a)
void openOnlineHelp_Handbook ()
void openOnlineHelp_Howto ()
void processCommandline (bool ignoreSession, const QString &bibleKey)
void slotBookshelfWizard ()
void slotOpenTipDialog ()
void slotSettingsOptions ()
Signals
void colorThemeChanged ()
void toggledTextWindowHeader (bool newState)
void toggledTextWindowModuleChooser (bool newState)
void toggledTextWindowNavigator (bool newState)
void toggledTextWindowToolButtons (bool newState)
Public Member Functions
BibleTime (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
void clearMdiToolBars ()
BtModelViewReadDisplay * getCurrentDisplay ()
const CSwordModuleInfo * getCurrentModule ()
InfoDisplay::CInfoDisplay * infoDisplay () const
CKeyChooser * keyChooser () const
QToolBar * navToolBar () const
void openFindWidget ()
void openSearchDialog (BtConstModuleList modules, QString const &searchText=QString())
void saveConfigSettings ()
void setDisplayFocus ()
QToolBar * toolsToolBar () const
BtModuleChooserBar * worksToolBar () const
~BibleTime () override
Static Public Member Functions
static BibleTime * instance ()
static bool moduleUnlock (CSwordModuleInfo *module, QWidget *parent=nullptr)
Protected Slots
bool autoScrollAnyKey (int key)
void autoScrollDown ()
void autoScrollPause ()
void autoScrollUp ()
CDisplayWindow * createReadDisplayWindow (CSwordModuleInfo *module, const QString &key=QString())
CDisplayWindow * createReadDisplayWindow (QList< CSwordModuleInfo * > modules, const QString &key)
void deleteProfile (QAction *action)
void loadProfile (const QString &profileKey)
void loadProfile (QAction *action)
void moduleAbout (CSwordModuleInfo *module)
void refreshProfileMenus ()
void reloadProfile ()
void saveProfile ()
void saveToNewProfile ()
void slotActiveWindowChanged (QMdiSubWindow *window)
void slotAutoScroll ()
void slotCascade ()
void slotModuleUnlock (CSwordModuleInfo *module)
void slotOpenAboutDialog ()
void slotOpenWindowsMenuAboutToShow ()
void slotSearchDefaultBible ()
void slotSearchModules ()
void slotSetActiveSubWindow (QWidget *window)
void slotTile ()
void slotTileHorizontal ()
void slotTileVertical ()
void slotToggleMainToolbar ()
void slotToggleNavigatorToolbar ()
void slotToggleTextWindowHeader ()
void slotToggleToolBarsInEachWindow ()
void slotToggleToolsToolbar ()
void slotToggleWorksToolbar ()
void slotUpdateWindowArrangementActions (QAction *trigerredAction)
void slotWindowMenuAboutToShow ()
void toggleFullscreen ()
Protected Member Functions
void createCentralWidget ()
void createMenuAndToolBar ()
bool event (QEvent *event) override
void initActions ()
void initBackends ()
void initConnections ()
void initMenubar ()
void initSwordConfigFile ()
void initToolbars ()
void initView ()
void refreshDisplayWindows () const
void retranslateUi ()
Static Protected Member Functions
static void retranslateUiActions (BtActionCollection *ac)
Private Member Functions
void deleteDebugWindow ()
void setAutoScrollTimerInterval ()
void showOrHideToolBars ()
void slotDebugTimeout ()
void slotDebugWindowClosing ()
void slotShowDebugWindow (bool)
Private Attributes
QAction * m_aboutBibleTimeAction
BtActionCollection * m_actionCollection
struct {
bool enabled
bool paused
int speed
} m_autoScroll
QAction * m_autoScrollDownAction
QAction * m_autoScrollPauseAction
QTimer m_autoScrollTimer
QAction * m_autoScrollUpAction
QAction * m_bibleStudyHowtoAction
QDockWidget * m_bookmarksDock
CBookmarkIndex * m_bookmarksPage
BtBookshelfDockWidget * m_bookshelfDock
QAction * m_bookshelfManagerAction
QAction * m_bookshelfWizardAction
QAction * m_debugWidgetAction
QMenu * m_fileMenu
BtFindWidget * m_findWidget
QMenu * m_helpMenu
InfoDisplay::CInfoDisplay * m_infoDisplay
QDockWidget * m_magDock
QToolBar * m_mainToolBar
CMDIArea * m_mdi
QToolBar * m_navToolBar
QAction * m_openHandbookAction
QMenu * m_openWindowsMenu
BtOpenWorkAction * m_openWorkAction
QAction * m_quitAction
QMenu * m_scrollMenu
QPointer< Search::CSearchDialog > m_searchDialog
QMenu * m_searchMenu
QAction * m_searchOpenWorksAction
QAction * m_searchStandardBibleAction
QAction * m_setPreferencesAction
QMenu * m_settingsMenu
QAction * m_showBookmarksAction
QAction * m_showBookshelfAction
QAction * m_showMagAction
QAction * m_showMainWindowToolbarAction
QAction * m_showTextAreaHeadersAction
QAction * m_showTextWindowModuleChooserAction
QAction * m_showTextWindowNavigationAction
QAction * m_showTextWindowToolButtonsAction
QAction * m_tipOfTheDayAction
QAction * m_toolbarsInEachWindow
QMenu * m_toolBarsMenu
QToolBar * m_toolsToolBar
QMenu * m_viewMenu
QActionGroup * m_windowArrangementActionGroup
QMenu * m_windowArrangementMenu
QAction * m_windowAutoCascadeAction
QAction * m_windowAutoTabbedAction
QAction * m_windowAutoTileAction
QAction * m_windowAutoTileHorizontalAction
QAction * m_windowAutoTileVerticalAction
QAction * m_windowCascadeAction
QAction * m_windowCloseAction
QAction * m_windowCloseAllAction
QMenu * m_windowDeleteProfileMenu
QAction * m_windowFullscreenAction
QActionGroup * m_windowLoadProfileActionGroup
QMenu * m_windowLoadProfileMenu
QAction * m_windowManualModeAction
QMenu * m_windowMenu
QAction * m_windowSaveToNewProfileAction
QAction * m_windowTileAction
QAction * m_windowTileHorizontalAction
QAction * m_windowTileVerticalAction
BtModuleChooserBar * m_worksToolBar
Static Private Attributes
static QLabel * m_debugWindow = nullptr
static std::mutex m_debugWindowLock
static BibleTime * m_instance = nullptr
Friends
class CDisplayWindow
Detailed Description
BibleTime's main class. The main class of BibleTime. Here are the main widgets created.
This is the main class of BibleTime! This class creates the GUI, the QAction objects and connects to some slots. Please insert the creation of actions in initActions, the creation of widgets into initView and the connect(...) calls into initConnections. Reading from a config file on creation time should go into readSettings(), saving into saveSettings(). This is the general way of all BibleTime classes.
Definition at line 132 of file bibletime.h.
Constructor & Destructor Documentation
BibleTime()
BibleTime::BibleTime (QWidget * parent = nullptr, Qt::WindowFlags flags = Qt::WindowFlags())
Definition at line 78 of file bibletime.cpp.
References BT_ASSERT, btConfig(), util::directory::getPicsDir(), initActions(), initBackends(), initConnections(), initMenubar(), initToolbars(), initView(), m_autoScroll, m_instance, and retranslateUi().
~BibleTime()
BibleTime::~BibleTime () override
Definition at line 143 of file bibletime.cpp.
References deleteDebugWindow(), m_bookshelfDock, BtBookshelfDockWidget::saveBookshelfState(), and saveProfile().
Member Function Documentation
autoScrollAnyKey
bool BibleTime::autoScrollAnyKey (int key) protected slot
Definition at line 564 of file bibletime_slots.cpp.
References autoScrollStop(), and m_autoScroll.
Referenced by event().
autoScrollDown
void BibleTime::autoScrollDown () protected slot
Definition at line 538 of file bibletime_slots.cpp.
References m_autoScroll, m_autoScrollTimer, setAutoScrollTimerInterval(), and setDisplayFocus().
Referenced by initActions().
autoScrollPause
void BibleTime::autoScrollPause () protected slot
Definition at line 555 of file bibletime_slots.cpp.
References m_autoScroll, m_autoScrollTimer, and setDisplayFocus().
Referenced by initActions().
autoScrollStop
void BibleTime::autoScrollStop () slot
Definition at line 571 of file bibletime_slots.cpp.
References m_autoScroll, and m_autoScrollTimer.
Referenced by autoScrollAnyKey(), CDisplayWindow::lookupSwordKey(), slotActiveWindowChanged(), BtQmlScrollView::slotSliderMoved(), and BtQuickWidget::wheelEvent().
autoScrollUp
void BibleTime::autoScrollUp () protected slot
Definition at line 521 of file bibletime_slots.cpp.
References m_autoScroll, m_autoScrollTimer, setAutoScrollTimerInterval(), and setDisplayFocus().
Referenced by initActions().
clearMdiToolBars()
void BibleTime::clearMdiToolBars ()
Clears the actions of the MDI related toolbars
Definition at line 324 of file bibletime_init.cpp.
Referenced by CDisplayWindow::init().
colorThemeChanged
void BibleTime::colorThemeChanged () signal
Referenced by event(), processCommandline(), and CDisplayWindow::setDisplayWidget().
createCentralWidget()
void BibleTime::createCentralWidget () protected
Creates mdi and and BtFindWidget
Definition at line 363 of file bibletime_init.cpp.
References BT_CONNECT, BtFindWidget::findNext(), CMDIArea::findNextTextInActiveWindow(), BtFindWidget::findPrevious(), CMDIArea::findPreviousTextInActiveWindow(), BtFindWidget::highlightText(), CMDIArea::highlightTextInActiveWindow(), and slotActiveWindowChanged().
createMenuAndToolBar()
void BibleTime::createMenuAndToolBar () protected
Create the main window menu and toolbar
Definition at line 338 of file bibletime_init.cpp.
References btConfig(), createToolBar(), BtConfig::session(), and BtConfigCore::value().
createReadDisplayWindow [1/2]
CDisplayWindow * BibleTime::createReadDisplayWindow (CSwordModuleInfo * module, const QString & key = QString()) protected slot
Creates a new presenter in the MDI area according to the type of the module.
Definition at line 198 of file bibletime.cpp.
References createReadDisplayWindow().
createReadDisplayWindow [2/2]
CDisplayWindow * BibleTime::createReadDisplayWindow (QList< CSwordModuleInfo * > modules, const QString & key) protected slot
Creates a new presenter in the MDI area according to the type of the module.
Definition at line 176 of file bibletime.cpp.
References CMDIArea::addSubWindow(), anonymous_namespace{bibletime.cpp}::createReadInstance(), CDisplayWindow::init(), CDisplayWindow::lookupKey(), and m_mdi.
Referenced by createReadDisplayWindow(), initConnections(), CDisplayWindow::lookupKey(), processCommandline(), and reloadProfile().
deleteDebugWindow()
void BibleTime::deleteDebugWindow () private
Definition at line 924 of file bibletime_init.cpp.
References slotDebugWindowClosing().
Referenced by ~BibleTime().
deleteProfile
void BibleTime::deleteProfile (QAction * action) protected slot
Deletes the chosen session from the menu and from disk.
Todo:
Ask for confirmation
Definition at line 505 of file bibletime_slots.cpp.
References BT_ASSERT, btConfig(), BtConfig::deleteSession(), and refreshProfileMenus().
Referenced by initMenubar().
event()
bool BibleTime::event (QEvent * event) override protected
Catch QMainWindow events
Definition at line 306 of file bibletime.cpp.
References autoScrollAnyKey(), and colorThemeChanged().
getCurrentDisplay()
BtModelViewReadDisplay * BibleTime::getCurrentDisplay ()
Get a pointer to the display associated with the current window
Definition at line 334 of file bibletime.cpp.
References CDisplayWindow::displayWidget(), and m_mdi.
Referenced by setDisplayFocus(), and slotAutoScroll().
getCurrentModule()
const CSwordModuleInfo * BibleTime::getCurrentModule ()
Get a pointer to the module associated with the current window
Definition at line 324 of file bibletime.cpp.
References m_mdi, and CDisplayWindow::modules().
Referenced by InfoDisplay::CInfoDisplay::setInfo().
infoDisplay()
InfoDisplay::CInfoDisplay* BibleTime::infoDisplay () const inline
Returns
a pointer to the info display.
Definition at line 164 of file bibletime.h.
References m_infoDisplay.
Referenced by BtQmlInterface::BtQmlInterface().
initActions()
void BibleTime::initActions () protected
Initializes the action objects of the GUI
Definition at line 393 of file bibletime_init.cpp.
References autoCascade, autoScrollDown(), autoScrollPause(), autoScrollUp(), autoTabbed, autoTile, autoTileHorizontal, autoTileVertical, BT_CONNECT, btConfig(), BtConfigCore::group(), manual, openOnlineHelp_Handbook(), openOnlineHelp_Howto(), saveToNewProfile(), BtConfig::session(), slotBookshelfWizard(), slotCascade(), slotOpenAboutDialog(), slotOpenTipDialog(), slotSearchDefaultBible(), slotSearchModules(), slotSettingsOptions(), slotShowDebugWindow(), slotTile(), slotTileHorizontal(), slotTileVertical(), slotToggleMainToolbar(), slotToggleNavigatorToolbar(), slotToggleTextWindowHeader(), slotToggleToolBarsInEachWindow(), slotToggleToolsToolbar(), slotToggleWorksToolbar(), toggleFullscreen(), and BtOpenWorkAction::triggered().
Referenced by BibleTime().
initBackends()
void BibleTime::initBackends () protected
Initializes the backend
Todo:
refactor this hack
Definition at line 860 of file bibletime_init.cpp.
References BtInstallBackend::backend(), btApp, btConfig(), CSwordBackend::createInstance(), CSwordBackend::initModules(), CSwordBackend::instance(), CSwordBackend::OtherChange, and CDisplaySettingsPage::resetLanguage().
Referenced by BibleTime().
initConnections()
void BibleTime::initConnections () protected
Initializes the SIGNAL / SLOT connections
Definition at line 796 of file bibletime_init.cpp.
References BT_CONNECT, CBookmarkIndex::createReadDisplayWindow(), createReadDisplayWindow(), BtBookshelfDockWidget::installWorksClicked(), moduleAbout(), BtBookshelfDockWidget::moduleAboutTriggered(), BtBookshelfDockWidget::moduleOpenTriggered(), BtBookshelfDockWidget::moduleSearchTriggered(), BtBookshelfDockWidget::moduleUnlockTriggered(), slotBookshelfWizard(), and slotModuleUnlock().
Referenced by BibleTime().
initMenubar()
void BibleTime::initMenubar () protected
Initializes the menubar of BibleTime.
Definition at line 612 of file bibletime_init.cpp.
References BT_CONNECT, deleteProfile(), loadProfile(), slotOpenWindowsMenuAboutToShow(), slotUpdateWindowArrangementActions(), and slotWindowMenuAboutToShow().
Referenced by BibleTime().
initSwordConfigFile()
void BibleTime::initSwordConfigFile () protected
Initializes the sword.conf in the $HOME\Sword directory
Definition at line 818 of file bibletime_init.cpp.
References util::directory::convertDirSeparators(), util::directory::getUserHomeSwordDir(), and Rendering::Text.
initToolbars()
void BibleTime::initToolbars () protected
Initializes the toolbars.
Definition at line 727 of file bibletime_init.cpp.
Referenced by BibleTime().
initView()
void BibleTime::initView () protected
Initializes the view of this widget
Definition at line 63 of file bibletime_init.cpp.
References BT_CONNECT, CBookmarkIndex::magInfoProvided(), BtBookshelfDockWidget::moduleHovered(), InfoDisplay::CInfoDisplay::setInfo(), and slotAutoScroll().
Referenced by BibleTime().
insertKeyboardActions
void BibleTime::insertKeyboardActions (BtActionCollection *const a) static slot
Creates QAction's that have keyboard shortcuts
Definition at line 105 of file bibletime_init.cpp.
References CResMgr::mainMenu::mainIndex::search::accel, CResMgr::mainMenu::mainIndex::searchdefaultbible::accel, CResMgr::mainMenu::window::saveToNewProfile::accel, CResMgr::mainMenu::window::showFullscreen::accel, CResMgr::mainMenu::window::arrangementMode::manual::accel, CResMgr::mainMenu::window::arrangementMode::autoTileHorizontal::accel, CResMgr::mainMenu::window::arrangementMode::autoTileVertical::accel, CResMgr::mainMenu::window::arrangementMode::autoTile::accel, CResMgr::mainMenu::window::arrangementMode::autoTabbed::accel, CResMgr::mainMenu::window::arrangementMode::autoCascade::accel, CResMgr::mainMenu::window::tileHorizontal::accel, CResMgr::mainMenu::window::tileVertical::accel, CResMgr::mainMenu::window::tile::accel, CResMgr::mainMenu::window::cascade::accel, CResMgr::mainMenu::window::close::accel, CResMgr::mainMenu::window::closeAll::accel, CResMgr::mainMenu::settings::swordSetupDialog::accel, CResMgr::mainMenu::help::handbook::accel, CResMgr::mainMenu::help::bibleStudyHowTo::accel, CResMgr::mainMenu::help::tipOfTheDay::accel, and BtActionCollection::addAction().
instance()
static BibleTime* BibleTime::instance () inline static
Definition at line 142 of file bibletime.h.
References m_instance.
Referenced by BtQmlInterface::BtQmlInterface(), CDisplayWindow::initActions(), CDisplayWindow::lookupSwordKey(), BtQmlScrollView::slotSliderMoved(), and BtQuickWidget::wheelEvent().
keyChooser()
CKeyChooser * BibleTime::keyChooser () const
Returns the main window CKeyChooser
Definition at line 331 of file bibletime_init.cpp.
References BT_ASSERT.
loadProfile [1/2]
void BibleTime::loadProfile (const QString & profileKey) protected slot
Loads the profile with the given key
Definition at line 380 of file bibletime_slots.cpp.
References BT_ASSERT, btConfig(), m_mdi, refreshProfileMenus(), reloadProfile(), and saveProfile().
loadProfile [2/2]
void BibleTime::loadProfile (QAction * action) protected slot
Loads the profile with the menu id ID
Definition at line 372 of file bibletime_slots.cpp.
References BT_ASSERT, and btConfig().
Referenced by initMenubar().
moduleAbout
void BibleTime::moduleAbout (CSwordModuleInfo * module) protected slot
Definition at line 247 of file bibletime.cpp.
Referenced by initConnections().
moduleUnlock()
bool BibleTime::moduleUnlock (CSwordModuleInfo * module, QWidget * parent = nullptr) static
Displays a dialog which asks the user an unlock key for the given module and tries to unlock the module. If an invalid unlock key is given, a warning message is issued and the user is again asked for the key.
Parameters
[in] module The module to unlock.
[in] parent The parent widget for the unlock dialogs.
Returns
whether the module was successfully unlocked.
Todo:
Write a proper unlocking dialog with integrated error messages.
Todo:
refactor this module reload
Definition at line 202 of file bibletime.cpp.
References BtInstallBackend::backend(), BT_ASSERT, CSwordModuleInfo::CipherKey, CSwordModuleInfo::config(), CSwordModuleInfo::getUnlockInfo(), BtMessageInputDialog::getUserInput(), CSwordBackend::instance(), CSwordModuleInfo::isLocked(), CSwordModuleInfo::name(), CSwordBackend::OtherChange, BtMessageInputDialog::Password, message::showWarning(), and CSwordModuleInfo::unlock().
Referenced by slotModuleUnlock().
navToolBar()
QToolBar* BibleTime::navToolBar () const inline
Get pointer to Navigation toolbar
Definition at line 151 of file bibletime.h.
References m_navToolBar.
Referenced by CDisplayWindow::clearMainWindowToolBars(), CBookReadWindow::setupMainWindowToolBars(), and CDisplayWindow::setupMainWindowToolBars().
openFindWidget()
void BibleTime::openFindWidget ()
Open the BtFindWidget below the mdi area
Definition at line 357 of file bibletime.cpp.
References m_findWidget, and BtFindWidget::showAndSelect().
Referenced by BtModelViewReadDisplay::openFindTextDialog().
openOnlineHelp_Handbook
void BibleTime::openOnlineHelp_Handbook () slot
Opens the handbook.
Definition at line 307 of file bibletime_slots.cpp.
References util::directory::getHandbook(), and message::showCritical().
Referenced by initActions().
openOnlineHelp_Howto
void BibleTime::openOnlineHelp_Howto () slot
Opens the bible study howto.
Definition at line 323 of file bibletime_slots.cpp.
References util::directory::getHowto(), and message::showCritical().
Referenced by initActions().
openSearchDialog()
void BibleTime::openSearchDialog (BtConstModuleList modules, QString const & searchText = QString())
Definition at line 349 of file bibletime.cpp.
References m_searchDialog.
Referenced by CDisplayWindow::initActions(), slotSearchDefaultBible(), and slotSearchModules().
processCommandline
void BibleTime::processCommandline (bool ignoreSession, const QString & bibleKey) slot
Processes the command-line options given to BibleTime.
Parameters
[in] ignoreSession Specifies whether –ignore-session was used.
[in] bibleKey If –open-default-bible was used, the bible key specified, or null otherwise.
Definition at line 262 of file bibletime.cpp.
References btConfig(), colorThemeChanged(), createReadDisplayWindow(), BtConfig::getDefaultSwordModuleByType(), CSwordVerseKey::index(), CSwordVerseKey::key(), m_mdi, CMDIArea::myTileVertical(), CSwordVerseKey::positionToTop(), anonymous_namespace{bibletime.cpp}::randInt(), reloadProfile(), CSwordVerseKey::setIndex(), BtConfigCore::setValue(), and BtConfigCore::sync().
Referenced by main().
refreshDisplayWindows()
void BibleTime::refreshDisplayWindows () const protected
Refreshes all presenter supporting at least in of the features given as parameter.
Refreshes all presenters.
Definition at line 255 of file bibletime.cpp.
References m_mdi, and CSwordBackend::OtherChange.
Referenced by slotSettingsOptions().
refreshProfileMenus
void BibleTime::refreshProfileMenus () protected slot
Slot to refresh the save profile and load profile menus.
Slot to refresh the saved profile and load profile menus.
Definition at line 628 of file bibletime_slots.cpp.
References btConfig(), BtConfig::currentSessionKey(), m_windowDeleteProfileMenu, m_windowLoadProfileActionGroup, m_windowLoadProfileMenu, and BtConfig::sessionNames().
Referenced by deleteProfile(), loadProfile(), saveToNewProfile(), and slotSettingsOptions().
reloadProfile
void BibleTime::reloadProfile () protected slot
Reloads the current profile
Bug:
The main window (except decors) is all black without this (not even hover over toolbar buttons work)
Bug:
The main window would not refresh at all. A call to this function or adjustSize() seems to fix this
Todo:
For windows in failedWindows ask whether to keep the settings / close windows etc
Definition at line 400 of file bibletime_slots.cpp.
References CMDIArea::ArrangementModeTile, BT_ASSERT, btConfig(), createReadDisplayWindow(), CSwordBackend::findModuleByName(), BtConfigCore::group(), CSwordBackend::instance(), m_findWidget, m_mdi, m_showMainWindowToolbarAction, m_showTextAreaHeadersAction, m_showTextWindowModuleChooserAction, m_showTextWindowNavigationAction, m_showTextWindowToolButtonsAction, m_toolbarsInEachWindow, m_windowFullscreenAction, BtConfig::session(), CMDIArea::setMDIArrangementMode(), message::setQActionCheckedNoTrigger(), showOrHideToolBars(), and CMDIArea::triggerWindowUpdate().
Referenced by loadProfile(), and processCommandline().
retranslateUi()
void BibleTime::retranslateUi () protected
Retranslates the UI.
Definition at line 741 of file bibletime_init.cpp.
Referenced by BibleTime().
retranslateUiActions()
void BibleTime::retranslateUiActions (BtActionCollection * ac) static protected
Retranslates the UI actions.
retranslation for actions used in this class This is called for two different collections of actions One set is for the actual use in the menus, etc The second is used during the use of the configuration shortcut editor
Definition at line 780 of file bibletime_init.cpp.
References BtActionCollection::action().
saveConfigSettings()
void BibleTime::saveConfigSettings ()
Save the configuration dialog settings, don't open dialog
Save the settings, used when no settings have been saved before
Definition at line 74 of file bibletime_slots.cpp.
References BtConfigDialog::save().
Referenced by main().
saveProfile
void BibleTime::saveProfile () protected slot
Saves the current settings into the currently activated profile.
Definition at line 349 of file bibletime_slots.cpp.
References btConfig(), CMDIArea::getMDIArrangementMode(), m_findWidget, m_mdi, BtConfig::session(), BtConfigCore::setValue(), and CDisplayWindow::storeProfileSettings().
Referenced by loadProfile(), saveToNewProfile(), and ~BibleTime().
saveToNewProfile
void BibleTime::saveToNewProfile () protected slot
Saves current settings into a new profile.
Definition at line 589 of file bibletime_slots.cpp.
References BtConfig::addSession(), btConfig(), refreshProfileMenus(), saveProfile(), BtConfig::sessionNames(), BtConfig::setCurrentSession(), and message::showInformation().
Referenced by initActions().
setAutoScrollTimerInterval()
void BibleTime::setAutoScrollTimerInterval () private
Definition at line 363 of file bibletime.cpp.
References anonymous_namespace{bibletime.cpp}::autoScrollTimeInterval, m_autoScroll, and m_autoScrollTimer.
Referenced by autoScrollDown(), and autoScrollUp().
setDisplayFocus()
void BibleTime::setDisplayFocus ()
Set the focus on the display widget
Definition at line 344 of file bibletime.cpp.
References getCurrentDisplay().
Referenced by autoScrollDown(), autoScrollPause(), and autoScrollUp().
showOrHideToolBars()
void BibleTime::showOrHideToolBars () private
Set the visibility of all tool bars according to the configuration taking the toolbarsInEachWindow setting into account.
Definition at line 244 of file bibletime_slots.cpp.
References btConfig(), BtConfigCore::group(), m_navToolBar, m_toolsToolBar, m_worksToolBar, BtConfig::session(), toggledTextWindowModuleChooser(), toggledTextWindowNavigator(), and toggledTextWindowToolButtons().
Referenced by reloadProfile(), and slotToggleToolBarsInEachWindow().
slotActiveWindowChanged
void BibleTime::slotActiveWindowChanged (QMdiSubWindow * window) protected slot
The active window was changed
Definition at line 288 of file bibletime_slots.cpp.
References autoScrollStop(), and m_findWidget.
Referenced by createCentralWidget().
slotAutoScroll
void BibleTime::slotAutoScroll () protected slot
Automatically scroll the display
Definition at line 576 of file bibletime_slots.cpp.
References getCurrentDisplay(), m_autoScroll, and m_autoScrollTimer.
Referenced by initView().
slotBookshelfWizard
void BibleTime::slotBookshelfWizard () slot
Opens the bookshelf wizard.
Definition at line 78 of file bibletime_slots.cpp.
Referenced by initActions(), initConnections(), and main().
slotCascade
void BibleTime::slotCascade () protected slot
Definition at line 169 of file bibletime_slots.cpp.
References m_windowCascadeAction, and slotUpdateWindowArrangementActions().
Referenced by initActions().
slotDebugTimeout()
void BibleTime::slotDebugTimeout () private
Definition at line 940 of file bibletime_init.cpp.
Referenced by slotShowDebugWindow().
slotDebugWindowClosing()
void BibleTime::slotDebugWindowClosing () private
Definition at line 934 of file bibletime_init.cpp.
Referenced by deleteDebugWindow(), and slotShowDebugWindow().
slotModuleUnlock
void BibleTime::slotModuleUnlock (CSwordModuleInfo * module) protected slot
Definition at line 243 of file bibletime.cpp.
References moduleUnlock().
Referenced by initConnections().
slotOpenAboutDialog
void BibleTime::slotOpenAboutDialog () protected slot
Open the About Dialog
Definition at line 339 of file bibletime_slots.cpp.
Referenced by initActions().
slotOpenTipDialog
void BibleTime::slotOpenTipDialog () slot
Open the Tip Dialog
Definition at line 344 of file bibletime_slots.cpp.
Referenced by initActions(), and main().
slotOpenWindowsMenuAboutToShow
void BibleTime::slotOpenWindowsMenuAboutToShow () protected slot
Is called when the open windows menu is about to show ;-)
Is called just before the open windows menu is shown.
Definition at line 98 of file bibletime_slots.cpp.
References BT_ASSERT, BT_CONNECT, m_mdi, m_openWindowsMenu, slotSetActiveSubWindow(), and CMDIArea::usableWindowList().
Referenced by initMenubar().
slotSearchDefaultBible
void BibleTime::slotSearchDefaultBible () protected slot
Called for search default bible
Definition at line 298 of file bibletime_slots.cpp.
References btConfig(), BtConfig::getDefaultSwordModuleByType(), and openSearchDialog().
Referenced by initActions().
slotSearchModules
void BibleTime::slotSearchModules () protected slot
Called when search button is pressed
Definition at line 275 of file bibletime_slots.cpp.
References m_mdi, CDisplayWindow::modules(), and openSearchDialog().
Referenced by initActions().
slotSetActiveSubWindow
void BibleTime::slotSetActiveSubWindow (QWidget * window) protected slot
Used to set the active menu
Sets the active window.
Definition at line 269 of file bibletime_slots.cpp.
References m_mdi.
Referenced by slotOpenWindowsMenuAboutToShow().
slotSettingsOptions
void BibleTime::slotSettingsOptions () slot
Opens the optionsdialog of BibleTime.
Todo:
update the bookmarks after Bible bookname language has been changed.
Definition at line 48 of file bibletime_slots.cpp.
References BT_CONNECT, btConfig(), CSwordBackend::instance(), m_actionCollection, m_infoDisplay, BtActionCollection::readShortcuts(), refreshDisplayWindows(), refreshProfileMenus(), CSwordBackend::setBooknameLanguage(), BtConfigDialog::signalSettingsChanged(), and InfoDisplay::CInfoDisplay::updateColors().
Referenced by initActions().
slotShowDebugWindow()
void BibleTime::slotShowDebugWindow (bool show) private
Definition at line 904 of file bibletime_init.cpp.
References BT_CONNECT, slotDebugTimeout(), and slotDebugWindowClosing().
Referenced by initActions().
slotTile
void BibleTime::slotTile () protected slot
Definition at line 165 of file bibletime_slots.cpp.
References m_windowTileAction, and slotUpdateWindowArrangementActions().
Referenced by initActions().
slotTileHorizontal
void BibleTime::slotTileHorizontal () protected slot
Definition at line 177 of file bibletime_slots.cpp.
References m_windowTileHorizontalAction, and slotUpdateWindowArrangementActions().
Referenced by initActions().
slotTileVertical
void BibleTime::slotTileVertical () protected slot
Definition at line 173 of file bibletime_slots.cpp.
References m_windowTileVerticalAction, and slotUpdateWindowArrangementActions().
Referenced by initActions().
slotToggleMainToolbar
void BibleTime::slotToggleMainToolbar () protected slot
Shows/hides the main toolbar
Shows/hides the toolbar
Definition at line 182 of file bibletime_slots.cpp.
References BT_ASSERT, btConfig(), BtConfigCore::group(), m_mainToolBar, m_showMainWindowToolbarAction, BtConfig::session(), and BtConfigCore::value().
Referenced by initActions().
slotToggleNavigatorToolbar
void BibleTime::slotToggleNavigatorToolbar () protected slot
Definition at line 203 of file bibletime_slots.cpp.
References btConfig(), BtConfigCore::group(), m_navToolBar, BtConfig::session(), toggledTextWindowNavigator(), and BtConfigCore::value().
Referenced by initActions().
slotToggleTextWindowHeader
void BibleTime::slotToggleTextWindowHeader () protected slot
Shows/hides the text window text area headers and sets configuration that newly opened windows don't user headers.
Definition at line 195 of file bibletime_slots.cpp.
References btConfig(), BtConfigCore::group(), BtConfig::session(), toggledTextWindowHeader(), and BtConfigCore::value().
Referenced by initActions().
slotToggleToolBarsInEachWindow
void BibleTime::slotToggleToolBarsInEachWindow () protected slot
Definition at line 236 of file bibletime_slots.cpp.
References btConfig(), BtConfigCore::group(), BtConfig::session(), showOrHideToolBars(), and BtConfigCore::value().
Referenced by initActions().
slotToggleToolsToolbar
void BibleTime::slotToggleToolsToolbar () protected slot
Definition at line 214 of file bibletime_slots.cpp.
References btConfig(), BtConfigCore::group(), m_toolsToolBar, BtConfig::session(), toggledTextWindowToolButtons(), and BtConfigCore::value().
Referenced by initActions().
slotToggleWorksToolbar
void BibleTime::slotToggleWorksToolbar () protected slot
Definition at line 225 of file bibletime_slots.cpp.
References btConfig(), BtConfigCore::group(), m_worksToolBar, BtConfig::session(), toggledTextWindowModuleChooser(), and BtConfigCore::value().
Referenced by initActions().
slotUpdateWindowArrangementActions
void BibleTime::slotUpdateWindowArrangementActions (QAction * trigerredAction) protected slot
This slot is connected with the windowAutoTileAction object
Definition at line 112 of file bibletime_slots.cpp.
References CMDIArea::ArrangementModeCascade, CMDIArea::ArrangementModeManual, CMDIArea::ArrangementModeTabbed, CMDIArea::ArrangementModeTile, CMDIArea::ArrangementModeTileHorizontal, CMDIArea::ArrangementModeTileVertical, autoCascade, autoTabbed, autoTile, autoTileHorizontal, autoTileVertical, BT_ASSERT, btConfig(), CMDIArea::enableWindowMinMaxFlags(), BtConfigCore::group(), m_mdi, m_windowAutoCascadeAction, m_windowAutoTabbedAction, m_windowAutoTileAction, m_windowAutoTileHorizontalAction, m_windowAutoTileVerticalAction, m_windowCascadeAction, m_windowManualModeAction, m_windowTileAction, m_windowTileHorizontalAction, m_windowTileVerticalAction, manual, CMDIArea::myCascade(), CMDIArea::myTile(), CMDIArea::myTileHorizontal(), CMDIArea::myTileVertical(), BtConfig::session(), and CMDIArea::setMDIArrangementMode().
Referenced by initMenubar(), slotCascade(), slotTile(), slotTileHorizontal(), and slotTileVertical().
slotWindowMenuAboutToShow
void BibleTime::slotWindowMenuAboutToShow () protected slot
Is called when the window menu is about to show ;-)
Is called just before the window menu is shown.
Definition at line 82 of file bibletime_slots.cpp.
References BT_ASSERT, m_mdi, m_openWindowsMenu, m_windowCascadeAction, m_windowCloseAction, m_windowCloseAllAction, m_windowMenu, m_windowTileAction, m_windowTileHorizontalAction, and m_windowTileVerticalAction.
Referenced by initMenubar().
toggledTextWindowHeader
void BibleTime::toggledTextWindowHeader (bool newState) signal
Referenced by anonymous_namespace{cdisplaywindow.cpp}::getProfileWindow(), and slotToggleTextWindowHeader().
toggledTextWindowModuleChooser
void BibleTime::toggledTextWindowModuleChooser (bool newState) signal
Referenced by anonymous_namespace{cdisplaywindow.cpp}::getProfileWindow(), showOrHideToolBars(), and slotToggleWorksToolbar().
toggledTextWindowNavigator
void BibleTime::toggledTextWindowNavigator (bool newState) signal
Referenced by anonymous_namespace{cdisplaywindow.cpp}::getProfileWindow(), showOrHideToolBars(), and slotToggleNavigatorToolbar().
toggledTextWindowToolButtons
void BibleTime::toggledTextWindowToolButtons (bool newState) signal
Referenced by anonymous_namespace{cdisplaywindow.cpp}::getProfileWindow(), showOrHideToolBars(), and slotToggleToolsToolbar().
toggleFullscreen
void BibleTime::toggleFullscreen () protected slot
Toggles between normal and fullscreen mode.
Definition at line 516 of file bibletime_slots.cpp.
References m_mdi, and CMDIArea::triggerWindowUpdate().
Referenced by initActions().
toolsToolBar()
QToolBar* BibleTime::toolsToolBar () const inline
Get pointer to Tools toolbar
Definition at line 159 of file bibletime.h.
References m_toolsToolBar.
Referenced by CDisplayWindow::clearMainWindowToolBars(), CBookReadWindow::setupMainWindowToolBars(), CCommentaryReadWindow::setupMainWindowToolBars(), and CDisplayWindow::setupMainWindowToolBars().
worksToolBar()
BtModuleChooserBar* BibleTime::worksToolBar () const inline
Get pointer to Works toolbar
Definition at line 155 of file bibletime.h.
References m_worksToolBar.
Referenced by CBookReadWindow::setupMainWindowToolBars(), and CDisplayWindow::setupMainWindowToolBars().
Friends And Related Function Documentation
CDisplayWindow
friend class CDisplayWindow friend
Definition at line 133 of file bibletime.h.
Member Data Documentation
enabled
bool BibleTime::enabled
Definition at line 496 of file bibletime.h.
m_aboutBibleTimeAction
QAction* BibleTime::m_aboutBibleTimeAction private
Definition at line 481 of file bibletime.h.
m_actionCollection
BtActionCollection* BibleTime::m_actionCollection private
Definition at line 484 of file bibletime.h.
Referenced by slotSettingsOptions().
m_autoScroll
struct { ... } BibleTime::m_autoScroll
Referenced by autoScrollAnyKey(), autoScrollDown(), autoScrollPause(), autoScrollStop(), autoScrollUp(), BibleTime(), setAutoScrollTimerInterval(), and slotAutoScroll().
m_autoScrollDownAction
QAction* BibleTime::m_autoScrollDownAction private
Definition at line 487 of file bibletime.h.
m_autoScrollPauseAction
QAction* BibleTime::m_autoScrollPauseAction private
Definition at line 488 of file bibletime.h.
m_autoScrollTimer
QTimer BibleTime::m_autoScrollTimer private
Definition at line 500 of file bibletime.h.
Referenced by autoScrollDown(), autoScrollPause(), autoScrollStop(), autoScrollUp(), setAutoScrollTimerInterval(), and slotAutoScroll().
m_autoScrollUpAction
QAction* BibleTime::m_autoScrollUpAction private
Definition at line 486 of file bibletime.h.
m_bibleStudyHowtoAction
QAction* BibleTime::m_bibleStudyHowtoAction private
Definition at line 480 of file bibletime.h.
m_bookmarksDock
QDockWidget* BibleTime::m_bookmarksDock private
Definition at line 415 of file bibletime.h.
m_bookmarksPage
CBookmarkIndex* BibleTime::m_bookmarksPage private
Definition at line 416 of file bibletime.h.
m_bookshelfDock
BtBookshelfDockWidget* BibleTime::m_bookshelfDock private
Definition at line 414 of file bibletime.h.
Referenced by ~BibleTime().
m_bookshelfManagerAction
QAction* BibleTime::m_bookshelfManagerAction private
Definition at line 474 of file bibletime.h.
m_bookshelfWizardAction
QAction* BibleTime::m_bookshelfWizardAction private
Definition at line 475 of file bibletime.h.
m_debugWidgetAction
QAction* BibleTime::m_debugWidgetAction private
Definition at line 519 of file bibletime.h.
m_debugWindow
QLabel * BibleTime::m_debugWindow = nullptr static private
Definition at line 520 of file bibletime.h.
m_debugWindowLock
std::mutex BibleTime::m_debugWindowLock static private
Definition at line 521 of file bibletime.h.
m_fileMenu
QMenu* BibleTime::m_fileMenu private
Definition at line 426 of file bibletime.h.
m_findWidget
BtFindWidget* BibleTime::m_findWidget private
Definition at line 493 of file bibletime.h.
Referenced by openFindWidget(), reloadProfile(), saveProfile(), and slotActiveWindowChanged().
m_helpMenu
QMenu* BibleTime::m_helpMenu private
Definition at line 478 of file bibletime.h.
m_infoDisplay
InfoDisplay::CInfoDisplay* BibleTime::m_infoDisplay private
Definition at line 418 of file bibletime.h.
Referenced by infoDisplay(), and slotSettingsOptions().
m_instance
BibleTime * BibleTime::m_instance = nullptr static private
Definition at line 411 of file bibletime.h.
Referenced by BibleTime(), and instance().
m_magDock
QDockWidget* BibleTime::m_magDock private
Definition at line 417 of file bibletime.h.
m_mainToolBar
QToolBar* BibleTime::m_mainToolBar private
Definition at line 420 of file bibletime.h.
Referenced by slotToggleMainToolbar().
m_mdi
CMDIArea* BibleTime::m_mdi private
Definition at line 492 of file bibletime.h.
Referenced by createReadDisplayWindow(), getCurrentDisplay(), getCurrentModule(), loadProfile(), processCommandline(), refreshDisplayWindows(), reloadProfile(), saveProfile(), slotOpenWindowsMenuAboutToShow(), slotSearchModules(), slotSetActiveSubWindow(), slotUpdateWindowArrangementActions(), slotWindowMenuAboutToShow(), and toggleFullscreen().
m_navToolBar
QToolBar* BibleTime::m_navToolBar private
Definition at line 421 of file bibletime.h.
Referenced by navToolBar(), showOrHideToolBars(), and slotToggleNavigatorToolbar().
m_openHandbookAction
QAction* BibleTime::m_openHandbookAction private
Definition at line 479 of file bibletime.h.
m_openWindowsMenu
QMenu* BibleTime::m_openWindowsMenu private
Definition at line 451 of file bibletime.h.
Referenced by slotOpenWindowsMenuAboutToShow(), and slotWindowMenuAboutToShow().
m_openWorkAction
BtOpenWorkAction* BibleTime::m_openWorkAction private
Definition at line 427 of file bibletime.h.
m_quitAction
QAction* BibleTime::m_quitAction private
Definition at line 428 of file bibletime.h.
m_scrollMenu
QMenu* BibleTime::m_scrollMenu private
Definition at line 436 of file bibletime.h.
m_searchDialog
QPointer<Search::CSearchDialog> BibleTime::m_searchDialog private
Definition at line 501 of file bibletime.h.
Referenced by openSearchDialog().
m_searchMenu
QMenu* BibleTime::m_searchMenu private
Definition at line 445 of file bibletime.h.
m_searchOpenWorksAction
QAction* BibleTime::m_searchOpenWorksAction private
Definition at line 446 of file bibletime.h.
m_searchStandardBibleAction
QAction* BibleTime::m_searchStandardBibleAction private
Definition at line 447 of file bibletime.h.
m_setPreferencesAction
QAction* BibleTime::m_setPreferencesAction private
Definition at line 473 of file bibletime.h.
m_settingsMenu
QMenu* BibleTime::m_settingsMenu private
Definition at line 472 of file bibletime.h.
m_showBookmarksAction
QAction* BibleTime::m_showBookmarksAction private
Definition at line 433 of file bibletime.h.
m_showBookshelfAction
QAction* BibleTime::m_showBookshelfAction private
Definition at line 432 of file bibletime.h.
m_showMagAction
QAction* BibleTime::m_showMagAction private
Definition at line 434 of file bibletime.h.
m_showMainWindowToolbarAction
QAction* BibleTime::m_showMainWindowToolbarAction private
Definition at line 437 of file bibletime.h.
Referenced by reloadProfile(), and slotToggleMainToolbar().
m_showTextAreaHeadersAction
QAction* BibleTime::m_showTextAreaHeadersAction private
Definition at line 438 of file bibletime.h.
Referenced by reloadProfile().
m_showTextWindowModuleChooserAction
QAction* BibleTime::m_showTextWindowModuleChooserAction private
Definition at line 440 of file bibletime.h.
Referenced by reloadProfile().
m_showTextWindowNavigationAction
QAction* BibleTime::m_showTextWindowNavigationAction private
Definition at line 439 of file bibletime.h.
Referenced by reloadProfile().
m_showTextWindowToolButtonsAction
QAction* BibleTime::m_showTextWindowToolButtonsAction private
Definition at line 441 of file bibletime.h.
Referenced by reloadProfile().
m_tipOfTheDayAction
QAction* BibleTime::m_tipOfTheDayAction private
Definition at line 482 of file bibletime.h.
m_toolbarsInEachWindow
QAction* BibleTime::m_toolbarsInEachWindow private
Definition at line 442 of file bibletime.h.
Referenced by reloadProfile().
m_toolBarsMenu
QMenu* BibleTime::m_toolBarsMenu private
Definition at line 435 of file bibletime.h.
m_toolsToolBar
QToolBar* BibleTime::m_toolsToolBar private
Definition at line 423 of file bibletime.h.
Referenced by showOrHideToolBars(), slotToggleToolsToolbar(), and toolsToolBar().
m_viewMenu
QMenu* BibleTime::m_viewMenu private
Definition at line 431 of file bibletime.h.
m_windowArrangementActionGroup
QActionGroup* BibleTime::m_windowArrangementActionGroup private
Definition at line 458 of file bibletime.h.
m_windowArrangementMenu
QMenu* BibleTime::m_windowArrangementMenu private
Definition at line 457 of file bibletime.h.
m_windowAutoCascadeAction
QAction* BibleTime::m_windowAutoCascadeAction private
Definition at line 459 of file bibletime.h.
Referenced by slotUpdateWindowArrangementActions().
m_windowAutoTabbedAction
QAction* BibleTime::m_windowAutoTabbedAction private
Definition at line 461 of file bibletime.h.
Referenced by slotUpdateWindowArrangementActions().
m_windowAutoTileAction
QAction* BibleTime::m_windowAutoTileAction private
Definition at line 460 of file bibletime.h.
Referenced by slotUpdateWindowArrangementActions().
m_windowAutoTileHorizontalAction
QAction* BibleTime::m_windowAutoTileHorizontalAction private
Definition at line 463 of file bibletime.h.
Referenced by slotUpdateWindowArrangementActions().
m_windowAutoTileVerticalAction
QAction* BibleTime::m_windowAutoTileVerticalAction private
Definition at line 462 of file bibletime.h.
Referenced by slotUpdateWindowArrangementActions().
m_windowCascadeAction
QAction* BibleTime::m_windowCascadeAction private
Definition at line 452 of file bibletime.h.
Referenced by slotCascade(), slotUpdateWindowArrangementActions(), and slotWindowMenuAboutToShow().
m_windowCloseAction
QAction* BibleTime::m_windowCloseAction private
Definition at line 464 of file bibletime.h.
Referenced by slotWindowMenuAboutToShow().
m_windowCloseAllAction
QAction* BibleTime::m_windowCloseAllAction private
Definition at line 465 of file bibletime.h.
Referenced by slotWindowMenuAboutToShow().
m_windowDeleteProfileMenu
QMenu* BibleTime::m_windowDeleteProfileMenu private
Definition at line 469 of file bibletime.h.
Referenced by refreshProfileMenus().
m_windowFullscreenAction
QAction* BibleTime::m_windowFullscreenAction private
Definition at line 490 of file bibletime.h.
Referenced by reloadProfile().
m_windowLoadProfileActionGroup
QActionGroup* BibleTime::m_windowLoadProfileActionGroup private
Definition at line 468 of file bibletime.h.
Referenced by refreshProfileMenus().
m_windowLoadProfileMenu
QMenu* BibleTime::m_windowLoadProfileMenu private
Definition at line 467 of file bibletime.h.
Referenced by refreshProfileMenus().
m_windowManualModeAction
QAction* BibleTime::m_windowManualModeAction private
Definition at line 456 of file bibletime.h.
Referenced by slotUpdateWindowArrangementActions().
m_windowMenu
QMenu* BibleTime::m_windowMenu private
Definition at line 450 of file bibletime.h.
Referenced by slotWindowMenuAboutToShow().
m_windowSaveToNewProfileAction
QAction* BibleTime::m_windowSaveToNewProfileAction private
Definition at line 466 of file bibletime.h.
m_windowTileAction
QAction* BibleTime::m_windowTileAction private
Definition at line 453 of file bibletime.h.
Referenced by slotTile(), slotUpdateWindowArrangementActions(), and slotWindowMenuAboutToShow().
m_windowTileHorizontalAction
QAction* BibleTime::m_windowTileHorizontalAction private
Definition at line 454 of file bibletime.h.
Referenced by slotTileHorizontal(), slotUpdateWindowArrangementActions(), and slotWindowMenuAboutToShow().
m_windowTileVerticalAction
QAction* BibleTime::m_windowTileVerticalAction private
Definition at line 455 of file bibletime.h.
Referenced by slotTileVertical(), slotUpdateWindowArrangementActions(), and slotWindowMenuAboutToShow().
m_worksToolBar
BtModuleChooserBar* BibleTime::m_worksToolBar private
Definition at line 422 of file bibletime.h.
Referenced by showOrHideToolBars(), slotToggleWorksToolbar(), and worksToolBar().
paused
bool BibleTime::paused
Definition at line 497 of file bibletime.h.
speed
int BibleTime::speed
Definition at line 498 of file bibletime.h.
The documentation for this class was generated from the following files:
bibletime.h
bibletime.cpp
bibletime_init.cpp
bibletime_slots.cpp