BibleTime: anonymous_namespace{osistohtml.cpp} Namespace Reference
anonymous_namespace{osistohtml.cpp} Namespace Reference
Functions
template<typename UserData >
void renderReference (char const *const osisRef, sword::SWBuf &buf, sword::SWModule const &myModule, UserData const &myUserData)
Function Documentation
renderReference()
template<typename UserData > void anonymous_namespace{osistohtml.cpp}::renderReference (char const *const osisRef, sword::SWBuf & buf, sword::SWModule const & myModule, UserData const & myUserData)
Todo:
Should we add something if there were no referenced module available?
Definition at line 35 of file osistohtml.cpp.
References CSwordModuleInfo::Bible, btConfig(), CSwordModuleInfo::Commentary, CSwordBackend::findFirstAvailableModule(), CSwordBackend::findSwordModuleByPointer(), BtConfig::getDefaultSwordModuleByType(), and CSwordBackend::instance().