BibleTime: BtTextWindowHeader Class Reference
BtTextWindowHeader Class Reference
#include <bttextwindowheader.h>
Public Slots
void slotBackendModulesChanged () override
void slotWindowModulesChanged () override
Signals
void sigModuleAdd (int index, QString module)
void sigModuleRemove (int index)
void sigModuleReplace (int index, QString newModule)
Public Member Functions
BtTextWindowHeader (CSwordModuleInfo::ModuleType modtype, QStringList modules, CDisplayWindow *window)
Public Member Functions inherited from BtWindowModuleChooser
BtWindowModuleChooser (CSwordModuleInfo::ModuleType moduleType, CDisplayWindow *parentWindow)
virtual void slotBackendModulesChanged ()=0
virtual void slotWindowModulesChanged ()=0
Private Member Functions
BtTextWindowHeaderWidget * addWidget ()
void adjustWidgetCount (bool adjustToZero=false)
void initMenus ()
void setModules (QStringList useModules)
void updateWidgets ()
Private Attributes
QList< BtTextWindowHeaderWidget * > m_widgetList
Additional Inherited Members
Protected Attributes inherited from BtWindowModuleChooser
QStringList m_modules
CSwordModuleInfo::ModuleType m_moduleType
CDisplayWindow * m_window
Detailed Description
Definition at line 27 of file bttextwindowheader.h.
Constructor & Destructor Documentation
BtTextWindowHeader()
BtTextWindowHeader::BtTextWindowHeader (CSwordModuleInfo::ModuleType modtype, QStringList modules, CDisplayWindow * window)
Definition at line 28 of file bttextwindowheader.cpp.
References BT_CONNECT, setModules(), CDisplayWindow::sigModuleListChanged(), CDisplayWindow::sigModuleListSet(), slotBackendModulesChanged(), and slotWindowModulesChanged().
Member Function Documentation
addWidget()
BtTextWindowHeaderWidget * BtTextWindowHeader::addWidget () private
Adds an empty widget to the header.
Definition at line 94 of file bttextwindowheader.cpp.
References BT_CONNECT, BtWindowModuleChooser::m_moduleType, m_widgetList, BtWindowModuleChooser::m_window, BtTextWindowHeaderWidget::sigModuleAdd(), BtTextWindowHeaderWidget::sigModuleRemove(), BtTextWindowHeaderWidget::sigModuleReplace(), CDisplayWindow::slotAddModule(), CDisplayWindow::slotRemoveModule(), and CDisplayWindow::slotReplaceModule().
Referenced by adjustWidgetCount(), and setModules().
adjustWidgetCount()
void BtTextWindowHeader::adjustWidgetCount (bool adjustToZero = false) private
Removes or adds widgets so that the count matches the limit. The module count is the limit unless adjustToZero is true when limit is 0 and list is emptied.
Definition at line 64 of file bttextwindowheader.cpp.
References addWidget(), CSwordModuleInfo::GenericBook, BtWindowModuleChooser::m_modules, BtWindowModuleChooser::m_moduleType, and m_widgetList.
Referenced by setModules(), slotBackendModulesChanged(), and slotWindowModulesChanged().
initMenus()
void BtTextWindowHeader::initMenus () private
Called when backend has changed and menus must be created from scratch.
setModules()
void BtTextWindowHeader::setModules (QStringList useModules) private
Sets the initial modules.
Definition at line 112 of file bttextwindowheader.cpp.
References addWidget(), adjustWidgetCount(), BtWindowModuleChooser::m_modules, and updateWidgets().
Referenced by BtTextWindowHeader().
sigModuleAdd
void BtTextWindowHeader::sigModuleAdd (int index, QString module) signal
User selected a module from menu to add
sigModuleRemove
void BtTextWindowHeader::sigModuleRemove (int index) signal
User selected a module from menu to be removed
sigModuleReplace
void BtTextWindowHeader::sigModuleReplace (int index, QString newModule) signal
User selected a module from menu to replace another module
slotBackendModulesChanged
void BtTextWindowHeader::slotBackendModulesChanged () override slot
The backend module list was updated, module list and widgets must be updated from scratch.
Definition at line 45 of file bttextwindowheader.cpp.
References adjustWidgetCount(), CDisplayWindow::getModuleList(), leftLikeParallelModules(), BtWindowModuleChooser::m_modules, m_widgetList, and BtWindowModuleChooser::m_window.
Referenced by BtTextWindowHeader().
slotWindowModulesChanged
void BtTextWindowHeader::slotWindowModulesChanged () override slot
The window module list was updated, module list and widgets must be updated.
Definition at line 58 of file bttextwindowheader.cpp.
References adjustWidgetCount(), CDisplayWindow::getModuleList(), BtWindowModuleChooser::m_modules, BtWindowModuleChooser::m_window, and updateWidgets().
Referenced by BtTextWindowHeader().
updateWidgets()
void BtTextWindowHeader::updateWidgets () private
Updates all widgets without recreating them.
Definition at line 123 of file bttextwindowheader.cpp.
References leftLikeParallelModules(), BtWindowModuleChooser::m_modules, and m_widgetList.
Referenced by setModules(), and slotWindowModulesChanged().
Member Data Documentation
m_widgetList
QList<BtTextWindowHeaderWidget*> BtTextWindowHeader::m_widgetList private
Definition at line 69 of file bttextwindowheader.h.
Referenced by addWidget(), adjustWidgetCount(), slotBackendModulesChanged(), and updateWidgets().
The documentation for this class was generated from the following files:
bttextwindowheader.h
bttextwindowheader.cpp