BibleTime: anonymous_namespace{btshortcutseditor.cpp} Namespace Reference
anonymous_namespace{btshortcutseditor.cpp} Namespace Reference
Classes
class BtShortcutsEditorItem
Functions
auto getShortcutsEditor (QTableWidget const &tableWidget, int const row)
Function Documentation
getShortcutsEditor()
auto anonymous_namespace{btshortcutseditor.cpp}::getShortcutsEditor (QTableWidget const & tableWidget, int const row) inline
Definition at line 111 of file btshortcutseditor.cpp.
Referenced by BtShortcutsEditor::clearConflictWithKeys(), BtShortcutsEditor::commitChanges(), BtShortcutsEditor::customButtonClicked(), BtShortcutsEditor::defaultButtonClicked(), BtShortcutsEditor::noneButtonClicked(), and BtShortcutsEditor::slotSelectionChanged().