BibleTime: BtQmlScrollView Class Reference
BtQmlScrollView Class Reference
#include <btqmlscrollview.h>
Signals
void referenceDropped (const QString &reference)
Public Member Functions
BtQmlScrollView (QWidget *parent, BtModelViewReadDisplay *readDisplay)
void findTextHighlight (const QString &text, bool caseSensitive)
BtQmlInterface * getQmlInterface () const
void pageDown ()
void pageUp ()
BtQmlInterface * qmlInterface () const
BtQuickWidget * quickWidget ()
void referenceChoosen ()
void scrollToSwordKey (CSwordKey *key)
void setFilterOptions (FilterOptions filterOptions)
void setKey (CSwordKey *key)
void setModules (const QStringList &modules)
void settingsChanged ()
~BtQmlScrollView () override
Protected Member Functions
void contextMenuEvent (QContextMenuEvent *event) override
virtual void resizeEvent (QResizeEvent *event) override
Private Slots
void slotSliderMoved (int value)
void slotSliderPressed ()
void slotSliderReleased ()
Private Member Functions
void initScrollBar ()
Private Attributes
BtQmlInterface * m_qmlInterface
BtQuickWidget * m_quickWidget
BtModelViewReadDisplay * m_readDisplay
QScrollBar * m_scrollBar
int m_scrollBarPosition
Detailed Description
Definition at line 34 of file btqmlscrollview.h.
Constructor & Destructor Documentation
BtQmlScrollView()
BtQmlScrollView::BtQmlScrollView (QWidget * parent, BtModelViewReadDisplay * readDisplay)
Definition at line 42 of file btqmlscrollview.cpp.
References BT_CONNECT, initScrollBar(), m_qmlInterface, m_quickWidget, m_scrollBar, BtQmlInterface::newBibleReference(), referenceDropped(), and BtQuickWidget::referenceDropped().
~BtQmlScrollView()
BtQmlScrollView::~BtQmlScrollView () override
Definition at line 72 of file btqmlscrollview.cpp.
Member Function Documentation
contextMenuEvent()
void BtQmlScrollView::contextMenuEvent (QContextMenuEvent * event) override protected
Definition at line 76 of file btqmlscrollview.cpp.
References BtModelViewReadDisplay::contextMenu(), m_quickWidget, m_readDisplay, and BtQuickWidget::saveContextMenuIndex().
findTextHighlight()
void BtQmlScrollView::findTextHighlight (const QString & text, bool caseSensitive)
hightlight text
Definition at line 149 of file btqmlscrollview.cpp.
References m_qmlInterface, and BtQmlInterface::setHighlightWords().
getQmlInterface()
BtQmlInterface * BtQmlScrollView::getQmlInterface () const
Definition at line 115 of file btqmlscrollview.cpp.
References m_qmlInterface.
Referenced by BtQuickWidget::getQmlInterface().
initScrollBar()
void BtQmlScrollView::initScrollBar () private
Definition at line 86 of file btqmlscrollview.cpp.
References BT_CONNECT, m_scrollBar, slotSliderMoved(), slotSliderPressed(), and slotSliderReleased().
Referenced by BtQmlScrollView().
pageDown()
void BtQmlScrollView::pageDown ()
Definition at line 141 of file btqmlscrollview.cpp.
References m_qmlInterface, and BtQmlInterface::pageDown.
Referenced by BtModelViewReadDisplay::pageDown().
pageUp()
void BtQmlScrollView::pageUp ()
Definition at line 145 of file btqmlscrollview.cpp.
References m_qmlInterface, and BtQmlInterface::pageUp.
Referenced by BtModelViewReadDisplay::pageUp().
qmlInterface()
BtQmlInterface* BtQmlScrollView::qmlInterface () const inline
Definition at line 58 of file btqmlscrollview.h.
References m_qmlInterface.
Referenced by BtModelViewReadDisplay::BtModelViewReadDisplay(), BtModelViewReadDisplay::contextMenu(), BtModelViewReadDisplay::findText(), BtModelViewReadDisplay::highlightText(), BtModelViewReadDisplay::qmlInterface(), BtModelViewReadDisplay::setDisplayOptions(), and BtModelViewReadDisplay::setModules().
quickWidget()
BtQuickWidget* BtQmlScrollView::quickWidget () inline
Definition at line 54 of file btqmlscrollview.h.
References m_quickWidget.
Referenced by BtModelViewReadDisplay::quickWidget(), BtModelViewReadDisplay::scroll(), BtModelViewReadDisplay::setDisplayFocus(), and BtModelViewReadDisplay::updateReferenceText().
referenceChoosen()
void BtQmlScrollView::referenceChoosen ()
Definition at line 133 of file btqmlscrollview.cpp.
References m_qmlInterface, and BtQmlInterface::referenceChosen().
referenceDropped
void BtQmlScrollView::referenceDropped (const QString & reference) signal
Referenced by BtQmlScrollView().
resizeEvent()
void BtQmlScrollView::resizeEvent (QResizeEvent * event) override protected virtual
Definition at line 157 of file btqmlscrollview.cpp.
scrollToSwordKey()
void BtQmlScrollView::scrollToSwordKey (CSwordKey * key)
Definition at line 129 of file btqmlscrollview.cpp.
References m_qmlInterface, and BtQmlInterface::scrollToSwordKey().
Referenced by BtModelViewReadDisplay::scrollToKey().
setFilterOptions()
void BtQmlScrollView::setFilterOptions (FilterOptions filterOptions)
Definition at line 153 of file btqmlscrollview.cpp.
References m_qmlInterface, and BtQmlInterface::setFilterOptions().
Referenced by BtModelViewReadDisplay::setFilterOptions().
setKey()
void BtQmlScrollView::setKey (CSwordKey * key)
Sets the new sword key.
Definition at line 124 of file btqmlscrollview.cpp.
References BT_ASSERT, m_qmlInterface, and BtQmlInterface::setKey().
setModules()
void BtQmlScrollView::setModules (const QStringList & modules)
Definition at line 119 of file btqmlscrollview.cpp.
References m_qmlInterface, and BtQmlInterface::setModules().
settingsChanged()
void BtQmlScrollView::settingsChanged ()
Definition at line 137 of file btqmlscrollview.cpp.
References m_qmlInterface, and BtQmlInterface::settingsChanged().
Referenced by BtModelViewReadDisplay::settingsChanged().
slotSliderMoved
void BtQmlScrollView::slotSliderMoved (int value) private slot
Definition at line 97 of file btqmlscrollview.cpp.
References BibleTime::autoScrollStop(), BibleTime::instance(), m_quickWidget, m_scrollBarPosition, and BtQuickWidget::scroll().
Referenced by initScrollBar().
slotSliderPressed
void BtQmlScrollView::slotSliderPressed () private slot
Definition at line 105 of file btqmlscrollview.cpp.
References m_scrollBar, and m_scrollBarPosition.
Referenced by initScrollBar().
slotSliderReleased
void BtQmlScrollView::slotSliderReleased () private slot
Definition at line 109 of file btqmlscrollview.cpp.
References m_quickWidget, m_scrollBar, and BtQuickWidget::updateReferenceText().
Referenced by initScrollBar().
Member Data Documentation
m_qmlInterface
BtQmlInterface* BtQmlScrollView::m_qmlInterface private
Definition at line 77 of file btqmlscrollview.h.
Referenced by BtQmlScrollView(), findTextHighlight(), getQmlInterface(), pageDown(), pageUp(), qmlInterface(), referenceChoosen(), scrollToSwordKey(), setFilterOptions(), setKey(), setModules(), and settingsChanged().
m_quickWidget
BtQuickWidget* BtQmlScrollView::m_quickWidget private
Definition at line 78 of file btqmlscrollview.h.
Referenced by BtQmlScrollView(), contextMenuEvent(), quickWidget(), slotSliderMoved(), and slotSliderReleased().
m_readDisplay
BtModelViewReadDisplay* BtQmlScrollView::m_readDisplay private
Definition at line 76 of file btqmlscrollview.h.
Referenced by contextMenuEvent().
m_scrollBar
QScrollBar* BtQmlScrollView::m_scrollBar private
Definition at line 79 of file btqmlscrollview.h.
Referenced by BtQmlScrollView(), initScrollBar(), slotSliderPressed(), and slotSliderReleased().
m_scrollBarPosition
int BtQmlScrollView::m_scrollBarPosition private
Definition at line 80 of file btqmlscrollview.h.
Referenced by slotSliderMoved(), and slotSliderPressed().
The documentation for this class was generated from the following files:
btqmlscrollview.h
btqmlscrollview.cpp