BibleTime: ColorManager Namespace Reference
ColorManager Namespace Reference
Namespaces
anonymous_namespace{colormanager.cpp}
Functions
QString getBackgroundColor ()
QString getBackgroundColor (QString const &templateName)
QString getBackgroundHighlightColor ()
QString getBackgroundHighlightColor (QString const &templateName)
QString getCrossRefColor ()
QString getCrossRefColor (QString const &templateName)
QString getForegroundColor ()
QString getForegroundColor (QString const &templateName)
QString replaceColors (QString content)
QString replaceColors (QString content, QString const &templateName)
Function Documentation
getBackgroundColor() [1/2]
QString ColorManager::getBackgroundColor ()
Definition at line 147 of file colormanager.cpp.
References CDisplayTemplateMgr::activeTemplateName().
Referenced by BtQmlInterface::getBackgroundColor(), InfoDisplay::CInfoDisplay::updateColors(), and CDisplaySettingsPage::updateStylePreview().
getBackgroundColor() [2/2]
QString ColorManager::getBackgroundColor (QString const & templateName)
Definition at line 150 of file colormanager.cpp.
References ColorManager::anonymous_namespace{colormanager.cpp}::getColorByPattern().
getBackgroundHighlightColor() [1/2]
QString ColorManager::getBackgroundHighlightColor ()
Definition at line 153 of file colormanager.cpp.
References CDisplayTemplateMgr::activeTemplateName().
Referenced by BtQmlInterface::getBackgroundHighlightColor().
getBackgroundHighlightColor() [2/2]
QString ColorManager::getBackgroundHighlightColor (QString const & templateName)
Definition at line 158 of file colormanager.cpp.
References ColorManager::anonymous_namespace{colormanager.cpp}::getColorByPattern().
getCrossRefColor() [1/2]
QString ColorManager::getCrossRefColor ()
Definition at line 169 of file colormanager.cpp.
References CDisplayTemplateMgr::activeTemplateName().
getCrossRefColor() [2/2]
QString ColorManager::getCrossRefColor (QString const & templateName)
Definition at line 172 of file colormanager.cpp.
References ColorManager::anonymous_namespace{colormanager.cpp}::getColorByPattern().
getForegroundColor() [1/2]
QString ColorManager::getForegroundColor ()
Definition at line 163 of file colormanager.cpp.
References CDisplayTemplateMgr::activeTemplateName().
Referenced by BtQmlInterface::getForegroundColor(), InfoDisplay::CInfoDisplay::updateColors(), and CDisplaySettingsPage::updateStylePreview().
getForegroundColor() [2/2]
QString ColorManager::getForegroundColor (QString const & templateName)
Definition at line 166 of file colormanager.cpp.
References ColorManager::anonymous_namespace{colormanager.cpp}::getColorByPattern().
replaceColors() [1/2]
QString ColorManager::replaceColors (QString content)
Definition at line 133 of file colormanager.cpp.
References CDisplayTemplateMgr::activeTemplateName().
Referenced by BtModuleTextModel::lexiconData(), InfoDisplay::CInfoDisplay::setInfo(), Search::BtSearchResultArea::updatePreview(), CDisplaySettingsPage::updateStylePreview(), and BtModuleTextModel::verseData().
replaceColors() [2/2]
QString ColorManager::replaceColors (QString content, QString const & templateName)
Definition at line 138 of file colormanager.cpp.
References BT_ASSERT, and ColorManager::anonymous_namespace{colormanager.cpp}::colorMaps().