BibleTime: DebugWindow Class Reference
DebugWindow Class Reference
#include <debugwindow.h>
Public Member Functions
DebugWindow ()
void retranslateUi ()
void timerEvent (QTimerEvent *const event) override
Static Public Member Functions
static QQuickItem const * quickItemInFocus (QQuickWidget const *quickWidget, QPointF cursorPosition)
Private Attributes
int const m_updateTimerId
Detailed Description
Definition at line 23 of file debugwindow.h.
Constructor & Destructor Documentation
DebugWindow()
DebugWindow::DebugWindow ()
Definition at line 58 of file debugwindow.cpp.
References retranslateUi().
Member Function Documentation
quickItemInFocus()
QQuickItem const * DebugWindow::quickItemInFocus (QQuickWidget const * quickWidget, QPointF cursorPosition) static
Definition at line 101 of file debugwindow.cpp.
Referenced by BtModelViewReadDisplay::contextMenuEvent(), and timerEvent().
retranslateUi()
void DebugWindow::retranslateUi ()
Definition at line 69 of file debugwindow.cpp.
Referenced by DebugWindow().
timerEvent()
void DebugWindow::timerEvent (QTimerEvent *const event) override
Definition at line 72 of file debugwindow.cpp.
References m_updateTimerId, and quickItemInFocus().
Member Data Documentation
m_updateTimerId
int const DebugWindow::m_updateTimerId private
Definition at line 40 of file debugwindow.h.
Referenced by timerEvent().
The documentation for this class was generated from the following files:
debugwindow.h
debugwindow.cpp