BibleTime: BtBookshelfSourcesProgressPage Class Reference
BtBookshelfSourcesProgressPage Class Reference final
#include <btbookshelfsourcesprogresspage.h>
Public Slots
void slotStopInstall ()
Public Member Functions
BtBookshelfSourcesProgressPage (QWidget *parent=nullptr)
void destroyThread () noexcept
void initializePage () final override
bool isComplete () const final override
int nextId () const final override
~BtBookshelfSourcesProgressPage () noexcept override
Public Member Functions inherited from BtBookshelfWizardPage
BtBookshelfWizardPage (QWidget *parent=nullptr)
BtBookshelfWizard & btWizard () const noexcept
Private Slots
void slotThreadFinished ()
Private Member Functions
void retranslateUi ()
Private Attributes
bool m_installCompleted = false
QLabel * m_msgLabel
QProgressBar * m_progressBar
QPushButton * m_stopButton
BtSourcesThread * m_thread = nullptr
Detailed Description
Definition at line 27 of file btbookshelfsourcesprogresspage.h.
Constructor & Destructor Documentation
BtBookshelfSourcesProgressPage()
BtBookshelfSourcesProgressPage::BtBookshelfSourcesProgressPage (QWidget * parent = nullptr)
Definition at line 32 of file btbookshelfsourcesprogresspage.cpp.
References BT_CONNECT, m_msgLabel, m_progressBar, m_stopButton, and slotStopInstall().
~BtBookshelfSourcesProgressPage()
BtBookshelfSourcesProgressPage::~BtBookshelfSourcesProgressPage () inline override noexcept
Definition at line 34 of file btbookshelfsourcesprogresspage.h.
References destroyThread().
Member Function Documentation
destroyThread()
void BtBookshelfSourcesProgressPage::destroyThread () noexcept
Definition at line 72 of file btbookshelfsourcesprogresspage.cpp.
References m_thread, and BtSourcesThread::stop().
Referenced by initializePage(), and ~BtBookshelfSourcesProgressPage().
initializePage()
void BtBookshelfSourcesProgressPage::initializePage () final override
Definition at line 97 of file btbookshelfsourcesprogresspage.cpp.
References BT_CONNECT, BtBookshelfWizardPage::btWizard(), destroyThread(), BtBookshelfWizard::downloadStarted(), m_installCompleted, m_msgLabel, m_progressBar, m_stopButton, m_thread, BtSourcesThread::percentComplete(), retranslateUi(), BtSourcesThread::showMessage(), and slotThreadFinished().
isComplete()
bool BtBookshelfSourcesProgressPage::isComplete () const final override
Definition at line 117 of file btbookshelfsourcesprogresspage.cpp.
References m_installCompleted.
nextId()
int BtBookshelfSourcesProgressPage::nextId () const final override
Definition at line 91 of file btbookshelfsourcesprogresspage.cpp.
References BtBookshelfWizardPage::btWizard(), sourcesPage, updateWorks, and updateWorksPage.
retranslateUi()
void BtBookshelfSourcesProgressPage::retranslateUi () private
Definition at line 81 of file btbookshelfsourcesprogresspage.cpp.
References m_stopButton.
Referenced by initializePage().
slotStopInstall
void BtBookshelfSourcesProgressPage::slotStopInstall () slot
Definition at line 129 of file btbookshelfsourcesprogresspage.cpp.
References m_stopButton, m_thread, and BtSourcesThread::stop().
Referenced by BtBookshelfSourcesProgressPage(), and BtBookshelfWizard::stopDownload().
slotThreadFinished
void BtBookshelfSourcesProgressPage::slotThreadFinished () private slot
Definition at line 120 of file btbookshelfsourcesprogresspage.cpp.
References BtBookshelfWizardPage::btWizard(), BtBookshelfWizard::downloadFinished(), BtSourcesThread::finishedSuccessfully(), m_installCompleted, m_stopButton, m_thread, and BtBookshelfWizard::setAutoUpdateSources().
Referenced by initializePage().
Member Data Documentation
m_installCompleted
bool BtBookshelfSourcesProgressPage::m_installCompleted = false private
Definition at line 55 of file btbookshelfsourcesprogresspage.h.
Referenced by initializePage(), isComplete(), and slotThreadFinished().
m_msgLabel
QLabel* BtBookshelfSourcesProgressPage::m_msgLabel private
Definition at line 56 of file btbookshelfsourcesprogresspage.h.
Referenced by BtBookshelfSourcesProgressPage(), and initializePage().
m_progressBar
QProgressBar* BtBookshelfSourcesProgressPage::m_progressBar private
Definition at line 57 of file btbookshelfsourcesprogresspage.h.
Referenced by BtBookshelfSourcesProgressPage(), and initializePage().
m_stopButton
QPushButton* BtBookshelfSourcesProgressPage::m_stopButton private
Definition at line 58 of file btbookshelfsourcesprogresspage.h.
Referenced by BtBookshelfSourcesProgressPage(), initializePage(), retranslateUi(), slotStopInstall(), and slotThreadFinished().
m_thread
BtSourcesThread* BtBookshelfSourcesProgressPage::m_thread = nullptr private
Definition at line 59 of file btbookshelfsourcesprogresspage.h.
Referenced by destroyThread(), initializePage(), slotStopInstall(), and slotThreadFinished().
The documentation for this class was generated from the following files:
btbookshelfsourcesprogresspage.h
btbookshelfsourcesprogresspage.cpp