BibleTime: anonymous_namespace{cdisplaytemplatemgr.cpp} Namespace Reference
anonymous_namespace{cdisplaytemplatemgr.cpp} Namespace Reference
Functions
QString readFileToString (const QString &filename)
Variables
auto const defaultTemplateName = QStringLiteral("Blue.css")
Function Documentation
readFileToString()
QString anonymous_namespace{cdisplaytemplatemgr.cpp}::readFileToString (const QString & filename) inline
Definition at line 39 of file cdisplaytemplatemgr.cpp.
Referenced by CDisplayTemplateMgr::loadCSSTemplate(), and CDisplayTemplateMgr::loadTemplate().
Variable Documentation
defaultTemplateName
auto const anonymous_namespace{cdisplaytemplatemgr.cpp}::defaultTemplateName = QStringLiteral("Blue.css")
Definition at line 44 of file cdisplaytemplatemgr.cpp.
Referenced by CDisplayTemplateMgr::activeTemplateName(), and CDisplayTemplateMgr::CDisplayTemplateMgr().