BibleTime: anonymous_namespace{btlocalemgr.cpp} Namespace Reference
anonymous_namespace{btlocalemgr.cpp} Namespace Reference
Classes
struct BtLocaleMgrImpl
Functions
BtLocaleMgrImpl & btLocaleMgrInstance ()
Function Documentation
btLocaleMgrInstance()
BtLocaleMgrImpl& anonymous_namespace{btlocalemgr.cpp}::btLocaleMgrInstance ()
Definition at line 43 of file btlocalemgr.cpp.
Referenced by BtLocaleMgr::defaultLocaleName(), BtLocaleMgr::internalSwordLocales(), BtLocaleMgr::localeTranslator(), and BtLocaleMgr::setDefaultLocaleName().