BibleTime: btqmlinterface.cpp File Reference
btqmlinterface.cpp File Reference
#include "btqmlinterface.h"
#include <QApplication>
#include <QClipboard>
#include <QScreen>
#include <QTimer>
#include <utility>
#include "../../../backend/config/btconfig.h"
#include "../../../backend/drivers/cswordbookmoduleinfo.h"
#include "../../../backend/drivers/cswordlexiconmoduleinfo.h"
#include "../../../backend/drivers/cswordmoduleinfo.h"
#include "../../../backend/keys/cswordkey.h"
#include "../../../backend/managers/colormanager.h"
#include "../../../backend/managers/cdisplaytemplatemgr.h"
#include "../../../backend/managers/cswordbackend.h"
#include "../../../backend/models/btmoduletextmodel.h"
#include "../../../backend/rendering/btinforendering.h"
#include "../../../backend/rendering/cplaintextexportrendering.h"
#include "../../../backend/rendering/ctextrendering.h"
#include "../../../util/btconnect.h"
#include "../../bibletime.h"
#include "../../cinfodisplay.h"
#include "../../edittextwizard/btedittextwizard.h"
Functions
static bool moduleIsBibleOrCommentary (const CSwordModuleInfo *module)
static bool moduleIsBook (const CSwordModuleInfo *module)
static bool moduleIsLexicon (const CSwordModuleInfo *module)
Function Documentation
moduleIsBibleOrCommentary()
static bool moduleIsBibleOrCommentary (const CSwordModuleInfo * module) static
Definition at line 79 of file btqmlinterface.cpp.
References CSwordModuleInfo::Bible, CSwordModuleInfo::Commentary, and CSwordModuleInfo::type().
Referenced by BtQmlInterface::getCurrentModelIndex(), and BtQmlInterface::isBibleOrCommentary().
moduleIsBook()
static bool moduleIsBook (const CSwordModuleInfo * module) static
Definition at line 65 of file btqmlinterface.cpp.
References CSwordModuleInfo::GenericBook, and CSwordModuleInfo::type().
Referenced by BtQmlInterface::getCurrentModelIndex().
moduleIsLexicon()
static bool moduleIsLexicon (const CSwordModuleInfo * module) static
Definition at line 72 of file btqmlinterface.cpp.
References CSwordModuleInfo::Lexicon, and CSwordModuleInfo::type().
Referenced by BtQmlInterface::getCurrentModelIndex().