BibleTime: util::tool Namespace Reference
util::tool Namespace Reference
Functions
QLabel * explanationLabel (QWidget *const parent, const QString &heading, const QString &text)
QString fixSwordBcp47 (QString input)
const QIcon & getIconForModule (const CSwordModuleInfo *const module)
bool inHTMLTag (const int pos, const QString &text)
void initExplanationLabel (QLabel *label, const QString &heading, const QString &text)
Initializes a QLabel to explain difficult things of dialogs.
int mWidth (const QWidget *widget, int mCount)
Calculates a maximum rendered text width for a widget and a string with the a given length.
QString remoteModuleToolTip (const CSwordModuleInfo &module, const QString &localVer)
bool savePlainFile (const QString &filename, const QString &text, QTextCodec *const fileCodec)
Function Documentation
explanationLabel()
QLabel * util::tool::explanationLabel (QWidget * parent, const QString & heading, const QString & text)
Creates a new explanation label.
Parameters
[in] parent the parent widget.
[in] heading the heading of the label.
[in] text the text of the label.
Returns
a new QLabel initialized by initExplanationLabel().
Definition at line 131 of file tool.cpp.
fixSwordBcp47()
QString util::tool::fixSwordBcp47 (QString input)
Parameters
[in] input The potentially invalid BCP 47 string from Sword to fix.
Returns
a string (hopefully) more conformant to BCP 47
Definition at line 245 of file tool.cpp.
Referenced by CDisplaySettingsPage::initSwordLocaleCombo(), and CDisplaySettingsPage::resetLanguage().
getIconForModule()
const QIcon & util::tool::getIconForModule (const CSwordModuleInfo * module)
Parameters
[in] module the module whose icon to return.
Returns
the icon used for the a module.
Definition at line 95 of file tool.cpp.
Referenced by CBookReadWindow::initView(), CDisplayWindow::initView(), CBibleReadWindow::setupPopupMenu(), CDisplayWindow::setupPopupMenu(), and Search::CModuleResultView::setupTree().
inHTMLTag()
bool util::tool::inHTMLTag (int pos, const QString & text)
Returns
whether the character at position "pos" of text is inside an HTML tag.
Definition at line 164 of file tool.cpp.
References CSwordModuleInfo::category(), CSwordModuleInfo::config(), CSwordModuleInfo::Cult, CSwordModuleInfo::Description, CSwordModuleInfo::isEncrypted(), and CSwordModuleInfo::name().
initExplanationLabel()
void util::tool::initExplanationLabel (QLabel * label, const QString & heading, const QString & text)
Initializes a QLabel to explain difficult things of dialogs.
The label should be used to explain difficult things of the GUI, e.g. in the options dialog pages.
Parameters
[in] label The label to initialize
[in] heading The heading for the label.
[in] text The text for the label.
Definition at line 140 of file tool.cpp.
Referenced by BtSearchModuleChooserDialog::retranslateUi(), BtStandardWorksTab::retranslateUi(), and BtTextFiltersTab::retranslateUi().
mWidth()
int util::tool::mWidth (const QWidget * widget, int mCount)
Calculates a maximum rendered text width for a widget and a string with the a given length.
This function can be used for setting the size for a widget. It may be better to roughly calculate the size based on some text width rather than use a hard- coded value.
Parameters
[in] widget the widget whose font metrics to use. If 0, then the font metrics of the application are used.
[in] mCount the length of the string of 'M' characters to use for calculating the width.
Returns
the width in pixels.
Definition at line 232 of file tool.cpp.
Referenced by BtIndexDialog::BtIndexDialog(), Search::BtSearchOptionsArea::initView(), CBookmarkIndex::paintEvent(), and CListWidget::setCharWidth().
remoteModuleToolTip()
QString util::tool::remoteModuleToolTip (const CSwordModuleInfo & module, const QString & localVer)
Parameters
[in] module The module required for the tooltip
Returns
the remote module's tooltip text.
Definition at line 182 of file tool.cpp.
savePlainFile()
bool util::tool::savePlainFile (const QString & filename, const QString & text, QTextCodec *const fileCodec)
Creates the file filename and put text into the file.
Creates the file filename and save the given text into the file.
Parameters
[in] filename the filename to save to.
[in] text the string data to save.
[in] forceOverwrite whether to force the overwrite.
[in] fileCodec the codec to use to save the given string data.
Note
if the file exists, and forceOverwrite is false, a confirmation dialog is shown to ask the user whether to overwrite the existing file.
Returns
whether the file was properly saved.
Definition at line 59 of file tool.cpp.
Referenced by BtModelViewReadDisplay::save(), BtBookmarksModel::save(), CExportManager::saveKey(), and CExportManager::saveKeyList().