BibleTime: Rendering::CBookDisplay Class Reference
Rendering::CBookDisplay Class Reference
CEntryDisplay implementation for GenBook modules,.
#include <cbookdisplay.h>
Public Member Functions
const QString text (const BtConstModuleList &modules, const QString &key, const DisplayOptions &displayOptions, const FilterOptions &filterOptions) override
Public Member Functions inherited from Rendering::CEntryDisplay
virtual char display (CSwordModuleInfo &mod)
const QString textKeyRendering (const BtConstModuleList &modules, const QString &key, const DisplayOptions &displayOptions, const FilterOptions &filterOptions, CTextRendering::KeyTreeItem::Settings::KeyRenderingFace keyRendering)
virtual ~CEntryDisplay ()
Detailed Description
CEntryDisplay implementation for GenBook modules,.
A CEntryDisplay implementation which works on tree-based GenBook modules of Sword.
Definition at line 32 of file cbookdisplay.h.
Member Function Documentation
text()
const QString Rendering::CBookDisplay::text (const BtConstModuleList & modules, const QString & key, const DisplayOptions & displayOptions, const FilterOptions & filterOptions) override virtual
Returns
the rendered text using the modules in the list and using the key parameter.
Check whether displaying displayLevel levels together is possible. For this count the childs and parents of the required position
Reimplemented from Rendering::CEntryDisplay.
Definition at line 58 of file cbookdisplay.cpp.
References BT_ASSERT, CSwordKey::createInstance(), CSwordModuleInfo::DisplayLevel, DisplayOptions::lineBreaks, Rendering::CTextRendering::renderKeyTree(), and anonymous_namespace{cbookdisplay.cpp}::setupRenderTree().
The documentation for this class was generated from the following files:
cbookdisplay.h
cbookdisplay.cpp