BibleTime: Rendering::CChapterDisplay Class Reference
Rendering::CChapterDisplay Class Reference
CEntryDisplay implementation for whole chapters.
#include <cchapterdisplay.h>
Public Member Functions
const QString text (const BtConstModuleList &modules, const QString &key, const DisplayOptions &displayOptions, const FilterOptions &filterOptions) override
Public Member Functions inherited from Rendering::CEntryDisplay
virtual char display (CSwordModuleInfo &mod)
const QString textKeyRendering (const BtConstModuleList &modules, const QString &key, const DisplayOptions &displayOptions, const FilterOptions &filterOptions, CTextRendering::KeyTreeItem::Settings::KeyRenderingFace keyRendering)
virtual ~CEntryDisplay ()
Detailed Description
CEntryDisplay implementation for whole chapters.
A CEntryDisplay implementation made for Bibles to display whole chapters at once.
Definition at line 36 of file cchapterdisplay.h.
Member Function Documentation
text()
const QString Rendering::CChapterDisplay::text (const BtConstModuleList & modules, const QString & key, const DisplayOptions & displayOptions, const FilterOptions & filterOptions) override virtual
Returns
the rendered text using the modules in the list and using the key parameter.
Reimplemented from Rendering::CEntryDisplay.
Definition at line 29 of file cchapterdisplay.cpp.
References CSwordModuleInfo::Bible, CSwordVerseKey::bookName(), BT_ASSERT, CSwordVerseKey::chapter(), Rendering::CTextRendering::KeyTreeItem::Settings::keyRenderingFace, CSwordModuleInfo::module(), Rendering::CTextRendering::KeyTreeItem::Settings::NoKey, Rendering::CTextRendering::renderKeyRange(), CSwordVerseKey::setChapter(), CSwordVerseKey::setIntros(), CSwordVerseKey::setKey(), CSwordVerseKey::setVerse(), Rendering::CTextRendering::KeyTreeItem::Settings::SimpleKey, CSwordModuleInfo::type(), and DisplayOptions::verseNumbers.
The documentation for this class was generated from the following files:
cchapterdisplay.h
cchapterdisplay.cpp