BibleTime: CLexiconKeyChooser Class Reference
CLexiconKeyChooser Class Reference final
#include <clexiconkeychooser.h>
Public Slots
void updateKey (CSwordKey *key) final override
Public Slots inherited from CKeyChooser
void handleHistoryMoved (QString const &newKey)
virtual void updateKey (CSwordKey *key)=0
Public Member Functions
CLexiconKeyChooser (BtConstModuleList const &modules, CSwordKey *key=nullptr, QWidget *parent=nullptr)
CSwordKey * key () final override
void refreshContent () final override
void setKey (CSwordKey *key) final override
void setModules (BtConstModuleList const &modules, bool refresh=true) final override
Private Attributes
CSwordLDKey * m_key
QList< CSwordLexiconModuleInfo const * > m_modules
CKeyChooserWidget * m_widget
Additional Inherited Members
Signals inherited from CKeyChooser
void keyChanged (CSwordKey *newKey)
Static Public Member Functions inherited from CKeyChooser
static CKeyChooser * createInstance (const BtConstModuleList &modules, CSwordKey *key, QWidget *parent)
Protected Member Functions inherited from CKeyChooser
CKeyChooser (QWidget *parent=nullptr)
Detailed Description
Definition at line 30 of file clexiconkeychooser.h.
Constructor & Destructor Documentation
CLexiconKeyChooser()
CLexiconKeyChooser::CLexiconKeyChooser (BtConstModuleList const & modules, CSwordKey * key = nullptr, QWidget * parent = nullptr)
Definition at line 34 of file clexiconkeychooser.cpp.
References BT_CONNECT, CKeyChooserWidget::changed(), CKeyChooserWidget::comboBox(), CKeyChooserWidget::focusOut(), CSwordLDKey::key(), key(), m_key, m_widget, CSwordLDKey::setKey(), setKey(), setModules(), and CKeyChooserWidget::setToolTips().
Member Function Documentation
key()
CSwordKey * CLexiconKeyChooser::key () final override virtual
Returns
the current CKey.
Implements CKeyChooser.
Definition at line 84 of file clexiconkeychooser.cpp.
References m_key.
Referenced by CLexiconKeyChooser(), setKey(), and updateKey().
refreshContent()
void CLexiconKeyChooser::refreshContent () final override virtual
Reimplementation.
Implements CKeyChooser.
Definition at line 112 of file clexiconkeychooser.cpp.
References m_modules, m_widget, and CKeyChooserWidget::reset().
Referenced by setModules().
setKey()
void CLexiconKeyChooser::setKey (CSwordKey * key) final override virtual
Sets the CKey
Parameters
key the key which the widget should be set to.
Implements CKeyChooser.
Definition at line 100 of file clexiconkeychooser.cpp.
References key(), CKeyChooser::keyChanged(), m_key, and updateKey().
Referenced by CLexiconKeyChooser().
setModules()
void CLexiconKeyChooser::setModules (BtConstModuleList const & modules, bool refresh = true) final override virtual
Sets the module of this keychooser and refreshes the comboboxes
Implements CKeyChooser.
Definition at line 154 of file clexiconkeychooser.cpp.
References m_modules, and refreshContent().
Referenced by CLexiconKeyChooser().
updateKey
void CLexiconKeyChooser::updateKey (CSwordKey * key) final override slot
Update key display without emiting a signal
Definition at line 90 of file clexiconkeychooser.cpp.
References CKeyChooserWidget::comboBox(), CSwordLDKey::key(), key(), m_key, and m_widget.
Referenced by setKey().
Member Data Documentation
m_key
CSwordLDKey* CLexiconKeyChooser::m_key private
Definition at line 58 of file clexiconkeychooser.h.
Referenced by CLexiconKeyChooser(), key(), setKey(), and updateKey().
m_modules
QList<CSwordLexiconModuleInfo const *> CLexiconKeyChooser::m_modules private
Definition at line 59 of file clexiconkeychooser.h.
Referenced by refreshContent(), and setModules().
m_widget
CKeyChooserWidget* CLexiconKeyChooser::m_widget private
Definition at line 57 of file clexiconkeychooser.h.
Referenced by CLexiconKeyChooser(), refreshContent(), and updateKey().
The documentation for this class was generated from the following files:
clexiconkeychooser.h
clexiconkeychooser.cpp