BibleTime: BtCopyByReferencesDialog Class Reference
BtCopyByReferencesDialog Class Reference
#include <btcopybyreferencesdialog.h>
Classes
struct Result
Public Member Functions
BtCopyByReferencesDialog (BtModuleTextModel const *model, std::optional< BtQmlInterface::Selection > const &selection, CDisplayWindow *parent)
Result const & result () const noexcept
Private Member Functions
void resetThreshold ()
void retranslateUi ()
Private Attributes
QDialogButtonBox *const m_buttonBox
CKeyChooser * m_firstKeyChooser
QLabel *const m_firstKeyLabel
CKeyChooser * m_lastKeyChooser
QLabel *const m_lastKeyLabel
Result m_result
QLabel *const m_sizeTooLargeLabel
QComboBox *const m_workCombo
QLabel *const m_workLabel
Detailed Description
Definition at line 29 of file btcopybyreferencesdialog.h.
Constructor & Destructor Documentation
BtCopyByReferencesDialog()
BtCopyByReferencesDialog::BtCopyByReferencesDialog (BtModuleTextModel const * model, std::optional< BtQmlInterface::Selection > const & selection, CDisplayWindow * parent)
Definition at line 34 of file btcopybyreferencesdialog.cpp.
References BT_ASSERT, BT_CONNECT, CDisplayWindow::constModules(), CKeyChooser::createInstance(), BtCopyByReferencesDialog::Result::index1, BtCopyByReferencesDialog::Result::index2, BtModuleTextModel::indexToKey(), CDisplayWindow::key(), CKeyChooser::key(), BtCopyByReferencesDialog::Result::key1, BtCopyByReferencesDialog::Result::key2, CKeyChooser::keyChanged(), BtModuleTextModel::keyToIndex(), m_buttonBox, m_firstKeyChooser, m_firstKeyLabel, m_lastKeyChooser, m_lastKeyLabel, m_result, m_sizeTooLargeLabel, m_workCombo, m_workLabel, BtCopyByReferencesDialog::Result::module, message::prepareDialogBox(), resetThreshold(), retranslateUi(), and CKeyChooser::setKey().
Member Function Documentation
resetThreshold()
void BtCopyByReferencesDialog::resetThreshold () private
Definition at line 138 of file btcopybyreferencesdialog.cpp.
References CSwordModuleInfo::Bible, CSwordModuleInfo::Commentary, BtCopyByReferencesDialog::Result::index1, BtCopyByReferencesDialog::Result::index2, m_buttonBox, m_result, m_sizeTooLargeLabel, m_workCombo, and CSwordModuleInfo::type().
Referenced by BtCopyByReferencesDialog().
result()
Result const& BtCopyByReferencesDialog::result () const inline noexcept
Definition at line 50 of file btcopybyreferencesdialog.h.
References m_result.
Referenced by BtModelViewReadDisplay::copyByReferences().
retranslateUi()
void BtCopyByReferencesDialog::retranslateUi () private
Definition at line 130 of file btcopybyreferencesdialog.cpp.
References m_firstKeyLabel, m_lastKeyLabel, m_sizeTooLargeLabel, and m_workLabel.
Referenced by BtCopyByReferencesDialog().
Member Data Documentation
m_buttonBox
QDialogButtonBox* const BtCopyByReferencesDialog::m_buttonBox private
Definition at line 66 of file btcopybyreferencesdialog.h.
Referenced by BtCopyByReferencesDialog(), and resetThreshold().
m_firstKeyChooser
CKeyChooser* BtCopyByReferencesDialog::m_firstKeyChooser private
Definition at line 62 of file btcopybyreferencesdialog.h.
Referenced by BtCopyByReferencesDialog().
m_firstKeyLabel
QLabel* const BtCopyByReferencesDialog::m_firstKeyLabel private
Definition at line 61 of file btcopybyreferencesdialog.h.
Referenced by BtCopyByReferencesDialog(), and retranslateUi().
m_lastKeyChooser
CKeyChooser* BtCopyByReferencesDialog::m_lastKeyChooser private
Definition at line 64 of file btcopybyreferencesdialog.h.
Referenced by BtCopyByReferencesDialog().
m_lastKeyLabel
QLabel* const BtCopyByReferencesDialog::m_lastKeyLabel private
Definition at line 63 of file btcopybyreferencesdialog.h.
Referenced by BtCopyByReferencesDialog(), and retranslateUi().
m_result
Result BtCopyByReferencesDialog::m_result private
Definition at line 68 of file btcopybyreferencesdialog.h.
Referenced by BtCopyByReferencesDialog(), resetThreshold(), and result().
m_sizeTooLargeLabel
QLabel* const BtCopyByReferencesDialog::m_sizeTooLargeLabel private
Definition at line 65 of file btcopybyreferencesdialog.h.
Referenced by BtCopyByReferencesDialog(), resetThreshold(), and retranslateUi().
m_workCombo
QComboBox* const BtCopyByReferencesDialog::m_workCombo private
Definition at line 60 of file btcopybyreferencesdialog.h.
Referenced by BtCopyByReferencesDialog(), and resetThreshold().
m_workLabel
QLabel* const BtCopyByReferencesDialog::m_workLabel private
Definition at line 59 of file btcopybyreferencesdialog.h.
Referenced by BtCopyByReferencesDialog(), and retranslateUi().
The documentation for this class was generated from the following files:
btcopybyreferencesdialog.h
btcopybyreferencesdialog.cpp