BibleTime: BtIndexDialog Class Reference
BtIndexDialog Class Reference final
#include <btindexdialog.h>
Public Member Functions
BtIndexDialog (QWidget *parent=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
Private Slots
void autoDeleteOrphanedIndicesChanged (Qt::CheckState newState)
void createIndices ()
void deleteIndices ()
void slotSwordSetupChanged ()
Private Member Functions
void populateModuleList ()
void retranslateUi ()
Private Attributes
QCheckBox * m_autoDeleteOrphanedIndicesBox
QPushButton * m_closeButton
QPushButton * m_createButton
QPushButton * m_deleteButton
QTreeWidgetItem * m_modsWithIndices
QTreeWidgetItem * m_modsWithoutIndices
QTreeWidget * m_moduleList
Detailed Description
This class encapsulates the "Manage search indices" page of the Bookshelf Manager. It allows for creation and deletion of search indicies for each installed module. It also allows for deletion of orphaned indices.
Definition at line 33 of file btindexdialog.h.
Constructor & Destructor Documentation
BtIndexDialog()
BtIndexDialog::BtIndexDialog (QWidget * parent = nullptr, Qt::WindowFlags f = Qt::WindowFlags())
Definition at line 35 of file btindexdialog.cpp.
References autoDeleteOrphanedIndicesChanged(), BT_CONNECT, btConfig(), createIndices(), deleteIndices(), CSwordBackend::instance(), m_autoDeleteOrphanedIndicesBox, m_closeButton, m_createButton, m_deleteButton, m_moduleList, util::tool::mWidth(), retranslateUi(), CSwordBackend::sigSwordSetupChanged(), and slotSwordSetupChanged().
Member Function Documentation
autoDeleteOrphanedIndicesChanged
void BtIndexDialog::autoDeleteOrphanedIndicesChanged (Qt::CheckState newState) private slot
Definition at line 153 of file btindexdialog.cpp.
References btConfig(), and BtConfigCore::setValue().
Referenced by BtIndexDialog().
createIndices
void BtIndexDialog::createIndices () private slot
Creates indices for selected modules if no index currently exists
Definition at line 160 of file btindexdialog.cpp.
References BtModuleIndexDialog::indexAllModules(), CSwordBackend::instance(), m_modsWithoutIndices, and populateModuleList().
Referenced by BtIndexDialog().
deleteIndices
void BtIndexDialog::deleteIndices () private slot
Deletes indices for selected modules
Definition at line 179 of file btindexdialog.cpp.
References CSwordBackend::instance(), m_modsWithIndices, and populateModuleList().
Referenced by BtIndexDialog().
populateModuleList()
void BtIndexDialog::populateModuleList () private
Populates the module list with installed modules and orphaned indices
Definition at line 94 of file btindexdialog.cpp.
References CSwordBackend::instance(), m_modsWithIndices, m_modsWithoutIndices, m_moduleList, and CSwordBackend::moduleList().
Referenced by createIndices(), deleteIndices(), retranslateUi(), and slotSwordSetupChanged().
retranslateUi()
void BtIndexDialog::retranslateUi () private
Definition at line 129 of file btindexdialog.cpp.
References m_autoDeleteOrphanedIndicesBox, m_closeButton, m_createButton, m_deleteButton, m_moduleList, and populateModuleList().
Referenced by BtIndexDialog().
slotSwordSetupChanged
void BtIndexDialog::slotSwordSetupChanged () private slot
Definition at line 199 of file btindexdialog.cpp.
References populateModuleList().
Referenced by BtIndexDialog().
Member Data Documentation
m_autoDeleteOrphanedIndicesBox
QCheckBox* BtIndexDialog::m_autoDeleteOrphanedIndicesBox private
Definition at line 56 of file btindexdialog.h.
Referenced by BtIndexDialog(), and retranslateUi().
m_closeButton
QPushButton* BtIndexDialog::m_closeButton private
Definition at line 60 of file btindexdialog.h.
Referenced by BtIndexDialog(), and retranslateUi().
m_createButton
QPushButton* BtIndexDialog::m_createButton private
Definition at line 59 of file btindexdialog.h.
Referenced by BtIndexDialog(), and retranslateUi().
m_deleteButton
QPushButton* BtIndexDialog::m_deleteButton private
Definition at line 58 of file btindexdialog.h.
Referenced by BtIndexDialog(), and retranslateUi().
m_modsWithIndices
QTreeWidgetItem* BtIndexDialog::m_modsWithIndices private
Definition at line 62 of file btindexdialog.h.
Referenced by deleteIndices(), and populateModuleList().
m_modsWithoutIndices
QTreeWidgetItem* BtIndexDialog::m_modsWithoutIndices private
Definition at line 63 of file btindexdialog.h.
Referenced by createIndices(), and populateModuleList().
m_moduleList
QTreeWidget* BtIndexDialog::m_moduleList private
Definition at line 57 of file btindexdialog.h.
Referenced by BtIndexDialog(), populateModuleList(), and retranslateUi().
The documentation for this class was generated from the following files:
btindexdialog.h
btindexdialog.cpp