BibleTime: BtBookshelfRemoveFinalPage Class Reference
BtBookshelfRemoveFinalPage Class Reference final
#include <btbookshelfremovefinalpage.h>
Public Member Functions
BtBookshelfRemoveFinalPage (QWidget *parent=nullptr)
void initializePage () final override
bool isComplete () const final override
int nextId () const final override
Public Member Functions inherited from BtBookshelfWizardPage
BtBookshelfWizardPage (QWidget *parent=nullptr)
BtBookshelfWizard & btWizard () const noexcept
Private Member Functions
void retranslateUi ()
Private Attributes
QLabel * m_msgLabel
QVBoxLayout * m_verticalLayout
Detailed Description
Definition at line 25 of file btbookshelfremovefinalpage.h.
Constructor & Destructor Documentation
BtBookshelfRemoveFinalPage()
BtBookshelfRemoveFinalPage::BtBookshelfRemoveFinalPage (QWidget * parent = nullptr)
Definition at line 31 of file btbookshelfremovefinalpage.cpp.
References m_msgLabel, and m_verticalLayout.
Member Function Documentation
initializePage()
void BtBookshelfRemoveFinalPage::initializePage () final override
Definition at line 55 of file btbookshelfremovefinalpage.cpp.
References BtBookshelfWizardPage::btWizard(), CSwordBackend::instance(), retranslateUi(), and CSwordBackend::uninstallModules().
isComplete()
bool BtBookshelfRemoveFinalPage::isComplete () const final override
Definition at line 62 of file btbookshelfremovefinalpage.cpp.
nextId()
int BtBookshelfRemoveFinalPage::nextId () const final override
Definition at line 64 of file btbookshelfremovefinalpage.cpp.
retranslateUi()
void BtBookshelfRemoveFinalPage::retranslateUi () private
Definition at line 52 of file btbookshelfremovefinalpage.cpp.
References m_msgLabel.
Referenced by initializePage().
Member Data Documentation
m_msgLabel
QLabel* BtBookshelfRemoveFinalPage::m_msgLabel private
Definition at line 43 of file btbookshelfremovefinalpage.h.
Referenced by BtBookshelfRemoveFinalPage(), and retranslateUi().
m_verticalLayout
QVBoxLayout* BtBookshelfRemoveFinalPage::m_verticalLayout private
Definition at line 44 of file btbookshelfremovefinalpage.h.
Referenced by BtBookshelfRemoveFinalPage().
The documentation for this class was generated from the following files:
btbookshelfremovefinalpage.h
btbookshelfremovefinalpage.cpp