BibleTime: BtBookshelfTaskPage Class Reference
BtBookshelfTaskPage Class Reference final
#include <btbookshelftaskpage.h>
Public Member Functions
BtBookshelfTaskPage (QWidget *parent=nullptr)
int nextId () const final override
WizardTaskType taskType () const
Public Member Functions inherited from BtBookshelfWizardPage
BtBookshelfWizardPage (QWidget *parent=nullptr)
BtBookshelfWizard & btWizard () const noexcept
Private Member Functions
void retranslateUi ()
bool timeToUpdate () const
Private Attributes
QGroupBox * m_groupBox
QRadioButton * m_installRadioButton
QRadioButton * m_removeRadioButton
QRadioButton * m_updateRadioButton
QVBoxLayout * m_verticalLayout
QLabel * m_warningLabel
Detailed Description
Definition at line 28 of file btbookshelftaskpage.h.
Constructor & Destructor Documentation
BtBookshelfTaskPage()
BtBookshelfTaskPage::BtBookshelfTaskPage (QWidget * parent = nullptr)
Definition at line 27 of file btbookshelftaskpage.cpp.
References m_groupBox, m_installRadioButton, m_removeRadioButton, m_updateRadioButton, m_verticalLayout, m_warningLabel, and retranslateUi().
Member Function Documentation
nextId()
int BtBookshelfTaskPage::nextId () const final override
Definition at line 107 of file btbookshelftaskpage.cpp.
References m_installRadioButton, m_removeRadioButton, m_updateRadioButton, removeWorksPage, sourcesPage, sourcesProgressPage, timeToUpdate(), and updateWorksPage.
retranslateUi()
void BtBookshelfTaskPage::retranslateUi () private
Definition at line 74 of file btbookshelftaskpage.cpp.
References m_groupBox, m_installRadioButton, m_removeRadioButton, m_updateRadioButton, and m_warningLabel.
Referenced by BtBookshelfTaskPage().
taskType()
WizardTaskType BtBookshelfTaskPage::taskType () const
Definition at line 123 of file btbookshelftaskpage.cpp.
References installWorks, m_installRadioButton, m_updateRadioButton, removeWorks, and updateWorks.
Referenced by BtBookshelfWizard::installPath(), BtBookshelfWizard::selectedWorks(), and BtBookshelfWizard::taskType().
timeToUpdate()
bool BtBookshelfTaskPage::timeToUpdate () const private
Definition at line 100 of file btbookshelftaskpage.cpp.
References BtBookshelfWizard::autoUpdateSources(), and CSwordBackend::instance().
Referenced by nextId().
Member Data Documentation
m_groupBox
QGroupBox* BtBookshelfTaskPage::m_groupBox private
Definition at line 47 of file btbookshelftaskpage.h.
Referenced by BtBookshelfTaskPage(), and retranslateUi().
m_installRadioButton
QRadioButton* BtBookshelfTaskPage::m_installRadioButton private
Definition at line 49 of file btbookshelftaskpage.h.
Referenced by BtBookshelfTaskPage(), nextId(), retranslateUi(), and taskType().
m_removeRadioButton
QRadioButton* BtBookshelfTaskPage::m_removeRadioButton private
Definition at line 51 of file btbookshelftaskpage.h.
Referenced by BtBookshelfTaskPage(), nextId(), and retranslateUi().
m_updateRadioButton
QRadioButton* BtBookshelfTaskPage::m_updateRadioButton private
Definition at line 50 of file btbookshelftaskpage.h.
Referenced by BtBookshelfTaskPage(), nextId(), retranslateUi(), and taskType().
m_verticalLayout
QVBoxLayout* BtBookshelfTaskPage::m_verticalLayout private
Definition at line 48 of file btbookshelftaskpage.h.
Referenced by BtBookshelfTaskPage().
m_warningLabel
QLabel* BtBookshelfTaskPage::m_warningLabel private
Definition at line 46 of file btbookshelftaskpage.h.
Referenced by BtBookshelfTaskPage(), and retranslateUi().
The documentation for this class was generated from the following files:
btbookshelftaskpage.h
btbookshelftaskpage.cpp