BibleTime: CKeyChooser Class Reference
CKeyChooser Class Reference abstract
#include <ckeychooser.h>
Public Slots
virtual void updateKey (CSwordKey *key)=0
Signals
void keyChanged (CSwordKey *newKey)
Public Member Functions
BTHistory * history () const
virtual CSwordKey * key ()=0
virtual void refreshContent ()=0
virtual void setKey (CSwordKey *key)=0
virtual void setModules (const BtConstModuleList &modules, bool refresh=true)=0
Static Public Member Functions
static CKeyChooser * createInstance (const BtConstModuleList &modules, BTHistory *history, CSwordKey *key, QWidget *parent)
Protected Member Functions
CKeyChooser (const BtConstModuleList &info, BTHistory *history, QWidget *parent=nullptr)
virtual void handleHistoryMoved (QString const &newKey)=0
Private Attributes
BTHistory *const m_history
Detailed Description
The base class for the KeyChooser. Do not use directly, create a KeyChooser with createInstance , this will create the proper one of the classes that inherit from CKeyChooser
Definition at line 30 of file ckeychooser.h.
Constructor & Destructor Documentation
CKeyChooser()
CKeyChooser::CKeyChooser (const BtConstModuleList & info, BTHistory * history, QWidget * parent = nullptr) protected
Definition at line 29 of file ckeychooser.cpp.
References BT_CONNECT, handleHistoryMoved(), and BTHistory::historyMoved().
Member Function Documentation
createInstance()
CKeyChooser * CKeyChooser::createInstance (const BtConstModuleList & modules, BTHistory * history, CSwordKey * key, QWidget * parent) static
Creates a proper Instance, either CLexiconKeyChooser or CBibleKeyChooser
Parameters
info the CModuleInfo to be represented by the KeyChooser
key if not NULL, the CKey the KeyChooser should be set to
parent the parent of the widget to create
Definition at line 39 of file ckeychooser.cpp.
References CSwordModuleInfo::Bible, BT_ASSERT, CSwordModuleInfo::Commentary, CSwordModuleInfo::GenericBook, key(), and CSwordModuleInfo::Lexicon.
Referenced by BtCopyByReferencesDialog::BtCopyByReferencesDialog(), CBookReadWindow::initView(), CDisplayWindow::initView(), CBookReadWindow::setupMainWindowToolBars(), and CDisplayWindow::setupMainWindowToolBars().
handleHistoryMoved()
virtual void CKeyChooser::handleHistoryMoved (QString const & newKey) protected pure virtual
Implemented in CBookKeyChooser, CBookTreeChooser, CLexiconKeyChooser, and CBibleKeyChooser.
Referenced by CKeyChooser().
history()
BTHistory* CKeyChooser::history () const inline
Returns
the history object of this keychooser.
Definition at line 39 of file ckeychooser.h.
References m_history.
Referenced by CBibleKeyChooser::CBibleKeyChooser(), CBookKeyChooser::CBookKeyChooser(), CBookTreeChooser::CBookTreeChooser(), and CLexiconKeyChooser::CLexiconKeyChooser().
key()
virtual CSwordKey* CKeyChooser::key () pure virtual
Returns
the current CKey.
Implemented in CBookKeyChooser, CBookTreeChooser, CLexiconKeyChooser, and CBibleKeyChooser.
Referenced by BtCopyByReferencesDialog::BtCopyByReferencesDialog(), createInstance(), and CDisplayWindow::setupMainWindowToolBars().
keyChanged
void CKeyChooser::keyChanged (CSwordKey * newKey) signal
is emitted if the CKey was changed by the user
Referenced by BtCopyByReferencesDialog::BtCopyByReferencesDialog(), CBibleKeyChooser::CBibleKeyChooser(), CBookKeyChooser::CBookKeyChooser(), CBookTreeChooser::CBookTreeChooser(), CLexiconKeyChooser::CLexiconKeyChooser(), CBookReadWindow::initConnections(), CDisplayWindow::initConnections(), CBookTreeChooser::itemActivated(), CBibleKeyChooser::setKey(), CLexiconKeyChooser::setKey(), CBookTreeChooser::setKey(), CBookKeyChooser::setKey(), CBookReadWindow::setupMainWindowToolBars(), and CDisplayWindow::setupMainWindowToolBars().
refreshContent()
virtual void CKeyChooser::refreshContent () pure virtual
Refreshes the content of the different key chooser parts.
Implemented in CLexiconKeyChooser, CBibleKeyChooser, CBookKeyChooser, and CBookTreeChooser.
Referenced by CCommentaryReadWindow::reload(), and CBibleReadWindow::reload().
setKey()
virtual void CKeyChooser::setKey (CSwordKey * key) pure virtual
Sets the CKey
Parameters
key the key which the widget should be set to.
Implemented in CBookKeyChooser, CBookTreeChooser, CLexiconKeyChooser, and CBibleKeyChooser.
Referenced by BtCopyByReferencesDialog::BtCopyByReferencesDialog(), CDisplayWindow::lookupKey(), CCommentaryReadWindow::nextBook(), CBibleReadWindow::nextBook(), CCommentaryReadWindow::nextChapter(), CBibleReadWindow::nextChapter(), CLexiconReadWindow::nextEntry(), CCommentaryReadWindow::nextVerse(), CBibleReadWindow::nextVerse(), CCommentaryReadWindow::previousBook(), CBibleReadWindow::previousBook(), CCommentaryReadWindow::previousChapter(), CBibleReadWindow::previousChapter(), CLexiconReadWindow::previousEntry(), CCommentaryReadWindow::previousVerse(), and CBibleReadWindow::previousVerse().
setModules()
virtual void CKeyChooser::setModules (const BtConstModuleList & modules, bool refresh = true) pure virtual
Sets the module of this keychooser and refreshes the comboboxes
Implemented in CLexiconKeyChooser, CBookTreeChooser, CBibleKeyChooser, and CBookKeyChooser.
Referenced by CDisplayWindow::modulesChanged().
updateKey
virtual void CKeyChooser::updateKey (CSwordKey * key) pure virtual slot
Updates the CKey.
Parameters
key the key which the widget should be set to.
Referenced by CBookReadWindow::initConnections(), CBookReadWindow::setupMainWindowToolBars(), and CDisplayWindow::setupMainWindowToolBars().
Member Data Documentation
m_history
BTHistory* const CKeyChooser::m_history private
Definition at line 102 of file ckeychooser.h.
Referenced by history().
The documentation for this class was generated from the following files:
ckeychooser.h
ckeychooser.cpp