BibleTime: InfoDisplay::CInfoDisplay Class Reference
InfoDisplay::CInfoDisplay Class Reference
#include <cinfodisplay.h>
Public Slots
void setInfo (CSwordModuleInfo *module)
void setInfo (Rendering::InfoType const, QString const &data)
Public Member Functions
CInfoDisplay (BibleTime *parent=nullptr)
void setInfo (const QString &renderedData, const QString &lang=QString())
void setInfo (Rendering::ListInfoData const &)
QSize sizeHint () const override
void unsetInfo ()
void updateColors ()
Private Member Functions
void setBrowserFont (const CSwordModuleInfo *const module)
Private Attributes
BibleTime * m_mainWindow
BtTextBrowser * m_textBrowser
Detailed Description
Definition at line 28 of file cinfodisplay.h.
Constructor & Destructor Documentation
CInfoDisplay()
InfoDisplay::CInfoDisplay::CInfoDisplay (BibleTime * parent = nullptr)
Definition at line 39 of file cinfodisplay.cpp.
References BT_CONNECT, btApp, ReferenceManager::decodeHyperlink(), m_textBrowser, setInfo(), and unsetInfo().
Member Function Documentation
setBrowserFont()
void InfoDisplay::CInfoDisplay::setBrowserFont (const CSwordModuleInfo *const module) private
Definition at line 154 of file cinfodisplay.cpp.
References btConfig(), and m_textBrowser.
Referenced by setInfo().
setInfo() [1/4]
void InfoDisplay::CInfoDisplay::setInfo (const QString & renderedData, const QString & lang = QString())
Definition at line 113 of file cinfodisplay.cpp.
References Rendering::formatInfo(), m_textBrowser, and ColorManager::replaceColors().
Referenced by CInfoDisplay(), BibleTime::initView(), setInfo(), setInfo(), setInfo(), BtQmlInterface::timerEvent(), and unsetInfo().
setInfo [2/4]
void InfoDisplay::CInfoDisplay::setInfo (CSwordModuleInfo * module) slot
Definition at line 143 of file cinfodisplay.cpp.
References CSwordModuleInfo::config(), CSwordModuleInfo::Description, CSwordModuleInfo::ModuleVersion, CSwordModuleInfo::name(), setInfo(), and unsetInfo().
setInfo [3/4]
void InfoDisplay::CInfoDisplay::setInfo (Rendering::InfoType const type, QString const & data) slot
Definition at line 121 of file cinfodisplay.cpp.
References setInfo().
setInfo() [4/4]
void InfoDisplay::CInfoDisplay::setInfo (Rendering::ListInfoData const & list)
Definition at line 125 of file cinfodisplay.cpp.
References Rendering::formatInfo(), BibleTime::getCurrentModule(), m_mainWindow, m_textBrowser, setBrowserFont(), and setInfo().
sizeHint()
QSize InfoDisplay::CInfoDisplay::sizeHint () const override
Definition at line 163 of file cinfodisplay.cpp.
unsetInfo()
void InfoDisplay::CInfoDisplay::unsetInfo ()
Definition at line 98 of file cinfodisplay.cpp.
References setInfo().
Referenced by CInfoDisplay(), and setInfo().
updateColors()
void InfoDisplay::CInfoDisplay::updateColors ()
Definition at line 106 of file cinfodisplay.cpp.
References ColorManager::getBackgroundColor(), ColorManager::getForegroundColor(), and m_textBrowser.
Referenced by BibleTime::slotSettingsOptions().
Member Data Documentation
m_mainWindow
BibleTime* InfoDisplay::CInfoDisplay::m_mainWindow private
Definition at line 54 of file cinfodisplay.h.
Referenced by setInfo().
m_textBrowser
BtTextBrowser* InfoDisplay::CInfoDisplay::m_textBrowser private
Definition at line 53 of file cinfodisplay.h.
Referenced by CInfoDisplay(), setBrowserFont(), setInfo(), setInfo(), and updateColors().
The documentation for this class was generated from the following files:
cinfodisplay.h
cinfodisplay.cpp