BibleTime: BtLocaleMgr Namespace Reference
BtLocaleMgr Namespace Reference
Functions
QString defaultLocaleName ()
std::map< sword::SWBuf, sword::SWLocale * > const & internalSwordLocales ()
sword::SWLocale * localeTranslator ()
void setDefaultLocaleName (QString const &localeName)
Detailed Description
An interface replacement for sword::LocaleMgr.
Function Documentation
defaultLocaleName()
QString BtLocaleMgr::defaultLocaleName ()
Definition at line 57 of file btlocalemgr.cpp.
References anonymous_namespace{btlocalemgr.cpp}::btLocaleMgrInstance().
Referenced by CSwordBackend::booknameLanguage(), and CSwordBackend::setBooknameLanguage().
internalSwordLocales()
auto BtLocaleMgr::internalSwordLocales ()
Definition at line 48 of file btlocalemgr.cpp.
References BT_ASSERT, and anonymous_namespace{btlocalemgr.cpp}::btLocaleMgrInstance().
Referenced by CDisplaySettingsPage::initSwordLocaleCombo(), ReferenceManager::parseVerseReference(), and CDisplaySettingsPage::resetLanguage().
localeTranslator()
sword::SWLocale * BtLocaleMgr::localeTranslator ()
Definition at line 54 of file btlocalemgr.cpp.
References anonymous_namespace{btlocalemgr.cpp}::btLocaleMgrInstance().
Referenced by Language::fromAbbrev().
setDefaultLocaleName()
void BtLocaleMgr::setDefaultLocaleName (QString const & localeName)
Definition at line 60 of file btlocalemgr.cpp.
References anonymous_namespace{btlocalemgr.cpp}::btLocaleMgrInstance(), and setDefaultLocaleName().
Referenced by CSwordBackend::setBooknameLanguage(), and setDefaultLocaleName().