BibleTime: anonymous_namespace{btinforendering.cpp} Namespace Reference
anonymous_namespace{btinforendering.cpp} Namespace Reference
Functions
QString decodeAbbreviation (QString const &data)
QString decodeCrossReference (QString const &data, BtConstModuleList const &modules)
QString decodeFootnote (QString const &data)
QString decodeMorph (QString const &data)
QString decodeStrongs (QString const &data)
QString decodeSwordReference (QString const &data)
CSwordModuleInfo * getFirstAvailableStrongsModule (bool wantHebrew)
CSwordModuleInfo * getStrongsModule (bool const wantHebrew)
Function Documentation
decodeAbbreviation()
QString anonymous_namespace{btinforendering.cpp}::decodeAbbreviation (QString const & data)
Todo:
Is "text" correct?
Definition at line 61 of file btinforendering.cpp.
Referenced by Rendering::formatInfo().
decodeCrossReference()
QString anonymous_namespace{btinforendering.cpp}::decodeCrossReference (QString const & data, BtConstModuleList const & modules)
Definition at line 74 of file btinforendering.cpp.
References CSwordModuleInfo::Bible, BT_ASSERT, btConfig(), Rendering::CTextRendering::KeyTreeItem::Settings::CompleteShort, CSwordBackend::findModuleByName(), BtConfig::getDefaultSwordModuleByType(), CSwordBackend::instance(), CSwordModuleInfo::language(), DisplayOptions::lineBreaks, Rendering::CTextRendering::renderKeyTree(), CSwordModuleInfo::textDirectionAsHtml(), CSwordModuleInfo::type(), and DisplayOptions::verseNumbers.
Referenced by Rendering::formatInfo().
decodeFootnote()
QString anonymous_namespace{btinforendering.cpp}::decodeFootnote (QString const & data)
Definition at line 164 of file btinforendering.cpp.
References BT_ASSERT, CSwordBackend::findModuleByName(), FilterOptions::footnotes, CSwordBackend::instance(), CSwordKey::ProcessEntryAttributesOnly, and CSwordBackend::setFilterOptions().
Referenced by Rendering::formatInfo().
decodeMorph()
QString anonymous_namespace{btinforendering.cpp}::decodeMorph (QString const & data)
Todo:
we can't tell here if it's a greek or hebrew moprh code, that's a problem we have to solve
Todo:
: what if the module doesn't exist?
Definition at line 256 of file btinforendering.cpp.
References btConfig(), CSwordModuleInfo::createKey(), CSwordBackend::findModuleByName(), BtConfig::getDefaultSwordModuleByType(), CSwordBackend::instance(), and CSwordModuleInfo::language().
Referenced by Rendering::formatInfo().
decodeStrongs()
QString anonymous_namespace{btinforendering.cpp}::decodeStrongs (QString const & data)
Definition at line 230 of file btinforendering.cpp.
References CSwordModuleInfo::createKey(), getStrongsModule(), and CSwordModuleInfo::language().
Referenced by Rendering::formatInfo().
decodeSwordReference()
QString anonymous_namespace{btinforendering.cpp}::decodeSwordReference (QString const & data)
Definition at line 346 of file btinforendering.cpp.
References CSwordBackend::instance().
Referenced by Rendering::formatInfo().
getFirstAvailableStrongsModule()
CSwordModuleInfo* anonymous_namespace{btinforendering.cpp}::getFirstAvailableStrongsModule (bool wantHebrew)
Definition at line 204 of file btinforendering.cpp.
References CSwordModuleInfo::FeatureGreekDef, CSwordModuleInfo::FeatureHebrewDef, CSwordBackend::instance(), and CSwordModuleInfo::Lexicon.
Referenced by getStrongsModule().
getStrongsModule()
CSwordModuleInfo* anonymous_namespace{btinforendering.cpp}::getStrongsModule (bool const wantHebrew)
Definition at line 221 of file btinforendering.cpp.
References btConfig(), BtConfig::getDefaultSwordModuleByType(), and getFirstAvailableStrongsModule().
Referenced by decodeStrongs().