BibleTime: BtActionCollection Class Reference
BtActionCollection Class Reference
#include <btactioncollection.h>
Classes
class Item
Public Member Functions
QAction & action (QString const &name) const
template<typename T >
T & actionAs (QString const &name) const
void addAction (QString const &name, QAction *const action)
BtActionCollection (QObject *const parent=nullptr)
template<typename F >
void foreachQAction (F &&f) const
QKeySequence getDefaultShortcut (QAction *const action) const
void readShortcuts (QString const &group)
Read shortcuts from config.
void removeAction (QString const &name)
void writeShortcuts (QString const &group) const
Write shortcuts to config.
Private Types
using ActionMap = QMap< QString, Item * >
Private Member Functions
Item * findActionItem (QString const &name) const
Private Attributes
ActionMap m_actions
Detailed Description
Definition at line 24 of file btactioncollection.h.
Member Typedef Documentation
ActionMap
using BtActionCollection::ActionMap = QMap<QString, Item *> private
Definition at line 56 of file btactioncollection.h.
Constructor & Destructor Documentation
BtActionCollection()
BtActionCollection::BtActionCollection (QObject *const parent = nullptr) inline
Definition at line 60 of file btactioncollection.h.
Member Function Documentation
action()
QAction & BtActionCollection::action (QString const & name) const
Definition at line 20 of file btactioncollection.cpp.
References BT_ASSERT, findActionItem(), and BtActionCollection::Item::m_action.
Referenced by addAction(), getDefaultShortcut(), CDisplayWindow::initAction(), CBookReadWindow::initActions(), CBibleReadWindow::initActions(), CCommentaryReadWindow::initActions(), and BibleTime::retranslateUiActions().
actionAs()
template<typename T > T& BtActionCollection::actionAs (QString const & name) const inline
Definition at line 71 of file btactioncollection.h.
addAction()
void BtActionCollection::addAction (QString const & name, QAction *const action)
Definition at line 26 of file btactioncollection.cpp.
References action(), BT_ASSERT, and m_actions.
Referenced by CCommentaryReadWindow::insertKeyboardActions(), CLexiconReadWindow::insertKeyboardActions(), CBibleReadWindow::insertKeyboardActions(), CBookReadWindow::insertKeyboardActions(), CDisplayWindow::insertKeyboardActions(), and BibleTime::insertKeyboardActions().
findActionItem()
BtActionCollection::Item * BtActionCollection::findActionItem (QString const & name) const private
Definition at line 69 of file btactioncollection.cpp.
References m_actions.
Referenced by action(), and readShortcuts().
foreachQAction()
template<typename F > void BtActionCollection::foreachQAction (F && f) const inline
Definition at line 78 of file btactioncollection.h.
getDefaultShortcut()
QKeySequence BtActionCollection::getDefaultShortcut (QAction *const action) const
Definition at line 48 of file btactioncollection.cpp.
References action(), and m_actions.
readShortcuts()
void BtActionCollection::readShortcuts (QString const & group)
Read shortcuts from config.
Read the shortcuts for the given group from the configuration and add them to this action collection.
Parameters
[in] group Shortcut group to read actions from.
Definition at line 55 of file btactioncollection.cpp.
References btConfig(), findActionItem(), and BtConfig::getShortcuts().
Referenced by CAcceleratorSettingsPage::CAcceleratorSettingsPage(), CLexiconReadWindow::initActions(), CBookReadWindow::initActions(), CBibleReadWindow::initActions(), CCommentaryReadWindow::initActions(), CDisplayWindow::initActions(), CLexiconReadWindow::reload(), CCommentaryReadWindow::reload(), CBibleReadWindow::reload(), CDisplayWindow::reload(), and BibleTime::slotSettingsOptions().
removeAction()
void BtActionCollection::removeAction (QString const & name)
Definition at line 40 of file btactioncollection.cpp.
References BT_ASSERT, and m_actions.
writeShortcuts()
void BtActionCollection::writeShortcuts (QString const & group) const
Write shortcuts to config.
Write the shortcuts of this action collection to the given group in the configuration.
Parameters
[in] group Shortcut group to write actions to.
Definition at line 62 of file btactioncollection.cpp.
References btConfig(), m_actions, and BtConfig::setShortcuts().
Referenced by CAcceleratorSettingsPage::save().
Member Data Documentation
m_actions
ActionMap BtActionCollection::m_actions private
Definition at line 112 of file btactioncollection.h.
Referenced by addAction(), findActionItem(), getDefaultShortcut(), removeAction(), and writeShortcuts().
The documentation for this class was generated from the following files:
btactioncollection.h
btactioncollection.cpp