BibleTime: cswordmoduleinfo.h File Reference
cswordmoduleinfo.h File Reference
#include <QObject>
#include <atomic>
#include <memory>
#include <QIcon>
#include <QMetaType>
#include <QString>
#include <QtGlobal>
#include "../cswordmodulesearch.h"
#include "../language.h"
Classes
class CSwordModuleInfo
struct CSwordModuleInfo::FilterOption
Namespaces
namespace sword
Functions
size_t lucene_utf8towcs (wchar_t *, const char *, size_t maxslen)
size_t lucene_wcstoutf8 (char *, const wchar_t *, size_t maxslen)
Function Documentation
lucene_utf8towcs()
size_t lucene_utf8towcs (wchar_t * , const char * , size_t maxslen) extern
Referenced by CSwordModuleInfo::buildIndex(), and CSwordModuleInfo::searchIndexed().
lucene_wcstoutf8()
size_t lucene_wcstoutf8 (char * , const wchar_t * , size_t maxslen) extern
Referenced by CSwordModuleInfo::searchIndexed().