BibleTime: BtTipDialog Class Reference
BtTipDialog Class Reference
#include <bttipdialog.h>
Public Member Functions
BtTipDialog (QWidget *parent=nullptr, Qt::WindowFlags wflags=Qt::Dialog)
Private Member Functions
void displayTip ()
void retranslateUi ()
Private Attributes
QDialogButtonBox * m_buttonBox
QCheckBox * m_showTipsCheckBox
int m_tipNumber
QStringList m_tips
QTextBrowser * m_tipView
Detailed Description
The Tip Of The Day dialog.
Definition at line 30 of file bttipdialog.h.
Constructor & Destructor Documentation
BtTipDialog()
BtTipDialog::BtTipDialog (QWidget * parent = nullptr, Qt::WindowFlags wflags = Qt::Dialog)
Definition at line 75 of file bttipdialog.cpp.
References BT_CONNECT, btConfig(), displayTip(), m_buttonBox, m_showTipsCheckBox, m_tipNumber, m_tips, m_tipView, message::prepareDialogBox(), retranslateUi(), BtConfigCore::setValue(), and BtConfigCore::value().
Member Function Documentation
displayTip()
void BtTipDialog::displayTip () private
Sends the current tip to the web view
Definition at line 200 of file bttipdialog.cpp.
References m_tipNumber, m_tips, and m_tipView.
Referenced by BtTipDialog(), and retranslateUi().
retranslateUi()
void BtTipDialog::retranslateUi () private
Definition at line 134 of file bttipdialog.cpp.
References displayTip(), iconToHtml(), and m_tips.
Referenced by BtTipDialog().
Member Data Documentation
m_buttonBox
QDialogButtonBox* BtTipDialog::m_buttonBox private
Definition at line 46 of file bttipdialog.h.
Referenced by BtTipDialog().
m_showTipsCheckBox
QCheckBox* BtTipDialog::m_showTipsCheckBox private
Definition at line 48 of file bttipdialog.h.
Referenced by BtTipDialog().
m_tipNumber
int BtTipDialog::m_tipNumber private
Definition at line 49 of file bttipdialog.h.
Referenced by BtTipDialog(), and displayTip().
m_tips
QStringList BtTipDialog::m_tips private
Definition at line 50 of file bttipdialog.h.
Referenced by BtTipDialog(), displayTip(), and retranslateUi().
m_tipView
QTextBrowser* BtTipDialog::m_tipView private
Definition at line 47 of file bttipdialog.h.
Referenced by BtTipDialog(), and displayTip().
The documentation for this class was generated from the following files:
bttipdialog.h
bttipdialog.cpp