BibleTime: anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder Class Reference
anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder Class Reference final
Public Member Functions
void addChild (BookmarkItemBase *child)
BookmarkFolder (const QString &name, BookmarkFolder *parent=nullptr)
QList< BookmarkItemBase * > const & children () const noexcept
QList< BookmarkItemBase * > & children () noexcept
BookmarkFolder * deepCopy () const
Qt::ItemFlags flags () const noexcept final override
bool hasDescendant (BookmarkItemBase const *item) const
QIcon const & icon () const noexcept final override
void insertChild (int index, BookmarkItemBase *child)
void insertChildren (int index, QList< BookmarkItemBase * > children)
void removeChild (int index)
~BookmarkFolder () final override
Public Member Functions inherited from anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase
BookmarkItemBase (BookmarkFolder *parent=nullptr)
BookmarkItemBase (const BookmarkItemBase &other)
int index () const
BookmarkFolder * parent () const
void setParent (BookmarkFolder *parent)
void setText (QString const &text)
QString const & text () const
virtual QString toolTip () const
virtual ~BookmarkItemBase ()
Private Attributes
QList< BookmarkItemBase * > m_children
Detailed Description
Definition at line 153 of file btbookmarksmodel.cpp.
Constructor & Destructor Documentation
BookmarkFolder()
BookmarkFolder::BookmarkFolder (const QString & name, BookmarkFolder * parent = nullptr)
Definition at line 426 of file btbookmarksmodel.cpp.
~BookmarkFolder()
anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::~BookmarkFolder () inline final override
Definition at line 158 of file btbookmarksmodel.cpp.
Member Function Documentation
addChild()
void anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::addChild (BookmarkItemBase * child) inline
Children routines.
Definition at line 170 of file btbookmarksmodel.cpp.
References BT_ASSERT, and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::setParent().
Referenced by anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::BookmarkItemBase(), and deepCopy().
children() [1/2]
QList< BookmarkItemBase * > const & anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::children () const inline noexcept
Definition at line 177 of file btbookmarksmodel.cpp.
children() [2/2]
QList< BookmarkItemBase * > & anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::children () inline noexcept
Definition at line 176 of file btbookmarksmodel.cpp.
Referenced by anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::index(), BtBookmarksModelPrivate::saveItem(), and BtBookmarksModelPrivate::serializeTreeFromRootItem().
deepCopy()
BookmarkFolder * BookmarkFolder::deepCopy () const
Creates a deep copy of this item.
Definition at line 444 of file btbookmarksmodel.cpp.
References addChild().
flags()
Qt::ItemFlags anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::flags () const inline final override virtual noexcept
Reimplemented from anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase.
Definition at line 160 of file btbookmarksmodel.cpp.
hasDescendant()
bool BookmarkFolder::hasDescendant (BookmarkItemBase const * item) const
Returns true if the given item is this or a direct or indirect subitem of this.
Definition at line 431 of file btbookmarksmodel.cpp.
icon()
QIcon const & anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::icon () const inline final override virtual noexcept
Reimplemented from anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase.
Definition at line 166 of file btbookmarksmodel.cpp.
insertChild()
void anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::insertChild (int index, BookmarkItemBase * child) inline
Definition at line 180 of file btbookmarksmodel.cpp.
References BT_ASSERT, and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::setParent().
insertChildren()
void anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::insertChildren (int index, QList< BookmarkItemBase * > children) inline
Definition at line 186 of file btbookmarksmodel.cpp.
removeChild()
void anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::removeChild (int index) inline
Definition at line 191 of file btbookmarksmodel.cpp.
Member Data Documentation
m_children
QList<BookmarkItemBase *> anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::m_children private
Definition at line 204 of file btbookmarksmodel.cpp.
The documentation for this class was generated from the following file:
btbookmarksmodel.cpp