BibleTime: Search::CSearchAnalysisDialog Class Reference
Search::CSearchAnalysisDialog Class Reference
#include <csearchanalysisdialog.h>
Public Member Functions
CSearchAnalysisDialog (QString searchedText, CSwordModuleSearch::Results const &results, QWidget *parentDialog=nullptr)
Protected Member Functions
void resizeEvent (QResizeEvent *event) override
void showEvent (QShowEvent *event) override
Private Member Functions
void retranslateUi ()
Private Attributes
CSearchAnalysisScene * m_analysis
CSearchAnalysisView * m_analysisView
QDialogButtonBox * m_buttonBox
bool m_shown = false
Detailed Description
Definition at line 31 of file csearchanalysisdialog.h.
Constructor & Destructor Documentation
CSearchAnalysisDialog()
Search::CSearchAnalysisDialog::CSearchAnalysisDialog (QString searchedText, CSwordModuleSearch::Results const & results, QWidget * parentDialog = nullptr)
Definition at line 35 of file csearchanalysisdialog.cpp.
References BT_CONNECT, m_analysis, m_analysisView, m_buttonBox, message::prepareDialogBox(), retranslateUi(), and Search::CSearchAnalysisScene::saveAsHTML().
Member Function Documentation
resizeEvent()
void Search::CSearchAnalysisDialog::resizeEvent (QResizeEvent * event) override protected
Definition at line 64 of file csearchanalysisdialog.cpp.
References m_analysis, and Search::CSearchAnalysisScene::resizeHeight().
retranslateUi()
void Search::CSearchAnalysisDialog::retranslateUi () private
Definition at line 82 of file csearchanalysisdialog.cpp.
Referenced by CSearchAnalysisDialog().
showEvent()
void Search::CSearchAnalysisDialog::showEvent (QShowEvent * event) override protected
Definition at line 69 of file csearchanalysisdialog.cpp.
References Search::DIALOG_BORDER, Search::DIALOG_HEIGHT, m_analysis, and m_shown.
Member Data Documentation
m_analysis
CSearchAnalysisScene* Search::CSearchAnalysisDialog::m_analysis private
Definition at line 48 of file csearchanalysisdialog.h.
Referenced by CSearchAnalysisDialog(), resizeEvent(), and showEvent().
m_analysisView
CSearchAnalysisView* Search::CSearchAnalysisDialog::m_analysisView private
Definition at line 49 of file csearchanalysisdialog.h.
Referenced by CSearchAnalysisDialog().
m_buttonBox
QDialogButtonBox* Search::CSearchAnalysisDialog::m_buttonBox private
Definition at line 50 of file csearchanalysisdialog.h.
Referenced by CSearchAnalysisDialog().
m_shown
bool Search::CSearchAnalysisDialog::m_shown = false private
Definition at line 51 of file csearchanalysisdialog.h.
Referenced by showEvent().
The documentation for this class was generated from the following files:
csearchanalysisdialog.h
csearchanalysisdialog.cpp