BibleTime: BtIcons Namespace Reference
BtIcons Namespace Reference
Functions
QIcon const & icon_add ()
QIcon const & icon_automatically ()
QIcon const & icon_back ()
QIcon const & icon_bible ()
QIcon const & icon_bible_add ()
QIcon const & icon_bible_locked ()
QIcon const & icon_bible_remove ()
QIcon const & icon_bibletime ()
QIcon const & icon_book ()
QIcon const & icon_book_add ()
QIcon const & icon_book_locked ()
QIcon const & icon_bookmark ()
QIcon const & icon_books ()
QIcon const & icon_calendar ()
QIcon const & icon_calendar_add ()
QIcon const & icon_calendar_locked ()
QIcon const & icon_cascade ()
QIcon const & icon_cascade_auto ()
QIcon const & icon_checkbox ()
QIcon const & icon_commentary ()
QIcon const & icon_commentary_add ()
QIcon const & icon_commentary_locked ()
QIcon const & icon_configure ()
QIcon const & icon_contents2 ()
QIcon const & icon_delete ()
QIcon const & icon_dictionary ()
QIcon const & icon_dictionary_add ()
QIcon const & icon_dictionary_locked ()
QIcon const & icon_displayconfig ()
QIcon const & icon_document_magnifier ()
QIcon const & icon_edit_clear_locationbar ()
QIcon const & icon_edit_copy ()
QIcon const & icon_exit ()
QIcon const & icon_export ()
QIcon const & icon_file_save ()
QIcon const & icon_fileclose ()
QIcon const & icon_find ()
QIcon const & icon_flag ()
QIcon const & icon_folder ()
QIcon const & icon_folder_add ()
QIcon const & icon_folder_open ()
QIcon const & icon_fonts ()
QIcon const & icon_forward ()
QIcon const & icon_import ()
QIcon const & icon_info ()
QIcon const & icon_key_bindings ()
QIcon const & icon_layer_visible_on ()
QIcon const & icon_lexicon ()
QIcon const & icon_lexicon_add ()
QIcon const & icon_lexicon_locked ()
QIcon const & icon_light_bulb ()
QIcon const & icon_lock ()
QIcon const & icon_manual ()
QIcon const & icon_map ()
QIcon const & icon_map_add ()
QIcon const & icon_map_locked ()
QIcon const & icon_null ()
QIcon const & icon_plus ()
QIcon const & icon_pointing_arrow ()
QIcon const & icon_print ()
QIcon const & icon_questionable ()
QIcon const & icon_questionable_add ()
QIcon const & icon_questionable_locked ()
QIcon const & icon_remove ()
QIcon const & icon_speaker ()
QIcon const & icon_startconfig ()
QIcon const & icon_stop ()
QIcon const & icon_swordconfig ()
QIcon const & icon_sync ()
QIcon const & icon_tabbed ()
QIcon const & icon_text_bold ()
QIcon const & icon_text_center ()
QIcon const & icon_text_italic ()
QIcon const & icon_text_leftalign ()
QIcon const & icon_text_rightalign ()
QIcon const & icon_text_under ()
QIcon const & icon_tile ()
QIcon const & icon_tile_auto ()
QIcon const & icon_tile_horiz ()
QIcon const & icon_tile_horiz_auto ()
QIcon const & icon_tile_vert ()
QIcon const & icon_tile_vert_auto ()
QIcon const & icon_trash ()
QIcon const & icon_unlock ()
QIcon const & icon_view_index ()
QIcon const & icon_view_mag ()
QIcon const & icon_view_profile ()
QIcon const & icon_view_tree ()
QIcon const & icon_window_fullscreen ()
Function Documentation
icon_add()
QIcon const & BtIcons::icon_add ()
icon_automatically()
QIcon const & BtIcons::icon_automatically ()
icon_back()
QIcon const & BtIcons::icon_back ()
icon_bible()
QIcon const & BtIcons::icon_bible ()
icon_bible_add()
QIcon const & BtIcons::icon_bible_add ()
icon_bible_locked()
QIcon const & BtIcons::icon_bible_locked ()
icon_bible_remove()
QIcon const & BtIcons::icon_bible_remove ()
icon_bibletime()
QIcon const & BtIcons::icon_bibletime ()
Referenced by BtAboutDialog::BtAboutDialog(), and BtWelcomeDialog::BtWelcomeDialog().
icon_book()
QIcon const & BtIcons::icon_book ()
icon_book_add()
QIcon const & BtIcons::icon_book_add ()
icon_book_locked()
QIcon const & BtIcons::icon_book_locked ()
icon_bookmark()
QIcon const & BtIcons::icon_bookmark ()
icon_books()
QIcon const & BtIcons::icon_books ()
icon_calendar()
QIcon const & BtIcons::icon_calendar ()
icon_calendar_add()
QIcon const & BtIcons::icon_calendar_add ()
icon_calendar_locked()
QIcon const & BtIcons::icon_calendar_locked ()
icon_cascade()
QIcon const & BtIcons::icon_cascade ()
icon_cascade_auto()
QIcon const & BtIcons::icon_cascade_auto ()
icon_checkbox()
QIcon const & BtIcons::icon_checkbox ()
icon_commentary()
QIcon const & BtIcons::icon_commentary ()
icon_commentary_add()
QIcon const & BtIcons::icon_commentary_add ()
icon_commentary_locked()
QIcon const & BtIcons::icon_commentary_locked ()
icon_configure()
QIcon const & BtIcons::icon_configure ()
icon_contents2()
QIcon const & BtIcons::icon_contents2 ()
icon_delete()
QIcon const & BtIcons::icon_delete ()
icon_dictionary()
QIcon const & BtIcons::icon_dictionary ()
icon_dictionary_add()
QIcon const & BtIcons::icon_dictionary_add ()
icon_dictionary_locked()
QIcon const & BtIcons::icon_dictionary_locked ()
icon_displayconfig()
QIcon const & BtIcons::icon_displayconfig ()
icon_document_magnifier()
QIcon const & BtIcons::icon_document_magnifier ()
icon_edit_clear_locationbar()
QIcon const & BtIcons::icon_edit_clear_locationbar ()
icon_edit_copy()
QIcon const & BtIcons::icon_edit_copy ()
icon_exit()
QIcon const & BtIcons::icon_exit ()
icon_export()
QIcon const & BtIcons::icon_export ()
icon_file_save()
QIcon const & BtIcons::icon_file_save ()
icon_fileclose()
QIcon const & BtIcons::icon_fileclose ()
icon_find()
QIcon const & BtIcons::icon_find ()
icon_flag()
QIcon const & BtIcons::icon_flag ()
icon_folder()
QIcon const & BtIcons::icon_folder ()
icon_folder_add()
QIcon const & BtIcons::icon_folder_add ()
icon_folder_open()
QIcon const & BtIcons::icon_folder_open ()
icon_fonts()
QIcon const & BtIcons::icon_fonts ()
icon_forward()
QIcon const & BtIcons::icon_forward ()
icon_import()
QIcon const & BtIcons::icon_import ()
icon_info()
QIcon const & BtIcons::icon_info ()
icon_key_bindings()
QIcon const & BtIcons::icon_key_bindings ()
icon_layer_visible_on()
QIcon const & BtIcons::icon_layer_visible_on ()
icon_lexicon()
QIcon const & BtIcons::icon_lexicon ()
icon_lexicon_add()
QIcon const & BtIcons::icon_lexicon_add ()
icon_lexicon_locked()
QIcon const & BtIcons::icon_lexicon_locked ()
icon_light_bulb()
QIcon const & BtIcons::icon_light_bulb ()
icon_lock()
QIcon const & BtIcons::icon_lock ()
icon_manual()
QIcon const & BtIcons::icon_manual ()
icon_map()
QIcon const & BtIcons::icon_map ()
icon_map_add()
QIcon const & BtIcons::icon_map_add ()
icon_map_locked()
QIcon const & BtIcons::icon_map_locked ()
icon_null()
QIcon const & BtIcons::icon_null ()
icon_plus()
QIcon const & BtIcons::icon_plus ()
icon_pointing_arrow()
QIcon const & BtIcons::icon_pointing_arrow ()
Referenced by CBookmarkIndex::paintEvent().
icon_print()
QIcon const & BtIcons::icon_print ()
icon_questionable()
QIcon const & BtIcons::icon_questionable ()
icon_questionable_add()
QIcon const & BtIcons::icon_questionable_add ()
icon_questionable_locked()
QIcon const & BtIcons::icon_questionable_locked ()
icon_remove()
QIcon const & BtIcons::icon_remove ()
icon_speaker()
QIcon const & BtIcons::icon_speaker ()
icon_startconfig()
QIcon const & BtIcons::icon_startconfig ()
icon_stop()
QIcon const & BtIcons::icon_stop ()
icon_swordconfig()
QIcon const & BtIcons::icon_swordconfig ()
icon_sync()
QIcon const & BtIcons::icon_sync ()
icon_tabbed()
QIcon const & BtIcons::icon_tabbed ()
icon_text_bold()
QIcon const & BtIcons::icon_text_bold ()
icon_text_center()
QIcon const & BtIcons::icon_text_center ()
icon_text_italic()
QIcon const & BtIcons::icon_text_italic ()
icon_text_leftalign()
QIcon const & BtIcons::icon_text_leftalign ()
icon_text_rightalign()
QIcon const & BtIcons::icon_text_rightalign ()
icon_text_under()
QIcon const & BtIcons::icon_text_under ()
icon_tile()
QIcon const & BtIcons::icon_tile ()
icon_tile_auto()
QIcon const & BtIcons::icon_tile_auto ()
icon_tile_horiz()
QIcon const & BtIcons::icon_tile_horiz ()
icon_tile_horiz_auto()
QIcon const & BtIcons::icon_tile_horiz_auto ()
icon_tile_vert()
QIcon const & BtIcons::icon_tile_vert ()
icon_tile_vert_auto()
QIcon const & BtIcons::icon_tile_vert_auto ()
icon_trash()
QIcon const & BtIcons::icon_trash ()
icon_unlock()
QIcon const & BtIcons::icon_unlock ()
icon_view_index()
QIcon const & BtIcons::icon_view_index ()
icon_view_mag()
QIcon const & BtIcons::icon_view_mag ()
icon_view_profile()
QIcon const & BtIcons::icon_view_profile ()
icon_view_tree()
QIcon const & BtIcons::icon_view_tree ()
icon_window_fullscreen()
QIcon const & BtIcons::icon_window_fullscreen ()