BibleTime: BtAboutDialog Class Reference
BtAboutDialog Class Reference
#include <btaboutdialog.h>
Public Member Functions
BtAboutDialog (QWidget *parent=nullptr, Qt::WindowFlags wflags=Qt::Dialog)
Protected Member Functions
void resizeEvent (QResizeEvent *event) override
Private Member Functions
void initTab (QTextBrowser *&tab)
void retranslateBtTab ()
void retranslateContributorsTab ()
void retranslateLicenceTab ()
void retranslateQtTab ()
void retranslateSwordTab ()
void retranslateUi ()
Private Attributes
QTextBrowser * m_bibletimeTab
QDialogButtonBox * m_buttonBox
QTextBrowser * m_contributorsTab
QLabel * m_iconLabel
QTextBrowser * m_licenceTab
QTextBrowser * m_qtTab
QTextBrowser * m_swordTab
QTabWidget * m_tabWidget
QLabel * m_versionLabel
Detailed Description
Definition at line 29 of file btaboutdialog.h.
Constructor & Destructor Documentation
BtAboutDialog()
BtAboutDialog::BtAboutDialog (QWidget * parent = nullptr, Qt::WindowFlags wflags = Qt::Dialog)
Definition at line 65 of file btaboutdialog.cpp.
References BT_CONNECT, initTab(), BtIcons::instance(), m_bibletimeTab, m_buttonBox, m_contributorsTab, m_iconLabel, m_licenceTab, m_qtTab, m_swordTab, m_tabWidget, m_versionLabel, and retranslateUi().
Member Function Documentation
initTab()
void BtAboutDialog::initTab (QTextBrowser *& tab) private
Definition at line 116 of file btaboutdialog.cpp.
References BT_CONNECT, and m_tabWidget.
Referenced by BtAboutDialog().
resizeEvent()
void BtAboutDialog::resizeEvent (QResizeEvent * event) override protected
Definition at line 106 of file btaboutdialog.cpp.
References m_iconLabel, and m_versionLabel.
retranslateBtTab()
void BtAboutDialog::retranslateBtTab () private
Definition at line 145 of file btaboutdialog.cpp.
References m_bibletimeTab, m_tabWidget, MAKE_HTML, and MAKE_LINK_STATIC.
Referenced by retranslateUi().
retranslateContributorsTab()
void BtAboutDialog::retranslateContributorsTab () private
Definition at line 157 of file btaboutdialog.cpp.
References m_contributorsTab, m_tabWidget, MAKE_CONTR, MAKE_CONTR2, MAKE_HTML, and MAKE_LINK_STATIC.
Referenced by retranslateUi().
retranslateLicenceTab()
void BtAboutDialog::retranslateLicenceTab () private
Definition at line 290 of file btaboutdialog.cpp.
References util::directory::getLicenseDir(), m_licenceTab, m_tabWidget, and MAKE_STYLE.
Referenced by retranslateUi().
retranslateQtTab()
void BtAboutDialog::retranslateQtTab () private
Definition at line 273 of file btaboutdialog.cpp.
References m_qtTab, m_tabWidget, MAKE_HTML, and MAKE_LINK.
Referenced by retranslateUi().
retranslateSwordTab()
void BtAboutDialog::retranslateSwordTab () private
Definition at line 253 of file btaboutdialog.cpp.
References m_swordTab, m_tabWidget, MAKE_HTML, and MAKE_LINK_STATIC.
Referenced by retranslateUi().
retranslateUi()
void BtAboutDialog::retranslateUi () private
Definition at line 133 of file btaboutdialog.cpp.
References m_buttonBox, message::prepareDialogBox(), retranslateBtTab(), retranslateContributorsTab(), retranslateLicenceTab(), retranslateQtTab(), and retranslateSwordTab().
Referenced by BtAboutDialog().
Member Data Documentation
m_bibletimeTab
QTextBrowser* BtAboutDialog::m_bibletimeTab private
Definition at line 49 of file btaboutdialog.h.
Referenced by BtAboutDialog(), and retranslateBtTab().
m_buttonBox
QDialogButtonBox* BtAboutDialog::m_buttonBox private
Definition at line 54 of file btaboutdialog.h.
Referenced by BtAboutDialog(), and retranslateUi().
m_contributorsTab
QTextBrowser* BtAboutDialog::m_contributorsTab private
Definition at line 50 of file btaboutdialog.h.
Referenced by BtAboutDialog(), and retranslateContributorsTab().
m_iconLabel
QLabel* BtAboutDialog::m_iconLabel private
Definition at line 55 of file btaboutdialog.h.
Referenced by BtAboutDialog(), and resizeEvent().
m_licenceTab
QTextBrowser* BtAboutDialog::m_licenceTab private
Definition at line 53 of file btaboutdialog.h.
Referenced by BtAboutDialog(), and retranslateLicenceTab().
m_qtTab
QTextBrowser* BtAboutDialog::m_qtTab private
Definition at line 52 of file btaboutdialog.h.
Referenced by BtAboutDialog(), and retranslateQtTab().
m_swordTab
QTextBrowser* BtAboutDialog::m_swordTab private
Definition at line 51 of file btaboutdialog.h.
Referenced by BtAboutDialog(), and retranslateSwordTab().
m_tabWidget
QTabWidget* BtAboutDialog::m_tabWidget private
Definition at line 48 of file btaboutdialog.h.
Referenced by BtAboutDialog(), initTab(), retranslateBtTab(), retranslateContributorsTab(), retranslateLicenceTab(), retranslateQtTab(), and retranslateSwordTab().
m_versionLabel
QLabel* BtAboutDialog::m_versionLabel private
Definition at line 56 of file btaboutdialog.h.
Referenced by BtAboutDialog(), and resizeEvent().
The documentation for this class was generated from the following files:
btaboutdialog.h
btaboutdialog.cpp