BibleTime: BtEditTextPage Class Reference
BtEditTextPage Class Reference final
#include <btedittextpage.h>
Signals
void signalFontChanged (const QFont &)
void signalFontColorChanged (const QColor &)
void signalFontSizeChanged (int)
Public Member Functions
BtEditTextPage (BtEditTextWizard &parent)
void cleanupPage () final override
void initializePage () final override
void setFont (const QFont &font)
void setText (const QString &text)
void setTitle (const QString &text)
QString text () const
bool validatePage () final override
Private Member Functions
void alignmentChanged (int)
void initActions ()
QFont initHtmlFont ()
void retranslateUi ()
void setupToolBar ()
Private Attributes
struct {
QAction * alignCenter
QAction * alignLeft
QAction * alignRight
QAction * bold
QAction * italic
QAction * underline
} m_actions
BtColorWidget * m_fontColorChooser
QFontComboBox * m_fontFamilyComboBox
BtFontSizeWidget * m_fontSizeWidget
bool m_handingFormatChangeFromEditor
QTextEdit * m_htmlTextEdit
QTextEdit * m_plainTextEdit
QFont m_plainTextFont
QString m_text
QToolBar * m_toolBar
BtEditTextWizard & m_wizard
Detailed Description
Definition at line 31 of file btedittextpage.h.
Constructor & Destructor Documentation
BtEditTextPage()
BtEditTextPage::BtEditTextPage (BtEditTextWizard & parent)
Definition at line 42 of file btedittextpage.cpp.
References BT_ASSERT, BT_CONNECT, btConfig(), BtConfigCore::group(), initActions(), m_actions, m_handingFormatChangeFromEditor, m_htmlTextEdit, m_plainTextEdit, m_toolBar, retranslateUi(), BtConfig::session(), setupToolBar(), BtConfigCore::setValue(), signalFontChanged(), signalFontColorChanged(), and signalFontSizeChanged().
Member Function Documentation
alignmentChanged()
void BtEditTextPage::alignmentChanged (int a) private
The text's alignment changed. Enable the right buttons.
Definition at line 265 of file btedittextpage.cpp.
References alignCenter, alignLeft, alignRight, BT_ASSERT, m_actions, and m_handingFormatChangeFromEditor.
cleanupPage()
void BtEditTextPage::cleanupPage () final override
Definition at line 89 of file btedittextpage.cpp.
References m_htmlTextEdit, m_plainTextEdit, and m_text.
initActions()
void BtEditTextPage::initActions () private
Definition at line 169 of file btedittextpage.cpp.
References CResMgr::displaywindows::writeWindow::boldText::accel, CResMgr::displaywindows::writeWindow::italicText::accel, CResMgr::displaywindows::writeWindow::underlinedText::accel, CResMgr::displaywindows::writeWindow::alignLeft::accel, BT_CONNECT, initHtmlFont(), and m_actions.
Referenced by BtEditTextPage().
initHtmlFont()
QFont BtEditTextPage::initHtmlFont () private
Definition at line 161 of file btedittextpage.cpp.
References btConfig(), BtConfigCore::group(), m_htmlTextEdit, and BtConfig::session().
Referenced by initActions(), and initializePage().
initializePage()
void BtEditTextPage::initializePage () final override
Definition at line 96 of file btedittextpage.cpp.
References BtEditTextWizard::htmlMode(), initHtmlFont(), m_htmlTextEdit, m_plainTextEdit, m_plainTextFont, m_text, m_toolBar, and m_wizard.
retranslateUi()
void BtEditTextPage::retranslateUi () private
Definition at line 142 of file btedittextpage.cpp.
References m_actions, m_fontColorChooser, m_fontFamilyComboBox, and m_fontSizeWidget.
Referenced by BtEditTextPage().
setFont()
void BtEditTextPage::setFont (const QFont & font)
Definition at line 138 of file btedittextpage.cpp.
References m_plainTextFont.
Referenced by BtEditTextWizard::setFont().
setText()
void BtEditTextPage::setText (const QString & text)
Definition at line 134 of file btedittextpage.cpp.
References m_text, and text().
Referenced by BtEditTextWizard::setText().
setTitle()
void BtEditTextPage::setTitle (const QString & text)
setupToolBar()
void BtEditTextPage::setupToolBar () private
Definition at line 291 of file btedittextpage.cpp.
References BT_CONNECT, BtColorWidget::changed(), BtFontSizeWidget::fontSizeChanged(), m_actions, m_fontColorChooser, m_fontFamilyComboBox, m_fontSizeWidget, m_handingFormatChangeFromEditor, m_htmlTextEdit, m_toolBar, BtColorWidget::setColor(), BtFontSizeWidget::setFontSize(), signalFontChanged(), signalFontColorChanged(), and signalFontSizeChanged().
Referenced by BtEditTextPage().
signalFontChanged
void BtEditTextPage::signalFontChanged (const QFont &) signal
Referenced by BtEditTextPage(), and setupToolBar().
signalFontColorChanged
void BtEditTextPage::signalFontColorChanged (const QColor &) signal
Referenced by BtEditTextPage(), and setupToolBar().
signalFontSizeChanged
void BtEditTextPage::signalFontSizeChanged (int) signal
Referenced by BtEditTextPage(), and setupToolBar().
text()
QString BtEditTextPage::text () const
Definition at line 130 of file btedittextpage.cpp.
References m_text.
Referenced by setText(), and BtEditTextWizard::text().
validatePage()
bool BtEditTextPage::validatePage () final override
Definition at line 122 of file btedittextpage.cpp.
References m_htmlTextEdit, m_plainTextEdit, and m_text.
Member Data Documentation
alignCenter
QAction* BtEditTextPage::alignCenter
Definition at line 80 of file btedittextpage.h.
Referenced by alignmentChanged().
alignLeft
QAction* BtEditTextPage::alignLeft
Definition at line 79 of file btedittextpage.h.
Referenced by alignmentChanged().
alignRight
QAction* BtEditTextPage::alignRight
Definition at line 81 of file btedittextpage.h.
Referenced by alignmentChanged().
bold
QAction* BtEditTextPage::bold
Definition at line 75 of file btedittextpage.h.
italic
QAction* BtEditTextPage::italic
Definition at line 76 of file btedittextpage.h.
[struct]
struct { ... } BtEditTextPage::m_actions
Referenced by alignmentChanged(), BtEditTextPage(), initActions(), retranslateUi(), and setupToolBar().
m_fontColorChooser
BtColorWidget* BtEditTextPage::m_fontColorChooser private
Definition at line 68 of file btedittextpage.h.
Referenced by retranslateUi(), and setupToolBar().
m_fontFamilyComboBox
QFontComboBox* BtEditTextPage::m_fontFamilyComboBox private
Definition at line 66 of file btedittextpage.h.
Referenced by retranslateUi(), and setupToolBar().
m_fontSizeWidget
BtFontSizeWidget* BtEditTextPage::m_fontSizeWidget private
Definition at line 67 of file btedittextpage.h.
Referenced by retranslateUi(), and setupToolBar().
m_handingFormatChangeFromEditor
bool BtEditTextPage::m_handingFormatChangeFromEditor private
Definition at line 69 of file btedittextpage.h.
Referenced by alignmentChanged(), BtEditTextPage(), and setupToolBar().
m_htmlTextEdit
QTextEdit* BtEditTextPage::m_htmlTextEdit private
Definition at line 64 of file btedittextpage.h.
Referenced by BtEditTextPage(), cleanupPage(), initHtmlFont(), initializePage(), setupToolBar(), and validatePage().
m_plainTextEdit
QTextEdit* BtEditTextPage::m_plainTextEdit private
Definition at line 63 of file btedittextpage.h.
Referenced by BtEditTextPage(), cleanupPage(), initializePage(), and validatePage().
m_plainTextFont
QFont BtEditTextPage::m_plainTextFont private
Definition at line 71 of file btedittextpage.h.
Referenced by initializePage(), and setFont().
m_text
QString BtEditTextPage::m_text private
Definition at line 72 of file btedittextpage.h.
Referenced by cleanupPage(), initializePage(), setText(), text(), and validatePage().
m_toolBar
QToolBar* BtEditTextPage::m_toolBar private
Definition at line 65 of file btedittextpage.h.
Referenced by BtEditTextPage(), initializePage(), and setupToolBar().
m_wizard
BtEditTextWizard& BtEditTextPage::m_wizard private
Definition at line 62 of file btedittextpage.h.
Referenced by initializePage().
underline
QAction* BtEditTextPage::underline
Definition at line 77 of file btedittextpage.h.
The documentation for this class was generated from the following files:
btedittextpage.h
btedittextpage.cpp