BibleTime: CSwordModuleInfo Class Reference
CSwordModuleInfo Class Reference abstract
#include <cswordmoduleinfo.h>
Classes
struct FilterOption
Public Types
enum class Category {
Bibles = 0x01 , Commentaries = 0x02 , Books = 0x04 , Lexicons = 0x08 ,
Glossaries = 0x10 , DailyDevotionals = 0x20 , MapsAndImages = 0x40 , Questionable = 0x80
}
enum ConfigEntry {
AboutInformation , AbsoluteDataPath , CipherKey , DataPath ,
Description , ModuleVersion , MinimumSwordVersion , TextDir ,
DisplayLevel , GlossaryFrom , GlossaryTo , DistributionLicense ,
DistributionSource , DistributionNotes , TextSource , CopyrightNotes ,
CopyrightHolder , CopyrightDate , CopyrightContactName , CopyrightContactAddress ,
CopyrightContactEmail , Markup
}
enum Feature {
FeatureStrongsNumbers = 1 , FeatureGreekDef = 1 << 1 , FeatureHebrewDef = 1 << 2 , FeatureGreekParse = 1 << 3 ,
FeatureHebrewParse = 1 << 4 , FeatureDailyDevotion = 1 << 5 , FeatureGlossary = 1 << 6 , FeatureImages = 1 << 7 ,
FeatureNoParagraphs = 1 << 8
}
enum ModuleType { Bible , Commentary , Lexicon , GenericBook }
enum TextDirection { LeftToRight , RightToLeft }
enum UnlockErrorCode { noError , wrongUnlockKey , notLocked , noPermission }
Public Slots
void cancelIndexing (std::memory_order const memoryOrder=std::memory_order_relaxed) noexcept
Signals
void hasIndexChanged (bool hasIndex)
void hiddenChanged (bool hidden)
void indexingFinished ()
void indexingProgress (int)
void unlockedChanged (bool unlocked)
Public Member Functions
QString aboutText () const
void buildIndex ()
CSwordModuleInfo::Category category () const
QString config (const CSwordModuleInfo::ConfigEntry entry) const
virtual CSwordKey * createKey () const =0
CSwordModuleInfo (CSwordModuleInfo &&)=delete
CSwordModuleInfo (CSwordModuleInfo const &)=delete
void deleteIndex ()
QString getModuleBaseIndexLocation () const
QString getModuleStandardIndexLocation () const
QString getUnlockInfo ()
std::shared_ptr< Language const > glossaryTargetlanguage () const
bool has (CSwordModuleInfo::Feature const feature) const noexcept
bool has (CSwordModuleInfo::FilterOption const &) const
bool hasIndex () const
bool hasVersion () const
::qint64 indexSize () const
bool isEncrypted () const
bool isHidden () const
bool isLocked () const
bool isUnicode () const noexcept
virtual bool isWritable () const
std::shared_ptr< Language const > language () const
sword::SWVersion minimumSwordVersion () const
QIcon moduleIcon () const
QString const & name () const
CSwordModuleInfo & operator= (CSwordModuleInfo &&)=delete
CSwordModuleInfo & operator= (CSwordModuleInfo const &)=delete
CSwordModuleSearch::ModuleResultList searchIndexed (QString const &searchedText, sword::ListKey const &scope) const
bool setHidden (bool hide)
virtual bool snap () const
sword::SWModule & swordModule () const
CSwordModuleInfo::TextDirection textDirection () const
char const * textDirectionAsHtml () const
ModuleType type () const
bool unlock (const QString &unlockKey)
bool unlockKeyIsValid () const
void write (CSwordKey *key, const QString &newText)
Static Public Member Functions
static QIcon const & categoryIcon (CSwordModuleInfo::Category category)
static QIcon const & categoryIconAdd (CSwordModuleInfo::Category category)
static QIcon const & categoryIconAdd (CSwordModuleInfo::ModuleType type)
static QIcon const & categoryIconLocked (CSwordModuleInfo::Category category)
static QString categoryName (const CSwordModuleInfo::Category &category)
static void deleteIndexForModule (const QString &name)
static QString getGlobalBaseIndexLocation ()
Static Public Attributes
static FilterOption const footnotes
static FilterOption const greekAccents
static FilterOption const headings
static FilterOption const hebrewCantillation
static FilterOption const hebrewPoints
static FilterOption const lemmas
static FilterOption const morphSegmentation
static FilterOption const morphTags
static FilterOption const redLetterWords
static FilterOption const scriptureReferences
static FilterOption const strongNumbers
static FilterOption const textualVariants
Protected Member Functions
CSwordBackend & backend () const
CSwordModuleInfo (sword::SWModule &module, CSwordBackend &backend, ModuleType type)
QString getFormattedConfigEntry (const QString &name) const
QString getSimpleConfigEntry (const QString &name) const
bool hasImportantFilterOption () const
void setImportantFilterOptions (bool enable)
Private Attributes
CSwordBackend & m_backend
CSwordModuleInfo::Category const m_cachedCategory
Features const m_cachedFeatures
std::shared_ptr< Language const > const m_cachedGlossaryTargetLanguage
bool const m_cachedHasVersion
std::shared_ptr< Language const > const m_cachedLanguage
QString const m_cachedName
std::atomic< bool > m_cancelIndexing
bool m_hidden
sword::SWModule & m_swordModule
ModuleType const m_type
Detailed Description
Base class for Sword modules. This is the base class for all Sword modules. Every class handling a special Sword module type does inherit from this class.
Author
The BibleTime team
Version
Id
cswordmoduleinfo.h,v 1.83 2007/02/04 23:12:32 joachim Exp
Definition at line 48 of file cswordmoduleinfo.h.
Member Enumeration Documentation
Category
enum class CSwordModuleInfo::Category strong
Enumerator
Bibles
Commentaries
Books
Lexicons
Glossaries
DailyDevotionals
MapsAndImages
Questionable
Definition at line 144 of file cswordmoduleinfo.h.
ConfigEntry
enum CSwordModuleInfo::ConfigEntry
Enumerator
AboutInformation
The about information of a module which is stored in the config file
AbsoluteDataPath
The absolute data path stored in the config object
CipherKey
The cipher key which was used to unlock the module. Not necessarily set.
DataPath
The relative path. See AbsoluteDataPath
Description
The module description stored in the config file
ModuleVersion
The module's version.
MinimumSwordVersion
The required Sword Version of this module. Otherwise some things may not work (compression etc.).
TextDir
The text direction
DisplayLevel
Mostly used for books. Gives the level which should contain the connected entries.
GlossaryFrom
lamguage from which the Glosaary tramslates
GlossaryTo
lamguages to which the glossary maps to
DistributionLicense
DistributionSource
DistributionNotes
TextSource
CopyrightNotes
CopyrightHolder
CopyrightDate
CopyrightContactName
CopyrightContactAddress
CopyrightContactEmail
Markup
The markup of this module
Definition at line 106 of file cswordmoduleinfo.h.
Feature
enum CSwordModuleInfo::Feature
Enumerator
FeatureStrongsNumbers
FeatureGreekDef
FeatureHebrewDef
FeatureGreekParse
FeatureHebrewParse
FeatureDailyDevotion
FeatureGlossary
FeatureImages
FeatureNoParagraphs
Definition at line 131 of file cswordmoduleinfo.h.
ModuleType
enum CSwordModuleInfo::ModuleType
The module type.
Enumerator
Bible
Bible module
Commentary
Commentary module
Lexicon
Lexicon module
GenericBook
Generic book module
Definition at line 86 of file cswordmoduleinfo.h.
TextDirection
enum CSwordModuleInfo::TextDirection
The text direction of a module
Enumerator
LeftToRight
Left to right text direction, the default setting
RightToLeft
Right to left text directin, e.g. for hebrew
Definition at line 80 of file cswordmoduleinfo.h.
UnlockErrorCode
enum CSwordModuleInfo::UnlockErrorCode
This enum is used to give back an error code after unlocking the module BibleTime stores the unlock key not in the module's config file but in BibleTime's configuration file.
Enumerator
noError
No error occured, everything worked ok. The key was written to the BibleTime config
wrongUnlockKey
The wrong key was used. Module is not unlocked
notLocked
The module was not locked so it can't be unlocked
noPermission
The key was not written to config because we have no permissions
Definition at line 99 of file cswordmoduleinfo.h.
Constructor & Destructor Documentation
CSwordModuleInfo() [1/3]
CSwordModuleInfo::CSwordModuleInfo (CSwordModuleInfo &&) delete
CSwordModuleInfo() [2/3]
CSwordModuleInfo::CSwordModuleInfo (CSwordModuleInfo const &) delete
CSwordModuleInfo() [3/3]
CSwordModuleInfo::CSwordModuleInfo (sword::SWModule & module, CSwordBackend & backend, ModuleType type) protected
Todo:
if this is the case, can we use the module at all?
Definition at line 219 of file cswordmoduleinfo.cpp.
References btConfig(), m_cachedHasVersion, m_cachedName, m_hidden, minimumSwordVersion(), and BtConfigCore::value().
Member Function Documentation
aboutText()
QString CSwordModuleInfo::aboutText () const
The about text which belongs to this module.
Definition at line 908 of file cswordmoduleinfo.cpp.
References AboutInformation, AbsoluteDataPath, CipherKey, config(), CopyrightContactAddress, CopyrightContactEmail, CopyrightContactName, CopyrightDate, CopyrightHolder, CopyrightNotes, DistributionLicense, DistributionNotes, DistributionSource, footnotes, greekAccents, has(), headings, hebrewCantillation, hebrewPoints, isEncrypted(), isWritable(), lemmas, m_cachedCategory, m_cachedHasVersion, m_cachedLanguage, m_swordModule, ModuleVersion, morphSegmentation, morphTags, Questionable, redLetterWords, scriptureReferences, strongNumbers, TextSource, and textualVariants.
Referenced by BTAboutModuleDialog::retranslateUi().
backend()
CSwordBackend & CSwordModuleInfo::backend () const inline protected
Definition at line 403 of file cswordmoduleinfo.h.
References m_backend.
Referenced by CSwordBibleModuleInfo::books().
buildIndex()
void CSwordModuleInfo::buildIndex ()
Builds a search index for this module
Exceptions
when unsuccessful
Definition at line 402 of file cswordmoduleinfo.cpp.
References BT_ASSERT, BT_MAX_LUCENE_FIELD_LENGTH, btConfig(), CANCEL_INDEXING, config(), deleteIndex(), getGlobalBaseIndexLocation(), getModuleBaseIndexLocation(), getModuleStandardIndexLocation(), hasImportantFilterOption(), hasIndexChanged(), CSwordVerseKey::index(), INDEX_VERSION, indexingProgress(), Lexicon, CSwordBibleModuleInfo::lowerBound(), lucene_utf8towcs(), m_backend, m_cachedHasVersion, m_cancelIndexing, m_swordModule, m_type, ModuleVersion, morphSegmentation, redLetterWords, scriptureReferences, CSwordBackend::setFilterOptions(), setImportantFilterOptions(), CSwordBackend::setOption(), U, and CSwordBibleModuleInfo::upperBound().
cancelIndexing
void CSwordModuleInfo::cancelIndexing (std::memory_order const memoryOrder = std::memory_order_relaxed) inline slot noexcept
Definition at line 393 of file cswordmoduleinfo.h.
References m_cancelIndexing.
category()
CSwordModuleInfo::Category CSwordModuleInfo::category () const inline
Returns
the category of this module.
Definition at line 341 of file cswordmoduleinfo.h.
References m_cachedCategory.
Referenced by BtModuleChooserMenu::buttonIcon(), categoryName(), and BtBookshelfModel::data().
categoryIcon()
static QIcon const & CSwordModuleInfo::categoryIcon (CSwordModuleInfo::Category category) static
Parameters
[in] category The category whose icon to return.
Returns
an ("unlocked") icon for the given category.
Referenced by BtModuleChooserMenu::buttonIcon(), BookshelfModel::CategoryItem::data(), and moduleIcon().
categoryIconAdd() [1/2]
static QIcon const & CSwordModuleInfo::categoryIconAdd (CSwordModuleInfo::Category category) static
Parameters
[in] category The category whose icon to return.
Returns
an "add" icon for the given category.
Referenced by BtModuleChooserMenu::buttonIcon(), and categoryIconAdd().
categoryIconAdd() [2/2]
QIcon const & CSwordModuleInfo::categoryIconAdd (CSwordModuleInfo::ModuleType type) static
Returns an "add" category icon based on a module type.
Parameters
[in] module The module whose category icon to return.
Definition at line 1063 of file cswordmoduleinfo.cpp.
References Bible, Bibles, Books, BT_ASSERT, categoryIconAdd(), Commentaries, Commentary, GenericBook, Lexicon, Lexicons, and type().
categoryIconLocked()
static QIcon const & CSwordModuleInfo::categoryIconLocked (CSwordModuleInfo::Category category) static
Parameters
[in] category The category whose icon to return.
Returns
a "locked" icon for the given category.
Referenced by moduleIcon().
categoryName()
QString CSwordModuleInfo::categoryName (const CSwordModuleInfo::Category & category) static
Returns a translated name for the given category.
Parameters
[in] module The category whose translated name to return.
Definition at line 1077 of file cswordmoduleinfo.cpp.
References Bibles, Books, category(), Commentaries, DailyDevotionals, Glossaries, Lexicons, MapsAndImages, and Questionable.
Referenced by BookshelfModel::CategoryItem::data().
config()
QString CSwordModuleInfo::config (const CSwordModuleInfo::ConfigEntry entry) const
Returns the config entry which is pecified by the parameter.
Todo:
is this needed?
Definition at line 741 of file cswordmoduleinfo.cpp.
References AboutInformation, AbsoluteDataPath, btConfig(), CipherKey, CopyrightContactAddress, CopyrightContactEmail, CopyrightContactName, CopyrightDate, CopyrightHolder, CopyrightNotes, DataPath, Description, DisplayLevel, DistributionLicense, DistributionNotes, DistributionSource, GenericBook, getFormattedConfigEntry(), BtConfig::getModuleEncryptionKey(), getSimpleConfigEntry(), Glossaries, GlossaryFrom, GlossaryTo, Lexicon, m_cachedCategory, m_cachedName, m_swordModule, m_type, Markup, MinimumSwordVersion, ModuleVersion, TextDir, and TextSource.
Referenced by aboutText(), buildIndex(), BtBookshelfModel::data(), CSwordLexiconModuleInfo::entries(), anonymous_namespace{btbookshelfworkspage.cpp}::filter(), hasIndex(), isEncrypted(), minimumSwordVersion(), BibleTime::moduleUnlock(), BtInstallThread::removeModule(), BtBookmarksModelPrivate::saveItem(), InfoDisplay::CInfoDisplay::setInfo(), and textDirection().
createKey()
virtual CSwordKey * CSwordModuleInfo::createKey () const pure virtual
Implemented in CSwordBibleModuleInfo, CSwordBookModuleInfo, and CSwordLexiconModuleInfo.
Referenced by searchIndexed().
deleteIndex()
void CSwordModuleInfo::deleteIndex ()
Removes the search index for this module (rm -rf).
Definition at line 656 of file cswordmoduleinfo.cpp.
References deleteIndexForModule(), hasIndexChanged(), and m_cachedName.
Referenced by buildIndex().
deleteIndexForModule()
void CSwordModuleInfo::deleteIndexForModule (const QString & name) static
Removes search index for a module, even if the module is not there any more.
Parameters
[in] name name of the module.
Definition at line 661 of file cswordmoduleinfo.cpp.
References getGlobalBaseIndexLocation(), and name().
Referenced by deleteIndex(), and CSwordBackend::deleteOrphanedIndices().
getFormattedConfigEntry()
QString CSwordModuleInfo::getFormattedConfigEntry (const QString & name) const protected
Note
See http://www.crosswire.org/wiki/DevTools:conf_Files#Localization
Definition at line 1107 of file cswordmoduleinfo.cpp.
References CSwordBackend::instance(), isUnicode(), m_swordModule, and name().
Referenced by config().
getGlobalBaseIndexLocation()
QString CSwordModuleInfo::getGlobalBaseIndexLocation () static
Returns the base directory for search indices
Definition at line 337 of file cswordmoduleinfo.cpp.
References util::directory::getUserIndexDir().
Referenced by buildIndex(), deleteIndexForModule(), CSwordBackend::deleteOrphanedIndices(), and getModuleBaseIndexLocation().
getModuleBaseIndexLocation()
QString CSwordModuleInfo::getModuleBaseIndexLocation () const
Returns
the path to this module's index base dir
Definition at line 341 of file cswordmoduleinfo.cpp.
References getGlobalBaseIndexLocation(), and m_cachedName.
Referenced by buildIndex(), getModuleStandardIndexLocation(), hasIndex(), and indexSize().
getModuleStandardIndexLocation()
QString CSwordModuleInfo::getModuleStandardIndexLocation () const
Returns
the path to this module's standard index
Definition at line 346 of file cswordmoduleinfo.cpp.
References getModuleBaseIndexLocation().
Referenced by buildIndex(), hasIndex(), and searchIndexed().
getSimpleConfigEntry()
QString CSwordModuleInfo::getSimpleConfigEntry (const QString & name) const protected
Definition at line 1100 of file cswordmoduleinfo.cpp.
References isUnicode(), m_swordModule, and name().
Referenced by config().
getUnlockInfo()
QString CSwordModuleInfo::getUnlockInfo ()
Gets the "UnlockInfo" tag value from the module's config file
Returns
Unlock information string (may be empty if not specified for module)
Definition at line 333 of file cswordmoduleinfo.cpp.
References m_swordModule.
Referenced by BibleTime::moduleUnlock().
glossaryTargetlanguage()
std::shared_ptr< Language const > CSwordModuleInfo::glossaryTargetlanguage () const inline
Returns
the target language of the glossary, if this is a glossary.
Definition at line 318 of file cswordmoduleinfo.h.
References m_cachedGlossaryTargetLanguage.
has() [1/2]
bool CSwordModuleInfo::has (CSwordModuleInfo::Feature const feature) const inline noexcept
Returns
whether the module supports the feature given as parameter.
Definition at line 294 of file cswordmoduleinfo.h.
References m_cachedFeatures.
Referenced by aboutText(), and hasImportantFilterOption().
has() [2/2]
bool CSwordModuleInfo::has (CSwordModuleInfo::FilterOption const & option) const
Todo:
This is a BAD workaround to see if the filter is GBF, OSIS or ThML!
Definition at line 864 of file cswordmoduleinfo.cpp.
References CSwordModuleInfo::FilterOption::configOptionName, and m_swordModule.
hasImportantFilterOption()
bool CSwordModuleInfo::hasImportantFilterOption () const protected
Definition at line 384 of file cswordmoduleinfo.cpp.
References Bible, footnotes, has(), headings, m_type, morphTags, and strongNumbers.
Referenced by buildIndex().
hasIndex()
bool CSwordModuleInfo::hasIndex () const
Returns
true if the module's index has been built.
Definition at line 351 of file cswordmoduleinfo.cpp.
References config(), getModuleBaseIndexLocation(), getModuleStandardIndexLocation(), INDEX_VERSION, m_cachedHasVersion, m_cachedName, and ModuleVersion.
hasIndexChanged
void CSwordModuleInfo::hasIndexChanged (bool hasIndex) signal
Referenced by BtBookshelfModel::addModule(), buildIndex(), deleteIndex(), and BtBookshelfModel::removeModule().
hasVersion()
bool CSwordModuleInfo::hasVersion () const inline
Return values
true if this module has a version number
false if it doesn't have a version number
Definition at line 230 of file cswordmoduleinfo.h.
References m_cachedHasVersion.
hiddenChanged
void CSwordModuleInfo::hiddenChanged (bool hidden) signal
Referenced by BtBookshelfModel::addModule(), BtBookshelfModel::removeModule(), and setHidden().
indexingFinished
void CSwordModuleInfo::indexingFinished () signal
Referenced by BtModuleIndexDialog::indexAllModulesPrivate().
indexingProgress
void CSwordModuleInfo::indexingProgress (int) signal
Referenced by buildIndex(), and BtModuleIndexDialog::indexAllModulesPrivate().
indexSize()
qint64 CSwordModuleInfo::indexSize () const
Returns
index size
Definition at line 666 of file cswordmoduleinfo.cpp.
References getModuleBaseIndexLocation().
isEncrypted()
bool CSwordModuleInfo::isEncrypted () const
This function does return true if the data files of the module are encrypted by the module author (the on who made the module) no matter if it's locked or not.
Returns
True if this module is encryped
If we have the CipherKey entry the module is encrypted but not necessarily locked
Definition at line 291 of file cswordmoduleinfo.cpp.
References config(), CSwordBackend::getConfig(), m_backend, and m_cachedName.
Referenced by aboutText(), isLocked(), and unlock().
isHidden()
bool CSwordModuleInfo::isHidden () const inline
Returns true if this module is hidden (not to be shown with other modules in certain views).
Definition at line 329 of file cswordmoduleinfo.h.
References m_hidden.
isLocked()
bool CSwordModuleInfo::isLocked () const
This function returns true if this module is locked (encrypted + correct cipher key), otherwise return false.
Returns
True if this module is locked, i.e. encrypted but without a key set
Definition at line 284 of file cswordmoduleinfo.cpp.
References isEncrypted(), and unlockKeyIsValid().
Referenced by BtBookshelfDockWidget::initMenus(), moduleIcon(), BibleTime::moduleUnlock(), and BtModuleChooserMenu::newAction().
isUnicode()
bool CSwordModuleInfo::isUnicode () const noexcept
Returns true if this module is Unicode encoded. False if the charset is iso8859-1. Protected because it should not be used outside of the CSword*ModuleInfo classes.
Definition at line 1022 of file cswordmoduleinfo.cpp.
References m_swordModule.
Referenced by CSwordLexiconModuleInfo::entries(), getFormattedConfigEntry(), CSwordTreeKey::getLocalNameUnicode(), getSimpleConfigEntry(), CSwordLDKey::key(), CSwordTreeKey::key(), CSwordTreeKey::setKey(), CSwordLDKey::setKey(), unlockKeyIsValid(), and write().
isWritable()
virtual bool CSwordModuleInfo::isWritable () const inline virtual
Returns
whether this module may be written to.
Reimplemented in CSwordCommentaryModuleInfo.
Definition at line 324 of file cswordmoduleinfo.h.
Referenced by aboutText().
language()
std::shared_ptr< Language const > CSwordModuleInfo::language () const inline
Returns
the language of the module.
Definition at line 314 of file cswordmoduleinfo.h.
References m_cachedLanguage.
Referenced by anonymous_namespace{btinforendering.cpp}::decodeCrossReference(), anonymous_namespace{btbookshelfworkspage.cpp}::filter(), and Rendering::CTextRendering::finishText().
minimumSwordVersion()
sword::SWVersion CSwordModuleInfo::minimumSwordVersion () const
Returns the required Sword version for this module. Returns -1 if no special Sword version is required.
Definition at line 736 of file cswordmoduleinfo.cpp.
References config(), and MinimumSwordVersion.
Referenced by CSwordModuleInfo().
moduleIcon()
QIcon CSwordModuleInfo::moduleIcon () const
Returns
an icon for this module based on it's isLocked() status.
Definition at line 1025 of file cswordmoduleinfo.cpp.
References categoryIcon(), categoryIconLocked(), isLocked(), and m_cachedCategory.
Referenced by CDisplayWindow::slotAddModule(), CDisplayWindow::slotReplaceModule(), and BtTextWindowHeaderWidget::updateWidget().
name()
QString const & CSwordModuleInfo::name () const inline
Note
The Sword library takes care of the duplicate names: _n is added after each duplicate.
Returns
The name of this module.
Definition at line 283 of file cswordmoduleinfo.h.
References m_cachedName.
Referenced by BtBookshelfModel::data(), deleteIndexForModule(), ReferenceManager::encodeHyperlink(), CSwordLexiconModuleInfo::entries(), Rendering::CDisplayRendering::entryLink(), anonymous_namespace{btbookshelfworkspage.cpp}::filter(), getFormattedConfigEntry(), BtBookshelfModel::getModule(), getSimpleConfigEntry(), BtBookshelfDockWidget::initMenus(), Search::CSearchResultView::mimeData(), BibleTime::moduleUnlock(), BtInstallThread::removeModule(), Filters::TeiToHtml::renderReference(), Filters::TeiToHtml::renderTargetReference(), BTAboutModuleDialog::retranslateUi(), BtConfig::setDefaultSwordModuleByType(), InfoDisplay::CInfoDisplay::setInfo(), CDisplayWindow::slotAddModule(), CDisplayWindow::slotReplaceModule(), BtModelViewReadDisplay::text(), BtModuleChooserButton::updateMenu(), and BtTextWindowHeaderWidget::updateWidget().
operator=() [1/2]
CSwordModuleInfo & CSwordModuleInfo::operator= (CSwordModuleInfo &&) delete
operator=() [2/2]
CSwordModuleInfo & CSwordModuleInfo::operator= (CSwordModuleInfo const &) delete
searchIndexed()
CSwordModuleSearch::ModuleResultList CSwordModuleInfo::searchIndexed (QString const & searchedText, sword::ListKey const & scope) const
This function uses CLucene to perform and index based search.
Returns
the result
Exceptions
on error
Definition at line 672 of file cswordmoduleinfo.cpp.
References BT_ASSERT, BT_MAX_LUCENE_FIELD_LENGTH, createKey(), getModuleStandardIndexLocation(), lucene_utf8towcs(), lucene_wcstoutf8(), and m_swordModule.
setHidden()
bool CSwordModuleInfo::setHidden (bool hide)
Shows or hides the module.
Parameters
hide Whether the module should be hidden.
Returns
whether the hidden state was changed.
Definition at line 1134 of file cswordmoduleinfo.cpp.
References BT_ASSERT, btConfig(), hiddenChanged(), m_cachedName, m_hidden, and BtConfigCore::setValue().
setImportantFilterOptions()
void CSwordModuleInfo::setImportantFilterOptions (bool enable) inline protected
Definition at line 395 of file cswordmoduleinfo.cpp.
References footnotes, headings, m_backend, morphTags, CSwordBackend::setOption(), and strongNumbers.
Referenced by buildIndex().
snap()
virtual bool CSwordModuleInfo::snap () const inline virtual
Snaps to the closest entry in the module if the current key is not present in the data files.
Reimplemented in CSwordLexiconModuleInfo.
Definition at line 289 of file cswordmoduleinfo.h.
Referenced by CSwordKey::renderedText(), and CSwordLDKey::setKey().
swordModule()
sword::SWModule & CSwordModuleInfo::swordModule () const inline
Returns the module object so all objects can access the original Sword module.
Definition at line 187 of file cswordmoduleinfo.h.
References m_swordModule.
Referenced by CSwordBibleModuleInfo::bookNumber(), CSwordBibleModuleInfo::chapterCount(), CSwordBibleModuleInfo::createKey(), CSwordLexiconModuleInfo::createKey(), CSwordLexiconModuleInfo::entries(), CSwordCommentaryModuleInfo::isWritable(), CSwordVerseKey::next(), CSwordLDKey::NextEntry(), CSwordVerseKey::previous(), CSwordLDKey::PreviousEntry(), CSwordKey::rawText(), CSwordKey::renderedText(), Filters::TeiToHtml::renderReference(), Filters::TeiToHtml::renderTargetReference(), CSwordLDKey::setKey(), CSwordVerseKey::setModule(), CSwordLexiconModuleInfo::snap(), CSwordKey::strippedText(), CSwordBookModuleInfo::tree(), and CSwordBibleModuleInfo::verseCount().
textDirection()
CSwordModuleInfo::TextDirection CSwordModuleInfo::textDirection () const
Returns
the text direction of the module's text.
Definition at line 889 of file cswordmoduleinfo.cpp.
References config(), LeftToRight, RightToLeft, and TextDir.
Referenced by Rendering::CTextRendering::finishText(), and textDirectionAsHtml().
textDirectionAsHtml()
char const * CSwordModuleInfo::textDirectionAsHtml () const
Returns
the text direction of the module's text as an HTML value.
Definition at line 895 of file cswordmoduleinfo.cpp.
References RightToLeft, and textDirection().
type()
ModuleType CSwordModuleInfo::type () const inline
Returns
the type of the module.
Definition at line 270 of file cswordmoduleinfo.h.
References m_type.
Referenced by categoryIconAdd(), anonymous_namespace{btinforendering.cpp}::decodeCrossReference(), ReferenceManager::encodeHyperlink(), BtPrinter::entryLink(), BtQmlInterface::getCurrentModelIndex(), BtQmlInterface::isBibleOrCommentary(), Rendering::CTextRendering::KeyTreeItem::KeyTreeItem(), CSwordKey::renderedText(), BtCopyByReferencesDialog::resetThreshold(), CSwordLDKey::setModule(), CSwordTreeKey::setModule(), and CSwordVerseKey::setModule().
unlock()
bool CSwordModuleInfo::unlock (const QString & unlockKey)
  Sets the unlock key of the modules and writes the key into the config file.
  @return True if the unlock process was succesful, if the key was
wrong, or if the config file was write protected return false.
Todo:
remove this comment once it is no longer needed
Todo:
write to Sword config as well
Definition at line 261 of file cswordmoduleinfo.cpp.
References btConfig(), isEncrypted(), m_backend, m_cachedName, m_swordModule, CSwordBackend::raw(), BtConfig::setModuleEncryptionKey(), unlockedChanged(), and unlockKeyIsValid().
unlockedChanged
void CSwordModuleInfo::unlockedChanged (bool unlocked) signal
Referenced by BtBookshelfModel::addModule(), BtBookshelfModel::removeModule(), and unlock().
unlockKeyIsValid()
bool CSwordModuleInfo::unlockKeyIsValid () const
This function makes an estimate if a module was properly unlocked. It returns true if the first entry of the module is not empty and contains only printable characters (for the first 100 chars or so). If that is the case, we can safely assume that a) the module was properly unlocked and b) no buffer overflows will occur, which can happen when Sword filters process garbage text which was not properly decrypted.
Definition at line 308 of file cswordmoduleinfo.cpp.
References isUnicode(), and m_swordModule.
Referenced by isLocked(), and unlock().
write()
void CSwordModuleInfo::write (CSwordKey * key, const QString & newText)
Writes the new text at the given position into the module. This does only work for writabe modules.
Definition at line 898 of file cswordmoduleinfo.cpp.
References isUnicode(), CSwordKey::key(), and m_swordModule.
Member Data Documentation
footnotes
CSwordModuleInfo::FilterOption const CSwordModuleInfo::footnotes static
Initial value:
{
    "Footnotes",
    "Footnotes",
    QT_TRANSLATE_NOOP("QObject", "Footnotes")}
Footnotes embedded in the module's text
Definition at line 158 of file cswordmoduleinfo.h.
Referenced by aboutText(), hasImportantFilterOption(), BtDisplaySettingsButton::repopulateMenu(), CSwordBackend::setFilterOptions(), and setImportantFilterOptions().
greekAccents
CSwordModuleInfo::FilterOption const CSwordModuleInfo::greekAccents static
Initial value:
{
    "Greek Accents",
    "GreekAccents",
    QT_TRANSLATE_NOOP("QObject", "Greek accents")}
Greek accents may be switched on and off
Definition at line 193 of file cswordmoduleinfo.h.
Referenced by aboutText(), BtDisplaySettingsButton::repopulateMenu(), and CSwordBackend::setFilterOptions().
headings
CSwordModuleInfo::FilterOption const CSwordModuleInfo::headings static
Initial value:
{
    "Headings",
    "Headings",
     QT_TRANSLATE_NOOP("QObject", "Headings")}
additional section headings
Definition at line 168 of file cswordmoduleinfo.h.
Referenced by aboutText(), hasImportantFilterOption(), BtDisplaySettingsButton::repopulateMenu(), CSwordBackend::setFilterOptions(), and setImportantFilterOptions().
hebrewCantillation
CSwordModuleInfo::FilterOption const CSwordModuleInfo::hebrewCantillation static
Initial value:
{
    "Hebrew Cantillation",
    "Cantillation",
    QT_TRANSLATE_NOOP("QObject", "Hebrew cantillation marks")}
Hebrew cantillation points
Definition at line 188 of file cswordmoduleinfo.h.
Referenced by aboutText(), BtDisplaySettingsButton::repopulateMenu(), and CSwordBackend::setFilterOptions().
hebrewPoints
CSwordModuleInfo::FilterOption const CSwordModuleInfo::hebrewPoints static
Initial value:
{
    "Hebrew Vowel Points",
    "HebrewPoints",
    QT_TRANSLATE_NOOP("QObject", "Hebrew vowel points")}
Hebrew vowel points
Definition at line 183 of file cswordmoduleinfo.h.
Referenced by aboutText(), BtDisplaySettingsButton::repopulateMenu(), and CSwordBackend::setFilterOptions().
lemmas
CSwordModuleInfo::FilterOption const CSwordModuleInfo::lemmas static
Initial value:
{
    "Lemmas",
    "Lemma",
    QT_TRANSLATE_NOOP("QObject", "Lemmas")}
lemma tags
Definition at line 178 of file cswordmoduleinfo.h.
Referenced by aboutText(), Filters::GbfToHtml::processText(), and CSwordBackend::setFilterOptions().
m_backend
CSwordBackend& CSwordModuleInfo::m_backend private
Definition at line 422 of file cswordmoduleinfo.h.
Referenced by backend(), buildIndex(), isEncrypted(), setImportantFilterOptions(), and unlock().
m_cachedCategory
CSwordModuleInfo::Category const CSwordModuleInfo::m_cachedCategory private
Definition at line 430 of file cswordmoduleinfo.h.
Referenced by aboutText(), category(), config(), and moduleIcon().
m_cachedFeatures
Features const CSwordModuleInfo::m_cachedFeatures private
Definition at line 429 of file cswordmoduleinfo.h.
Referenced by has().
m_cachedGlossaryTargetLanguage
std::shared_ptr<Language const> const CSwordModuleInfo::m_cachedGlossaryTargetLanguage private
Definition at line 432 of file cswordmoduleinfo.h.
Referenced by glossaryTargetlanguage().
m_cachedHasVersion
bool const CSwordModuleInfo::m_cachedHasVersion private
Definition at line 433 of file cswordmoduleinfo.h.
Referenced by aboutText(), buildIndex(), CSwordModuleInfo(), hasIndex(), and hasVersion().
m_cachedLanguage
std::shared_ptr<Language const> const CSwordModuleInfo::m_cachedLanguage private
Definition at line 431 of file cswordmoduleinfo.h.
Referenced by aboutText(), and language().
m_cachedName
QString const CSwordModuleInfo::m_cachedName private
Definition at line 428 of file cswordmoduleinfo.h.
Referenced by config(), CSwordModuleInfo(), deleteIndex(), getModuleBaseIndexLocation(), hasIndex(), isEncrypted(), name(), setHidden(), and unlock().
m_cancelIndexing
std::atomic<bool> CSwordModuleInfo::m_cancelIndexing private
Definition at line 425 of file cswordmoduleinfo.h.
Referenced by buildIndex(), and cancelIndexing().
m_hidden
bool CSwordModuleInfo::m_hidden private
Definition at line 424 of file cswordmoduleinfo.h.
Referenced by CSwordModuleInfo(), isHidden(), and setHidden().
m_swordModule
sword::SWModule& CSwordModuleInfo::m_swordModule private
Definition at line 421 of file cswordmoduleinfo.h.
Referenced by aboutText(), buildIndex(), config(), getFormattedConfigEntry(), getSimpleConfigEntry(), getUnlockInfo(), has(), isUnicode(), searchIndexed(), swordModule(), unlock(), unlockKeyIsValid(), and write().
m_type
ModuleType const CSwordModuleInfo::m_type private
Definition at line 423 of file cswordmoduleinfo.h.
Referenced by buildIndex(), config(), hasImportantFilterOption(), and type().
morphSegmentation
CSwordModuleInfo::FilterOption const CSwordModuleInfo::morphSegmentation static
Initial value:
{
    "Morph Segmentation",
    "MorphSegmentation",
    QT_TRANSLATE_NOOP("QObject", "Morph segmentation")}
morph word segmentation, supported by OSIS
Definition at line 214 of file cswordmoduleinfo.h.
Referenced by aboutText(), buildIndex(), BtDisplaySettingsButton::repopulateMenu(), and CSwordBackend::setFilterOptions().
morphTags
CSwordModuleInfo::FilterOption const CSwordModuleInfo::morphTags static
Initial value:
{
     "Morphological Tags",
     "Morph",
     QT_TRANSLATE_NOOP("QObject", "Morphological tags")}
morphology
Definition at line 173 of file cswordmoduleinfo.h.
Referenced by aboutText(), hasImportantFilterOption(), Filters::GbfToHtml::processText(), CSwordBackend::setFilterOptions(), and setImportantFilterOptions().
redLetterWords
CSwordModuleInfo::FilterOption const CSwordModuleInfo::redLetterWords static
Initial value:
{
    "Words of Christ in Red",
    "RedLetterWords",
    QT_TRANSLATE_NOOP("QObject", "Red letter words")}
Jesus words in red, color is template specific
Definition at line 203 of file cswordmoduleinfo.h.
Referenced by aboutText(), buildIndex(), BtDisplaySettingsButton::repopulateMenu(), and CSwordBackend::setFilterOptions().
scriptureReferences
CSwordModuleInfo::FilterOption const CSwordModuleInfo::scriptureReferences static
Initial value:
{
    "Cross-references",
    "Scripref",
    QT_TRANSLATE_NOOP("QObject", "Scripture cross-references")}
scripture references may be switched on and off, just makes sense in Bibles
Definition at line 198 of file cswordmoduleinfo.h.
Referenced by aboutText(), buildIndex(), BtDisplaySettingsButton::repopulateMenu(), and CSwordBackend::setFilterOptions().
strongNumbers
CSwordModuleInfo::FilterOption const CSwordModuleInfo::strongNumbers static
Initial value:
{
    "Strong's Numbers",
    "Strongs",
    QT_TRANSLATE_NOOP("QObject", "Strong's numbers")}
strong numbers, usually in the text for the info display
Definition at line 163 of file cswordmoduleinfo.h.
Referenced by aboutText(), hasImportantFilterOption(), Filters::GbfToHtml::processText(), CSwordBackend::setFilterOptions(), and setImportantFilterOptions().
textualVariants
CSwordModuleInfo::FilterOption const CSwordModuleInfo::textualVariants static
Initial value:
{
    "Textual Variants",
    "Variants",
    QT_TRANSLATE_NOOP("QObject", "Textual variants"),
    &CSwordModuleInfo::FilterOption::valueToReadings}
variants
Definition at line 208 of file cswordmoduleinfo.h.
Referenced by aboutText(), BtDisplaySettingsButton::repopulateMenu(), and CSwordBackend::setFilterOptions().
The documentation for this class was generated from the following files:
cswordmoduleinfo.h
cswordmoduleinfo.cpp