BibleTime: CSwordModuleSearch::anonymous_namespace{cswordmodulesearch.cpp} Namespace Reference
CSwordModuleSearch::anonymous_namespace{cswordmodulesearch.cpp} Namespace Reference
Functions
QStringList queryParser (QString const &queryString)
static QRegularExpression const spaceRegexp (spaceRegexpString)
static auto const spaceRegexpString (QStringLiteral(R"PCRE(\s+)PCRE"))
Function Documentation
queryParser()
QStringList CSwordModuleSearch::anonymous_namespace{cswordmodulesearch.cpp}::queryParser (QString const & queryString)
This function does a terrible job of trying to parse a CLucene query string into a list of words (potentially containing the * or ? glob characters) for word highlighting purposes.
Definition at line 58 of file cswordmodulesearch.cpp.
References queryParser().
Referenced by queryParser().
spaceRegexp()
static QRegularExpression const CSwordModuleSearch::anonymous_namespace{cswordmodulesearch.cpp}::spaceRegexp (spaceRegexpString) static
References spaceRegexp().
Referenced by spaceRegexp().
spaceRegexpString()
static auto const CSwordModuleSearch::anonymous_namespace{cswordmodulesearch.cpp}::spaceRegexpString (QStringLiteral(R"PCRE(\s+)PCRE")) static
References spaceRegexpString().
Referenced by spaceRegexpString().