BibleTime: BtBookshelfWizardPage Class Reference
BtBookshelfWizardPage Class Reference
#include <btbookshelfwizardpage.h>
Public Member Functions
BtBookshelfWizardPage (QWidget *parent=nullptr)
BtBookshelfWizard & btWizard () const noexcept
Detailed Description
Definition at line 24 of file btbookshelfwizardpage.h.
Constructor & Destructor Documentation
BtBookshelfWizardPage()
BtBookshelfWizardPage::BtBookshelfWizardPage (QWidget * parent = nullptr)
Definition at line 20 of file btbookshelfwizardpage.cpp.
Member Function Documentation
btWizard()
BtBookshelfWizard & BtBookshelfWizardPage::btWizard () const noexcept
Definition at line 24 of file btbookshelfwizardpage.cpp.
References BT_ASSERT.
Referenced by BtBookshelfLanguagesPage::initializeLanguages(), BtBookshelfInstallFinalPage::initializePage(), BtBookshelfRemoveFinalPage::initializePage(), BtBookshelfSourcesProgressPage::initializePage(), BtBookshelfWorksPage::initializePage(), BtBookshelfSourcesPage::nextId(), BtBookshelfSourcesProgressPage::nextId(), BtBookshelfWorksPage::nextId(), BtBookshelfInstallFinalPage::retranslateUi(), BtBookshelfInstallFinalPage::slotThreadFinished(), and BtBookshelfSourcesProgressPage::slotThreadFinished().
The documentation for this class was generated from the following files:
btbookshelfwizardpage.h
btbookshelfwizardpage.cpp