BibleTime: CBookReadWindow Class Reference
CBookReadWindow Class Reference
#include <cbookreadwindow.h>
Public Member Functions
void applyProfileSettings (BtConfigCore const &windowConf) override
Loads the settings of this window from configuration.
CBookReadWindow (QList< CSwordModuleInfo * > const &modules, CMDIArea *parent)
CSwordModuleInfo::ModuleType moduleType () const override
void storeProfileSettings (BtConfigCore &windowConf) const override
Stores the settings of this window to configuration.
Public Member Functions inherited from CDisplayWindow
BtActionCollection * actionCollection () const
BibleTime * btMainWindow ()
QToolBar * buttonsToolBar () const
virtual void copyDisplayedText ()
const DisplayOptions & displayOptions () const
BtModelViewReadDisplay * displayWidget () const
const FilterOptions & filterOptions () const
int getFirstSelectedIndex () const
int getLastSelectedIndex () const
const QStringList & getModuleList () const
CSwordKey * getMouseClickedKey () const
int getSelectedColumn () const
bool hasSelectedText ()
BTHistory * history ()
bool init ()
bool isReady () const
CSwordKey * key () const
CKeyChooser * keyChooser () const
QToolBar * mainToolBar () const
CMDIArea * mdi () const
BtConstModuleList modules () const
void setButtonsToolBar (QToolBar *bar)
void setDisplaySettingsButton (BtDisplaySettingsButton *button)
void setDisplayWidget (BtModelViewReadDisplay *newDisplay)
void setMainToolBar (QToolBar *bar)
virtual bool syncAllowed () const
void windowActivated ()
QString windowCaption ()
Static Public Member Functions
static void insertKeyboardActions (BtActionCollection *const a)
Static Public Member Functions inherited from CDisplayWindow
static void insertKeyboardActions (BtActionCollection *const a)
Protected Slots
void modulesChanged () override
Protected Slots inherited from CDisplayWindow
void lookup ()
virtual void modulesChanged ()
void printAll ()
void printAnchorWithText ()
void saveRawHTML ()
Protected Member Functions
void initActions () override
void initConnections () override
void initToolbars () override
void initView () override
void setupMainWindowToolBars () override
Protected Member Functions inherited from CDisplayWindow
CDisplayWindow (const QList< CSwordModuleInfo * > &modules, CMDIArea *parent)
void clearMainWindowToolBars ()
QToolBar * headerBar () const
template<typename ... Args>
QAction & initAddAction (Args &&... args)
virtual void lookupSwordKey (CSwordKey *)
BtModuleChooserBar * moduleChooserBar () const
QMenu * popup ()
‍** Returns the installed popup menu. *‍/
void setDisplayOptions (DisplayOptions const &v)
void setFilterOptions (FilterOptions const &v)
void setKeyChooser (CKeyChooser *ck)
void setModuleChooserBar (BtModuleChooserBar *bar)
void setToolBarsHidden ()
virtual void setupPopupMenu ()
virtual void updatePopupMenu ()
~CDisplayWindow () override
Private Slots
void treeToggled ()
Private Attributes
QAction * m_treeAction
CBookTreeChooser * m_treeChooser
Additional Inherited Members
Public Slots inherited from CDisplayWindow
void lookupKey (QString const &key)
virtual void reload (CSwordBackend::SetupChangedReason reason)
void slotAddModule (int index, QString module)
void slotRemoveModule (int index)
void slotReplaceModule (int index, QString newModule)
Signals inherited from CDisplayWindow
void sigDisplayOptionsChanged (const DisplayOptions &displayOptions)
void sigFilterOptionsChanged (const FilterOptions &filterOptions)
void sigKeyChanged (CSwordKey *key)
void sigModuleAdded (int index, QString module)
void sigModuleListChanged ()
void sigModuleListSet (QStringList modules)
void sigModuleRemoved (int index)
void sigModuleReplaced (int index, QString newModule)
void sigModulesChanged (const BtConstModuleList &modules)
Protected Attributes inherited from CDisplayWindow
struct CDisplayWindow::ActionsStruct m_actions
Detailed Description
Definition at line 29 of file cbookreadwindow.h.
Constructor & Destructor Documentation
CBookReadWindow()
CBookReadWindow::CBookReadWindow (QList< CSwordModuleInfo * > const & modules, CMDIArea * parent) inline
Definition at line 35 of file cbookreadwindow.h.
Member Function Documentation
applyProfileSettings()
void CBookReadWindow::applyProfileSettings (BtConfigCore const & windowConf) override virtual
Loads the settings of this window from configuration.
Parameters
[in] windowConf The locked configuration group.
Note
We don't use restoreGeometry/saveGeometry for MDI subwindows, because they give slightly incorrect results with some window managers. Might be related to Qt bug QTBUG-7634.
Reimplemented from CDisplayWindow.
Definition at line 36 of file cbookreadwindow.cpp.
References CDisplayWindow::applyProfileSettings(), BT_ASSERT, m_treeAction, and BtConfigCore::value().
initActions()
void CBookReadWindow::initActions () override protected virtual
Initializes the internel keyboard actions.
Reimplemented from CDisplayWindow.
Definition at line 49 of file cbookreadwindow.cpp.
References BtActionCollection::action(), CDisplayWindow::actionCollection(), BT_ASSERT, BT_CONNECT, CDisplayWindow::initActions(), insertKeyboardActions(), m_treeAction, BtActionCollection::readShortcuts(), and treeToggled().
initConnections()
void CBookReadWindow::initConnections () override protected virtual
No descriptions
Reimplemented from CDisplayWindow.
Definition at line 74 of file cbookreadwindow.cpp.
References BT_CONNECT, CDisplayWindow::initConnections(), CKeyChooser::keyChanged(), CDisplayWindow::keyChooser(), CDisplayWindow::lookupSwordKey(), m_treeChooser, CBookTreeChooser::updateKey(), and CKeyChooser::updateKey().
initToolbars()
void CBookReadWindow::initToolbars () override protected virtual
Initialize the toolbars.
Reimplemented from CDisplayWindow.
Definition at line 118 of file cbookreadwindow.cpp.
References CDisplayWindow::actionCollection(), CResMgr::displaywindows::general::search::actionName, CDisplayWindow::ActionsStruct::backInHistory, BT_ASSERT, CDisplayWindow::buttonsToolBar(), CDisplayWindow::ActionsStruct::forwardInHistory, CDisplayWindow::keyChooser(), CDisplayWindow::m_actions, m_treeAction, CDisplayWindow::mainToolBar(), and CDisplayWindow::setDisplaySettingsButton().
initView()
void CBookReadWindow::initView () override protected virtual
Init the view
Reimplemented from CDisplayWindow.
Definition at line 86 of file cbookreadwindow.cpp.
References CDisplayWindow::buttonsToolBar(), CKeyChooser::createInstance(), CDisplayWindow::displayWidget(), util::tool::getIconForModule(), CDisplayWindow::getModuleList(), CDisplayWindow::history(), CDisplayWindow::key(), m_treeChooser, CDisplayWindow::mainToolBar(), CDisplayWindow::moduleChooserBar(), CDisplayWindow::modules(), CDisplayWindow::setButtonsToolBar(), CDisplayWindow::setDisplayWidget(), CDisplayWindow::setKeyChooser(), CDisplayWindow::setMainToolBar(), CDisplayWindow::setModuleChooserBar(), BtModuleChooserBar::setModules(), and CBookTreeChooser::setModules().
insertKeyboardActions()
void CBookReadWindow::insertKeyboardActions (BtActionCollection *const a) static
Definition at line 63 of file cbookreadwindow.cpp.
References BtActionCollection::addAction().
Referenced by initActions().
modulesChanged
void CBookReadWindow::modulesChanged () override protected slot
Reimplementation to take care of the tree chooser.
Definition at line 174 of file cbookreadwindow.cpp.
References m_treeChooser, CDisplayWindow::modules(), CDisplayWindow::modulesChanged(), and CBookTreeChooser::setModules().
moduleType()
CSwordModuleInfo::ModuleType CBookReadWindow::moduleType () const inline override virtual
Reimplemented from CDisplayWindow.
Definition at line 41 of file cbookreadwindow.h.
References CSwordModuleInfo::GenericBook.
setupMainWindowToolBars()
void CBookReadWindow::setupMainWindowToolBars () override protected virtual
Called to add actions to mainWindow toolbars
Reimplemented from CDisplayWindow.
Definition at line 138 of file cbookreadwindow.cpp.
References CDisplayWindow::actionCollection(), CResMgr::displaywindows::general::search::actionName, CDisplayWindow::ActionsStruct::backInHistory, BT_CONNECT, CDisplayWindow::btMainWindow(), CDisplayWindow::buttonsToolBar(), CKeyChooser::createInstance(), CDisplayWindow::ActionsStruct::forwardInHistory, CDisplayWindow::getModuleList(), CDisplayWindow::history(), CDisplayWindow::key(), CKeyChooser::keyChanged(), CDisplayWindow::keyChooser(), CDisplayWindow::lookupSwordKey(), CDisplayWindow::m_actions, m_treeAction, CDisplayWindow::modules(), BibleTime::navToolBar(), CDisplayWindow::setDisplaySettingsButton(), BtModuleChooserBar::setModules(), CDisplayWindow::sigKeyChanged(), BibleTime::toolsToolBar(), CKeyChooser::updateKey(), and BibleTime::worksToolBar().
storeProfileSettings()
void CBookReadWindow::storeProfileSettings (BtConfigCore & conf) const override virtual
Stores the settings of this window to configuration.
Parameters
[in] windowConf The locked configuration group.
Store the settings of this window in the given CProfileWindow object.
Note
We don't use saveGeometry/restoreGeometry for MDI subwindows, because they give slightly incorrect results with some window managers. Might be related to Qt bug QTBUG-7634.
Reimplemented from CDisplayWindow.
Definition at line 44 of file cbookreadwindow.cpp.
References m_treeAction, BtConfigCore::setValue(), and CDisplayWindow::storeProfileSettings().
treeToggled
void CBookReadWindow::treeToggled () private slot
Is called when the action was executed to toggle the tree view.
Definition at line 164 of file cbookreadwindow.cpp.
References CBookTreeChooser::doShow(), m_treeAction, and m_treeChooser.
Referenced by initActions().
Member Data Documentation
m_treeAction
QAction* CBookReadWindow::m_treeAction private
Definition at line 69 of file cbookreadwindow.h.
Referenced by applyProfileSettings(), initActions(), initToolbars(), setupMainWindowToolBars(), storeProfileSettings(), and treeToggled().
m_treeChooser
CBookTreeChooser* CBookReadWindow::m_treeChooser private
Definition at line 70 of file cbookreadwindow.h.
Referenced by initConnections(), initView(), modulesChanged(), and treeToggled().
The documentation for this class was generated from the following files:
cbookreadwindow.h
cbookreadwindow.cpp