BibleTime: anonymous_namespace{colormanager.cpp} Namespace Reference
anonymous_namespace{colormanager.cpp} Namespace Reference
Functions
bool darkMode ()
QString getColorByPattern (std::map< QString, std::map< QString, QString > > const &maps, QString const &pattern, QString const &style)
Function Documentation
darkMode()
bool anonymous_namespace{colormanager.cpp}::darkMode () inline
Definition at line 42 of file colormanager.cpp.
Referenced by ColorManager::loadColorMaps().
getColorByPattern()
QString anonymous_namespace{colormanager.cpp}::getColorByPattern (std::map< QString, std::map< QString, QString > > const & maps, QString const & pattern, QString const & style)
Definition at line 45 of file colormanager.cpp.
Referenced by ColorManager::getBackgroundColor(), ColorManager::getBackgroundHighlightColor(), ColorManager::getCrossRefColor(), and ColorManager::getForegroundColor().