BibleTime: Rendering::CDisplayRendering Class Reference
Rendering::CDisplayRendering Class Reference
Rendering for the html display widget.
#include <cdisplayrendering.h>
Public Member Functions
CDisplayRendering ()
CDisplayRendering (DisplayOptions const &displayOptions, FilterOptions const &filterOptions)
QString const & displayTemplateName () const noexcept
QString renderDisplayEntry (BtConstModuleList const &modules, QString const &key, CTextRendering::KeyTreeItem::Settings::KeyRenderingFace keyRendering=CTextRendering::KeyTreeItem::Settings::CompleteShort) const
void setDisplayTemplateName (QString displayTemplateName) noexcept
Public Member Functions inherited from Rendering::CTextRendering
CTextRendering (bool addText)
CTextRendering (bool addText, DisplayOptions const &displayOptions, FilterOptions const &filterOptions)
DisplayOptions const & displayOptions () const noexcept
FilterOptions const & filterOptions () const noexcept
QString renderKeyRange (CSwordVerseKey const &lowerBound, CSwordVerseKey const &upperBound, const BtConstModuleList &modules, const QString &hightlightKey=QString(), const KeyTreeItem::Settings &settings=KeyTreeItem::Settings())
QString renderKeyTree (KeyTree const &tree) const
QString renderSingleKey (const QString &key, const BtConstModuleList &modules, const KeyTreeItem::Settings &settings=KeyTreeItem::Settings())
void setDisplayOptions (DisplayOptions const &displayOptions) noexcept
void setFilterOptions (FilterOptions const &filterOptions) noexcept
virtual ~CTextRendering ()
Static Public Member Functions
static QString keyToHTMLAnchor (QString const &key)
Protected Member Functions
QString entryLink (KeyTreeItem const &item, CSwordModuleInfo const &module) const override
QString finishText (QString const &text, KeyTree const &tree) const override
Protected Member Functions inherited from Rendering::CTextRendering
virtual QString renderEntry (KeyTreeItem const &item, CSwordKey *key=nullptr) const
Private Attributes
QString m_displayTemplateName
Additional Inherited Members
Public Types inherited from Rendering::CTextRendering
using KeyTree = std::list< KeyTreeItem >
Static Protected Member Functions inherited from Rendering::CTextRendering
static BtConstModuleList collectModules (KeyTree const &tree)
Protected Attributes inherited from Rendering::CTextRendering
bool const m_addText
DisplayOptions m_displayOptions
FilterOptions m_filterOptions
Detailed Description
Rendering for the html display widget.
HTML rendering for the text display widgets.
Author
The BibleTime team
Definition at line 27 of file cdisplayrendering.h.
Constructor & Destructor Documentation
CDisplayRendering() [1/2]
Rendering::CDisplayRendering::CDisplayRendering ()
Definition at line 45 of file cdisplayrendering.cpp.
CDisplayRendering() [2/2]
Rendering::CDisplayRendering::CDisplayRendering (DisplayOptions const & displayOptions, FilterOptions const & filterOptions)
Definition at line 50 of file cdisplayrendering.cpp.
Member Function Documentation
displayTemplateName()
QString const & Rendering::CDisplayRendering::displayTemplateName () const inline noexcept
Definition at line 37 of file cdisplayrendering.h.
References m_displayTemplateName.
Referenced by setDisplayTemplateName().
entryLink()
QString Rendering::CDisplayRendering::entryLink (KeyTreeItem const & item, CSwordModuleInfo const & module) const override protected virtual
Reimplemented from Rendering::CTextRendering.
Definition at line 103 of file cdisplayrendering.cpp.
References CSwordVerseKey::bookName(), CSwordVerseKey::chapter(), ReferenceManager::encodeHyperlink(), CSwordVerseKey::isBoundSet(), Rendering::CTextRendering::KeyTreeItem::key(), CSwordKey::key(), CSwordVerseKey::key(), Rendering::CTextRendering::KeyTreeItem::Settings::keyRenderingFace, keyToHTMLAnchor(), CSwordVerseKey::lowerBound(), Rendering::CTextRendering::KeyTreeItem::mappedKey(), Rendering::CTextRendering::KeyTreeItem::modules(), CSwordModuleInfo::name(), CSwordVerseKey::setIntros(), CSwordVerseKey::setKey(), Rendering::CTextRendering::KeyTreeItem::settings(), CSwordVerseKey::shortText(), CSwordVerseKey::upperBound(), and CSwordVerseKey::verse().
finishText()
QString Rendering::CDisplayRendering::finishText (QString const & text, KeyTree const & tree) const override protected virtual
Reimplemented from Rendering::CTextRendering.
Definition at line 218 of file cdisplayrendering.cpp.
References CDisplayTemplateMgr::activeTemplateName(), Rendering::CTextRendering::collectModules(), CDisplayTemplateMgr::fillTemplate(), CDisplayTemplateMgr::instance(), CDisplayTemplateMgr::Settings::langAbbrev, m_displayTemplateName, CDisplayTemplateMgr::Settings::modules, and CDisplayTemplateMgr::Settings::textDirection.
keyToHTMLAnchor()
QString Rendering::CDisplayRendering::keyToHTMLAnchor (QString const & key) static
Definition at line 210 of file cdisplayrendering.cpp.
Referenced by entryLink().
renderDisplayEntry()
QString Rendering::CDisplayRendering::renderDisplayEntry (BtConstModuleList const & modules, QString const & key, CTextRendering::KeyTreeItem::Settings::KeyRenderingFace keyRendering = CTextRendering::KeyTreeItem::Settings::CompleteShort) const
Definition at line 55 of file cdisplayrendering.cpp.
References CSwordModuleInfo::Bible, BT_ASSERT, CSwordVerseKey::chapter(), CSwordModuleInfo::Commentary, CSwordVerseKey::key(), Rendering::CTextRendering::KeyTreeItem::Settings::NoKey, CSwordKey::rawText(), Rendering::CTextRendering::renderKeyTree(), CSwordVerseKey::setChapter(), CSwordVerseKey::setIntros(), CSwordVerseKey::setKey(), CSwordVerseKey::setVerse(), and CSwordVerseKey::verse().
setDisplayTemplateName()
void Rendering::CDisplayRendering::setDisplayTemplateName (QString displayTemplateName) inline noexcept
Definition at line 40 of file cdisplayrendering.h.
References displayTemplateName(), and m_displayTemplateName.
Referenced by CDisplaySettingsPage::updateStylePreview().
Member Data Documentation
m_displayTemplateName
QString Rendering::CDisplayRendering::m_displayTemplateName private
Definition at line 61 of file cdisplayrendering.h.
Referenced by displayTemplateName(), finishText(), and setDisplayTemplateName().
The documentation for this class was generated from the following files:
cdisplayrendering.h
cdisplayrendering.cpp