BibleTime: util::directory Namespace Reference
util::directory Namespace Reference
Namespaces
anonymous_namespace{directory.cpp}
Functions
QString convertDirSeparators (const QString &path)
size_t getDirSizeRecursive (QString const &dir)
const QDir & getDisplayTemplatesDir ()
QString getHandbook ()
QString getHowto ()
const QDir & getIconDir ()
const QDir & getLicenseDir ()
const QDir & getLocaleDir ()
const QDir & getPicsDir ()
const QDir & getSwordPathDir ()
const QDir & getUserBaseDir ()
const QDir & getUserCacheDir ()
const QDir & getUserDisplayTemplatesDir ()
const QDir & getUserHomeDir ()
const QDir & getUserHomeSwordDir ()
const QDir & getUserHomeSwordModsDir ()
const QDir & getUserIndexDir ()
const QDir & getUserSessionsDir ()
bool initDirectoryCache ()
Initializes the directory cache and returns whether it was successful.
void removeRecursive (const QString &dir)
Detailed Description
Tools for working with directories.
Function Documentation
convertDirSeparators()
QString util::directory::convertDirSeparators (const QString & path)
Convert directory path separators to those for each platform Windows = "\", Others = "/"
Definition at line 346 of file directory.cpp.
Referenced by CSwordBackend::getPrivateSwordConfigFile(), CSwordBackend::getSharedSwordConfigFiles(), BibleTime::initSwordConfigFile(), BtInstallBackend::setTargetList(), BtBookshelfWorksPage::slotInitPathCombo(), and CSwordBackend::swordDirList().
getDirSizeRecursive()
std::size_t util::directory::getDirSizeRecursive (QString const & dir)
Returns the size of the directory including the size of all it's files and it's subdirs.
Returns the size of the directory including the size of all its files and its subdirs.
Todo:
Check if it's suitable for huge dir trees, as it holds a QDir object for each of it at the same time in the deepest recursion. For really deep dir tree this may lead to a stack overflow.
Returns
The size of the dir in bytes
Definition at line 321 of file directory.cpp.
Referenced by CSwordModuleInfo::indexSize().
getDisplayTemplatesDir()
const QDir & util::directory::getDisplayTemplatesDir ()
Return the path to the default display template files.
Definition at line 438 of file directory.cpp.
References util::directory::anonymous_namespace{directory.cpp}::cachedUserSessionsDir.
Referenced by CDisplayTemplateMgr::CDisplayTemplateMgr(), CDisplayTemplateMgr::fillTemplate(), and ColorManager::loadColorMaps().
getHandbook()
QString util::directory::getHandbook ()
Returns
an absolute path to a handbook or QString() if not found.
Definition at line 434 of file directory.cpp.
References util::directory::anonymous_namespace{directory.cpp}::cachedUserHomeSwordModsDir.
Referenced by BibleTime::openOnlineHelp_Handbook().
getHowto()
QString util::directory::getHowto ()
Returns
an absolute path to a howto or QString() if not found.
Definition at line 436 of file directory.cpp.
Referenced by BibleTime::openOnlineHelp_Howto().
getIconDir()
const QDir & util::directory::getIconDir ()
Return the path to the icons.
Definition at line 379 of file directory.cpp.
getLicenseDir()
const QDir & util::directory::getLicenseDir ()
Return the path to the license.
Definition at line 383 of file directory.cpp.
Referenced by BtAboutDialog::retranslateLicenceTab().
getLocaleDir()
const QDir & util::directory::getLocaleDir ()
Return the path to the translation files.
Definition at line 391 of file directory.cpp.
Referenced by main().
getPicsDir()
const QDir & util::directory::getPicsDir ()
Return the path to the pictures.
Definition at line 387 of file directory.cpp.
Referenced by BibleTime::BibleTime().
getSwordPathDir()
const QDir & util::directory::getSwordPathDir ()
Return the path to the SWORD_PATH env var directory
Definition at line 375 of file directory.cpp.
References util::directory::anonymous_namespace{directory.cpp}::cachedDocDir, and util::directory::anonymous_namespace{directory.cpp}::getDocFile().
getUserBaseDir()
const QDir & util::directory::getUserBaseDir ()
Return the path to the user's settings directory.
Definition at line 442 of file directory.cpp.
References util::directory::anonymous_namespace{directory.cpp}::cachedUserCacheDir.
Referenced by BtBookmarksModelPrivate::defaultBookmarksFile(), and BtConfig::initBtConfig().
getUserCacheDir()
const QDir & util::directory::getUserCacheDir ()
Return the path to the user's cache directory.
Definition at line 462 of file directory.cpp.
Referenced by CSwordLexiconModuleInfo::entries().
getUserDisplayTemplatesDir()
const QDir & util::directory::getUserDisplayTemplatesDir ()
Return the path to the user's custom display templates directory.
Definition at line 470 of file directory.cpp.
Referenced by CDisplayTemplateMgr::CDisplayTemplateMgr(), and ColorManager::loadColorMaps().
getUserHomeDir()
const QDir & util::directory::getUserHomeDir ()
Return the path to the user's home directory. APPDATA% on Windows $HOME on linux
Definition at line 446 of file directory.cpp.
References util::directory::anonymous_namespace{directory.cpp}::cachedUserIndexDir.
Referenced by main(), BtInstallBackend::setTargetList(), BtInstallBackend::swordConfigFilename(), and BtInstallBackend::swordDir().
getUserHomeSwordDir()
const QDir & util::directory::getUserHomeSwordDir ()
Return the path to the user's home .sword (or Sword) directory. APPDATA%\Sword on Windows $HOME.sword on linux
Definition at line 450 of file directory.cpp.
References util::directory::anonymous_namespace{directory.cpp}::cachedUserDisplayTemplatesDir.
Referenced by BtInstallBackend::configPath(), CSwordBackend::getPrivateSwordConfigPath(), BibleTime::initSwordConfigFile(), and main().
getUserHomeSwordModsDir()
const QDir & util::directory::getUserHomeSwordModsDir ()
Return the path to the user's home .sword (or Sword) mods.d directory. APPDATA%\Sword\mods.d on Windows $HOME.sword\mods.d on linux
Definition at line 454 of file directory.cpp.
getUserIndexDir()
const QDir & util::directory::getUserIndexDir ()
Return the path to the user's indices directory.
Definition at line 466 of file directory.cpp.
Referenced by CSwordModuleInfo::getGlobalBaseIndexLocation().
getUserSessionsDir()
const QDir & util::directory::getUserSessionsDir ()
Return the path to the user's sessions directory.
Definition at line 458 of file directory.cpp.
initDirectoryCache()
bool util::directory::initDirectoryCache ()
Initializes the directory cache and returns whether it was successful.
Note
When this function returns unsuccessfully, the program should exit.
Definition at line 102 of file directory.cpp.
Referenced by main().
removeRecursive()
void util::directory::removeRecursive (const QString & dir)
Removes the given dir with all it's files and subdirs.
Todo:
Check if it's suitable for huge dir trees, as it holds a QDir object for each of it at the same time in the deepest recursion. For really deep dir tree this may lead to a stack overflow.
Definition at line 298 of file directory.cpp.
References BT_ASSERT.
Referenced by CSwordModuleInfo::deleteIndexForModule().