BibleTime: Rendering::CEntryDisplay Class Reference
Rendering::CEntryDisplay Class Reference
#include <centrydisplay.h>
Public Member Functions
virtual char display (CSwordModuleInfo &mod)
virtual const QString text (const BtConstModuleList &modules, const QString &key, const DisplayOptions &displayOptions, const FilterOptions &filterOptions)
const QString textKeyRendering (const BtConstModuleList &modules, const QString &key, const DisplayOptions &displayOptions, const FilterOptions &filterOptions, CTextRendering::KeyTreeItem::Settings::KeyRenderingFace keyRendering)
virtual ~CEntryDisplay ()
Detailed Description
Definition at line 25 of file centrydisplay.h.
Constructor & Destructor Documentation
~CEntryDisplay()
virtual Rendering::CEntryDisplay::~CEntryDisplay () inline virtual
Definition at line 29 of file centrydisplay.h.
Member Function Documentation
display()
virtual char Rendering::CEntryDisplay::display (CSwordModuleInfo & mod) inline virtual
Definition at line 46 of file centrydisplay.h.
text()
const QString CEntryDisplay::text (const BtConstModuleList & modules, const QString & key, const DisplayOptions & displayOptions, const FilterOptions & filterOptions) virtual
Returns
the rendered text using the modules in the list and using the key parameter.
Reimplemented in Rendering::CChapterDisplay, and Rendering::CBookDisplay.
Definition at line 37 of file centrydisplay.cpp.
References Rendering::CTextRendering::KeyTreeItem::Settings::CompleteShort, and textKeyRendering().
Referenced by BtModuleTextModel::lexiconData().
textKeyRendering()
const QString CEntryDisplay::textKeyRendering (const BtConstModuleList & modules, const QString & key, const DisplayOptions & displayOptions, const FilterOptions & filterOptions, CTextRendering::KeyTreeItem::Settings::KeyRenderingFace keyRendering)
Definition at line 46 of file centrydisplay.cpp.
References CSwordModuleInfo::Bible, CSwordVerseKey::chapter(), CSwordModuleInfo::Commentary, CSwordVerseKey::key(), CSwordModuleInfo::module(), Rendering::CTextRendering::KeyTreeItem::Settings::NoKey, CSwordKey::rawText(), Rendering::CTextRendering::renderKeyTree(), CSwordVerseKey::setChapter(), CSwordVerseKey::setIntros(), CSwordVerseKey::setKey(), CSwordVerseKey::setVerse(), CSwordModuleInfo::type(), and CSwordVerseKey::verse().
Referenced by BtModuleTextModel::bookData(), text(), and BtModuleTextModel::verseData().
The documentation for this class was generated from the following files:
centrydisplay.h
centrydisplay.cpp