BibleTime: BtInstallThread Class Reference
BtInstallThread Class Reference
#include <btinstallthread.h>
Signals
void downloadStarted (int moduleIndex)
void installCompleted (int moduleIndex, bool success)
void preparingInstall (int moduleIndex)
void statusUpdated (int moduleIndex, int progressPercent)
Public Member Functions
BtInstallThread (const QList< CSwordModuleInfo * > &modules, const QString &destination, QObject *const parent=nullptr)
void stopInstall ()
Protected Member Functions
void run () override
Private Slots
void slotDownloadStarted ()
void slotManagerStatusUpdated (int totalProgress, int fileProgress)
Private Member Functions
void installModule ()
bool removeModule ()
Private Attributes
int m_currentModuleIndex = 0
const QString m_destination
BtInstallMgr m_iMgr
const QList< CSwordModuleInfo * > & m_modules
std::atomic< bool > m_stopRequested
Detailed Description
Definition at line 28 of file btinstallthread.h.
Constructor & Destructor Documentation
BtInstallThread()
BtInstallThread::BtInstallThread (const QList< CSwordModuleInfo * > & modules, const QString & destination, QObject *const parent = nullptr) inline
Definition at line 34 of file btinstallthread.h.
References BT_CONNECT, BtInstallMgr::downloadStarted(), m_iMgr, BtInstallMgr::percentCompleted(), slotDownloadStarted(), and slotManagerStatusUpdated().
Member Function Documentation
downloadStarted
void BtInstallThread::downloadStarted (int moduleIndex) signal
Emitted when the first file download has been started.
Referenced by BtBookshelfInstallFinalPage::initializePage(), and slotDownloadStarted().
installCompleted
void BtInstallThread::installCompleted (int moduleIndex, bool success) signal
Emitted when installing is complete.
Referenced by BtBookshelfInstallFinalPage::initializePage(), and installModule().
installModule()
void BtInstallThread::installModule () private
Todo:
silently removing without undo if the user cancels the update is WRONG!!!
Definition at line 67 of file btinstallthread.cpp.
References installCompleted(), BtInstallBackend::isRemote(), m_currentModuleIndex, m_destination, m_iMgr, m_stopRequested, preparingInstall(), removeModule(), BtInstallBackend::source(), and statusUpdated().
Referenced by run().
preparingInstall
void BtInstallThread::preparingInstall (int moduleIndex) signal
Emitted when starting the installation.
Referenced by BtBookshelfInstallFinalPage::initializePage(), and installModule().
removeModule()
bool BtInstallThread::removeModule () private
Definition at line 117 of file btinstallthread.cpp.
References CSwordModuleInfo::AbsoluteDataPath, BtInstallBackend::backend(), CSwordModuleInfo::config(), CSwordModuleInfo::DataPath, CSwordBackend::findModuleByName(), CSwordBackend::instance(), m_currentModuleIndex, m_destination, m_modules, CSwordModuleInfo::name(), CSwordBackend::prefixPath(), and BtInstallBackend::source().
Referenced by installModule().
run()
void BtInstallThread::run () override protected
Todo:
move this to some common precondition
Definition at line 46 of file btinstallthread.cpp.
References installModule(), m_currentModuleIndex, m_destination, m_modules, and m_stopRequested.
slotDownloadStarted
void BtInstallThread::slotDownloadStarted () private slot
Definition at line 113 of file btinstallthread.cpp.
References downloadStarted(), and m_currentModuleIndex.
Referenced by BtInstallThread().
slotManagerStatusUpdated
void BtInstallThread::slotManagerStatusUpdated (int totalProgress, int fileProgress) private slot
Definition at line 109 of file btinstallthread.cpp.
References m_currentModuleIndex, and statusUpdated().
Referenced by BtInstallThread().
statusUpdated
void BtInstallThread::statusUpdated (int moduleIndex, int progressPercent) signal
Emitted when the install progress status is updated.
Referenced by BtBookshelfInstallFinalPage::initializePage(), installModule(), and slotManagerStatusUpdated().
stopInstall()
void BtInstallThread::stopInstall () inline
Definition at line 50 of file btinstallthread.h.
References m_stopRequested.
Referenced by BtBookshelfInstallFinalPage::destroyThread(), and BtBookshelfInstallFinalPage::slotStopInstall().
Member Data Documentation
m_currentModuleIndex
int BtInstallThread::m_currentModuleIndex = 0 private
Definition at line 86 of file btinstallthread.h.
Referenced by installModule(), removeModule(), run(), slotDownloadStarted(), and slotManagerStatusUpdated().
m_destination
const QString BtInstallThread::m_destination private
Definition at line 84 of file btinstallthread.h.
Referenced by installModule(), removeModule(), and run().
m_iMgr
BtInstallMgr BtInstallThread::m_iMgr private
Definition at line 85 of file btinstallthread.h.
Referenced by BtInstallThread(), and installModule().
m_modules
const QList<CSwordModuleInfo *>& BtInstallThread::m_modules private
Definition at line 83 of file btinstallthread.h.
Referenced by removeModule(), and run().
m_stopRequested
std::atomic<bool> BtInstallThread::m_stopRequested private
Definition at line 87 of file btinstallthread.h.
Referenced by installModule(), run(), and stopInstall().
The documentation for this class was generated from the following files:
btinstallthread.h
btinstallthread.cpp