BibleTime: btbookmarksmodel.cpp File Reference
btbookmarksmodel.cpp File Reference
#include "btbookmarksmodel.h"
#include <algorithm>
#include <memory>
#include <QDir>
#include <QDomElement>
#include <QDomNode>
#include <QFile>
#include <QIODevice>
#include <QList>
#include <QString>
#include <QTextCodec>
#include <QTextStream>
#include <QTime>
#include <QTimer>
#include "../util/btassert.h"
#include "../util/btconnect.h"
#include "../util/cresmgr.h"
#include "../util/directory.h"
#include "../util/tool.h"
#include "btglobal.h"
#include "config/btconfig.h"
#include "drivers/cswordmoduleinfo.h"
#include "keys/cswordversekey.h"
#include "managers/cswordbackend.h"
Classes
class BtBookmarksModelPrivate
class BtBookmarksModelPrivate::BookmarkFolder
class BtBookmarksModelPrivate::BookmarkItem
class BtBookmarksModelPrivate::BookmarkItemBase
Namespaces
anonymous_namespace{btbookmarksmodel.cpp}
Macros
#define CURRENT_SYNTAX_VERSION 1
Typedefs
using BookmarkFolder = BtBookmarksModelPrivate::BookmarkFolder
using BookmarkItem = BtBookmarksModelPrivate::BookmarkItem
using BookmarkItemBase = BtBookmarksModelPrivate::BookmarkItemBase
Functions
bool BtBookmarksModelSortAscending (BookmarkItemBase *i1, BookmarkItemBase *i2)
bool BtBookmarksModelSortDescending (BookmarkItemBase *i1, BookmarkItemBase *i2)
QString anonymous_namespace{btbookmarksmodel.cpp}::toHeader (QString const &key, QString const &moduleName)
Macro Definition Documentation
CURRENT_SYNTAX_VERSION
#define CURRENT_SYNTAX_VERSION 1
Total change list that should be applied after refactoring complete: non latin bookmark titles shown with unrecognized symbols feature request: hold Shift and Ctrl upon dragging item move loader to private class add ability to create bookmarks data with setData/insertRows unrecognized characters increaases in size file each save/load root folder for bookmarks
Definition at line 50 of file btbookmarksmodel.cpp.
Typedef Documentation
BookmarkFolder
using BookmarkFolder = BtBookmarksModelPrivate::BookmarkFolder
Definition at line 445 of file btbookmarksmodel.cpp.
BookmarkItem
using BookmarkItem = BtBookmarksModelPrivate::BookmarkItem
Definition at line 444 of file btbookmarksmodel.cpp.
BookmarkItemBase
using BookmarkItemBase = BtBookmarksModelPrivate::BookmarkItemBase
Definition at line 443 of file btbookmarksmodel.cpp.
Function Documentation
BtBookmarksModelSortAscending()
bool BtBookmarksModelSortAscending (BookmarkItemBase * i1, BookmarkItemBase * i2)
Definition at line 938 of file btbookmarksmodel.cpp.
References BtBookmarksModelPrivate::BookmarkItemBase::text().
Referenced by BtBookmarksModel::sortItems().
BtBookmarksModelSortDescending()
bool BtBookmarksModelSortDescending (BookmarkItemBase * i1, BookmarkItemBase * i2)
Definition at line 943 of file btbookmarksmodel.cpp.
References BtBookmarksModelPrivate::BookmarkItemBase::text().
Referenced by BtBookmarksModel::sortItems().