BibleTime: BtBookshelfTreeModel::Grouping Class Reference
BtBookshelfTreeModel::Grouping Class Reference
#include <btbookshelftreemodel.h>
Public Member Functions
Grouping ()=default
Grouping (Grouping &&copy)=default
Grouping (Grouping const &copy)=default
Grouping (std::initializer_list< Group > values)
auto const & list () const noexcept
bool loadFrom (BtConfigCore const &config, QString const &key)
Grouping & operator= (Grouping &&copy)=default
Grouping & operator= (Grouping const &copy)=default
void saveTo (BtConfigCore &config, QString const &key) const
~Grouping ()=default
Static Public Attributes
static Grouping const CAT
static Grouping const CAT_LANG
static Grouping const DEFAULT
static Grouping const LANG
static Grouping const LANG_CAT
static Grouping const NONE
Private Attributes
QList< Group > m_list
Friends
bool operator== (Grouping const &lhs, Grouping const &rhs)
QDataStream & operator>> (QDataStream &is, BtBookshelfTreeModel::Grouping &o)
Detailed Description
Definition at line 67 of file btbookshelftreemodel.h.
Constructor & Destructor Documentation
Grouping() [1/4]
BtBookshelfTreeModel::Grouping::Grouping () default
Grouping() [2/4]
BtBookshelfTreeModel::Grouping::Grouping (Grouping && copy) default
Grouping() [3/4]
BtBookshelfTreeModel::Grouping::Grouping (Grouping const & copy) default
Grouping() [4/4]
BtBookshelfTreeModel::Grouping::Grouping (std::initializer_list< Group > values) inline
Definition at line 74 of file btbookshelftreemodel.h.
~Grouping()
BtBookshelfTreeModel::Grouping::~Grouping () default
Member Function Documentation
list()
auto const & BtBookshelfTreeModel::Grouping::list () const inline noexcept
Definition at line 81 of file btbookshelftreemodel.h.
References m_list.
Referenced by BtBookshelfTreeModel::addModule(), BtBookshelfWidget::initMenus(), operator<<(), and BtBookshelfWorksPage::slotGroupingActionTriggered().
loadFrom()
bool BtBookshelfTreeModel::Grouping::loadFrom (BtConfigCore const & config, QString const & key)
Definition at line 49 of file btbookshelftreemodel.cpp.
References BT_ASSERT, and BtConfigCore::qVariantValue().
Referenced by BtBookshelfTreeModel::BtBookshelfTreeModel(), and BtBookshelfWorksPage::BtBookshelfWorksPage().
operator=() [1/2]
Grouping & BtBookshelfTreeModel::Grouping::operator= (Grouping && copy) default
operator=() [2/2]
Grouping & BtBookshelfTreeModel::Grouping::operator= (Grouping const & copy) default
saveTo()
void BtBookshelfTreeModel::Grouping::saveTo (BtConfigCore & config, QString const & key) const
Definition at line 61 of file btbookshelftreemodel.cpp.
References BT_ASSERT, and BtConfigCore::setValue().
Referenced by BtSearchModuleChooserDialog::BtSearchModuleChooserDialog(), BtOpenWorkActionMenu::postBuildMenu(), and BtBookshelfWorksPage::slotGroupingOrderChanged().
Friends And Related Symbol Documentation
operator==
bool operator== (Grouping const & lhs, Grouping const & rhs) friend
Definition at line 86 of file btbookshelftreemodel.h.
operator>>
QDataStream & operator>> (QDataStream & is, BtBookshelfTreeModel::Grouping & o) friend
Definition at line 629 of file btbookshelftreemodel.cpp.
Member Data Documentation
CAT
BtBookshelfTreeModel::Grouping const BtBookshelfTreeModel::Grouping::CAT static
Initial value:
=
        { GROUP_CATEGORY }
Definition at line 38 of file btbookshelftreemodel.h.
Referenced by BtBookshelfWorksPage::initializePage().
CAT_LANG
BtBookshelfTreeModel::Grouping const BtBookshelfTreeModel::Grouping::CAT_LANG static
Initial value:
=
        { GROUP_CATEGORY, GROUP_LANGUAGE }
Definition at line 40 of file btbookshelftreemodel.h.
Referenced by BtBookshelfWorksPage::initializePage().
DEFAULT
BtBookshelfTreeModel::Grouping const BtBookshelfTreeModel::Grouping::DEFAULT static
Initial value:
=
        CAT_LANG
Definition at line 99 of file btbookshelftreemodel.h.
Referenced by BtBookshelfTreeModel::BtBookshelfTreeModel(), and BtBookshelfWorksPage::BtBookshelfWorksPage().
LANG
BtBookshelfTreeModel::Grouping const BtBookshelfTreeModel::Grouping::LANG static
Initial value:
=
        { GROUP_LANGUAGE }
Definition at line 42 of file btbookshelftreemodel.h.
LANG_CAT
BtBookshelfTreeModel::Grouping const BtBookshelfTreeModel::Grouping::LANG_CAT static
Initial value:
=
        { GROUP_LANGUAGE, GROUP_CATEGORY }
Definition at line 44 of file btbookshelftreemodel.h.
m_list
QList<Group> BtBookshelfTreeModel::Grouping::m_list private
Definition at line 103 of file btbookshelftreemodel.h.
Referenced by list().
NONE
BtBookshelfTreeModel::Grouping const BtBookshelfTreeModel::Grouping::NONE static
Definition at line 94 of file btbookshelftreemodel.h.
The documentation for this class was generated from the following files:
btbookshelftreemodel.h
btbookshelftreemodel.cpp