BibleTime: CCommentaryReadWindow Class Reference
CCommentaryReadWindow Class Reference
#include <ccommentaryreadwindow.h>
Public Slots
void nextBook ()
void nextChapter ()
void nextVerse ()
void previousBook ()
void previousChapter ()
void previousVerse ()
void reload (CSwordBackend::SetupChangedReason) override
Public Slots inherited from CDisplayWindow
void lookupKey (QString const &key)
virtual void reload (CSwordBackend::SetupChangedReason reason)
void slotAddModule (int index, QString module)
void slotRemoveModule (int index)
void slotReplaceModule (int index, QString newModule)
Public Member Functions
void applyProfileSettings (BtConfigCore const &windowConf) override
Loads the settings of this window from configuration.
CCommentaryReadWindow (QList< CSwordModuleInfo * > const &modules, CMDIArea *parent)
CSwordModuleInfo::ModuleType moduleType () const override
void storeProfileSettings (BtConfigCore &windowConf) const override
Stores the settings of this window to configuration.
bool syncAllowed () const override
Public Member Functions inherited from CDisplayWindow
BtActionCollection * actionCollection () const
BibleTime * btMainWindow ()
QToolBar * buttonsToolBar () const
virtual void copyDisplayedText ()
const DisplayOptions & displayOptions () const
BtModelViewReadDisplay * displayWidget () const
const FilterOptions & filterOptions () const
int getFirstSelectedIndex () const
int getLastSelectedIndex () const
const QStringList & getModuleList () const
CSwordKey * getMouseClickedKey () const
int getSelectedColumn () const
bool hasSelectedText ()
BTHistory * history ()
bool init ()
bool isReady () const
CSwordKey * key () const
CKeyChooser * keyChooser () const
QToolBar * mainToolBar () const
CMDIArea * mdi () const
BtConstModuleList modules () const
void setButtonsToolBar (QToolBar *bar)
void setDisplaySettingsButton (BtDisplaySettingsButton *button)
void setDisplayWidget (BtModelViewReadDisplay *newDisplay)
void setMainToolBar (QToolBar *bar)
void windowActivated ()
QString windowCaption ()
Static Public Member Functions
static void insertKeyboardActions (BtActionCollection *const a)
Static Public Member Functions inherited from CDisplayWindow
static void insertKeyboardActions (BtActionCollection *const a)
Protected Member Functions
void initActions () override
void initToolbars () override
void setupMainWindowToolBars () override
Protected Member Functions inherited from CDisplayWindow
CDisplayWindow (const QList< CSwordModuleInfo * > &modules, CMDIArea *parent)
void clearMainWindowToolBars ()
QToolBar * headerBar () const
template<typename ... Args>
QAction & initAddAction (Args &&... args)
virtual void initConnections ()
virtual void initView ()
virtual void lookupSwordKey (CSwordKey *)
BtModuleChooserBar * moduleChooserBar () const
QMenu * popup ()
‍** Returns the installed popup menu. *‍/
void setDisplayOptions (DisplayOptions const &v)
void setFilterOptions (FilterOptions const &v)
void setKeyChooser (CKeyChooser *ck)
void setModuleChooserBar (BtModuleChooserBar *bar)
void setToolBarsHidden ()
virtual void setupPopupMenu ()
virtual void updatePopupMenu ()
~CDisplayWindow () override
Private Member Functions
CSwordVerseKey * verseKey ()
Private Attributes
QAction * m_syncButton
Additional Inherited Members
Signals inherited from CDisplayWindow
void sigDisplayOptionsChanged (const DisplayOptions &displayOptions)
void sigFilterOptionsChanged (const FilterOptions &filterOptions)
void sigKeyChanged (CSwordKey *key)
void sigModuleAdded (int index, QString module)
void sigModuleListChanged ()
void sigModuleListSet (QStringList modules)
void sigModuleRemoved (int index)
void sigModuleReplaced (int index, QString newModule)
void sigModulesChanged (const BtConstModuleList &modules)
Protected Slots inherited from CDisplayWindow
void lookup ()
virtual void modulesChanged ()
void printAll ()
void printAnchorWithText ()
void saveRawHTML ()
Protected Attributes inherited from CDisplayWindow
struct CDisplayWindow::ActionsStruct m_actions
Detailed Description
Author
The BibleTime team
Definition at line 25 of file ccommentaryreadwindow.h.
Constructor & Destructor Documentation
CCommentaryReadWindow()
CCommentaryReadWindow::CCommentaryReadWindow (QList< CSwordModuleInfo * > const & modules, CMDIArea * parent) inline
Definition at line 33 of file ccommentaryreadwindow.h.
Member Function Documentation
applyProfileSettings()
void CCommentaryReadWindow::applyProfileSettings (BtConfigCore const & windowConf) override virtual
Loads the settings of this window from configuration.
Parameters
[in] windowConf The locked configuration group.
Note
We don't use restoreGeometry/saveGeometry for MDI subwindows, because they give slightly incorrect results with some window managers. Might be related to Qt bug QTBUG-7634.
Reimplemented from CDisplayWindow.
Definition at line 86 of file ccommentaryreadwindow.cpp.
References CDisplayWindow::applyProfileSettings(), BT_ASSERT, m_syncButton, and BtConfigCore::value().
initActions()
void CCommentaryReadWindow::initActions () override protected virtual
Initializes the internel keyboard actions.
Reimplemented from CDisplayWindow.
Definition at line 65 of file ccommentaryreadwindow.cpp.
References BtActionCollection::action(), CDisplayWindow::actionCollection(), CResMgr::displaywindows::commentaryWindow::syncWindow::actionName, CDisplayWindow::initActions(), CDisplayWindow::initAddAction(), insertKeyboardActions(), m_syncButton, nextBook(), nextChapter(), nextVerse(), previousBook(), previousChapter(), previousVerse(), and BtActionCollection::readShortcuts().
initToolbars()
void CCommentaryReadWindow::initToolbars () override protected virtual
Initialize the toolbars.
Reimplemented from CDisplayWindow.
Definition at line 100 of file ccommentaryreadwindow.cpp.
References CDisplayWindow::buttonsToolBar(), CDisplayWindow::initToolbars(), and m_syncButton.
insertKeyboardActions()
void CCommentaryReadWindow::insertKeyboardActions (BtActionCollection *const a) static
Reimplementation.
Definition at line 30 of file ccommentaryreadwindow.cpp.
References CResMgr::displaywindows::bibleWindow::nextBook::accel, CResMgr::displaywindows::bibleWindow::previousBook::accel, CResMgr::displaywindows::bibleWindow::nextChapter::accel, CResMgr::displaywindows::bibleWindow::previousChapter::accel, CResMgr::displaywindows::bibleWindow::nextVerse::accel, CResMgr::displaywindows::bibleWindow::previousVerse::accel, CResMgr::displaywindows::commentaryWindow::syncWindow::accel, CResMgr::displaywindows::commentaryWindow::syncWindow::actionName, and BtActionCollection::addAction().
Referenced by initActions().
moduleType()
CSwordModuleInfo::ModuleType CCommentaryReadWindow::moduleType () const inline override virtual
Reimplemented from CDisplayWindow.
Definition at line 38 of file ccommentaryreadwindow.h.
References CSwordModuleInfo::Commentary.
nextBook
void CCommentaryReadWindow::nextBook () slot
Moves to the next book.
Definition at line 129 of file ccommentaryreadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseBook, and verseKey().
Referenced by initActions().
nextChapter
void CCommentaryReadWindow::nextChapter () slot
Moves to the next book.
Definition at line 141 of file ccommentaryreadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseChapter, and verseKey().
Referenced by initActions().
nextVerse
void CCommentaryReadWindow::nextVerse () slot
Moves to the next book.
Definition at line 153 of file ccommentaryreadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseVerse, and verseKey().
Referenced by initActions().
previousBook
void CCommentaryReadWindow::previousBook () slot
Moves one book behind.
Definition at line 135 of file ccommentaryreadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseBook, and verseKey().
Referenced by initActions().
previousChapter
void CCommentaryReadWindow::previousChapter () slot
Moves one book behind.
Definition at line 147 of file ccommentaryreadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseChapter, and verseKey().
Referenced by initActions().
previousVerse
void CCommentaryReadWindow::previousVerse () slot
Moves one book behind.
Definition at line 159 of file ccommentaryreadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseVerse, and verseKey().
Referenced by initActions().
reload
void CCommentaryReadWindow::reload (CSwordBackend::SetupChangedReason reason) override slot
Reimplementation to handle the keychooser refresh.
Definition at line 111 of file ccommentaryreadwindow.cpp.
References CDisplayWindow::actionCollection(), CSwordBackend::instance(), CDisplayWindow::keyChooser(), BtActionCollection::readShortcuts(), CKeyChooser::refreshContent(), CDisplayWindow::reload(), CSwordVerseKey::setLocale(), and verseKey().
setupMainWindowToolBars()
void CCommentaryReadWindow::setupMainWindowToolBars () override protected virtual
Called to add actions to mainWindow toolbars
Reimplemented from CDisplayWindow.
Definition at line 105 of file ccommentaryreadwindow.cpp.
References CDisplayWindow::btMainWindow(), m_syncButton, CDisplayWindow::setupMainWindowToolBars(), and BibleTime::toolsToolBar().
storeProfileSettings()
void CCommentaryReadWindow::storeProfileSettings (BtConfigCore & conf) const override virtual
Stores the settings of this window to configuration.
Parameters
[in] windowConf The locked configuration group.
Store the settings of this window in the given CProfileWindow object.
Note
We don't use saveGeometry/restoreGeometry for MDI subwindows, because they give slightly incorrect results with some window managers. Might be related to Qt bug QTBUG-7634.
Reimplemented from CDisplayWindow.
Definition at line 92 of file ccommentaryreadwindow.cpp.
References BT_ASSERT, m_syncButton, BtConfigCore::setValue(), and CDisplayWindow::storeProfileSettings().
syncAllowed()
bool CCommentaryReadWindow::syncAllowed () const override virtual
Returns whether syncs to the active window are allowed at this time for this display window
Returns
boolean value whether sync is allowed
Reimplemented from CDisplayWindow.
Definition at line 164 of file ccommentaryreadwindow.cpp.
References m_syncButton.
verseKey()
CSwordVerseKey * CCommentaryReadWindow::verseKey () private
rapper around key() to return the right type of key.
Definition at line 122 of file ccommentaryreadwindow.cpp.
References BT_ASSERT, and CDisplayWindow::key().
Referenced by nextBook(), nextChapter(), nextVerse(), previousBook(), previousChapter(), previousVerse(), and reload().
Member Data Documentation
m_syncButton
QAction* CCommentaryReadWindow::m_syncButton private
Definition at line 60 of file ccommentaryreadwindow.h.
Referenced by applyProfileSettings(), initActions(), initToolbars(), setupMainWindowToolBars(), storeProfileSettings(), and syncAllowed().
The documentation for this class was generated from the following files:
ccommentaryreadwindow.h
ccommentaryreadwindow.cpp