BibleTime: BtOpenWorkAction Class Reference
BtOpenWorkAction Class Reference
#include <btopenworkaction.h>
Signals
void triggered (CSwordModuleInfo *module)
Public Member Functions
BtOpenWorkAction (BtConfigCore groupingConfigGroup, QString groupingConfigKey, QObject *parent=nullptr)
~BtOpenWorkAction () override
Protected Member Functions
void retranslateUi ()
Private Attributes
BtOpenWorkActionMenu * m_menu
Detailed Description
Definition at line 68 of file btopenworkaction.h.
Constructor & Destructor Documentation
BtOpenWorkAction()
BtOpenWorkAction::BtOpenWorkAction (BtConfigCore groupingConfigGroup, QString groupingConfigKey, QObject * parent = nullptr) explicit
Definition at line 86 of file btopenworkaction.cpp.
References BT_CONNECT, CSwordBackend::instance(), m_menu, BtOpenWorkActionMenu::postFilterModel(), retranslateUi(), BtOpenWorkActionMenu::setSourceModel(), BtOpenWorkActionMenu::triggered(), and triggered().
~BtOpenWorkAction()
BtOpenWorkAction::~BtOpenWorkAction () override
Definition at line 117 of file btopenworkaction.cpp.
References m_menu.
Member Function Documentation
retranslateUi()
void BtOpenWorkAction::retranslateUi () protected
Definition at line 121 of file btopenworkaction.cpp.
Referenced by BtOpenWorkAction().
triggered
void BtOpenWorkAction::triggered (CSwordModuleInfo * module) signal
Referenced by BtOpenWorkAction(), and BibleTime::initActions().
Member Data Documentation
m_menu
BtOpenWorkActionMenu* BtOpenWorkAction::m_menu private
Definition at line 83 of file btopenworkaction.h.
Referenced by BtOpenWorkAction(), and ~BtOpenWorkAction().
The documentation for this class was generated from the following files:
btopenworkaction.h
btopenworkaction.cpp