BibleTime: CSwordVerseKey Class Reference
CSwordVerseKey Class Reference final
CSwordKey implementation for Sword's VerseKey.
#include <cswordversekey.h>
Public Types
enum JumpType { UseBook , UseChapter , UseVerse }
Public Types inherited from CSwordKey
enum TextRenderType { Normal , ProcessEntryAttributesOnly }
Public Member Functions
const BtSignal * afterChangedSignaller ()
sword::SWKey const & asSwordKey () const noexcept final override
char bibleBook () const
BibleTime_CSwordVerseKey_DEFINE_COMP (<=>) BibleTime_CSwordVerseKey_DEFINE_COMP(
char book () const
QString bookName () const
int chapter () const
CSwordVerseKey * copy () const final override
CSwordVerseKey (const CSwordModuleInfo *module)
CSwordVerseKey (const CSwordVerseKey &copy)
CSwordVerseKey (const sword::VerseKey *k, const CSwordModuleInfo *module)
void emitAfterChanged ()
long index () const
bool isBoundSet () const
QString key () const final override
CSwordVerseKey lowerBound () const
bool next (const JumpType type=JumpType::UseVerse)
QString normalizedKey () const final override
void positionToTop ()
bool previous (const JumpType type=JumpType::UseVerse)
void setBook (char v)
void setBookName (QString const &newBookName)
void setChapter (int v)
void setIndex (long v)
void setIntros (bool v)
bool setKey (const char *key) final override
bool setKey (const QString &key) final override
void setLocale (char const *const locale)
void setLowerBound (CSwordVerseKey const &bound)
void setModule (const CSwordModuleInfo *newModule) final override
void setSuffix (char v)
void setTestament (char v)
void setUpperBound (CSwordVerseKey const &bound)
void setVerse (int v)
void setVersification (const char *name)
QString shortText () const
char suffix () const
char testament () const
CSwordVerseKey upperBound () const
int verse () const
QString versification () const
~CSwordVerseKey () override
Public Member Functions inherited from CSwordKey
bool isValid () const
CSwordModuleInfo const * module () const
CSwordKey & operator= (CSwordKey const &)=delete
QString rawText ()
QString renderedText (const CSwordKey::TextRenderType mode=CSwordKey::Normal)
QString strippedText ()
virtual ~CSwordKey () noexcept
Protected Member Functions
const char * rawKey () const final override
Protected Member Functions inherited from CSwordKey
CSwordKey (CSwordKey const &copy)=default
CSwordKey (CSwordModuleInfo const *const module=nullptr)
Private Attributes
QPointer< BtSignal > m_afterChangedSignaller
sword::VerseKey m_key
Additional Inherited Members
Protected Attributes inherited from CSwordKey
const CSwordModuleInfo * m_module
bool m_valid = true
Detailed Description
CSwordKey implementation for Sword's VerseKey.
The CSwordKey implementation for verse based modules (Bibles and Commentaries)
This class is the implementation of CKey for verse based modules like Bibles and commentaries. This class provides the special functions to work with the verse based modules.
Useful functions are
See also
NextBook()
PreviousBook()
NextChapter()
PreviousChapter()
NextVerse()
PreviousVerse().
Call the constructor only with valid verse based modules, otherwise this key will be invalid and the application will probably crash.
Version
Id
cswordversekey.h,v 1.26 2006/02/25 11:38:15 joachim Exp
Author
The BibleTime team
Definition at line 62 of file cswordversekey.h.
Member Enumeration Documentation
JumpType
enum CSwordVerseKey::JumpType
Enumerator
UseBook
UseChapter
UseVerse
Definition at line 65 of file cswordversekey.h.
Constructor & Destructor Documentation
CSwordVerseKey() [1/3]
CSwordVerseKey::CSwordVerseKey (const CSwordModuleInfo * module)
Constructs a versekey with the current module position and setups the m_module members.
Definition at line 37 of file cswordversekey.cpp.
References m_key, CSwordKey::module(), and setKey().
CSwordVerseKey() [2/3]
CSwordVerseKey::CSwordVerseKey (const CSwordVerseKey & copy)
Definition at line 50 of file cswordversekey.cpp.
References m_key.
CSwordVerseKey() [3/3]
CSwordVerseKey::CSwordVerseKey (const sword::VerseKey * k, const CSwordModuleInfo * module)
Constructs a CSwordVerseKey using the given module at the position given by the versekey.
Parameters
[in] k Position to use.
[in] module Module to use.
Definition at line 55 of file cswordversekey.cpp.
~CSwordVerseKey()
CSwordVerseKey::~CSwordVerseKey () override
Definition at line 61 of file cswordversekey.cpp.
References m_afterChangedSignaller.
Member Function Documentation
afterChangedSignaller()
const BtSignal * CSwordVerseKey::afterChangedSignaller ()
Definition at line 384 of file cswordversekey.cpp.
References m_afterChangedSignaller.
asSwordKey()
sword::SWKey const & CSwordVerseKey::asSwordKey () const final override virtual noexcept
Returns
a reference to this object as a sword::SWKey.
Implements CSwordKey.
Definition at line 63 of file cswordversekey.cpp.
References m_key.
bibleBook()
char CSwordVerseKey::bibleBook () const
Return book number within entire bible
Definition at line 110 of file cswordversekey.cpp.
References book(), m_key, and testament().
Referenced by BtBibleKeyWidget::populateChapterMenu().
BibleTime_CSwordVerseKey_DEFINE_COMP()
CSwordVerseKey::BibleTime_CSwordVerseKey_DEFINE_COMP (<=)
book()
char CSwordVerseKey::book () const inline
Return book number within a testament
Definition at line 156 of file cswordversekey.h.
References m_key.
Referenced by bibleBook(), and CBibleReadWindow::saveChapter().
bookName()
QString CSwordVerseKey::bookName () const
This functions returns the current book as localised text, not as book numer.
Use "char Book()" to retrieve the book number of the current book.
Returns
The name of the current book
Returns the current book as Text, not as integer.
Definition at line 126 of file cswordversekey.cpp.
References CSwordBibleModuleInfo::hasOldTestament(), m_key, and CSwordKey::module().
Referenced by CSwordBibleModuleInfo::books(), CBibleReadWindow::copyDisplayedText(), Rendering::CDisplayRendering::entryLink(), BtBibleKeyWidget::populateVerseMenu(), BtModelViewReadDisplay::print(), and CExportManager::saveKey().
chapter()
int CSwordVerseKey::chapter () const inline
Definition at line 159 of file cswordversekey.h.
References m_key.
Referenced by CBibleReadWindow::copyDisplayedText(), Rendering::CDisplayRendering::entryLink(), BtBibleKeyWidget::populateVerseMenu(), BtModelViewReadDisplay::print(), Rendering::CDisplayRendering::renderDisplayEntry(), CBibleReadWindow::saveChapter(), CExportManager::saveKey(), and Search::BtSearchResultArea::updatePreview().
copy()
CSwordVerseKey * CSwordVerseKey::copy () const final override virtual
Clones this object.
Implements CSwordKey.
Definition at line 67 of file cswordversekey.cpp.
emitAfterChanged()
void CSwordVerseKey::emitAfterChanged ()
This is called after a key change to emit a signal.
Definition at line 392 of file cswordversekey.cpp.
References m_afterChangedSignaller.
Referenced by next(), previous(), setKey(), and setModule().
index()
long CSwordVerseKey::index () const inline
Definition at line 165 of file cswordversekey.h.
References m_key.
Referenced by CSwordModuleInfo::buildIndex(), and BibleTime::processCommandline().
isBoundSet()
bool CSwordVerseKey::isBoundSet () const inline
Definition at line 150 of file cswordversekey.h.
References m_key.
Referenced by CExportManager::copyKey(), Rendering::CDisplayRendering::entryLink(), and CExportManager::saveKey().
key()
QString CSwordVerseKey::key () const final override virtual
Sets the key we use to the parameter.
Implements CSwordKey.
Definition at line 163 of file cswordversekey.cpp.
References m_key.
Referenced by CSwordBibleModuleInfo::books(), Rendering::CDisplayRendering::entryLink(), Rendering::CrossRefRendering::entryLink(), BtPrinter::entryLink(), Rendering::CTextRendering::KeyTreeItem::KeyTreeItem(), next(), normalizedKey(), ReferenceManager::parseVerseReference(), previous(), BtModelViewReadDisplay::print(), BibleTime::processCommandline(), Rendering::CDisplayRendering::renderDisplayEntry(), Rendering::CTextRendering::renderKeyRange(), BtBibleKeyWidget::setKey(), and BtBibleKeyWidget::updateText().
lowerBound()
CSwordVerseKey CSwordVerseKey::lowerBound () const
Definition at line 113 of file cswordversekey.cpp.
References m_key, and CSwordKey::module().
Referenced by CExportManager::copyKey(), Rendering::CDisplayRendering::entryLink(), and CExportManager::saveKey().
next()
bool CSwordVerseKey::next (const JumpType type = JumpType::UseVerse)
Jumps to the next entry of the given type
Definition at line 204 of file cswordversekey.cpp.
References emitAfterChanged(), key(), m_key, CSwordKey::m_module, CSwordKey::module(), setKey(), CSwordModuleInfo::swordModule(), UseBook, UseChapter, and UseVerse.
Referenced by CSwordBibleModuleInfo::books(), BtBibleKeyWidget::BtBibleKeyWidget(), Rendering::CTextRendering::KeyTreeItem::KeyTreeItem(), and Search::BtSearchResultArea::updatePreview().
normalizedKey()
QString CSwordVerseKey::normalizedKey () const final override virtual
Returns
the normalized (English) key.
Reimplemented from CSwordKey.
Definition at line 169 of file cswordversekey.cpp.
References key(), and m_key.
positionToTop()
void CSwordVerseKey::positionToTop () inline
Definition at line 167 of file cswordversekey.h.
References m_key.
Referenced by BibleTime::processCommandline().
previous()
bool CSwordVerseKey::previous (const JumpType type = JumpType::UseVerse)
Jumps to the previous entry of the given type
Warning
Weird comment:
Definition at line 297 of file cswordversekey.cpp.
References emitAfterChanged(), key(), m_key, CSwordKey::m_module, CSwordKey::module(), setKey(), CSwordModuleInfo::swordModule(), UseBook, UseChapter, and UseVerse.
Referenced by BtBibleKeyWidget::BtBibleKeyWidget(), and Search::BtSearchResultArea::updatePreview().
rawKey()
const char * CSwordVerseKey::rawKey () const final override protected virtual
Returns
the encoded key appropriate for use directly with Sword.
Implements CSwordKey.
Definition at line 180 of file cswordversekey.cpp.
References m_key.
setBook()
void CSwordVerseKey::setBook (char v) inline
Definition at line 158 of file cswordversekey.h.
References m_key.
setBookName()
void CSwordVerseKey::setBookName (QString const & newBookName) inline
Definition at line 135 of file cswordversekey.h.
References m_key, and setBookName().
Referenced by setBookName().
setChapter()
void CSwordVerseKey::setChapter (int v) inline
Definition at line 160 of file cswordversekey.h.
References m_key.
Referenced by Rendering::CDisplayRendering::renderDisplayEntry(), and Search::BtSearchResultArea::updatePreview().
setIndex()
void CSwordVerseKey::setIndex (long v) inline
Definition at line 166 of file cswordversekey.h.
References m_key.
Referenced by BibleTime::processCommandline(), and Rendering::CTextRendering::renderEntry().
setIntros()
void CSwordVerseKey::setIntros (bool v) inline
Definition at line 151 of file cswordversekey.h.
References m_key.
Referenced by Rendering::CDisplayRendering::entryLink(), Rendering::CDisplayRendering::renderDisplayEntry(), Rendering::CTextRendering::renderEntry(), and Search::BtSearchResultArea::updatePreview().
setKey() [1/2]
bool CSwordVerseKey::setKey (const char * key) final override virtual
Set the key using a utf8-decoded c-string.
Parameters
[in] key The key which should be used to set the current one.
Todo:
Do we ALWAYS need to emit this signal
Implements CSwordKey.
Definition at line 186 of file cswordversekey.cpp.
References emitAfterChanged(), m_key, and CSwordKey::m_valid.
setKey() [2/2]
bool CSwordVerseKey::setKey (const QString & key) final override virtual
Sets the current key using a utf8 enabled QString.
Parameters
[in] key The key which should be used to set the current one.
Implements CSwordKey.
Definition at line 182 of file cswordversekey.cpp.
References setKey().
Referenced by CSwordBibleModuleInfo::books(), CSwordVerseKey(), Rendering::CDisplayRendering::entryLink(), Rendering::CrossRefRendering::entryLink(), BtPrinter::entryLink(), Rendering::CTextRendering::KeyTreeItem::KeyTreeItem(), next(), ReferenceManager::parseVerseReference(), previous(), Rendering::CDisplayRendering::renderDisplayEntry(), setKey(), BtBibleKeyWidget::setKey(), setModule(), and Search::BtSearchResultArea::updatePreview().
setLocale()
void CSwordVerseKey::setLocale (char const *const locale) inline
Definition at line 149 of file cswordversekey.h.
References m_key.
Referenced by ReferenceManager::parseVerseReference(), CBibleReadWindow::reload(), and CCommentaryReadWindow::reload().
setLowerBound()
void CSwordVerseKey::setLowerBound (CSwordVerseKey const & bound)
Definition at line 116 of file cswordversekey.cpp.
References m_key.
Referenced by CBibleReadWindow::copyDisplayedText(), and CBibleReadWindow::saveChapter().
setModule()
void CSwordVerseKey::setModule (const CSwordModuleInfo * newModule) final override virtual
Sets the module for this key
Remap key position to new versification
Limit to Bible bounds
Reimplemented from CSwordKey.
Definition at line 71 of file cswordversekey.cpp.
References CSwordModuleInfo::Bible, BT_ASSERT, CSwordModuleInfo::Commentary, emitAfterChanged(), CSwordBibleModuleInfo::lowerBound(), m_key, CSwordKey::m_module, CSwordKey::m_valid, setKey(), CSwordModuleInfo::swordModule(), CSwordModuleInfo::type(), and CSwordBibleModuleInfo::upperBound().
Referenced by BtBibleKeyWidget::setModule().
setSuffix()
void CSwordVerseKey::setSuffix (char v) inline
Definition at line 164 of file cswordversekey.h.
References m_key.
setTestament()
void CSwordVerseKey::setTestament (char v) inline
Definition at line 153 of file cswordversekey.h.
References m_key.
setUpperBound()
void CSwordVerseKey::setUpperBound (CSwordVerseKey const & bound)
Definition at line 122 of file cswordversekey.cpp.
References m_key.
Referenced by CBibleReadWindow::copyDisplayedText(), and CBibleReadWindow::saveChapter().
setVerse()
void CSwordVerseKey::setVerse (int v) inline
Definition at line 162 of file cswordversekey.h.
References m_key.
Referenced by CBibleReadWindow::copyDisplayedText(), BtModelViewReadDisplay::print(), Rendering::CDisplayRendering::renderDisplayEntry(), CBibleReadWindow::saveChapter(), and Search::BtSearchResultArea::updatePreview().
setVersification()
void CSwordVerseKey::setVersification (const char * name) inline
Definition at line 175 of file cswordversekey.h.
References m_key.
shortText()
QString CSwordVerseKey::shortText () const inline
Definition at line 146 of file cswordversekey.h.
References m_key.
Referenced by Rendering::CDisplayRendering::entryLink(), Rendering::CrossRefRendering::entryLink(), and BtPrinter::entryLink().
suffix()
char CSwordVerseKey::suffix () const inline
Definition at line 163 of file cswordversekey.h.
References m_key.
testament()
char CSwordVerseKey::testament () const inline
Definition at line 152 of file cswordversekey.h.
References m_key.
Referenced by bibleBook().
upperBound()
CSwordVerseKey CSwordVerseKey::upperBound () const
Definition at line 119 of file cswordversekey.cpp.
References m_key, and CSwordKey::module().
Referenced by CExportManager::copyKey(), Rendering::CDisplayRendering::entryLink(), and CExportManager::saveKey().
verse()
int CSwordVerseKey::verse () const inline
Definition at line 161 of file cswordversekey.h.
References m_key.
Referenced by Rendering::CDisplayRendering::entryLink(), Rendering::CrossRefRendering::entryLink(), BtPrinter::entryLink(), Rendering::CDisplayRendering::renderDisplayEntry(), and Search::BtSearchResultArea::updatePreview().
versification()
QString CSwordVerseKey::versification () const inline
Definition at line 172 of file cswordversekey.h.
References m_key.
Member Data Documentation
m_afterChangedSignaller
QPointer<BtSignal> CSwordVerseKey::m_afterChangedSignaller private
Definition at line 191 of file cswordversekey.h.
Referenced by afterChangedSignaller(), emitAfterChanged(), and ~CSwordVerseKey().
m_key
sword::VerseKey CSwordVerseKey::m_key private
Definition at line 190 of file cswordversekey.h.
Referenced by asSwordKey(), bibleBook(), book(), bookName(), chapter(), CSwordVerseKey(), CSwordVerseKey(), index(), isBoundSet(), key(), lowerBound(), next(), normalizedKey(), positionToTop(), previous(), rawKey(), setBook(), setBookName(), setChapter(), setIndex(), setIntros(), setKey(), setLocale(), setLowerBound(), setModule(), setSuffix(), setTestament(), setUpperBound(), setVerse(), setVersification(), shortText(), suffix(), testament(), upperBound(), verse(), and versification().
The documentation for this class was generated from the following files:
cswordversekey.h
cswordversekey.cpp