BibleTime: cswordsetupinstallsourcesdialog.cpp File Reference
cswordsetupinstallsourcesdialog.cpp File Reference
#include "cswordsetupinstallsourcesdialog.h"
#include <QByteArray>
#include <QComboBox>
#include <QDebug>
#include <QDir>
#include <QFileInfo>
#include <QFileDialog>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QLineEdit>
#include <QMessageBox>
#include <QNonConstOverload>
#include <QPushButton>
#include <Qt>
#include <QVBoxLayout>
#include <QDialogButtonBox>
#include <QProgressDialog>
#include <QApplication>
#include "../../backend/btinstallbackend.h"
#include "../../backend/btinstallmgr.h"
#include "../../util/btconnect.h"
#include "../messagedialog.h"
#include <installmgr.h>
#include <swbuf.h>
Functions
const QString PROTO_FILE (QObject::tr("Local"))
const QString PROTO_FTP (QObject::tr("Remote FTP"))
const QString PROTO_HTTP (QObject::tr("Remote HTTP"))
const QString PROTO_HTTPS (QObject::tr("Remote HTTPS"))
const QString PROTO_SFTP (QObject::tr("Remote SFTP"))
Function Documentation
PROTO_FILE()
const QString PROTO_FILE (QObject::tr("Local"))
Referenced by CSwordSetupInstallSourcesDialog::CSwordSetupInstallSourcesDialog().
PROTO_FTP()
const QString PROTO_FTP (QObject::tr("Remote FTP"))
Referenced by CSwordSetupInstallSourcesDialog::CSwordSetupInstallSourcesDialog(), CSwordSetupInstallSourcesDialog::getSource(), and CSwordSetupInstallSourcesDialog::isRemote().
PROTO_HTTP()
const QString PROTO_HTTP (QObject::tr("Remote HTTP"))
Referenced by CSwordSetupInstallSourcesDialog::CSwordSetupInstallSourcesDialog(), CSwordSetupInstallSourcesDialog::getSource(), and CSwordSetupInstallSourcesDialog::isRemote().
PROTO_HTTPS()
const QString PROTO_HTTPS (QObject::tr("Remote HTTPS"))
Referenced by CSwordSetupInstallSourcesDialog::CSwordSetupInstallSourcesDialog(), CSwordSetupInstallSourcesDialog::getSource(), and CSwordSetupInstallSourcesDialog::isRemote().
PROTO_SFTP()
const QString PROTO_SFTP (QObject::tr("Remote SFTP"))
Referenced by CSwordSetupInstallSourcesDialog::CSwordSetupInstallSourcesDialog(), CSwordSetupInstallSourcesDialog::getSource(), and CSwordSetupInstallSourcesDialog::isRemote().