BibleTime: Search::CRangeChooserDialog::RangeItem Class Reference
Search::CRangeChooserDialog::RangeItem Class Reference
Public Member Functions
QString caption () const
QString const & range () const
RangeItem (QString const &caption, QString const &range=QString(), QListWidget *parent=nullptr)
void setCaption (QString const &caption)
void setRange (QString const &range)
Private Attributes
QString m_range
Detailed Description
Definition at line 39 of file crangechooserdialog.h.
Constructor & Destructor Documentation
RangeItem()
Search::CRangeChooserDialog::RangeItem::RangeItem (QString const & caption, QString const & range = QString(), QListWidget * parent = nullptr) inline
Definition at line 43 of file crangechooserdialog.h.
Member Function Documentation
caption()
QString Search::CRangeChooserDialog::RangeItem::caption () const inline
Definition at line 49 of file crangechooserdialog.h.
Referenced by Search::CRangeChooserDialog::accept(), Search::CRangeChooserDialog::resetEditControls(), and setCaption().
range()
QString const & Search::CRangeChooserDialog::RangeItem::range () const inline
Definition at line 51 of file crangechooserdialog.h.
References m_range.
Referenced by Search::CRangeChooserDialog::accept(), Search::CRangeChooserDialog::resetEditControls(), and setRange().
setCaption()
void Search::CRangeChooserDialog::RangeItem::setCaption (QString const & caption) inline
Definition at line 50 of file crangechooserdialog.h.
References caption().
Referenced by Search::CRangeChooserDialog::saveCurrentToRange().
setRange()
void Search::CRangeChooserDialog::RangeItem::setRange (QString const & range) inline
Definition at line 52 of file crangechooserdialog.h.
References m_range, and range().
Referenced by Search::CRangeChooserDialog::saveCurrentToRange().
Member Data Documentation
m_range
QString Search::CRangeChooserDialog::RangeItem::m_range private
Definition at line 56 of file crangechooserdialog.h.
Referenced by range(), and setRange().
The documentation for this class was generated from the following file:
crangechooserdialog.h