BibleTime: CConfigurationDialog Class Reference
CConfigurationDialog Class Reference
#include <cconfigurationdialog.h>
Public Member Functions
CConfigurationDialog (QWidget *const parent=nullptr, Qt::WindowFlags const f=Qt::WindowFlags())
~CConfigurationDialog () noexcept override
Public Member Functions inherited from BtConfigDialog
void addPage (Page *const pageWidget)
Adds the page to this dialog, taking ownership.
BtConfigDialog (QWidget *const parent=nullptr, Qt::WindowFlags const flags=Qt::WindowFlags())
void save ()
Additional Inherited Members
Signals inherited from BtConfigDialog
void signalSettingsChanged ()
Detailed Description
Definition at line 24 of file cconfigurationdialog.h.
Constructor & Destructor Documentation
CConfigurationDialog()
CConfigurationDialog::CConfigurationDialog (QWidget *const parent = nullptr, Qt::WindowFlags const f = Qt::WindowFlags())
Definition at line 28 of file cconfigurationdialog.cpp.
References BtConfigDialog::addPage(), and btConfig().
~CConfigurationDialog()
CConfigurationDialog::~CConfigurationDialog () override noexcept
Definition at line 46 of file cconfigurationdialog.cpp.
References btConfig(), and BtConfigCore::setValue().
The documentation for this class was generated from the following files:
cconfigurationdialog.h
cconfigurationdialog.cpp