BibleTime: BtConfig Class Reference
BtConfig Class Reference
#include <btconfig.h>
Public Types
using FontSettingsPair = QPair< bool, QFont >
using ShortcutsMap = QHash< QString, QList< QKeySequence > >
using StringMap = QMap< QString, QString >
Public Member Functions
QString addSession (const QString &name)
Creates a new session with the given name.
QString booknameLanguage ()
const QString & currentSessionKey () const
QString currentSessionName () const
void deleteSearchScopesWithCurrentLocale ()
void deleteSession (const QString &key)
Deletes the session with the given key.
const QFont & getDefaultFont () const
CSwordModuleInfo * getDefaultSwordModuleByType (const QString &moduleType)
Returns default sword module info class for a given module type.
DisplayOptions getDisplayOptions () const
FilterOptions getFilterOptions () const
FontSettingsPair getFontForLanguage (Language const &language)
Get font for a language.
QString getModuleEncryptionKey (const QString &name)
Function to get a module decryption key.
StringMap getSearchScopesForCurrentLocale (const QStringList &scopeModules)
ShortcutsMap getShortcuts (QString const &shortcutGroup)
Gets the shortcuts for the given group.
BtConfigCore session () const
QHash< QString, QString > sessionNames () const
void setCurrentSession (const QString &key)
Notifies the configuration system that the session settings should be read from and saved to the given session.
void setDefaultSwordModuleByType (const QString &moduleType, const CSwordModuleInfo *const module)
Sets the default sword module for a module type.
void setFontForLanguage (Language const &language, FontSettingsPair const &fontSettings)
Set font for a language.
void setModuleEncryptionKey (const QString &name, const QString &key)
Function to set a module decryption key.
void setSearchScopesWithCurrentLocale (const QStringList &scopeModules, StringMap searchScopes)
void setShortcuts (QString const &shortcutGroup, ShortcutsMap const &shortcuts)
Sets the shortcuts for the given group.
Public Member Functions inherited from BtConfigCore
BtConfigCore (BtConfigCore &&)=default
BtConfigCore (BtConfigCore const &)=default
QStringList childGroups () const
QStringList childKeys () const
template<typename Prefix >
BtConfigCore group (Prefix &&prefix) &&
template<typename Prefix >
BtConfigCore group (Prefix &&prefix) const &
BtConfigCore & operator= (BtConfigCore &&)=default
BtConfigCore & operator= (BtConfigCore const &)=default
QVariant qVariantValue (QString const &key, QVariant const &defaultValue=QVariant()) const
Returns the settings value for the given global key as a QVariant.
void remove (QString const &key)
removes a key (and its children) from the current group.
template<typename T >
void setValue (QString const &key, T const &value)
Sets a value for a key.
void sync ()
Synchronizes the configuration to disk.
template<typename T >
T value (QString const &key, T const &defaultValue=T()) const
Returns the settings value for the given global key.
~BtConfigCore ()
Static Public Member Functions
static BtConfig & getInstance ()
static DisplayOptions loadDisplayOptionsFromGroup (BtConfigCore const &group)
static FilterOptions loadFilterOptionsFromGroup (BtConfigCore const &group)
static sword::ListKey parseVerseListWithModules (const QString &data, const QStringList &scopeModules)
static void storeDisplayOptionsToGroup (DisplayOptions const &options, BtConfigCore &group)
Saves the current display options.
static void storeFilterOptionsToGroup (FilterOptions const &options, BtConfigCore &group)
Saves the current filter options.
Private Types
using FontCacheMap = QHash< Language const *, FontSettingsPair >
enum InitState { INIT_NEED_UNIMPLEMENTED_BACKWARD_MIGRATE = -2, INIT_OK = 0, INIT_NEED_UNIMPLEMENTED_FORWARD_MIGRATE = 2 }
Private Member Functions
BtConfig (const QString &settingsFile)
Static Private Member Functions
static void destroyInstance ()
static void forceMigrate ()
static InitState initBtConfig ()
Private Attributes
QString m_currentSessionKey
QFont m_defaultFont
default font used when no special one is set
FontCacheMap m_fontCache
a cache for the fonts saved in the configuration file for speed
QHash< QString, QString > m_sessionNames
Static Private Attributes
static StringMap m_defaultSearchScopes
static BtConfig * m_instance = nullptr
singleton instance
Friends
class BibleTimeApp
Detailed Description
Definition at line 35 of file btconfig.h.
Member Typedef Documentation
FontCacheMap
using BtConfig::FontCacheMap = QHash<Language const *, FontSettingsPair> private
Definition at line 53 of file btconfig.h.
FontSettingsPair
using BtConfig::FontSettingsPair = QPair<bool, QFont>
The first parameter indicates whether the custom font should be used or not. The second parameter is the custom font that has been set.
Definition at line 47 of file btconfig.h.
ShortcutsMap
using BtConfig::ShortcutsMap = QHash<QString, QList<QKeySequence> >
Definition at line 49 of file btconfig.h.
StringMap
using BtConfig::StringMap = QMap<QString, QString>
Definition at line 48 of file btconfig.h.
Member Enumeration Documentation
InitState
enum BtConfig::InitState private
Enumerator
INIT_NEED_UNIMPLEMENTED_BACKWARD_MIGRATE
INIT_OK
INIT_NEED_UNIMPLEMENTED_FORWARD_MIGRATE
Definition at line 55 of file btconfig.h.
Constructor & Destructor Documentation
BtConfig()
BtConfig::BtConfig (const QString & settingsFile) explicit private
Definition at line 65 of file btconfig.cpp.
References BT_ASSERT, BtConfigCore::group(), anonymous_namespace{btconfig.cpp}::GROUP_SESSIONS, anonymous_namespace{btconfig.cpp}::KEY_CURRENT_SESSION, anonymous_namespace{btconfig.cpp}::KEY_SESSION_NAME, m_currentSessionKey, m_defaultFont, m_defaultSearchScopes, m_instance, m_sessionNames, and BtConfigCore::setValue().
Member Function Documentation
addSession()
QString BtConfig::addSession (const QString & name)
Creates a new session with the given name.
Precondition
The given name must not be an empty string.
Parameters
[in] name the name of the session
Returns
the key of the created session.
Definition at line 161 of file btconfig.cpp.
References BT_ASSERT, anonymous_namespace{btconfig.cpp}::KEY_SESSION_NAME, m_sessionNames, and BtConfigCore::setValue().
Referenced by BibleTime::saveToNewProfile().
booknameLanguage()
QString BtConfig::booknameLanguage ()
Returns
the configured language code for book names.
Definition at line 427 of file btconfig.cpp.
References BtConfigCore::setValue().
Referenced by CDisplaySettingsPage::bookNameAbbreviationsTryVector().
currentSessionKey()
const QString& BtConfig::currentSessionKey () const inline
Returns
the key of the current session.
Definition at line 68 of file btconfig.h.
References m_currentSessionKey.
Referenced by BibleTime::refreshProfileMenus().
currentSessionName()
QString BtConfig::currentSessionName () const inline
Returns
the name of the current session.
Definition at line 73 of file btconfig.h.
References BT_ASSERT, m_currentSessionKey, and m_sessionNames.
deleteSearchScopesWithCurrentLocale()
void BtConfig::deleteSearchScopesWithCurrentLocale ()
Deletes the searchScopes given in the current locale.
Definition at line 453 of file btconfig.cpp.
References BtConfigCore::remove().
deleteSession()
void BtConfig::deleteSession (const QString & key)
Deletes the session with the given key.
Precondition
The session with the given key must exist.
The session with the given key must not be the current session.
Parameters
[in] key the key of the session to delete.
Postcondition
The session with the given key and its settings are deleted.
Returns
whether deleting the session was successful.
Definition at line 189 of file btconfig.cpp.
References BT_ASSERT, anonymous_namespace{btconfig.cpp}::GROUP_SESSIONS_PREFIX, m_currentSessionKey, m_sessionNames, and BtConfigCore::remove().
Referenced by BibleTime::deleteProfile().
destroyInstance()
void BtConfig::destroyInstance () static private
Definition at line 200 of file btconfig.cpp.
References m_instance.
Referenced by BibleTimeApp::~BibleTimeApp().
forceMigrate()
void BtConfig::forceMigrate () static private
Definition at line 145 of file btconfig.cpp.
References BTCONFIG_API_VERSION, anonymous_namespace{btconfig.cpp}::BTCONFIG_API_VERSION_KEY, m_instance, and BtConfigCore::setValue().
Referenced by BibleTimeApp::initBtConfig().
getDefaultFont()
const QFont& BtConfig::getDefaultFont () const inline
Returns a default font that is suitable for the current language.
Returns
QFont suitable for current language.
Definition at line 194 of file btconfig.h.
References m_defaultFont.
Referenced by CDisplayTemplateMgr::fillTemplate(), getFontForLanguage(), and BtQmlInterface::getFontsFromSettings().
getDefaultSwordModuleByType()
CSwordModuleInfo * BtConfig::getDefaultSwordModuleByType (const QString & moduleType)
Returns default sword module info class for a given module type.
This is basically a convenience function for getting the respective "settings/defaults/ *" variable and searching that module manually. If module is not installed 0 will be returned.
Parameters
[in] moduleType module type to return the default sword module info for
Returns
sword module info pointer or 0
Definition at line 457 of file btconfig.cpp.
References CSwordBackend::findModuleByName(), and CSwordBackend::instance().
Referenced by BtQmlInterface::configModuleByType(), ReferenceManager::decodeHyperlink(), BibleTime::processCommandline(), anonymous_namespace{osistohtml.cpp}::renderReference(), and BibleTime::slotSearchDefaultBible().
getDisplayOptions()
DisplayOptions BtConfig::getDisplayOptions () const inline
Definition at line 178 of file btconfig.h.
References BtConfigCore::group(), loadDisplayOptionsFromGroup(), and session().
getFilterOptions()
FilterOptions BtConfig::getFilterOptions () const inline
Definition at line 162 of file btconfig.h.
References BtConfigCore::group(), loadFilterOptionsFromGroup(), and session().
Referenced by BtBookmarksModelPrivate::BookmarkItem::toolTip().
getFontForLanguage()
BtConfig::FontSettingsPair BtConfig::getFontForLanguage (Language const & language)
Get font for a language.
Gets a FontSettingsPair for the language given. If no font has been saved a default font is returned.
Parameters
[in] language pointer to a language to get the font for.
Returns
FontSettingsPair for given language
Todo:
Definition at line 335 of file btconfig.cpp.
References Language::abbrev(), BT_ASSERT, Language::englishName(), getDefaultFont(), m_fontCache, and BtConfigCore::qVariantValue().
Referenced by CBookKeyChooser::adjustFont(), BtFontSettingsPage::BtFontSettingsPage(), CDisplayTemplateMgr::fillTemplate(), and BtQmlInterface::getFontsFromSettings().
getInstance()
BtConfig & BtConfig::getInstance () static
Definition at line 148 of file btconfig.cpp.
References BT_ASSERT, and m_instance.
Referenced by btConfig().
getModuleEncryptionKey()
QString BtConfig::getModuleEncryptionKey (const QString & name)
Function to get a module decryption key.
This helper function will retrieve a previously set module decryption key from the configuration. If the key is not set it will return a null string.
Parameters
[in] name Name of module to retrieve the key for
Returns
Decryption key as a string
Definition at line 212 of file btconfig.cpp.
References BT_ASSERT.
Referenced by CSwordModuleInfo::config().
getSearchScopesForCurrentLocale()
BtConfig::StringMap BtConfig::getSearchScopesForCurrentLocale (const QStringList & scopeModules)
Todo:
: unit test these functions
Returns the searchScopes for the current locale.
This function retrieves the search scopes of the "properties/searchScopes" property and converts them to the current locale.
Returns
Search scopes in current locale.
Definition at line 380 of file btconfig.cpp.
References m_defaultSearchScopes, and parseVerseListWithModules().
Referenced by Search::BtSearchOptionsArea::searchScope().
getShortcuts()
BtConfig::ShortcutsMap BtConfig::getShortcuts (QString const & shortcutGroup)
Gets the shortcuts for the given group.
Returns a hash of shortcuts for strings for the respective shortcut group.
Parameters
[in] shortcutGroup The group to retrieve shortcuts for.
Returns
Hash of strings and lists of shortcuts.
Definition at line 217 of file btconfig.cpp.
References BtConfigCore::group().
Referenced by BtActionCollection::readShortcuts().
initBtConfig()
BtConfig::InitState BtConfig::initBtConfig () static private
Definition at line 125 of file btconfig.cpp.
References BT_ASSERT, BtConfigCore::BtConfig, BTCONFIG_API_VERSION, anonymous_namespace{btconfig.cpp}::BTCONFIG_API_VERSION_KEY, util::directory::getUserBaseDir(), INIT_NEED_UNIMPLEMENTED_BACKWARD_MIGRATE, INIT_NEED_UNIMPLEMENTED_FORWARD_MIGRATE, INIT_OK, m_instance, BtConfigCore::setValue(), and BtConfigCore::value().
Referenced by BibleTimeApp::initBtConfig().
loadDisplayOptionsFromGroup()
DisplayOptions BtConfig::loadDisplayOptionsFromGroup (BtConfigCore const & group) static
Returns
DisplayOptions structure containing display settings.
Definition at line 295 of file btconfig.cpp.
References BtConfigCore::group(), DisplayOptions::lineBreaks, and DisplayOptions::verseNumbers.
Referenced by CBibleReadWindow::applyProfileSettings(), and getDisplayOptions().
loadFilterOptionsFromGroup()
FilterOptions BtConfig::loadFilterOptionsFromGroup (BtConfigCore const & group) static
Returns
FilterOptions structure containing filter settings.
Definition at line 258 of file btconfig.cpp.
References FilterOptions::footnotes, FilterOptions::greekAccents, BtConfigCore::group(), FilterOptions::headings, FilterOptions::hebrewCantillation, FilterOptions::hebrewPoints, FilterOptions::lemmas, FilterOptions::morphSegmentation, FilterOptions::morphTags, FilterOptions::redLetterWords, FilterOptions::scriptureReferences, FilterOptions::strongNumbers, and FilterOptions::textualVariants.
Referenced by CBibleReadWindow::applyProfileSettings(), and getFilterOptions().
parseVerseListWithModules()
sword::ListKey BtConfig::parseVerseListWithModules (const QString & data, const QStringList & scopeModules) static
Definition at line 440 of file btconfig.cpp.
References CSwordBackend::findModuleByName(), CSwordBackend::instance(), and CSwordModuleInfo::module().
Referenced by getSearchScopesForCurrentLocale(), Search::BtSearchOptionsArea::searchScope(), and setSearchScopesWithCurrentLocale().
session()
BtConfigCore BtConfig::session () const
Definition at line 197 of file btconfig.cpp.
References BtConfigCore::group(), anonymous_namespace{btconfig.cpp}::GROUP_SESSIONS_PREFIX, and m_currentSessionKey.
Referenced by BtEditTextPage::BtEditTextPage(), BtTextFiltersTab::BtTextFiltersTab(), BibleTime::createMenuAndToolBar(), getDisplayOptions(), getFilterOptions(), BibleTime::initActions(), BtEditTextPage::initHtmlFont(), BibleTime::reloadProfile(), BtTextFiltersTab::save(), BibleTime::saveProfile(), BibleTime::showOrHideToolBars(), BibleTime::slotToggleMainToolbar(), BibleTime::slotToggleNavigatorToolbar(), BibleTime::slotToggleTextWindowHeader(), BibleTime::slotToggleToolBarsInEachWindow(), BibleTime::slotToggleToolsToolbar(), BibleTime::slotToggleWorksToolbar(), and BibleTime::slotUpdateWindowArrangementActions().
sessionNames()
QHash<QString, QString> BtConfig::sessionNames () const inline
Returns
a hashmap with the keys and printable names of the sessions.
Definition at line 80 of file btconfig.h.
References m_sessionNames.
Referenced by BibleTime::refreshProfileMenus(), and BibleTime::saveToNewProfile().
setCurrentSession()
void BtConfig::setCurrentSession (const QString & key)
Notifies the configuration system that the session settings should be read from and saved to the given session.
Precondition
The session with the given key must exist.
Parameters
[in] key the key of the session to switch to.
Postcondition
the sessionValue() and value() methods will work with the settings of the given session.
Definition at line 153 of file btconfig.cpp.
References BT_ASSERT, anonymous_namespace{btconfig.cpp}::KEY_CURRENT_SESSION, m_currentSessionKey, m_sessionNames, and BtConfigCore::setValue().
Referenced by BibleTime::saveToNewProfile().
setDefaultSwordModuleByType()
void BtConfig::setDefaultSwordModuleByType (const QString & moduleType, const CSwordModuleInfo *const module)
Sets the default sword module for a module type.
This is basically a convenience function for setting the "settings/defaults/ *" variables to the module->name() string manually. 0 is allowed as the module, then the default module will be unset.
Parameters
[in] moduleType module type to set
[in] module the sword module info to set as default module
Definition at line 465 of file btconfig.cpp.
References CSwordModuleInfo::name(), and BtConfigCore::setValue().
Referenced by BtQmlInterface::configModuleByType().
setFontForLanguage()
void BtConfig::setFontForLanguage (Language const & language, FontSettingsPair const & fontSettings)
Set font for a language.
Todo:
: put FontSettingsPair in QVariant directly
Sets a FontSettingsPair for the language given.
Parameters
[in] language pointer to a language to set the font for
[in] fontSettings FontSettingsPair to set
Definition at line 311 of file btconfig.cpp.
References Language::abbrev(), BT_ASSERT, Language::englishName(), m_fontCache, and BtConfigCore::setValue().
Referenced by BtFontSettingsPage::save().
setModuleEncryptionKey()
void BtConfig::setModuleEncryptionKey (const QString & name, const QString & key)
Function to set a module decryption key.
This helper function will set a module decryption key in the configuration. Any previous key will be overwritten.
Parameters
[in] name Name of module to set the key for
[in] key Decryption key to set as string
Definition at line 205 of file btconfig.cpp.
References BT_ASSERT, and BtConfigCore::setValue().
Referenced by CSwordModuleInfo::unlock().
setSearchScopesWithCurrentLocale()
void BtConfig::setSearchScopesWithCurrentLocale (const QStringList & scopeModules, StringMap searchScopes)
Sets the searchScopes given in the current locale.
This function sets the search scopes of the "properties/searchScopes" property, the scopes are converted to the english locale before saving them.
Parameters
[in] searchScopes Search scopes in any locale.
We want to make sure that the search scopes are saved with english key names so loading them will always work with each locale set.
Definition at line 395 of file btconfig.cpp.
References parseVerseListWithModules(), and BtConfigCore::setValue().
setShortcuts()
void BtConfig::setShortcuts (QString const & shortcutGroup, ShortcutsMap const & shortcuts)
Sets the shortcuts for the given group.
Writes a hash of shortcuts for strings for the respective shortcut group.
Parameters
[in] shortcutGroup The group to retrieve shortcuts for.
[in] Hash of strings and lists of shortcuts to write.
Note
saving QKeySequences directly doesn't appear to work!
Definition at line 242 of file btconfig.cpp.
References BtConfigCore::group().
Referenced by BtActionCollection::writeShortcuts().
storeDisplayOptionsToGroup()
void BtConfig::storeDisplayOptionsToGroup (DisplayOptions const & options, BtConfigCore & group) static
Saves the current display options.
Parameters
[in] options The display options to save.
Definition at line 303 of file btconfig.cpp.
References BtConfigCore::group(), DisplayOptions::lineBreaks, BtConfigCore::setValue(), and DisplayOptions::verseNumbers.
Referenced by CBibleReadWindow::storeProfileSettings().
storeFilterOptionsToGroup()
void BtConfig::storeFilterOptionsToGroup (FilterOptions const & options, BtConfigCore & group) static
Saves the current filter options.
Parameters
[in] options The filter options to save.
Definition at line 276 of file btconfig.cpp.
References FilterOptions::footnotes, FilterOptions::greekAccents, BtConfigCore::group(), FilterOptions::headings, FilterOptions::hebrewCantillation, FilterOptions::hebrewPoints, FilterOptions::lemmas, FilterOptions::morphSegmentation, FilterOptions::morphTags, FilterOptions::redLetterWords, FilterOptions::scriptureReferences, BtConfigCore::setValue(), FilterOptions::strongNumbers, and FilterOptions::textualVariants.
Referenced by CBibleReadWindow::storeProfileSettings().
Friends And Related Function Documentation
BibleTimeApp
friend class BibleTimeApp friend
Definition at line 39 of file btconfig.h.
Member Data Documentation
m_currentSessionKey
QString BtConfig::m_currentSessionKey private
Definition at line 295 of file btconfig.h.
Referenced by BtConfig(), currentSessionKey(), currentSessionName(), deleteSession(), session(), and setCurrentSession().
m_defaultFont
QFont BtConfig::m_defaultFont private
default font used when no special one is set
Definition at line 289 of file btconfig.h.
Referenced by BtConfig(), and getDefaultFont().
m_defaultSearchScopes
BtConfig::StringMap BtConfig::m_defaultSearchScopes static private
Definition at line 292 of file btconfig.h.
Referenced by BtConfig(), and getSearchScopesForCurrentLocale().
m_fontCache
FontCacheMap BtConfig::m_fontCache private
a cache for the fonts saved in the configuration file for speed
Definition at line 290 of file btconfig.h.
Referenced by getFontForLanguage(), and setFontForLanguage().
m_instance
BtConfig * BtConfig::m_instance = nullptr static private
singleton instance
Definition at line 287 of file btconfig.h.
Referenced by BtConfig(), destroyInstance(), forceMigrate(), getInstance(), initBtConfig(), and BibleTimeApp::~BibleTimeApp().
m_sessionNames
QHash<QString, QString> BtConfig::m_sessionNames private
Definition at line 294 of file btconfig.h.
Referenced by addSession(), BtConfig(), currentSessionName(), deleteSession(), sessionNames(), and setCurrentSession().
The documentation for this class was generated from the following files:
btconfig.h
btconfig.cpp