BibleTime: BookshelfModel::ModuleItem Class Reference
BookshelfModel::ModuleItem Class Reference
#include <moduleitem.h>
Public Member Functions
QVariant data (int role=Qt::DisplayRole) const override
bool fitFor (CSwordModuleInfo const &) const override
Returns whether this item is fit to contain the given module.
CSwordModuleInfo & moduleInfo () const
ModuleItem (CSwordModuleInfo &module, BtBookshelfTreeModel &parentModel)
Public Member Functions inherited from BookshelfModel::Item
Qt::CheckState checkState () const
Returns the check state of this item.
int childIndex () const
Returns the index of this item under its parent.
QList< Item * > & children ()
Returns the list of child items of this node.
template<class T >
T * getGroupItem (CSwordModuleInfo const &module, int &outIndex)
int indexFor (Item const &newItem)
Returns the position for where the given child item would be inserted.
void insertChild (int const index, Item *const newItem)
Inserts the given item as a child at the given index.
Item (Type const type)
virtual bool operator< (Item const &other) const
Comparsion operator used sorting child items.
Item * parent () const
Returns a pointer to the parent item of this item.
void setCheckState (Qt::CheckState const state)
Sets the check state of this item.
Type type () const
Returns the type of this item.
virtual ~Item ()
Private Attributes
CSwordModuleInfo & m_moduleInfo
BtBookshelfTreeModel & m_parentModel
Additional Inherited Members
Public Types inherited from BookshelfModel::Item
enum Type {
ITEM_ROOT = 0 , ITEM_CATEGORY = 1 , ITEM_LANGUAGE = 2 , ITEM_MODULE = 3 ,
ITEM_INDEXING = 4
}
Detailed Description
Definition at line 26 of file moduleitem.h.
Constructor & Destructor Documentation
ModuleItem()
BookshelfModel::ModuleItem::ModuleItem (CSwordModuleInfo & module, BtBookshelfTreeModel & parentModel) inline
Definition at line 30 of file moduleitem.h.
Member Function Documentation
data()
QVariant BookshelfModel::ModuleItem::data (int role = Qt::DisplayRole) const override virtual
Reimplementation of Item::data() which dispatches all requests to the parent model (BtBookshelfTreeModel).
Reimplemented from BookshelfModel::Item.
Definition at line 20 of file moduleitem.cpp.
References BtBookshelfTreeModel::data(), m_moduleInfo, and m_parentModel.
fitFor()
bool BookshelfModel::ModuleItem::fitFor (CSwordModuleInfo const & module) const inline override virtual
Returns whether this item is fit to contain the given module.
Parameters
[in] module The module to check with.
Return values
true If this item is a group and can contain the given module.
false This item is not a group or is a wrong group.
Implements BookshelfModel::Item.
Definition at line 44 of file moduleitem.h.
moduleInfo()
CSwordModuleInfo & BookshelfModel::ModuleItem::moduleInfo () const inline
Definition at line 42 of file moduleitem.h.
References m_moduleInfo.
Referenced by BtBookshelfTreeModel::data(), and BtBookshelfTreeModel::setData().
Member Data Documentation
m_moduleInfo
CSwordModuleInfo& BookshelfModel::ModuleItem::m_moduleInfo private
Definition at line 48 of file moduleitem.h.
Referenced by data(), and moduleInfo().
m_parentModel
BtBookshelfTreeModel& BookshelfModel::ModuleItem::m_parentModel private
Definition at line 49 of file moduleitem.h.
Referenced by data().
The documentation for this class was generated from the following files:
moduleitem.h
moduleitem.cpp