BibleTime: BtBookshelfView Class Reference
BtBookshelfView Class Reference
#include <btbookshelfview.h>
Signals
void contextMenuActivated (QPoint pos)
void moduleActivated (CSwordModuleInfo *item)
void moduleContextMenuActivated (CSwordModuleInfo *item, QPoint pos)
void moduleHovered (CSwordModuleInfo *item)
Public Member Functions
BtBookshelfView (QWidget *parent=nullptr)
CSwordModuleInfo * getModule (const QModelIndex &index) const
Protected Member Functions
void keyPressEvent (QKeyEvent *event) override
void mousePressEvent (QMouseEvent *event) override
Detailed Description
Definition at line 28 of file btbookshelfview.h.
Constructor & Destructor Documentation
BtBookshelfView()
BtBookshelfView::BtBookshelfView (QWidget * parent = nullptr)
Definition at line 28 of file btbookshelfview.cpp.
References BT_CONNECT, getModule(), moduleActivated(), and moduleHovered().
Member Function Documentation
contextMenuActivated
void BtBookshelfView::contextMenuActivated (QPoint pos) signal
Referenced by BtBookshelfWidget::BtBookshelfWidget(), keyPressEvent(), and mousePressEvent().
getModule()
CSwordModuleInfo * BtBookshelfView::getModule (const QModelIndex & index) const
Definition at line 51 of file btbookshelfview.cpp.
Referenced by BtBookshelfView(), keyPressEvent(), and mousePressEvent().
keyPressEvent()
void BtBookshelfView::keyPressEvent (QKeyEvent * event) override protected
Definition at line 57 of file btbookshelfview.cpp.
References contextMenuActivated(), getModule(), moduleActivated(), and moduleContextMenuActivated().
moduleActivated
void BtBookshelfView::moduleActivated (CSwordModuleInfo * item) signal
Referenced by BtBookshelfDockWidget::BtBookshelfDockWidget(), BtBookshelfView(), BtModuleChooserDialog::BtModuleChooserDialog(), and keyPressEvent().
moduleContextMenuActivated
void BtBookshelfView::moduleContextMenuActivated (CSwordModuleInfo * item, QPoint pos) signal
Referenced by BtBookshelfWidget::BtBookshelfWidget(), keyPressEvent(), and mousePressEvent().
moduleHovered
void BtBookshelfView::moduleHovered (CSwordModuleInfo * item) signal
Referenced by BtBookshelfView().
mousePressEvent()
void BtBookshelfView::mousePressEvent (QMouseEvent * event) override protected
Definition at line 93 of file btbookshelfview.cpp.
References contextMenuActivated(), getModule(), and moduleContextMenuActivated().
The documentation for this class was generated from the following files:
btbookshelfview.h
btbookshelfview.cpp