BibleTime: BtModelViewReadDisplay Class Reference
BtModelViewReadDisplay Class Reference
#include <btmodelviewreaddisplay.h>
Public Types
enum TextPart {
Document, SelectedText, AnchorOnly, AnchorTextOnly,
AnchorWithText
}
enum TextType { HTMLText, PlainText }
Signals
void completed ()
Public Member Functions
BtModelViewReadDisplay (CDisplayWindow *displayWindow, QWidget *parent=nullptr)
void contextMenu (QContextMenuEvent *event)
bool copy (TextType const format, TextPart const part)
Copies the given text with the specified format into the applications clipboard.
void copyAll ()
void copyAnchorOnly ()
void copyAnchorTextOnly ()
void copyAnchorWithText ()
void copyByReferences ()
Copies the given text specified by asking user for first and last references.
void copySelectedText ()
Copies the currently selected text.
void findText (const QString &text, bool caseSensitive, bool backward)
QString getCurrentNodeInfo () const
QString getCurrentSource ()
bool hasActiveAnchor () const
void highlightText (const QString &text, bool caseSensitive)
QMenu * installedPopup ()
void installPopup (QMenu *const popup)
Installs the popup which should be opened when the right mouse button was pressed.
void openFindTextDialog ()
void pageDown ()
void pageUp ()
void print (TextPart const, DisplayOptions const &displayOptions, FilterOptions const &filterOptions)
void printAll (DisplayOptions const &displayOptions, FilterOptions const &filterOptions)
void printAnchorWithText (DisplayOptions const &displayOptions, FilterOptions const &filterOptions)
BtQmlInterface * qmlInterface () const
BtQuickWidget * quickWidget ()
const BtQuickWidget * quickWidget () const
void reloadModules ()
bool save (TextType const format, TextPart const part)
Saves the given text with the specified format into the applications clipboard.
void saveAnchorWithText ()
void scroll (int pixels)
void scrollToKey (CSwordKey *key)
void setDisplayFocus ()
void setDisplayOptions (const DisplayOptions &displayOptions)
void setFilterOptions (FilterOptions filterOptions)
void setLemma (const QString &lemma)
void setModules (QStringList const &modules)
void settingsChanged ()
QString text (TextType const format=HTMLText, TextPart const part=Document)
void updateReferenceText ()
QWidget * view ()
~BtModelViewReadDisplay () override
Private Attributes
QString m_activeAnchor
QString m_currentAnchorCache
QString m_currentSource
int m_magTimerId
QString m_nodeInfo
CDisplayWindow * m_parentWindow
QMenu * m_popup
BtQmlScrollView * m_widget
Detailed Description
The view implementation for the Model/View read display.
Definition at line 62 of file btmodelviewreaddisplay.h.
Member Enumeration Documentation
TextPart
enum BtModelViewReadDisplay::TextPart
Enumerator
Document
SelectedText
AnchorOnly
AnchorTextOnly
AnchorWithText
Definition at line 72 of file btmodelviewreaddisplay.h.
TextType
enum BtModelViewReadDisplay::TextType
Enumerator
HTMLText
PlainText
Definition at line 67 of file btmodelviewreaddisplay.h.
Constructor & Destructor Documentation
BtModelViewReadDisplay()
BtModelViewReadDisplay::BtModelViewReadDisplay (CDisplayWindow * displayWindow, QWidget * parent = nullptr)
Todo:
Fix me
Definition at line 48 of file btmodelviewreaddisplay.cpp.
References BT_CONNECT, BtQmlInterface::dragOccuring(), m_widget, BtQmlScrollView::qmlInterface(), and BtQmlInterface::updateReference().
~BtModelViewReadDisplay()
BtModelViewReadDisplay::~BtModelViewReadDisplay () override default
Member Function Documentation
completed
void BtModelViewReadDisplay::completed () signal
contextMenu()
void BtModelViewReadDisplay::contextMenu (QContextMenuEvent * event)
Definition at line 300 of file btmodelviewreaddisplay.cpp.
References BtQmlInterface::getActiveLink(), BtQmlInterface::getBibleUrlFromLink(), BtQmlInterface::getLemmaFromLink(), installedPopup(), m_activeAnchor, m_widget, BtQmlScrollView::qmlInterface(), and setLemma().
Referenced by BtQmlScrollView::contextMenuEvent().
copy()
bool BtModelViewReadDisplay::copy (TextType const format, TextPart const part)
Copies the given text with the specified format into the applications clipboard.
Definition at line 102 of file btmodelviewreaddisplay.cpp.
References text().
Referenced by copyAll(), copyAnchorOnly(), copyAnchorTextOnly(), and copyAnchorWithText().
copyAll()
void BtModelViewReadDisplay::copyAll () inline
Definition at line 97 of file btmodelviewreaddisplay.h.
References copy(), Document, and PlainText.
Referenced by CDisplayWindow::initActions().
copyAnchorOnly()
void BtModelViewReadDisplay::copyAnchorOnly () inline
Definition at line 93 of file btmodelviewreaddisplay.h.
References AnchorOnly, copy(), and PlainText.
Referenced by CDisplayWindow::initActions().
copyAnchorTextOnly()
void BtModelViewReadDisplay::copyAnchorTextOnly () inline
Definition at line 94 of file btmodelviewreaddisplay.h.
References AnchorTextOnly, copy(), and PlainText.
Referenced by CBibleReadWindow::initActions().
copyAnchorWithText()
void BtModelViewReadDisplay::copyAnchorWithText () inline
Definition at line 95 of file btmodelviewreaddisplay.h.
References AnchorWithText, copy(), and PlainText.
Referenced by CBibleReadWindow::initActions().
copyByReferences()
void BtModelViewReadDisplay::copyByReferences ()
Copies the given text specified by asking user for first and last references.
Definition at line 110 of file btmodelviewreaddisplay.cpp.
References CSwordModuleInfo::Bible, CSwordModuleInfo::Commentary, m_parentWindow, qmlInterface(), and BtCopyByReferencesDialog::result().
Referenced by CDisplayWindow::initActions().
copySelectedText()
void BtModelViewReadDisplay::copySelectedText ()
Copies the currently selected text.
Definition at line 107 of file btmodelviewreaddisplay.cpp.
References qmlInterface().
Referenced by CDisplayWindow::initActions().
findText()
void BtModelViewReadDisplay::findText (const QString & text, bool caseSensitive, bool backward)
Definition at line 352 of file btmodelviewreaddisplay.cpp.
References BtQmlInterface::findText(), m_widget, BtQmlScrollView::qmlInterface(), and text().
Referenced by CMDIArea::findTextInActiveWindow().
getCurrentNodeInfo()
QString BtModelViewReadDisplay::getCurrentNodeInfo () const inline
Definition at line 163 of file btmodelviewreaddisplay.h.
References m_nodeInfo.
Referenced by CDisplayWindow::initActions(), and CDisplayWindow::updatePopupMenu().
getCurrentSource()
QString BtModelViewReadDisplay::getCurrentSource () inline
Definition at line 156 of file btmodelviewreaddisplay.h.
References m_currentSource.
Referenced by CDisplayWindow::saveRawHTML().
hasActiveAnchor()
bool BtModelViewReadDisplay::hasActiveAnchor () const inline
Returns
whether the display has an active anchor.
Definition at line 191 of file btmodelviewreaddisplay.h.
References m_activeAnchor.
Referenced by print(), and CDisplayWindow::updatePopupMenu().
highlightText()
void BtModelViewReadDisplay::highlightText (const QString & text, bool caseSensitive)
Definition at line 348 of file btmodelviewreaddisplay.cpp.
References m_widget, BtQmlScrollView::qmlInterface(), BtQmlInterface::setHighlightWords(), and text().
Referenced by CMDIArea::highlightTextInActiveWindow().
installedPopup()
QMenu* BtModelViewReadDisplay::installedPopup () inline
Returns
the popup menu which was set by installPopupMenu()
Definition at line 133 of file btmodelviewreaddisplay.h.
References m_popup.
Referenced by contextMenu().
installPopup()
void BtModelViewReadDisplay::installPopup (QMenu *const popup) inline
Installs the popup which should be opened when the right mouse button was pressed.
Definition at line 130 of file btmodelviewreaddisplay.h.
References m_popup.
Referenced by CDisplayWindow::popup().
openFindTextDialog()
void BtModelViewReadDisplay::openFindTextDialog ()
Definition at line 363 of file btmodelviewreaddisplay.cpp.
References CDisplayWindow::btMainWindow(), m_parentWindow, and BibleTime::openFindWidget().
Referenced by CDisplayWindow::initActions().
pageDown()
void BtModelViewReadDisplay::pageDown ()
Definition at line 340 of file btmodelviewreaddisplay.cpp.
References m_widget, and BtQmlScrollView::pageDown().
Referenced by CDisplayWindow::initActions().
pageUp()
void BtModelViewReadDisplay::pageUp ()
Definition at line 344 of file btmodelviewreaddisplay.cpp.
References m_widget, and BtQmlScrollView::pageUp().
Referenced by CDisplayWindow::initActions().
print()
void BtModelViewReadDisplay::print (TextPart const type, DisplayOptions const & displayOptions, FilterOptions const & filterOptions)
Definition at line 147 of file btmodelviewreaddisplay.cpp.
References AnchorWithText, CSwordModuleInfo::Bible, CSwordVerseKey::bookName(), CSwordVerseKey::chapter(), CSwordModuleInfo::Commentary, CDisplayWindow::displayOptions(), Document, CDisplayWindow::filterOptions(), CSwordModuleInfo::GenericBook, hasActiveAnchor(), CSwordKey::key(), CSwordTreeKey::key(), CDisplayWindow::key(), CSwordVerseKey::key(), CSwordModuleInfo::Lexicon, m_activeAnchor, m_parentWindow, CSwordKey::module(), CExportManager::printByHyperlink(), CExportManager::printKey(), CSwordVerseKey::setVerse(), and CSwordModuleInfo::type().
Referenced by printAll(), and printAnchorWithText().
printAll()
void BtModelViewReadDisplay::printAll (DisplayOptions const & displayOptions, FilterOptions const & filterOptions) inline
Definition at line 118 of file btmodelviewreaddisplay.h.
References Document, and print().
Referenced by CDisplayWindow::printAll().
printAnchorWithText()
void BtModelViewReadDisplay::printAnchorWithText (DisplayOptions const & displayOptions, FilterOptions const & filterOptions) inline
Definition at line 122 of file btmodelviewreaddisplay.h.
References AnchorWithText, and print().
Referenced by CDisplayWindow::printAnchorWithText().
qmlInterface()
BtQmlInterface * BtModelViewReadDisplay::qmlInterface () const
Definition at line 312 of file btmodelviewreaddisplay.cpp.
References m_widget, and BtQmlScrollView::qmlInterface().
Referenced by copyByReferences(), copySelectedText(), CDisplayWindow::hasSelectedText(), reloadModules(), and CDisplayWindow::setDisplayWidget().
quickWidget() [1/2]
BtQuickWidget* BtModelViewReadDisplay::quickWidget () inline
Definition at line 183 of file btmodelviewreaddisplay.h.
References m_widget, and BtQmlScrollView::quickWidget().
Referenced by CDisplayWindow::getFirstSelectedIndex(), CDisplayWindow::getLastSelectedIndex(), and CDisplayWindow::getSelectedColumn().
quickWidget() [2/2]
const BtQuickWidget* BtModelViewReadDisplay::quickWidget () const inline
Definition at line 185 of file btmodelviewreaddisplay.h.
References m_widget, and BtQmlScrollView::quickWidget().
reloadModules()
void BtModelViewReadDisplay::reloadModules ()
Definition at line 209 of file btmodelviewreaddisplay.cpp.
References qmlInterface(), and BtQmlInterface::textModel.
Referenced by CDisplayWindow::reload().
save()
bool BtModelViewReadDisplay::save (TextType const format, TextPart const part)
Saves the given text with the specified format into the applications clipboard.
Definition at line 126 of file btmodelviewreaddisplay.cpp.
References anonymous_namespace{btbookshelfworkspage.cpp}::filter(), HTMLText, PlainText, util::tool::savePlainFile(), and text().
Referenced by saveAnchorWithText().
saveAnchorWithText()
void BtModelViewReadDisplay::saveAnchorWithText () inline
Definition at line 96 of file btmodelviewreaddisplay.h.
References AnchorWithText, PlainText, and save().
Referenced by CBibleReadWindow::initActions().
scroll()
void BtModelViewReadDisplay::scroll (int pixels)
Definition at line 324 of file btmodelviewreaddisplay.cpp.
References m_widget, BtQmlScrollView::quickWidget(), and BtQuickWidget::scroll().
scrollToKey()
void BtModelViewReadDisplay::scrollToKey (CSwordKey * key)
Definition at line 320 of file btmodelviewreaddisplay.cpp.
References m_widget, and BtQmlScrollView::scrollToSwordKey().
Referenced by CDisplayWindow::lookupSwordKey().
setDisplayFocus()
void BtModelViewReadDisplay::setDisplayFocus ()
Definition at line 292 of file btmodelviewreaddisplay.cpp.
References m_widget, and BtQmlScrollView::quickWidget().
setDisplayOptions()
void BtModelViewReadDisplay::setDisplayOptions (const DisplayOptions & displayOptions)
Definition at line 296 of file btmodelviewreaddisplay.cpp.
References m_widget, BtQmlScrollView::qmlInterface(), and BtQmlInterface::textModel.
Referenced by CDisplayWindow::lookupSwordKey(), and CDisplayWindow::setDisplaySettingsButton().
setFilterOptions()
void BtModelViewReadDisplay::setFilterOptions (FilterOptions filterOptions)
Definition at line 328 of file btmodelviewreaddisplay.cpp.
References m_widget, and BtQmlScrollView::setFilterOptions().
Referenced by CDisplayWindow::lookupSwordKey().
setLemma()
void BtModelViewReadDisplay::setLemma (const QString & lemma)
Definition at line 358 of file btmodelviewreaddisplay.cpp.
References m_nodeInfo.
Referenced by contextMenu().
setModules()
void BtModelViewReadDisplay::setModules (QStringList const & modules)
Definition at line 316 of file btmodelviewreaddisplay.cpp.
References m_widget, BtQmlScrollView::qmlInterface(), and BtQmlInterface::setModules().
Referenced by CDisplayWindow::slotAddModule(), CDisplayWindow::slotRemoveModule(), and CDisplayWindow::slotReplaceModule().
settingsChanged()
void BtModelViewReadDisplay::settingsChanged ()
Definition at line 332 of file btmodelviewreaddisplay.cpp.
References m_widget, and BtQmlScrollView::settingsChanged().
Referenced by CDisplayWindow::reload().
text()
QString BtModelViewReadDisplay::text (TextType const format = HTMLText, TextPart const part = Document)
Parameters
[in] format The format to use for the text.
[in] part The part of the text to return.
Returns
the right text part in the specified format.
Definition at line 214 of file btmodelviewreaddisplay.cpp.
References AnchorOnly, AnchorTextOnly, AnchorWithText, BT_ASSERT, CSwordModuleInfo::Commentary, CSwordKey::createInstance(), ReferenceManager::decodeHyperlink(), Document, CSwordModuleInfo::GenericBook, HTMLText, CSwordBackend::instance(), CSwordKey::key(), CDisplayWindow::key(), CSwordModuleInfo::Lexicon, m_activeAnchor, m_currentSource, m_parentWindow, CSwordKey::module(), CSwordModuleInfo::name(), CSwordBackend::setFilterOptions(), CSwordKey::strippedText(), and CSwordModuleInfo::type().
Referenced by copy(), findText(), highlightText(), and save().
updateReferenceText()
void BtModelViewReadDisplay::updateReferenceText ()
Definition at line 336 of file btmodelviewreaddisplay.cpp.
References m_widget, BtQmlScrollView::quickWidget(), and BtQuickWidget::updateReferenceText().
view()
QWidget* BtModelViewReadDisplay::view () inline
Returns
the view of this display widget.
Definition at line 150 of file btmodelviewreaddisplay.h.
References m_widget.
Referenced by CDisplayWindow::initView().
Member Data Documentation
m_activeAnchor
QString BtModelViewReadDisplay::m_activeAnchor private
Definition at line 200 of file btmodelviewreaddisplay.h.
Referenced by contextMenu(), hasActiveAnchor(), print(), and text().
m_currentAnchorCache
QString BtModelViewReadDisplay::m_currentAnchorCache private
Definition at line 208 of file btmodelviewreaddisplay.h.
m_currentSource
QString BtModelViewReadDisplay::m_currentSource private
Definition at line 202 of file btmodelviewreaddisplay.h.
Referenced by getCurrentSource(), and text().
m_magTimerId
int BtModelViewReadDisplay::m_magTimerId private
Definition at line 205 of file btmodelviewreaddisplay.h.
m_nodeInfo
QString BtModelViewReadDisplay::m_nodeInfo private
Definition at line 204 of file btmodelviewreaddisplay.h.
Referenced by getCurrentNodeInfo(), and setLemma().
m_parentWindow
CDisplayWindow* BtModelViewReadDisplay::m_parentWindow private
Definition at line 198 of file btmodelviewreaddisplay.h.
Referenced by copyByReferences(), openFindTextDialog(), print(), and text().
m_popup
QMenu* BtModelViewReadDisplay::m_popup private
Definition at line 199 of file btmodelviewreaddisplay.h.
Referenced by installedPopup(), and installPopup().
m_widget
BtQmlScrollView* BtModelViewReadDisplay::m_widget private
Definition at line 207 of file btmodelviewreaddisplay.h.
Referenced by BtModelViewReadDisplay(), contextMenu(), findText(), highlightText(), pageDown(), pageUp(), qmlInterface(), quickWidget(), scroll(), scrollToKey(), setDisplayFocus(), setDisplayOptions(), setFilterOptions(), setModules(), settingsChanged(), updateReferenceText(), and view().
The documentation for this class was generated from the following files:
btmodelviewreaddisplay.h
btmodelviewreaddisplay.cpp