BibleTime: CSwordBackend::Private Struct Reference
CSwordBackend::Private Struct Reference
Public Member Functions
void addRenderFilters (sword::SWModule *module, sword::ConfigEntMap &section) override
void reloadConfig ()
void shutdownModules ()
Public Attributes
Filters::GbfToHtml m_gbfFilter
Filters::OsisToHtml m_osisFilter
Filters::PlainToHtml m_plainFilter
Filters::TeiToHtml m_teiFilter
Filters::ThmlToHtml m_thmlFilter
Detailed Description
Definition at line 276 of file cswordbackend.h.
Member Function Documentation
addRenderFilters()
void CSwordBackend::Private::addRenderFilters (sword::SWModule * module, sword::ConfigEntMap & section) override
Definition at line 241 of file cswordbackend.cpp.
References m_gbfFilter, m_osisFilter, m_plainFilter, m_teiFilter, and m_thmlFilter.
reloadConfig()
void CSwordBackend::Private::reloadConfig ()
Definition at line 472 of file cswordbackend.cpp.
References BtInstallBackend::configPath(), and CSwordBackend::prefixPath().
Referenced by CSwordBackend::reloadModules().
shutdownModules()
void CSwordBackend::Private::shutdownModules ()
Definition at line 275 of file cswordbackend.cpp.
Referenced by CSwordBackend::shutdownModules().
Member Data Documentation
m_gbfFilter
Filters::GbfToHtml CSwordBackend::Private::m_gbfFilter
Definition at line 289 of file cswordbackend.h.
Referenced by addRenderFilters().
m_osisFilter
Filters::OsisToHtml CSwordBackend::Private::m_osisFilter
Definition at line 290 of file cswordbackend.h.
Referenced by addRenderFilters().
m_plainFilter
Filters::PlainToHtml CSwordBackend::Private::m_plainFilter
Definition at line 291 of file cswordbackend.h.
Referenced by addRenderFilters().
m_teiFilter
Filters::TeiToHtml CSwordBackend::Private::m_teiFilter
Definition at line 292 of file cswordbackend.h.
Referenced by addRenderFilters().
m_thmlFilter
Filters::ThmlToHtml CSwordBackend::Private::m_thmlFilter
Definition at line 293 of file cswordbackend.h.
Referenced by addRenderFilters().
The documentation for this struct was generated from the following files:
cswordbackend.h
cswordbackend.cpp