BibleTime: Search::CHistoryComboBox Class Reference
Search::CHistoryComboBox Class Reference
#include <chistorycombobox.h>
Public Member Functions
void addToHistory (const QString &item)
CHistoryComboBox (QWidget *parent=nullptr)
QStringList historyItems () const
~CHistoryComboBox () override
Detailed Description
Definition at line 26 of file chistorycombobox.h.
Constructor & Destructor Documentation
CHistoryComboBox()
Search::CHistoryComboBox::CHistoryComboBox (QWidget * parent = nullptr)
Definition at line 21 of file chistorycombobox.cpp.
~CHistoryComboBox()
Search::CHistoryComboBox::~CHistoryComboBox () override
Definition at line 27 of file chistorycombobox.cpp.
Member Function Documentation
addToHistory()
void Search::CHistoryComboBox::addToHistory (const QString & item)
Definition at line 30 of file chistorycombobox.cpp.
Referenced by Search::BtSearchOptionsArea::addToHistory(), and Search::BtSearchOptionsArea::initConnections().
historyItems()
QStringList Search::CHistoryComboBox::historyItems () const
Definition at line 38 of file chistorycombobox.cpp.
Referenced by Search::BtSearchOptionsArea::saveSettings().
The documentation for this class was generated from the following files:
chistorycombobox.h
chistorycombobox.cpp