BibleTime: CLexiconReadWindow Class Reference
CLexiconReadWindow Class Reference
The class used to display lexicons.
#include <clexiconreadwindow.h>
Public Slots
void reload (CSwordBackend::SetupChangedReason reason) override
Public Slots inherited from CDisplayWindow
void lookupKey (QString const &key)
virtual void reload (CSwordBackend::SetupChangedReason reason)
void slotAddModule (int index, QString module)
void slotRemoveModule (int index)
void slotReplaceModule (int index, QString newModule)
Public Member Functions
CLexiconReadWindow (QList< CSwordModuleInfo * > const &modules, CMDIArea *parent)
Public Member Functions inherited from CDisplayWindow
BtActionCollection * actionCollection () const
virtual void applyProfileSettings (BtConfigCore const &windowConf)
Loads the settings of this window from configuration.
BibleTime * btMainWindow ()
QToolBar * buttonsToolBar () const
virtual void copyDisplayedText ()
const DisplayOptions & displayOptions () const
BtModelViewReadDisplay * displayWidget () const
const FilterOptions & filterOptions () const
int getFirstSelectedIndex () const
int getLastSelectedIndex () const
const QStringList & getModuleList () const
CSwordKey * getMouseClickedKey () const
int getSelectedColumn () const
bool hasSelectedText ()
BTHistory * history ()
bool init ()
bool isReady () const
CSwordKey * key () const
CKeyChooser * keyChooser () const
QToolBar * mainToolBar () const
CMDIArea * mdi () const
BtConstModuleList modules () const
virtual CSwordModuleInfo::ModuleType moduleType () const
void setButtonsToolBar (QToolBar *bar)
void setDisplaySettingsButton (BtDisplaySettingsButton *button)
void setDisplayWidget (BtModelViewReadDisplay *newDisplay)
void setMainToolBar (QToolBar *bar)
virtual void storeProfileSettings (BtConfigCore &windowConf) const
Stores the settings of this window to configuration.
virtual bool syncAllowed () const
void windowActivated ()
QString windowCaption ()
Static Public Member Functions
static void insertKeyboardActions (BtActionCollection *a)
Static Public Member Functions inherited from CDisplayWindow
static void insertKeyboardActions (BtActionCollection *const a)
Protected Slots
void nextEntry ()
void previousEntry ()
Protected Slots inherited from CDisplayWindow
void lookup ()
virtual void modulesChanged ()
void printAll ()
void printAnchorWithText ()
void saveRawHTML ()
Protected Member Functions
void initActions () override
Protected Member Functions inherited from CDisplayWindow
CDisplayWindow (const QList< CSwordModuleInfo * > &modules, CMDIArea *parent)
void clearMainWindowToolBars ()
QToolBar * headerBar () const
template<typename ... Args>
QAction & initAddAction (Args &&... args)
virtual void initConnections ()
virtual void initToolbars ()
virtual void initView ()
virtual void lookupSwordKey (CSwordKey *)
BtModuleChooserBar * moduleChooserBar () const
QMenu * popup ()
‍** Returns the installed popup menu. *‍/
void setDisplayOptions (DisplayOptions const &v)
void setFilterOptions (FilterOptions const &v)
void setKeyChooser (CKeyChooser *ck)
void setModuleChooserBar (BtModuleChooserBar *bar)
void setToolBarsHidden ()
virtual void setupMainWindowToolBars ()
virtual void setupPopupMenu ()
virtual void updatePopupMenu ()
~CDisplayWindow () override
Private Member Functions
CSwordLDKey * ldKey ()
Additional Inherited Members
Signals inherited from CDisplayWindow
void sigDisplayOptionsChanged (const DisplayOptions &displayOptions)
void sigFilterOptionsChanged (const FilterOptions &filterOptions)
void sigKeyChanged (CSwordKey *key)
void sigModuleAdded (int index, QString module)
void sigModuleListChanged ()
void sigModuleListSet (QStringList modules)
void sigModuleRemoved (int index)
void sigModuleReplaced (int index, QString newModule)
void sigModulesChanged (const BtConstModuleList &modules)
Protected Attributes inherited from CDisplayWindow
struct CDisplayWindow::ActionsStruct m_actions
Detailed Description
The class used to display lexicons.
Definition at line 28 of file clexiconreadwindow.h.
Constructor & Destructor Documentation
CLexiconReadWindow()
CLexiconReadWindow::CLexiconReadWindow (QList< CSwordModuleInfo * > const & modules, CMDIArea * parent)
Definition at line 25 of file clexiconreadwindow.cpp.
Member Function Documentation
initActions()
void CLexiconReadWindow::initActions () override protected virtual
Initializes the internel keyboard actions.
Reimplemented from CDisplayWindow.
Definition at line 41 of file clexiconreadwindow.cpp.
References CDisplayWindow::actionCollection(), CDisplayWindow::initActions(), CDisplayWindow::initAddAction(), insertKeyboardActions(), CDisplayWindow::m_actionCollection, nextEntry(), previousEntry(), and BtActionCollection::readShortcuts().
insertKeyboardActions()
void CLexiconReadWindow::insertKeyboardActions (BtActionCollection * a) static
Definition at line 31 of file clexiconreadwindow.cpp.
References CResMgr::displaywindows::lexiconWindow::nextEntry::accel, CResMgr::displaywindows::lexiconWindow::previousEntry::accel, and BtActionCollection::addAction().
Referenced by initActions().
ldKey()
CSwordLDKey * CLexiconReadWindow::ldKey () private
Definition at line 60 of file clexiconreadwindow.cpp.
References CDisplayWindow::m_swordKey.
Referenced by nextEntry(), and previousEntry().
nextEntry
void CLexiconReadWindow::nextEntry () protected slot
Definition at line 54 of file clexiconreadwindow.cpp.
References CDisplayWindow::keyChooser(), ldKey(), and CKeyChooser::setKey().
Referenced by initActions().
previousEntry
void CLexiconReadWindow::previousEntry () protected slot
Definition at line 57 of file clexiconreadwindow.cpp.
References CDisplayWindow::keyChooser(), ldKey(), and CKeyChooser::setKey().
Referenced by initActions().
reload
void CLexiconReadWindow::reload (CSwordBackend::SetupChangedReason reason) override slot
Definition at line 49 of file clexiconreadwindow.cpp.
References CDisplayWindow::actionCollection(), BtActionCollection::readShortcuts(), and CDisplayWindow::reload().
The documentation for this class was generated from the following files:
clexiconreadwindow.h
clexiconreadwindow.cpp