BibleTime: BtSourcesThread Class Reference
BtSourcesThread Class Reference
#include <btsourcesthread.h>
Signals
void percentComplete (int percent)
void showMessage (QString const &msg)
Public Member Functions
BtSourcesThread (QObject *parent=nullptr)
bool finishedSuccessfully () const noexcept
void stop () noexcept
Protected Member Functions
void run () override
Private Member Functions
bool shouldStop () const noexcept
Private Attributes
std::atomic< bool > m_finishedSuccessfully
std::atomic< bool > m_stop
Detailed Description
Definition at line 22 of file btsourcesthread.h.
Constructor & Destructor Documentation
BtSourcesThread()
BtSourcesThread::BtSourcesThread (QObject * parent = nullptr) inline
Definition at line 28 of file btsourcesthread.h.
Member Function Documentation
finishedSuccessfully()
bool BtSourcesThread::finishedSuccessfully () const inline noexcept
Definition at line 36 of file btsourcesthread.h.
References m_finishedSuccessfully.
Referenced by BtBookshelfSourcesProgressPage::slotThreadFinished().
percentComplete
void BtSourcesThread::percentComplete (int percent) signal
Referenced by BtBookshelfSourcesProgressPage::initializePage(), and run().
run()
void BtSourcesThread::run () override protected
Definition at line 29 of file btsourcesthread.cpp.
References BT_ASSERT, m_finishedSuccessfully, percentComplete(), shouldStop(), showMessage(), BtInstallBackend::source(), and BtInstallBackend::sourceNameList().
shouldStop()
bool BtSourcesThread::shouldStop () const inline private noexcept
Definition at line 50 of file btsourcesthread.h.
References m_stop.
Referenced by run().
showMessage
void BtSourcesThread::showMessage (QString const & msg) signal
Referenced by BtBookshelfSourcesProgressPage::initializePage(), and run().
stop()
void BtSourcesThread::stop () inline noexcept
Definition at line 34 of file btsourcesthread.h.
References m_stop.
Referenced by BtBookshelfSourcesProgressPage::destroyThread(), and BtBookshelfSourcesProgressPage::slotStopInstall().
Member Data Documentation
m_finishedSuccessfully
std::atomic<bool> BtSourcesThread::m_finishedSuccessfully private
Definition at line 56 of file btsourcesthread.h.
Referenced by finishedSuccessfully(), and run().
m_stop
std::atomic<bool> BtSourcesThread::m_stop private
Definition at line 55 of file btsourcesthread.h.
Referenced by shouldStop(), and stop().
The documentation for this class was generated from the following files:
btsourcesthread.h
btsourcesthread.cpp