BibleTime: CScrollerWidgetSet Class Reference
CScrollerWidgetSet Class Reference
#include <cscrollerwidgetset.h>
Signals
void change (int count)
void scroller_pressed ()
void scroller_released ()
Public Member Functions
CScrollerWidgetSet (QWidget *parent=nullptr)
void setToolTips (const QString &nextEntry, const QString &scrollButton, const QString &previousEntry)
Protected Member Functions
void wheelEvent (QWheelEvent *e) override
Private Attributes
QToolButton * m_buttonDown
QToolButton * m_buttonUp
QVBoxLayout * m_layout
CScrollButton * m_scrollButton
Detailed Description
This class implements the Scroller Widget-set, which consists of two normal ref @QToolButton and a enhanced CScrollButton
Definition at line 30 of file cscrollerwidgetset.h.
Constructor & Destructor Documentation
CScrollerWidgetSet()
CScrollerWidgetSet::CScrollerWidgetSet (QWidget * parent = nullptr)
Definition at line 30 of file cscrollerwidgetset.cpp.
References ARROW_HEIGHT, BT_CONNECT, change(), CScrollButton::change_requested(), CScrollButton::lock(), m_buttonDown, m_buttonUp, m_layout, m_scrollButton, MOVER_HEIGHT, scroller_pressed(), scroller_released(), CScrollButton::unlock(), and WIDTH.
Member Function Documentation
change
void CScrollerWidgetSet::change (int count) signal
Is emitted to proceed to some other entry relative to the current, indicated by the int value.
Parameters
count offset to change to
Referenced by CScrollerWidgetSet(), CKeyChooserWidget::init(), and wheelEvent().
scroller_pressed
void CScrollerWidgetSet::scroller_pressed () signal
Referenced by CScrollerWidgetSet(), and CKeyChooserWidget::init().
scroller_released
void CScrollerWidgetSet::scroller_released () signal
Referenced by CScrollerWidgetSet(), and CKeyChooserWidget::init().
setToolTips()
void CScrollerWidgetSet::setToolTips (const QString & nextEntryTip, const QString & scrollButtonTip, const QString & previousEntryTip)
Sets the tooltips for the given entries using the parameters as text.
Definition at line 72 of file cscrollerwidgetset.cpp.
References m_buttonDown, m_buttonUp, and m_scrollButton.
Referenced by CKeyChooserWidget::setToolTips().
wheelEvent()
void CScrollerWidgetSet::wheelEvent (QWheelEvent * e) override protected
Definition at line 82 of file cscrollerwidgetset.cpp.
References change().
Member Data Documentation
m_buttonDown
QToolButton* CScrollerWidgetSet::m_buttonDown private
Definition at line 66 of file cscrollerwidgetset.h.
Referenced by CScrollerWidgetSet(), and setToolTips().
m_buttonUp
QToolButton* CScrollerWidgetSet::m_buttonUp private
Definition at line 65 of file cscrollerwidgetset.h.
Referenced by CScrollerWidgetSet(), and setToolTips().
m_layout
QVBoxLayout* CScrollerWidgetSet::m_layout private
Definition at line 64 of file cscrollerwidgetset.h.
Referenced by CScrollerWidgetSet().
m_scrollButton
CScrollButton* CScrollerWidgetSet::m_scrollButton private
Definition at line 67 of file cscrollerwidgetset.h.
Referenced by CScrollerWidgetSet(), and setToolTips().
The documentation for this class was generated from the following files:
cscrollerwidgetset.h
cscrollerwidgetset.cpp