BibleTime: BtModuleChooserButton Class Reference
BtModuleChooserButton Class Reference
#include <btmodulechooserbutton.h>
Signals
void sigModuleAdd (int index, QString module)
void sigModuleRemove (int index)
void sigModuleReplace (int index, QString newModule)
Public Member Functions
BtModuleChooserButton (CSwordModuleInfo::ModuleType mtype, QWidget *parent=nullptr)
Constructs an new empty button.
void updateMenu (QStringList newModulesToUse, QString thisModule, int newIndex, int leftLikeModules)
Private Slots
void moduleChosen (CSwordModuleInfo const *const module)
Private Member Functions
const QIcon & icon ()
Private Attributes
BtModuleChooserMenu * m_popup
Detailed Description
Definition at line 32 of file btmodulechooserbutton.h.
Constructor & Destructor Documentation
BtModuleChooserButton()
BtModuleChooserButton::BtModuleChooserButton (CSwordModuleInfo::ModuleType mtype, QWidget * parent = nullptr)
Constructs an new empty button.
Note
updateMenu() is needed to update the icon, menu items etc.
Definition at line 22 of file btmodulechooserbutton.cpp.
References BT_CONNECT, icon(), m_popup, moduleChosen(), and BtModuleChooserMenu::sigModuleChosen().
Member Function Documentation
icon()
const QIcon & BtModuleChooserButton::icon () private
Returns the icon used for the current status.
Definition at line 40 of file btmodulechooserbutton.cpp.
References CSwordModuleInfo::Bible, CSwordModuleInfo::Commentary, CSwordModuleInfo::GenericBook, CSwordModuleInfo::Lexicon, m_popup, BtModuleChooserMenu::moduleType(), and BtModuleChooserMenu::selectedModule().
Referenced by BtModuleChooserButton(), moduleChosen(), and updateMenu().
moduleChosen
void BtModuleChooserButton::moduleChosen (CSwordModuleInfo const *const newModule) private slot
Handle the action signal from the menu.
Is called after a module was selected in the popup
Definition at line 87 of file btmodulechooserbutton.cpp.
References BtModuleChooserMenu::buttonIndex(), icon(), m_popup, CSwordModuleInfo::moduleIcon(), CSwordModuleInfo::name(), BtModuleChooserMenu::selectedModule(), BtModuleChooserMenu::setSelectedModule(), sigModuleAdd(), sigModuleRemove(), and sigModuleReplace().
Referenced by BtModuleChooserButton().
sigModuleAdd
void BtModuleChooserButton::sigModuleAdd (int index, QString module) signal
User selected a module from menu to add.
Referenced by BtModuleChooserBar::addButton(), and moduleChosen().
sigModuleRemove
void BtModuleChooserButton::sigModuleRemove (int index) signal
User selected a module from menu to be removed.
Referenced by BtModuleChooserBar::addButton(), and moduleChosen().
sigModuleReplace
void BtModuleChooserButton::sigModuleReplace (int index, QString newModule) signal
User selected a module from menu to replace another module.
Referenced by BtModuleChooserBar::addButton(), and moduleChosen().
updateMenu()
void BtModuleChooserButton::updateMenu (QStringList newModulesToUse, QString thisModule, int newIndex, int leftLikeModules)
Definition at line 63 of file btmodulechooserbutton.cpp.
References icon(), CSwordBackend::instance(), m_popup, and BtModuleChooserMenu::update().
Member Data Documentation
m_popup
BtModuleChooserMenu* BtModuleChooserButton::m_popup private
Definition at line 72 of file btmodulechooserbutton.h.
Referenced by BtModuleChooserButton(), icon(), moduleChosen(), and updateMenu().
The documentation for this class was generated from the following files:
btmodulechooserbutton.h
btmodulechooserbutton.cpp