BibleTime: anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem Class Reference
anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem Class Reference final
Public Member Functions
BookmarkItem (BookmarkFolder *parent)
BookmarkItem (const BookmarkItem &other)
BookmarkItem (const CSwordModuleInfo &module, const QString &key, const QString &description, const QString &title)
QString const & description () const
QString const & englishKey () const
Qt::ItemFlags flags () const noexcept final override
QIcon const & icon () const noexcept final override
QString key () const
CSwordModuleInfo * module () const
QString const & moduleName () const
void setDescription (QString const &description)
void setKey (QString const &key)
void setModule (QString const &moduleName)
QString toolTip () const override
Public Member Functions inherited from anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase
BookmarkItemBase (BookmarkFolder *parent=nullptr)
BookmarkItemBase (const BookmarkItemBase &other)
int index () const
BookmarkFolder * parent () const
void setParent (BookmarkFolder *parent)
void setText (QString const &text)
QString const & text () const
virtual ~BookmarkItemBase ()
Private Attributes
QString m_description
QString m_key
QString m_moduleName
Detailed Description
Definition at line 100 of file btbookmarksmodel.cpp.
Constructor & Destructor Documentation
BookmarkItem() [1/3]
BookmarkItem::BookmarkItem (BookmarkFolder * parent)
Definition at line 484 of file btbookmarksmodel.cpp.
References key(), module(), anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::setText(), and anonymous_namespace{btbookmarksmodel.cpp}::toHeader().
BookmarkItem() [2/3]
anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::BookmarkItem (const CSwordModuleInfo & module, const QString & key, const QString & description, const QString & title)
Creates a bookmark with module, key and description.
BookmarkItem() [3/3]
BookmarkItem::BookmarkItem (const BookmarkItem & other)
Creates a copy.
Definition at line 489 of file btbookmarksmodel.cpp.
References key(), module(), anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::setText(), and anonymous_namespace{btbookmarksmodel.cpp}::toHeader().
Member Function Documentation
description()
QString const & anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::description () const inline
Returns the used description.
Definition at line 130 of file btbookmarksmodel.cpp.
References BookmarkItem::m_description.
Referenced by BtBookmarksModelPrivate::saveItem(), and toolTip().
englishKey()
QString const & anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::englishKey () const inline
Returns the english key.
Definition at line 139 of file btbookmarksmodel.cpp.
References BookmarkItem::m_key.
Referenced by BtBookmarksModelPrivate::saveItem().
flags()
Qt::ItemFlags anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::flags () const inline final override virtual noexcept
Reimplemented from anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase.
Definition at line 112 of file btbookmarksmodel.cpp.
icon()
QIcon const & anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::icon () const inline final override virtual noexcept
Reimplemented from anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase.
Definition at line 118 of file btbookmarksmodel.cpp.
key()
QString anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::key () const
Returns the used key.
Referenced by BookmarkItem(), BookmarkItem(), anonymous_namespace{btbookmarksmodel.cpp}::toHeader(), and toolTip().
module()
CSwordModuleInfo * anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::module () const
Returns the used module, 0 if there is no such module.
Referenced by BookmarkItem(), BookmarkItem(), BtBookmarksModelPrivate::saveItem(), and toolTip().
moduleName()
QString const & anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::moduleName () const inline
Definition at line 144 of file btbookmarksmodel.cpp.
References BookmarkItem::m_moduleName.
Referenced by BtBookmarksModelPrivate::saveItem(), and anonymous_namespace{btbookmarksmodel.cpp}::toHeader().
setDescription()
void anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::setDescription (QString const & description) inline
Definition at line 132 of file btbookmarksmodel.cpp.
References BookmarkItem::description(), and BookmarkItem::m_description.
Referenced by BtBookmarksModelPrivate::handleXmlElement().
setKey()
void anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::setKey (QString const & key) inline
Definition at line 127 of file btbookmarksmodel.cpp.
References BookmarkItem::key(), and BookmarkItem::m_key.
Referenced by BtBookmarksModelPrivate::handleXmlElement().
setModule()
void anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::setModule (QString const & moduleName) inline
Definition at line 141 of file btbookmarksmodel.cpp.
References BookmarkItem::m_moduleName.
Referenced by BtBookmarksModelPrivate::handleXmlElement().
toolTip()
QString BookmarkItem::toolTip () const override virtual
Returns a tooltip for this bookmark.
Reimplemented from anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase.
Definition at line 520 of file btbookmarksmodel.cpp.
References BT_ASSERT, btConfig(), description(), FilterOptions::footnotes, BtConfig::getFilterOptions(), CSwordBackend::instance(), key(), module(), FilterOptions::scriptureReferences, CSwordBackend::setFilterOptions(), anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::text(), and anonymous_namespace{btbookmarksmodel.cpp}::toHeader().
Member Data Documentation
m_description
QString anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::m_description private
Definition at line 148 of file btbookmarksmodel.cpp.
m_key
QString anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::m_key private
Definition at line 147 of file btbookmarksmodel.cpp.
m_moduleName
QString anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::m_moduleName private
Definition at line 149 of file btbookmarksmodel.cpp.
The documentation for this class was generated from the following file:
btbookmarksmodel.cpp