BibleTime: Search::CSearchResultView Class Reference
Search::CSearchResultView Class Reference
#include <csearchresultview.h>
Public Slots
void contextMenuEvent (QContextMenuEvent *event) override
void setupStrongsTree (CSwordModuleInfo *, const QStringList &)
void setupTree (CSwordModuleInfo const *m, CSwordModuleSearch::ModuleResultList const &results)
Signals
void keyDeselected ()
void keySelected (const QString &)
Public Member Functions
CSearchResultView (QWidget *parent)
CSwordModuleInfo const * module () const
Protected Member Functions
void initConnections ()
void initView ()
QMimeData * mimeData (QList< QTreeWidgetItem * > const &items) const override
QStringList mimeTypes () const override
Private Attributes
struct {
struct {
QAction * result
QAction * resultWithText
} copy
QMenu * copyMenu
struct {
QAction * result
} print
QMenu * printMenu
struct {
QAction * result
QAction * resultWithText
} save
QMenu * saveMenu
} m_actions
const CSwordModuleInfo * m_module
QMenu * m_popup
Detailed Description
Definition at line 27 of file csearchresultview.h.
Constructor & Destructor Documentation
CSearchResultView()
Search::CSearchResultView::CSearchResultView (QWidget * parent)
Definition at line 32 of file csearchresultview.cpp.
References initConnections(), and initView().
Member Function Documentation
contextMenuEvent
void Search::CSearchResultView::contextMenuEvent (QContextMenuEvent * event) override slot
Todo:
another function?
Reimplementation to show the popup menu.
Definition at line 202 of file csearchresultview.cpp.
References m_popup.
initConnections()
void Search::CSearchResultView::initConnections () protected
No descriptions
Todo:
are these right after porting?
Definition at line 133 of file csearchresultview.cpp.
References BT_CONNECT, keyDeselected(), and keySelected().
Referenced by CSearchResultView().
initView()
void Search::CSearchResultView::initView () protected
Initializes the view of this widget.
Definition at line 40 of file csearchresultview.cpp.
References BT_CONNECT, m_actions, m_module, and m_popup.
Referenced by CSearchResultView().
keyDeselected
void Search::CSearchResultView::keyDeselected () signal
Referenced by Search::BtSearchResultArea::BtSearchResultArea(), and initConnections().
keySelected
void Search::CSearchResultView::keySelected (const QString &) signal
Referenced by Search::BtSearchResultArea::BtSearchResultArea(), and initConnections().
mimeData()
QMimeData * Search::CSearchResultView::mimeData (QList< QTreeWidgetItem * > const & items) const override protected
Todo:
port this to the new d'n'd
Definition at line 225 of file csearchresultview.cpp.
References m_module, and CSwordModuleInfo::name().
mimeTypes()
QStringList Search::CSearchResultView::mimeTypes () const override protected
Definition at line 234 of file csearchresultview.cpp.
module()
CSwordModuleInfo const * Search::CSearchResultView::module () const inline
Returns
the module which is currently used.
Definition at line 35 of file csearchresultview.h.
References m_module.
setupStrongsTree
void Search::CSearchResultView::setupStrongsTree (CSwordModuleInfo * m, const QStringList & vList) slot
Todo:
select the first item
Definition at line 174 of file csearchresultview.cpp.
References m_module.
Referenced by Search::BtSearchResultArea::BtSearchResultArea().
setupTree
void Search::CSearchResultView::setupTree (CSwordModuleInfo const * m, CSwordModuleSearch::ModuleResultList const & result) slot
Setups the list with the given module.
Definition at line 147 of file csearchresultview.cpp.
References m_module, and result.
Referenced by Search::BtSearchResultArea::BtSearchResultArea().
Member Data Documentation
[struct]
struct { ... } Search::CSearchResultView::copy
copyMenu
QMenu* Search::CSearchResultView::copyMenu
Definition at line 76 of file csearchresultview.h.
[struct]
struct { ... } Search::CSearchResultView::m_actions
Referenced by initView().
m_module
const CSwordModuleInfo* Search::CSearchResultView::m_module private
Definition at line 86 of file csearchresultview.h.
Referenced by initView(), mimeData(), module(), setupStrongsTree(), and setupTree().
m_popup
QMenu* Search::CSearchResultView::m_popup private
Definition at line 85 of file csearchresultview.h.
Referenced by contextMenuEvent(), and initView().
[struct]
struct { ... } Search::CSearchResultView::print
printMenu
QMenu* Search::CSearchResultView::printMenu
Definition at line 70 of file csearchresultview.h.
result
QAction* Search::CSearchResultView::result
Definition at line 65 of file csearchresultview.h.
Referenced by setupTree().
resultWithText
QAction* Search::CSearchResultView::resultWithText
Definition at line 66 of file csearchresultview.h.
[struct]
struct { ... } Search::CSearchResultView::save
saveMenu
QMenu* Search::CSearchResultView::saveMenu
Definition at line 63 of file csearchresultview.h.
The documentation for this class was generated from the following files:
csearchresultview.h
csearchresultview.cpp