BibleTime: BtOpenWorkActionMenu Class Reference
BtOpenWorkActionMenu Class Reference
#include <btopenworkaction.h>
Signals
void triggered (CSwordModuleInfo *module)
Signals inherited from BtMenuView
void triggered (QModelIndex index)
Public Member Functions
BtOpenWorkActionMenu (BtConfigCore groupingConfigGroup, QString groupingConfigKey, QWidget *parent=nullptr)
BtBookshelfFilterModel * postFilterModel () const
void setSourceModel (std::shared_ptr< QAbstractItemModel > model)
std::shared_ptr< QAbstractItemModel > sourceModel () const
BtBookshelfTreeModel * treeModel () const
Public Member Functions inherited from BtMenuView
BtMenuView (QString const &title, QWidget *parent=nullptr)
BtMenuView (QWidget *parent=nullptr)
bool event (QEvent *e) override
QAbstractItemModel * model () const
void setModel (QAbstractItemModel *model)
~BtMenuView () override
Private Member Functions
void postBuildMenu (QActionGroup *actions) override
void retranslateUi ()
Private Attributes
BtConfigCore m_groupingConfigGroup
QString const m_groupingConfigKey
BtBookshelfGroupingMenu * m_groupingMenu
BtBookshelfFilterModel * m_postFilterModel
BtBookshelfTreeModel * m_treeModel
Additional Inherited Members
Protected Member Functions inherited from BtMenuView
virtual QAction * newAction (QMenu *parentMenu, const QModelIndex &itemIndex)
virtual QMenu * newMenu (QMenu *parentMenu, const QModelIndex &itemIndex)
virtual void preBuildMenu (QActionGroup *actions)
void rebuildMenu ()
Rebuilds the menu.
Detailed Description
Definition at line 32 of file btopenworkaction.h.
Constructor & Destructor Documentation
BtOpenWorkActionMenu()
BtOpenWorkActionMenu::BtOpenWorkActionMenu (BtConfigCore groupingConfigGroup, QString groupingConfigKey, QWidget * parent = nullptr)
Definition at line 29 of file btopenworkaction.cpp.
References BT_CONNECT, m_groupingConfigGroup, m_groupingConfigKey, m_postFilterModel, m_treeModel, BtMenuView::model(), BtBookshelfModel::ModulePointerRole, BtMenuView::setModel(), triggered(), and BtMenuView::triggered().
Member Function Documentation
postBuildMenu()
void BtOpenWorkActionMenu::postBuildMenu (QActionGroup * actions) override private virtual
This method is called by BtMenuView after populating itself with data from the model. If there was no model set, this method is still called after preBuildMenu(). Reimplement this method to add any menus/actions to this menu after the items of the menu. The default implementation does nothing.
Reimplemented from BtMenuView.
Definition at line 70 of file btopenworkaction.cpp.
References BT_CONNECT, BtBookshelfTreeModel::groupingOrder(), m_groupingConfigGroup, m_groupingConfigKey, m_groupingMenu, m_treeModel, retranslateUi(), BtBookshelfTreeModel::Grouping::saveTo(), BtBookshelfGroupingMenu::setGrouping(), BtBookshelfTreeModel::setGroupingOrder(), and BtBookshelfGroupingMenu::signalGroupingOrderChanged().
postFilterModel()
BtBookshelfFilterModel * BtOpenWorkActionMenu::postFilterModel () const inline
Definition at line 46 of file btopenworkaction.h.
References m_postFilterModel.
Referenced by BtOpenWorkAction::BtOpenWorkAction().
retranslateUi()
void BtOpenWorkActionMenu::retranslateUi () private
Definition at line 62 of file btopenworkaction.cpp.
References m_groupingMenu.
Referenced by postBuildMenu().
setSourceModel()
void BtOpenWorkActionMenu::setSourceModel (std::shared_ptr< QAbstractItemModel > model)
Definition at line 58 of file btopenworkaction.cpp.
References m_treeModel, BtMenuView::model(), and BtBookshelfTreeModel::setSourceModel().
Referenced by BtOpenWorkAction::BtOpenWorkAction().
sourceModel()
std::shared_ptr< QAbstractItemModel > BtOpenWorkActionMenu::sourceModel () const inline
Definition at line 41 of file btopenworkaction.h.
References m_treeModel, and BtBookshelfTreeModel::sourceModel().
treeModel()
BtBookshelfTreeModel * BtOpenWorkActionMenu::treeModel () const inline
Definition at line 44 of file btopenworkaction.h.
References m_treeModel.
triggered
void BtOpenWorkActionMenu::triggered (CSwordModuleInfo * module) signal
Referenced by BtOpenWorkAction::BtOpenWorkAction(), and BtOpenWorkActionMenu().
Member Data Documentation
m_groupingConfigGroup
BtConfigCore BtOpenWorkActionMenu::m_groupingConfigGroup private
Definition at line 64 of file btopenworkaction.h.
Referenced by BtOpenWorkActionMenu(), and postBuildMenu().
m_groupingConfigKey
QString const BtOpenWorkActionMenu::m_groupingConfigKey private
Definition at line 65 of file btopenworkaction.h.
Referenced by BtOpenWorkActionMenu(), and postBuildMenu().
m_groupingMenu
BtBookshelfGroupingMenu* BtOpenWorkActionMenu::m_groupingMenu private
Definition at line 63 of file btopenworkaction.h.
Referenced by postBuildMenu(), and retranslateUi().
m_postFilterModel
BtBookshelfFilterModel* BtOpenWorkActionMenu::m_postFilterModel private
Definition at line 60 of file btopenworkaction.h.
Referenced by BtOpenWorkActionMenu(), and postFilterModel().
m_treeModel
BtBookshelfTreeModel* BtOpenWorkActionMenu::m_treeModel private
Definition at line 59 of file btopenworkaction.h.
Referenced by BtOpenWorkActionMenu(), postBuildMenu(), setSourceModel(), sourceModel(), and treeModel().
The documentation for this class was generated from the following files:
btopenworkaction.h
btopenworkaction.cpp