BibleTime: Search::BtSearchSyntaxHelpDialog Class Reference
Search::BtSearchSyntaxHelpDialog Class Reference
#include <btsearchsyntaxhelpdialog.h>
Public Member Functions
BtSearchSyntaxHelpDialog (QWidget *parent=nullptr, Qt::WindowFlags wflags=Qt::Dialog)
Protected Member Functions
void retranslateUi ()
Private Attributes
QDialogButtonBox * m_buttons
QTextBrowser * m_textBrowser
Detailed Description
Definition at line 28 of file btsearchsyntaxhelpdialog.h.
Constructor & Destructor Documentation
BtSearchSyntaxHelpDialog()
Search::BtSearchSyntaxHelpDialog::BtSearchSyntaxHelpDialog (QWidget * parent = nullptr, Qt::WindowFlags wflags = Qt::Dialog)
Definition at line 30 of file btsearchsyntaxhelpdialog.cpp.
References BT_CONNECT, m_buttons, m_textBrowser, and retranslateUi().
Member Function Documentation
retranslateUi()
void Search::BtSearchSyntaxHelpDialog::retranslateUi () protected
Definition at line 62 of file btsearchsyntaxhelpdialog.cpp.
References m_buttons, m_textBrowser, and message::prepareDialogBox().
Referenced by BtSearchSyntaxHelpDialog().
Member Data Documentation
m_buttons
QDialogButtonBox* Search::BtSearchSyntaxHelpDialog::m_buttons private
Definition at line 38 of file btsearchsyntaxhelpdialog.h.
Referenced by BtSearchSyntaxHelpDialog(), and retranslateUi().
m_textBrowser
QTextBrowser* Search::BtSearchSyntaxHelpDialog::m_textBrowser private
Definition at line 37 of file btsearchsyntaxhelpdialog.h.
Referenced by BtSearchSyntaxHelpDialog(), and retranslateUi().
The documentation for this class was generated from the following files:
btsearchsyntaxhelpdialog.h
btsearchsyntaxhelpdialog.cpp