BibleTime: CBookKeyChooser Class Reference
CBookKeyChooser Class Reference final
#include <cbookkeychooser.h>
Public Slots
void updateKey (CSwordKey *key) final override
Updates the keychoosers for the given key but emit no signal.
Public Slots inherited from CKeyChooser
void handleHistoryMoved (QString const &newKey)
virtual void updateKey (CSwordKey *key)=0
Public Member Functions
CBookKeyChooser (BtConstModuleList const &modules, CSwordKey *key=nullptr, QWidget *parent=nullptr)
CSwordKey * key () final override
void refreshContent () final override
void setKey (CSwordKey *key) final override
void setKey (CSwordKey *key, bool const emitSignal)
Sets a new key to this keychooser.
void setModules (BtConstModuleList const &modules, bool refresh=false) final override
Protected Member Functions
void setupCombo (QString const &key, int const depth, int const currentItem)
Protected Member Functions inherited from CKeyChooser
CKeyChooser (QWidget *parent=nullptr)
Private Slots
void keyChooserChanged (int)
A keychooser changed. Update and emit a signal if necessary.
Private Member Functions
void adjustFont ()
Private Attributes
QList< CKeyChooserWidget * > m_chooserWidgets
CSwordTreeKey * m_key
QHBoxLayout * m_layout
QList< CSwordBookModuleInfo const * > m_modules
Additional Inherited Members
Signals inherited from CKeyChooser
void keyChanged (CSwordKey *newKey)
Static Public Member Functions inherited from CKeyChooser
static CKeyChooser * createInstance (const BtConstModuleList &modules, CSwordKey *key, QWidget *parent)
Detailed Description
Definition at line 30 of file cbookkeychooser.h.
Constructor & Destructor Documentation
CBookKeyChooser()
CBookKeyChooser::CBookKeyChooser (BtConstModuleList const & modules, CSwordKey * key = nullptr, QWidget * parent = nullptr)
Definition at line 37 of file cbookkeychooser.cpp.
References adjustFont(), key(), m_key, setKey(), and setModules().
Member Function Documentation
adjustFont()
void CBookKeyChooser::adjustFont () private
No descriptions
Definition at line 202 of file cbookkeychooser.cpp.
References btConfig(), BtConfig::getFontForLanguage(), m_chooserWidgets, and m_modules.
Referenced by CBookKeyChooser(), and setModules().
key()
CSwordKey * CBookKeyChooser::key () final override virtual
Returns the key of this kechooser.
Implements CKeyChooser.
Definition at line 123 of file cbookkeychooser.cpp.
References m_key.
Referenced by CBookKeyChooser(), setKey(), setupCombo(), and updateKey().
keyChooserChanged
void CBookKeyChooser::keyChooserChanged (int newIndex) private slot
A keychooser changed. Update and emit a signal if necessary.
A keychooser changed. Update and emit a signal if necessary.
Definition at line 240 of file cbookkeychooser.cpp.
References BT_ASSERT, CKeyChooserWidget::comboBox(), ID_PROPERTY_NAME, m_chooserWidgets, m_key, CSwordTreeKey::setKey(), and setKey().
Referenced by setModules().
refreshContent()
void CBookKeyChooser::refreshContent () final override virtual
Refreshes the content.
Implements CKeyChooser.
Definition at line 211 of file cbookkeychooser.cpp.
References m_key, and updateKey().
setKey() [1/2]
void CBookKeyChooser::setKey (CSwordKey * key) final override virtual
Sets the CKey
Parameters
key the key which the widget should be set to.
Implements CKeyChooser.
Definition at line 50 of file cbookkeychooser.cpp.
References setKey().
Referenced by CBookKeyChooser(), keyChooserChanged(), setKey(), and updateKey().
setKey() [2/2]
void CBookKeyChooser::setKey (CSwordKey * newKey, bool const emitSignal)
Sets a new key to this keychooser.
Sets a new key to this keychooser
Definition at line 55 of file cbookkeychooser.cpp.
References CSwordTreeKey::getLocalNameUnicode(), CSwordTreeKey::hasChildren(), CSwordTreeKey::key(), key(), CKeyChooser::keyChanged(), m_chooserWidgets, m_key, m_modules, CSwordTreeKey::offset(), CSwordTreeKey::positionToFirstChild(), CSwordTreeKey::positionToNextSibling(), CSwordTreeKey::positionToRoot(), CKeyChooserWidget::reset(), CSwordTreeKey::setKey(), CSwordTreeKey::setOffset(), and setupCombo().
setModules()
void CBookKeyChooser::setModules (BtConstModuleList const & modules, bool refresh = false) final override virtual
Sets another module to this keychooser
Implements CKeyChooser.
Definition at line 128 of file cbookkeychooser.cpp.
References adjustFont(), BT_ASSERT, BT_CONNECT, CKeyChooserWidget::changed(), CKeyChooserWidget::comboBox(), CKeyChooserWidget::focusOut(), CSwordModuleInfo::GenericBook, ID_PROPERTY_NAME, keyChooserChanged(), m_chooserWidgets, m_key, m_layout, m_modules, and updateKey().
Referenced by CBookKeyChooser().
setupCombo()
void CBookKeyChooser::setupCombo (QString const & key, int const depth, int const currentItem) protected
Fills the combo given by depth with the items from the key having depth "depth". The parent sibling is given by key.
Definition at line 216 of file cbookkeychooser.cpp.
References CSwordTreeKey::getLocalNameUnicode(), key(), m_chooserWidgets, m_key, CSwordTreeKey::positionToFirstChild(), CSwordTreeKey::positionToNextSibling(), CSwordTreeKey::positionToParent(), CKeyChooserWidget::reset(), and CSwordTreeKey::setKey().
Referenced by setKey().
updateKey
void CBookKeyChooser::updateKey (CSwordKey * key) final override slot
Updates the keychoosers for the given key but emit no signal.
Updates the keychoosers for the given key but emit no signal.
Definition at line 261 of file cbookkeychooser.cpp.
References key(), and setKey().
Referenced by refreshContent(), and setModules().
Member Data Documentation
m_chooserWidgets
QList<CKeyChooserWidget *> CBookKeyChooser::m_chooserWidgets private
Definition at line 77 of file cbookkeychooser.h.
Referenced by adjustFont(), keyChooserChanged(), setKey(), setModules(), and setupCombo().
m_key
CSwordTreeKey* CBookKeyChooser::m_key private
Definition at line 79 of file cbookkeychooser.h.
Referenced by CBookKeyChooser(), key(), keyChooserChanged(), refreshContent(), setKey(), setModules(), and setupCombo().
m_layout
QHBoxLayout* CBookKeyChooser::m_layout private
Definition at line 80 of file cbookkeychooser.h.
Referenced by setModules().
m_modules
QList<CSwordBookModuleInfo const *> CBookKeyChooser::m_modules private
Definition at line 78 of file cbookkeychooser.h.
Referenced by adjustFont(), setKey(), and setModules().
The documentation for this class was generated from the following files:
cbookkeychooser.h
cbookkeychooser.cpp