BibleTime: CMDIArea Class Reference
CMDIArea Class Reference
#include <cmdiarea.h>
Public Types
enum MDIArrangementMode {
ArrangementModeTileVertical = 1 , ArrangementModeTileHorizontal = 2 , ArrangementModeCascade = 3 , ArrangementModeManual = 4 ,
ArrangementModeTile = 5 , ArrangementModeTabbed = 6
}
Public Slots
void findNextTextInActiveWindow ()
void findPreviousTextInActiveWindow ()
void highlightTextInActiveWindow (const QString &text, bool caseSensitive)
void myCascade ()
void myTile ()
void myTileHorizontal ()
void myTileVertical ()
Signals
void sigSetToplevelCaption (const QString &)
Public Member Functions
QMdiSubWindow * addDisplayWindow (CDisplayWindow *displayWindow)
BibleTime * bibleTimeWindow ()
CMDIArea (BibleTime *parent)
void enableWindowMinMaxFlags (bool enable)
MDIArrangementMode getMDIArrangementMode () const
void setMDIArrangementMode (const MDIArrangementMode mode)
void triggerWindowUpdate ()
QList< QMdiSubWindow * > usableWindowList () const
Protected Member Functions
void emitWindowCaptionChanged ()
bool eventFilter (QObject *o, QEvent *e) override
void findTextInActiveWindow (bool const backward)
void resizeEvent (QResizeEvent *e) override
Properties
MDIArrangementMode m_mdiArrangementMode
Private Attributes
CDisplayWindow * m_activeWindow
BibleTime * m_bibleTime
Detailed Description
A custom MDI area widget.
Definition at line 31 of file cmdiarea.h.
Member Enumeration Documentation
MDIArrangementMode
enum CMDIArea::MDIArrangementMode
Possible MDI subwindow arrangement modes.
Enumerator
ArrangementModeTileVertical
ArrangementModeTileHorizontal
ArrangementModeCascade
ArrangementModeManual
ArrangementModeTile
ArrangementModeTabbed
Definition at line 41 of file cmdiarea.h.
Constructor & Destructor Documentation
CMDIArea()
CMDIArea::CMDIArea (BibleTime * parent)
Parameters
[in] parent BibleTime main window used for parent widget.
Definition at line 44 of file cmdiarea.cpp.
References BT_CONNECT, BibleTime::clearMdiToolBars(), m_activeWindow, m_bibleTime, sigSetToplevelCaption(), and CDisplayWindow::windowActivated().
Member Function Documentation
addDisplayWindow()
QMdiSubWindow * CMDIArea::addDisplayWindow (CDisplayWindow * displayWindow)
Definition at line 85 of file cmdiarea.cpp.
References ArrangementModeManual, BT_CONNECT, enableWindowMinMaxFlags(), m_mdiArrangementMode, and triggerWindowUpdate().
Referenced by BibleTime::createReadDisplayWindow().
bibleTimeWindow()
BibleTime * CMDIArea::bibleTimeWindow () inline
Returns the BibleTime main window
Definition at line 62 of file cmdiarea.h.
References m_bibleTime.
emitWindowCaptionChanged()
void CMDIArea::emitWindowCaptionChanged () protected
Definition at line 323 of file cmdiarea.cpp.
References sigSetToplevelCaption().
Referenced by myCascade(), myTile(), myTileHorizontal(), and myTileVertical().
enableWindowMinMaxFlags()
void CMDIArea::enableWindowMinMaxFlags (bool enable)
Show or hide the sub-window min/max buttons.
Definition at line 438 of file cmdiarea.cpp.
Referenced by addDisplayWindow(), and BibleTime::slotUpdateWindowArrangementActions().
eventFilter()
bool CMDIArea::eventFilter (QObject * o, QEvent * e) override protected
Reimplementation of QObject::eventFilter() used to handle some MDI subwindow events.
Definition at line 371 of file cmdiarea.cpp.
References sigSetToplevelCaption(), and triggerWindowUpdate().
findNextTextInActiveWindow
void CMDIArea::findNextTextInActiveWindow () slot
Definition at line 342 of file cmdiarea.cpp.
References findTextInActiveWindow().
Referenced by BibleTime::createCentralWidget().
findPreviousTextInActiveWindow
void CMDIArea::findPreviousTextInActiveWindow () slot
Definition at line 344 of file cmdiarea.cpp.
References findTextInActiveWindow().
Referenced by BibleTime::createCentralWidget().
findTextInActiveWindow()
void CMDIArea::findTextInActiveWindow (bool const backward) protected
Definition at line 351 of file cmdiarea.cpp.
References CDisplayWindow::displayWidget(), and BtModelViewReadDisplay::findText().
Referenced by findNextTextInActiveWindow(), and findPreviousTextInActiveWindow().
getMDIArrangementMode()
MDIArrangementMode CMDIArea::getMDIArrangementMode () const inline
Returns the current MDI arrangement mode.
Definition at line 75 of file cmdiarea.h.
References m_mdiArrangementMode.
Referenced by BibleTime::saveProfile().
highlightTextInActiveWindow
void CMDIArea::highlightTextInActiveWindow (const QString & text, bool caseSensitive) slot
Definition at line 346 of file cmdiarea.cpp.
References CDisplayWindow::displayWidget(), and BtModelViewReadDisplay::highlightText().
Referenced by BibleTime::createCentralWidget().
myCascade
void CMDIArea::myCascade () slot
Our own cascade version which, if only one subwindow is left, shows it maximized.
Note
This not set an automatic arrangement mode, it just arranges the subwindows once. However, this method is also used when arranging the subwindows into a cascade automatically.
Definition at line 277 of file cmdiarea.cpp.
References emitWindowCaptionChanged(), and usableWindowList().
Referenced by BibleTime::slotUpdateWindowArrangementActions(), and triggerWindowUpdate().
myTile
void CMDIArea::myTile () slot
Our own auto tile version which, if only one subwindow is left, shows it
Note
This not set an automatic arrangement mode, it just arranges the subwindows once. However, this method is also used when arranging the subwindows into a tile automatically.
Definition at line 222 of file cmdiarea.cpp.
References emitWindowCaptionChanged(), and usableWindowList().
Referenced by setMDIArrangementMode(), BibleTime::slotUpdateWindowArrangementActions(), and triggerWindowUpdate().
myTileHorizontal
void CMDIArea::myTileHorizontal () slot
Our own horizontal tile version which, if only one subwindow is left, shows it maximized.
Note
This not set an automatic arrangement mode, it just arranges the subwindows once. However, this method is also used when arranging the subwindows into a horizontal tiling automatically.
Definition at line 188 of file cmdiarea.cpp.
References emitWindowCaptionChanged(), and usableWindowList().
Referenced by BibleTime::slotUpdateWindowArrangementActions(), and triggerWindowUpdate().
myTileVertical
void CMDIArea::myTileVertical () slot
Our own vertical tile version which, if only one subwindow is left, shows it maximized.
Note
This not set an automatic arrangement mode, it just arranges the subwindows once. However, this method is also used when arranging the subwindows into a vertical tiling automatically.
Definition at line 154 of file cmdiarea.cpp.
References emitWindowCaptionChanged(), and usableWindowList().
Referenced by BibleTime::processCommandline(), BibleTime::slotUpdateWindowArrangementActions(), and triggerWindowUpdate().
resizeEvent()
void CMDIArea::resizeEvent (QResizeEvent * e) override protected
Reimplementation of QWidget::resizeEvent() to handle our automatic tiling properly.
Definition at line 354 of file cmdiarea.cpp.
References ArrangementModeTabbed, m_mdiArrangementMode, and triggerWindowUpdate().
setMDIArrangementMode()
void CMDIArea::setMDIArrangementMode (const MDIArrangementMode mode)
Resets the MDI arrangement mode and arranges the windows.
Parameters
[in] mode new MDI arrangement mode.
Definition at line 134 of file cmdiarea.cpp.
References ArrangementModeManual, ArrangementModeTabbed, ArrangementModeTile, m_mdiArrangementMode, myTile(), and triggerWindowUpdate().
Referenced by BibleTime::reloadProfile(), and BibleTime::slotUpdateWindowArrangementActions().
sigSetToplevelCaption
void CMDIArea::sigSetToplevelCaption (const QString &) signal
Emits a signal to set the caption of the toplevel widget.
Referenced by CMDIArea(), emitWindowCaptionChanged(), and eventFilter().
triggerWindowUpdate()
void CMDIArea::triggerWindowUpdate ()
Forces an update of the currently chosen window arrangement.
Definition at line 417 of file cmdiarea.cpp.
References ArrangementModeCascade, ArrangementModeTile, ArrangementModeTileHorizontal, ArrangementModeTileVertical, m_mdiArrangementMode, myCascade(), myTile(), myTileHorizontal(), and myTileVertical().
Referenced by addDisplayWindow(), eventFilter(), BibleTime::reloadProfile(), resizeEvent(), setMDIArrangementMode(), and BibleTime::toggleFullscreen().
usableWindowList()
QList< QMdiSubWindow * > CMDIArea::usableWindowList () const
Returns
a lists of all subwindows which are not minimized or hidden.
Definition at line 332 of file cmdiarea.cpp.
Referenced by myCascade(), myTile(), myTileHorizontal(), myTileVertical(), and BibleTime::slotOpenWindowsMenuAboutToShow().
Member Data Documentation
m_activeWindow
CDisplayWindow* CMDIArea::m_activeWindow private
Definition at line 167 of file cmdiarea.h.
Referenced by CMDIArea().
m_bibleTime
BibleTime* CMDIArea::m_bibleTime private
Definition at line 168 of file cmdiarea.h.
Referenced by bibleTimeWindow(), and CMDIArea().
Property Documentation
m_mdiArrangementMode
MDIArrangementMode CMDIArea::m_mdiArrangementMode read write
Definition at line 34 of file cmdiarea.h.
Referenced by addDisplayWindow(), getMDIArrangementMode(), resizeEvent(), setMDIArrangementMode(), and triggerWindowUpdate().
The documentation for this class was generated from the following files:
cmdiarea.h
cmdiarea.cpp