BibleTime: BtBookshelfWorksPage Class Reference
BtBookshelfWorksPage Class Reference final
#include <btbookshelfworkspage.h>
Public Member Functions
BtBookshelfWorksPage (WizardTaskType iType, QWidget *parent=nullptr)
BtModuleSet const & checkedModules () const
void initializePage () final override
QString installPath () const
bool isComplete () const final override
int nextId () const final override
Public Member Functions inherited from BtBookshelfWizardPage
BtBookshelfWizardPage (QWidget *parent=nullptr)
BtBookshelfWizard & btWizard () const noexcept
Private Slots
void slotGroupingActionTriggered (BtBookshelfTreeModel::Grouping const &grouping)
void slotGroupingOrderChanged (BtBookshelfTreeModel::Grouping const &g)
void slotInitPathCombo ()
void slotPathChanged (int const index)
Private Member Functions
void retranslateUi ()
Private Attributes
std::shared_ptr< BtBookshelfModel > m_bookshelfModel
BtBookshelfView * m_bookshelfView
QMenu * m_contextMenu
QToolButton * m_groupingButton
QLabel * m_groupingLabel
BtBookshelfGroupingMenu * m_groupingMenu
BtBookshelfTreeModel::Grouping m_groupingOrder
BtInstallPageModel * m_installPageModel
QMenu * m_itemContextMenu
QLabel * m_msgLabel
QLineEdit * m_nameFilterEdit
QLabel * m_nameFilterLabel
QComboBox * m_pathCombo
QLabel * m_pathLabel
WizardTaskType const m_taskType
std::vector< std::unique_ptr< CSwordBackend const > > m_usedBackends
Detailed Description
Definition at line 38 of file btbookshelfworkspage.h.
Constructor & Destructor Documentation
BtBookshelfWorksPage()
BtBookshelfWorksPage::BtBookshelfWorksPage (WizardTaskType iType, QWidget * parent = nullptr)
Todo:
is this useless if m_taskType == WizardTaskType::removeWorks?
Definition at line 89 of file btbookshelfworkspage.cpp.
References BT_CONNECT, btConfig(), BtBookshelfTreeModel::CHECKED, BtBookshelfTreeModel::Grouping::DEFAULT, BtBookshelfTreeModel::groupingOrderChanged(), CSwordBackend::instance(), BtBookshelfTreeModel::Grouping::loadFrom(), m_bookshelfModel, m_bookshelfView, m_contextMenu, m_groupingButton, m_groupingLabel, m_groupingMenu, m_groupingOrder, m_installPageModel, m_itemContextMenu, m_msgLabel, m_nameFilterEdit, m_nameFilterLabel, m_pathCombo, m_pathLabel, m_taskType, BtBookshelfTreeModel::moduleChecked(), BtBookshelfModel::newInstance(), removeWorks, retranslateUi(), BtBookshelfTreeModel::setDefaultChecked(), BtBookshelfGroupingMenu::setGrouping(), BtBookshelfFilterModel::setNameFilterFixedString(), BtBookshelfTreeModel::setSourceModel(), BtBookshelfGroupingMenu::signalGroupingOrderChanged(), CSwordBackend::sigSwordSetupChanged(), slotGroupingActionTriggered(), slotGroupingOrderChanged(), slotInitPathCombo(), slotPathChanged(), and updateWorks.
Member Function Documentation
checkedModules()
BtModuleSet const & BtBookshelfWorksPage::checkedModules () const
Definition at line 327 of file btbookshelfworkspage.cpp.
References BtBookshelfTreeModel::checkedModules(), and m_installPageModel.
Referenced by isComplete(), and BtBookshelfWizard::selectedWorks().
initializePage()
void BtBookshelfWorksPage::initializePage () final override
Definition at line 254 of file btbookshelfworkspage.cpp.
References BtInstallBackend::backend(), BtBookshelfWizardPage::btWizard(), BtBookshelfTreeModel::Grouping::CAT, BtBookshelfTreeModel::Grouping::CAT_LANG, installWorks, m_bookshelfModel, m_bookshelfView, m_groupingButton, m_groupingLabel, m_groupingOrder, m_msgLabel, m_taskType, m_usedBackends, BtBookshelfWizard::selectedLanguages(), BtBookshelfWizard::selectedSources(), slotGroupingActionTriggered(), BtInstallBackend::source(), and BtInstallBackend::sourceNameList().
installPath()
QString BtBookshelfWorksPage::installPath () const
Definition at line 330 of file btbookshelfworkspage.cpp.
References m_pathCombo.
Referenced by BtBookshelfWizard::installPath().
isComplete()
bool BtBookshelfWorksPage::isComplete () const final override
Definition at line 317 of file btbookshelfworkspage.cpp.
References checkedModules().
nextId()
int BtBookshelfWorksPage::nextId () const final override
Definition at line 248 of file btbookshelfworkspage.cpp.
References BtBookshelfWizardPage::btWizard(), installFinalPage, removeFinalPage, and removeWorks.
retranslateUi()
void BtBookshelfWorksPage::retranslateUi () private
Definition at line 200 of file btbookshelfworkspage.cpp.
References BT_ASSERT, installWorks, m_groupingButton, m_groupingLabel, m_msgLabel, m_nameFilterLabel, m_pathCombo, m_pathLabel, m_taskType, removeWorks, and updateWorks.
Referenced by BtBookshelfWorksPage().
slotGroupingActionTriggered
void BtBookshelfWorksPage::slotGroupingActionTriggered (BtBookshelfTreeModel::Grouping const & grouping) private slot
Definition at line 310 of file btbookshelfworkspage.cpp.
References BtBookshelfTreeModel::Grouping::list(), m_bookshelfView, m_installPageModel, and BtBookshelfTreeModel::setGroupingOrder().
Referenced by BtBookshelfWorksPage(), and initializePage().
slotGroupingOrderChanged
void BtBookshelfWorksPage::slotGroupingOrderChanged (BtBookshelfTreeModel::Grouping const & g) private slot
Definition at line 320 of file btbookshelfworkspage.cpp.
References btConfig(), m_groupingOrder, and BtBookshelfTreeModel::Grouping::saveTo().
Referenced by BtBookshelfWorksPage().
slotInitPathCombo
void BtBookshelfWorksPage::slotInitPathCombo () private slot
Definition at line 345 of file btbookshelfworkspage.cpp.
References btConfig(), installPathIsUsable(), CSwordBackend::instance(), m_pathCombo, m_pathLabel, CSwordBackend::swordDirList(), and BtConfigCore::value().
Referenced by BtBookshelfWorksPage().
slotPathChanged
void BtBookshelfWorksPage::slotPathChanged (int const index) private slot
Definition at line 333 of file btbookshelfworkspage.cpp.
References btConfig(), and BtConfigCore::setValue().
Referenced by BtBookshelfWorksPage().
Member Data Documentation
m_bookshelfModel
std::shared_ptr<BtBookshelfModel> BtBookshelfWorksPage::m_bookshelfModel private
Definition at line 81 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), and initializePage().
m_bookshelfView
BtBookshelfView* BtBookshelfWorksPage::m_bookshelfView private
Definition at line 70 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), initializePage(), and slotGroupingActionTriggered().
m_contextMenu
QMenu* BtBookshelfWorksPage::m_contextMenu private
Definition at line 83 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage().
m_groupingButton
QToolButton* BtBookshelfWorksPage::m_groupingButton private
Definition at line 69 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), initializePage(), and retranslateUi().
m_groupingLabel
QLabel* BtBookshelfWorksPage::m_groupingLabel private
Definition at line 73 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), initializePage(), and retranslateUi().
m_groupingMenu
BtBookshelfGroupingMenu* BtBookshelfWorksPage::m_groupingMenu private
Definition at line 84 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage().
m_groupingOrder
BtBookshelfTreeModel::Grouping BtBookshelfWorksPage::m_groupingOrder private
Definition at line 67 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), initializePage(), and slotGroupingOrderChanged().
m_installPageModel
BtInstallPageModel* BtBookshelfWorksPage::m_installPageModel private
Definition at line 79 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), checkedModules(), and slotGroupingActionTriggered().
m_itemContextMenu
QMenu* BtBookshelfWorksPage::m_itemContextMenu private
Definition at line 85 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage().
m_msgLabel
QLabel* BtBookshelfWorksPage::m_msgLabel private
Definition at line 71 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), initializePage(), and retranslateUi().
m_nameFilterEdit
QLineEdit* BtBookshelfWorksPage::m_nameFilterEdit private
Definition at line 77 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage().
m_nameFilterLabel
QLabel* BtBookshelfWorksPage::m_nameFilterLabel private
Definition at line 76 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), and retranslateUi().
m_pathCombo
QComboBox* BtBookshelfWorksPage::m_pathCombo private
Definition at line 74 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), installPath(), retranslateUi(), and slotInitPathCombo().
m_pathLabel
QLabel* BtBookshelfWorksPage::m_pathLabel private
Definition at line 72 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), retranslateUi(), and slotInitPathCombo().
m_taskType
WizardTaskType const BtBookshelfWorksPage::m_taskType private
Definition at line 66 of file btbookshelfworkspage.h.
Referenced by BtBookshelfWorksPage(), initializePage(), and retranslateUi().
m_usedBackends
std::vector<std::unique_ptr<CSwordBackend const> > BtBookshelfWorksPage::m_usedBackends private
Definition at line 80 of file btbookshelfworkspage.h.
Referenced by initializePage().
The documentation for this class was generated from the following files:
btbookshelfworkspage.h
btbookshelfworkspage.cpp