BibleTime: BTMimeData Class Reference
BTMimeData Class Reference
#include <BtMimeData.h>
Public Types
using ItemList = QList< BookmarkItem >
Public Member Functions
void appendBookmark (QString const &module, QString const &key, QString const &description)
const BookmarkItem & bookmark () const
const ItemList & bookmarks () const noexcept
BTMimeData ()
BTMimeData (QString const &module, QString const &key, QString const &description)
BTMimeData (QString const &text)
Private Attributes
ItemList m_bookmarkList
Detailed Description
Represents the Drag'n'Drop data. Inherits QMimeData as described in its documentation, "storing custom data in a QMimeData object": approach 3. Any custom data may be added and extracted as with QMimeData, but this class includes also a list of bookmark items. For further documentation see http://doc.trolltech.com/4.3/dnd.html
Definition at line 31 of file BtMimeData.h.
Member Typedef Documentation
ItemList
using BTMimeData::ItemList = QList<BookmarkItem>
Type for bookmark item list. Usage: BTMimeData::ItemList.
Definition at line 48 of file BtMimeData.h.
Constructor & Destructor Documentation
BTMimeData() [1/3]
BTMimeData::BTMimeData ()
Creates a new empty BTMimeData.
Definition at line 18 of file BtMimeData.cpp.
BTMimeData() [2/3]
BTMimeData::BTMimeData (QString const & module, QString const & key, QString const & description)
Creates a new BTMimeData. Creates a new bookmark item and appends it to the list. MIME type "BibleTime/Bookmark" is added. Bookmarks can not be reached by data() method, use bookmark() or bookmarks() instead.
Definition at line 20 of file BtMimeData.cpp.
References appendBookmark().
BTMimeData() [3/3]
BTMimeData::BTMimeData (QString const & text)
Creates a new BTMimeData, setting the text MIME type (see QMimeData::setText()).
Definition at line 25 of file BtMimeData.cpp.
Member Function Documentation
appendBookmark()
void BTMimeData::appendBookmark (QString const & module, QString const & key, QString const & description)
Appends a new bookmark item into the list. Creates the item using the arguments. MIME type "BibleTime/Bookmark" is added.
Definition at line 28 of file BtMimeData.cpp.
References m_bookmarkList.
Referenced by BTMimeData(), Search::CSearchResultView::contextMenuEvent(), and CBookmarkIndex::dragObject().
bookmark()
const BookmarkItem& BTMimeData::bookmark () const inline
Returns
the first bookmark item in the list.
Definition at line 80 of file BtMimeData.h.
bookmarks()
const ItemList& BTMimeData::bookmarks () const inline noexcept
Returns
the bookmarks list.
Definition at line 77 of file BtMimeData.h.
Member Data Documentation
m_bookmarkList
ItemList BTMimeData::m_bookmarkList private
Definition at line 84 of file BtMimeData.h.
Referenced by appendBookmark().
The documentation for this class was generated from the following files:
BtMimeData.h
BtMimeData.cpp