BibleTime: BtBookshelfSourcesPage Class Reference
BtBookshelfSourcesPage Class Reference final
#include <btbookshelfsourcespage.h>
Public Member Functions
BtBookshelfSourcesPage (QWidget *parent=nullptr)
void initializePage () final override
bool isComplete () const final override
int nextId () const final override
QStringList selectedSources () const
Public Member Functions inherited from BtBookshelfWizardPage
BtBookshelfWizardPage (QWidget *parent=nullptr)
BtBookshelfWizard & btWizard () const noexcept
Private Slots
void slotButtonClicked (int row)
Private Member Functions
void retranslateUi ()
void selectSourcesInModel (QStringList const &sources)
void updateSourcesModel ()
Private Attributes
bool m_firstTimeInit = true
BtListModel * m_model
QTableView * m_sourcesTableView
QVBoxLayout * m_verticalLayout
Detailed Description
Definition at line 27 of file btbookshelfsourcespage.h.
Constructor & Destructor Documentation
BtBookshelfSourcesPage()
BtBookshelfSourcesPage::BtBookshelfSourcesPage (QWidget * parent = nullptr)
Definition at line 60 of file btbookshelfsourcespage.cpp.
Member Function Documentation
initializePage()
void BtBookshelfSourcesPage::initializePage () final override
Definition at line 95 of file btbookshelfsourcespage.cpp.
References btConfig(), anonymous_namespace{btbookshelfsourcespage.cpp}::initialSelection, m_firstTimeInit, retranslateUi(), selectedSources(), selectSourcesInModel(), anonymous_namespace{btbookshelfsourcespage.cpp}::SourcesKey, updateSourcesModel(), and BtConfigCore::value().
isComplete()
bool BtBookshelfSourcesPage::isComplete () const final override
Definition at line 169 of file btbookshelfsourcespage.cpp.
References m_model.
nextId()
int BtBookshelfSourcesPage::nextId () const final override
Definition at line 87 of file btbookshelfsourcespage.cpp.
References BtBookshelfWizardPage::btWizard(), installWorksPage, languagesPage, and BtBookshelfWizard::languagesPage().
retranslateUi()
void BtBookshelfSourcesPage::retranslateUi () private
Definition at line 79 of file btbookshelfsourcespage.cpp.
Referenced by initializePage().
selectedSources()
QStringList BtBookshelfSourcesPage::selectedSources () const
Definition at line 176 of file btbookshelfsourcespage.cpp.
References m_model.
Referenced by initializePage(), BtBookshelfWizard::selectedSources(), and slotButtonClicked().
selectSourcesInModel()
void BtBookshelfSourcesPage::selectSourcesInModel (QStringList const & sources) private
Definition at line 114 of file btbookshelfsourcespage.cpp.
References m_model.
Referenced by initializePage(), and slotButtonClicked().
slotButtonClicked
void BtBookshelfSourcesPage::slotButtonClicked (int row) private slot
Definition at line 186 of file btbookshelfsourcespage.cpp.
References BtInstallBackend::addSource(), anonymous_namespace{btbookshelfsourcespage.cpp}::buttonPropertyName, anonymous_namespace{btbookshelfsourcespage.cpp}::ButtonTagRemove, BtInstallBackend::deleteSource(), CSwordSetupInstallSourcesDialog::getSource(), m_model, m_sourcesTableView, selectedSources(), selectSourcesInModel(), updateSourcesModel(), and CSwordSetupInstallSourcesDialog::wasRemoteListAdded().
Referenced by updateSourcesModel().
updateSourcesModel()
void BtBookshelfSourcesPage::updateSourcesModel () private
Definition at line 122 of file btbookshelfsourcespage.cpp.
References BtListModel::appendItem(), BT_CONNECT, anonymous_namespace{btbookshelfsourcespage.cpp}::buttonPropertyName, anonymous_namespace{btbookshelfsourcespage.cpp}::ButtonTagAdd, anonymous_namespace{btbookshelfsourcespage.cpp}::ButtonTagRemove, m_model, m_sourcesTableView, slotButtonClicked(), BtInstallBackend::source(), and BtInstallBackend::sourceNameList().
Referenced by initializePage(), and slotButtonClicked().
Member Data Documentation
m_firstTimeInit
bool BtBookshelfSourcesPage::m_firstTimeInit = true private
Definition at line 52 of file btbookshelfsourcespage.h.
Referenced by initializePage().
m_model
BtListModel* BtBookshelfSourcesPage::m_model private
Definition at line 55 of file btbookshelfsourcespage.h.
Referenced by isComplete(), selectedSources(), selectSourcesInModel(), slotButtonClicked(), and updateSourcesModel().
m_sourcesTableView
QTableView* BtBookshelfSourcesPage::m_sourcesTableView private
Definition at line 53 of file btbookshelfsourcespage.h.
Referenced by slotButtonClicked(), and updateSourcesModel().
m_verticalLayout
QVBoxLayout* BtBookshelfSourcesPage::m_verticalLayout private
Definition at line 54 of file btbookshelfsourcespage.h.
The documentation for this class was generated from the following files:
btbookshelfsourcespage.h
btbookshelfsourcespage.cpp