BibleTime: Search::BtSearchResultArea Class Reference
Search::BtSearchResultArea Class Reference
#include <btsearchresultarea.h>
Public Slots
void reset ()
void showAnalysis ()
Public Member Functions
BtSearchResultArea (QWidget *parent=nullptr)
QSize minimumSizeHint () const override
void setSearchResult (QString searchedText, CSwordModuleSearch::Results results)
QSize sizeHint () const override
~BtSearchResultArea () override
Protected Slots
void clearPreview ()
void copySelection ()
void updatePreview (const QString &key)
Protected Member Functions
void loadDialogSettings ()
void saveDialogSettings () const
void setBrowserFont (const CSwordModuleInfo *const module)
Private Attributes
QMenu * m_contextMenu
QAction * m_copyAction
QFrame * m_displayFrame
QSplitter * m_mainSplitter
CModuleResultView * m_moduleListBox
BtTextBrowser * m_previewDisplay
CSearchResultView * m_resultListBox
QSplitter * m_resultListSplitter
CSwordModuleSearch::Results m_results
QString m_searchedText
QAction * m_selectAllAction
Detailed Description
The page of the search dialog which contains the search result part.
Author
The BibleTime team
Definition at line 78 of file btsearchresultarea.h.
Constructor & Destructor Documentation
BtSearchResultArea()
Search::BtSearchResultArea::BtSearchResultArea (QWidget * parent = nullptr)
Definition at line 53 of file btsearchresultarea.cpp.
References BT_CONNECT, clearPreview(), Search::CSearchResultView::keyDeselected(), Search::CSearchResultView::keySelected(), loadDialogSettings(), m_contextMenu, m_copyAction, m_displayFrame, m_mainSplitter, m_moduleListBox, m_previewDisplay, m_resultListBox, m_resultListSplitter, m_selectAllAction, Search::CModuleResultView::moduleChanged(), Search::CModuleResultView::moduleSelected(), util::tool::mWidth(), Search::CSearchResultView::setupStrongsTree(), Search::CSearchResultView::setupTree(), Search::CModuleResultView::strongsSelected(), and updatePreview().
~BtSearchResultArea()
Search::BtSearchResultArea::~BtSearchResultArea () inline override
Definition at line 82 of file btsearchresultarea.h.
References saveDialogSettings().
Member Function Documentation
clearPreview
void Search::BtSearchResultArea::clearPreview () protected slot
Clear the preview of the selected key.
Definition at line 151 of file btsearchresultarea.cpp.
References m_previewDisplay.
Referenced by BtSearchResultArea(), and reset().
copySelection
void Search::BtSearchResultArea::copySelection () inline protected slot
Copy selected text
Definition at line 136 of file btsearchresultarea.h.
References m_previewDisplay.
loadDialogSettings()
void Search::BtSearchResultArea::loadDialogSettings () protected
Load the settings from the resource file
Definition at line 254 of file btsearchresultarea.cpp.
References btConfig(), m_mainSplitter, m_moduleListBox, m_resultListSplitter, Search::CModuleResultView::sizeHint(), and BtConfigCore::value().
Referenced by BtSearchResultArea().
minimumSizeHint()
QSize Search::BtSearchResultArea::minimumSizeHint () const inline override
Definition at line 94 of file btsearchresultarea.h.
reset
void Search::BtSearchResultArea::reset () slot
Resets the current list of modules and the displayed list of found entries.
Definition at line 145 of file btsearchresultarea.cpp.
References clearPreview(), m_moduleListBox, and m_resultListBox.
Referenced by Search::CSearchDialog::reset(), setSearchResult(), and Search::CSearchDialog::startSearch().
saveDialogSettings()
void Search::BtSearchResultArea::saveDialogSettings () const protected
Save the settings to the resource file
Definition at line 274 of file btsearchresultarea.cpp.
References btConfig(), m_mainSplitter, m_resultListSplitter, and BtConfigCore::setValue().
Referenced by ~BtSearchResultArea().
setBrowserFont()
void Search::BtSearchResultArea::setBrowserFont (const CSwordModuleInfo *const module) protected
Definition at line 242 of file btsearchresultarea.cpp.
References btConfig(), and m_previewDisplay.
Referenced by updatePreview().
setSearchResult()
void Search::BtSearchResultArea::setSearchResult (QString searchedText, CSwordModuleSearch::Results results)
Sets the modules which contain the result of each.
Definition at line 130 of file btsearchresultarea.cpp.
References m_moduleListBox, m_results, m_searchedText, reset(), and Search::CModuleResultView::setupTree().
Referenced by Search::CSearchDialog::startSearch().
showAnalysis
void Search::BtSearchResultArea::showAnalysis () inline slot
Shows a dialog with the search analysis of the current search.
Definition at line 105 of file btsearchresultarea.h.
References m_results, and m_searchedText.
Referenced by Search::CSearchDialog::CSearchDialog().
sizeHint()
QSize Search::BtSearchResultArea::sizeHint () const inline override
Definition at line 90 of file btsearchresultarea.h.
updatePreview
void Search::BtSearchResultArea::updatePreview (const QString & key) protected slot
Update the preview of the selected key.
Definition at line 156 of file btsearchresultarea.cpp.
References CSwordModuleInfo::Bible, CSwordVerseKey::chapter(), CSwordModuleInfo::Commentary, CSwordModuleSearch::highlightSearchedText(), Rendering::CTextRendering::KeyTreeItem::Settings::keyRenderingFace, m_previewDisplay, m_searchedText, CSwordVerseKey::next(), CSwordVerseKey::previous(), Rendering::CTextRendering::renderKeyRange(), Rendering::CTextRendering::renderSingleKey(), ColorManager::replaceColors(), setBrowserFont(), CSwordVerseKey::setChapter(), CSwordVerseKey::setIntros(), CSwordVerseKey::setKey(), CSwordVerseKey::setVerse(), and CSwordVerseKey::verse().
Referenced by BtSearchResultArea().
Member Data Documentation
m_contextMenu
QMenu* Search::BtSearchResultArea::m_contextMenu private
Definition at line 149 of file btsearchresultarea.h.
Referenced by BtSearchResultArea().
m_copyAction
QAction* Search::BtSearchResultArea::m_copyAction private
Definition at line 151 of file btsearchresultarea.h.
Referenced by BtSearchResultArea().
m_displayFrame
QFrame* Search::BtSearchResultArea::m_displayFrame private
Definition at line 147 of file btsearchresultarea.h.
Referenced by BtSearchResultArea().
m_mainSplitter
QSplitter* Search::BtSearchResultArea::m_mainSplitter private
Definition at line 155 of file btsearchresultarea.h.
Referenced by BtSearchResultArea(), loadDialogSettings(), and saveDialogSettings().
m_moduleListBox
CModuleResultView* Search::BtSearchResultArea::m_moduleListBox private
Definition at line 144 of file btsearchresultarea.h.
Referenced by BtSearchResultArea(), loadDialogSettings(), reset(), and setSearchResult().
m_previewDisplay
BtTextBrowser* Search::BtSearchResultArea::m_previewDisplay private
Definition at line 153 of file btsearchresultarea.h.
Referenced by BtSearchResultArea(), clearPreview(), copySelection(), setBrowserFont(), and updatePreview().
m_resultListBox
CSearchResultView* Search::BtSearchResultArea::m_resultListBox private
Definition at line 145 of file btsearchresultarea.h.
Referenced by BtSearchResultArea(), and reset().
m_resultListSplitter
QSplitter* Search::BtSearchResultArea::m_resultListSplitter private
Definition at line 156 of file btsearchresultarea.h.
Referenced by BtSearchResultArea(), loadDialogSettings(), and saveDialogSettings().
m_results
CSwordModuleSearch::Results Search::BtSearchResultArea::m_results private
Definition at line 142 of file btsearchresultarea.h.
Referenced by setSearchResult(), and showAnalysis().
m_searchedText
QString Search::BtSearchResultArea::m_searchedText private
Definition at line 141 of file btsearchresultarea.h.
Referenced by setSearchResult(), showAnalysis(), and updatePreview().
m_selectAllAction
QAction* Search::BtSearchResultArea::m_selectAllAction private
Definition at line 150 of file btsearchresultarea.h.
Referenced by BtSearchResultArea().
The documentation for this class was generated from the following files:
btsearchresultarea.h
btsearchresultarea.cpp