BibleTime: BtFindWidget Class Reference
BtFindWidget Class Reference final
#include <btfindwidget.h>
Classes
struct HighlightState
Signals
void findNext ()
void findPrevious ()
void highlightText (QString const &text, bool caseSensitive)
Public Member Functions
BtFindWidget (QWidget *parent=nullptr)
void showAndSelect ()
Protected Member Functions
void timerEvent (QTimerEvent *const event) final override
Private Member Functions
void highlightImmediately ()
void queueHighlight ()
void retranslateUi ()
Private Attributes
QCheckBox * m_caseCheckBox
HighlightState m_lastHighlightState {{}, false}
QToolButton * m_nextButton
QToolButton * m_previousButton
QLineEdit * m_textEditor
int m_throttleTimerId = 0
Detailed Description
Definition at line 25 of file btfindwidget.h.
Constructor & Destructor Documentation
BtFindWidget()
BtFindWidget::BtFindWidget (QWidget * parent = nullptr)
Definition at line 30 of file btfindwidget.cpp.
References BT_ASSERT, BT_CONNECT, BtFindWidget::HighlightState::caseSensitive, findNext(), findPrevious(), highlightImmediately(), m_caseCheckBox, m_lastHighlightState, m_nextButton, m_previousButton, m_textEditor, queueHighlight(), retranslateUi(), and BtFindWidget::HighlightState::text.
Member Function Documentation
findNext
void BtFindWidget::findNext () signal
Referenced by BtFindWidget(), and BibleTime::createCentralWidget().
findPrevious
void BtFindWidget::findPrevious () signal
Referenced by BtFindWidget(), and BibleTime::createCentralWidget().
highlightImmediately()
void BtFindWidget::highlightImmediately () private
Definition at line 115 of file btfindwidget.cpp.
References highlightText(), m_caseCheckBox, m_lastHighlightState, m_textEditor, and m_throttleTimerId.
Referenced by BtFindWidget(), and timerEvent().
highlightText
void BtFindWidget::highlightText (QString const & text, bool caseSensitive) signal
Referenced by BibleTime::createCentralWidget(), and highlightImmediately().
queueHighlight()
void BtFindWidget::queueHighlight () private
Definition at line 110 of file btfindwidget.cpp.
References m_throttleTimerId.
Referenced by BtFindWidget().
retranslateUi()
void BtFindWidget::retranslateUi () private
Definition at line 126 of file btfindwidget.cpp.
References m_caseCheckBox, m_nextButton, m_previousButton, and m_textEditor.
Referenced by BtFindWidget().
showAndSelect()
void BtFindWidget::showAndSelect ()
Definition at line 94 of file btfindwidget.cpp.
References m_textEditor.
Referenced by BibleTime::openFindWidget().
timerEvent()
void BtFindWidget::timerEvent (QTimerEvent *const event) final override protected
Definition at line 100 of file btfindwidget.cpp.
References BT_ASSERT, highlightImmediately(), and m_throttleTimerId.
Member Data Documentation
m_caseCheckBox
QCheckBox* BtFindWidget::m_caseCheckBox private
Definition at line 77 of file btfindwidget.h.
Referenced by BtFindWidget(), highlightImmediately(), and retranslateUi().
m_lastHighlightState
HighlightState BtFindWidget::m_lastHighlightState {{}, false} private
Definition at line 78 of file btfindwidget.h.
Referenced by BtFindWidget(), and highlightImmediately().
m_nextButton
QToolButton* BtFindWidget::m_nextButton private
Definition at line 75 of file btfindwidget.h.
Referenced by BtFindWidget(), and retranslateUi().
m_previousButton
QToolButton* BtFindWidget::m_previousButton private
Definition at line 76 of file btfindwidget.h.
Referenced by BtFindWidget(), and retranslateUi().
m_textEditor
QLineEdit* BtFindWidget::m_textEditor private
Definition at line 74 of file btfindwidget.h.
Referenced by BtFindWidget(), highlightImmediately(), retranslateUi(), and showAndSelect().
m_throttleTimerId
int BtFindWidget::m_throttleTimerId = 0 private
Definition at line 79 of file btfindwidget.h.
Referenced by highlightImmediately(), queueHighlight(), and timerEvent().
The documentation for this class was generated from the following files:
btfindwidget.h
btfindwidget.cpp