BibleTime: BtFontSizeWidget Class Reference
BtFontSizeWidget Class Reference
#include <btfontsizewidget.h>
Public Slots
void setFontSize (int size)
Signals
void fontSizeChanged (int)
Public Member Functions
BtFontSizeWidget (QWidget *parent=nullptr)
int fontSize () const
Private Attributes
QIntValidator *const m_validator
Detailed Description
Definition at line 24 of file btfontsizewidget.h.
Constructor & Destructor Documentation
BtFontSizeWidget()
BtFontSizeWidget::BtFontSizeWidget (QWidget * parent = nullptr)
Definition at line 23 of file btfontsizewidget.cpp.
References BT_CONNECT, fontSizeChanged(), and m_validator.
Member Function Documentation
fontSize()
int BtFontSizeWidget::fontSize () const
Definition at line 48 of file btfontsizewidget.cpp.
fontSizeChanged
void BtFontSizeWidget::fontSizeChanged (int) signal
Referenced by BtFontSizeWidget(), and BtEditTextPage::setupToolBar().
setFontSize
void BtFontSizeWidget::setFontSize (int size) slot
Definition at line 42 of file btfontsizewidget.cpp.
References m_validator.
Referenced by BtEditTextPage::setupToolBar().
Member Data Documentation
m_validator
QIntValidator* const BtFontSizeWidget::m_validator private
Definition at line 44 of file btfontsizewidget.h.
Referenced by BtFontSizeWidget(), and setFontSize().
The documentation for this class was generated from the following files:
btfontsizewidget.h
btfontsizewidget.cpp