BibleTime: BtIcons Class Reference
BtIcons Class Reference
#include <bticons.h>
Classes
class OverlayedIcon
class RegularIcon
Public Member Functions
BtIcons ()
Static Public Member Functions
static BtIcons & instance ()
Public Attributes
RegularIcon const icon_add
RegularIcon const icon_automatically
RegularIcon const icon_back
RegularIcon const icon_bible
OverlayedIcon const icon_bible_add
OverlayedIcon const icon_bible_locked
OverlayedIcon const icon_bible_remove
RegularIcon const icon_bibletime
RegularIcon const icon_book
OverlayedIcon const icon_book_add
OverlayedIcon const icon_book_locked
RegularIcon const icon_bookmark
RegularIcon const icon_books
RegularIcon const icon_calendar
OverlayedIcon const icon_calendar_add
OverlayedIcon const icon_calendar_locked
RegularIcon const icon_cascade
OverlayedIcon const icon_cascade_auto
RegularIcon const icon_checkbox
RegularIcon const icon_commentary
OverlayedIcon const icon_commentary_add
OverlayedIcon const icon_commentary_locked
RegularIcon const icon_configure
RegularIcon const icon_contents2
RegularIcon const icon_delete
RegularIcon const icon_dictionary
OverlayedIcon const icon_dictionary_add
OverlayedIcon const icon_dictionary_locked
RegularIcon const icon_displayconfig
RegularIcon const icon_document_magnifier
RegularIcon const icon_edit_clear_locationbar
RegularIcon const icon_edit_copy
RegularIcon const icon_exit
RegularIcon const icon_export
RegularIcon const icon_file_save
RegularIcon const icon_fileclose
RegularIcon const icon_find
RegularIcon const icon_flag
RegularIcon const icon_folder
OverlayedIcon const icon_folder_add
RegularIcon const icon_folder_open
RegularIcon const icon_fonts
RegularIcon const icon_forward
RegularIcon const icon_import
RegularIcon const icon_info
RegularIcon const icon_key_bindings
RegularIcon const icon_layer_visible_on
RegularIcon const icon_lexicon
OverlayedIcon const icon_lexicon_add
OverlayedIcon const icon_lexicon_locked
RegularIcon const icon_light_bulb
RegularIcon const icon_lock
RegularIcon const icon_manual
RegularIcon const icon_map
OverlayedIcon const icon_map_add
OverlayedIcon const icon_map_locked
QIcon const icon_null
RegularIcon const icon_plus
RegularIcon const icon_pointing_arrow
RegularIcon const icon_print
RegularIcon const icon_questionable
OverlayedIcon const icon_questionable_add
OverlayedIcon const icon_questionable_locked
RegularIcon const icon_remove
RegularIcon const icon_speaker
RegularIcon const icon_startconfig
RegularIcon const icon_stop
RegularIcon const icon_swordconfig
RegularIcon const icon_sync
RegularIcon const icon_tabbed
RegularIcon const icon_text_bold
RegularIcon const icon_text_center
RegularIcon const icon_text_italic
RegularIcon const icon_text_leftalign
RegularIcon const icon_text_rightalign
RegularIcon const icon_text_under
RegularIcon const icon_tile
OverlayedIcon const icon_tile_auto
RegularIcon const icon_tile_horiz
OverlayedIcon const icon_tile_horiz_auto
RegularIcon const icon_tile_vert
OverlayedIcon const icon_tile_vert_auto
RegularIcon const icon_trash
RegularIcon const icon_unlock
RegularIcon const icon_view_index
RegularIcon const icon_view_mag
RegularIcon const icon_view_profile
RegularIcon const icon_view_tree
RegularIcon const icon_window_fullscreen
Static Private Attributes
static BtIcons * m_instance = nullptr
Detailed Description
Definition at line 20 of file bticons.h.
Constructor & Destructor Documentation
BtIcons()
BtIcons::BtIcons ()
Definition at line 101 of file bticons.cpp.
References BT_ASSERT, and m_instance.
Member Function Documentation
instance()
static BtIcons & BtIcons::instance () inline static
Definition at line 44 of file bticons.h.
References BT_ASSERT, and m_instance.
Referenced by BtAboutDialog::BtAboutDialog(), BtWelcomeDialog::BtWelcomeDialog(), and CBookmarkIndex::paintEvent().
Member Data Documentation
icon_add
RegularIcon const BtIcons::icon_add
Definition at line 58 of file bticons.h.
icon_automatically
RegularIcon const BtIcons::icon_automatically
Definition at line 59 of file bticons.h.
icon_back
RegularIcon const BtIcons::icon_back
Definition at line 60 of file bticons.h.
icon_bible
RegularIcon const BtIcons::icon_bible
Definition at line 61 of file bticons.h.
icon_bible_add
OverlayedIcon const BtIcons::icon_bible_add
Definition at line 126 of file bticons.h.
icon_bible_locked
OverlayedIcon const BtIcons::icon_bible_locked
Definition at line 127 of file bticons.h.
icon_bible_remove
OverlayedIcon const BtIcons::icon_bible_remove
Definition at line 128 of file bticons.h.
icon_bibletime
RegularIcon const BtIcons::icon_bibletime
Definition at line 62 of file bticons.h.
icon_book
RegularIcon const BtIcons::icon_book
Definition at line 63 of file bticons.h.
icon_book_add
OverlayedIcon const BtIcons::icon_book_add
Definition at line 129 of file bticons.h.
icon_book_locked
OverlayedIcon const BtIcons::icon_book_locked
Definition at line 130 of file bticons.h.
icon_bookmark
RegularIcon const BtIcons::icon_bookmark
Definition at line 64 of file bticons.h.
icon_books
RegularIcon const BtIcons::icon_books
Definition at line 65 of file bticons.h.
icon_calendar
RegularIcon const BtIcons::icon_calendar
Definition at line 66 of file bticons.h.
icon_calendar_add
OverlayedIcon const BtIcons::icon_calendar_add
Definition at line 131 of file bticons.h.
icon_calendar_locked
OverlayedIcon const BtIcons::icon_calendar_locked
Definition at line 132 of file bticons.h.
icon_cascade
RegularIcon const BtIcons::icon_cascade
Definition at line 67 of file bticons.h.
icon_cascade_auto
OverlayedIcon const BtIcons::icon_cascade_auto
Definition at line 133 of file bticons.h.
icon_checkbox
RegularIcon const BtIcons::icon_checkbox
Definition at line 68 of file bticons.h.
icon_commentary
RegularIcon const BtIcons::icon_commentary
Definition at line 69 of file bticons.h.
icon_commentary_add
OverlayedIcon const BtIcons::icon_commentary_add
Definition at line 134 of file bticons.h.
icon_commentary_locked
OverlayedIcon const BtIcons::icon_commentary_locked
Definition at line 135 of file bticons.h.
icon_configure
RegularIcon const BtIcons::icon_configure
Definition at line 70 of file bticons.h.
icon_contents2
RegularIcon const BtIcons::icon_contents2
Definition at line 71 of file bticons.h.
icon_delete
RegularIcon const BtIcons::icon_delete
Definition at line 72 of file bticons.h.
icon_dictionary
RegularIcon const BtIcons::icon_dictionary
Definition at line 73 of file bticons.h.
icon_dictionary_add
OverlayedIcon const BtIcons::icon_dictionary_add
Definition at line 136 of file bticons.h.
icon_dictionary_locked
OverlayedIcon const BtIcons::icon_dictionary_locked
Definition at line 137 of file bticons.h.
icon_displayconfig
RegularIcon const BtIcons::icon_displayconfig
Definition at line 74 of file bticons.h.
icon_document_magnifier
RegularIcon const BtIcons::icon_document_magnifier
Definition at line 75 of file bticons.h.
icon_edit_clear_locationbar
RegularIcon const BtIcons::icon_edit_clear_locationbar
Definition at line 76 of file bticons.h.
icon_edit_copy
RegularIcon const BtIcons::icon_edit_copy
Definition at line 77 of file bticons.h.
icon_exit
RegularIcon const BtIcons::icon_exit
Definition at line 78 of file bticons.h.
icon_export
RegularIcon const BtIcons::icon_export
Definition at line 79 of file bticons.h.
icon_file_save
RegularIcon const BtIcons::icon_file_save
Definition at line 80 of file bticons.h.
icon_fileclose
RegularIcon const BtIcons::icon_fileclose
Definition at line 81 of file bticons.h.
icon_find
RegularIcon const BtIcons::icon_find
Definition at line 82 of file bticons.h.
icon_flag
RegularIcon const BtIcons::icon_flag
Definition at line 83 of file bticons.h.
icon_folder
RegularIcon const BtIcons::icon_folder
Definition at line 85 of file bticons.h.
icon_folder_add
OverlayedIcon const BtIcons::icon_folder_add
Definition at line 138 of file bticons.h.
icon_folder_open
RegularIcon const BtIcons::icon_folder_open
Definition at line 84 of file bticons.h.
icon_fonts
RegularIcon const BtIcons::icon_fonts
Definition at line 86 of file bticons.h.
icon_forward
RegularIcon const BtIcons::icon_forward
Definition at line 87 of file bticons.h.
icon_import
RegularIcon const BtIcons::icon_import
Definition at line 88 of file bticons.h.
icon_info
RegularIcon const BtIcons::icon_info
Definition at line 89 of file bticons.h.
icon_key_bindings
RegularIcon const BtIcons::icon_key_bindings
Definition at line 90 of file bticons.h.
icon_layer_visible_on
RegularIcon const BtIcons::icon_layer_visible_on
Definition at line 91 of file bticons.h.
icon_lexicon
RegularIcon const BtIcons::icon_lexicon
Definition at line 92 of file bticons.h.
icon_lexicon_add
OverlayedIcon const BtIcons::icon_lexicon_add
Definition at line 139 of file bticons.h.
icon_lexicon_locked
OverlayedIcon const BtIcons::icon_lexicon_locked
Definition at line 140 of file bticons.h.
icon_light_bulb
RegularIcon const BtIcons::icon_light_bulb
Definition at line 93 of file bticons.h.
icon_lock
RegularIcon const BtIcons::icon_lock
Definition at line 94 of file bticons.h.
icon_manual
RegularIcon const BtIcons::icon_manual
Definition at line 95 of file bticons.h.
icon_map
RegularIcon const BtIcons::icon_map
Definition at line 96 of file bticons.h.
icon_map_add
OverlayedIcon const BtIcons::icon_map_add
Definition at line 141 of file bticons.h.
icon_map_locked
OverlayedIcon const BtIcons::icon_map_locked
Definition at line 142 of file bticons.h.
icon_null
QIcon const BtIcons::icon_null
Definition at line 55 of file bticons.h.
icon_plus
RegularIcon const BtIcons::icon_plus
Definition at line 97 of file bticons.h.
icon_pointing_arrow
RegularIcon const BtIcons::icon_pointing_arrow
Definition at line 98 of file bticons.h.
Referenced by CBookmarkIndex::paintEvent().
icon_print
RegularIcon const BtIcons::icon_print
Definition at line 99 of file bticons.h.
icon_questionable
RegularIcon const BtIcons::icon_questionable
Definition at line 101 of file bticons.h.
icon_questionable_add
OverlayedIcon const BtIcons::icon_questionable_add
Definition at line 143 of file bticons.h.
icon_questionable_locked
OverlayedIcon const BtIcons::icon_questionable_locked
Definition at line 144 of file bticons.h.
icon_remove
RegularIcon const BtIcons::icon_remove
Definition at line 100 of file bticons.h.
icon_speaker
RegularIcon const BtIcons::icon_speaker
Definition at line 102 of file bticons.h.
icon_startconfig
RegularIcon const BtIcons::icon_startconfig
Definition at line 103 of file bticons.h.
icon_stop
RegularIcon const BtIcons::icon_stop
Definition at line 104 of file bticons.h.
icon_swordconfig
RegularIcon const BtIcons::icon_swordconfig
Definition at line 105 of file bticons.h.
icon_sync
RegularIcon const BtIcons::icon_sync
Definition at line 106 of file bticons.h.
icon_tabbed
RegularIcon const BtIcons::icon_tabbed
Definition at line 107 of file bticons.h.
icon_text_bold
RegularIcon const BtIcons::icon_text_bold
Definition at line 108 of file bticons.h.
icon_text_center
RegularIcon const BtIcons::icon_text_center
Definition at line 109 of file bticons.h.
icon_text_italic
RegularIcon const BtIcons::icon_text_italic
Definition at line 110 of file bticons.h.
icon_text_leftalign
RegularIcon const BtIcons::icon_text_leftalign
Definition at line 111 of file bticons.h.
icon_text_rightalign
RegularIcon const BtIcons::icon_text_rightalign
Definition at line 112 of file bticons.h.
icon_text_under
RegularIcon const BtIcons::icon_text_under
Definition at line 113 of file bticons.h.
icon_tile
RegularIcon const BtIcons::icon_tile
Definition at line 114 of file bticons.h.
icon_tile_auto
OverlayedIcon const BtIcons::icon_tile_auto
Definition at line 145 of file bticons.h.
icon_tile_horiz
RegularIcon const BtIcons::icon_tile_horiz
Definition at line 115 of file bticons.h.
icon_tile_horiz_auto
OverlayedIcon const BtIcons::icon_tile_horiz_auto
Definition at line 146 of file bticons.h.
icon_tile_vert
RegularIcon const BtIcons::icon_tile_vert
Definition at line 116 of file bticons.h.
icon_tile_vert_auto
OverlayedIcon const BtIcons::icon_tile_vert_auto
Definition at line 147 of file bticons.h.
icon_trash
RegularIcon const BtIcons::icon_trash
Definition at line 117 of file bticons.h.
icon_unlock
RegularIcon const BtIcons::icon_unlock
Definition at line 118 of file bticons.h.
icon_view_index
RegularIcon const BtIcons::icon_view_index
Definition at line 120 of file bticons.h.
icon_view_mag
RegularIcon const BtIcons::icon_view_mag
Definition at line 121 of file bticons.h.
icon_view_profile
RegularIcon const BtIcons::icon_view_profile
Definition at line 122 of file bticons.h.
icon_view_tree
RegularIcon const BtIcons::icon_view_tree
Definition at line 119 of file bticons.h.
icon_window_fullscreen
RegularIcon const BtIcons::icon_window_fullscreen
Definition at line 123 of file bticons.h.
m_instance
BtIcons * BtIcons::m_instance = nullptr static private
Definition at line 51 of file bticons.h.
Referenced by BtIcons(), and instance().
The documentation for this class was generated from the following files:
bticons.h
bticons.cpp