BibleTime: BtBookshelfFilterModel Class Reference
BtBookshelfFilterModel Class Reference
#include <btbookshelffiltermodel.h>
Public Slots
void setModuleChooserType (std::optional< CSwordModuleInfo::ModuleType > type)
void setNameFilterFixedString (QString const &nameFilter)
void setShowHidden (bool show)
Public Member Functions
BtBookshelfFilterModel (QObject *parent=nullptr)
bool filterAcceptsRow (int row, QModelIndex const &parent) const override
CSwordModuleInfo * module (QModelIndex const &index) const noexcept
std::optional< CSwordModuleInfo::ModuleType > const & moduleChooserType () const noexcept
QString const & nameFilter () const noexcept
bool showHidden () const noexcept
Private Member Functions
template<typename Field , typename Value >
void changeFilter (Field &field, Value &&value)
Private Attributes
std::optional< CSwordModuleInfo::ModuleType > m_moduleChooserType
QString m_nameFilter
bool m_showHidden
Detailed Description
Definition at line 24 of file btbookshelffiltermodel.h.
Constructor & Destructor Documentation
BtBookshelfFilterModel()
BtBookshelfFilterModel::BtBookshelfFilterModel (QObject * parent = nullptr)
Definition at line 20 of file btbookshelffiltermodel.cpp.
Member Function Documentation
changeFilter()
template<typename Field , typename Value > void BtBookshelfFilterModel::changeFilter (Field & field, Value && value) private
Definition at line 33 of file btbookshelffiltermodel.cpp.
Referenced by setModuleChooserType(), setNameFilterFixedString(), and setShowHidden().
filterAcceptsRow()
bool BtBookshelfFilterModel::filterAcceptsRow (int row, QModelIndex const & parent) const override
Definition at line 57 of file btbookshelffiltermodel.cpp.
References CSwordModuleInfo::Bible, BT_ASSERT, CSwordModuleInfo::Commentary, filterAcceptsRow(), m_moduleChooserType, m_nameFilter, m_showHidden, module(), BtBookshelfModel::ModuleHiddenRole, BtBookshelfModel::ModuleNameRole, and BtBookshelfModel::ModulePointerRole.
Referenced by filterAcceptsRow().
module()
CSwordModuleInfo * BtBookshelfFilterModel::module (QModelIndex const & index) const noexcept
Definition at line 26 of file btbookshelffiltermodel.cpp.
References BtBookshelfModel::ModulePointerRole.
Referenced by BtModuleChooserMenu::BtModuleChooserMenu(), and filterAcceptsRow().
moduleChooserType()
std::optional< CSwordModuleInfo::ModuleType > const & BtBookshelfFilterModel::moduleChooserType () const inline noexcept
Definition at line 39 of file btbookshelffiltermodel.h.
References m_moduleChooserType.
Referenced by BtModuleChooserMenu::buttonIcon(), and BtModuleChooserMenu::newAction().
nameFilter()
QString const & BtBookshelfFilterModel::nameFilter () const inline noexcept
Definition at line 34 of file btbookshelffiltermodel.h.
References m_nameFilter.
setModuleChooserType
void BtBookshelfFilterModel::setModuleChooserType (std::optional< CSwordModuleInfo::ModuleType > type) slot
Definition at line 53 of file btbookshelffiltermodel.cpp.
References changeFilter(), and m_moduleChooserType.
Referenced by BtModuleChooserMenu::BtModuleChooserMenu().
setNameFilterFixedString
void BtBookshelfFilterModel::setNameFilterFixedString (QString const & nameFilter) slot
Definition at line 47 of file btbookshelffiltermodel.cpp.
References changeFilter(), and m_nameFilter.
Referenced by BtBookshelfWidget::BtBookshelfWidget(), and BtBookshelfWorksPage::BtBookshelfWorksPage().
setShowHidden
void BtBookshelfFilterModel::setShowHidden (bool show) slot
Definition at line 50 of file btbookshelffiltermodel.cpp.
References changeFilter(), and m_showHidden.
Referenced by BtBookshelfWidget::initActions().
showHidden()
bool BtBookshelfFilterModel::showHidden () const inline noexcept
Definition at line 36 of file btbookshelffiltermodel.h.
References m_showHidden.
Member Data Documentation
m_moduleChooserType
std::optional<CSwordModuleInfo::ModuleType> BtBookshelfFilterModel::m_moduleChooserType private
Definition at line 58 of file btbookshelffiltermodel.h.
Referenced by filterAcceptsRow(), moduleChooserType(), and setModuleChooserType().
m_nameFilter
QString BtBookshelfFilterModel::m_nameFilter private
Definition at line 56 of file btbookshelffiltermodel.h.
Referenced by filterAcceptsRow(), nameFilter(), and setNameFilterFixedString().
m_showHidden
bool BtBookshelfFilterModel::m_showHidden private
Definition at line 57 of file btbookshelffiltermodel.h.
Referenced by filterAcceptsRow(), setShowHidden(), and showHidden().
The documentation for this class was generated from the following files:
btbookshelffiltermodel.h
btbookshelffiltermodel.cpp