BibleTime: Rendering Namespace Reference
Rendering Namespace Reference
Classes
class CBookDisplay
CEntryDisplay implementation for GenBook modules,.
class CChapterDisplay
CEntryDisplay implementation for whole chapters.
class CDisplayRendering
Rendering for the html display widget.
class CEntryDisplay
class CPlainTextExportRendering
Text rendering as plain text.
class CrossRefRendering
class CTextRendering
Text rendering based on trees.
Typedefs
using InfoData = QPair< InfoType, QString >
using ListInfoData = QList< InfoData >
Enumerations
enum InfoType {
Abbreviation, CrossReference, Footnote, Lemma,
Morph, Text, Reference
}
Functions
QString decodeAbbreviation (QString const &data)
QString decodeCrossReference (QString const &data, BtConstModuleList const &modules)
QString decodeFootnote (QString const &data)
QString decodeMorph (QString const &data)
QString decodeStrongs (QString const &data)
QString decodeSwordReference (QString const &data)
ListInfoData detectInfo (QString const &data)
QString formatInfo (const ListInfoData &list, BtConstModuleList const &modules)
QString formatInfo (QString const &info, QString const &lang)
CSwordModuleInfo * getFirstAvalibleStrongsModule (bool wantHebrew)
CSwordModuleInfo * getStrongsModule (bool wantHebrew)
Typedef Documentation
InfoData
using Rendering::InfoData = typedef QPair<InfoType, QString>
Definition at line 44 of file btinforendering.h.
ListInfoData
using Rendering::ListInfoData = typedef QList<InfoData>
Definition at line 45 of file btinforendering.h.
Enumeration Type Documentation
InfoType
enum Rendering::InfoType
Enumerator
Abbreviation
CrossReference
Footnote
Lemma
Morph
Text
Reference
Definition at line 34 of file btinforendering.h.
Function Documentation
decodeAbbreviation()
QString Rendering::decodeAbbreviation (QString const & data)
Definition at line 167 of file btinforendering.cpp.
Referenced by formatInfo().
decodeCrossReference()
QString Rendering::decodeCrossReference (QString const & data, BtConstModuleList const & modules = BtConstModuleList())
Parameters
modules render references to each Bible module in the list, if empty use standard Bible. If module was provided in reference (KJV:John.1.1) this parameter has no effect.
Definition at line 175 of file btinforendering.cpp.
Referenced by formatInfo().
decodeFootnote()
QString Rendering::decodeFootnote (QString const & data)
Definition at line 262 of file btinforendering.cpp.
Referenced by formatInfo().
decodeMorph()
QString Rendering::decodeMorph (QString const & data)
Todo:
we can't tell here if it's a greek or hebrew moprh code, that's a problem we have to solve
Todo:
: what if the module doesn't exist?
Definition at line 354 of file btinforendering.cpp.
References CSwordBackend::findModuleByName(), and CSwordBackend::instance().
Referenced by formatInfo().
decodeStrongs()
QString Rendering::decodeStrongs (QString const & data)
Definition at line 326 of file btinforendering.cpp.
Referenced by formatInfo().
decodeSwordReference()
QString Rendering::decodeSwordReference (QString const & data)
Definition at line 431 of file btinforendering.cpp.
Referenced by formatInfo().
detectInfo()
ListInfoData Rendering::detectInfo (QString const & data)
Parse string for attributes
Definition at line 63 of file btinforendering.cpp.
Referenced by BtQmlInterface::BtQmlInterface().
formatInfo() [1/2]
QString Rendering::formatInfo (const ListInfoData & info, BtConstModuleList const & modules = BtConstModuleList())
Process list of InfoData and format all data into string
Todo:
Why is this here?
Definition at line 91 of file btinforendering.cpp.
References Abbreviation, BT_ASSERT, CrossReference, decodeAbbreviation(), decodeCrossReference(), decodeFootnote(), decodeMorph(), decodeStrongs(), decodeSwordReference(), Footnote, Lemma, Morph, Reference, and Text.
Referenced by InfoDisplay::CInfoDisplay::setInfo().
formatInfo() [2/2]
QString Rendering::formatInfo (QString const & info, QString const & lang)
Definition at line 148 of file btinforendering.cpp.
getFirstAvalibleStrongsModule()
CSwordModuleInfo* Rendering::getFirstAvalibleStrongsModule (bool wantHebrew)
Definition at line 305 of file btinforendering.cpp.
getStrongsModule()
CSwordModuleInfo* Rendering::getStrongsModule (bool wantHebrew)
Definition at line 318 of file btinforendering.cpp.
References CSwordKey::createInstance().