BibleTime: util::directory::anonymous_namespace{directory.cpp} Namespace Reference
util::directory::anonymous_namespace{directory.cpp} Namespace Reference
Functions
QString getDocFile (QString docName)
Variables
QString const BIBLETIME = QStringLiteral(".bibletime")
std::optional< QDir > cachedDisplayTemplatesDir
std::optional< QDir > cachedLocaleDir
std::optional< QDir > cachedPicsDir
std::optional< QDir > cachedPrefix
std::optional< QDir > cachedUserBaseDir
std::optional< QDir > cachedUserCacheDir
std::optional< QDir > cachedUserDisplayTemplatesDir
std::optional< QDir > cachedUserHomeDir
std::optional< QDir > cachedUserHomeSwordDir
std::optional< QDir > cachedUserIndexDir
QString const SWORD_DIR = QStringLiteral(".sword")
Function Documentation
getDocFile()
QString util::directory::anonymous_namespace{directory.cpp}::getDocFile (QString docName)
Definition at line 256 of file directory.cpp.
References cachedPrefix, getDocFile(), and r().
Referenced by getDocFile().
Variable Documentation
BIBLETIME
QString const util::directory::anonymous_namespace{directory.cpp}::BIBLETIME = QStringLiteral(".bibletime")
Definition at line 56 of file directory.cpp.
cachedDisplayTemplatesDir
std::optional<QDir> util::directory::anonymous_namespace{directory.cpp}::cachedDisplayTemplatesDir
Definition at line 39 of file directory.cpp.
cachedLocaleDir
std::optional<QDir> util::directory::anonymous_namespace{directory.cpp}::cachedLocaleDir
Definition at line 38 of file directory.cpp.
cachedPicsDir
std::optional<QDir> util::directory::anonymous_namespace{directory.cpp}::cachedPicsDir
Definition at line 37 of file directory.cpp.
cachedPrefix
std::optional<QDir> util::directory::anonymous_namespace{directory.cpp}::cachedPrefix
Definition at line 36 of file directory.cpp.
Referenced by getDocFile().
cachedUserBaseDir
std::optional<QDir> util::directory::anonymous_namespace{directory.cpp}::cachedUserBaseDir
Definition at line 41 of file directory.cpp.
cachedUserCacheDir
std::optional<QDir> util::directory::anonymous_namespace{directory.cpp}::cachedUserCacheDir
Definition at line 44 of file directory.cpp.
cachedUserDisplayTemplatesDir
std::optional<QDir> util::directory::anonymous_namespace{directory.cpp}::cachedUserDisplayTemplatesDir
Definition at line 40 of file directory.cpp.
cachedUserHomeDir
std::optional<QDir> util::directory::anonymous_namespace{directory.cpp}::cachedUserHomeDir
Definition at line 42 of file directory.cpp.
cachedUserHomeSwordDir
std::optional<QDir> util::directory::anonymous_namespace{directory.cpp}::cachedUserHomeSwordDir
Definition at line 43 of file directory.cpp.
cachedUserIndexDir
std::optional<QDir> util::directory::anonymous_namespace{directory.cpp}::cachedUserIndexDir
Definition at line 45 of file directory.cpp.
SWORD_DIR
QString const util::directory::anonymous_namespace{directory.cpp}::SWORD_DIR = QStringLiteral(".sword")
Definition at line 57 of file directory.cpp.