BibleTime: BtColorWidget Class Reference
BtColorWidget Class Reference
#include <btcolorwidget.h>
Public Slots
void setColor (QColor const &color)
Signals
void changed (QColor const &color)
Public Member Functions
BtColorWidget (QWidget *parent=nullptr)
QSize sizeHint () const override
Protected Member Functions
void mouseReleaseEvent (QMouseEvent *event) override
Detailed Description
Definition at line 26 of file btcolorwidget.h.
Constructor & Destructor Documentation
BtColorWidget()
BtColorWidget::BtColorWidget (QWidget * parent = nullptr)
Definition at line 22 of file btcolorwidget.cpp.
Member Function Documentation
changed
void BtColorWidget::changed (QColor const & color) signal
Referenced by mouseReleaseEvent(), and BtEditTextPage::setupToolBar().
mouseReleaseEvent()
void BtColorWidget::mouseReleaseEvent (QMouseEvent * event) override protected
Definition at line 41 of file btcolorwidget.cpp.
References changed(), and setColor().
setColor
void BtColorWidget::setColor (QColor const & color) slot
Definition at line 34 of file btcolorwidget.cpp.
Referenced by mouseReleaseEvent(), and BtEditTextPage::setupToolBar().
sizeHint()
QSize BtColorWidget::sizeHint () const override
Definition at line 32 of file btcolorwidget.cpp.
The documentation for this class was generated from the following files:
btcolorwidget.h
btcolorwidget.cpp