BibleTime: Search::CRangeChooserDialog Class Reference
Search::CRangeChooserDialog Class Reference
#include <crangechooserdialog.h>
Classes
class RangeItem
Public Member Functions
void accept () override
CRangeChooserDialog (const QStringList &rangeScopeModule, QWidget *parentDialog=nullptr)
Private Slots
void nameEditTextChanged (const QString &newText)
Private Member Functions
void initConnections ()
void initView ()
void resetEditControls ()
void retranslateUi ()
void saveCurrentToRange (RangeItem *i)
Private Attributes
QDialogButtonBox * m_buttonBox
QPushButton * m_deleteRangeButton
QLineEdit * m_nameEdit
QLabel * m_nameEditLabel
QPushButton * m_newRangeButton
QTextEdit * m_rangeEdit
QLabel * m_rangeEditLabel
QListWidget * m_rangeList
QLabel * m_rangeListLabel
QListWidget * m_resultList
QLabel * m_resultListLabel
QStringList m_scopeModules
Detailed Description
Todo:
Redesign this dialog and rename to have a Bt prefix.
Definition at line 33 of file crangechooserdialog.h.
Constructor & Destructor Documentation
CRangeChooserDialog()
Search::CRangeChooserDialog::CRangeChooserDialog (const QStringList & rangeScopeModule, QWidget * parentDialog = nullptr)
Definition at line 57 of file crangechooserdialog.cpp.
References btConfig(), BtConfig::getSearchScopesForCurrentLocale(), initConnections(), initView(), m_rangeList, resetEditControls(), and retranslateUi().
Member Function Documentation
accept()
void Search::CRangeChooserDialog::accept () override
Definition at line 273 of file crangechooserdialog.cpp.
References BT_ASSERT, btConfig(), Search::CRangeChooserDialog::RangeItem::caption(), m_rangeList, m_scopeModules, Search::CRangeChooserDialog::RangeItem::range(), saveCurrentToRange(), and BtConfig::setSearchScopesWithCurrentLocale().
Referenced by initConnections().
initConnections()
void Search::CRangeChooserDialog::initConnections () private
Initializes connections.
Definition at line 134 of file crangechooserdialog.cpp.
References accept(), BT_ASSERT, BT_CONNECT, btConfig(), BtConfig::deleteSearchScopesWithCurrentLocale(), CSwordBackend::instance(), m_buttonBox, m_deleteRangeButton, m_nameEdit, m_newRangeButton, m_rangeEdit, m_rangeList, m_resultList, m_scopeModules, nameEditTextChanged(), resetEditControls(), and saveCurrentToRange().
Referenced by CRangeChooserDialog().
initView()
void Search::CRangeChooserDialog::initView () private
Initializes widgets.
Definition at line 73 of file crangechooserdialog.cpp.
References m_buttonBox, m_deleteRangeButton, m_nameEdit, m_nameEditLabel, m_newRangeButton, m_rangeEdit, m_rangeEditLabel, m_rangeList, m_rangeListLabel, m_resultList, m_resultListLabel, and message::prepareDialogBox().
Referenced by CRangeChooserDialog().
nameEditTextChanged
void Search::CRangeChooserDialog::nameEditTextChanged (const QString & newText) private slot
Called when m_nameEdit changes.
Definition at line 294 of file crangechooserdialog.cpp.
References m_buttonBox, and m_rangeList.
Referenced by initConnections(), and resetEditControls().
resetEditControls()
void Search::CRangeChooserDialog::resetEditControls () private
Resets the editing controls based on whether a range is selected in the range list.
Definition at line 255 of file crangechooserdialog.cpp.
References BT_ASSERT, Search::CRangeChooserDialog::RangeItem::caption(), m_deleteRangeButton, m_nameEdit, m_rangeEdit, m_rangeList, m_resultList, nameEditTextChanged(), and Search::CRangeChooserDialog::RangeItem::range().
Referenced by CRangeChooserDialog(), and initConnections().
retranslateUi()
void Search::CRangeChooserDialog::retranslateUi () private
Definition at line 219 of file crangechooserdialog.cpp.
References m_deleteRangeButton, m_nameEdit, m_nameEditLabel, m_newRangeButton, m_rangeEdit, m_rangeEditLabel, m_rangeList, m_rangeListLabel, m_resultList, and m_resultListLabel.
Referenced by CRangeChooserDialog().
saveCurrentToRange()
void Search::CRangeChooserDialog::saveCurrentToRange (RangeItem * i) private
Stores the values from the current edit view to the given RangeItem.
Parameters
[out] i The RangeItem object to store the values to.
Definition at line 248 of file crangechooserdialog.cpp.
References m_nameEdit, m_rangeEdit, Search::CRangeChooserDialog::RangeItem::setCaption(), and Search::CRangeChooserDialog::RangeItem::setRange().
Referenced by accept(), and initConnections().
Member Data Documentation
m_buttonBox
QDialogButtonBox* Search::CRangeChooserDialog::m_buttonBox private
Definition at line 116 of file crangechooserdialog.h.
Referenced by initConnections(), initView(), and nameEditTextChanged().
m_deleteRangeButton
QPushButton* Search::CRangeChooserDialog::m_deleteRangeButton private
Definition at line 114 of file crangechooserdialog.h.
Referenced by initConnections(), initView(), resetEditControls(), and retranslateUi().
m_nameEdit
QLineEdit* Search::CRangeChooserDialog::m_nameEdit private
Definition at line 105 of file crangechooserdialog.h.
Referenced by initConnections(), initView(), resetEditControls(), retranslateUi(), and saveCurrentToRange().
m_nameEditLabel
QLabel* Search::CRangeChooserDialog::m_nameEditLabel private
Definition at line 104 of file crangechooserdialog.h.
Referenced by initView(), and retranslateUi().
m_newRangeButton
QPushButton* Search::CRangeChooserDialog::m_newRangeButton private
Definition at line 113 of file crangechooserdialog.h.
Referenced by initConnections(), initView(), and retranslateUi().
m_rangeEdit
QTextEdit* Search::CRangeChooserDialog::m_rangeEdit private
Definition at line 108 of file crangechooserdialog.h.
Referenced by initConnections(), initView(), resetEditControls(), retranslateUi(), and saveCurrentToRange().
m_rangeEditLabel
QLabel* Search::CRangeChooserDialog::m_rangeEditLabel private
Definition at line 107 of file crangechooserdialog.h.
Referenced by initView(), and retranslateUi().
m_rangeList
QListWidget* Search::CRangeChooserDialog::m_rangeList private
Definition at line 102 of file crangechooserdialog.h.
Referenced by accept(), CRangeChooserDialog(), initConnections(), initView(), nameEditTextChanged(), resetEditControls(), and retranslateUi().
m_rangeListLabel
QLabel* Search::CRangeChooserDialog::m_rangeListLabel private
Definition at line 101 of file crangechooserdialog.h.
Referenced by initView(), and retranslateUi().
m_resultList
QListWidget* Search::CRangeChooserDialog::m_resultList private
Definition at line 111 of file crangechooserdialog.h.
Referenced by initConnections(), initView(), resetEditControls(), and retranslateUi().
m_resultListLabel
QLabel* Search::CRangeChooserDialog::m_resultListLabel private
Definition at line 110 of file crangechooserdialog.h.
Referenced by initView(), and retranslateUi().
m_scopeModules
QStringList Search::CRangeChooserDialog::m_scopeModules private
Definition at line 118 of file crangechooserdialog.h.
Referenced by accept(), and initConnections().
The documentation for this class was generated from the following files:
crangechooserdialog.h
crangechooserdialog.cpp