BibleTime: btconfig.h File Reference
btconfig.h File Reference
#include "btconfigcore.h"
#include <QCoreApplication>
#include <QFont>
#include <QHash>
#include <QList>
#include <QMap>
#include <QMetaType>
#include <QPair>
#include <QString>
#include <QStringList>
#include "../../util/btassert.h"
#include "../btglobal.h"
Classes
class BtConfig
Namespaces
namespace sword
Functions
BtConfig & btConfig ()
This is a shortchand for BtConfig::getInstance().
Function Documentation
btConfig()
BtConfig & btConfig () inline
This is a shortchand for BtConfig::getInstance().
Returns
BtConfig singleton instance.
Definition at line 305 of file btconfig.h.
References BtConfig::getInstance().
Referenced by BtBookshelfWizard::accept(), BtEditTextWizard::accept(), Search::CRangeChooserDialog::accept(), BibleTime::ActionCollection::ActionCollection(), CDisplayTemplateMgr::activeTemplateName(), CBookKeyChooser::adjustFont(), CBookTreeChooser::adjustFont(), BtIndexDialog::autoDeleteOrphanedIndicesChanged(), BibleTime::BibleTime(), CDisplaySettingsPage::bookNameAbbreviationsTryVector(), BtBookshelfDockWidget::BtBookshelfDockWidget(), BtBookshelfWizard::BtBookshelfWizard(), BtBookshelfWorksPage::BtBookshelfWorksPage(), BtEditTextPage::BtEditTextPage(), BtEditTextWizard::BtEditTextWizard(), BtFontSettingsPage::BtFontSettingsPage(), BtIndexDialog::BtIndexDialog(), BtSearchModuleChooserDialog::BtSearchModuleChooserDialog(), BtTextFiltersTab::BtTextFiltersTab(), BtTipDialog::BtTipDialog(), CSwordModuleInfo::buildIndex(), CBookmarkIndex::CBookmarkIndex(), CConfigurationDialog::CConfigurationDialog(), CDisplaySettingsPage::CDisplaySettingsPage(), CDisplayWindow::CDisplayWindow(), CSwordModuleInfo::config(), Search::CRangeChooserDialog::CRangeChooserDialog(), BibleTime::createMenuAndToolBar(), Search::CSearchDialog::CSearchDialog(), CSwordBackend::CSwordBackend(), CSwordModuleInfo::CSwordModuleInfo(), ReferenceManager::decodeHyperlink(), anonymous_namespace{btinforendering.cpp}::decodeMorph(), CSwordBackend::deleteOrphanedIndices(), BibleTime::deleteProfile(), CDisplayTemplateMgr::fillTemplate(), BtQmlInterface::getFontsFromSettings(), anonymous_namespace{btinforendering.cpp}::getStrongsModule(), Search::BtSearchOptionsArea::getUniqueWorksList(), CDisplayWindow::init(), BibleTime::initActions(), Search::CRangeChooserDialog::initConnections(), BtEditTextPage::initHtmlFont(), BtBookshelfLanguagesPage::initializePage(), BtBookshelfSourcesPage::initializePage(), BibleTimeApp::initLightDarkPalette(), CSwordBackend::initModules(), BtLocationEdit::keyPressEvent(), BtBookshelfWidget::loadBookshelfState(), Search::BtSearchResultArea::loadDialogSettings(), BibleTime::loadProfile(), BibleTime::loadProfile(), main(), BibleTime::processCommandline(), Search::BtSearchOptionsArea::readSettings(), BtActionCollection::readShortcuts(), BibleTime::refreshProfileMenus(), Search::BtSearchOptionsArea::refreshRanges(), BibleTime::reloadProfile(), anonymous_namespace{osistohtml.cpp}::renderReference(), Filters::TeiToHtml::renderReference(), Search::BtSearchOptionsArea::reset(), CDisplaySettingsPage::resetLanguage(), BtTextFiltersTab::save(), BtFontSettingsPage::save(), CDisplaySettingsPage::save(), BtBookshelfWidget::saveBookshelfState(), Search::BtSearchResultArea::saveDialogSettings(), BibleTime::saveProfile(), Search::BtSearchOptionsArea::saveSettings(), BibleTime::saveToNewProfile(), CSwordModuleSearch::search(), Search::BtSearchOptionsArea::searchScope(), CDisplayWindow::setBibleReference(), InfoDisplay::CInfoDisplay::setBrowserFont(), Search::BtSearchResultArea::setBrowserFont(), CSwordModuleInfo::setHidden(), Search::BtSearchOptionsArea::setModules(), BibleTime::showOrHideToolBars(), BtBookshelfWorksPage::slotGroupingOrderChanged(), BtBookshelfWorksPage::slotInitPathCombo(), BtBookshelfWorksPage::slotPathChanged(), BibleTime::slotSearchDefaultBible(), BibleTime::slotSettingsOptions(), BibleTime::slotToggleMainToolbar(), BibleTime::slotToggleNavigatorToolbar(), BibleTime::slotToggleTextWindowHeader(), BibleTime::slotToggleToolBarsInEachWindow(), BibleTime::slotToggleToolsToolbar(), BibleTime::slotToggleWorksToolbar(), BibleTime::slotUpdateWindowArrangementActions(), anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::toolTip(), CSwordModuleInfo::unlock(), BtActionCollection::writeShortcuts(), BibleTimeApp::~BibleTimeApp(), CConfigurationDialog::~CConfigurationDialog(), and Search::CSearchDialog::~CSearchDialog().