BibleTime: CSwordBibleModuleInfo Class Reference
CSwordBibleModuleInfo Class Reference
Implementation for Sword Bibles.
#include <cswordbiblemoduleinfo.h>
Public Member Functions
unsigned int bookNumber (const QString &book) const
const QStringList & books () const
unsigned int chapterCount (const QString &book) const
unsigned int chapterCount (const unsigned int book) const
CSwordBibleModuleInfo (sword::SWModule &module, CSwordBackend &backend, ModuleType type=Bible)
bool hasNewTestament () const
bool hasOldTestament () const
const CSwordVerseKey & lowerBound () const
const CSwordVerseKey & upperBound () const
unsigned int verseCount (const QString &book, const unsigned int chapter) const
unsigned int verseCount (const unsigned int book, const unsigned int chapter) const
~CSwordBibleModuleInfo () noexcept
Public Member Functions inherited from CSwordModuleInfo
QString aboutText () const
void buildIndex ()
CSwordModuleInfo::Category category () const
QString config (const CSwordModuleInfo::ConfigEntry entry) const
CSwordModuleInfo (CSwordModuleInfo &&)=delete
CSwordModuleInfo (CSwordModuleInfo const &)=delete
void deleteEntry (CSwordKey *const key)
void deleteIndex ()
Rendering::CEntryDisplay * getDisplay () const noexcept
QString getModuleBaseIndexLocation () const
QString getModuleStandardIndexLocation () const
QString getUnlockInfo ()
std::shared_ptr< Language const > glossaryTargetlanguage () const
bool has (const CSwordModuleInfo::Feature) const
bool has (const CSwordModuleInfo::FilterTypes) const
bool hasIndex () const
bool hasVersion () const
size_t indexSize () const
bool isEncrypted () const
bool isHidden () const
bool isLocked () const
bool isUnicode () const noexcept
virtual bool isWritable () const
std::shared_ptr< Language const > language () const
sword::SWVersion minimumSwordVersion () const
sword::SWModule & module () const
QIcon moduleIcon () const
const QString & name () const
CSwordModuleInfo & operator= (CSwordModuleInfo &&)=delete
CSwordModuleInfo & operator= (CSwordModuleInfo const &)=delete
CSwordModuleSearch::ModuleResultList searchIndexed (QString const &searchedText, sword::ListKey const &scope) const
void setDisplay (Rendering::CEntryDisplay *display=nullptr) noexcept
bool setHidden (bool hide)
virtual bool snap () const
CSwordModuleInfo::TextDirection textDirection () const
const char * textDirectionAsHtml () const
ModuleType type () const
bool unlock (const QString &unlockKey)
bool unlockKeyIsValid () const
void write (CSwordKey *key, const QString &newText)
Private Member Functions
void initBounds () const
Private Attributes
std::optional< QStringList > m_bookList
bool m_boundsInitialized
QString m_cachedLocale
bool m_hasNT
bool m_hasOT
CSwordVerseKey m_lowerBound
CSwordVerseKey m_upperBound
Additional Inherited Members
Public Types inherited from CSwordModuleInfo
enum Category {
UnknownCategory = 0x0, NoCategory = 0x0, Bibles = 0x01, Commentaries = 0x02,
Books = 0x04, Lexicons = 0x08, Glossary = 0x10, DailyDevotional = 0x20,
Images = 0x40, Cult = 0x80, AllCategories = 0xff
}
enum ConfigEntry {
AboutInformation, AbsoluteDataPath, CipherKey, DataPath,
Description, ModuleVersion, MinimumSwordVersion, TextDir,
DisplayLevel, GlossaryFrom, GlossaryTo, DistributionLicense,
DistributionSource, DistributionNotes, TextSource, CopyrightNotes,
CopyrightHolder, CopyrightDate, CopyrightContactName, CopyrightContactAddress,
CopyrightContactEmail, Markup
}
enum Feature {
GreekDef, HebrewDef, GreekParse, HebrewParse,
featureMin = GreekDef, featureMax = HebrewParse
}
enum FilterTypes {
footnotes, strongNumbers, headings, morphTags,
lemmas, hebrewPoints, hebrewCantillation, greekAccents,
scriptureReferences, redLetterWords, textualVariants, morphSegmentation,
filterTypesMIN = footnotes, filterTypesMAX = morphSegmentation
}
enum ModuleType {
Unknown, Bible, Commentary, Lexicon,
GenericBook
}
enum TextDirection { LeftToRight, RightToLeft }
enum UnlockErrorCode { noError, wrongUnlockKey, notLocked, noPermission }
Public Slots inherited from CSwordModuleInfo
void cancelIndexing (std::memory_order const memoryOrder=std::memory_order_relaxed) noexcept
Signals inherited from CSwordModuleInfo
void hasIndexChanged (bool hasIndex)
void hiddenChanged (bool hidden)
void indexingFinished ()
void indexingProgress (int)
void unlockedChanged (bool unlocked)
Static Public Member Functions inherited from CSwordModuleInfo
static const QIcon & categoryIcon (CSwordModuleInfo::Category category)
static QString categoryName (const CSwordModuleInfo::Category &category)
static void deleteIndexForModule (const QString &name)
static QString englishCategoryName (const CSwordModuleInfo::Category &category)
static QString getGlobalBaseIndexLocation ()
static const QIcon & moduleIcon (CSwordModuleInfo const &module)
Protected Member Functions inherited from CSwordModuleInfo
CSwordBackend & backend () const
CSwordModuleInfo (sword::SWModule &module, CSwordBackend &backend, ModuleType type)
QString getFormattedConfigEntry (const QString &name) const
QString getSimpleConfigEntry (const QString &name) const
bool hasImportantFilterOption () const
void setImportantFilterOptions (bool enable)
Detailed Description
Implementation for Sword Bibles.
This is the CModuleInfo imlementation for Bible modules managed by Sword.
Definition at line 27 of file cswordbiblemoduleinfo.h.
Constructor & Destructor Documentation
CSwordBibleModuleInfo()
CSwordBibleModuleInfo::CSwordBibleModuleInfo (sword::SWModule & module, CSwordBackend & backend, ModuleType type = Bible)
Definition at line 24 of file cswordbiblemoduleinfo.cpp.
~CSwordBibleModuleInfo()
CSwordBibleModuleInfo::~CSwordBibleModuleInfo () default noexcept
Member Function Documentation
bookNumber()
unsigned int CSwordBibleModuleInfo::bookNumber (const QString & book) const
Returns
the index of the book given by its name.
Return values
0 if a book with the given name was not found.
Definition at line 149 of file cswordbiblemoduleinfo.cpp.
References CSwordModuleInfo::module().
Referenced by chapterCount(), and verseCount().
books()
const QStringList & CSwordBibleModuleInfo::books () const
Returns
a QStringList containing the books available in this module.
Returns the books available in this module
Definition at line 62 of file cswordbiblemoduleinfo.cpp.
References CSwordModuleInfo::backend(), CSwordBackend::booknameLanguage(), initBounds(), m_bookList, m_boundsInitialized, m_cachedLocale, m_hasNT, m_hasOT, and CSwordModuleInfo::module().
Referenced by BtBibleKeyWidget::populateBookMenu().
chapterCount() [1/2]
unsigned int CSwordBibleModuleInfo::chapterCount (const QString & book) const
Returns
the number of available chapters in the given book.
Definition at line 119 of file cswordbiblemoduleinfo.cpp.
References bookNumber(), and chapterCount().
chapterCount() [2/2]
unsigned int CSwordBibleModuleInfo::chapterCount (const unsigned int book) const
Returns
the number of available chapters in the given book.
Definition at line 104 of file cswordbiblemoduleinfo.cpp.
References CSwordModuleInfo::module().
Referenced by chapterCount(), and BtBibleKeyWidget::populateChapterMenu().
hasNewTestament()
bool CSwordBibleModuleInfo::hasNewTestament () const inline
Returns
whether this module has the New Testament texts.
Definition at line 96 of file cswordbiblemoduleinfo.h.
hasOldTestament()
bool CSwordBibleModuleInfo::hasOldTestament () const inline
Returns
whether this module has the Old Testament texts.
Definition at line 87 of file cswordbiblemoduleinfo.h.
Referenced by CSwordVerseKey::bookName().
initBounds()
void CSwordBibleModuleInfo::initBounds () const private
Todo:
The fields calculated by this method could be cached to disk.
Definition at line 35 of file cswordbiblemoduleinfo.cpp.
References BT_ASSERT.
Referenced by books().
lowerBound()
const CSwordVerseKey& CSwordBibleModuleInfo::lowerBound () const inline
Returns
the key which represents the lower bound of this module.
Definition at line 105 of file cswordbiblemoduleinfo.h.
Referenced by CSwordModuleInfo::buildIndex(), and CSwordVerseKey::setModule().
upperBound()
const CSwordVerseKey& CSwordBibleModuleInfo::upperBound () const inline
Returns
the key which represents the upper bound of this module.
Definition at line 114 of file cswordbiblemoduleinfo.h.
Referenced by CSwordModuleInfo::buildIndex(), and CSwordVerseKey::setModule().
verseCount() [1/2]
unsigned int CSwordBibleModuleInfo::verseCount (const QString & book, const unsigned int chapter) const
Returns
the number of avalable verses for the given chapter and book.
Parameters
book The name of the book we use
chapter The number of the chapter we use
Definition at line 143 of file cswordbiblemoduleinfo.cpp.
References bookNumber(), and verseCount().
verseCount() [2/2]
unsigned int CSwordBibleModuleInfo::verseCount (const unsigned int book, const unsigned int chapter) const
Returns
the number of avalable verses for the given chapter and book.
Parameters
book The number book we should use
chapter The chapter we should use
Returns the number of verses for the given chapter.
Definition at line 125 of file cswordbiblemoduleinfo.cpp.
References CSwordModuleInfo::module().
Referenced by CBibleReadWindow::copyDisplayedText(), BtBibleKeyWidget::populateVerseMenu(), CBibleReadWindow::saveChapter(), and verseCount().
Member Data Documentation
m_bookList
std::optional<QStringList> CSwordBibleModuleInfo::m_bookList mutable private
Definition at line 132 of file cswordbiblemoduleinfo.h.
Referenced by books().
m_boundsInitialized
bool CSwordBibleModuleInfo::m_boundsInitialized mutable private
Definition at line 126 of file cswordbiblemoduleinfo.h.
Referenced by books().
m_cachedLocale
QString CSwordBibleModuleInfo::m_cachedLocale mutable private
Definition at line 133 of file cswordbiblemoduleinfo.h.
Referenced by books().
m_hasNT
bool CSwordBibleModuleInfo::m_hasNT mutable private
Definition at line 130 of file cswordbiblemoduleinfo.h.
Referenced by books().
m_hasOT
bool CSwordBibleModuleInfo::m_hasOT mutable private
Definition at line 129 of file cswordbiblemoduleinfo.h.
Referenced by books().
m_lowerBound
CSwordVerseKey CSwordBibleModuleInfo::m_lowerBound mutable private
Definition at line 127 of file cswordbiblemoduleinfo.h.
m_upperBound
CSwordVerseKey CSwordBibleModuleInfo::m_upperBound mutable private
Definition at line 128 of file cswordbiblemoduleinfo.h.
The documentation for this class was generated from the following files:
cswordbiblemoduleinfo.h
cswordbiblemoduleinfo.cpp