BibleTime: BtBookmarksModelPrivate::BookmarkItem Class Reference
BtBookmarksModelPrivate::BookmarkItem Class Reference
Public Member Functions
BookmarkItem (BookmarkItemBase *parent)
BookmarkItem (const BookmarkItem &other)
BookmarkItem (const CSwordModuleInfo &module, const QString &key, const QString &description, const QString &title)
const QString & description () const
const QString & englishKey () const
QString key () const
CSwordModuleInfo * module () const
const QString & moduleName () const
void setDescription (QString const &description)
void setKey (QString const &key)
void setModule (QString const &moduleName)
QString toolTip () const override
Public Member Functions inherited from BtBookmarksModelPrivate::BookmarkItemBase
void addChild (BookmarkItemBase *child)
BookmarkItemBase (BookmarkItemBase *parent=nullptr)
BookmarkItemBase (const BookmarkItemBase &other)
BookmarkItemBase * child (int index) const
int childCount () const
QList< BookmarkItemBase * > & children ()
Qt::ItemFlags flags () const
QIcon icon () const
int index () const
void insertChild (int index, BookmarkItemBase *child)
void insertChildren (int index, QList< BookmarkItemBase * > children)
BookmarkItemBase * parent () const
void removeChild (int index)
void setFlags (Qt::ItemFlags flags)
void setIcon (QIcon const &icon)
void setParent (BookmarkItemBase *parent)
void setText (QString const &text)
void setToolTip (QString const &tooltip)
const QString & text () const
virtual ~BookmarkItemBase ()
Private Attributes
QString m_description
QString m_key
QString m_moduleName
Friends
class BookmarkLoader
Detailed Description
Definition at line 161 of file btbookmarksmodel.cpp.
Constructor & Destructor Documentation
BookmarkItem() [1/3]
BookmarkItem::BookmarkItem (BookmarkItemBase * parent)
Definition at line 518 of file btbookmarksmodel.cpp.
References key(), module(), BtBookmarksModelPrivate::BookmarkItemBase::setFlags(), BtBookmarksModelPrivate::BookmarkItemBase::setIcon(), BtBookmarksModelPrivate::BookmarkItemBase::setText(), and anonymous_namespace{btbookmarksmodel.cpp}::toHeader().
BookmarkItem() [2/3]
BtBookmarksModelPrivate::BookmarkItem::BookmarkItem (const CSwordModuleInfo & module, const QString & key, const QString & description, const QString & title)
Creates a bookmark with module, key and description.
BookmarkItem() [3/3]
BookmarkItem::BookmarkItem (const BookmarkItem & other)
Creates a copy.
Definition at line 525 of file btbookmarksmodel.cpp.
References key(), module(), BtBookmarksModelPrivate::BookmarkItemBase::setIcon(), BtBookmarksModelPrivate::BookmarkItemBase::setText(), and anonymous_namespace{btbookmarksmodel.cpp}::toHeader().
Member Function Documentation
description()
const QString& BtBookmarksModelPrivate::BookmarkItem::description () const inline
Returns the used description.
Definition at line 183 of file btbookmarksmodel.cpp.
References m_description.
Referenced by BtBookmarksModelPrivate::saveItem(), setDescription(), and toolTip().
englishKey()
const QString& BtBookmarksModelPrivate::BookmarkItem::englishKey () const inline
Returns the english key.
Definition at line 192 of file btbookmarksmodel.cpp.
References m_key.
Referenced by BtBookmarksModelPrivate::saveItem().
key()
QString BtBookmarksModelPrivate::BookmarkItem::key () const
Returns the used key.
Referenced by BookmarkItem(), setKey(), and toolTip().
module()
CSwordModuleInfo* BtBookmarksModelPrivate::BookmarkItem::module () const
Returns the used module, 0 if there is no such module.
Referenced by BookmarkItem(), BtBookmarksModelPrivate::saveItem(), and toolTip().
moduleName()
const QString& BtBookmarksModelPrivate::BookmarkItem::moduleName () const inline
Definition at line 197 of file btbookmarksmodel.cpp.
References m_moduleName.
Referenced by BtBookmarksModelPrivate::saveItem(), and setModule().
setDescription()
void BtBookmarksModelPrivate::BookmarkItem::setDescription (QString const & description) inline
Definition at line 185 of file btbookmarksmodel.cpp.
References description(), and m_description.
Referenced by BtBookmarksModelPrivate::handleXmlElement().
setKey()
void BtBookmarksModelPrivate::BookmarkItem::setKey (QString const & key) inline
Definition at line 180 of file btbookmarksmodel.cpp.
References key(), and m_key.
Referenced by BtBookmarksModelPrivate::handleXmlElement().
setModule()
void BtBookmarksModelPrivate::BookmarkItem::setModule (QString const & moduleName) inline
Definition at line 194 of file btbookmarksmodel.cpp.
References m_moduleName, and moduleName().
Referenced by BtBookmarksModelPrivate::handleXmlElement().
toolTip()
QString BookmarkItem::toolTip () const override virtual
Returns a tooltip for this bookmark.
Reimplemented from BtBookmarksModelPrivate::BookmarkItemBase.
Definition at line 558 of file btbookmarksmodel.cpp.
References BT_ASSERT, btConfig(), CSwordKey::createInstance(), description(), FilterOptions::footnotes, BtConfig::getFilterOptions(), CSwordBackend::instance(), key(), module(), FilterOptions::scriptureReferences, CSwordBackend::setFilterOptions(), BtBookmarksModelPrivate::BookmarkItemBase::text(), and anonymous_namespace{btbookmarksmodel.cpp}::toHeader().
Friends And Related Function Documentation
BookmarkLoader
friend class BookmarkLoader friend
Definition at line 163 of file btbookmarksmodel.cpp.
Member Data Documentation
m_description
QString BtBookmarksModelPrivate::BookmarkItem::m_description private
Definition at line 201 of file btbookmarksmodel.cpp.
Referenced by description(), and setDescription().
m_key
QString BtBookmarksModelPrivate::BookmarkItem::m_key private
Definition at line 200 of file btbookmarksmodel.cpp.
Referenced by englishKey(), and setKey().
m_moduleName
QString BtBookmarksModelPrivate::BookmarkItem::m_moduleName private
Definition at line 202 of file btbookmarksmodel.cpp.
Referenced by moduleName(), and setModule().
The documentation for this class was generated from the following file:
btbookmarksmodel.cpp