BibleTime: message::anonymous_namespace{messagedialog.cpp} Namespace Reference
message::anonymous_namespace{messagedialog.cpp} Namespace Reference
Functions
QMessageBox::StandardButton bt_messageBox (QMessageBox::Icon icon, QWidget *parent, const QString &title, const QString &text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
void replaceText (QDialogButtonBox *box, QDialogButtonBox::StandardButton flag, const QString &text)
Function Documentation
bt_messageBox()
QMessageBox::StandardButton message::anonymous_namespace{messagedialog.cpp}::bt_messageBox (QMessageBox::Icon icon, QWidget * parent, const QString & title, const QString & text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
Definition at line 37 of file messagedialog.cpp.
References BT_ASSERT, and message::prepareDialogBox().
Referenced by message::showCritical(), message::showInformation(), message::showQuestion(), and message::showWarning().
replaceText()
void message::anonymous_namespace{messagedialog.cpp}::replaceText (QDialogButtonBox * box, QDialogButtonBox::StandardButton flag, const QString & text)
Definition at line 29 of file messagedialog.cpp.
Referenced by message::prepareDialogBox().