BibleTime: BtBookshelfDockWidget Class Reference
BtBookshelfDockWidget Class Reference
#include <btbookshelfdockwidget.h>
Signals
void groupingOrderChanged (BtBookshelfTreeModel::Grouping newGrouping)
void installWorksClicked ()
void moduleAboutTriggered (CSwordModuleInfo *module)
void moduleHovered (CSwordModuleInfo *module)
void moduleOpenTriggered (CSwordModuleInfo *module)
void moduleSearchTriggered (CSwordModuleInfo *module)
void moduleUnlockTriggered (CSwordModuleInfo *module)
Public Member Functions
BtBookshelfDockWidget (QWidget *parent=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
BtBookshelfTreeModel::Grouping const & groupingOrder () const
void loadBookshelfState ()
void saveBookshelfState ()
BtBookshelfTreeModel * treeModel () noexcept
Static Public Member Functions
static BtBookshelfDockWidget * getInstance ()
Protected Member Functions
void initMenus ()
void retranslateUi ()
Protected Attributes
BtBookshelfWidget * m_bookshelfWidget
QPushButton * m_installButton
QLabel * m_installLabel
QAction * m_itemAboutAction
QMenu * m_itemContextMenu
QAction * m_itemOpenAction
QAction * m_itemSearchAction
QAction * m_itemUnlockAction
QStackedWidget * m_stackedWidget
BtBookshelfTreeModel * m_treeModel
QWidget * m_welcomeWidget
Static Protected Attributes
static BtBookshelfDockWidget * m_instance = nullptr
Detailed Description
Definition at line 32 of file btbookshelfdockwidget.h.
Constructor & Destructor Documentation
BtBookshelfDockWidget()
BtBookshelfDockWidget::BtBookshelfDockWidget (QWidget * parent = nullptr, Qt::WindowFlags f = Qt::WindowFlags())
Bug:
The correct grouping action is not selected on startup.
Todo:
Implement a better unlock dialog, which could incorporate the following warning message. Actually the whole case when the user tries to open a locked module needs to be rethought and refactored.
Todo:
We need to keep the module name because unlocking currently reloads sword.
Definition at line 46 of file btbookshelfdockwidget.cpp.
References BT_ASSERT, BT_CONNECT, btConfig(), initMenus(), CSwordBackend::instance(), m_bookshelfWidget, m_installButton, m_installLabel, m_instance, m_itemContextMenu, m_stackedWidget, m_treeModel, m_welcomeWidget, BtBookshelfView::moduleActivated(), BtBookshelfWidget::setItemContextMenu(), BtBookshelfWidget::setSourceModel(), BtBookshelfWidget::setTreeModel(), and BtBookshelfWidget::treeView().
Member Function Documentation
getInstance()
static BtBookshelfDockWidget * BtBookshelfDockWidget::getInstance () inline static
Definition at line 37 of file btbookshelfdockwidget.h.
References m_instance.
Referenced by BtModuleChooserMenu::BtModuleChooserMenu().
groupingOrder()
BtBookshelfTreeModel::Grouping const & BtBookshelfDockWidget::groupingOrder () const inline
Definition at line 41 of file btbookshelfdockwidget.h.
References BtBookshelfTreeModel::groupingOrder(), and m_treeModel.
groupingOrderChanged
void BtBookshelfDockWidget::groupingOrderChanged (BtBookshelfTreeModel::Grouping newGrouping) signal
initMenus()
void BtBookshelfDockWidget::initMenus () protected
Definition at line 152 of file btbookshelfdockwidget.cpp.
References BT_CONNECT, CSwordModuleInfo::isLocked(), m_itemAboutAction, m_itemContextMenu, m_itemOpenAction, m_itemSearchAction, m_itemUnlockAction, moduleAboutTriggered(), moduleOpenTriggered(), moduleSearchTriggered(), moduleUnlockTriggered(), and CSwordModuleInfo::name().
Referenced by BtBookshelfDockWidget().
installWorksClicked
void BtBookshelfDockWidget::installWorksClicked () signal
Referenced by BibleTime::initConnections().
loadBookshelfState()
void BtBookshelfDockWidget::loadBookshelfState ()
Definition at line 212 of file btbookshelfdockwidget.cpp.
References BtBookshelfWidget::loadBookshelfState(), and m_bookshelfWidget.
Referenced by BibleTime::initView().
moduleAboutTriggered
void BtBookshelfDockWidget::moduleAboutTriggered (CSwordModuleInfo * module) signal
Referenced by BibleTime::initConnections(), and initMenus().
moduleHovered
void BtBookshelfDockWidget::moduleHovered (CSwordModuleInfo * module) signal
Referenced by BibleTime::initView().
moduleOpenTriggered
void BtBookshelfDockWidget::moduleOpenTriggered (CSwordModuleInfo * module) signal
Referenced by BibleTime::initConnections(), and initMenus().
moduleSearchTriggered
void BtBookshelfDockWidget::moduleSearchTriggered (CSwordModuleInfo * module) signal
Referenced by BibleTime::initConnections(), and initMenus().
moduleUnlockTriggered
void BtBookshelfDockWidget::moduleUnlockTriggered (CSwordModuleInfo * module) signal
Referenced by BibleTime::initConnections(), and initMenus().
retranslateUi()
void BtBookshelfDockWidget::retranslateUi () protected
Definition at line 200 of file btbookshelfdockwidget.cpp.
References m_installButton, m_installLabel, m_itemAboutAction, m_itemOpenAction, and m_itemUnlockAction.
saveBookshelfState()
void BtBookshelfDockWidget::saveBookshelfState ()
Definition at line 216 of file btbookshelfdockwidget.cpp.
References m_bookshelfWidget, and BtBookshelfWidget::saveBookshelfState().
Referenced by BibleTime::~BibleTime().
treeModel()
BtBookshelfTreeModel * BtBookshelfDockWidget::treeModel () inline noexcept
Definition at line 39 of file btbookshelfdockwidget.h.
References m_treeModel.
Member Data Documentation
m_bookshelfWidget
BtBookshelfWidget* BtBookshelfDockWidget::m_bookshelfWidget protected
Definition at line 64 of file btbookshelfdockwidget.h.
Referenced by BtBookshelfDockWidget(), loadBookshelfState(), and saveBookshelfState().
m_installButton
QPushButton* BtBookshelfDockWidget::m_installButton protected
Definition at line 67 of file btbookshelfdockwidget.h.
Referenced by BtBookshelfDockWidget(), and retranslateUi().
m_installLabel
QLabel* BtBookshelfDockWidget::m_installLabel protected
Definition at line 66 of file btbookshelfdockwidget.h.
Referenced by BtBookshelfDockWidget(), and retranslateUi().
m_instance
BtBookshelfDockWidget * BtBookshelfDockWidget::m_instance = nullptr static protected
Definition at line 76 of file btbookshelfdockwidget.h.
Referenced by BtBookshelfDockWidget(), and getInstance().
m_itemAboutAction
QAction* BtBookshelfDockWidget::m_itemAboutAction protected
Definition at line 74 of file btbookshelfdockwidget.h.
Referenced by initMenus(), and retranslateUi().
m_itemContextMenu
QMenu* BtBookshelfDockWidget::m_itemContextMenu protected
Definition at line 70 of file btbookshelfdockwidget.h.
Referenced by BtBookshelfDockWidget(), and initMenus().
m_itemOpenAction
QAction* BtBookshelfDockWidget::m_itemOpenAction protected
Definition at line 71 of file btbookshelfdockwidget.h.
Referenced by initMenus(), and retranslateUi().
m_itemSearchAction
QAction* BtBookshelfDockWidget::m_itemSearchAction protected
Definition at line 72 of file btbookshelfdockwidget.h.
Referenced by initMenus().
m_itemUnlockAction
QAction* BtBookshelfDockWidget::m_itemUnlockAction protected
Definition at line 73 of file btbookshelfdockwidget.h.
Referenced by initMenus(), and retranslateUi().
m_stackedWidget
QStackedWidget* BtBookshelfDockWidget::m_stackedWidget protected
Definition at line 63 of file btbookshelfdockwidget.h.
Referenced by BtBookshelfDockWidget().
m_treeModel
BtBookshelfTreeModel* BtBookshelfDockWidget::m_treeModel protected
Definition at line 61 of file btbookshelfdockwidget.h.
Referenced by BtBookshelfDockWidget(), groupingOrder(), and treeModel().
m_welcomeWidget
QWidget* BtBookshelfDockWidget::m_welcomeWidget protected
Definition at line 65 of file btbookshelfdockwidget.h.
Referenced by BtBookshelfDockWidget().
The documentation for this class was generated from the following files:
btbookshelfdockwidget.h
btbookshelfdockwidget.cpp