BibleTime: BtFontSettingsPage Class Reference
BtFontSettingsPage Class Reference
#include <btfontsettings.h>
Classes
struct WorkSetting
Public Member Functions
BtFontSettingsPage (CConfigurationDialog *parent=nullptr)
void save () const final override
Public Member Functions inherited from BtConfigDialog::Page
Page (QIcon const &icon, QWidget *const parent=nullptr)
void setHeaderText (QString const &headerText)
~Page () noexcept override
Protected Slots
void useOwnFontClicked (bool)
Private Member Functions
void retranslateUi ()
Private Attributes
QFontDialog * m_fontChooser
QGroupBox * m_fontsGroupBox
QCheckBox * m_languageCheckBox
QComboBox * m_languageComboBox
QLabel * m_languageLabel
std::vector< WorkSetting > m_workSettings
Detailed Description
Definition at line 31 of file btfontsettings.h.
Constructor & Destructor Documentation
BtFontSettingsPage()
BtFontSettingsPage::BtFontSettingsPage (CConfigurationDialog * parent = nullptr)
Todo:
remember the last selected font and jump there.
Todo:
Eeli's wishlist: why not show something relevant here, like a Bible verse in chosen (not tr()'ed!) language?
Definition at line 39 of file btfontsettings.cpp.
References CSwordBackend::availableLanguages(), BT_ASSERT, BT_CONNECT, btConfig(), BtConfig::getFontForLanguage(), CSwordBackend::instance(), m_fontChooser, m_fontsGroupBox, m_languageCheckBox, m_languageComboBox, m_languageLabel, m_workSettings, retranslateUi(), and useOwnFontClicked().
Member Function Documentation
retranslateUi()
void BtFontSettingsPage::retranslateUi () private
Definition at line 156 of file btfontsettings.cpp.
References m_languageCheckBox, m_languageComboBox, m_languageLabel, and BtConfigDialog::Page::setHeaderText().
Referenced by BtFontSettingsPage().
save()
void BtFontSettingsPage::save () const final override virtual
Implements BtConfigDialog::Page.
Definition at line 142 of file btfontsettings.cpp.
References btConfig(), m_workSettings, and BtConfig::setFontForLanguage().
useOwnFontClicked
void BtFontSettingsPage::useOwnFontClicked (bool isOn) protected slot
Definition at line 147 of file btfontsettings.cpp.
References m_fontChooser, m_languageComboBox, and m_workSettings.
Referenced by BtFontSettingsPage().
Member Data Documentation
m_fontChooser
QFontDialog* BtFontSettingsPage::m_fontChooser private
Definition at line 63 of file btfontsettings.h.
Referenced by BtFontSettingsPage(), and useOwnFontClicked().
m_fontsGroupBox
QGroupBox* BtFontSettingsPage::m_fontsGroupBox private
Definition at line 59 of file btfontsettings.h.
Referenced by BtFontSettingsPage().
m_languageCheckBox
QCheckBox* BtFontSettingsPage::m_languageCheckBox private
Definition at line 62 of file btfontsettings.h.
Referenced by BtFontSettingsPage(), and retranslateUi().
m_languageComboBox
QComboBox* BtFontSettingsPage::m_languageComboBox private
Definition at line 61 of file btfontsettings.h.
Referenced by BtFontSettingsPage(), retranslateUi(), and useOwnFontClicked().
m_languageLabel
QLabel* BtFontSettingsPage::m_languageLabel private
Definition at line 60 of file btfontsettings.h.
Referenced by BtFontSettingsPage(), and retranslateUi().
m_workSettings
std::vector<WorkSetting> BtFontSettingsPage::m_workSettings private
Definition at line 65 of file btfontsettings.h.
Referenced by BtFontSettingsPage(), save(), and useOwnFontClicked().
The documentation for this class was generated from the following files:
btfontsettings.h
btfontsettings.cpp