BibleTime: BTAboutModuleDialog Class Reference
BTAboutModuleDialog Class Reference
#include <btaboutmoduledialog.h>
Public Member Functions
BTAboutModuleDialog (const CSwordModuleInfo *moduleInfo, QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
Protected Member Functions
void retranslateUi ()
Private Attributes
QDialogButtonBox * m_buttons
const CSwordModuleInfo * m_moduleInfo
QTextEdit * m_textEdit
Detailed Description
Dialog to show the information about a module.
Definition at line 30 of file btaboutmoduledialog.h.
Constructor & Destructor Documentation
BTAboutModuleDialog()
BTAboutModuleDialog::BTAboutModuleDialog (const CSwordModuleInfo * moduleInfo, QWidget * parent = nullptr, Qt::WindowFlags flags = Qt::WindowFlags())
Definition at line 23 of file btaboutmoduledialog.cpp.
References BT_CONNECT, m_buttons, m_textEdit, and retranslateUi().
Member Function Documentation
retranslateUi()
void BTAboutModuleDialog::retranslateUi () protected
Definition at line 48 of file btaboutmoduledialog.cpp.
References CSwordModuleInfo::aboutText(), m_buttons, m_moduleInfo, m_textEdit, CSwordModuleInfo::name(), and message::prepareDialogBox().
Referenced by BTAboutModuleDialog().
Member Data Documentation
m_buttons
QDialogButtonBox* BTAboutModuleDialog::m_buttons private
Definition at line 48 of file btaboutmoduledialog.h.
Referenced by BTAboutModuleDialog(), and retranslateUi().
m_moduleInfo
const CSwordModuleInfo* BTAboutModuleDialog::m_moduleInfo private
Definition at line 46 of file btaboutmoduledialog.h.
Referenced by retranslateUi().
m_textEdit
QTextEdit* BTAboutModuleDialog::m_textEdit private
Definition at line 47 of file btaboutmoduledialog.h.
Referenced by BTAboutModuleDialog(), and retranslateUi().
The documentation for this class was generated from the following files:
btaboutmoduledialog.h
btaboutmoduledialog.cpp