BibleTime: BtDropdownChooserButton Class Reference
BtDropdownChooserButton Class Reference
#include <btdropdownchooserbutton.h>
Signals
void stepItem (int step)
Public Member Functions
BtDropdownChooserButton (void(BtBibleKeyWidget::*populateMenu)(QMenu &), BtBibleKeyWidget &parent)
void mousePressEvent (QMouseEvent *event) override
Protected Member Functions
void wheelEvent (QWheelEvent *event) override
Private Attributes
BtBibleKeyWidget & m_parent
void(BtBibleKeyWidget::* m_populateMenu)(QMenu &)
Detailed Description
Base class for book/ch/v dropdown list chooser buttons.
Definition at line 23 of file btdropdownchooserbutton.h.
Constructor & Destructor Documentation
BtDropdownChooserButton()
BtDropdownChooserButton::BtDropdownChooserButton (void(BtBibleKeyWidget::*)(QMenu &) populateMenu, BtBibleKeyWidget & parent)
Definition at line 22 of file btdropdownchooserbutton.cpp.
References ARROW_HEIGHT.
Member Function Documentation
mousePressEvent()
void BtDropdownChooserButton::mousePressEvent (QMouseEvent * event) override
The item list is constructed here just before the menu is shown.
Definition at line 47 of file btdropdownchooserbutton.cpp.
References m_parent, and m_populateMenu.
stepItem
void BtDropdownChooserButton::stepItem (int step) signal
Referenced by wheelEvent().
wheelEvent()
void BtDropdownChooserButton::wheelEvent (QWheelEvent * event) override protected
Definition at line 55 of file btdropdownchooserbutton.cpp.
References stepItem().
Member Data Documentation
m_parent
BtBibleKeyWidget& BtDropdownChooserButton::m_parent private
Definition at line 43 of file btdropdownchooserbutton.h.
Referenced by mousePressEvent().
m_populateMenu
void(BtBibleKeyWidget::* BtDropdownChooserButton::m_populateMenu) (QMenu &) private
Definition at line 42 of file btdropdownchooserbutton.h.
Referenced by mousePressEvent().
The documentation for this class was generated from the following files:
btdropdownchooserbutton.h
btdropdownchooserbutton.cpp