BibleTime: BtTextFiltersTab Class Reference
BtTextFiltersTab Class Reference
#include <bttextfilterstab.h>
Public Member Functions
BtTextFiltersTab (CSwordSettingsPage *parent)
void save ()
Protected Member Functions
void retranslateUi ()
Private Member Functions
TEXT_FILTERS_TAB_FIELD (greekAccents)
TEXT_FILTERS_TAB_FIELD (headings)
TEXT_FILTERS_TAB_FIELD (hebrewCantillation)
TEXT_FILTERS_TAB_FIELD (hebrewPoints)
TEXT_FILTERS_TAB_FIELD (morphSegmentation)
TEXT_FILTERS_TAB_FIELD (scriptureReferences)
TEXT_FILTERS_TAB_FIELD (textualVariants)
TEXT_FILTERS_TAB_FIELD (verseNumbers)
Private Attributes
QLabel * m_explanationLabel
Detailed Description
Definition at line 26 of file bttextfilterstab.h.
Constructor & Destructor Documentation
BtTextFiltersTab()
BtTextFiltersTab::BtTextFiltersTab (CSwordSettingsPage * parent)
Definition at line 30 of file bttextfilterstab.cpp.
References btConfig(), BtConfigCore::group(), m_explanationLabel, retranslateUi(), BtConfig::session(), and TEXT_FILTERS_TAB_ADD_ROW.
Member Function Documentation
retranslateUi()
void BtTextFiltersTab::retranslateUi () protected
Definition at line 76 of file bttextfilterstab.cpp.
References util::tool::initExplanationLabel(), and m_explanationLabel.
Referenced by BtTextFiltersTab().
save()
void BtTextFiltersTab::save ()
Definition at line 63 of file bttextfilterstab.cpp.
References btConfig(), BtConfigCore::group(), BtConfig::session(), and TEXT_FILTERS_TAB_SAVE.
Referenced by CSwordSettingsPage::save().
TEXT_FILTERS_TAB_FIELD() [1/8]
BtTextFiltersTab::TEXT_FILTERS_TAB_FIELD (greekAccents) private
TEXT_FILTERS_TAB_FIELD() [2/8]
BtTextFiltersTab::TEXT_FILTERS_TAB_FIELD (headings) private
TEXT_FILTERS_TAB_FIELD() [3/8]
BtTextFiltersTab::TEXT_FILTERS_TAB_FIELD (hebrewCantillation) private
TEXT_FILTERS_TAB_FIELD() [4/8]
BtTextFiltersTab::TEXT_FILTERS_TAB_FIELD (hebrewPoints) private
TEXT_FILTERS_TAB_FIELD() [5/8]
BtTextFiltersTab::TEXT_FILTERS_TAB_FIELD (morphSegmentation) private
TEXT_FILTERS_TAB_FIELD() [6/8]
BtTextFiltersTab::TEXT_FILTERS_TAB_FIELD (scriptureReferences) private
TEXT_FILTERS_TAB_FIELD() [7/8]
BtTextFiltersTab::TEXT_FILTERS_TAB_FIELD (textualVariants) private
TEXT_FILTERS_TAB_FIELD() [8/8]
BtTextFiltersTab::TEXT_FILTERS_TAB_FIELD (verseNumbers) private
Member Data Documentation
m_explanationLabel
QLabel* BtTextFiltersTab::m_explanationLabel private
Definition at line 42 of file bttextfilterstab.h.
Referenced by BtTextFiltersTab(), and retranslateUi().
The documentation for this class was generated from the following files:
bttextfilterstab.h
bttextfilterstab.cpp