BibleTime: Language Class Reference
Language Class Reference
#include <language.h>
Public Member Functions
QString const & abbrev () const
QStringList const & abbrevs () const
QString const & englishName () const noexcept
Language (Language &&)=delete
Language (Language const &)=delete
Language (QStringList abbrevs, QString englishName)
Language & operator= (Language &&)=delete
Language & operator= (Language const &)=delete
virtual QString translatedName () const
virtual ~Language ()
Static Public Member Functions
static std::shared_ptr< Language const > fromAbbrev (QString const &abbrev)
Private Attributes
QStringList const m_abbrevs
QString const m_englishName
Detailed Description
Definition at line 20 of file language.h.
Constructor & Destructor Documentation
Language() [1/3]
Language::Language (Language &&) delete
Referenced by fromAbbrev().
Language() [2/3]
Language::Language (Language const &) delete
Language() [3/3]
Language::Language (QStringList abbrevs, QString englishName)
Definition at line 315 of file language.cpp.
References BT_ASSERT, m_abbrevs, and m_englishName.
~Language()
Language::~Language () virtual default
Member Function Documentation
abbrev()
QString const& Language::abbrev () const inline
Returns
the first abbreviation of this language.
Definition at line 34 of file language.h.
References m_abbrevs.
Referenced by fromAbbrev(), BtConfig::getFontForLanguage(), and BtConfig::setFontForLanguage().
abbrevs()
QStringList const& Language::abbrevs () const inline
Returns
the abbreviations of this language.
Definition at line 37 of file language.h.
References m_abbrevs.
Referenced by fromAbbrev().
englishName()
QString const& Language::englishName () const inline noexcept
Returns
the english name of this language.
Definition at line 43 of file language.h.
References m_englishName.
Referenced by fromAbbrev(), BtConfig::getFontForLanguage(), BtConfig::setFontForLanguage(), and translatedName().
fromAbbrev()
std::shared_ptr< Language const > Language::fromAbbrev (QString const & abbrev) static
Parameters
[in] abbrev the language abbreviation in BCP 47 format.
Returns
a pointer to the language of the given abbreviation.
Definition at line 329 of file language.cpp.
References abbrev(), abbrevs(), BT_ASSERT, englishName(), Language(), BtLocaleMgr::localeTranslator(), and translatedName().
Referenced by CDisplaySettingsPage::bookNameAbbreviationsTryVector(), and CDisplaySettingsPage::initSwordLocaleCombo().
operator=() [1/2]
Language& Language::operator= (Language &&) delete
operator=() [2/2]
Language& Language::operator= (Language const &) delete
translatedName()
QString Language::translatedName () const virtual
Returns
the translated name of this language.
Definition at line 326 of file language.cpp.
References englishName().
Referenced by fromAbbrev().
Member Data Documentation
m_abbrevs
QStringList const Language::m_abbrevs private
Definition at line 53 of file language.h.
Referenced by abbrev(), abbrevs(), and Language().
m_englishName
QString const Language::m_englishName private
Definition at line 54 of file language.h.
Referenced by englishName(), and Language().
The documentation for this class was generated from the following files:
language.h
language.cpp