BibleTime: BtToolBarPopupAction Class Reference
BtToolBarPopupAction Class Reference
#include <bttoolbarpopupaction.h>
Public Member Functions
BtToolBarPopupAction (const QIcon &icon, const QString &text, QObject *parent)
bool event (QEvent *e) override
QMenu * popupMenu () const
~BtToolBarPopupAction () override
Protected Member Functions
QWidget * createWidget (QWidget *parent) override
Private Attributes
QIcon m_icon
std::unique_ptr< QMenu > const m_menu
QString m_text
Detailed Description
Definition at line 29 of file bttoolbarpopupaction.h.
Constructor & Destructor Documentation
BtToolBarPopupAction()
BtToolBarPopupAction::BtToolBarPopupAction (const QIcon & icon, const QString & text, QObject * parent)
Definition at line 37 of file bttoolbarpopupaction.cpp.
~BtToolBarPopupAction()
BtToolBarPopupAction::~BtToolBarPopupAction () override default
Member Function Documentation
createWidget()
QWidget * BtToolBarPopupAction::createWidget (QWidget * parent) override protected
Definition at line 51 of file bttoolbarpopupaction.cpp.
References BT_CONNECT, m_icon, m_menu, and m_text.
event()
bool BtToolBarPopupAction::event (QEvent * e) override
Definition at line 64 of file bttoolbarpopupaction.cpp.
References event().
Referenced by event().
popupMenu()
QMenu * BtToolBarPopupAction::popupMenu () const
Definition at line 49 of file bttoolbarpopupaction.cpp.
References m_menu.
Referenced by CDisplayWindow::initConnections().
Member Data Documentation
m_icon
QIcon BtToolBarPopupAction::m_icon private
Definition at line 46 of file bttoolbarpopupaction.h.
Referenced by createWidget().
m_menu
std::unique_ptr<QMenu> const BtToolBarPopupAction::m_menu private
Definition at line 45 of file bttoolbarpopupaction.h.
Referenced by createWidget(), and popupMenu().
m_text
QString BtToolBarPopupAction::m_text private
Definition at line 47 of file bttoolbarpopupaction.h.
Referenced by createWidget().
The documentation for this class was generated from the following files:
bttoolbarpopupaction.h
bttoolbarpopupaction.cpp