BibleTime: Search::CSearchAnalysisScene Class Reference
Search::CSearchAnalysisScene Class Reference
#include <csearchanalysisscene.h>
Public Member Functions
CSearchAnalysisScene (QString searchedText, CSwordModuleSearch::Results const &results, QObject *parent)
void resizeHeight (int height)
void saveAsHTML () const
Static Public Member Functions
static QColor getColor (int index)
Protected Slots
void slotResized ()
Private Member Functions
void saveAsHTML (QTextStream &out) const
Private Attributes
std::map< std::tuple< char, char >, CSearchAnalysisItem * > m_itemList
std::unique_ptr< CSearchAnalysisLegendItem > m_legend
std::size_t m_maxCount = 0
CSwordModuleSearch::Results m_results
QString const m_searchedText
Detailed Description
Definition at line 31 of file csearchanalysisscene.h.
Constructor & Destructor Documentation
CSearchAnalysisScene()
Search::CSearchAnalysisScene::CSearchAnalysisScene (QString searchedText, CSwordModuleSearch::Results const & results, QObject * parent)
Definition at line 50 of file csearchanalysisscene.cpp.
References Search::BAR_DELTAX, Search::BAR_WIDTH, CSwordModuleInfo::Bible, BT_ASSERT, CSwordModuleInfo::Commentary, Search::CSearchAnalysisItem::counts(), getColor(), Search::ITEM_TEXT_SIZE, Search::LEFT_BORDER, Search::LEGEND_DELTAY, Search::LEGEND_INNER_BORDER, Search::LEGEND_WIDTH, m_itemList, m_legend, m_maxCount, m_results, Search::RIGHT_BORDER, ROW_END, ROW_START, slotResized(), Search::SPACE_BETWEEN_PARTS, and Search::UPPER_BORDER.
Member Function Documentation
getColor()
QColor Search::CSearchAnalysisScene::getColor (int index) static
This function returns a color for each module
Returns
The color at position index in the list
This function returns a color for each module
Definition at line 175 of file csearchanalysisscene.cpp.
Referenced by CSearchAnalysisScene(), Search::CSearchAnalysisItem::paint(), and Search::CSearchAnalysisLegendItem::paint().
resizeHeight()
void Search::CSearchAnalysisScene::resizeHeight (int height)
resize the height of the scene
Definition at line 285 of file csearchanalysisscene.cpp.
References slotResized().
Referenced by Search::CSearchAnalysisDialog::resizeEvent().
saveAsHTML() [1/2]
void Search::CSearchAnalysisScene::saveAsHTML () const
Definition at line 202 of file csearchanalysisscene.cpp.
References saveAsHTML(), and util::tool::savePlainFile().
Referenced by Search::CSearchAnalysisDialog::CSearchAnalysisDialog(), and saveAsHTML().
saveAsHTML() [2/2]
void Search::CSearchAnalysisScene::saveAsHTML (QTextStream & out) const private
Definition at line 220 of file csearchanalysisscene.cpp.
References m_itemList, m_results, and m_searchedText.
slotResized
void Search::CSearchAnalysisScene::slotResized () protected slot
No descriptions
Definition at line 155 of file csearchanalysisscene.cpp.
References Search::BAR_DELTAX, Search::BAR_DELTAY, Search::BAR_LOWER_BORDER, Search::BAR_WIDTH, Search::LOWER_BORDER, m_itemList, m_maxCount, m_results, and Search::UPPER_BORDER.
Referenced by CSearchAnalysisScene(), and resizeHeight().
Member Data Documentation
m_itemList
std::map<std::tuple<char, char>, CSearchAnalysisItem *> Search::CSearchAnalysisScene::m_itemList private
Definition at line 65 of file csearchanalysisscene.h.
Referenced by CSearchAnalysisScene(), saveAsHTML(), and slotResized().
m_legend
std::unique_ptr<CSearchAnalysisLegendItem> Search::CSearchAnalysisScene::m_legend private
Definition at line 67 of file csearchanalysisscene.h.
Referenced by CSearchAnalysisScene().
m_maxCount
std::size_t Search::CSearchAnalysisScene::m_maxCount = 0 private
Definition at line 66 of file csearchanalysisscene.h.
Referenced by CSearchAnalysisScene(), and slotResized().
m_results
CSwordModuleSearch::Results Search::CSearchAnalysisScene::m_results private
Definition at line 64 of file csearchanalysisscene.h.
Referenced by CSearchAnalysisScene(), saveAsHTML(), and slotResized().
m_searchedText
QString const Search::CSearchAnalysisScene::m_searchedText private
Definition at line 63 of file csearchanalysisscene.h.
Referenced by saveAsHTML().
The documentation for this class was generated from the following files:
csearchanalysisscene.h
csearchanalysisscene.cpp