BibleTime: message Namespace Reference
message Namespace Reference
Namespaces
namespace anonymous_namespace{messagedialog.cpp}
Functions
void prepareDialogBox (QDialogButtonBox *box)
void setQActionCheckedNoTrigger (QAction *const action, const bool checked)
QMessageBox::StandardButton showCritical (QWidget *parent, const QString &title, const QString &text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
QMessageBox::StandardButton showInformation (QWidget *parent, const QString &title, const QString &text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
QMessageBox::StandardButton showQuestion (QWidget *parent, const QString &title, const QString &text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
QMessageBox::StandardButton showWarning (QWidget *parent, const QString &title, const QString &text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
Function Documentation
prepareDialogBox()
void message::prepareDialogBox (QDialogButtonBox * box)
Translates standard buttons in a QDialogButtonBox.
Definition at line 64 of file messagedialog.cpp.
Referenced by message::anonymous_namespace{messagedialog.cpp}::bt_messageBox(), BtConfigDialog::BtConfigDialog(), BtCopyByReferencesDialog::BtCopyByReferencesDialog(), BtEditBookmarkDialog::BtEditBookmarkDialog(), BtMessageInputDialog::BtMessageInputDialog(), BtShortcutsDialog::BtShortcutsDialog(), BtTipDialog::BtTipDialog(), Search::CSearchAnalysisDialog::CSearchAnalysisDialog(), CSwordSetupInstallSourcesDialog::CSwordSetupInstallSourcesDialog(), Search::CRangeChooserDialog::initView(), BtAboutDialog::retranslateUi(), BTAboutModuleDialog::retranslateUi(), BtModuleChooserDialog::retranslateUi(), and Search::BtSearchSyntaxHelpDialog::retranslateUi().
setQActionCheckedNoTrigger()
void message::setQActionCheckedNoTrigger (QAction *const action, const bool checked = true)
Change the state of a QAction without triggering their signals.
Parameters
action The QAction instance to set the state for.
[in] checked The new state.
Definition at line 57 of file messagedialog.cpp.
References BT_ASSERT.
Referenced by BibleTime::reloadProfile().
showCritical()
QMessageBox::StandardButton message::showCritical (QWidget * parent, const QString & title, const QString & text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
Definition at line 90 of file messagedialog.cpp.
Referenced by CSwordSetupInstallSourcesDialog::CSwordSetupInstallSourcesDialog(), BibleTimeApp::initDisplayTemplateManager(), BibleTime::openOnlineHelp_Handbook(), and BibleTime::openOnlineHelp_Howto().
showInformation()
QMessageBox::StandardButton message::showInformation (QWidget * parent, const QString & title, const QString & text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
Definition at line 86 of file messagedialog.cpp.
Referenced by BibleTime::saveToNewProfile(), and CDisplayWindow::setBibleReference().
showQuestion()
QMessageBox::StandardButton message::showQuestion (QWidget * parent, const QString & title, const QString & text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
Definition at line 94 of file messagedialog.cpp.
Referenced by CAcceleratorSettingsPage::CAcceleratorSettingsPage(), CBookmarkIndex::CBookmarkIndex(), CSwordSetupInstallSourcesDialog::CSwordSetupInstallSourcesDialog(), and Search::CSearchDialog::startSearch().
showWarning()
QMessageBox::StandardButton message::showWarning (QWidget * parent, const QString & title, const QString & text, QMessageBox::StandardButtons buttons, QMessageBox::StandardButton defaultButton)
Definition at line 82 of file messagedialog.cpp.
Referenced by BtModuleIndexDialog::indexAllModulesPrivate(), BibleTimeApp::initBtConfig(), BibleTime::moduleUnlock(), and Search::CSearchDialog::startSearch().