BibleTime: btmodules.cpp File Reference
btmodules.cpp File Reference
#include "btmodules.h"
#include <QString>
#include "../backend/drivers/cswordmoduleinfo.h"
#include "../backend/managers/cswordbackend.h"
Namespaces
anonymous_namespace{btmodules.cpp}
Functions
bool anonymous_namespace{btmodules.cpp}::equalModuleCategories (QString const &n1, QString const &n2)
int leftLikeParallelModules (QStringList const &modules)
Function Documentation
leftLikeParallelModules()
int leftLikeParallelModules (QStringList const & modules)
Definition at line 31 of file btmodules.cpp.
References anonymous_namespace{btmodules.cpp}::equalModuleCategories().
Referenced by BtTextWindowHeader::slotBackendModulesChanged(), BtModuleChooserBar::slotBackendModulesChanged(), BtModuleChooserBar::updateButtonMenus(), and BtTextWindowHeader::updateWidgets().