BibleTime: Rendering::CTextRendering::KeyTreeItem Class Reference
Rendering::CTextRendering::KeyTreeItem Class Reference
#include <ctextrendering.h>
Classes
struct Settings
Public Member Functions
KeyTree & childList () const noexcept
QString const & getAlternativeContent () const
bool hasAlternativeContent () const
QString const & key () const
KeyTreeItem (const QString &content, const Settings &settings)
KeyTreeItem (const QString &key, const BtConstModuleList &modules, const Settings &settings)
KeyTreeItem (const QString &key, const CSwordModuleInfo *module, const Settings &settings)
KeyTreeItem (const QString &startKey, const QString &stopKey, const CSwordModuleInfo *module, const Settings &settings)
KeyTreeItem (KeyTreeItem &&)=delete
KeyTreeItem (KeyTreeItem const &&)=delete
CSwordKey const * mappedKey () const
BtConstModuleList const & modules () const
KeyTreeItem & operator= (KeyTreeItem &&)=delete
KeyTreeItem & operator= (KeyTreeItem const &&)=delete
void setMappedKey (CSwordKey const *key) const
Settings const & settings () const
Private Attributes
QString m_alternativeContent
KeyTree m_childList
QString m_key
CSwordKey const * m_mappedKey = nullptr
BtConstModuleList m_moduleList
Settings m_settings
Detailed Description
Definition at line 42 of file ctextrendering.h.
Constructor & Destructor Documentation
KeyTreeItem() [1/6]
Rendering::CTextRendering::KeyTreeItem::KeyTreeItem (KeyTreeItem &&) delete
KeyTreeItem() [2/6]
Rendering::CTextRendering::KeyTreeItem::KeyTreeItem (KeyTreeItem const &&) delete
KeyTreeItem() [3/6]
CTextRendering::KeyTreeItem::KeyTreeItem (const QString & key, const CSwordModuleInfo * module, const Settings & settings)
Definition at line 31 of file ctextrendering.cpp.
References m_moduleList.
KeyTreeItem() [4/6]
CTextRendering::KeyTreeItem::KeyTreeItem (const QString & key, const BtConstModuleList & modules, const Settings & settings)
Definition at line 44 of file ctextrendering.cpp.
KeyTreeItem() [5/6]
CTextRendering::KeyTreeItem::KeyTreeItem (const QString & startKey, const QString & stopKey, const CSwordModuleInfo * module, const Settings & settings)
Definition at line 52 of file ctextrendering.cpp.
References CSwordModuleInfo::Bible, BT_ASSERT, CSwordModuleInfo::Commentary, CSwordModuleInfo::GenericBook, CSwordVerseKey::key(), Rendering::CTextRendering::KeyTreeItem::Settings::keyRenderingFace, CSwordModuleInfo::Lexicon, m_alternativeContent, m_childList, m_key, m_moduleList, CSwordVerseKey::next(), Rendering::CTextRendering::KeyTreeItem::Settings::NoKey, CSwordVerseKey::setKey(), settings(), and CSwordModuleInfo::type().
KeyTreeItem() [6/6]
CTextRendering::KeyTreeItem::KeyTreeItem (const QString & content, const Settings & settings)
Definition at line 38 of file ctextrendering.cpp.
Member Function Documentation
childList()
KeyTree & Rendering::CTextRendering::KeyTreeItem::childList () const inline noexcept
Definition at line 98 of file ctextrendering.h.
References m_childList.
Referenced by BtPrinter::renderEntry(), and Rendering::CTextRendering::renderEntry().
getAlternativeContent()
QString const & Rendering::CTextRendering::KeyTreeItem::getAlternativeContent () const inline
Definition at line 85 of file ctextrendering.h.
References m_alternativeContent.
Referenced by BtPrinter::renderEntry(), and Rendering::CTextRendering::renderEntry().
hasAlternativeContent()
bool Rendering::CTextRendering::KeyTreeItem::hasAlternativeContent () const inline
Definition at line 88 of file ctextrendering.h.
References m_alternativeContent.
Referenced by BtPrinter::renderEntry(), and Rendering::CTextRendering::renderEntry().
key()
QString const & Rendering::CTextRendering::KeyTreeItem::key () const inline
Definition at line 94 of file ctextrendering.h.
References m_key.
Referenced by Rendering::CTextRendering::entryLink(), Rendering::CDisplayRendering::entryLink(), Rendering::CrossRefRendering::entryLink(), BtPrinter::entryLink(), Rendering::CTextRendering::renderEntry(), Rendering::CPlainTextExportRendering::renderEntry(), and setMappedKey().
mappedKey()
CSwordKey const * Rendering::CTextRendering::KeyTreeItem::mappedKey () const inline
Definition at line 103 of file ctextrendering.h.
References m_mappedKey.
Referenced by Rendering::CDisplayRendering::entryLink().
modules()
BtConstModuleList const & Rendering::CTextRendering::KeyTreeItem::modules () const inline
Definition at line 91 of file ctextrendering.h.
References m_moduleList.
Referenced by Rendering::CDisplayRendering::entryLink(), Rendering::CTextRendering::renderEntry(), and Rendering::CPlainTextExportRendering::renderEntry().
operator=() [1/2]
KeyTreeItem & Rendering::CTextRendering::KeyTreeItem::operator= (KeyTreeItem &&) delete
operator=() [2/2]
KeyTreeItem & Rendering::CTextRendering::KeyTreeItem::operator= (KeyTreeItem const &&) delete
setMappedKey()
void Rendering::CTextRendering::KeyTreeItem::setMappedKey (CSwordKey const * key) const inline
Definition at line 100 of file ctextrendering.h.
References key(), and m_mappedKey.
Referenced by Rendering::CTextRendering::renderEntry().
settings()
Settings const & Rendering::CTextRendering::KeyTreeItem::settings () const inline
Definition at line 96 of file ctextrendering.h.
References m_settings.
Referenced by Rendering::CDisplayRendering::entryLink(), Rendering::CrossRefRendering::entryLink(), BtPrinter::entryLink(), KeyTreeItem(), and Rendering::CTextRendering::renderEntry().
Member Data Documentation
m_alternativeContent
QString Rendering::CTextRendering::KeyTreeItem::m_alternativeContent private
Definition at line 113 of file ctextrendering.h.
Referenced by getAlternativeContent(), hasAlternativeContent(), and KeyTreeItem().
m_childList
KeyTree Rendering::CTextRendering::KeyTreeItem::m_childList mutable private
Definition at line 111 of file ctextrendering.h.
Referenced by childList(), and KeyTreeItem().
m_key
QString Rendering::CTextRendering::KeyTreeItem::m_key private
Definition at line 109 of file ctextrendering.h.
Referenced by key(), and KeyTreeItem().
m_mappedKey
CSwordKey const* Rendering::CTextRendering::KeyTreeItem::m_mappedKey = nullptr mutable private
Definition at line 110 of file ctextrendering.h.
Referenced by mappedKey(), and setMappedKey().
m_moduleList
BtConstModuleList Rendering::CTextRendering::KeyTreeItem::m_moduleList private
Definition at line 108 of file ctextrendering.h.
Referenced by KeyTreeItem(), KeyTreeItem(), and modules().
m_settings
Settings Rendering::CTextRendering::KeyTreeItem::m_settings private
Definition at line 107 of file ctextrendering.h.
Referenced by settings().
The documentation for this class was generated from the following files:
ctextrendering.h
ctextrendering.cpp