BibleTime: BtBookshelfInstallFinalPage Class Reference
BtBookshelfInstallFinalPage Class Reference final
#include <btbookshelfinstallfinalpage.h>
Public Slots
void slotStopInstall ()
Public Member Functions
BtBookshelfInstallFinalPage (QWidget *parent=nullptr)
void destroyThread () noexcept
void initializePage () final override
bool isComplete () const final override
int nextId () const final override
BtModuleSet selectedWorks () const
~BtBookshelfInstallFinalPage () noexcept final override
Public Member Functions inherited from BtBookshelfWizardPage
BtBookshelfWizardPage (QWidget *parent=nullptr)
BtBookshelfWizard & btWizard () const noexcept
Private Slots
void slotInstallStarted (int moduleIndex)
void slotOneItemCompleted (int moduleIndex, bool status)
void slotStatusUpdated (int moduleIndex, int status)
void slotThreadFinished ()
Private Member Functions
void retranslateUi ()
Private Attributes
bool m_installCompleted = false
bool m_installFailed = false
int m_lastStatus = -1
QList< CSwordModuleInfo * > m_modules
QLabel * m_msgLabel
QLabel * m_msgLabel2
QProgressBar * m_progressBar
QPushButton * m_stopButton
BtInstallThread * m_thread = nullptr
QVBoxLayout * m_verticalLayout
Detailed Description
Definition at line 31 of file btbookshelfinstallfinalpage.h.
Constructor & Destructor Documentation
BtBookshelfInstallFinalPage()
BtBookshelfInstallFinalPage::BtBookshelfInstallFinalPage (QWidget * parent = nullptr)
Definition at line 41 of file btbookshelfinstallfinalpage.cpp.
References BT_CONNECT, m_msgLabel, m_msgLabel2, m_progressBar, m_stopButton, m_verticalLayout, and slotStopInstall().
~BtBookshelfInstallFinalPage()
BtBookshelfInstallFinalPage::~BtBookshelfInstallFinalPage () inline final override noexcept
Definition at line 38 of file btbookshelfinstallfinalpage.h.
References destroyThread().
Member Function Documentation
destroyThread()
void BtBookshelfInstallFinalPage::destroyThread () noexcept
Definition at line 86 of file btbookshelfinstallfinalpage.cpp.
References m_thread, and BtInstallThread::stopInstall().
Referenced by initializePage(), and ~BtBookshelfInstallFinalPage().
initializePage()
void BtBookshelfInstallFinalPage::initializePage () final override
Definition at line 115 of file btbookshelfinstallfinalpage.cpp.
References BT_CONNECT, BtBookshelfWizardPage::btWizard(), destroyThread(), BtInstallThread::downloadStarted(), BtInstallThread::installCompleted(), m_installCompleted, m_installFailed, m_modules, m_progressBar, m_stopButton, m_thread, BtInstallThread::preparingInstall(), retranslateUi(), slotInstallStarted(), slotOneItemCompleted(), slotStatusUpdated(), slotThreadFinished(), and BtInstallThread::statusUpdated().
isComplete()
bool BtBookshelfInstallFinalPage::isComplete () const final override
Definition at line 143 of file btbookshelfinstallfinalpage.cpp.
References m_installCompleted.
nextId()
int BtBookshelfInstallFinalPage::nextId () const final override
Definition at line 113 of file btbookshelfinstallfinalpage.cpp.
retranslateUi()
void BtBookshelfInstallFinalPage::retranslateUi () private
Definition at line 95 of file btbookshelfinstallfinalpage.cpp.
References BtBookshelfWizardPage::btWizard(), m_stopButton, and updateWorks.
Referenced by initializePage().
selectedWorks()
BtModuleSet BtBookshelfInstallFinalPage::selectedWorks () const
slotInstallStarted
void BtBookshelfInstallFinalPage::slotInstallStarted (int moduleIndex) private slot
Definition at line 152 of file btbookshelfinstallfinalpage.cpp.
References CSwordModuleInfo::Description, m_lastStatus, m_modules, m_msgLabel, and m_msgLabel2.
Referenced by initializePage().
slotOneItemCompleted
void BtBookshelfInstallFinalPage::slotOneItemCompleted (int moduleIndex, bool status) private slot
Definition at line 175 of file btbookshelfinstallfinalpage.cpp.
References m_installFailed, m_modules, and m_progressBar.
Referenced by initializePage().
slotStatusUpdated
void BtBookshelfInstallFinalPage::slotStatusUpdated (int moduleIndex, int status) private slot
Definition at line 159 of file btbookshelfinstallfinalpage.cpp.
References m_lastStatus, m_modules, and m_progressBar.
Referenced by initializePage().
slotStopInstall
void BtBookshelfInstallFinalPage::slotStopInstall () slot
Definition at line 146 of file btbookshelfinstallfinalpage.cpp.
References m_installFailed, m_stopButton, m_thread, and BtInstallThread::stopInstall().
Referenced by BtBookshelfInstallFinalPage(), and BtBookshelfWizard::stopDownload().
slotThreadFinished
void BtBookshelfInstallFinalPage::slotThreadFinished () private slot
Definition at line 183 of file btbookshelfinstallfinalpage.cpp.
References BtBookshelfWizardPage::btWizard(), BtBookshelfWizard::downloadFinished(), CSwordBackend::instance(), m_installCompleted, m_installFailed, m_msgLabel, m_msgLabel2, m_progressBar, m_stopButton, and CSwordBackend::reloadModules().
Referenced by initializePage().
Member Data Documentation
m_installCompleted
bool BtBookshelfInstallFinalPage::m_installCompleted = false private
Definition at line 71 of file btbookshelfinstallfinalpage.h.
Referenced by initializePage(), isComplete(), and slotThreadFinished().
m_installFailed
bool BtBookshelfInstallFinalPage::m_installFailed = false private
Definition at line 70 of file btbookshelfinstallfinalpage.h.
Referenced by initializePage(), slotOneItemCompleted(), slotStopInstall(), and slotThreadFinished().
m_lastStatus
int BtBookshelfInstallFinalPage::m_lastStatus = -1 private
Definition at line 74 of file btbookshelfinstallfinalpage.h.
Referenced by slotInstallStarted(), and slotStatusUpdated().
m_modules
QList<CSwordModuleInfo *> BtBookshelfInstallFinalPage::m_modules private
Definition at line 73 of file btbookshelfinstallfinalpage.h.
Referenced by initializePage(), slotInstallStarted(), slotOneItemCompleted(), and slotStatusUpdated().
m_msgLabel
QLabel* BtBookshelfInstallFinalPage::m_msgLabel private
Definition at line 63 of file btbookshelfinstallfinalpage.h.
Referenced by BtBookshelfInstallFinalPage(), slotInstallStarted(), and slotThreadFinished().
m_msgLabel2
QLabel* BtBookshelfInstallFinalPage::m_msgLabel2 private
Definition at line 64 of file btbookshelfinstallfinalpage.h.
Referenced by BtBookshelfInstallFinalPage(), slotInstallStarted(), and slotThreadFinished().
m_progressBar
QProgressBar* BtBookshelfInstallFinalPage::m_progressBar private
Definition at line 65 of file btbookshelfinstallfinalpage.h.
Referenced by BtBookshelfInstallFinalPage(), initializePage(), slotOneItemCompleted(), slotStatusUpdated(), and slotThreadFinished().
m_stopButton
QPushButton* BtBookshelfInstallFinalPage::m_stopButton private
Definition at line 66 of file btbookshelfinstallfinalpage.h.
Referenced by BtBookshelfInstallFinalPage(), initializePage(), retranslateUi(), slotStopInstall(), and slotThreadFinished().
m_thread
BtInstallThread* BtBookshelfInstallFinalPage::m_thread = nullptr private
Definition at line 67 of file btbookshelfinstallfinalpage.h.
Referenced by destroyThread(), initializePage(), and slotStopInstall().
m_verticalLayout
QVBoxLayout* BtBookshelfInstallFinalPage::m_verticalLayout private
Definition at line 68 of file btbookshelfinstallfinalpage.h.
Referenced by BtBookshelfInstallFinalPage().
The documentation for this class was generated from the following files:
btbookshelfinstallfinalpage.h
btbookshelfinstallfinalpage.cpp