BibleTime: BtStandardWorksTab Class Reference
BtStandardWorksTab Class Reference
#include <btstandardworkstab.h>
Public Member Functions
BtStandardWorksTab (CSwordSettingsPage *parent)
void save ()
Protected Member Functions
void retranslateUi ()
Private Member Functions
STANDARD_WORKS_TAB_FIELD (standardBible)
STANDARD_WORKS_TAB_FIELD (standardCommentary)
STANDARD_WORKS_TAB_FIELD (standardDailyDevotional)
STANDARD_WORKS_TAB_FIELD (standardGreekMorphLexicon)
STANDARD_WORKS_TAB_FIELD (standardGreekStrongsLexicon)
STANDARD_WORKS_TAB_FIELD (standardHebrewMorphLexicon)
STANDARD_WORKS_TAB_FIELD (standardHebrewStrongsLexicon)
STANDARD_WORKS_TAB_FIELD (standardLexicon)
Private Attributes
QLabel * m_explanationLabel
Detailed Description
Definition at line 25 of file btstandardworkstab.h.
Constructor & Destructor Documentation
BtStandardWorksTab()
BtStandardWorksTab::BtStandardWorksTab (CSwordSettingsPage * parent)
Definition at line 29 of file btstandardworkstab.cpp.
References CSwordModuleInfo::DailyDevotionals, CSwordModuleInfo::FeatureGreekDef, CSwordModuleInfo::FeatureGreekParse, CSwordModuleInfo::FeatureHebrewDef, CSwordModuleInfo::FeatureHebrewParse, m_explanationLabel, retranslateUi(), and STANDARD_WORKS_TAB_ADD_ROW.
Member Function Documentation
retranslateUi()
void BtStandardWorksTab::retranslateUi () protected
Definition at line 140 of file btstandardworkstab.cpp.
References util::tool::initExplanationLabel(), and m_explanationLabel.
Referenced by BtStandardWorksTab().
save()
void BtStandardWorksTab::save ()
Definition at line 128 of file btstandardworkstab.cpp.
References STANDARD_WORKS_SET_DEFAULT.
Referenced by CSwordSettingsPage::save().
STANDARD_WORKS_TAB_FIELD() [1/8]
BtStandardWorksTab::STANDARD_WORKS_TAB_FIELD (standardBible) private
STANDARD_WORKS_TAB_FIELD() [2/8]
BtStandardWorksTab::STANDARD_WORKS_TAB_FIELD (standardCommentary) private
STANDARD_WORKS_TAB_FIELD() [3/8]
BtStandardWorksTab::STANDARD_WORKS_TAB_FIELD (standardDailyDevotional) private
STANDARD_WORKS_TAB_FIELD() [4/8]
BtStandardWorksTab::STANDARD_WORKS_TAB_FIELD (standardGreekMorphLexicon) private
STANDARD_WORKS_TAB_FIELD() [5/8]
BtStandardWorksTab::STANDARD_WORKS_TAB_FIELD (standardGreekStrongsLexicon) private
STANDARD_WORKS_TAB_FIELD() [6/8]
BtStandardWorksTab::STANDARD_WORKS_TAB_FIELD (standardHebrewMorphLexicon) private
STANDARD_WORKS_TAB_FIELD() [7/8]
BtStandardWorksTab::STANDARD_WORKS_TAB_FIELD (standardHebrewStrongsLexicon) private
STANDARD_WORKS_TAB_FIELD() [8/8]
BtStandardWorksTab::STANDARD_WORKS_TAB_FIELD (standardLexicon) private
Member Data Documentation
m_explanationLabel
QLabel* BtStandardWorksTab::m_explanationLabel private
Definition at line 41 of file btstandardworkstab.h.
Referenced by BtStandardWorksTab(), and retranslateUi().
The documentation for this class was generated from the following files:
btstandardworkstab.h
btstandardworkstab.cpp