BibleTime: anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase Class Reference
anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase Class Reference
Public Member Functions
BookmarkItemBase (BookmarkFolder *parent=nullptr)
BookmarkItemBase (const BookmarkItemBase &other)
virtual Qt::ItemFlags flags () const noexcept
virtual QIcon const & icon () const noexcept
int index () const
BookmarkFolder * parent () const
void setParent (BookmarkFolder *parent)
void setText (QString const &text)
QString const & text () const
virtual QString toolTip () const
virtual ~BookmarkItemBase ()
Private Attributes
BookmarkFolder * m_parent
QString m_text
Detailed Description
Definition at line 60 of file btbookmarksmodel.cpp.
Constructor & Destructor Documentation
BookmarkItemBase() [1/2]
anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::BookmarkItemBase (BookmarkFolder * parent = nullptr)
Definition at line 209 of file btbookmarksmodel.cpp.
References anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::addChild(), and m_parent.
BookmarkItemBase() [2/2]
anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::BookmarkItemBase (const BookmarkItemBase & other) inline
Definition at line 66 of file btbookmarksmodel.cpp.
~BookmarkItemBase()
virtual anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::~BookmarkItemBase () inline virtual
Definition at line 71 of file btbookmarksmodel.cpp.
Member Function Documentation
flags()
virtual Qt::ItemFlags anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::flags () const inline virtual noexcept
Reimplemented in anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem, and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder.
Definition at line 79 of file btbookmarksmodel.cpp.
icon()
virtual QIcon const & anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::icon () const inline virtual noexcept
Reimplemented in anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem, and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder.
Definition at line 81 of file btbookmarksmodel.cpp.
index()
int anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::index () const
Returns
index of this item in parent's child array.
Definition at line 216 of file btbookmarksmodel.cpp.
References BT_ASSERT, anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::children(), and m_parent.
parent()
BookmarkFolder * anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::parent () const inline
Definition at line 88 of file btbookmarksmodel.cpp.
setParent()
void anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::setParent (BookmarkFolder * parent) inline
Definition at line 86 of file btbookmarksmodel.cpp.
Referenced by anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::addChild(), and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkFolder::insertChild().
setText()
void anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::setText (QString const & text) inline
Definition at line 73 of file btbookmarksmodel.cpp.
Referenced by anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::BookmarkItem(), anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::BookmarkItem(), and BtBookmarksModelPrivate::handleXmlElement().
text()
QString const & anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::text () const inline
Definition at line 75 of file btbookmarksmodel.cpp.
Referenced by BtBookmarksModelPrivate::saveItem(), and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::toolTip().
toolTip()
virtual QString anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::toolTip () const inline virtual
Reimplemented in anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem.
Definition at line 77 of file btbookmarksmodel.cpp.
Member Data Documentation
m_parent
BookmarkFolder* anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::m_parent private
Definition at line 95 of file btbookmarksmodel.cpp.
Referenced by BookmarkItemBase(), and index().
m_text
QString anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItemBase::m_text private
Definition at line 96 of file btbookmarksmodel.cpp.
The documentation for this class was generated from the following file:
btbookmarksmodel.cpp