BibleTime: CDisplayWindow Class Reference
CDisplayWindow Class Reference
The base class for all display windows of BibleTime.
#include <cdisplaywindow.h>
Classes
struct ActionsStruct
Public Slots
void lookupKey (QString const &key)
virtual void reload (CSwordBackend::SetupChangedReason reason)
void slotAddModule (int index, QString module)
void slotRemoveModule (int index)
void slotReplaceModule (int index, QString newModule)
Signals
void sigDisplayOptionsChanged (const DisplayOptions &displayOptions)
void sigFilterOptionsChanged (const FilterOptions &filterOptions)
void sigKeyChanged (CSwordKey *key)
void sigModuleAdded (int index, QString module)
void sigModuleListChanged ()
void sigModuleListSet (QStringList modules)
void sigModuleRemoved (int index)
void sigModuleReplaced (int index, QString newModule)
void sigModulesChanged (const BtConstModuleList &modules)
Public Member Functions
BtActionCollection * actionCollection () const
virtual void applyProfileSettings (BtConfigCore const &windowConf)
Loads the settings of this window from configuration.
BibleTime * btMainWindow ()
QToolBar * buttonsToolBar () const
virtual void copyDisplayedText ()
const DisplayOptions & displayOptions () const
BtModelViewReadDisplay * displayWidget () const
const FilterOptions & filterOptions () const
int getFirstSelectedIndex () const
int getLastSelectedIndex () const
const QStringList & getModuleList () const
CSwordKey * getMouseClickedKey () const
int getSelectedColumn () const
bool hasSelectedText ()
BTHistory * history ()
bool init ()
bool isReady () const
CSwordKey * key () const
CKeyChooser * keyChooser () const
QToolBar * mainToolBar () const
CMDIArea * mdi () const
BtConstModuleList modules () const
virtual CSwordModuleInfo::ModuleType moduleType () const
void setButtonsToolBar (QToolBar *bar)
void setDisplaySettingsButton (BtDisplaySettingsButton *button)
void setDisplayWidget (BtModelViewReadDisplay *newDisplay)
void setMainToolBar (QToolBar *bar)
virtual void storeProfileSettings (BtConfigCore &windowConf) const
Stores the settings of this window to configuration.
virtual bool syncAllowed () const
void windowActivated ()
QString windowCaption ()
Static Public Member Functions
static void insertKeyboardActions (BtActionCollection *const a)
Protected Slots
void lookup ()
virtual void modulesChanged ()
void printAll ()
void printAnchorWithText ()
void saveRawHTML ()
Protected Member Functions
CDisplayWindow (const QList< CSwordModuleInfo * > &modules, CMDIArea *parent)
void clearMainWindowToolBars ()
QToolBar * headerBar () const
virtual void initActions ()
template<typename ... Args>
QAction & initAddAction (Args &&... args)
virtual void initConnections ()
virtual void initToolbars ()
virtual void initView ()
virtual void lookupSwordKey (CSwordKey *)
BtModuleChooserBar * moduleChooserBar () const
QMenu * popup ()
‍** Returns the installed popup menu. *‍/
void setDisplayOptions (DisplayOptions const &v)
void setFilterOptions (FilterOptions const &v)
void setKeyChooser (CKeyChooser *ck)
void setModuleChooserBar (BtModuleChooserBar *bar)
void setToolBarsHidden ()
virtual void setupMainWindowToolBars ()
virtual void setupPopupMenu ()
virtual void updatePopupMenu ()
~CDisplayWindow () override
Protected Attributes
struct CDisplayWindow::ActionsStruct m_actions
Private Member Functions
template<typename Name , typename ... Args>
QAction & initAction (Name &&name, Args &&... args)
Private Attributes
BtActionCollection * m_actionCollection
QToolBar * m_buttonsToolBar
DisplayOptions m_displayOptions
BtModelViewReadDisplay * m_displayWidget = nullptr
FilterOptions m_filterOptions
QToolBar * m_headerBar
BTHistory * m_history
bool m_isReady
CKeyChooser * m_keyChooser
QToolBar * m_mainToolBar
CMDIArea * m_mdi
BtModuleChooserBar * m_moduleChooserBar
QStringList m_modules
QMenu * m_popupMenu
CSwordKey * m_swordKey
Friends
class CBibleReadWindow
class CLexiconReadWindow
Detailed Description
The base class for all display windows of BibleTime.
Definition at line 42 of file cdisplaywindow.h.
Constructor & Destructor Documentation
CDisplayWindow()
CDisplayWindow::CDisplayWindow (const QList< CSwordModuleInfo * > & modules, CMDIArea * parent) protected
Definition at line 55 of file cdisplaywindow.cpp.
~CDisplayWindow()
CDisplayWindow::~CDisplayWindow () override protected
Definition at line 114 of file cdisplaywindow.cpp.
References m_swordKey.
Member Function Documentation
actionCollection()
BtActionCollection* CDisplayWindow::actionCollection () const inline
Definition at line 142 of file cdisplaywindow.h.
References m_actionCollection.
Referenced by CLexiconReadWindow::initActions(), CBibleReadWindow::initActions(), CBookReadWindow::initActions(), CCommentaryReadWindow::initActions(), CBookReadWindow::initToolbars(), initToolbars(), CLexiconReadWindow::reload(), CCommentaryReadWindow::reload(), CBibleReadWindow::reload(), reload(), CBookReadWindow::setupMainWindowToolBars(), and setupMainWindowToolBars().
applyProfileSettings()
void CDisplayWindow::applyProfileSettings (BtConfigCore const & windowConf) virtual
Loads the settings of this window from configuration.
Parameters
[in] windowConf The locked configuration group.
Note
We don't use restoreGeometry/saveGeometry for MDI subwindows, because they give slightly incorrect results with some window managers. Might be related to Qt bug QTBUG-7634.
Reimplemented in CBibleReadWindow, CBookReadWindow, and CCommentaryReadWindow.
Definition at line 191 of file cdisplaywindow.cpp.
References BT_ASSERT, anonymous_namespace{cdisplaywindow.cpp}::getProfileWindow(), and BtConfigCore::value().
Referenced by CCommentaryReadWindow::applyProfileSettings(), CBibleReadWindow::applyProfileSettings(), and CBookReadWindow::applyProfileSettings().
btMainWindow()
BibleTime * CDisplayWindow::btMainWindow ()
Return pointer to the BibleTime main window
Definition at line 122 of file cdisplaywindow.cpp.
References m_mdi.
Referenced by clearMainWindowToolBars(), init(), initActions(), lookupKey(), BtModelViewReadDisplay::openFindTextDialog(), setDisplayWidget(), CBookReadWindow::setupMainWindowToolBars(), CCommentaryReadWindow::setupMainWindowToolBars(), and setupMainWindowToolBars().
buttonsToolBar()
QToolBar* CDisplayWindow::buttonsToolBar () const inline
Returns the tool buttons toolbar.
Definition at line 113 of file cdisplaywindow.h.
References m_buttonsToolBar.
Referenced by CBookReadWindow::initToolbars(), CCommentaryReadWindow::initToolbars(), initToolbars(), CBookReadWindow::initView(), initView(), CBookReadWindow::setupMainWindowToolBars(), and setupMainWindowToolBars().
clearMainWindowToolBars()
void CDisplayWindow::clearMainWindowToolBars () protected
Definition at line 135 of file cdisplaywindow.cpp.
References btMainWindow(), BibleTime::navToolBar(), and BibleTime::toolsToolBar().
Referenced by init(), and windowActivated().
copyDisplayedText()
void CDisplayWindow::copyDisplayedText () virtual
Updates the status of the popup menu entries.
Definition at line 602 of file cdisplaywindow.cpp.
References CExportManager::copyKey(), m_swordKey, and CExportManager::Text.
displayOptions()
const DisplayOptions& CDisplayWindow::displayOptions () const inline
Returns the display options used by this display window.
Definition at line 77 of file cdisplaywindow.h.
References m_displayOptions.
Referenced by CBibleReadWindow::applyProfileSettings(), CBibleReadWindow::copyDisplayedText(), initActions(), lookupSwordKey(), BtModelViewReadDisplay::print(), CBibleReadWindow::saveChapter(), setDisplaySettingsButton(), and CBibleReadWindow::storeProfileSettings().
displayWidget()
BtModelViewReadDisplay* CDisplayWindow::displayWidget () const inline
Returns the display widget used by this implementation of CDisplayWindow.
Definition at line 119 of file cdisplaywindow.h.
References BT_ASSERT, and m_displayWidget.
Referenced by CMDIArea::findTextInActiveWindow(), BibleTime::getCurrentDisplay(), CMDIArea::highlightTextInActiveWindow(), CBibleReadWindow::initActions(), CBookReadWindow::initView(), and CBibleReadWindow::updatePopupMenu().
filterOptions()
const FilterOptions& CDisplayWindow::filterOptions () const inline
Returns the filter options used by this window.
Definition at line 80 of file cdisplaywindow.h.
References m_filterOptions.
Referenced by CBibleReadWindow::applyProfileSettings(), CBibleReadWindow::copyDisplayedText(), initActions(), lookupSwordKey(), BtModelViewReadDisplay::print(), CBibleReadWindow::saveChapter(), setDisplaySettingsButton(), and CBibleReadWindow::storeProfileSettings().
getFirstSelectedIndex()
int CDisplayWindow::getFirstSelectedIndex () const
Definition at line 611 of file cdisplaywindow.cpp.
References BtQuickWidget::getFirstSelectedIndex(), m_displayWidget, and BtModelViewReadDisplay::quickWidget().
Referenced by BtCopyByReferencesDialog::BtCopyByReferencesDialog().
getLastSelectedIndex()
int CDisplayWindow::getLastSelectedIndex () const
Definition at line 617 of file cdisplaywindow.cpp.
References BtQuickWidget::getLastSelectedIndex(), m_displayWidget, and BtModelViewReadDisplay::quickWidget().
Referenced by BtCopyByReferencesDialog::BtCopyByReferencesDialog().
getModuleList()
const QStringList& CDisplayWindow::getModuleList () const inline
Returns the used modules as a string list.
Definition at line 62 of file cdisplaywindow.h.
References m_modules.
Referenced by initToolbars(), CBookReadWindow::initView(), initView(), CBookReadWindow::setupMainWindowToolBars(), setupMainWindowToolBars(), BtTextWindowHeader::slotBackendModulesChanged(), BtModuleChooserBar::slotBackendModulesChanged(), BtTextWindowHeader::slotWindowModulesChanged(), and BtModuleChooserBar::slotWindowModulesChanged().
getMouseClickedKey()
CSwordKey * CDisplayWindow::getMouseClickedKey () const
Definition at line 623 of file cdisplaywindow.cpp.
References m_displayWidget.
Referenced by CBibleReadWindow::saveChapter().
getSelectedColumn()
int CDisplayWindow::getSelectedColumn () const
Definition at line 605 of file cdisplaywindow.cpp.
References BtQuickWidget::getSelectedColumn(), m_displayWidget, and BtModelViewReadDisplay::quickWidget().
Referenced by BtCopyByReferencesDialog::BtCopyByReferencesDialog().
hasSelectedText()
bool CDisplayWindow::hasSelectedText ()
Definition at line 596 of file cdisplaywindow.cpp.
References BtQmlInterface::hasSelectedText(), m_displayWidget, and BtModelViewReadDisplay::qmlInterface().
Referenced by CBibleReadWindow::updatePopupMenu(), and updatePopupMenu().
headerBar()
QToolBar* CDisplayWindow::headerBar () const inline protected
Definition at line 228 of file cdisplaywindow.h.
References m_headerBar.
Referenced by initToolbars(), and initView().
history()
BTHistory * CDisplayWindow::history ()
Returns history for this window
Definition at line 694 of file cdisplaywindow.cpp.
References m_history.
Referenced by BtCopyByReferencesDialog::BtCopyByReferencesDialog(), initActions(), initConnections(), CBookReadWindow::initView(), initView(), CBookReadWindow::setupMainWindowToolBars(), and setupMainWindowToolBars().
init()
bool CDisplayWindow::init ()
Initialize the window. Call this method from the outside, because calling this in the constructor is not possible!
Definition at line 752 of file cdisplaywindow.cpp.
References btConfig(), btMainWindow(), clearMainWindowToolBars(), BibleTime::clearMdiToolBars(), initActions(), initConnections(), initToolbars(), initView(), m_displayOptions, m_filterOptions, m_isReady, modules(), setToolBarsHidden(), setupPopupMenu(), sigDisplayOptionsChanged(), sigFilterOptionsChanged(), sigModulesChanged(), and windowCaption().
Referenced by BibleTime::createReadDisplayWindow().
initAction()
template<typename Name , typename ... Args> QAction& CDisplayWindow::initAction (Name && name, Args &&... args) inline private
Definition at line 272 of file cdisplaywindow.h.
References BtActionCollection::action(), BT_CONNECT, and m_actionCollection.
Referenced by initActions(), and initAddAction().
initActions()
void CDisplayWindow::initActions () protected virtual
Initializes the internel keyboard actions.
Reimplemented in CCommentaryReadWindow, CBibleReadWindow, CBookReadWindow, and CLexiconReadWindow.
Definition at line 284 of file cdisplaywindow.cpp.
References CResMgr::mainMenu::view::showMainIndex::actionName, CResMgr::displaywindows::general::backInHistory::actionName, CResMgr::displaywindows::general::forwardInHistory::actionName, CResMgr::displaywindows::general::findStrongs::actionName, BTHistory::back(), CDisplayWindow::ActionsStruct::backInHistory, btConfig(), btMainWindow(), CDisplayWindow::ActionsStruct::byReferences, CDisplayWindow::ActionsStruct::copy, BtModelViewReadDisplay::copyAll(), BtModelViewReadDisplay::copyAnchorOnly(), BtModelViewReadDisplay::copyByReferences(), BtModelViewReadDisplay::copySelectedText(), displayOptions(), CDisplayWindow::ActionsStruct::entry, CDisplayWindow::ActionsStruct::entryAsHTML, CDisplayWindow::ActionsStruct::entryAsPlain, filterOptions(), CDisplayWindow::ActionsStruct::findStrongs, CDisplayWindow::ActionsStruct::findText, CDisplayWindow::ActionsStruct::forwardInHistory, BTHistory::fw(), BtModelViewReadDisplay::getCurrentNodeInfo(), history(), CExportManager::HTML, initAction(), initAddAction(), insertKeyboardActions(), BibleTime::instance(), keyChooser(), m_actionCollection, m_actions, m_displayWidget, m_swordKey, modules(), BtModelViewReadDisplay::openFindTextDialog(), BibleTime::openSearchDialog(), BtModelViewReadDisplay::pageDown(), BtModelViewReadDisplay::pageUp(), CDisplayWindow::ActionsStruct::print, printAll(), printAnchorWithText(), BtActionCollection::readShortcuts(), CDisplayWindow::ActionsStruct::reference, CDisplayWindow::ActionsStruct::save, CExportManager::saveKey(), CDisplayWindow::ActionsStruct::selectedText, and CExportManager::Text.
Referenced by init(), CLexiconReadWindow::initActions(), CBookReadWindow::initActions(), CBibleReadWindow::initActions(), and CCommentaryReadWindow::initActions().
initAddAction()
template<typename ... Args> QAction& CDisplayWindow::initAddAction (Args &&... args) inline protected
Definition at line 207 of file cdisplaywindow.h.
References initAction().
Referenced by CLexiconReadWindow::initActions(), CBibleReadWindow::initActions(), CCommentaryReadWindow::initActions(), and initActions().
initConnections()
void CDisplayWindow::initConnections () protected virtual
Initializes the signal / slot connections of this display window.
Reimplemented in CBookReadWindow.
Definition at line 416 of file cdisplaywindow.cpp.
References CDisplayWindow::ActionsStruct::backInHistory, BT_ASSERT, BT_CONNECT, CDisplayWindow::ActionsStruct::forwardInHistory, history(), BTHistory::historyChanged(), CKeyChooser::keyChanged(), keyChooser(), lookupSwordKey(), m_actions, BTHistory::move(), and BtToolBarPopupAction::popupMenu().
Referenced by init(), and CBookReadWindow::initConnections().
initToolbars()
void CDisplayWindow::initToolbars () protected virtual
Initialize the toolbars.
Reimplemented in CCommentaryReadWindow, and CBookReadWindow.
Definition at line 492 of file cdisplaywindow.cpp.
References actionCollection(), CResMgr::displaywindows::general::search::actionName, CDisplayWindow::ActionsStruct::backInHistory, BT_ASSERT, buttonsToolBar(), CDisplayWindow::ActionsStruct::forwardInHistory, getModuleList(), headerBar(), keyChooser(), m_actions, mainToolBar(), modules(), and setDisplaySettingsButton().
Referenced by init(), and CCommentaryReadWindow::initToolbars().
initView()
void CDisplayWindow::initView () protected virtual
Initialize the view of this display window.
Reimplemented in CBookReadWindow, and CBibleReadWindow.
Definition at line 455 of file cdisplaywindow.cpp.
References btConfig(), buttonsToolBar(), CKeyChooser::createInstance(), util::tool::getIconForModule(), getModuleList(), headerBar(), history(), m_displayWidget, m_headerBar, m_swordKey, mainToolBar(), moduleChooserBar(), modules(), setButtonsToolBar(), setDisplayWidget(), setKeyChooser(), setMainToolBar(), setModuleChooserBar(), BtModuleChooserBar::setModules(), and BtModelViewReadDisplay::view().
Referenced by init(), and CBibleReadWindow::initView().
insertKeyboardActions()
void CDisplayWindow::insertKeyboardActions (BtActionCollection *const a) static
Insert the keyboard accelerators of this window into the given actioncollection.
Definition at line 215 of file cdisplaywindow.cpp.
References CResMgr::displaywindows::general::findStrongs::accel, CResMgr::displaywindows::general::search::accel, CResMgr::displaywindows::general::backInHistory::accel, CResMgr::displaywindows::general::forwardInHistory::accel, CResMgr::displaywindows::general::search::actionName, CResMgr::displaywindows::general::backInHistory::actionName, CResMgr::displaywindows::general::forwardInHistory::actionName, CResMgr::displaywindows::general::findStrongs::actionName, and BtActionCollection::addAction().
Referenced by initActions().
isReady()
bool CDisplayWindow::isReady () const inline
Returns true if the widget is ready for use.
Definition at line 83 of file cdisplaywindow.h.
References m_isReady.
Referenced by lookupKey(), and lookupSwordKey().
key()
CSwordKey* CDisplayWindow::key () const inline
Returns the key of this display window.
Definition at line 92 of file cdisplaywindow.h.
References BT_ASSERT, and m_swordKey.
Referenced by CBookReadWindow::initView(), CCommentaryReadWindow::nextBook(), CBibleReadWindow::nextBook(), CCommentaryReadWindow::nextChapter(), CBibleReadWindow::nextChapter(), CCommentaryReadWindow::nextVerse(), CBibleReadWindow::nextVerse(), CCommentaryReadWindow::previousBook(), CBibleReadWindow::previousBook(), CCommentaryReadWindow::previousChapter(), CBibleReadWindow::previousChapter(), CCommentaryReadWindow::previousVerse(), CBibleReadWindow::previousVerse(), BtModelViewReadDisplay::print(), CBibleReadWindow::saveChapter(), CBookReadWindow::setupMainWindowToolBars(), CBibleReadWindow::syncWindows(), BtModelViewReadDisplay::text(), CCommentaryReadWindow::verseKey(), and CBibleReadWindow::verseKey().
keyChooser()
CKeyChooser* CDisplayWindow::keyChooser () const inline
Returns the keychooser widget of this display window.
Definition at line 89 of file cdisplaywindow.h.
References m_keyChooser.
Referenced by initActions(), CBookReadWindow::initConnections(), initConnections(), CBookReadWindow::initToolbars(), initToolbars(), lookupKey(), modulesChanged(), CCommentaryReadWindow::nextBook(), CBibleReadWindow::nextBook(), CCommentaryReadWindow::nextChapter(), CBibleReadWindow::nextChapter(), CLexiconReadWindow::nextEntry(), CCommentaryReadWindow::nextVerse(), CBibleReadWindow::nextVerse(), CCommentaryReadWindow::previousBook(), CBibleReadWindow::previousBook(), CCommentaryReadWindow::previousChapter(), CBibleReadWindow::previousChapter(), CLexiconReadWindow::previousEntry(), CCommentaryReadWindow::previousVerse(), CBibleReadWindow::previousVerse(), CCommentaryReadWindow::reload(), CBibleReadWindow::reload(), reload(), CBookReadWindow::setupMainWindowToolBars(), and setupMainWindowToolBars().
lookup
void CDisplayWindow::lookup () protected slot
Lookup the current key. Used to refresh the display. This also needs to be called after programmatically changing filter/display options.
Lookup the current key. Used to refresh the display.
Definition at line 830 of file cdisplaywindow.cpp.
References lookupSwordKey(), and m_swordKey.
Referenced by CBibleReadWindow::applyProfileSettings(), reload(), setDisplaySettingsButton(), slotAddModule(), slotRemoveModule(), and slotReplaceModule().
lookupKey
void CDisplayWindow::lookupKey (QString const & key) slot
Lookup the key in the chosen modules.
Todo:
check if this is correct behavior
Todo:
check for containsRef compat
Definition at line 832 of file cdisplaywindow.cpp.
References BT_ASSERT, btMainWindow(), BibleTime::createReadDisplayWindow(), CSwordBackend::findModuleByName(), CSwordBackend::instance(), isReady(), keyChooser(), m_swordKey, modules(), CSwordKey::setKey(), CKeyChooser::setKey(), and sigKeyChanged().
Referenced by BibleTime::createReadDisplayWindow(), and CBibleReadWindow::syncWindows().
lookupSwordKey()
void CDisplayWindow::lookupSwordKey (CSwordKey * newKey) protected virtual
Lookup the given key.
Todo:
next-TODO how about options?
Definition at line 715 of file cdisplaywindow.cpp.
References BibleTime::autoScrollStop(), BT_ASSERT, displayOptions(), filterOptions(), BibleTime::instance(), isReady(), CSwordKey::key(), m_displayWidget, m_swordKey, modules(), BtModelViewReadDisplay::scrollToKey(), BtModelViewReadDisplay::setDisplayOptions(), BtModelViewReadDisplay::setFilterOptions(), CSwordKey::setKey(), and windowCaption().
Referenced by CBookReadWindow::initConnections(), initConnections(), lookup(), CBibleReadWindow::lookupSwordKey(), CBookReadWindow::setupMainWindowToolBars(), and setupMainWindowToolBars().
mainToolBar()
QToolBar* CDisplayWindow::mainToolBar () const inline
Returns the main navigation toolbar.
Definition at line 110 of file cdisplaywindow.h.
References m_mainToolBar.
Referenced by CBookReadWindow::initToolbars(), initToolbars(), CBookReadWindow::initView(), and initView().
mdi()
CMDIArea* CDisplayWindow::mdi () const inline
Returns pointer to the mdi area object.
Definition at line 53 of file cdisplaywindow.h.
References m_mdi.
Referenced by storeProfileSettings(), and CBibleReadWindow::syncWindows().
moduleChooserBar()
BtModuleChooserBar* CDisplayWindow::moduleChooserBar () const inline protected
Returns the module chooser bar.
Definition at line 220 of file cdisplaywindow.h.
References m_moduleChooserBar.
Referenced by CBookReadWindow::initView(), and initView().
modules()
BtConstModuleList CDisplayWindow::modules () const
Returns the used modules as a pointer list.
Returns the used modules as a pointer list
Definition at line 155 of file cdisplaywindow.cpp.
References CSwordBackend::getConstPointerList(), CSwordBackend::instance(), and m_modules.
Referenced by BtCopyByReferencesDialog::BtCopyByReferencesDialog(), CBibleReadWindow::copyDisplayedText(), BibleTime::getCurrentModule(), init(), initActions(), initToolbars(), CBookReadWindow::initView(), initView(), lookupKey(), lookupSwordKey(), CBookReadWindow::modulesChanged(), modulesChanged(), reload(), CBibleReadWindow::saveChapter(), setDisplaySettingsButton(), CBookReadWindow::setupMainWindowToolBars(), setupMainWindowToolBars(), CBibleReadWindow::setupPopupMenu(), setupPopupMenu(), and BibleTime::slotSearchModules().
modulesChanged
void CDisplayWindow::modulesChanged () protected virtual slot
Definition at line 700 of file cdisplaywindow.cpp.
References keyChooser(), m_swordKey, modules(), CSwordKey::setModule(), CKeyChooser::setModules(), and sigModulesChanged().
Referenced by CBookReadWindow::modulesChanged(), slotAddModule(), slotRemoveModule(), and slotReplaceModule().
moduleType()
CSwordModuleInfo::ModuleType CDisplayWindow::moduleType () const virtual
Reimplemented in CBibleReadWindow, CBookReadWindow, and CCommentaryReadWindow.
Definition at line 119 of file cdisplaywindow.cpp.
References CSwordModuleInfo::Lexicon.
popup()
QMenu * CDisplayWindow::popup () protected
‍** Returns the installed popup menu. *‍/
Returns the installed RMB popup menu.
Definition at line 864 of file cdisplaywindow.cpp.
References BT_CONNECT, BtModelViewReadDisplay::installPopup(), m_displayWidget, m_popupMenu, and updatePopupMenu().
Referenced by CBibleReadWindow::setupPopupMenu(), and setupPopupMenu().
printAll
void CDisplayWindow::printAll () protected slot
Definition at line 890 of file cdisplaywindow.cpp.
References m_displayOptions, m_displayWidget, m_filterOptions, and BtModelViewReadDisplay::printAll().
Referenced by CBibleReadWindow::initActions(), and initActions().
printAnchorWithText
void CDisplayWindow::printAnchorWithText () protected slot
Definition at line 893 of file cdisplaywindow.cpp.
References m_displayOptions, m_displayWidget, m_filterOptions, and BtModelViewReadDisplay::printAnchorWithText().
Referenced by CBibleReadWindow::initActions(), and initActions().
reload
void CDisplayWindow::reload (CSwordBackend::SetupChangedReason reason) virtual slot
Refresh the settings of this window.
Definition at line 632 of file cdisplaywindow.cpp.
References actionCollection(), BtInstallBackend::backend(), CSwordBackend::instance(), keyChooser(), lookup(), m_actionCollection, m_displayWidget, m_modules, modules(), BtActionCollection::readShortcuts(), BtModelViewReadDisplay::reloadModules(), BtModelViewReadDisplay::settingsChanged(), and sigModuleListSet().
Referenced by anonymous_namespace{cdisplaywindow.cpp}::getProfileWindow(), CLexiconReadWindow::reload(), CCommentaryReadWindow::reload(), and CBibleReadWindow::reload().
saveRawHTML
void CDisplayWindow::saveRawHTML () protected slot
Saving the raw HTML for debugging purposes
Definition at line 897 of file cdisplaywindow.cpp.
References BtModelViewReadDisplay::getCurrentSource(), m_displayWidget, BtInstallBackend::source(), and Rendering::Text.
Referenced by CBibleReadWindow::setupPopupMenu(), and setupPopupMenu().
setButtonsToolBar()
void CDisplayWindow::setButtonsToolBar (QToolBar * bar)
Sets and inits the properties of the tool buttons toolbar.
Setup the Tools toolbar.
Definition at line 794 of file cdisplaywindow.cpp.
References btConfig(), m_buttonsToolBar, and prepareToolBar().
Referenced by CBookReadWindow::initView(), and initView().
setDisplayOptions()
void CDisplayWindow::setDisplayOptions (DisplayOptions const & v) inline protected
Definition at line 202 of file cdisplaywindow.h.
References m_displayOptions.
Referenced by CBibleReadWindow::applyProfileSettings().
setDisplaySettingsButton()
void CDisplayWindow::setDisplaySettingsButton (BtDisplaySettingsButton * button)
Sets the display settings button.
Definition at line 800 of file cdisplaywindow.cpp.
References BT_CONNECT, displayOptions(), filterOptions(), lookup(), m_displayOptions, m_displayWidget, m_filterOptions, modules(), BtDisplaySettingsButton::setDisplayOptions(), BtModelViewReadDisplay::setDisplayOptions(), BtDisplaySettingsButton::setDisplayOptionsNoRepopulate(), BtDisplaySettingsButton::setFilterOptions(), BtDisplaySettingsButton::setFilterOptionsNoRepopulate(), BtDisplaySettingsButton::setModules(), BtDisplaySettingsButton::sigChanged(), BtDisplaySettingsButton::sigDisplayOptionsChanged(), sigDisplayOptionsChanged(), BtDisplaySettingsButton::sigFilterOptionsChanged(), sigFilterOptionsChanged(), and sigModulesChanged().
Referenced by CBookReadWindow::initToolbars(), initToolbars(), CBookReadWindow::setupMainWindowToolBars(), and setupMainWindowToolBars().
setDisplayWidget()
void CDisplayWindow::setDisplayWidget (BtModelViewReadDisplay * newDisplay)
Sets the display widget used by this display window.
Definition at line 877 of file cdisplaywindow.cpp.
References BT_ASSERT, BT_CONNECT, btMainWindow(), BtQmlInterface::changeColorTheme(), BibleTime::colorThemeChanged(), m_displayWidget, and BtModelViewReadDisplay::qmlInterface().
Referenced by CBookReadWindow::initView(), and initView().
setFilterOptions()
void CDisplayWindow::setFilterOptions (FilterOptions const & v) inline protected
Definition at line 204 of file cdisplaywindow.h.
References m_filterOptions.
Referenced by CBibleReadWindow::applyProfileSettings().
setKeyChooser()
void CDisplayWindow::setKeyChooser (CKeyChooser * ck) protected
Sets the keychooser widget for this display window.
Definition at line 690 of file cdisplaywindow.cpp.
References m_keyChooser.
Referenced by CBookReadWindow::initView(), and initView().
setMainToolBar()
void CDisplayWindow::setMainToolBar (QToolBar * bar)
Sets and inits the properties of the main navigation toolbar.
Setup the Navigation toolbar.
Definition at line 788 of file cdisplaywindow.cpp.
References btConfig(), m_mainToolBar, and prepareToolBar().
Referenced by CBookReadWindow::initView(), and initView().
setModuleChooserBar()
void CDisplayWindow::setModuleChooserBar (BtModuleChooserBar * bar) protected
Sets the module chooser bar.
Definition at line 737 of file cdisplaywindow.cpp.
References btConfig(), and m_moduleChooserBar.
Referenced by CBookReadWindow::initView(), and initView().
setToolBarsHidden()
void CDisplayWindow::setToolBarsHidden () protected
Definition at line 126 of file cdisplaywindow.cpp.
References m_buttonsToolBar, m_mainToolBar, and m_moduleChooserBar.
Referenced by init().
setupMainWindowToolBars()
void CDisplayWindow::setupMainWindowToolBars () protected virtual
Called to add actions to mainWindow toolbars
Reimplemented in CCommentaryReadWindow, and CBookReadWindow.
Definition at line 567 of file cdisplaywindow.cpp.
References actionCollection(), CResMgr::displaywindows::general::search::actionName, CDisplayWindow::ActionsStruct::backInHistory, BT_CONNECT, btMainWindow(), buttonsToolBar(), CKeyChooser::createInstance(), CDisplayWindow::ActionsStruct::forwardInHistory, getModuleList(), history(), CSwordKey::key(), CKeyChooser::key(), CKeyChooser::keyChanged(), keyChooser(), lookupSwordKey(), m_actions, m_swordKey, modules(), BibleTime::navToolBar(), setDisplaySettingsButton(), CSwordKey::setKey(), BtModuleChooserBar::setModules(), sigKeyChanged(), BibleTime::toolsToolBar(), CKeyChooser::updateKey(), and BibleTime::worksToolBar().
Referenced by CCommentaryReadWindow::setupMainWindowToolBars(), and windowActivated().
setupPopupMenu()
void CDisplayWindow::setupPopupMenu () protected virtual
Reimplemented in CBibleReadWindow.
Definition at line 513 of file cdisplaywindow.cpp.
References BT_CONNECT, btApp, CDisplayWindow::ActionsStruct::byReferences, CDisplayWindow::ActionsStruct::copy, CDisplayWindow::ActionsStruct::copyMenu, CDisplayWindow::ActionsStruct::entry, CDisplayWindow::ActionsStruct::entryAsHTML, CDisplayWindow::ActionsStruct::entryAsPlain, CDisplayWindow::ActionsStruct::findStrongs, CDisplayWindow::ActionsStruct::findText, util::tool::getIconForModule(), m_actions, modules(), popup(), CDisplayWindow::ActionsStruct::print, CDisplayWindow::ActionsStruct::printMenu, CDisplayWindow::ActionsStruct::reference, CDisplayWindow::ActionsStruct::save, CDisplayWindow::ActionsStruct::saveMenu, saveRawHTML(), and CDisplayWindow::ActionsStruct::selectedText.
Referenced by init().
sigDisplayOptionsChanged
void CDisplayWindow::sigDisplayOptionsChanged (const DisplayOptions & displayOptions) signal
Signal emitted when display options are changed.
Referenced by CBibleReadWindow::applyProfileSettings(), init(), and setDisplaySettingsButton().
sigFilterOptionsChanged
void CDisplayWindow::sigFilterOptionsChanged (const FilterOptions & filterOptions) signal
Signal emitted when display options are changed.
Referenced by CBibleReadWindow::applyProfileSettings(), init(), and setDisplaySettingsButton().
sigKeyChanged
void CDisplayWindow::sigKeyChanged (CSwordKey * key) signal
signal for sword key change
Referenced by lookupKey(), CBookReadWindow::setupMainWindowToolBars(), and setupMainWindowToolBars().
sigModuleAdded
void CDisplayWindow::sigModuleAdded (int index, QString module) signal
A module was added to this window.
sigModuleListChanged
void CDisplayWindow::sigModuleListChanged () signal
The module list of window changed but backend list didn't.
Referenced by BtTextWindowHeader::BtTextWindowHeader(), BtModuleChooserBar::setModules(), slotAddModule(), slotRemoveModule(), and slotReplaceModule().
sigModuleListSet
void CDisplayWindow::sigModuleListSet (QStringList modules) signal
The module list was set because backend was reloaded.
Referenced by BtTextWindowHeader::BtTextWindowHeader(), reload(), and BtModuleChooserBar::setModules().
sigModuleRemoved
void CDisplayWindow::sigModuleRemoved (int index) signal
sigModuleReplaced
void CDisplayWindow::sigModuleReplaced (int index, QString newModule) signal
sigModulesChanged
void CDisplayWindow::sigModulesChanged (const BtConstModuleList & modules) signal
signal for change of modules
Referenced by init(), modulesChanged(), and setDisplaySettingsButton().
slotAddModule
void CDisplayWindow::slotAddModule (int index, QString module) slot
Receives a signal telling that a module should be added.
Definition at line 662 of file cdisplaywindow.cpp.
References BT_ASSERT, lookup(), m_displayWidget, m_modules, modulesChanged(), BtModelViewReadDisplay::setModules(), and sigModuleListChanged().
Referenced by BtModuleChooserBar::addButton(), and BtTextWindowHeader::addWidget().
slotRemoveModule
void CDisplayWindow::slotRemoveModule (int index) slot
Definition at line 680 of file cdisplaywindow.cpp.
References BT_ASSERT, lookup(), m_displayWidget, m_modules, modulesChanged(), BtModelViewReadDisplay::setModules(), and sigModuleListChanged().
Referenced by BtModuleChooserBar::addButton(), and BtTextWindowHeader::addWidget().
slotReplaceModule
void CDisplayWindow::slotReplaceModule (int index, QString newModule) slot
Definition at line 671 of file cdisplaywindow.cpp.
References BT_ASSERT, lookup(), m_displayWidget, m_modules, modulesChanged(), BtModelViewReadDisplay::setModules(), and sigModuleListChanged().
Referenced by BtModuleChooserBar::addButton(), and BtTextWindowHeader::addWidget().
storeProfileSettings()
void CDisplayWindow::storeProfileSettings (BtConfigCore & conf) const virtual
Stores the settings of this window to configuration.
Parameters
[in] windowConf The locked configuration group.
Store the settings of this window in the given CProfileWindow object.
Note
We don't use saveGeometry/restoreGeometry for MDI subwindows, because they give slightly incorrect results with some window managers. Might be related to Qt bug QTBUG-7634.
Reimplemented in CBibleReadWindow, CBookReadWindow, and CCommentaryReadWindow.
Definition at line 159 of file cdisplaywindow.cpp.
References BT_ASSERT, anonymous_namespace{cdisplaywindow.cpp}::getProfileWindow(), m_modules, m_swordKey, mdi(), and BtConfigCore::setValue().
Referenced by BibleTime::saveProfile(), CCommentaryReadWindow::storeProfileSettings(), CBookReadWindow::storeProfileSettings(), and CBibleReadWindow::storeProfileSettings().
syncAllowed()
virtual bool CDisplayWindow::syncAllowed () const inline virtual
Returns whether syncs to the active window are allowed at this time for this display window
Returns
boolean value whether sync is allowed
Reimplemented in CCommentaryReadWindow.
Definition at line 131 of file cdisplaywindow.h.
Referenced by CBibleReadWindow::syncWindows().
updatePopupMenu()
void CDisplayWindow::updatePopupMenu () protected virtual
Update the status of the popup menu entries.
Reimplemented in CBibleReadWindow.
Definition at line 554 of file cdisplaywindow.cpp.
References CDisplayWindow::ActionsStruct::copy, CDisplayWindow::ActionsStruct::findStrongs, BtModelViewReadDisplay::getCurrentNodeInfo(), BtModelViewReadDisplay::hasActiveAnchor(), hasSelectedText(), m_actions, m_displayWidget, CDisplayWindow::ActionsStruct::print, CDisplayWindow::ActionsStruct::reference, and CDisplayWindow::ActionsStruct::selectedText.
Referenced by popup().
windowActivated()
void CDisplayWindow::windowActivated ()
Called when this window is activated
Definition at line 141 of file cdisplaywindow.cpp.
References clearMainWindowToolBars(), and setupMainWindowToolBars().
Referenced by anonymous_namespace{cmdiarea.cpp}::getDisplayWindow().
windowCaption()
QString CDisplayWindow::windowCaption ()
Returns the correct window caption.
Returns the right window caption.
Definition at line 147 of file cdisplaywindow.cpp.
References CSwordKey::key(), m_modules, and m_swordKey.
Referenced by init(), and lookupSwordKey().
Friends And Related Function Documentation
CBibleReadWindow
friend class CBibleReadWindow friend
Definition at line 197 of file cdisplaywindow.h.
CLexiconReadWindow
friend class CLexiconReadWindow friend
Definition at line 44 of file cdisplaywindow.h.
Member Data Documentation
m_actionCollection
BtActionCollection* CDisplayWindow::m_actionCollection private
Definition at line 306 of file cdisplaywindow.h.
Referenced by actionCollection(), initAction(), CLexiconReadWindow::initActions(), initActions(), and reload().
m_actions
struct CDisplayWindow::ActionsStruct CDisplayWindow::m_actions protected
Referenced by initActions(), initConnections(), CBookReadWindow::initToolbars(), initToolbars(), CBookReadWindow::setupMainWindowToolBars(), setupMainWindowToolBars(), setupPopupMenu(), and updatePopupMenu().
m_buttonsToolBar
QToolBar* CDisplayWindow::m_buttonsToolBar private
Definition at line 320 of file cdisplaywindow.h.
Referenced by buttonsToolBar(), setButtonsToolBar(), and setToolBarsHidden().
m_displayOptions
DisplayOptions CDisplayWindow::m_displayOptions private
Definition at line 313 of file cdisplaywindow.h.
Referenced by displayOptions(), init(), printAll(), printAnchorWithText(), setDisplayOptions(), and setDisplaySettingsButton().
m_displayWidget
BtModelViewReadDisplay* CDisplayWindow::m_displayWidget = nullptr private
Definition at line 323 of file cdisplaywindow.h.
Referenced by displayWidget(), getFirstSelectedIndex(), getLastSelectedIndex(), getMouseClickedKey(), getSelectedColumn(), hasSelectedText(), initActions(), initView(), lookupSwordKey(), popup(), printAll(), printAnchorWithText(), reload(), saveRawHTML(), setDisplaySettingsButton(), setDisplayWidget(), slotAddModule(), slotRemoveModule(), slotReplaceModule(), and updatePopupMenu().
m_filterOptions
FilterOptions CDisplayWindow::m_filterOptions private
Definition at line 312 of file cdisplaywindow.h.
Referenced by filterOptions(), init(), printAll(), printAnchorWithText(), setDisplaySettingsButton(), and setFilterOptions().
m_headerBar
QToolBar* CDisplayWindow::m_headerBar private
Definition at line 321 of file cdisplaywindow.h.
Referenced by headerBar(), and initView().
m_history
BTHistory* CDisplayWindow::m_history private
Definition at line 324 of file cdisplaywindow.h.
Referenced by history().
m_isReady
bool CDisplayWindow::m_isReady private
Definition at line 317 of file cdisplaywindow.h.
Referenced by init(), and isReady().
m_keyChooser
CKeyChooser* CDisplayWindow::m_keyChooser private
Definition at line 315 of file cdisplaywindow.h.
Referenced by keyChooser(), and setKeyChooser().
m_mainToolBar
QToolBar* CDisplayWindow::m_mainToolBar private
Definition at line 319 of file cdisplaywindow.h.
Referenced by mainToolBar(), setMainToolBar(), and setToolBarsHidden().
m_mdi
CMDIArea* CDisplayWindow::m_mdi private
Definition at line 307 of file cdisplaywindow.h.
Referenced by btMainWindow(), and mdi().
m_moduleChooserBar
BtModuleChooserBar* CDisplayWindow::m_moduleChooserBar private
Definition at line 318 of file cdisplaywindow.h.
Referenced by moduleChooserBar(), setModuleChooserBar(), and setToolBarsHidden().
m_modules
QStringList CDisplayWindow::m_modules private
Definition at line 310 of file cdisplaywindow.h.
Referenced by getModuleList(), modules(), CBibleReadWindow::reload(), reload(), slotAddModule(), slotRemoveModule(), slotReplaceModule(), storeProfileSettings(), and windowCaption().
m_popupMenu
QMenu* CDisplayWindow::m_popupMenu private
Definition at line 322 of file cdisplaywindow.h.
Referenced by popup().
m_swordKey
CSwordKey* CDisplayWindow::m_swordKey private
Definition at line 316 of file cdisplaywindow.h.
Referenced by copyDisplayedText(), initActions(), initView(), key(), CLexiconReadWindow::ldKey(), lookup(), lookupKey(), lookupSwordKey(), modulesChanged(), setupMainWindowToolBars(), storeProfileSettings(), windowCaption(), and ~CDisplayWindow().
The documentation for this class was generated from the following files:
cdisplaywindow.h
cdisplaywindow.cpp