BibleTime: BtBookmarksModelPrivate Class Reference
BtBookmarksModelPrivate Class Reference
Classes
class BookmarkFolder
class BookmarkItem
class BookmarkItemBase
Public Member Functions
BtBookmarksModelPrivate (BtBookmarksModel *parent)
BookmarkItemBase * handleXmlElement (QDomElement &element, BookmarkItemBase *parent)
BookmarkItemBase * item (const QModelIndex &index) const
template<typename T >
T * itemAs (QModelIndex const &index) const
QList< BookmarkItemBase * > loadTree (QString fileName=QString())
QString loadXmlFromFile (QString fileName=QString())
void needSave ()
void printItems () const
void saveItem (BookmarkItemBase *item, QDomElement &parentElement)
QString serializeTreeFromRootItem (BookmarkItemBase *rootItem)
~BtBookmarksModelPrivate ()
Static Public Member Functions
static QString defaultBookmarksFile ()
Public Attributes
BookmarkFolder * m_rootItem
QTimer m_saveTimer
BtBookmarksModel *const q_ptr
Static Public Attributes
static BtBookmarksModel * m_defaultModel = nullptr
Detailed Description
Definition at line 58 of file btbookmarksmodel.cpp.
Constructor & Destructor Documentation
BtBookmarksModelPrivate()
BtBookmarksModelPrivate::BtBookmarksModelPrivate (BtBookmarksModel * parent) inline
Definition at line 225 of file btbookmarksmodel.cpp.
References m_saveTimer.
~BtBookmarksModelPrivate()
BtBookmarksModelPrivate::~BtBookmarksModelPrivate () inline
Definition at line 232 of file btbookmarksmodel.cpp.
References m_rootItem.
Member Function Documentation
defaultBookmarksFile()
static QString BtBookmarksModelPrivate::defaultBookmarksFile () inline static
Definition at line 234 of file btbookmarksmodel.cpp.
References util::directory::getUserBaseDir().
Referenced by loadXmlFromFile(), and BtBookmarksModel::save().
handleXmlElement()
BookmarkItemBase* BtBookmarksModelPrivate::handleXmlElement (QDomElement & element, BookmarkItemBase * parent) inline
Create a new item from a document element.
Definition at line 324 of file btbookmarksmodel.cpp.
References BtBookmarksModelPrivate::BookmarkItem::setDescription(), BtBookmarksModelPrivate::BookmarkItem::setKey(), BtBookmarksModelPrivate::BookmarkItem::setModule(), and BtBookmarksModelPrivate::BookmarkItemBase::setText().
Referenced by loadTree().
item()
BookmarkItemBase* BtBookmarksModelPrivate::item (const QModelIndex & index) const inline
Definition at line 238 of file btbookmarksmodel.cpp.
References BT_ASSERT, and m_rootItem.
Referenced by BtBookmarksModelPrivate::BookmarkFolder::hasDescendant(), itemAs(), and saveItem().
itemAs()
template<typename T > T* BtBookmarksModelPrivate::itemAs (QModelIndex const & index) const inline
Definition at line 261 of file btbookmarksmodel.cpp.
References item().
loadTree()
QList<BookmarkItemBase *> BtBookmarksModelPrivate::loadTree (QString fileName = QString()) inline
Loads a list of items (with subitem trees) from a named file or from the default bookmarks file.
Definition at line 291 of file btbookmarksmodel.cpp.
References handleXmlElement(), and loadXmlFromFile().
loadXmlFromFile()
QString BtBookmarksModelPrivate::loadXmlFromFile (QString fileName = QString()) inline
Loads a bookmark XML document from a named file or from the default bookmarks file.
Definition at line 359 of file btbookmarksmodel.cpp.
References defaultBookmarksFile().
Referenced by loadTree().
needSave()
void BtBookmarksModelPrivate::needSave () inline
Definition at line 281 of file btbookmarksmodel.cpp.
References m_defaultModel, m_saveTimer, and q_ptr.
printItems()
void BtBookmarksModelPrivate::printItems () const inline
Test:
Definition at line 265 of file btbookmarksmodel.cpp.
References m_rootItem.
saveItem()
void BtBookmarksModelPrivate::saveItem (BookmarkItemBase * item, QDomElement & parentElement) inline
Writes one item to a document element.
Definition at line 401 of file btbookmarksmodel.cpp.
References BtBookmarksModelPrivate::BookmarkItemBase::child(), BtBookmarksModelPrivate::BookmarkItemBase::childCount(), CSwordModuleInfo::config(), CSwordModuleInfo::Description, BtBookmarksModelPrivate::BookmarkItem::description(), BtBookmarksModelPrivate::BookmarkItem::englishKey(), item(), BtBookmarksModelPrivate::BookmarkItem::module(), BtBookmarksModelPrivate::BookmarkItem::moduleName(), and BtBookmarksModelPrivate::BookmarkItemBase::text().
Referenced by serializeTreeFromRootItem().
serializeTreeFromRootItem()
QString BtBookmarksModelPrivate::serializeTreeFromRootItem (BookmarkItemBase * rootItem) inline
Takes one item and saves the tree which is under it to a named file or to the default bookmarks file, asking the user about overwriting if necessary.
Definition at line 382 of file btbookmarksmodel.cpp.
References BT_ASSERT, BtBookmarksModelPrivate::BookmarkItemBase::child(), BtBookmarksModelPrivate::BookmarkItemBase::childCount(), CURRENT_SYNTAX_VERSION, and saveItem().
Member Data Documentation
m_defaultModel
BtBookmarksModel * BtBookmarksModelPrivate::m_defaultModel = nullptr static
Definition at line 434 of file btbookmarksmodel.cpp.
Referenced by needSave().
m_rootItem
BookmarkFolder* BtBookmarksModelPrivate::m_rootItem
Definition at line 432 of file btbookmarksmodel.cpp.
Referenced by item(), printItems(), and ~BtBookmarksModelPrivate().
m_saveTimer
QTimer BtBookmarksModelPrivate::m_saveTimer
Definition at line 433 of file btbookmarksmodel.cpp.
Referenced by BtBookmarksModelPrivate(), and needSave().
q_ptr
BtBookmarksModel* const BtBookmarksModelPrivate::q_ptr
Definition at line 437 of file btbookmarksmodel.cpp.
Referenced by needSave().
The documentation for this class was generated from the following file:
btbookmarksmodel.cpp