BibleTime: BtTextFilter Class Reference
BtTextFilter Class Reference
This filter provides a method for modifying text generated by BtModuleTextModel.
#include <bttextfilter.h>
Public Member Functions
BtTextFilter ()
QString processText (const QString &text) override
void setShowReferences (bool on)
~BtTextFilter () override
Public Member Functions inherited from BtModuleTextFilter
virtual ~BtModuleTextFilter ()=0
Private Member Functions
void fixDoubleBR ()
QString fixNonRichText (const QString &text)
int rewriteFootnoteAsLink (int i, const QString &part)
int rewriteHref (int i, const QString &part)
int rewriteLemmaOrMorphAsLink (int i, const QString &part)
void splitText (const QString &text)
Private Attributes
QStringList m_parts
bool m_showReferences
Detailed Description
This filter provides a method for modifying text generated by BtModuleTextModel.
The "rich text" used by QML does not support attributes within a href tag. These attributes are added to the url so they can be obtained later for use of the MAG window. It also does some other miscellaneous processing.
Definition at line 31 of file bttextfilter.h.
Constructor & Destructor Documentation
BtTextFilter()
BtTextFilter::BtTextFilter ()
Definition at line 18 of file bttextfilter.cpp.
~BtTextFilter()
BtTextFilter::~BtTextFilter () override
Definition at line 22 of file bttextfilter.cpp.
Member Function Documentation
fixDoubleBR()
void BtTextFilter::fixDoubleBR () private
Definition at line 87 of file bttextfilter.cpp.
References m_parts.
Referenced by processText().
fixNonRichText()
QString BtTextFilter::fixNonRichText (const QString & text) private
Definition at line 57 of file bttextfilter.cpp.
Referenced by processText().
processText()
QString BtTextFilter::processText (const QString & text) override virtual
Implements BtModuleTextFilter.
Definition at line 25 of file bttextfilter.cpp.
References fixDoubleBR(), fixNonRichText(), m_parts, m_showReferences, rewriteFootnoteAsLink(), rewriteHref(), rewriteLemmaOrMorphAsLink(), and splitText().
rewriteFootnoteAsLink()
int BtTextFilter::rewriteFootnoteAsLink (int i, const QString & part) private
Definition at line 98 of file bttextfilter.cpp.
References m_parts.
Referenced by processText().
rewriteHref()
int BtTextFilter::rewriteHref (int i, const QString & part) private
Definition at line 121 of file bttextfilter.cpp.
References m_parts.
Referenced by processText().
rewriteLemmaOrMorphAsLink()
int BtTextFilter::rewriteLemmaOrMorphAsLink (int i, const QString & part) private
Definition at line 139 of file bttextfilter.cpp.
References m_parts.
Referenced by processText().
setShowReferences()
void BtTextFilter::setShowReferences (bool on)
Definition at line 164 of file bttextfilter.cpp.
References m_showReferences.
Referenced by BtQmlInterface::BtQmlInterface().
splitText()
void BtTextFilter::splitText (const QString & text) private
Definition at line 66 of file bttextfilter.cpp.
References m_parts.
Referenced by processText().
Member Data Documentation
m_parts
QStringList BtTextFilter::m_parts private
Definition at line 60 of file bttextfilter.h.
Referenced by fixDoubleBR(), processText(), rewriteFootnoteAsLink(), rewriteHref(), rewriteLemmaOrMorphAsLink(), and splitText().
m_showReferences
bool BtTextFilter::m_showReferences private
Definition at line 58 of file bttextfilter.h.
Referenced by processText(), and setShowReferences().
The documentation for this class was generated from the following files:
bttextfilter.h
bttextfilter.cpp