BibleTime: BtBookmarksModelPrivate::BookmarkFolder Class Reference
BtBookmarksModelPrivate::BookmarkFolder Class Reference
Public Member Functions
BookmarkFolder (const QString &name, BookmarkItemBase *parent=nullptr)
BookmarkFolder * deepCopy () const
QList< BookmarkItemBase * > getChildList () const
bool hasDescendant (BookmarkItemBase const *item) const
Public Member Functions inherited from BtBookmarksModelPrivate::BookmarkItemBase
void addChild (BookmarkItemBase *child)
BookmarkItemBase (BookmarkItemBase *parent=nullptr)
BookmarkItemBase (const BookmarkItemBase &other)
BookmarkItemBase * child (int index) const
int childCount () const
QList< BookmarkItemBase * > & children ()
Qt::ItemFlags flags () const
QIcon icon () const
int index () const
void insertChild (int index, BookmarkItemBase *child)
void insertChildren (int index, QList< BookmarkItemBase * > children)
BookmarkItemBase * parent () const
void removeChild (int index)
void setFlags (Qt::ItemFlags flags)
void setIcon (QIcon const &icon)
void setParent (BookmarkItemBase *parent)
void setText (QString const &text)
void setToolTip (QString const &tooltip)
const QString & text () const
virtual QString toolTip () const
virtual ~BookmarkItemBase ()
Detailed Description
Definition at line 206 of file btbookmarksmodel.cpp.
Constructor & Destructor Documentation
BookmarkFolder()
BookmarkFolder::BookmarkFolder (const QString & name, BookmarkItemBase * parent = nullptr)
Definition at line 448 of file btbookmarksmodel.cpp.
Referenced by deepCopy().
Member Function Documentation
deepCopy()
BookmarkFolder * BookmarkFolder::deepCopy () const
Creates a deep copy of this item.
Definition at line 476 of file btbookmarksmodel.cpp.
References BtBookmarksModelPrivate::BookmarkItemBase::addChild(), BookmarkFolder(), getChildList(), and BtBookmarksModelPrivate::BookmarkItemBase::text().
Referenced by BtBookmarksModel::copyItems().
getChildList()
QList< BookmarkItemBase * > BookmarkFolder::getChildList () const
Returns a list of direct childs of this item.
Definition at line 455 of file btbookmarksmodel.cpp.
References BtBookmarksModelPrivate::BookmarkItemBase::child(), and BtBookmarksModelPrivate::BookmarkItemBase::childCount().
Referenced by deepCopy(), and hasDescendant().
hasDescendant()
bool BookmarkFolder::hasDescendant (BookmarkItemBase const * item) const
Returns true if the given item is this or a direct or indirect subitem of this.
Definition at line 463 of file btbookmarksmodel.cpp.
References getChildList(), and BtBookmarksModelPrivate::item().
The documentation for this class was generated from the following file:
btbookmarksmodel.cpp