BibleTime: BtInstallBackend Namespace Reference
BtInstallBackend Namespace Reference
Functions
bool addSource (sword::InstallSource &source)
std::unique_ptr< CSwordBackend > backend (sword::InstallSource const &is)
QString configFilename ()
QString configPath ()
bool deleteSource (const QString &name)
void initPassiveFtpMode ()
bool isRemote (const sword::InstallSource &source)
bool setTargetList (const QStringList &targets)
sword::InstallSource source (const QString &name)
QStringList sourceNameList ()
QString swordConfigFilename ()
QDir swordDir ()
QStringList targetList ()
Function Documentation
addSource()
bool BtInstallBackend::addSource (sword::InstallSource & source)
Adds the source described by Source to the backend.
Adds the source to the backend.
Definition at line 46 of file btinstallbackend.cpp.
References configFilename(), isRemote(), and source().
Referenced by BtBookshelfSourcesPage::slotButtonClicked().
backend()
std::unique_ptr< CSwordBackend > BtInstallBackend::backend (sword::InstallSource const & is)
Returns backend Sword manager for the source.
Definition at line 281 of file btinstallbackend.cpp.
References isRemote(), and CSwordBackend::OtherChange.
Referenced by BtIndexDialog::createIndices(), BtIndexDialog::deleteIndices(), BibleTime::initBackends(), BtBookshelfLanguagesPage::initializeLanguages(), BtBookshelfWorksPage::initializePage(), BibleTime::moduleUnlock(), ReferenceManager::parseVerseReference(), CDisplayWindow::reload(), and BtInstallThread::removeModule().
configFilename()
QString BtInstallBackend::configFilename ()
Returns the name of the sword installer configuration file.
Definition at line 158 of file btinstallbackend.cpp.
References configPath().
Referenced by addSource(), deleteSource(), initPassiveFtpMode(), source(), and sourceNameList().
configPath()
QString BtInstallBackend::configPath ()
Returns the path of the sword installer configuration file.
Definition at line 154 of file btinstallbackend.cpp.
References util::directory::getUserHomeSwordDir().
Referenced by configFilename(), and CSwordBackend::Private::reloadConfig().
deleteSource()
bool BtInstallBackend::deleteSource (const QString & name)
Deletes the source.
Todo:
dummy
Definition at line 108 of file btinstallbackend.cpp.
References configFilename(), and source().
Referenced by BtBookshelfSourcesPage::slotButtonClicked().
initPassiveFtpMode()
void BtInstallBackend::initPassiveFtpMode ()
Sets the passive mode for as default.
Todo:
see if we can en/disable this per source.
Definition at line 252 of file btinstallbackend.cpp.
References configFilename().
isRemote()
bool BtInstallBackend::isRemote (const sword::InstallSource & source)
Tells if the source is remote or local.
Definition at line 147 of file btinstallbackend.cpp.
References source().
Referenced by addSource(), backend(), and BtInstallThread::installModule().
setTargetList()
bool BtInstallBackend::setTargetList (const QStringList & targets)
Saves the list of available install target paths to the sword config. Return success indicator.
Definition at line 167 of file btinstallbackend.cpp.
References util::directory::convertDirSeparators(), util::directory::getUserHomeDir(), CSwordBackend::instance(), CSwordBackend::PathChanged, CSwordBackend::reloadModules(), and swordConfigFilename().
source()
sword::InstallSource BtInstallBackend::source (const QString & name)
Returns the Source struct.
Returns the source struct.
Definition at line 73 of file btinstallbackend.cpp.
References configFilename().
Referenced by addSource(), CSwordSetupInstallSourcesDialog::CSwordSetupInstallSourcesDialog(), deleteSource(), BtBookshelfLanguagesPage::initializeLanguages(), BtBookshelfWorksPage::initializePage(), BtInstallThread::installModule(), isRemote(), BtInstallThread::removeModule(), BtSourcesThread::run(), CDisplayWindow::saveRawHTML(), and BtBookshelfSourcesPage::updateSourcesModel().
sourceNameList()
QStringList BtInstallBackend::sourceNameList ()
Definition at line 223 of file btinstallbackend.cpp.
References BT_ASSERT, and configFilename().
Referenced by BtBookshelfWorksPage::initializePage(), BtSourcesThread::run(), and BtBookshelfSourcesPage::updateSourcesModel().
swordConfigFilename()
QString BtInstallBackend::swordConfigFilename ()
Returns the file name for the Sword config file.
Definition at line 257 of file btinstallbackend.cpp.
References util::directory::getUserHomeDir().
Referenced by setTargetList().
swordDir()
QDir BtInstallBackend::swordDir ()
Returns the Sword directory ($HOME/.sword/) as a QDir, created with absolute path (not canonical).
Definition at line 271 of file btinstallbackend.cpp.
References util::directory::getUserHomeDir().
targetList()
QStringList BtInstallBackend::targetList ()
Returns the list of available install target paths.
Definition at line 162 of file btinstallbackend.cpp.
References CSwordBackend::instance(), and CSwordBackend::swordDirList().
Referenced by BtBookshelfWorksPage::slotInitPathCombo().