BibleTime: anonymous_namespace{cmdiarea.cpp} Namespace Reference
anonymous_namespace{cmdiarea.cpp} Namespace Reference
Functions
CDisplayWindow * getDisplayWindow (const QMdiSubWindow *const mdiWindow)
Function Documentation
getDisplayWindow()
CDisplayWindow* anonymous_namespace{cmdiarea.cpp}::getDisplayWindow (const QMdiSubWindow *const mdiWindow) inline
Definition at line 48 of file cmdiarea.cpp.
References BT_CONNECT, and CDisplayWindow::windowActivated().
Referenced by CMDIArea::findTextInActiveWindow(), and CMDIArea::highlightTextInActiveWindow().