BibleTime: btedittextwizard.cpp File Reference
btedittextwizard.cpp File Reference
#include "btedittextwizard.h"
#include <QByteArray>
#include <QDialog>
#include "btedittextpage.h"
#include "btplainorhtmlpage.h"
#include "../../backend/config/btconfig.h"
Namespaces
namespace anonymous_namespace{btedittextwizard.cpp}
Functions
void translateQWizardStandardButtons (QWizard *wizard)
Variables
auto const anonymous_namespace{btedittextwizard.cpp}::GeometryKey = QStringLiteral("GUI/EditTextWizard/geometry")
auto const anonymous_namespace{btedittextwizard.cpp}::HtmlModeKey = QStringLiteral("GUI/EditTextWizard/htmlMode")
Function Documentation
translateQWizardStandardButtons()
void translateQWizardStandardButtons (QWizard * wizard)
Definition at line 87 of file btbookshelfwizard.cpp.
References replaceButtonText().
Referenced by BtBookshelfWizard::retranslateUi(), and BtEditTextWizard::retranslateUi().