BibleTime: CSwordSetupInstallSourcesDialog Class Reference
CSwordSetupInstallSourcesDialog Class Reference final
#include <cswordsetupinstallsourcesdialog.h>
Public Member Functions
CSwordSetupInstallSourcesDialog ()
sword::InstallSource getSource ()
bool wasRemoteListAdded ()
Private Attributes
QLineEdit * m_captionEdit
QLineEdit * m_pathEdit
QComboBox * m_protocolCombo
bool m_remoteListAdded
QLineEdit * m_serverEdit
QLabel * m_serverLabel
Detailed Description
Definition at line 26 of file cswordsetupinstallsourcesdialog.h.
Constructor & Destructor Documentation
CSwordSetupInstallSourcesDialog()
CSwordSetupInstallSourcesDialog::CSwordSetupInstallSourcesDialog ()
Todo:
connect this directly to the dialog setValue(int) if possible:
Definition at line 52 of file cswordsetupinstallsourcesdialog.cpp.
References BT_CONNECT, anonymous_namespace{cswordsetupinstallsourcesdialog.cpp}::FTP, anonymous_namespace{cswordsetupinstallsourcesdialog.cpp}::HTTP, anonymous_namespace{cswordsetupinstallsourcesdialog.cpp}::HTTPS, anonymous_namespace{cswordsetupinstallsourcesdialog.cpp}::Local, m_captionEdit, m_pathEdit, m_protocolCombo, m_remoteListAdded, m_serverEdit, m_serverLabel, BtInstallMgr::percentCompleted(), message::prepareDialogBox(), anonymous_namespace{cswordsetupinstallsourcesdialog.cpp}::SFTP, message::showCritical(), message::showQuestion(), and BtInstallBackend::source().
Member Function Documentation
getSource()
sword::InstallSource CSwordSetupInstallSourcesDialog::getSource ()
Todo:
Add validator for server
Definition at line 225 of file cswordsetupinstallsourcesdialog.cpp.
References anonymous_namespace{cswordsetupinstallsourcesdialog.cpp}::FTP, anonymous_namespace{cswordsetupinstallsourcesdialog.cpp}::HTTP, anonymous_namespace{cswordsetupinstallsourcesdialog.cpp}::HTTPS, anonymous_namespace{cswordsetupinstallsourcesdialog.cpp}::Local, m_captionEdit, m_pathEdit, m_protocolCombo, m_serverEdit, and anonymous_namespace{cswordsetupinstallsourcesdialog.cpp}::SFTP.
Referenced by BtBookshelfSourcesPage::slotButtonClicked().
wasRemoteListAdded()
bool CSwordSetupInstallSourcesDialog::wasRemoteListAdded () inline
Definition at line 31 of file cswordsetupinstallsourcesdialog.h.
References m_remoteListAdded.
Referenced by BtBookshelfSourcesPage::slotButtonClicked().
Member Data Documentation
m_captionEdit
QLineEdit* CSwordSetupInstallSourcesDialog::m_captionEdit private
Definition at line 38 of file cswordsetupinstallsourcesdialog.h.
Referenced by CSwordSetupInstallSourcesDialog(), and getSource().
m_pathEdit
QLineEdit * CSwordSetupInstallSourcesDialog::m_pathEdit private
Definition at line 38 of file cswordsetupinstallsourcesdialog.h.
Referenced by CSwordSetupInstallSourcesDialog(), and getSource().
m_protocolCombo
QComboBox* CSwordSetupInstallSourcesDialog::m_protocolCombo private
Definition at line 39 of file cswordsetupinstallsourcesdialog.h.
Referenced by CSwordSetupInstallSourcesDialog(), and getSource().
m_remoteListAdded
bool CSwordSetupInstallSourcesDialog::m_remoteListAdded private
Definition at line 40 of file cswordsetupinstallsourcesdialog.h.
Referenced by CSwordSetupInstallSourcesDialog(), and wasRemoteListAdded().
m_serverEdit
QLineEdit * CSwordSetupInstallSourcesDialog::m_serverEdit private
Definition at line 38 of file cswordsetupinstallsourcesdialog.h.
Referenced by CSwordSetupInstallSourcesDialog(), and getSource().
m_serverLabel
QLabel* CSwordSetupInstallSourcesDialog::m_serverLabel private
Definition at line 37 of file cswordsetupinstallsourcesdialog.h.
Referenced by CSwordSetupInstallSourcesDialog().
The documentation for this class was generated from the following files:
cswordsetupinstallsourcesdialog.h
cswordsetupinstallsourcesdialog.cpp