BibleTime: anonymous_namespace{cdisplaywindow.cpp} Namespace Reference
anonymous_namespace{cdisplaywindow.cpp} Namespace Reference
Functions
QWidget * getProfileWindow (QWidget *w)
Function Documentation
getProfileWindow()
QWidget* anonymous_namespace{cdisplaywindow.cpp}::getProfileWindow (QWidget * w) inline
Definition at line 55 of file cdisplaywindow.cpp.
References BT_CONNECT, CSwordKey::createInstance(), CSwordBackend::instance(), CDisplayWindow::reload(), CSwordBackend::sigSwordSetupChanged(), BibleTime::toggledTextWindowHeader(), BibleTime::toggledTextWindowModuleChooser(), BibleTime::toggledTextWindowNavigator(), and BibleTime::toggledTextWindowToolButtons().
Referenced by CDisplayWindow::applyProfileSettings(), and CDisplayWindow::storeProfileSettings().