BibleTime: CResMgr::displaywindows::general::search Namespace Reference
CResMgr::displaywindows::general::search Namespace Reference
Functions
const QKeySequence accel (Qt::CTRL|Qt::Key_N)
Variables
const QKeySequence accel
QString const actionName = QStringLiteral("window_search_action")
Function Documentation
accel()
const QKeySequence CResMgr::displaywindows::general::search::accel (Qt::CTRL|Qt::Key_N)
Variable Documentation
accel
const QKeySequence CResMgr::displaywindows::general::search::accel extern
Referenced by CDisplayWindow::ActionCollection::ActionCollection().
actionName
QString const CResMgr::displaywindows::general::search::actionName = QStringLiteral("window_search_action")
Definition at line 24 of file cresmgr.cpp.
Referenced by CDisplayWindow::ActionCollection::ActionCollection(), CAcceleratorSettingsPage::CAcceleratorSettingsPage(), CDisplayWindow::CDisplayWindow(), CDisplayWindow::initToolbars(), CBookReadWindow::initToolbars(), CDisplayWindow::setupMainWindowToolBars(), and CBookReadWindow::setupMainWindowToolBars().