BibleTime: BtConfigDialog::Page Class Reference
BtConfigDialog::Page Class Reference abstract
#include <btconfigdialog.h>
Public Member Functions
Page (QIcon const &icon, QWidget *const parent=nullptr)
virtual void save () const =0
void setHeaderText (QString const &headerText)
~Page () noexcept override
Private Attributes
QListWidgetItem *const m_listWidgetItem
bool m_ownsListWidgetItem = true
Friends
class BtConfigDialog
Detailed Description
Base class for configuration dialog pages.
Definition at line 43 of file btconfigdialog.h.
Constructor & Destructor Documentation
Page()
BtConfigDialog::Page::Page (QIcon const & icon, QWidget *const parent = nullptr)
Definition at line 42 of file btconfigdialog.cpp.
References m_listWidgetItem.
~Page()
BtConfigDialog::Page::~Page () override noexcept
Definition at line 56 of file btconfigdialog.cpp.
Member Function Documentation
save()
virtual void BtConfigDialog::Page::save () const pure virtual
Implemented in BtFontSettingsPage, CAcceleratorSettingsPage, CDisplaySettingsPage, and CSwordSettingsPage.
setHeaderText()
void BtConfigDialog::Page::setHeaderText (QString const & headerText)
Definition at line 61 of file btconfigdialog.cpp.
Referenced by BtFontSettingsPage::retranslateUi(), CAcceleratorSettingsPage::retranslateUi(), CDisplaySettingsPage::retranslateUi(), and CSwordSettingsPage::retranslateUi().
Friends And Related Symbol Documentation
BtConfigDialog
friend class BtConfigDialog friend
Definition at line 45 of file btconfigdialog.h.
Member Data Documentation
m_listWidgetItem
QListWidgetItem* const BtConfigDialog::Page::m_listWidgetItem private
Definition at line 58 of file btconfigdialog.h.
Referenced by BtConfigDialog::addPage(), and Page().
m_ownsListWidgetItem
bool BtConfigDialog::Page::m_ownsListWidgetItem = true private
Definition at line 59 of file btconfigdialog.h.
Referenced by BtConfigDialog::addPage().
The documentation for this class was generated from the following files:
btconfigdialog.h
btconfigdialog.cpp