BibleTime: BtBookshelfWidget Class Reference
BtBookshelfWidget Class Reference
#include <btbookshelfwidget.h>
Public Member Functions
BtBookshelfWidget (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
QMenu * contextMenu () const
bool eventFilter (QObject *object, QEvent *event) override
QToolButton * groupingButton () const
BtBookshelfGroupingMenu * groupingMenu () const
QMenu * itemContextMenu () const
QWidget * leftCornerWidget () const
void loadBookshelfState ()
QLineEdit * nameFilterEdit () const
QLabel * nameFilterLabel () const
BtBookshelfFilterModel * postFilterModel () const
QWidget * rightCornerWidget () const
void saveBookshelfState ()
void setContextMenu (QMenu *newMenu)
void setItemContextMenu (QMenu *newMenu)
void setLeftCornerWidget (QWidget *w)
void setRightCornerWidget (QWidget *w)
void setSourceModel (std::shared_ptr< QAbstractItemModel > model)
void setTreeModel (BtBookshelfTreeModel *model)
QAction * showHideAction () const
QToolButton * showHideButton () const
BtBookshelfTreeModel * treeModel () const
BtBookshelfView * treeView () const
Protected Member Functions
void findExpanded (const QModelIndex &index, QString prefix, QStringList *expandedPaths)
void initActions ()
void initMenus ()
void initWidgets ()
void restoreExpanded (const QModelIndex &index, const QStringList &nodeList)
void retranslateUi ()
Private Attributes
QMenu * m_contextMenu
QToolButton * m_groupingButton
BtBookshelfGroupingMenu * m_groupingMenu
QAction * m_itemAboutAction
QActionGroup * m_itemActionGroup
QMenu * m_itemContextMenu
QAction * m_itemEditHtmlAction
QMenu * m_itemEditMenu
QAction * m_itemEditPlainAction
QAction * m_itemOpenAction
QAction * m_itemSearchAction
QAction * m_itemUnlockAction
QWidget * m_leftCornerWidget
QLineEdit * m_nameFilterEdit
QLabel * m_nameFilterLabel
BtBookshelfFilterModel * m_postFilterModel
QWidget * m_rightCornerWidget
QAction * m_showHideAction
QToolButton * m_showHideButton
std::shared_ptr< QAbstractItemModel > m_sourceModel
QHBoxLayout * m_toolBar
BtBookshelfTreeModel * m_treeModel
BtBookshelfView * m_treeView
Detailed Description
Definition at line 39 of file btbookshelfwidget.h.
Constructor & Destructor Documentation
BtBookshelfWidget()
BtBookshelfWidget::BtBookshelfWidget (QWidget * parent = nullptr, Qt::WindowFlags flags = Qt::WindowFlags()) explicit
Definition at line 41 of file btbookshelfwidget.cpp.
References BT_CONNECT, BtBookshelfView::contextMenuActivated(), initActions(), initMenus(), initWidgets(), m_contextMenu, m_itemContextMenu, m_nameFilterEdit, m_postFilterModel, m_treeView, BtBookshelfView::moduleContextMenuActivated(), retranslateUi(), and BtBookshelfFilterModel::setNameFilterFixedString().
Member Function Documentation
contextMenu()
QMenu * BtBookshelfWidget::contextMenu () const inline
Definition at line 64 of file btbookshelfwidget.h.
References m_contextMenu.
eventFilter()
bool BtBookshelfWidget::eventFilter (QObject * object, QEvent * event) override
Definition at line 180 of file btbookshelfwidget.cpp.
References BT_ASSERT, m_nameFilterEdit, and m_treeView.
findExpanded()
void BtBookshelfWidget::findExpanded (const QModelIndex & index, QString prefix, QStringList * expandedPaths) protected
Definition at line 198 of file btbookshelfwidget.cpp.
References findExpanded(), m_postFilterModel, and m_treeView.
Referenced by findExpanded(), and saveBookshelfState().
groupingButton()
QToolButton * BtBookshelfWidget::groupingButton () const inline
Definition at line 58 of file btbookshelfwidget.h.
References m_groupingButton.
groupingMenu()
BtBookshelfGroupingMenu * BtBookshelfWidget::groupingMenu () const inline
Definition at line 62 of file btbookshelfwidget.h.
References m_groupingMenu.
initActions()
void BtBookshelfWidget::initActions () protected
Definition at line 113 of file btbookshelfwidget.cpp.
References BT_CONNECT, m_postFilterModel, m_showHideAction, and BtBookshelfFilterModel::setShowHidden().
Referenced by BtBookshelfWidget().
initMenus()
void BtBookshelfWidget::initMenus () protected
Definition at line 121 of file btbookshelfwidget.cpp.
References BT_CONNECT, BtBookshelfTreeModel::Grouping::list(), m_contextMenu, m_groupingMenu, m_itemContextMenu, m_showHideAction, m_treeModel, m_treeView, BtBookshelfTreeModel::setGroupingOrder(), and BtBookshelfGroupingMenu::signalGroupingOrderChanged().
Referenced by BtBookshelfWidget().
initWidgets()
void BtBookshelfWidget::initWidgets () protected
Definition at line 140 of file btbookshelfwidget.cpp.
References m_groupingButton, m_groupingMenu, m_nameFilterEdit, m_nameFilterLabel, m_showHideAction, m_showHideButton, m_toolBar, and m_treeView.
Referenced by BtBookshelfWidget().
itemContextMenu()
QMenu * BtBookshelfWidget::itemContextMenu () const inline
Definition at line 65 of file btbookshelfwidget.h.
References m_itemContextMenu.
leftCornerWidget()
QWidget * BtBookshelfWidget::leftCornerWidget () const inline
Definition at line 55 of file btbookshelfwidget.h.
References m_leftCornerWidget.
loadBookshelfState()
void BtBookshelfWidget::loadBookshelfState ()
Definition at line 233 of file btbookshelfwidget.cpp.
References btConfig(), m_treeView, restoreExpanded(), and BtConfigCore::value().
Referenced by BtBookshelfDockWidget::loadBookshelfState().
nameFilterEdit()
QLineEdit * BtBookshelfWidget::nameFilterEdit () const inline
Definition at line 57 of file btbookshelfwidget.h.
References m_nameFilterEdit.
nameFilterLabel()
QLabel * BtBookshelfWidget::nameFilterLabel () const inline
Definition at line 56 of file btbookshelfwidget.h.
References m_nameFilterLabel.
postFilterModel()
BtBookshelfFilterModel * BtBookshelfWidget::postFilterModel () const inline
Definition at line 48 of file btbookshelfwidget.h.
References m_postFilterModel.
restoreExpanded()
void BtBookshelfWidget::restoreExpanded (const QModelIndex & index, const QStringList & nodeList) protected
Definition at line 215 of file btbookshelfwidget.cpp.
References m_postFilterModel, m_treeView, and restoreExpanded().
Referenced by loadBookshelfState(), and restoreExpanded().
retranslateUi()
void BtBookshelfWidget::retranslateUi () protected
Definition at line 172 of file btbookshelfwidget.cpp.
References m_groupingButton, m_groupingMenu, m_nameFilterLabel, and m_showHideAction.
Referenced by BtBookshelfWidget().
rightCornerWidget()
QWidget * BtBookshelfWidget::rightCornerWidget () const inline
Definition at line 60 of file btbookshelfwidget.h.
References m_rightCornerWidget.
saveBookshelfState()
void BtBookshelfWidget::saveBookshelfState ()
Definition at line 244 of file btbookshelfwidget.cpp.
References btConfig(), findExpanded(), m_treeView, and BtConfigCore::setValue().
Referenced by BtBookshelfDockWidget::saveBookshelfState().
setContextMenu()
void BtBookshelfWidget::setContextMenu (QMenu * newMenu) inline
Definition at line 75 of file btbookshelfwidget.h.
References m_contextMenu.
setItemContextMenu()
void BtBookshelfWidget::setItemContextMenu (QMenu * newMenu) inline
Definition at line 76 of file btbookshelfwidget.h.
References m_itemContextMenu.
Referenced by BtBookshelfDockWidget::BtBookshelfDockWidget().
setLeftCornerWidget()
void BtBookshelfWidget::setLeftCornerWidget (QWidget * w)
Definition at line 101 of file btbookshelfwidget.cpp.
References m_leftCornerWidget, and m_toolBar.
setRightCornerWidget()
void BtBookshelfWidget::setRightCornerWidget (QWidget * w)
Definition at line 107 of file btbookshelfwidget.cpp.
References m_rightCornerWidget, and m_toolBar.
setSourceModel()
void BtBookshelfWidget::setSourceModel (std::shared_ptr< QAbstractItemModel > model)
Definition at line 78 of file btbookshelfwidget.cpp.
References BT_ASSERT, m_sourceModel, m_treeModel, and BtBookshelfTreeModel::setSourceModel().
Referenced by BtBookshelfDockWidget::BtBookshelfDockWidget(), and BtSearchModuleChooserDialog::BtSearchModuleChooserDialog().
setTreeModel()
void BtBookshelfWidget::setTreeModel (BtBookshelfTreeModel * model)
Definition at line 88 of file btbookshelfwidget.cpp.
References BT_ASSERT, BT_CONNECT, BtBookshelfTreeModel::groupingOrder(), BtBookshelfTreeModel::groupingOrderChanged(), m_groupingMenu, m_postFilterModel, m_sourceModel, m_treeModel, BtBookshelfGroupingMenu::setGrouping(), and BtBookshelfTreeModel::setSourceModel().
Referenced by BtBookshelfDockWidget::BtBookshelfDockWidget(), and BtSearchModuleChooserDialog::BtSearchModuleChooserDialog().
showHideAction()
QAction * BtBookshelfWidget::showHideAction () const inline
Definition at line 72 of file btbookshelfwidget.h.
References m_showHideAction.
Referenced by BtSearchModuleChooserDialog::BtSearchModuleChooserDialog().
showHideButton()
QToolButton * BtBookshelfWidget::showHideButton () const inline
Definition at line 59 of file btbookshelfwidget.h.
References m_showHideButton.
Referenced by BtSearchModuleChooserDialog::BtSearchModuleChooserDialog().
treeModel()
BtBookshelfTreeModel * BtBookshelfWidget::treeModel () const inline
Definition at line 47 of file btbookshelfwidget.h.
References m_treeModel.
Referenced by BtSearchModuleChooserDialog::checkedModules(), and BtSearchModuleChooserDialog::setCheckedModules().
treeView()
BtBookshelfView * BtBookshelfWidget::treeView () const inline
Definition at line 61 of file btbookshelfwidget.h.
References m_treeView.
Referenced by BtBookshelfDockWidget::BtBookshelfDockWidget(), and BtModuleChooserDialog::BtModuleChooserDialog().
Member Data Documentation
m_contextMenu
QMenu* BtBookshelfWidget::m_contextMenu private
Definition at line 109 of file btbookshelfwidget.h.
Referenced by BtBookshelfWidget(), contextMenu(), initMenus(), and setContextMenu().
m_groupingButton
QToolButton* BtBookshelfWidget::m_groupingButton private
Definition at line 104 of file btbookshelfwidget.h.
Referenced by groupingButton(), initWidgets(), and retranslateUi().
m_groupingMenu
BtBookshelfGroupingMenu* BtBookshelfWidget::m_groupingMenu private
Definition at line 110 of file btbookshelfwidget.h.
Referenced by groupingMenu(), initMenus(), initWidgets(), retranslateUi(), and setTreeModel().
m_itemAboutAction
QAction* BtBookshelfWidget::m_itemAboutAction private
Definition at line 120 of file btbookshelfwidget.h.
m_itemActionGroup
QActionGroup* BtBookshelfWidget::m_itemActionGroup private
Definition at line 113 of file btbookshelfwidget.h.
m_itemContextMenu
QMenu* BtBookshelfWidget::m_itemContextMenu private
Definition at line 112 of file btbookshelfwidget.h.
Referenced by BtBookshelfWidget(), initMenus(), itemContextMenu(), and setItemContextMenu().
m_itemEditHtmlAction
QAction* BtBookshelfWidget::m_itemEditHtmlAction private
Definition at line 118 of file btbookshelfwidget.h.
m_itemEditMenu
QMenu* BtBookshelfWidget::m_itemEditMenu private
Definition at line 116 of file btbookshelfwidget.h.
m_itemEditPlainAction
QAction* BtBookshelfWidget::m_itemEditPlainAction private
Definition at line 117 of file btbookshelfwidget.h.
m_itemOpenAction
QAction* BtBookshelfWidget::m_itemOpenAction private
Definition at line 114 of file btbookshelfwidget.h.
m_itemSearchAction
QAction* BtBookshelfWidget::m_itemSearchAction private
Definition at line 115 of file btbookshelfwidget.h.
m_itemUnlockAction
QAction* BtBookshelfWidget::m_itemUnlockAction private
Definition at line 119 of file btbookshelfwidget.h.
m_leftCornerWidget
QWidget* BtBookshelfWidget::m_leftCornerWidget private
Definition at line 100 of file btbookshelfwidget.h.
Referenced by leftCornerWidget(), and setLeftCornerWidget().
m_nameFilterEdit
QLineEdit* BtBookshelfWidget::m_nameFilterEdit private
Definition at line 103 of file btbookshelfwidget.h.
Referenced by BtBookshelfWidget(), eventFilter(), initWidgets(), and nameFilterEdit().
m_nameFilterLabel
QLabel* BtBookshelfWidget::m_nameFilterLabel private
Definition at line 102 of file btbookshelfwidget.h.
Referenced by initWidgets(), nameFilterLabel(), and retranslateUi().
m_postFilterModel
BtBookshelfFilterModel* BtBookshelfWidget::m_postFilterModel private
Definition at line 96 of file btbookshelfwidget.h.
Referenced by BtBookshelfWidget(), findExpanded(), initActions(), postFilterModel(), restoreExpanded(), and setTreeModel().
m_rightCornerWidget
QWidget* BtBookshelfWidget::m_rightCornerWidget private
Definition at line 101 of file btbookshelfwidget.h.
Referenced by rightCornerWidget(), and setRightCornerWidget().
m_showHideAction
QAction* BtBookshelfWidget::m_showHideAction private
Definition at line 111 of file btbookshelfwidget.h.
Referenced by initActions(), initMenus(), initWidgets(), retranslateUi(), and showHideAction().
m_showHideButton
QToolButton* BtBookshelfWidget::m_showHideButton private
Definition at line 105 of file btbookshelfwidget.h.
Referenced by initWidgets(), and showHideButton().
m_sourceModel
std::shared_ptr<QAbstractItemModel> BtBookshelfWidget::m_sourceModel private
Definition at line 94 of file btbookshelfwidget.h.
Referenced by setSourceModel(), and setTreeModel().
m_toolBar
QHBoxLayout* BtBookshelfWidget::m_toolBar private
Definition at line 99 of file btbookshelfwidget.h.
Referenced by initWidgets(), setLeftCornerWidget(), and setRightCornerWidget().
m_treeModel
BtBookshelfTreeModel* BtBookshelfWidget::m_treeModel private
Definition at line 95 of file btbookshelfwidget.h.
Referenced by initMenus(), setSourceModel(), setTreeModel(), and treeModel().
m_treeView
BtBookshelfView* BtBookshelfWidget::m_treeView private
Definition at line 106 of file btbookshelfwidget.h.
Referenced by BtBookshelfWidget(), eventFilter(), findExpanded(), initMenus(), initWidgets(), loadBookshelfState(), restoreExpanded(), saveBookshelfState(), and treeView().
The documentation for this class was generated from the following files:
btbookshelfwidget.h
btbookshelfwidget.cpp