BibleTime: CBookmarkIndex Class Reference
CBookmarkIndex Class Reference
#include <cbookmarkindex.h>
Public Types
enum MenuAction {
NewFolder = 0 , ChangeFolder , EditBookmark , SortFolderBookmarks ,
SortAllBookmarks , ImportBookmarks , ExportBookmarks , PrintBookmarks ,
DeleteEntries , ActionCount , ActionBegin = NewFolder , ActionEnd = ActionCount
}
Signals
void createReadDisplayWindow (QList< CSwordModuleInfo * >, QString const &)
Emitted when a module should be opened.
void magInfoProvided (Rendering::InfoType const, QString const &data)
Public Member Functions
CBookmarkIndex (QWidget *const parent=nullptr)
Protected Member Functions
void dragEnterEvent (QDragEnterEvent *event) override
void dragLeaveEvent (QDragLeaveEvent *event) override
void dragMoveEvent (QDragMoveEvent *event) override
QMimeData * dragObject ()
void dropEvent (QDropEvent *event) override
void leaveEvent (QEvent *event) override
void mouseMoveEvent (QMouseEvent *event) override
void mouseReleaseEvent (QMouseEvent *event) override
void paintEvent (QPaintEvent *event) override
void startDrag (Qt::DropActions supportedActions) override
Private Member Functions
void deleteEntries ()
bool enableAction (QModelIndex const &index, MenuAction const type) const
bool hasBookmarksRecursively (QModelIndexList selected) const
void hideExtraItem ()
void showExtraItem ()
Private Attributes
QAction * m_actions [ActionCount]
BtBookmarksModel * m_bookmarksModel
QPoint m_dragMovementPosition
QPoint m_dragStartPosition
QPersistentModelIndex m_extraItem
QTimer m_magTimer
int m_mouseReleaseEventModifiers
QMenu * m_popup
QModelIndex m_previousEventItem
Detailed Description
The widget which manages all bookmarks.
Author
The BibleTime team
Definition at line 37 of file cbookmarkindex.h.
Member Enumeration Documentation
MenuAction
enum CBookmarkIndex::MenuAction
Enumerator
NewFolder
ChangeFolder
EditBookmark
SortFolderBookmarks
SortAllBookmarks
ImportBookmarks
ExportBookmarks
PrintBookmarks
DeleteEntries
ActionCount
ActionBegin
ActionEnd
Definition at line 43 of file cbookmarkindex.h.
Constructor & Destructor Documentation
CBookmarkIndex()
CBookmarkIndex::CBookmarkIndex (QWidget *const parent = nullptr)
Note
HACK: checking the modifier keys from the last mouseReleaseEvent depends on executing order: mouseReleaseEvent first, then itemClicked signal.
Definition at line 55 of file cbookmarkindex.cpp.
References ActionBegin, ActionEnd, BtBookmarksModel::addFolder(), BT_ASSERT, BT_CONNECT, btConfig(), ChangeFolder, createReadDisplayWindow(), Rendering::CrossReference, DeleteEntries, deleteEntries(), BtBookmarksModel::description(), EditBookmark, enableAction(), ExportBookmarks, BtConfig::getDisplayOptions(), BtConfig::getFilterOptions(), hasBookmarksRecursively(), ImportBookmarks, BtBookmarksModel::index(), BtBookmarksModel::insertRows(), BtBookmarksModel::isBookmark(), BtBookmarksModel::isFolder(), BtBookmarksModel::key(), BtBookmarksModel::load(), m_actions, m_bookmarksModel, m_extraItem, m_magTimer, m_mouseReleaseEventModifiers, m_popup, m_previousEventItem, magInfoProvided(), BtBookmarksModel::module(), NewFolder, PrintBookmarks, BtBookmarksModel::rowCount(), BtBookmarksModel::save(), BtBookmarksModel::setData(), BtBookmarksModel::setDescription(), showExtraItem(), message::showQuestion(), SortAllBookmarks, SortFolderBookmarks, BtBookmarksModel::sortItems(), and Rendering::Text.
Member Function Documentation
createReadDisplayWindow
void CBookmarkIndex::createReadDisplayWindow (QList< CSwordModuleInfo * > , QString const &) signal
Emitted when a module should be opened.
Referenced by CBookmarkIndex(), and BibleTime::initConnections().
deleteEntries()
void CBookmarkIndex::deleteEntries () private
Definition at line 620 of file cbookmarkindex.cpp.
Referenced by CBookmarkIndex(), and dropEvent().
dragEnterEvent()
void CBookmarkIndex::dragEnterEvent (QDragEnterEvent * event) override protected
Definition at line 360 of file cbookmarkindex.cpp.
dragLeaveEvent()
void CBookmarkIndex::dragLeaveEvent (QDragLeaveEvent * event) override protected
Definition at line 381 of file cbookmarkindex.cpp.
dragMoveEvent()
void CBookmarkIndex::dragMoveEvent (QDragMoveEvent * event) override protected
Definition at line 369 of file cbookmarkindex.cpp.
References m_dragMovementPosition.
dragObject()
QMimeData * CBookmarkIndex::dragObject () protected
Creates a drag mime data object for the current selection.
Definition at line 341 of file cbookmarkindex.cpp.
References BtBookmarksModel::description(), BtBookmarksModel::isBookmark(), BtBookmarksModel::key(), and m_bookmarksModel.
Referenced by startDrag().
dropEvent()
void CBookmarkIndex::dropEvent (QDropEvent * event) override protected
Todo:
add title
Definition at line 448 of file cbookmarkindex.cpp.
References BtBookmarksModel::addBookmark(), BT_ASSERT, BT_CONNECT, BtBookmarksModel::copyItems(), deleteEntries(), CSwordBackend::findModuleByName(), BtBookmarksModel::hasDescendant(), CSwordBackend::instance(), BtBookmarksModel::isBookmark(), BtBookmarksModel::isFolder(), m_bookmarksModel, and BtBookmarksModel::rowCount().
enableAction()
bool CBookmarkIndex::enableAction (QModelIndex const & index, CBookmarkIndex::MenuAction const type) const private
Definition at line 571 of file cbookmarkindex.cpp.
References ChangeFolder, DeleteEntries, EditBookmark, ExportBookmarks, hasBookmarksRecursively(), ImportBookmarks, BtBookmarksModel::isBookmark(), BtBookmarksModel::isFolder(), m_bookmarksModel, NewFolder, PrintBookmarks, and SortFolderBookmarks.
Referenced by CBookmarkIndex().
hasBookmarksRecursively()
bool CBookmarkIndex::hasBookmarksRecursively (QModelIndexList selected) const private
Definition at line 592 of file cbookmarkindex.cpp.
References BtBookmarksModel::isBookmark(), BtBookmarksModel::isFolder(), m_bookmarksModel, and BtBookmarksModel::rowCount().
Referenced by CBookmarkIndex(), and enableAction().
hideExtraItem()
void CBookmarkIndex::hideExtraItem () private
Definition at line 611 of file cbookmarkindex.cpp.
References m_extraItem.
Referenced by mouseMoveEvent().
leaveEvent()
void CBookmarkIndex::leaveEvent (QEvent * event) override protected
Definition at line 614 of file cbookmarkindex.cpp.
References showExtraItem().
magInfoProvided
void CBookmarkIndex::magInfoProvided (Rendering::InfoType const , QString const & data) signal
Referenced by CBookmarkIndex(), and BibleTime::initView().
mouseMoveEvent()
void CBookmarkIndex::mouseMoveEvent (QMouseEvent * event) override protected
Definition at line 650 of file cbookmarkindex.cpp.
References hideExtraItem(), m_extraItem, m_magTimer, m_previousEventItem, and showExtraItem().
mouseReleaseEvent()
void CBookmarkIndex::mouseReleaseEvent (QMouseEvent * event) override protected
Note
Hack to get single click and selection working. See slotExecuted.
Definition at line 335 of file cbookmarkindex.cpp.
References m_mouseReleaseEventModifiers.
paintEvent()
void CBookmarkIndex::paintEvent (QPaintEvent * event) override protected
Definition at line 386 of file cbookmarkindex.cpp.
References BtIcons::icon_pointing_arrow, BtIcons::instance(), BtBookmarksModel::isBookmark(), BtBookmarksModel::isFolder(), m_bookmarksModel, m_dragMovementPosition, m_extraItem, and util::tool::mWidth().
showExtraItem()
void CBookmarkIndex::showExtraItem () private
Definition at line 606 of file cbookmarkindex.cpp.
References m_extraItem.
Referenced by CBookmarkIndex(), leaveEvent(), and mouseMoveEvent().
startDrag()
void CBookmarkIndex::startDrag (Qt::DropActions supportedActions) override protected
Definition at line 640 of file cbookmarkindex.cpp.
References dragObject().
Member Data Documentation
m_actions
QAction* CBookmarkIndex::m_actions[ActionCount] private
Definition at line 98 of file cbookmarkindex.h.
Referenced by CBookmarkIndex().
m_bookmarksModel
BtBookmarksModel* CBookmarkIndex::m_bookmarksModel private
Pointer to bookmarks model, added for convenience.
Definition at line 109 of file cbookmarkindex.h.
Referenced by CBookmarkIndex(), dragObject(), dropEvent(), enableAction(), hasBookmarksRecursively(), and paintEvent().
m_dragMovementPosition
QPoint CBookmarkIndex::m_dragMovementPosition private
Definition at line 104 of file cbookmarkindex.h.
Referenced by dragMoveEvent(), and paintEvent().
m_dragStartPosition
QPoint CBookmarkIndex::m_dragStartPosition private
Definition at line 105 of file cbookmarkindex.h.
m_extraItem
QPersistentModelIndex CBookmarkIndex::m_extraItem private
Definition at line 106 of file cbookmarkindex.h.
Referenced by CBookmarkIndex(), hideExtraItem(), mouseMoveEvent(), paintEvent(), and showExtraItem().
m_magTimer
QTimer CBookmarkIndex::m_magTimer private
Definition at line 101 of file cbookmarkindex.h.
Referenced by CBookmarkIndex(), and mouseMoveEvent().
m_mouseReleaseEventModifiers
int CBookmarkIndex::m_mouseReleaseEventModifiers private
Definition at line 102 of file cbookmarkindex.h.
Referenced by CBookmarkIndex(), and mouseReleaseEvent().
m_popup
QMenu* CBookmarkIndex::m_popup private
Definition at line 100 of file cbookmarkindex.h.
Referenced by CBookmarkIndex().
m_previousEventItem
QModelIndex CBookmarkIndex::m_previousEventItem private
Definition at line 103 of file cbookmarkindex.h.
Referenced by CBookmarkIndex(), and mouseMoveEvent().
The documentation for this class was generated from the following files:
cbookmarkindex.h
cbookmarkindex.cpp