BibleTime: BtModuleChooserDialog Class Reference
BtModuleChooserDialog Class Reference
#include <btmodulechooserdialog.h>
Protected Member Functions
BtBookshelfWidget * bookshelfWidget () const
BtModuleChooserDialog (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
QDialogButtonBox * buttonBox () const
QLabel * label () const
void retranslateUi ()
Private Attributes
BtBookshelfWidget * m_bookshelfWidget
QDialogButtonBox * m_buttonBox
QLabel * m_captionLabel
Detailed Description
Definition at line 27 of file btmodulechooserdialog.h.
Constructor & Destructor Documentation
BtModuleChooserDialog()
BtModuleChooserDialog::BtModuleChooserDialog (QWidget * parent = nullptr, Qt::WindowFlags flags = Qt::WindowFlags()) explicit protected
Definition at line 26 of file btmodulechooserdialog.cpp.
References BT_CONNECT, m_bookshelfWidget, m_buttonBox, m_captionLabel, BtBookshelfView::moduleActivated(), retranslateUi(), and BtBookshelfWidget::treeView().
Member Function Documentation
bookshelfWidget()
BtBookshelfWidget * BtModuleChooserDialog::bookshelfWidget () const inline protected
Definition at line 37 of file btmodulechooserdialog.h.
References m_bookshelfWidget.
Referenced by BtSearchModuleChooserDialog::BtSearchModuleChooserDialog(), BtSearchModuleChooserDialog::checkedModules(), and BtSearchModuleChooserDialog::setCheckedModules().
buttonBox()
QDialogButtonBox * BtModuleChooserDialog::buttonBox () const inline protected
Definition at line 40 of file btmodulechooserdialog.h.
References m_buttonBox.
label()
QLabel * BtModuleChooserDialog::label () const inline protected
Definition at line 35 of file btmodulechooserdialog.h.
References m_captionLabel.
Referenced by BtSearchModuleChooserDialog::retranslateUi().
retranslateUi()
void BtModuleChooserDialog::retranslateUi () protected
Definition at line 57 of file btmodulechooserdialog.cpp.
References m_buttonBox, and message::prepareDialogBox().
Referenced by BtModuleChooserDialog().
Member Data Documentation
m_bookshelfWidget
BtBookshelfWidget* BtModuleChooserDialog::m_bookshelfWidget private
Definition at line 44 of file btmodulechooserdialog.h.
Referenced by bookshelfWidget(), and BtModuleChooserDialog().
m_buttonBox
QDialogButtonBox* BtModuleChooserDialog::m_buttonBox private
Definition at line 45 of file btmodulechooserdialog.h.
Referenced by BtModuleChooserDialog(), buttonBox(), and retranslateUi().
m_captionLabel
QLabel* BtModuleChooserDialog::m_captionLabel private
Definition at line 43 of file btmodulechooserdialog.h.
Referenced by BtModuleChooserDialog(), and label().
The documentation for this class was generated from the following files:
btmodulechooserdialog.h
btmodulechooserdialog.cpp