BibleTime: BtEditTextWizard Class Reference
BtEditTextWizard Class Reference final
The Edit Text wizard for editing the personal commentary.
#include <btedittextwizard.h>
Public Slots
void accept () final override
Public Member Functions
BtEditTextWizard (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
bool htmlMode () const
void setFont (const QFont &font)
void setText (const QString &text)
void setTitle (const QString &text)
QString text () const
Private Member Functions
void retranslateUi ()
Private Attributes
BtEditTextPage *const m_editTextPage
BtPlainOrHtmlPage *const m_plainOrHtmlPage
Detailed Description
The Edit Text wizard for editing the personal commentary.
Definition at line 28 of file btedittextwizard.h.
Constructor & Destructor Documentation
BtEditTextWizard()
BtEditTextWizard::BtEditTextWizard (QWidget * parent = nullptr, Qt::WindowFlags flags = Qt::WindowFlags())
Definition at line 29 of file btedittextwizard.cpp.
References btConfig(), m_editTextPage, m_plainOrHtmlPage, retranslateUi(), and BtPlainOrHtmlPage::setHtmlMode().
Member Function Documentation
accept
void BtEditTextWizard::accept () final override slot
Definition at line 42 of file btedittextwizard.cpp.
References btConfig(), htmlMode(), and BtConfigCore::setValue().
htmlMode()
bool BtEditTextWizard::htmlMode () const
Definition at line 48 of file btedittextwizard.cpp.
References BtPlainOrHtmlPage::htmlMode(), and m_plainOrHtmlPage.
Referenced by accept(), and BtEditTextPage::initializePage().
retranslateUi()
void BtEditTextWizard::retranslateUi () private
Definition at line 68 of file btedittextwizard.cpp.
References translateQWizardStandardButtons().
Referenced by BtEditTextWizard().
setFont()
void BtEditTextWizard::setFont (const QFont & font)
Definition at line 52 of file btedittextwizard.cpp.
References m_editTextPage, and BtEditTextPage::setFont().
Referenced by BtQmlInterface::openEditor().
setText()
void BtEditTextWizard::setText (const QString & text)
Definition at line 56 of file btedittextwizard.cpp.
References m_editTextPage, BtEditTextPage::setText(), and text().
Referenced by BtQmlInterface::openEditor().
setTitle()
void BtEditTextWizard::setTitle (const QString & text)
Definition at line 60 of file btedittextwizard.cpp.
References text().
Referenced by BtQmlInterface::openEditor().
text()
QString BtEditTextWizard::text () const
Definition at line 64 of file btedittextwizard.cpp.
References m_editTextPage, and BtEditTextPage::text().
Referenced by BtQmlInterface::openEditor(), setText(), and setTitle().
Member Data Documentation
m_editTextPage
BtEditTextPage* const BtEditTextWizard::m_editTextPage private
Definition at line 51 of file btedittextwizard.h.
Referenced by BtEditTextWizard(), setFont(), setText(), and text().
m_plainOrHtmlPage
BtPlainOrHtmlPage* const BtEditTextWizard::m_plainOrHtmlPage private
Definition at line 50 of file btedittextwizard.h.
Referenced by BtEditTextWizard(), and htmlMode().
The documentation for this class was generated from the following files:
btedittextwizard.h
btedittextwizard.cpp