BibleTime: anonymous_namespace{btbookshelfgroupingmenu.cpp} Namespace Reference
anonymous_namespace{btbookshelfgroupingmenu.cpp} Namespace Reference
Functions
const BtBookshelfTreeModel::Grouping & getActionRef (const QAction *a)
void initializeGroups ()
void setActionRef (QAction *a, const BtBookshelfTreeModel::Grouping &g)
Variables
BtBookshelfTreeModel::Grouping groupingCat (true)
BtBookshelfTreeModel::Grouping groupingCatLang
BtBookshelfTreeModel::Grouping groupingLang (true)
BtBookshelfTreeModel::Grouping groupingLangCat (true)
BtBookshelfTreeModel::Grouping groupingNone (true)
bool groupsInitialized = false
Function Documentation
getActionRef()
const BtBookshelfTreeModel::Grouping & anonymous_namespace{btbookshelfgroupingmenu.cpp}::getActionRef (const QAction * a) inline
Definition at line 50 of file btbookshelfgroupingmenu.cpp.
initializeGroups()
void anonymous_namespace{btbookshelfgroupingmenu.cpp}::initializeGroups () inline
Definition at line 32 of file btbookshelfgroupingmenu.cpp.
References BT_ASSERT, BtBookshelfTreeModel::GROUP_CATEGORY, BtBookshelfTreeModel::GROUP_LANGUAGE, groupingCat, groupingCatLang, groupingLang, groupingLangCat, groupingNone, and groupsInitialized.
setActionRef()
void anonymous_namespace{btbookshelfgroupingmenu.cpp}::setActionRef (QAction * a, const BtBookshelfTreeModel::Grouping & g) inline
Definition at line 44 of file btbookshelfgroupingmenu.cpp.
Variable Documentation
groupingCat
BtBookshelfTreeModel::Grouping anonymous_namespace{btbookshelfgroupingmenu.cpp}::groupingCat(true) (true)
Referenced by initializeGroups().
groupingCatLang
BtBookshelfTreeModel::Grouping anonymous_namespace{btbookshelfgroupingmenu.cpp}::groupingCatLang
Definition at line 28 of file btbookshelfgroupingmenu.cpp.
Referenced by initializeGroups().
groupingLang
BtBookshelfTreeModel::Grouping anonymous_namespace{btbookshelfgroupingmenu.cpp}::groupingLang(true) (true)
Referenced by initializeGroups().
groupingLangCat
BtBookshelfTreeModel::Grouping anonymous_namespace{btbookshelfgroupingmenu.cpp}::groupingLangCat(true) (true)
Referenced by initializeGroups().
groupingNone
BtBookshelfTreeModel::Grouping anonymous_namespace{btbookshelfgroupingmenu.cpp}::groupingNone(true) (true)
Referenced by initializeGroups().
groupsInitialized
bool anonymous_namespace{btbookshelfgroupingmenu.cpp}::groupsInitialized = false
Definition at line 25 of file btbookshelfgroupingmenu.cpp.
Referenced by initializeGroups().