BibleTime: BtModuleChooserBar Class Reference
BtModuleChooserBar Class Reference
#include <btmodulechooserbar.h>
Public Slots
void slotBackendModulesChanged () override
void slotWindowModulesChanged () override
Public Member Functions
BtModuleChooserBar (QWidget *parent)
void setModules (QStringList useModules, CSwordModuleInfo::ModuleType type, CDisplayWindow *window)
Public Member Functions inherited from BtWindowModuleChooser
BtWindowModuleChooser (CSwordModuleInfo::ModuleType moduleType, CDisplayWindow *parentWindow)
virtual void slotBackendModulesChanged ()=0
virtual void slotWindowModulesChanged ()=0
Private Member Functions
BtModuleChooserButton * addButton ()
void adjustButtonCount (bool adjustToZero=false)
void updateButtonMenus ()
Private Attributes
QList< BtModuleChooserButton * > m_buttonList
int m_idCounter
CSwordModuleInfo::ModuleType m_moduleType
CDisplayWindow * m_window
Additional Inherited Members
Protected Attributes inherited from BtWindowModuleChooser
QStringList m_modules
CSwordModuleInfo::ModuleType m_moduleType
CDisplayWindow * m_window
Detailed Description
Definition at line 29 of file btmodulechooserbar.h.
Constructor & Destructor Documentation
BtModuleChooserBar()
BtModuleChooserBar::BtModuleChooserBar (QWidget * parent)
Definition at line 25 of file btmodulechooserbar.cpp.
Member Function Documentation
addButton()
BtModuleChooserButton * BtModuleChooserBar::addButton () private
Adds an empty button to the toolbar.
Definition at line 80 of file btmodulechooserbar.cpp.
References BT_CONNECT, m_buttonList, m_moduleType, m_window, BtModuleChooserButton::sigModuleAdd(), BtModuleChooserButton::sigModuleRemove(), BtModuleChooserButton::sigModuleReplace(), CDisplayWindow::slotAddModule(), CDisplayWindow::slotRemoveModule(), and CDisplayWindow::slotReplaceModule().
Referenced by adjustButtonCount(), and setModules().
adjustButtonCount()
void BtModuleChooserBar::adjustButtonCount (bool adjustToZero = false) private
Removes or adds buttons so that the count matches the limit. If given limit is -1 the module count is the limit.
Definition at line 49 of file btmodulechooserbar.cpp.
References addButton(), CSwordModuleInfo::GenericBook, m_buttonList, BtWindowModuleChooser::m_modules, and m_moduleType.
Referenced by setModules(), slotBackendModulesChanged(), and slotWindowModulesChanged().
setModules()
void BtModuleChooserBar::setModules (QStringList useModules, CSwordModuleInfo::ModuleType type, CDisplayWindow * window)
Initialize with module list.
Sets the modules which are chosen in this module chooser bar.
Definition at line 107 of file btmodulechooserbar.cpp.
References addButton(), adjustButtonCount(), BT_CONNECT, CSwordModuleInfo::GenericBook, BtWindowModuleChooser::m_modules, m_moduleType, m_window, CDisplayWindow::sigModuleListChanged(), CDisplayWindow::sigModuleListSet(), slotBackendModulesChanged(), slotWindowModulesChanged(), and updateButtonMenus().
Referenced by CBookReadWindow::initView(), CDisplayWindow::initView(), CBookReadWindow::setupMainWindowToolBars(), and CDisplayWindow::setupMainWindowToolBars().
slotBackendModulesChanged
void BtModuleChooserBar::slotBackendModulesChanged () override slot
The backend module list was updated, module list and widgets must be updated. The signal comes from the window, not from the backend. The new list can be shorter but not longer than the old list.
Definition at line 34 of file btmodulechooserbar.cpp.
References adjustButtonCount(), CDisplayWindow::getModuleList(), leftLikeParallelModules(), m_buttonList, BtWindowModuleChooser::m_modules, and m_window.
Referenced by setModules().
slotWindowModulesChanged
void BtModuleChooserBar::slotWindowModulesChanged () override slot
The window module list was changed, i.e. 1 module added, removed or replaced.
Definition at line 74 of file btmodulechooserbar.cpp.
References adjustButtonCount(), CDisplayWindow::getModuleList(), BtWindowModuleChooser::m_modules, m_window, and updateButtonMenus().
Referenced by setModules().
updateButtonMenus()
void BtModuleChooserBar::updateButtonMenus () private
Updates every button's menu without recreating it.
Definition at line 134 of file btmodulechooserbar.cpp.
References leftLikeParallelModules(), m_buttonList, and BtWindowModuleChooser::m_modules.
Referenced by setModules(), and slotWindowModulesChanged().
Member Data Documentation
m_buttonList
QList<BtModuleChooserButton*> BtModuleChooserBar::m_buttonList private
Definition at line 67 of file btmodulechooserbar.h.
Referenced by addButton(), adjustButtonCount(), slotBackendModulesChanged(), and updateButtonMenus().
m_idCounter
int BtModuleChooserBar::m_idCounter private
Definition at line 64 of file btmodulechooserbar.h.
m_moduleType
CSwordModuleInfo::ModuleType BtModuleChooserBar::m_moduleType private
Definition at line 66 of file btmodulechooserbar.h.
Referenced by addButton(), adjustButtonCount(), and setModules().
m_window
CDisplayWindow* BtModuleChooserBar::m_window private
Definition at line 65 of file btmodulechooserbar.h.
Referenced by addButton(), setModules(), slotBackendModulesChanged(), and slotWindowModulesChanged().
The documentation for this class was generated from the following files:
btmodulechooserbar.h
btmodulechooserbar.cpp