BibleTime: Search::anonymous_namespace{cmoduleresultview.cpp} Namespace Reference
Search::anonymous_namespace{cmoduleresultview.cpp} Namespace Reference
Functions
QString getStrongsNumberText (QString const &verseContent, int &startIndex, QString const &lemmaText)
void populateStrongsResultList (QList< StrongsResult > &list, CSwordModuleInfo const *module, CSwordModuleSearch::ModuleResultList const &result, QString const &strongsNumber)
Function Documentation
getStrongsNumberText()
QString Search::anonymous_namespace{cmoduleresultview.cpp}::getStrongsNumberText (QString const & verseContent, int & startIndex, QString const & lemmaText)
Definition at line 40 of file cmoduleresultview.cpp.
References getStrongsNumberText().
Referenced by getStrongsNumberText(), and populateStrongsResultList().
populateStrongsResultList()
void Search::anonymous_namespace{cmoduleresultview.cpp}::populateStrongsResultList (QList< StrongsResult > & list, CSwordModuleInfo const * module, CSwordModuleSearch::ModuleResultList const & result, QString const & strongsNumber)
Definition at line 77 of file cmoduleresultview.cpp.
References getStrongsNumberText(), populateStrongsResultList(), and Rendering::CTextRendering::renderSingleKey().
Referenced by populateStrongsResultList().