BibleTime: BtBookshelfWizard Class Reference
BtBookshelfWizard Class Reference final
The Bookshelf Manager wizard.
#include <btbookshelfwizard.h>
Public Slots
void accept () final override
Public Member Functions
BtBookshelfWizard (QWidget *parent=nullptr, Qt::WindowFlags flags=Qt::WindowFlags())
void downloadFinished ()
void downloadStarted ()
QString installPath () const
BtBookshelfLanguagesPage & languagesPage () const noexcept
QStringList selectedLanguages () const
QStringList selectedSources () const
BtModuleSet selectedWorks () const
WizardTaskType taskType () const
Static Public Member Functions
static bool autoUpdateSources ()
static void setAutoUpdateSources (bool value)
Protected Member Functions
virtual void keyPressEvent (QKeyEvent *event) override
Private Member Functions
void retranslateUi ()
void stopDownload ()
Private Attributes
QMessageBox * m_closeMessageBox
bool m_closeRequested
bool m_downloadInProgress
BtBookshelfInstallFinalPage *const m_installFinalPage
BtBookshelfWorksPage *const m_installWorksPage
BtBookshelfLanguagesPage *const m_languagesPage
BtBookshelfWorksPage *const m_removeWorksPage
BtBookshelfSourcesPage *const m_sourcesPage
BtBookshelfSourcesProgressPage *const m_sourcesProgressPage
BtBookshelfTaskPage *const m_taskPage
BtBookshelfWorksPage *const m_updateWorksPage
Detailed Description
The Bookshelf Manager wizard.
Definition at line 36 of file btbookshelfwizard.h.
Constructor & Destructor Documentation
BtBookshelfWizard()
BtBookshelfWizard::BtBookshelfWizard (QWidget * parent = nullptr, Qt::WindowFlags flags = Qt::WindowFlags())
Definition at line 43 of file btbookshelfwizard.cpp.
References btConfig(), installFinalPage, installWorksPage, languagesPage, m_installFinalPage, m_installWorksPage, m_languagesPage, m_removeWorksPage, m_sourcesPage, m_sourcesProgressPage, m_taskPage, m_updateWorksPage, removeFinalPage, removeWorksPage, retranslateUi(), sourcesPage, sourcesProgressPage, taskPage, and updateWorksPage.
Member Function Documentation
accept
void BtBookshelfWizard::accept () final override slot
Definition at line 114 of file btbookshelfwizard.cpp.
References btConfig(), m_installFinalPage, selectedLanguages(), selectedSources(), and BtConfigCore::setValue().
Referenced by downloadFinished().
autoUpdateSources()
bool BtBookshelfWizard::autoUpdateSources () static
Definition at line 150 of file btbookshelfwizard.cpp.
Referenced by BtBookshelfTaskPage::timeToUpdate().
downloadFinished()
void BtBookshelfWizard::downloadFinished ()
Definition at line 179 of file btbookshelfwizard.cpp.
References accept(), m_closeMessageBox, m_closeRequested, and m_downloadInProgress.
Referenced by BtBookshelfInstallFinalPage::slotThreadFinished(), and BtBookshelfSourcesProgressPage::slotThreadFinished().
downloadStarted()
void BtBookshelfWizard::downloadStarted ()
Definition at line 175 of file btbookshelfwizard.cpp.
References m_downloadInProgress.
Referenced by BtBookshelfSourcesProgressPage::initializePage().
installPath()
QString BtBookshelfWizard::installPath () const
Definition at line 138 of file btbookshelfwizard.cpp.
References BT_ASSERT, BtBookshelfWorksPage::installPath(), installWorks, m_installWorksPage, m_taskPage, m_updateWorksPage, BtBookshelfTaskPage::taskType(), and updateWorks.
keyPressEvent()
void BtBookshelfWizard::keyPressEvent (QKeyEvent * event) override protected virtual
Definition at line 163 of file btbookshelfwizard.cpp.
References m_closeMessageBox, m_closeRequested, m_downloadInProgress, and stopDownload().
languagesPage()
BtBookshelfLanguagesPage & BtBookshelfWizard::languagesPage () const inline noexcept
Definition at line 53 of file btbookshelfwizard.h.
References m_languagesPage.
Referenced by BtBookshelfSourcesPage::nextId().
retranslateUi()
void BtBookshelfWizard::retranslateUi () private
Definition at line 96 of file btbookshelfwizard.cpp.
References m_closeMessageBox, and translateQWizardStandardButtons().
Referenced by BtBookshelfWizard().
selectedLanguages()
QStringList BtBookshelfWizard::selectedLanguages () const
Definition at line 111 of file btbookshelfwizard.cpp.
References m_languagesPage, and BtBookshelfLanguagesPage::selectedLanguages().
Referenced by accept(), and BtBookshelfWorksPage::initializePage().
selectedSources()
QStringList BtBookshelfWizard::selectedSources () const
Definition at line 108 of file btbookshelfwizard.cpp.
References m_sourcesPage, and BtBookshelfSourcesPage::selectedSources().
Referenced by accept(), BtBookshelfLanguagesPage::initializeLanguages(), and BtBookshelfWorksPage::initializePage().
selectedWorks()
BtModuleSet BtBookshelfWizard::selectedWorks () const
Definition at line 125 of file btbookshelfwizard.cpp.
References BT_ASSERT, BtBookshelfWorksPage::checkedModules(), installWorks, m_installWorksPage, m_removeWorksPage, m_taskPage, m_updateWorksPage, removeWorks, BtBookshelfTaskPage::taskType(), and updateWorks.
setAutoUpdateSources()
void BtBookshelfWizard::setAutoUpdateSources (bool value) static
Definition at line 146 of file btbookshelfwizard.cpp.
Referenced by BtBookshelfSourcesProgressPage::slotThreadFinished().
stopDownload()
void BtBookshelfWizard::stopDownload () private
Definition at line 154 of file btbookshelfwizard.cpp.
References m_installFinalPage, m_sourcesProgressPage, BtBookshelfInstallFinalPage::slotStopInstall(), and BtBookshelfSourcesProgressPage::slotStopInstall().
Referenced by keyPressEvent().
taskType()
WizardTaskType BtBookshelfWizard::taskType () const
Definition at line 135 of file btbookshelfwizard.cpp.
References m_taskPage, and BtBookshelfTaskPage::taskType().
Member Data Documentation
m_closeMessageBox
QMessageBox* BtBookshelfWizard::m_closeMessageBox private
Definition at line 76 of file btbookshelfwizard.h.
Referenced by downloadFinished(), keyPressEvent(), and retranslateUi().
m_closeRequested
bool BtBookshelfWizard::m_closeRequested private
Definition at line 75 of file btbookshelfwizard.h.
Referenced by downloadFinished(), and keyPressEvent().
m_downloadInProgress
bool BtBookshelfWizard::m_downloadInProgress private
Definition at line 74 of file btbookshelfwizard.h.
Referenced by downloadFinished(), downloadStarted(), and keyPressEvent().
m_installFinalPage
BtBookshelfInstallFinalPage* const BtBookshelfWizard::m_installFinalPage private
Definition at line 85 of file btbookshelfwizard.h.
Referenced by accept(), BtBookshelfWizard(), and stopDownload().
m_installWorksPage
BtBookshelfWorksPage* const BtBookshelfWizard::m_installWorksPage private
Definition at line 82 of file btbookshelfwizard.h.
Referenced by BtBookshelfWizard(), installPath(), and selectedWorks().
m_languagesPage
BtBookshelfLanguagesPage* const BtBookshelfWizard::m_languagesPage private
Definition at line 81 of file btbookshelfwizard.h.
Referenced by BtBookshelfWizard(), languagesPage(), and selectedLanguages().
m_removeWorksPage
BtBookshelfWorksPage* const BtBookshelfWizard::m_removeWorksPage private
Definition at line 84 of file btbookshelfwizard.h.
Referenced by BtBookshelfWizard(), and selectedWorks().
m_sourcesPage
BtBookshelfSourcesPage* const BtBookshelfWizard::m_sourcesPage private
Definition at line 79 of file btbookshelfwizard.h.
Referenced by BtBookshelfWizard(), and selectedSources().
m_sourcesProgressPage
BtBookshelfSourcesProgressPage* const BtBookshelfWizard::m_sourcesProgressPage private
Definition at line 80 of file btbookshelfwizard.h.
Referenced by BtBookshelfWizard(), and stopDownload().
m_taskPage
BtBookshelfTaskPage* const BtBookshelfWizard::m_taskPage private
Definition at line 78 of file btbookshelfwizard.h.
Referenced by BtBookshelfWizard(), installPath(), selectedWorks(), and taskType().
m_updateWorksPage
BtBookshelfWorksPage* const BtBookshelfWizard::m_updateWorksPage private
Definition at line 83 of file btbookshelfwizard.h.
Referenced by BtBookshelfWizard(), installPath(), and selectedWorks().
The documentation for this class was generated from the following files:
btbookshelfwizard.h
btbookshelfwizard.cpp