BibleTime: CDisplaySettingsPage Class Reference
CDisplaySettingsPage Class Reference
#include <cdisplaysettings.h>
Public Member Functions
CDisplaySettingsPage (CConfigurationDialog *parent=nullptr)
void save () const final override
Public Member Functions inherited from BtConfigDialog::Page
Page (QIcon const &icon, QWidget *const parent=nullptr)
void setHeaderText (QString const &headerText)
~Page () noexcept override
Static Public Member Functions
static void resetLanguage ()
Protected Member Functions
void retranslateUi ()
Private Slots
void updateStylePreview ()
Private Member Functions
void initSwordLocaleCombo ()
Static Private Member Functions
static QList< QString > bookNameAbbreviationsTryVector ()
Private Attributes
QLabel * m_availableLabel
QLabel * m_languageNamesLabel
QComboBox * m_lightDarkCombo
QLabel * m_lightDarkLabel
QLabel * m_previewLabel
QCheckBox * m_showLogoCheck
QLabel * m_showLogoLabel
QComboBox * m_styleChooserCombo
QLabel * m_stylePreviewViewer
QComboBox * m_swordLocaleCombo
QLabel * m_transifexLabel
Detailed Description
Definition at line 27 of file cdisplaysettings.h.
Constructor & Destructor Documentation
CDisplaySettingsPage()
CDisplaySettingsPage::CDisplaySettingsPage (CConfigurationDialog * parent = nullptr)
Initializes the startup section of the OD.
Definition at line 46 of file cdisplaysettings.cpp.
References CDisplayTemplateMgr::activeTemplateName(), CDisplayTemplateMgr::availableTemplates(), BT_CONNECT, btConfig(), initSwordLocaleCombo(), CDisplayTemplateMgr::instance(), m_availableLabel, m_languageNamesLabel, m_lightDarkCombo, m_lightDarkLabel, m_previewLabel, m_showLogoCheck, m_showLogoLabel, m_styleChooserCombo, m_stylePreviewViewer, m_swordLocaleCombo, m_transifexLabel, retranslateUi(), and updateStylePreview().
Member Function Documentation
bookNameAbbreviationsTryVector()
QList< QString > CDisplaySettingsPage::bookNameAbbreviationsTryVector () static private
Definition at line 168 of file cdisplaysettings.cpp.
References BtConfig::booknameLanguage(), btConfig(), and Language::fromAbbrev().
Referenced by initSwordLocaleCombo(), and resetLanguage().
initSwordLocaleCombo()
void CDisplaySettingsPage::initSwordLocaleCombo () private
Definition at line 189 of file cdisplaysettings.cpp.
References bookNameAbbreviationsTryVector(), util::tool::fixSwordBcp47(), Language::fromAbbrev(), BtLocaleMgr::internalSwordLocales(), and m_swordLocaleCombo.
Referenced by CDisplaySettingsPage().
resetLanguage()
void CDisplaySettingsPage::resetLanguage () static
Definition at line 147 of file cdisplaysettings.cpp.
References bookNameAbbreviationsTryVector(), BT_ASSERT, btConfig(), util::tool::fixSwordBcp47(), BtLocaleMgr::internalSwordLocales(), and BtConfigCore::setValue().
Referenced by BibleTimeApp::initBackends().
retranslateUi()
void CDisplaySettingsPage::retranslateUi () protected
Definition at line 117 of file cdisplaysettings.cpp.
References m_availableLabel, m_languageNamesLabel, m_lightDarkCombo, m_lightDarkLabel, m_previewLabel, m_showLogoLabel, m_swordLocaleCombo, m_transifexLabel, BtConfigDialog::Page::setHeaderText(), and updateStylePreview().
Referenced by CDisplaySettingsPage().
save()
void CDisplaySettingsPage::save () const final override virtual
Implements BtConfigDialog::Page.
Definition at line 360 of file cdisplaysettings.cpp.
References btConfig(), m_lightDarkCombo, m_showLogoCheck, m_styleChooserCombo, m_swordLocaleCombo, and BtConfigCore::setValue().
updateStylePreview
void CDisplaySettingsPage::updateStylePreview () private slot
Update the style preview widget.
Definition at line 225 of file cdisplaysettings.cpp.
References ColorManager::getBackgroundColor(), ColorManager::getForegroundColor(), Rendering::CTextRendering::KeyTreeItem::Settings::highlight, m_styleChooserCombo, m_stylePreviewViewer, Rendering::CTextRendering::renderKeyTree(), ColorManager::replaceColors(), and Rendering::CDisplayRendering::setDisplayTemplateName().
Referenced by CDisplaySettingsPage(), and retranslateUi().
Member Data Documentation
m_availableLabel
QLabel* CDisplaySettingsPage::m_availableLabel private
Definition at line 62 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), and retranslateUi().
m_languageNamesLabel
QLabel* CDisplaySettingsPage::m_languageNamesLabel private
Definition at line 56 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), and retranslateUi().
m_lightDarkCombo
QComboBox* CDisplaySettingsPage::m_lightDarkCombo private
Definition at line 59 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), retranslateUi(), and save().
m_lightDarkLabel
QLabel* CDisplaySettingsPage::m_lightDarkLabel private
Definition at line 58 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), and retranslateUi().
m_previewLabel
QLabel* CDisplaySettingsPage::m_previewLabel private
Definition at line 64 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), and retranslateUi().
m_showLogoCheck
QCheckBox* CDisplaySettingsPage::m_showLogoCheck private
Definition at line 55 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), and save().
m_showLogoLabel
QLabel* CDisplaySettingsPage::m_showLogoLabel private
Definition at line 54 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), and retranslateUi().
m_styleChooserCombo
QComboBox* CDisplaySettingsPage::m_styleChooserCombo private
Definition at line 61 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), save(), and updateStylePreview().
m_stylePreviewViewer
QLabel* CDisplaySettingsPage::m_stylePreviewViewer private
Definition at line 63 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), and updateStylePreview().
m_swordLocaleCombo
QComboBox* CDisplaySettingsPage::m_swordLocaleCombo private
Definition at line 57 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), initSwordLocaleCombo(), retranslateUi(), and save().
m_transifexLabel
QLabel* CDisplaySettingsPage::m_transifexLabel private
Definition at line 60 of file cdisplaysettings.h.
Referenced by CDisplaySettingsPage(), and retranslateUi().
The documentation for this class was generated from the following files:
cdisplaysettings.h
cdisplaysettings.cpp