BibleTime: CBibleReadWindow Class Reference
CBibleReadWindow Class Reference
#include <cbiblereadwindow.h>
Public Slots
void nextBook ()
void nextChapter ()
void nextVerse ()
void previousBook ()
void previousChapter ()
void previousVerse ()
void reload (CSwordBackend::SetupChangedReason reason) override
Public Slots inherited from CDisplayWindow
void lookupKey (QString const &key)
virtual void reload (CSwordBackend::SetupChangedReason reason)
void slotAddModule (int index, QString module)
void slotRemoveModule (int index)
void slotReplaceModule (int index, QString newModule)
Public Member Functions
void applyProfileSettings (BtConfigCore const &windowConf) override
Loads the settings of this window from configuration.
CBibleReadWindow (QList< CSwordModuleInfo * > const &modules, CMDIArea *parent)
CSwordModuleInfo::ModuleType moduleType () const override
void storeProfileSettings (BtConfigCore &windowConf) const override
Stores the settings of this window to configuration.
Public Member Functions inherited from CDisplayWindow
BtActionCollection * actionCollection () const
BibleTime * btMainWindow ()
QToolBar * buttonsToolBar () const
virtual void copyDisplayedText ()
const DisplayOptions & displayOptions () const
BtModelViewReadDisplay * displayWidget () const
const FilterOptions & filterOptions () const
int getFirstSelectedIndex () const
int getLastSelectedIndex () const
const QStringList & getModuleList () const
CSwordKey * getMouseClickedKey () const
int getSelectedColumn () const
bool hasSelectedText ()
BTHistory * history ()
bool init ()
bool isReady () const
CSwordKey * key () const
CKeyChooser * keyChooser () const
QToolBar * mainToolBar () const
CMDIArea * mdi () const
BtConstModuleList modules () const
void setButtonsToolBar (QToolBar *bar)
void setDisplaySettingsButton (BtDisplaySettingsButton *button)
void setDisplayWidget (BtModelViewReadDisplay *newDisplay)
void setMainToolBar (QToolBar *bar)
virtual bool syncAllowed () const
void windowActivated ()
QString windowCaption ()
Static Public Member Functions
static void insertKeyboardActions (BtActionCollection *const a)
Static Public Member Functions inherited from CDisplayWindow
static void insertKeyboardActions (BtActionCollection *const a)
Protected Slots
void copyDisplayedText () override
void lookupSwordKey (CSwordKey *newKey) override
void saveChapterHTML ()
void saveChapterPlain ()
void syncWindows ()
Protected Slots inherited from CDisplayWindow
void lookup ()
virtual void modulesChanged ()
void printAll ()
void printAnchorWithText ()
void saveRawHTML ()
Protected Member Functions
bool eventFilter (QObject *o, QEvent *e) override
void initActions () override
void initView () override
void setupPopupMenu () override
void updatePopupMenu () override
Protected Member Functions inherited from CDisplayWindow
CDisplayWindow (const QList< CSwordModuleInfo * > &modules, CMDIArea *parent)
void clearMainWindowToolBars ()
QToolBar * headerBar () const
template<typename ... Args>
QAction & initAddAction (Args &&... args)
virtual void initConnections ()
virtual void initToolbars ()
virtual void lookupSwordKey (CSwordKey *)
BtModuleChooserBar * moduleChooserBar () const
QMenu * popup ()
‍** Returns the installed popup menu. *‍/
void setDisplayOptions (DisplayOptions const &v)
void setFilterOptions (FilterOptions const &v)
void setKeyChooser (CKeyChooser *ck)
void setModuleChooserBar (BtModuleChooserBar *bar)
void setToolBarsHidden ()
virtual void setupMainWindowToolBars ()
~CDisplayWindow () override
Protected Attributes
struct {
struct {
QAction * byReferences
QAction * chapter
QAction * referenceAndText
QAction * referenceOnly
QAction * referenceTextOnly
QAction * selectedText
} copy
QMenu * copyMenu
QAction * findStrongs
QAction * findText
struct {
QAction * chapter
QAction * reference
} print
QMenu * printMenu
struct {
QAction * chapterAsHTML
QAction * chapterAsPlain
QAction * referenceAndText
} save
QMenu * saveMenu
} m_actions
Protected Attributes inherited from CDisplayWindow
struct CDisplayWindow::ActionsStruct m_actions
Private Member Functions
void saveChapter (CExportManager::Format const format)
CSwordVerseKey * verseKey ()
Additional Inherited Members
Signals inherited from CDisplayWindow
void sigDisplayOptionsChanged (const DisplayOptions &displayOptions)
void sigFilterOptionsChanged (const FilterOptions &filterOptions)
void sigKeyChanged (CSwordKey *key)
void sigModuleAdded (int index, QString module)
void sigModuleListChanged ()
void sigModuleListSet (QStringList modules)
void sigModuleRemoved (int index)
void sigModuleReplaced (int index, QString newModule)
void sigModulesChanged (const BtConstModuleList &modules)
Detailed Description
Definition at line 30 of file cbiblereadwindow.h.
Constructor & Destructor Documentation
CBibleReadWindow()
CBibleReadWindow::CBibleReadWindow (QList< CSwordModuleInfo * > const & modules, CMDIArea * parent) inline
Definition at line 36 of file cbiblereadwindow.h.
Member Function Documentation
applyProfileSettings()
void CBibleReadWindow::applyProfileSettings (BtConfigCore const & windowConf) override virtual
Loads the settings of this window from configuration.
Parameters
[in] windowConf The locked configuration group.
Note
We don't use restoreGeometry/saveGeometry for MDI subwindows, because they give slightly incorrect results with some window managers. Might be related to Qt bug QTBUG-7634.
Reimplemented from CDisplayWindow.
Definition at line 38 of file cbiblereadwindow.cpp.
References CDisplayWindow::applyProfileSettings(), CDisplayWindow::displayOptions(), CDisplayWindow::filterOptions(), BtConfig::loadDisplayOptionsFromGroup(), BtConfig::loadFilterOptionsFromGroup(), CDisplayWindow::lookup(), CDisplayWindow::setDisplayOptions(), CDisplayWindow::setFilterOptions(), CDisplayWindow::sigDisplayOptionsChanged(), and CDisplayWindow::sigFilterOptionsChanged().
copyDisplayedText
void CBibleReadWindow::copyDisplayedText () override protected slot
Copies the current chapter into the clipboard.
Definition at line 306 of file cbiblereadwindow.cpp.
References CSwordVerseKey::bookName(), CSwordVerseKey::chapter(), CExportManager::copyKey(), CDisplayWindow::displayOptions(), CDisplayWindow::filterOptions(), CDisplayWindow::modules(), CSwordVerseKey::setLowerBound(), CSwordVerseKey::setUpperBound(), CSwordVerseKey::setVerse(), CExportManager::Text, CSwordBibleModuleInfo::verseCount(), and verseKey().
Referenced by initActions().
eventFilter()
bool CBibleReadWindow::eventFilter (QObject * o, QEvent * e) override protected
No descriptions
Definition at line 368 of file cbiblereadwindow.cpp.
References syncWindows().
initActions()
void CBibleReadWindow::initActions () override protected virtual
Initializes the internel keyboard actions.
Reimplemented from CDisplayWindow.
Definition at line 123 of file cbiblereadwindow.cpp.
References BtActionCollection::action(), CDisplayWindow::actionCollection(), CResMgr::displaywindows::general::findStrongs::actionName, BtModelViewReadDisplay::copyAnchorTextOnly(), BtModelViewReadDisplay::copyAnchorWithText(), copyDisplayedText(), CDisplayWindow::displayWidget(), CDisplayWindow::initActions(), CDisplayWindow::initAddAction(), insertKeyboardActions(), m_actions, nextBook(), nextChapter(), nextVerse(), previousBook(), previousChapter(), previousVerse(), CDisplayWindow::printAll(), CDisplayWindow::printAnchorWithText(), BtActionCollection::readShortcuts(), BtModelViewReadDisplay::saveAnchorWithText(), saveChapterHTML(), and saveChapterPlain().
initView()
void CBibleReadWindow::initView () override protected virtual
Initialize the view of this display window.
Reimplemented from CDisplayWindow.
Definition at line 186 of file cbiblereadwindow.cpp.
References CDisplayWindow::initView().
insertKeyboardActions()
void CBibleReadWindow::insertKeyboardActions (BtActionCollection *const a) static
Reimplementation.
Definition at line 61 of file cbiblereadwindow.cpp.
References CResMgr::displaywindows::bibleWindow::nextBook::accel, CResMgr::displaywindows::bibleWindow::previousBook::accel, CResMgr::displaywindows::bibleWindow::nextChapter::accel, CResMgr::displaywindows::bibleWindow::previousChapter::accel, CResMgr::displaywindows::bibleWindow::nextVerse::accel, CResMgr::displaywindows::bibleWindow::previousVerse::accel, and BtActionCollection::addAction().
Referenced by initActions().
lookupSwordKey
void CBibleReadWindow::lookupSwordKey (CSwordKey * newKey) override protected slot
Definition at line 389 of file cbiblereadwindow.cpp.
References CDisplayWindow::lookupSwordKey(), and syncWindows().
moduleType()
CSwordModuleInfo::ModuleType CBibleReadWindow::moduleType () const inline override virtual
Reimplemented from CDisplayWindow.
Definition at line 41 of file cbiblereadwindow.h.
References CSwordModuleInfo::Bible.
nextBook
void CBibleReadWindow::nextBook () slot
Moves to the next book.
Definition at line 256 of file cbiblereadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseBook, and verseKey().
Referenced by initActions().
nextChapter
void CBibleReadWindow::nextChapter () slot
Moves to the next book.
Definition at line 270 of file cbiblereadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseChapter, and verseKey().
Referenced by initActions().
nextVerse
void CBibleReadWindow::nextVerse () slot
Moves to the next book.
Definition at line 284 of file cbiblereadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseVerse, and verseKey().
Referenced by initActions().
previousBook
void CBibleReadWindow::previousBook () slot
Moves one book behind.
Definition at line 263 of file cbiblereadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseBook, and verseKey().
Referenced by initActions().
previousChapter
void CBibleReadWindow::previousChapter () slot
Moves one book behind.
Definition at line 277 of file cbiblereadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseChapter, and verseKey().
Referenced by initActions().
previousVerse
void CBibleReadWindow::previousVerse () slot
Moves one book behind.
Definition at line 291 of file cbiblereadwindow.cpp.
References CDisplayWindow::key(), CDisplayWindow::keyChooser(), CKeyChooser::setKey(), CSwordVerseKey::UseVerse, and verseKey().
Referenced by initActions().
reload
void CBibleReadWindow::reload (CSwordBackend::SetupChangedReason reason) override slot
Definition at line 352 of file cbiblereadwindow.cpp.
References CDisplayWindow::actionCollection(), CSwordBackend::instance(), CDisplayWindow::keyChooser(), CDisplayWindow::m_modules, BtActionCollection::readShortcuts(), CKeyChooser::refreshContent(), CDisplayWindow::reload(), CSwordVerseKey::setLocale(), and verseKey().
saveChapter()
void CBibleReadWindow::saveChapter (CExportManager::Format const format) private
Definition at line 331 of file cbiblereadwindow.cpp.
References CSwordVerseKey::book(), CSwordVerseKey::chapter(), CDisplayWindow::displayOptions(), CDisplayWindow::filterOptions(), CDisplayWindow::getMouseClickedKey(), CDisplayWindow::key(), CDisplayWindow::modules(), CExportManager::saveKey(), CSwordVerseKey::setLowerBound(), CSwordVerseKey::setUpperBound(), CSwordVerseKey::setVerse(), CSwordBibleModuleInfo::verseCount(), and verseKey().
Referenced by saveChapterHTML(), and saveChapterPlain().
saveChapterHTML
void CBibleReadWindow::saveChapterHTML () protected slot
Saves the chapter as valid HTML page.
Definition at line 322 of file cbiblereadwindow.cpp.
References CExportManager::HTML, and saveChapter().
Referenced by initActions().
saveChapterPlain
void CBibleReadWindow::saveChapterPlain () protected slot
Saves the chapter as valid HTML page.
Definition at line 327 of file cbiblereadwindow.cpp.
References saveChapter(), and CExportManager::Text.
Referenced by initActions().
setupPopupMenu()
void CBibleReadWindow::setupPopupMenu () override protected virtual
Reimplementation.
Reimplemented from CDisplayWindow.
Definition at line 193 of file cbiblereadwindow.cpp.
References BT_CONNECT, btApp, util::tool::getIconForModule(), m_actions, CDisplayWindow::modules(), CDisplayWindow::popup(), and CDisplayWindow::saveRawHTML().
storeProfileSettings()
void CBibleReadWindow::storeProfileSettings (BtConfigCore & conf) const override virtual
Stores the settings of this window to configuration.
Parameters
[in] windowConf The locked configuration group.
Store the settings of this window in the given CProfileWindow object.
Note
We don't use saveGeometry/restoreGeometry for MDI subwindows, because they give slightly incorrect results with some window managers. Might be related to Qt bug QTBUG-7634.
Reimplemented from CDisplayWindow.
Definition at line 52 of file cbiblereadwindow.cpp.
References CDisplayWindow::displayOptions(), CDisplayWindow::filterOptions(), BtConfig::storeDisplayOptionsToGroup(), BtConfig::storeFilterOptionsToGroup(), and CDisplayWindow::storeProfileSettings().
syncWindows
void CBibleReadWindow::syncWindows () protected slot
Definition at line 394 of file cbiblereadwindow.cpp.
References CSwordKey::key(), CDisplayWindow::key(), CDisplayWindow::lookupKey(), CDisplayWindow::mdi(), and CDisplayWindow::syncAllowed().
Referenced by eventFilter(), and lookupSwordKey().
updatePopupMenu()
void CBibleReadWindow::updatePopupMenu () override protected virtual
Reimplemented.
Reimplemented from CDisplayWindow.
Definition at line 238 of file cbiblereadwindow.cpp.
References CDisplayWindow::displayWidget(), CDisplayWindow::hasSelectedText(), and m_actions.
verseKey()
CSwordVerseKey * CBibleReadWindow::verseKey () private
Wrapper around key() to return the right type of key.
wrapper around key() to return the right type of key.
Definition at line 298 of file cbiblereadwindow.cpp.
References BT_ASSERT, and CDisplayWindow::key().
Referenced by copyDisplayedText(), nextBook(), nextChapter(), nextVerse(), previousBook(), previousChapter(), previousVerse(), reload(), and saveChapter().
Member Data Documentation
byReferences
QAction* CBibleReadWindow::byReferences
Definition at line 67 of file cbiblereadwindow.h.
chapter
QAction* CBibleReadWindow::chapter
Definition at line 65 of file cbiblereadwindow.h.
chapterAsHTML
QAction* CBibleReadWindow::chapterAsHTML
Definition at line 75 of file cbiblereadwindow.h.
chapterAsPlain
QAction* CBibleReadWindow::chapterAsPlain
Definition at line 74 of file cbiblereadwindow.h.
copy
struct { ... } CBibleReadWindow::copy
copyMenu
QMenu* CBibleReadWindow::copyMenu
Definition at line 60 of file cbiblereadwindow.h.
findStrongs
QAction* CBibleReadWindow::findStrongs
Definition at line 58 of file cbiblereadwindow.h.
findText
QAction* CBibleReadWindow::findText
Definition at line 57 of file cbiblereadwindow.h.
m_actions
struct { ... } CBibleReadWindow::m_actions
Referenced by initActions(), setupPopupMenu(), and updatePopupMenu().
print
struct { ... } CBibleReadWindow::print
printMenu
QMenu* CBibleReadWindow::printMenu
Definition at line 79 of file cbiblereadwindow.h.
reference
QAction* CBibleReadWindow::reference
Definition at line 81 of file cbiblereadwindow.h.
referenceAndText
QAction* CBibleReadWindow::referenceAndText
Definition at line 64 of file cbiblereadwindow.h.
referenceOnly
QAction* CBibleReadWindow::referenceOnly
Definition at line 62 of file cbiblereadwindow.h.
referenceTextOnly
QAction* CBibleReadWindow::referenceTextOnly
Definition at line 63 of file cbiblereadwindow.h.
save
struct { ... } CBibleReadWindow::save
saveMenu
QMenu* CBibleReadWindow::saveMenu
Definition at line 71 of file cbiblereadwindow.h.
selectedText
QAction* CBibleReadWindow::selectedText
Definition at line 66 of file cbiblereadwindow.h.
The documentation for this class was generated from the following files:
cbiblereadwindow.h
cbiblereadwindow.cpp