BibleTime: BtBookshelfGroupingMenu Class Reference
BtBookshelfGroupingMenu Class Reference
#include <btbookshelfgroupingmenu.h>
Public Slots
void setGrouping (BtBookshelfTreeModel::Grouping const &grouping)
Signals
void signalGroupingOrderChanged (const BtBookshelfTreeModel::Grouping &)
Public Member Functions
BtBookshelfGroupingMenu (bool showNoGrouping, QWidget *parent=nullptr)
BtBookshelfGroupingMenu (QWidget *parent=nullptr)
Private Member Functions
void initMenu (bool showNoGrouping)
void retranslateUi ()
Private Attributes
QActionGroup * m_groupingActionGroup
QAction * m_groupingCatAction
QAction * m_groupingCatLangAction
QAction * m_groupingLangAction
QAction * m_groupingLangCatAction
QAction * m_groupingNoneAction
Detailed Description
Definition at line 26 of file btbookshelfgroupingmenu.h.
Constructor & Destructor Documentation
BtBookshelfGroupingMenu() [1/2]
BtBookshelfGroupingMenu::BtBookshelfGroupingMenu (QWidget * parent = nullptr) inline explicit
Definition at line 29 of file btbookshelfgroupingmenu.h.
References initMenu().
BtBookshelfGroupingMenu() [2/2]
BtBookshelfGroupingMenu::BtBookshelfGroupingMenu (bool showNoGrouping, QWidget * parent = nullptr) inline explicit
Definition at line 32 of file btbookshelfgroupingmenu.h.
References initMenu().
Member Function Documentation
initMenu()
void BtBookshelfGroupingMenu::initMenu (bool showNoGrouping) private
Definition at line 58 of file btbookshelfgroupingmenu.cpp.
References BT_CONNECT, m_groupingActionGroup, m_groupingCatAction, m_groupingCatLangAction, m_groupingLangAction, m_groupingLangCatAction, m_groupingNoneAction, retranslateUi(), and signalGroupingOrderChanged().
Referenced by BtBookshelfGroupingMenu(), and BtBookshelfGroupingMenu().
retranslateUi()
void BtBookshelfGroupingMenu::retranslateUi () private
Definition at line 106 of file btbookshelfgroupingmenu.cpp.
References m_groupingCatAction, m_groupingCatLangAction, m_groupingLangAction, m_groupingLangCatAction, and m_groupingNoneAction.
Referenced by initMenu().
setGrouping
void BtBookshelfGroupingMenu::setGrouping (BtBookshelfTreeModel::Grouping const & grouping) slot
Definition at line 39 of file btbookshelfgroupingmenu.cpp.
References BT_ASSERT, m_groupingCatAction, m_groupingCatLangAction, m_groupingLangAction, m_groupingLangCatAction, and m_groupingNoneAction.
Referenced by BtBookshelfWorksPage::BtBookshelfWorksPage(), BtOpenWorkActionMenu::postBuildMenu(), and BtBookshelfWidget::setTreeModel().
signalGroupingOrderChanged
void BtBookshelfGroupingMenu::signalGroupingOrderChanged (const BtBookshelfTreeModel::Grouping &) signal
Referenced by BtBookshelfWorksPage::BtBookshelfWorksPage(), initMenu(), BtBookshelfWidget::initMenus(), and BtOpenWorkActionMenu::postBuildMenu().
Member Data Documentation
m_groupingActionGroup
QActionGroup* BtBookshelfGroupingMenu::m_groupingActionGroup private
Definition at line 48 of file btbookshelfgroupingmenu.h.
Referenced by initMenu().
m_groupingCatAction
QAction* BtBookshelfGroupingMenu::m_groupingCatAction private
Definition at line 50 of file btbookshelfgroupingmenu.h.
Referenced by initMenu(), retranslateUi(), and setGrouping().
m_groupingCatLangAction
QAction* BtBookshelfGroupingMenu::m_groupingCatLangAction private
Definition at line 49 of file btbookshelfgroupingmenu.h.
Referenced by initMenu(), retranslateUi(), and setGrouping().
m_groupingLangAction
QAction* BtBookshelfGroupingMenu::m_groupingLangAction private
Definition at line 52 of file btbookshelfgroupingmenu.h.
Referenced by initMenu(), retranslateUi(), and setGrouping().
m_groupingLangCatAction
QAction* BtBookshelfGroupingMenu::m_groupingLangCatAction private
Definition at line 51 of file btbookshelfgroupingmenu.h.
Referenced by initMenu(), retranslateUi(), and setGrouping().
m_groupingNoneAction
QAction* BtBookshelfGroupingMenu::m_groupingNoneAction private
Definition at line 53 of file btbookshelfgroupingmenu.h.
Referenced by initMenu(), retranslateUi(), and setGrouping().
The documentation for this class was generated from the following files:
btbookshelfgroupingmenu.h
btbookshelfgroupingmenu.cpp