BibleTime: ColorManager::anonymous_namespace{colormanager.cpp} Namespace Reference
ColorManager::anonymous_namespace{colormanager.cpp} Namespace Reference
Typedefs
using ColorMaps = std::map< QString, std::map< QString, QString > >
Functions
auto const & colorMaps ()
ColorMaps createColorMaps ()
bool darkMode ()
QString getColorByPattern (QString const &pattern, QString const &templateName)
Typedef Documentation
ColorMaps
using ColorManager::anonymous_namespace{colormanager.cpp}::ColorMaps = typedef std::map<QString, std::map<QString, QString> >
Definition at line 46 of file colormanager.cpp.
Function Documentation
colorMaps()
auto const & ColorManager::anonymous_namespace{colormanager.cpp}::colorMaps ()
Definition at line 120 of file colormanager.cpp.
References colorMaps(), and createColorMaps().
Referenced by colorMaps(), createColorMaps(), and getColorByPattern().
createColorMaps()
ColorMaps ColorManager::anonymous_namespace{colormanager.cpp}::createColorMaps ()
Definition at line 48 of file colormanager.cpp.
References colorMaps(), createColorMaps(), and darkMode().
Referenced by colorMaps(), and createColorMaps().
darkMode()
bool ColorManager::anonymous_namespace{colormanager.cpp}::darkMode ()
Definition at line 34 of file colormanager.cpp.
References darkMode().
Referenced by createColorMaps(), and darkMode().
getColorByPattern()
QString ColorManager::anonymous_namespace{colormanager.cpp}::getColorByPattern (QString const & pattern, QString const & templateName)
Definition at line 125 of file colormanager.cpp.
References BT_ASSERT, colorMaps(), and getColorByPattern().
Referenced by getColorByPattern().