BibleTime: util::cp1252 Namespace Reference
util::cp1252 Namespace Reference
Functions
QByteArray fromUnicode (QString const &str)
QString toUnicode (QByteArray const &data)
Function Documentation
fromUnicode()
QByteArray util::cp1252::fromUnicode (QString const & str)
Definition at line 31 of file cp1252.cpp.
References BT_ASSERT.
Referenced by CSwordTreeKey::setKey(), and CSwordLDKey::setKey().
toUnicode()
QString util::cp1252::toUnicode (QByteArray const & data)
Definition at line 23 of file cp1252.cpp.
References BT_ASSERT.
Referenced by CSwordLexiconModuleInfo::entries(), CSwordTreeKey::getLocalNameUnicode(), CSwordLDKey::key(), and CSwordTreeKey::key().