BibleTime: btbookshelfwizard.cpp File Reference
btbookshelfwizard.cpp File Reference
#include "btbookshelfwizard.h"
#include <QAbstractButton>
#include <QApplication>
#include <QByteArray>
#include <QDialog>
#include <QKeyEvent>
#include <QMessageBox>
#include <QPushButton>
#include <QRect>
#include "../../backend/config/btconfig.h"
#include "../../backend/drivers/btmoduleset.h"
#include "../../util/btassert.h"
#include "btbookshelfinstallfinalpage.h"
#include "btbookshelflanguagespage.h"
#include "btbookshelfremovefinalpage.h"
#include "btbookshelfsourcespage.h"
#include "btbookshelfsourcesprogresspage.h"
#include "btbookshelftaskpage.h"
#include "btbookshelfwizardenums.h"
#include "btbookshelfworkspage.h"
Namespaces
namespace anonymous_namespace{btbookshelfwizard.cpp}
Functions
static void replaceButtonText (QWizard *wizard, QWizard::WizardButton which, const QString &text)
void translateQWizardStandardButtons (QWizard *wizard)
Variables
bool anonymous_namespace{btbookshelfwizard.cpp}::autoSourcesUpdate = true
auto const anonymous_namespace{btbookshelfwizard.cpp}::GeometryKey = QStringLiteral("GUI/BookshelfWizard/geometry")
auto const anonymous_namespace{btbookshelfwizard.cpp}::LanguagesKey = QStringLiteral("GUI/BookshelfWizard/languages")
auto const anonymous_namespace{btbookshelfwizard.cpp}::SourcesKey = QStringLiteral("GUI/BookshelfWizard/sources")
Function Documentation
replaceButtonText()
static void replaceButtonText (QWizard * wizard, QWizard::WizardButton which, const QString & text) static
Definition at line 80 of file btbookshelfwizard.cpp.
Referenced by translateQWizardStandardButtons().
translateQWizardStandardButtons()
void translateQWizardStandardButtons (QWizard * wizard)
Definition at line 87 of file btbookshelfwizard.cpp.
References replaceButtonText().
Referenced by BtBookshelfWizard::retranslateUi(), and BtEditTextWizard::retranslateUi().