BibleTime: BtBookshelfLanguagesPage Class Reference
BtBookshelfLanguagesPage Class Reference final
#include <btbookshelflanguagespage.h>
Public Member Functions
BtBookshelfLanguagesPage (QWidget *parent=nullptr)
void initializeLanguages ()
void initializePage () final override
bool isComplete () const final override
int nextId () const final override
QStringList selectedLanguages () const
bool skipPage () const noexcept
Public Member Functions inherited from BtBookshelfWizardPage
BtBookshelfWizardPage (QWidget *parent=nullptr)
BtBookshelfWizard & btWizard () const noexcept
Private Slots
void slotDataChanged ()
Private Member Functions
void retranslateUi ()
Private Attributes
bool m_firstTimeInit = true
QListView * m_languagesListView
QStandardItemModel * m_model
QVBoxLayout * m_verticalLayout
Detailed Description
Definition at line 27 of file btbookshelflanguagespage.h.
Constructor & Destructor Documentation
BtBookshelfLanguagesPage()
BtBookshelfLanguagesPage::BtBookshelfLanguagesPage (QWidget * parent = nullptr)
Definition at line 44 of file btbookshelflanguagespage.cpp.
References BT_CONNECT, m_languagesListView, m_model, m_verticalLayout, and slotDataChanged().
Member Function Documentation
initializeLanguages()
void BtBookshelfLanguagesPage::initializeLanguages ()
Definition at line 99 of file btbookshelflanguagespage.cpp.
References BtInstallBackend::backend(), BtBookshelfWizardPage::btWizard(), m_model, BtBookshelfWizard::selectedSources(), and BtInstallBackend::source().
Referenced by BtBookshelfSourcesPage::nextId().
initializePage()
void BtBookshelfLanguagesPage::initializePage () final override
Definition at line 69 of file btbookshelflanguagespage.cpp.
References btConfig(), m_firstTimeInit, m_languagesListView, m_model, retranslateUi(), selectedLanguages(), and BtConfigCore::value().
isComplete()
bool BtBookshelfLanguagesPage::isComplete () const final override
Definition at line 125 of file btbookshelflanguagespage.cpp.
References selectedLanguages().
nextId()
int BtBookshelfLanguagesPage::nextId () const final override
Definition at line 66 of file btbookshelflanguagespage.cpp.
References installWorksPage.
retranslateUi()
void BtBookshelfLanguagesPage::retranslateUi () private
Definition at line 59 of file btbookshelflanguagespage.cpp.
Referenced by initializePage().
selectedLanguages()
QStringList BtBookshelfLanguagesPage::selectedLanguages () const
Definition at line 128 of file btbookshelflanguagespage.cpp.
References m_model.
Referenced by initializePage(), isComplete(), and BtBookshelfWizard::selectedLanguages().
skipPage()
bool BtBookshelfLanguagesPage::skipPage () const noexcept
Definition at line 120 of file btbookshelflanguagespage.cpp.
References m_model.
slotDataChanged
void BtBookshelfLanguagesPage::slotDataChanged () private slot
Definition at line 123 of file btbookshelflanguagespage.cpp.
Referenced by BtBookshelfLanguagesPage().
Member Data Documentation
m_firstTimeInit
bool BtBookshelfLanguagesPage::m_firstTimeInit = true private
Definition at line 52 of file btbookshelflanguagespage.h.
Referenced by initializePage().
m_languagesListView
QListView* BtBookshelfLanguagesPage::m_languagesListView private
Definition at line 53 of file btbookshelflanguagespage.h.
Referenced by BtBookshelfLanguagesPage(), and initializePage().
m_model
QStandardItemModel* BtBookshelfLanguagesPage::m_model private
Definition at line 55 of file btbookshelflanguagespage.h.
Referenced by BtBookshelfLanguagesPage(), initializeLanguages(), initializePage(), selectedLanguages(), and skipPage().
m_verticalLayout
QVBoxLayout* BtBookshelfLanguagesPage::m_verticalLayout private
Definition at line 54 of file btbookshelflanguagespage.h.
Referenced by BtBookshelfLanguagesPage().
The documentation for this class was generated from the following files:
btbookshelflanguagespage.h
btbookshelflanguagespage.cpp