BibleTime: Filters::TeiToHtml Class Reference
Filters::TeiToHtml Class Reference
TEI to HTML conversion filter.
#include <teitohtml.h>
Public Member Functions
bool handleToken (sword::SWBuf &buf, const char *token, sword::BasicFilterUserData *userData) override
TeiToHtml ()
Private Member Functions
void renderReference (const char *osisRef, sword::SWBuf &buf, sword::BasicFilterUserData *myUserData)
void renderTargetReference (const char *osisRef, sword::SWBuf &buf, sword::BasicFilterUserData *myUserData)
Detailed Description
TEI to HTML conversion filter.
Definition at line 37 of file teitohtml.h.
Constructor & Destructor Documentation
TeiToHtml()
Filters::TeiToHtml::TeiToHtml ()
Definition at line 33 of file teitohtml.cpp.
Member Function Documentation
handleToken()
bool Filters::TeiToHtml::handleToken (sword::SWBuf & buf, const char * token, sword::BasicFilterUserData * userData) override
Definition at line 39 of file teitohtml.cpp.
References renderReference(), and renderTargetReference().
renderReference()
void Filters::TeiToHtml::renderReference (const char * osisRef, sword::SWBuf & buf, sword::BasicFilterUserData * myUserData) private
Definition at line 111 of file teitohtml.cpp.
References CSwordModuleInfo::Bible, btConfig(), ReferenceManager::encodeHyperlink(), CSwordBackend::findFirstAvailableModule(), CSwordBackend::findModuleByName(), BtConfig::getDefaultSwordModuleByType(), CSwordBackend::instance(), CSwordModuleInfo::name(), ReferenceManager::parseVerseReference(), and CSwordModuleInfo::swordModule().
Referenced by handleToken().
renderTargetReference()
void Filters::TeiToHtml::renderTargetReference (const char * osisRef, sword::SWBuf & buf, sword::BasicFilterUserData * myUserData) private
Definition at line 166 of file teitohtml.cpp.
References ReferenceManager::encodeHyperlink(), CSwordBackend::instance(), CSwordModuleInfo::name(), and CSwordModuleInfo::swordModule().
Referenced by handleToken().
The documentation for this class was generated from the following files:
teitohtml.h
teitohtml.cpp