BibleTime: BtPrinter Class Reference
BtPrinter Class Reference final
Manages the print item queue and printing.
#include <btprinter.h>
Public Member Functions
BtPrinter (DisplayOptions const &displayOptions, FilterOptions const &filterOptions)
void printKeyTree (KeyTree const &)
Public Member Functions inherited from Rendering::CDisplayRendering
CDisplayRendering ()
CDisplayRendering (DisplayOptions const &displayOptions, FilterOptions const &filterOptions)
QString const & displayTemplateName () const noexcept
QString renderDisplayEntry (BtConstModuleList const &modules, QString const &key, CTextRendering::KeyTreeItem::Settings::KeyRenderingFace keyRendering=CTextRendering::KeyTreeItem::Settings::CompleteShort) const
void setDisplayTemplateName (QString displayTemplateName) noexcept
Public Member Functions inherited from Rendering::CTextRendering
CTextRendering (bool addText)
CTextRendering (bool addText, DisplayOptions const &displayOptions, FilterOptions const &filterOptions)
DisplayOptions const & displayOptions () const noexcept
FilterOptions const & filterOptions () const noexcept
QString renderKeyRange (CSwordVerseKey const &lowerBound, CSwordVerseKey const &upperBound, const BtConstModuleList &modules, const QString &hightlightKey=QString(), const KeyTreeItem::Settings &settings=KeyTreeItem::Settings())
QString renderKeyTree (KeyTree const &tree) const
QString renderSingleKey (const QString &key, const BtConstModuleList &modules, const KeyTreeItem::Settings &settings=KeyTreeItem::Settings())
void setDisplayOptions (DisplayOptions const &displayOptions) noexcept
void setFilterOptions (FilterOptions const &filterOptions) noexcept
virtual ~CTextRendering ()
Private Member Functions
QString entryLink (KeyTreeItem const &item, CSwordModuleInfo const &module) const override
QString finishText (QString const &text, KeyTree const &tree) const override
QString renderEntry (KeyTreeItem const &item, CSwordKey *const key=nullptr) const override
Additional Inherited Members
Public Types inherited from Rendering::CTextRendering
using KeyTree = std::list< KeyTreeItem >
Static Public Member Functions inherited from Rendering::CDisplayRendering
static QString keyToHTMLAnchor (QString const &key)
Protected Member Functions inherited from Rendering::CDisplayRendering
QString entryLink (KeyTreeItem const &item, CSwordModuleInfo const &module) const override
QString finishText (QString const &text, KeyTree const &tree) const override
Static Protected Member Functions inherited from Rendering::CTextRendering
static BtConstModuleList collectModules (KeyTree const &tree)
Protected Attributes inherited from Rendering::CTextRendering
bool const m_addText
DisplayOptions m_displayOptions
FilterOptions m_filterOptions
Detailed Description
Manages the print item queue and printing.
Definition at line 19 of file btprinter.h.
Constructor & Destructor Documentation
BtPrinter()
BtPrinter::BtPrinter (DisplayOptions const & displayOptions, FilterOptions const & filterOptions)
Definition at line 36 of file btprinter.cpp.
Member Function Documentation
entryLink()
QString BtPrinter::entryLink (KeyTreeItem const & item, CSwordModuleInfo const & module) const override private virtual
Reimplemented from Rendering::CTextRendering.
Definition at line 51 of file btprinter.cpp.
References CSwordModuleInfo::Bible, Rendering::CTextRendering::KeyTreeItem::key(), CSwordVerseKey::key(), Rendering::CTextRendering::KeyTreeItem::Settings::keyRenderingFace, CSwordVerseKey::setKey(), Rendering::CTextRendering::KeyTreeItem::settings(), CSwordVerseKey::shortText(), CSwordModuleInfo::type(), and CSwordVerseKey::verse().
finishText()
QString BtPrinter::finishText (QString const & text, KeyTree const & tree) const override private virtual
Reimplemented from Rendering::CTextRendering.
Definition at line 94 of file btprinter.cpp.
References CDisplayTemplateMgr::activeTemplateName(), BT_ASSERT, Rendering::CTextRendering::collectModules(), CDisplayTemplateMgr::fillTemplate(), CDisplayTemplateMgr::instance(), CDisplayTemplateMgr::Settings::langAbbrev, CDisplayTemplateMgr::Settings::pageCSS_ID, and CDisplayTemplateMgr::Settings::textDirection.
printKeyTree()
void BtPrinter::printKeyTree (KeyTree const & tree)
Definition at line 41 of file btprinter.cpp.
References Rendering::CTextRendering::renderKeyTree().
renderEntry()
QString BtPrinter::renderEntry (KeyTreeItem const & item, CSwordKey *const key = nullptr) const override private virtual
Reimplemented from Rendering::CTextRendering.
Definition at line 75 of file btprinter.cpp.
References Rendering::CTextRendering::KeyTreeItem::childList(), Rendering::CTextRendering::KeyTreeItem::getAlternativeContent(), and Rendering::CTextRendering::KeyTreeItem::hasAlternativeContent().
The documentation for this class was generated from the following files:
btprinter.h
btprinter.cpp