BibleTime: anonymous_namespace{bttipdialog.cpp} Namespace Reference
anonymous_namespace{bttipdialog.cpp} Namespace Reference
Functions
QString make_html (QWidget *widget, const QString &text)
QString make_style (QWidget *widget)
QString vertical_align (const QString &text)
Variables
auto const LastTipNumberKey = QStringLiteral("GUI/lastTipNumber")
Function Documentation
make_html()
QString anonymous_namespace{bttipdialog.cpp}::make_html (QWidget * widget, const QString & text) inline
Definition at line 65 of file bttipdialog.cpp.
References make_html(), make_style(), and vertical_align().
Referenced by make_html().
make_style()
QString anonymous_namespace{bttipdialog.cpp}::make_style (QWidget * widget) inline
Definition at line 46 of file bttipdialog.cpp.
References make_style().
Referenced by make_html(), and make_style().
vertical_align()
QString anonymous_namespace{bttipdialog.cpp}::vertical_align (const QString & text) inline
Definition at line 39 of file bttipdialog.cpp.
References vertical_align().
Referenced by make_html(), and vertical_align().
Variable Documentation
LastTipNumberKey
auto const anonymous_namespace{bttipdialog.cpp}::LastTipNumberKey = QStringLiteral("GUI/lastTipNumber")
Definition at line 70 of file bttipdialog.cpp.