BibleTime: BtInstallPageModel Class Reference
BtInstallPageModel Class Reference
#include <btinstallpagemodel.h>
Public Member Functions
BtInstallPageModel (Grouping const &grouping, QObject *const parent=nullptr)
int columnCount (QModelIndex const &parent=QModelIndex()) const final override
QVariant data (QModelIndex const &index, int role=Qt::DisplayRole) const final override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const final override
Public Member Functions inherited from BtBookshelfTreeModel
BtBookshelfTreeModel (BtConfigCore const &config, QString const &configKey, QObject *const parent=nullptr)
BtBookshelfTreeModel (Grouping const &grouping, QObject *parent=nullptr)
BtBookshelfTreeModel (QObject *parent=nullptr)
bool checkable () const
BtModuleSet const & checkedModules () const
int columnCount (QModelIndex const &parent=QModelIndex()) const override
QVariant data (CSwordModuleInfo &module, int role=Qt::DisplayRole) const
QVariant data (QModelIndex const &index, int role=Qt::DisplayRole) const override
CheckedBehavior defaultChecked () const
Qt::ItemFlags flags (QModelIndex const &index) const override
Grouping const & groupingOrder () const
bool hasChildren (QModelIndex const &parent=QModelIndex()) const override
QVariant headerData (int section, Qt::Orientation orientation, int role=Qt::DisplayRole) const override
QModelIndex index (int row, int column, QModelIndex const &parent=QModelIndex()) const override
CSwordModuleInfo * module (QModelIndex const &index) const
QList< CSwordModuleInfo * > modules () const
QModelIndex parent (QModelIndex const &index) const override
int rowCount (QModelIndex const &parent=QModelIndex()) const override
bool setData (QModelIndex const &index, QVariant const &value, int role) override
std::shared_ptr< QAbstractItemModel > sourceModel () const noexcept
~BtBookshelfTreeModel () override
Additional Inherited Members
Public Types inherited from BtBookshelfTreeModel
enum CheckedBehavior { CHECKED , UNCHECKED , MODULE_HIDDEN , MODULE_INDEXED }
enum Group : int { GROUP_CATEGORY = 0 , GROUP_LANGUAGE = 1 , GROUP_INDEXING }
enum ModuleRole { CheckStateRole = BtBookshelfModel::UserRole , UserRole = BtBookshelfModel::UserRole + 100 }
Public Slots inherited from BtBookshelfTreeModel
void setCheckable (bool checkable)
void setCheckedModules (BtConstModuleSet const &modules)
void setDefaultChecked (CheckedBehavior const b)
void setGroupingOrder (BtBookshelfTreeModel::Grouping const &groupingOrder, bool emitSignal=true)
void setSourceModel (std::shared_ptr< QAbstractItemModel > sourceModel)
Signals inherited from BtBookshelfTreeModel
void groupingOrderChanged (BtBookshelfTreeModel::Grouping newGrouping)
void moduleChecked (CSwordModuleInfo *module, bool checked)
Protected Slots inherited from BtBookshelfTreeModel
void moduleDataChanged (QModelIndex const &topLeft, QModelIndex const &bottomRight)
void moduleInserted (QModelIndex const &parent, int start, int end)
void moduleRemoved (QModelIndex const &parent, int start, int end)
Protected Member Functions inherited from BtBookshelfTreeModel
void resetData ()
Detailed Description
Definition at line 24 of file btinstallpagemodel.h.
Constructor & Destructor Documentation
BtInstallPageModel()
BtInstallPageModel::BtInstallPageModel (Grouping const & grouping, QObject *const parent = nullptr)
Definition at line 21 of file btinstallpagemodel.cpp.
References BtBookshelfTreeModel::setCheckable(), BtBookshelfTreeModel::setDefaultChecked(), and BtBookshelfTreeModel::UNCHECKED.
Member Function Documentation
columnCount()
int BtInstallPageModel::columnCount (QModelIndex const & parent = QModelIndex()) const final override
Definition at line 68 of file btinstallpagemodel.cpp.
References BtBookshelfTreeModel::getGroup(), and BtBookshelfTreeModel::parent().
data()
QVariant BtInstallPageModel::data (QModelIndex const & index, int role = Qt::DisplayRole) const final override
Definition at line 29 of file btinstallpagemodel.cpp.
References BtBookshelfTreeModel::data(), CSwordModuleInfo::Description, BtBookshelfTreeModel::getGroup(), BtBookshelfTreeModel::index(), CSwordBackend::instance(), BtBookshelfTreeModel::module(), and CSwordModuleInfo::ModuleVersion.
headerData()
QVariant BtInstallPageModel::headerData (int section, Qt::Orientation orientation, int role = Qt::DisplayRole) const final override
Definition at line 73 of file btinstallpagemodel.cpp.
References BtBookshelfTreeModel::getGroup().
The documentation for this class was generated from the following files:
btinstallpagemodel.h
btinstallpagemodel.cpp