BibleTime: BtBibleKeyWidget Class Reference
BtBibleKeyWidget Class Reference
#include <btbiblekeywidget.h>
Public Slots
void updateText ()
Signals
void changed (CSwordVerseKey *key)
Public Member Functions
BtBibleKeyWidget (CSwordBibleModuleInfo const *module, CSwordVerseKey *key, QWidget *parent=nullptr)
bool eventFilter (QObject *o, QEvent *e) override
bool setKey (CSwordVerseKey *key)
void setModule (const CSwordBibleModuleInfo *m=nullptr)
~BtBibleKeyWidget () override
Protected Member Functions
void enterEvent (QEnterEvent *event) override
void leaveEvent (QEvent *event) override
void resetDropDownButtons ()
void resizeEvent (QResizeEvent *event) override
Private Member Functions
void populateBookMenu (QMenu &menu)
void populateChapterMenu (QMenu &menu)
void populateVerseMenu (QMenu &menu)
Private Attributes
QWidget * m_dropDownButtons
QTimer m_dropDownHoverTimer
CSwordVerseKey * m_key
const CSwordBibleModuleInfo * m_module
QLineEdit * m_textbox
QString oldKey
bool updatelock
Detailed Description
Definition at line 25 of file btbiblekeywidget.h.
Constructor & Destructor Documentation
BtBibleKeyWidget()
BtBibleKeyWidget::BtBibleKeyWidget (CSwordBibleModuleInfo const * module, CSwordVerseKey * key, QWidget * parent = nullptr)
Definition at line 35 of file btbiblekeywidget.cpp.
References BT_CONNECT, changed(), if(), m_dropDownButtons, m_key, m_textbox, CSwordVerseKey::next(), populateBookMenu(), CSwordVerseKey::previous(), updatelock, CSwordVerseKey::UseBook, CSwordVerseKey::UseChapter, and CSwordVerseKey::UseVerse.
~BtBibleKeyWidget()
BtBibleKeyWidget::~BtBibleKeyWidget () override
Definition at line 229 of file btbiblekeywidget.cpp.
References m_dropDownButtons.
Member Function Documentation
changed
void BtBibleKeyWidget::changed (CSwordVerseKey * key) signal
Referenced by BtBibleKeyWidget(), and CBibleKeyChooser::CBibleKeyChooser().
enterEvent()
void BtBibleKeyWidget::enterEvent (QEnterEvent * event) override protected
Definition at line 254 of file btbiblekeywidget.cpp.
References m_dropDownButtons, m_dropDownHoverTimer, and resetDropDownButtons().
eventFilter()
bool BtBibleKeyWidget::eventFilter (QObject * o, QEvent * e) override
Definition at line 240 of file btbiblekeywidget.cpp.
References m_dropDownButtons, and m_dropDownHoverTimer.
leaveEvent()
void BtBibleKeyWidget::leaveEvent (QEvent * event) override protected
Definition at line 263 of file btbiblekeywidget.cpp.
References m_dropDownHoverTimer.
populateBookMenu()
void BtBibleKeyWidget::populateBookMenu (QMenu & menu) private
Definition at line 301 of file btbiblekeywidget.cpp.
References CSwordBibleModuleInfo::books(), and m_module.
Referenced by BtBibleKeyWidget().
populateChapterMenu()
void BtBibleKeyWidget::populateChapterMenu (QMenu & menu) private
Definition at line 306 of file btbiblekeywidget.cpp.
References CSwordVerseKey::bibleBook(), CSwordBibleModuleInfo::chapterCount(), m_key, and m_module.
populateVerseMenu()
void BtBibleKeyWidget::populateVerseMenu (QMenu & menu) private
Definition at line 312 of file btbiblekeywidget.cpp.
References CSwordVerseKey::bookName(), CSwordVerseKey::chapter(), m_key, m_module, and CSwordBibleModuleInfo::verseCount().
resetDropDownButtons()
void BtBibleKeyWidget::resetDropDownButtons () protected
Definition at line 274 of file btbiblekeywidget.cpp.
References m_dropDownButtons, and m_textbox.
Referenced by enterEvent(), and resizeEvent().
resizeEvent()
void BtBibleKeyWidget::resizeEvent (QResizeEvent * event) override protected
Definition at line 267 of file btbiblekeywidget.cpp.
References m_dropDownButtons, and resetDropDownButtons().
setKey()
bool BtBibleKeyWidget::setKey (CSwordVerseKey * key)
Definition at line 294 of file btbiblekeywidget.cpp.
References CSwordVerseKey::key(), m_key, and CSwordVerseKey::setKey().
Referenced by CBibleKeyChooser::setKey().
setModule()
void BtBibleKeyWidget::setModule (const CSwordBibleModuleInfo * m = nullptr)
Definition at line 233 of file btbiblekeywidget.cpp.
References m_key, m_module, and CSwordVerseKey::setModule().
Referenced by CBibleKeyChooser::setModules().
updateText
void BtBibleKeyWidget::updateText () slot
Definition at line 283 of file btbiblekeywidget.cpp.
References CSwordVerseKey::key(), m_key, and m_textbox.
Referenced by CBibleKeyChooser::updateKey().
Member Data Documentation
m_dropDownButtons
QWidget* BtBibleKeyWidget::m_dropDownButtons private
Definition at line 62 of file btbiblekeywidget.h.
Referenced by BtBibleKeyWidget(), enterEvent(), eventFilter(), resetDropDownButtons(), resizeEvent(), and ~BtBibleKeyWidget().
m_dropDownHoverTimer
QTimer BtBibleKeyWidget::m_dropDownHoverTimer private
Definition at line 63 of file btbiblekeywidget.h.
Referenced by enterEvent(), eventFilter(), and leaveEvent().
m_key
CSwordVerseKey* BtBibleKeyWidget::m_key private
Definition at line 58 of file btbiblekeywidget.h.
Referenced by BtBibleKeyWidget(), populateChapterMenu(), populateVerseMenu(), setKey(), setModule(), and updateText().
m_module
const CSwordBibleModuleInfo* BtBibleKeyWidget::m_module private
Definition at line 67 of file btbiblekeywidget.h.
Referenced by populateBookMenu(), populateChapterMenu(), populateVerseMenu(), and setModule().
m_textbox
QLineEdit* BtBibleKeyWidget::m_textbox private
Definition at line 60 of file btbiblekeywidget.h.
Referenced by BtBibleKeyWidget(), resetDropDownButtons(), and updateText().
oldKey
QString BtBibleKeyWidget::oldKey private
Definition at line 66 of file btbiblekeywidget.h.
updatelock
bool BtBibleKeyWidget::updatelock private
Definition at line 65 of file btbiblekeywidget.h.
Referenced by BtBibleKeyWidget().
The documentation for this class was generated from the following files:
btbiblekeywidget.h
btbiblekeywidget.cpp