BibleTime: BtBookmarksModelPrivate::BookmarkItemBase Class Reference
BtBookmarksModelPrivate::BookmarkItemBase Class Reference
Public Member Functions
void addChild (BookmarkItemBase *child)
BookmarkItemBase (BookmarkItemBase *parent=nullptr)
BookmarkItemBase (const BookmarkItemBase &other)
BookmarkItemBase * child (int index) const
int childCount () const
QList< BookmarkItemBase * > & children ()
Qt::ItemFlags flags () const
QIcon icon () const
int index () const
void insertChild (int index, BookmarkItemBase *child)
void insertChildren (int index, QList< BookmarkItemBase * > children)
BookmarkItemBase * parent () const
void removeChild (int index)
void setFlags (Qt::ItemFlags flags)
void setIcon (QIcon const &icon)
void setParent (BookmarkItemBase *parent)
void setText (QString const &text)
void setToolTip (QString const &tooltip)
const QString & text () const
virtual QString toolTip () const
virtual ~BookmarkItemBase ()
Private Attributes
QList< BookmarkItemBase * > m_children
Qt::ItemFlags m_flags
QIcon m_icon
BookmarkItemBase * m_parent
QString m_text
QString m_tooltip
Detailed Description
Definition at line 62 of file btbookmarksmodel.cpp.
Constructor & Destructor Documentation
BookmarkItemBase() [1/2]
BtBookmarksModelPrivate::BookmarkItemBase::BookmarkItemBase (BookmarkItemBase * parent = nullptr) inline
Definition at line 66 of file btbookmarksmodel.cpp.
References BT_ASSERT, m_children, and m_parent.
BookmarkItemBase() [2/2]
BtBookmarksModelPrivate::BookmarkItemBase::BookmarkItemBase (const BookmarkItemBase & other) inline
Definition at line 73 of file btbookmarksmodel.cpp.
~BookmarkItemBase()
virtual BtBookmarksModelPrivate::BookmarkItemBase::~BookmarkItemBase () inline virtual
Definition at line 81 of file btbookmarksmodel.cpp.
References m_children.
Member Function Documentation
addChild()
void BtBookmarksModelPrivate::BookmarkItemBase::addChild (BookmarkItemBase * child) inline
Children routines.
Definition at line 86 of file btbookmarksmodel.cpp.
References BT_ASSERT, child(), m_children, and setParent().
Referenced by BtBookmarksModelPrivate::BookmarkFolder::deepCopy().
child()
BookmarkItemBase* BtBookmarksModelPrivate::BookmarkItemBase::child (int index) const inline
Definition at line 94 of file btbookmarksmodel.cpp.
References index(), and m_children.
Referenced by addChild(), BtBookmarksModelPrivate::BookmarkFolder::getChildList(), BtBookmarksModel::index(), index(), insertChild(), BtBookmarksModelPrivate::saveItem(), and BtBookmarksModelPrivate::serializeTreeFromRootItem().
childCount()
int BtBookmarksModelPrivate::BookmarkItemBase::childCount () const inline
Definition at line 92 of file btbookmarksmodel.cpp.
References m_children.
Referenced by BtBookmarksModelPrivate::BookmarkFolder::getChildList(), BtBookmarksModel::index(), index(), BtBookmarksModel::load(), BtBookmarksModelPrivate::saveItem(), and BtBookmarksModelPrivate::serializeTreeFromRootItem().
children()
QList<BookmarkItemBase *>& BtBookmarksModelPrivate::BookmarkItemBase::children () inline
Definition at line 98 of file btbookmarksmodel.cpp.
References m_children.
Referenced by insertChildren(), and BtBookmarksModel::sortItems().
flags()
Qt::ItemFlags BtBookmarksModelPrivate::BookmarkItemBase::flags () const inline
Definition at line 129 of file btbookmarksmodel.cpp.
References m_flags.
Referenced by setFlags().
icon()
QIcon BtBookmarksModelPrivate::BookmarkItemBase::icon () const inline
Definition at line 133 of file btbookmarksmodel.cpp.
References m_icon.
Referenced by BtBookmarksModel::data(), and setIcon().
index()
int BtBookmarksModelPrivate::BookmarkItemBase::index () const inline
Returns
index of this item in parent's child array.
Definition at line 142 of file btbookmarksmodel.cpp.
References BT_ASSERT, child(), childCount(), and parent().
Referenced by BtBookmarksModel::addFolder(), child(), insertChild(), insertChildren(), BtBookmarksModel::parent(), and removeChild().
insertChild()
void BtBookmarksModelPrivate::BookmarkItemBase::insertChild (int index, BookmarkItemBase * child) inline
Definition at line 102 of file btbookmarksmodel.cpp.
References BT_ASSERT, child(), index(), m_children, and setParent().
Referenced by insertChildren().
insertChildren()
void BtBookmarksModelPrivate::BookmarkItemBase::insertChildren (int index, QList< BookmarkItemBase * > children) inline
Definition at line 108 of file btbookmarksmodel.cpp.
References children(), index(), and insertChild().
Referenced by BtBookmarksModel::load().
parent()
BookmarkItemBase* BtBookmarksModelPrivate::BookmarkItemBase::parent () const inline
Definition at line 137 of file btbookmarksmodel.cpp.
References m_parent.
Referenced by index(), BtBookmarksModel::parent(), and setParent().
removeChild()
void BtBookmarksModelPrivate::BookmarkItemBase::removeChild (int index) inline
Definition at line 113 of file btbookmarksmodel.cpp.
References index(), and m_children.
setFlags()
void BtBookmarksModelPrivate::BookmarkItemBase::setFlags (Qt::ItemFlags flags) inline
Definition at line 127 of file btbookmarksmodel.cpp.
References flags(), and m_flags.
Referenced by BtBookmarksModelPrivate::BookmarkItem::BookmarkItem().
setIcon()
void BtBookmarksModelPrivate::BookmarkItemBase::setIcon (QIcon const & icon) inline
Definition at line 131 of file btbookmarksmodel.cpp.
References icon(), and m_icon.
Referenced by BtBookmarksModelPrivate::BookmarkItem::BookmarkItem().
setParent()
void BtBookmarksModelPrivate::BookmarkItemBase::setParent (BookmarkItemBase * parent) inline
Definition at line 135 of file btbookmarksmodel.cpp.
References m_parent, and parent().
Referenced by addChild(), and insertChild().
setText()
void BtBookmarksModelPrivate::BookmarkItemBase::setText (QString const & text) inline
Definition at line 119 of file btbookmarksmodel.cpp.
References m_text, and text().
Referenced by BtBookmarksModelPrivate::BookmarkItem::BookmarkItem(), BtBookmarksModelPrivate::handleXmlElement(), and BtBookmarksModel::setData().
setToolTip()
void BtBookmarksModelPrivate::BookmarkItemBase::setToolTip (QString const & tooltip) inline
Definition at line 123 of file btbookmarksmodel.cpp.
References m_tooltip.
Referenced by BtBookmarksModel::setData().
text()
const QString& BtBookmarksModelPrivate::BookmarkItemBase::text () const inline
Definition at line 121 of file btbookmarksmodel.cpp.
References m_text.
Referenced by BtBookmarksModelSortAscending(), BtBookmarksModelSortDescending(), BtBookmarksModel::data(), BtBookmarksModelPrivate::BookmarkFolder::deepCopy(), BtBookmarksModelPrivate::saveItem(), setText(), and BtBookmarksModelPrivate::BookmarkItem::toolTip().
toolTip()
virtual QString BtBookmarksModelPrivate::BookmarkItemBase::toolTip () const inline virtual
Reimplemented in BtBookmarksModelPrivate::BookmarkItem.
Definition at line 125 of file btbookmarksmodel.cpp.
References m_tooltip.
Referenced by BtBookmarksModel::data().
Member Data Documentation
m_children
QList<BookmarkItemBase *> BtBookmarksModelPrivate::BookmarkItemBase::m_children private
Definition at line 152 of file btbookmarksmodel.cpp.
Referenced by addChild(), BookmarkItemBase(), child(), childCount(), children(), insertChild(), removeChild(), and ~BookmarkItemBase().
m_flags
Qt::ItemFlags BtBookmarksModelPrivate::BookmarkItemBase::m_flags private
Definition at line 153 of file btbookmarksmodel.cpp.
Referenced by flags(), and setFlags().
m_icon
QIcon BtBookmarksModelPrivate::BookmarkItemBase::m_icon private
Definition at line 154 of file btbookmarksmodel.cpp.
Referenced by icon(), and setIcon().
m_parent
BookmarkItemBase* BtBookmarksModelPrivate::BookmarkItemBase::m_parent private
Definition at line 155 of file btbookmarksmodel.cpp.
Referenced by BookmarkItemBase(), parent(), and setParent().
m_text
QString BtBookmarksModelPrivate::BookmarkItemBase::m_text private
Definition at line 156 of file btbookmarksmodel.cpp.
Referenced by setText(), and text().
m_tooltip
QString BtBookmarksModelPrivate::BookmarkItemBase::m_tooltip private
Definition at line 157 of file btbookmarksmodel.cpp.
Referenced by setToolTip(), and toolTip().
The documentation for this class was generated from the following file:
btbookmarksmodel.cpp