BibleTime: BibleTimeApp Class Reference
BibleTimeApp Class Reference
#include <bibletimeapp.h>
Public Member Functions
BibleTimeApp (int &argc, char **argv)
bool debugMode () const noexcept
void initBackends ()
bool initBtConfig ()
bool initDisplayTemplateManager ()
void initIcons ()
void initLightDarkPalette ()
void setDebugMode (bool const debugMode) noexcept
void startInit ()
~BibleTimeApp () override
Private Attributes
std::optional< CSwordBackend > m_backend
bool m_debugMode
BtIcons * m_icons
bool m_init
Detailed Description
The BibleTimeApp class is used to clean up all instances of the backend and to delete all created module objects.
Definition at line 29 of file bibletimeapp.h.
Constructor & Destructor Documentation
BibleTimeApp()
BibleTimeApp::BibleTimeApp (int & argc, char ** argv)
Definition at line 113 of file bibletimeapp.cpp.
References m_debugMode.
~BibleTimeApp()
BibleTimeApp::~BibleTimeApp () override
Definition at line 159 of file bibletimeapp.cpp.
References btConfig(), BtConfig::destroyInstance(), CDisplayTemplateMgr::instance(), m_backend, m_icons, m_init, BtConfig::m_instance, and BtConfigCore::setValue().
Member Function Documentation
debugMode()
bool BibleTimeApp::debugMode () const inline noexcept
Definition at line 46 of file bibletimeapp.h.
References m_debugMode.
Referenced by setDebugMode().
initBackends()
void BibleTimeApp::initBackends ()
Todo:
refactor this hack
Definition at line 279 of file bibletimeapp.cpp.
References btApp, util::directory::getUserHomeSwordDir(), m_backend, and CDisplaySettingsPage::resetLanguage().
Referenced by BibleTime::BibleTime().
initBtConfig()
bool BibleTimeApp::initBtConfig ()
Todo:
Migrate from btConfigOldApi to BTCONFIG_API_VERSION
Definition at line 175 of file bibletimeapp.cpp.
References BT_ASSERT, BtConfig::forceMigrate(), BtConfig::INIT_NEED_UNIMPLEMENTED_BACKWARD_MIGRATE, BtConfig::INIT_NEED_UNIMPLEMENTED_FORWARD_MIGRATE, BtConfig::INIT_OK, BtConfig::initBtConfig(), m_init, r(), and message::showWarning().
Referenced by main().
initDisplayTemplateManager()
bool BibleTimeApp::initDisplayTemplateManager ()
Definition at line 266 of file bibletimeapp.cpp.
References BT_ASSERT, m_init, and message::showCritical().
Referenced by main().
initIcons()
void BibleTimeApp::initIcons ()
Definition at line 277 of file bibletimeapp.cpp.
References m_icons.
Referenced by main().
initLightDarkPalette()
void BibleTimeApp::initLightDarkPalette ()
Definition at line 216 of file bibletimeapp.cpp.
References btConfig(), and BtConfigCore::value().
Referenced by main().
setDebugMode()
void BibleTimeApp::setDebugMode (bool const debugMode) inline noexcept
Definition at line 47 of file bibletimeapp.h.
References debugMode(), and m_debugMode.
Referenced by main().
startInit()
void BibleTimeApp::startInit () inline
Definition at line 38 of file bibletimeapp.h.
References m_init.
Referenced by main().
Member Data Documentation
m_backend
std::optional<CSwordBackend> BibleTimeApp::m_backend private
Definition at line 55 of file bibletimeapp.h.
Referenced by initBackends(), and ~BibleTimeApp().
m_debugMode
bool BibleTimeApp::m_debugMode private
Definition at line 53 of file bibletimeapp.h.
Referenced by BibleTimeApp(), debugMode(), and setDebugMode().
m_icons
BtIcons* BibleTimeApp::m_icons private
Definition at line 54 of file bibletimeapp.h.
Referenced by initIcons(), and ~BibleTimeApp().
m_init
bool BibleTimeApp::m_init private
Definition at line 52 of file bibletimeapp.h.
Referenced by initBtConfig(), initDisplayTemplateManager(), startInit(), and ~BibleTimeApp().
The documentation for this class was generated from the following files:
bibletimeapp.h
bibletimeapp.cpp