BibleTime: Search::CModuleResultView Class Reference
Search::CModuleResultView Class Reference
#include <cmoduleresultview.h>
Signals
void moduleChanged ()
void moduleSelected (CSwordModuleInfo const *, CSwordModuleSearch::ModuleResultList const &)
void strongsSelected (CSwordModuleInfo *, const QStringList &)
Public Member Functions
CSwordModuleInfo * activeModule ()
CModuleResultView (QWidget *parent)
void setupTree (const CSwordModuleSearch::Results &results, const QString &searchedText)
QSize sizeHint () const override
~CModuleResultView () override
Protected Slots
void contextMenuEvent (QContextMenuEvent *event) override
void executed (QTreeWidgetItem *, QTreeWidgetItem *)
Protected Member Functions
void initConnections ()
void initView ()
Private Attributes
struct {
struct {
QAction * result
QAction * resultWithText
} copy
QMenu * copyMenu
struct {
QAction * result
} print
QMenu * printMenu
struct {
QAction * result
QAction * resultWithText
} save
QMenu * saveMenu
} m_actions
QMenu * m_popup
QHash< CSwordModuleInfo const *, CSwordModuleSearch::ModuleResultList > m_results
QSize m_size
QHash< CSwordModuleInfo const *, QList< StrongsResult > > m_strongsResults
Detailed Description
Definition at line 36 of file cmoduleresultview.h.
Constructor & Destructor Documentation
CModuleResultView()
Search::CModuleResultView::CModuleResultView (QWidget * parent)
Definition at line 134 of file cmoduleresultview.cpp.
References initConnections(), and initView().
~CModuleResultView()
Search::CModuleResultView::~CModuleResultView () override default
Member Function Documentation
activeModule()
CSwordModuleInfo * Search::CModuleResultView::activeModule ()
Returns the currently active module.
Definition at line 323 of file cmoduleresultview.cpp.
References BT_ASSERT, CSwordBackend::findModuleByName(), and CSwordBackend::instance().
Referenced by executed().
contextMenuEvent
void Search::CModuleResultView::contextMenuEvent (QContextMenuEvent * event) override protected slot
This event handler (reimplemented from QWidget) opens the popup menu at the given position.
Reimplementation from QWidget.
Definition at line 336 of file cmoduleresultview.cpp.
References m_popup.
executed
void Search::CModuleResultView::executed (QTreeWidgetItem * i, QTreeWidgetItem *) protected slot
Is executed when an item was selected in the list.
Todo:
Is executed when an item was selected in the list.
Definition at line 297 of file cmoduleresultview.cpp.
References activeModule(), CSwordBackend::instance(), m_results, m_strongsResults, moduleChanged(), moduleSelected(), and strongsSelected().
Referenced by initConnections().
initConnections()
void Search::CModuleResultView::initConnections () protected
Initializes the connections of this widget
Initializes the connections of this widget,
Todo:
Definition at line 229 of file cmoduleresultview.cpp.
References BT_CONNECT, and executed().
Referenced by CModuleResultView().
initView()
void Search::CModuleResultView::initView () protected
Initializes this widget.
Todo:
sorting
Definition at line 143 of file cmoduleresultview.cpp.
References BT_CONNECT, m_actions, m_popup, m_size, and util::tool::mWidth().
Referenced by CModuleResultView().
moduleChanged
void Search::CModuleResultView::moduleChanged () signal
Referenced by Search::BtSearchResultArea::BtSearchResultArea(), and executed().
moduleSelected
void Search::CModuleResultView::moduleSelected (CSwordModuleInfo const * , CSwordModuleSearch::ModuleResultList const &) signal
Referenced by Search::BtSearchResultArea::BtSearchResultArea(), and executed().
setupTree()
void Search::CModuleResultView::setupTree (const CSwordModuleSearch::Results & results, const QString & searchedText)
Setups the tree using the given list of modules.
Todo:
implement sorting in this method.
Todo:
item->setOpen(true);
Definition at line 235 of file cmoduleresultview.cpp.
References BT_ASSERT, m_results, m_strongsResults, and result.
Referenced by Search::BtSearchResultArea::setSearchResult().
sizeHint()
QSize Search::CModuleResultView::sizeHint () const inline override
Definition at line 53 of file cmoduleresultview.h.
References m_size.
Referenced by Search::BtSearchResultArea::loadDialogSettings().
strongsSelected
void Search::CModuleResultView::strongsSelected (CSwordModuleInfo * , const QStringList &) signal
Referenced by Search::BtSearchResultArea::BtSearchResultArea(), and executed().
Member Data Documentation
[struct]
struct { ... } Search::CModuleResultView::copy
copyMenu
QMenu* Search::CModuleResultView::copyMenu
Definition at line 98 of file cmoduleresultview.h.
[struct]
struct { ... } Search::CModuleResultView::m_actions
Referenced by initView().
m_popup
QMenu* Search::CModuleResultView::m_popup private
Definition at line 107 of file cmoduleresultview.h.
Referenced by contextMenuEvent(), and initView().
m_results
QHash<CSwordModuleInfo const *, CSwordModuleSearch::ModuleResultList> Search::CModuleResultView::m_results private
Definition at line 110 of file cmoduleresultview.h.
Referenced by executed(), and setupTree().
m_size
QSize Search::CModuleResultView::m_size private
Definition at line 112 of file cmoduleresultview.h.
Referenced by initView(), and sizeHint().
m_strongsResults
QHash<CSwordModuleInfo const *, QList<StrongsResult> > Search::CModuleResultView::m_strongsResults private
Definition at line 111 of file cmoduleresultview.h.
Referenced by executed(), and setupTree().
[struct]
struct { ... } Search::CModuleResultView::print
printMenu
QMenu* Search::CModuleResultView::printMenu
Definition at line 92 of file cmoduleresultview.h.
result
QAction* Search::CModuleResultView::result
Definition at line 87 of file cmoduleresultview.h.
Referenced by setupTree().
resultWithText
QAction* Search::CModuleResultView::resultWithText
Definition at line 88 of file cmoduleresultview.h.
[struct]
struct { ... } Search::CModuleResultView::save
saveMenu
QMenu* Search::CModuleResultView::saveMenu
Definition at line 85 of file cmoduleresultview.h.
The documentation for this class was generated from the following files:
cmoduleresultview.h
cmoduleresultview.cpp