BibleTime: anonymous_namespace{main.cpp} Namespace Reference
anonymous_namespace{main.cpp} Namespace Reference
Functions
int parseCommandLine (bool &showDebugMessages, bool &ignoreSession, QString &openBibleKey)
void printHelp (const QString &executable)
void registerMetaTypes ()
Detailed Description
Todo:
Reimplement signal handler which handles consecutive crashes.
Function Documentation
parseCommandLine()
int anonymous_namespace{main.cpp}::parseCommandLine (bool & showDebugMessages, bool & ignoreSession, QString & openBibleKey)
Parses all command-line arguments.
Parameters
[out] ignoreSession Whether –ignore-session was specified.
[out] openBibleKey Will be set to –open-default-bible if specified.
Return values
-1 Parsing was successful, the application should exit with EXIT_SUCCESS.
0 Parsing was successful.
1 Parsing failed, the application should exit with EXIT_FAILURE.
Definition at line 77 of file main.cpp.
References printHelp().
Referenced by main().
printHelp()
void anonymous_namespace{main.cpp}::printHelp (const QString & executable)
Prints command-line help text for BibleTime when –help is used.
Parameters
[in] executable The executed file name (argv[0]).
Definition at line 43 of file main.cpp.
Referenced by parseCommandLine().
registerMetaTypes()
void anonymous_namespace{main.cpp}::registerMetaTypes ()
Definition at line 128 of file main.cpp.
References BtQmlInterface::typeId.
Referenced by main().