BibleTime: BtShortcutsDialog Class Reference
BtShortcutsDialog Class Reference
#include <btshortcutsdialog.h>
Signals
void keyChangeRequest (QKeySequence const &keys)
Public Member Functions
BtShortcutsDialog (QWidget *parent=nullptr, Qt::WindowFlags f=Qt::WindowFlags())
void changeSelectedShortcut (QKeySequence const &keys)
QString getFirstKeys ()
QString getSecondKeys ()
void setFirstKeys (const QString &keys)
void setSecondKeys (const QString &keys)
Protected Member Functions
void keyReleaseEvent (QKeyEvent *event) override
Private Member Functions
void retranslateUi ()
Private Attributes
QRadioButton * m_alternateButton
QLabel * m_alternateLabel
QRadioButton * m_primaryButton
QLabel * m_primaryLabel
Detailed Description
Definition at line 31 of file btshortcutsdialog.h.
Constructor & Destructor Documentation
BtShortcutsDialog()
BtShortcutsDialog::BtShortcutsDialog (QWidget * parent = nullptr, Qt::WindowFlags f = Qt::WindowFlags()) explicit
Definition at line 31 of file btshortcutsdialog.cpp.
References BT_CONNECT, m_alternateButton, m_alternateLabel, m_primaryButton, m_primaryLabel, message::prepareDialogBox(), and retranslateUi().
Member Function Documentation
changeSelectedShortcut()
void BtShortcutsDialog::changeSelectedShortcut (QKeySequence const & keys)
Definition at line 114 of file btshortcutsdialog.cpp.
References m_alternateButton, m_alternateLabel, m_primaryButton, and m_primaryLabel.
Referenced by BtShortcutsEditor::changeShortcutInDialog().
getFirstKeys()
QString BtShortcutsDialog::getFirstKeys ()
Definition at line 76 of file btshortcutsdialog.cpp.
References m_primaryLabel.
Referenced by BtShortcutsEditor::customButtonClicked().
getSecondKeys()
QString BtShortcutsDialog::getSecondKeys ()
Definition at line 86 of file btshortcutsdialog.cpp.
References m_alternateLabel.
Referenced by BtShortcutsEditor::customButtonClicked().
keyChangeRequest
void BtShortcutsDialog::keyChangeRequest (QKeySequence const & keys) signal
Referenced by BtShortcutsEditor::BtShortcutsEditor(), and keyReleaseEvent().
keyReleaseEvent()
void BtShortcutsDialog::keyReleaseEvent (QKeyEvent * event) override protected
Definition at line 96 of file btshortcutsdialog.cpp.
References keyChangeRequest().
retranslateUi()
void BtShortcutsDialog::retranslateUi () private
Definition at line 126 of file btshortcutsdialog.cpp.
References m_alternateButton, m_alternateLabel, m_primaryButton, and m_primaryLabel.
Referenced by BtShortcutsDialog().
setFirstKeys()
void BtShortcutsDialog::setFirstKeys (const QString & keys)
Definition at line 81 of file btshortcutsdialog.cpp.
References m_primaryLabel.
Referenced by BtShortcutsEditor::customButtonClicked().
setSecondKeys()
void BtShortcutsDialog::setSecondKeys (const QString & keys)
Definition at line 91 of file btshortcutsdialog.cpp.
References m_alternateLabel.
Referenced by BtShortcutsEditor::customButtonClicked().
Member Data Documentation
m_alternateButton
QRadioButton* BtShortcutsDialog::m_alternateButton private
Definition at line 69 of file btshortcutsdialog.h.
Referenced by BtShortcutsDialog(), changeSelectedShortcut(), and retranslateUi().
m_alternateLabel
QLabel* BtShortcutsDialog::m_alternateLabel private
Definition at line 67 of file btshortcutsdialog.h.
Referenced by BtShortcutsDialog(), changeSelectedShortcut(), getSecondKeys(), retranslateUi(), and setSecondKeys().
m_primaryButton
QRadioButton* BtShortcutsDialog::m_primaryButton private
Definition at line 68 of file btshortcutsdialog.h.
Referenced by BtShortcutsDialog(), changeSelectedShortcut(), and retranslateUi().
m_primaryLabel
QLabel* BtShortcutsDialog::m_primaryLabel private
Definition at line 66 of file btshortcutsdialog.h.
Referenced by BtShortcutsDialog(), changeSelectedShortcut(), getFirstKeys(), retranslateUi(), and setFirstKeys().
The documentation for this class was generated from the following files:
btshortcutsdialog.h
btshortcutsdialog.cpp