BibleTime: anonymous_namespace{bttextfilter.cpp} Namespace Reference
anonymous_namespace{bttextfilter.cpp} Namespace Reference
Functions
void fixDoubleBR (QStringList &parts)
int rewriteClass (QStringList &parts, int i, QString const &part)
int rewriteFootnoteAsLink (QStringList &parts, int i, QString const &part)
void rewriteHref (QStringList &parts, int i, QString const &part)
int rewriteLemmaOrMorphAsLink (QStringList &parts, int i, QString const &part)
int rewriteTag (QStringList &parts, int i, QString const &tag)
int rewriteTitle (QStringList &parts, int i, QString const &tag)
QStringList splitText (QString const &text)
Function Documentation
fixDoubleBR()
void anonymous_namespace{bttextfilter.cpp}::fixDoubleBR (QStringList & parts)
Definition at line 44 of file bttextfilter.cpp.
Referenced by BtTextFilter::processText().
rewriteClass()
int anonymous_namespace{bttextfilter.cpp}::rewriteClass (QStringList & parts, int i, QString const & part)
Definition at line 140 of file bttextfilter.cpp.
References rewriteFootnoteAsLink(), rewriteTag(), and rewriteTitle().
Referenced by BtTextFilter::processText().
rewriteFootnoteAsLink()
int anonymous_namespace{bttextfilter.cpp}::rewriteFootnoteAsLink (QStringList & parts, int i, QString const & part)
Definition at line 55 of file bttextfilter.cpp.
Referenced by BtTextFilter::processText(), and rewriteClass().
rewriteHref()
void anonymous_namespace{bttextfilter.cpp}::rewriteHref (QStringList & parts, int i, QString const & part)
Definition at line 77 of file bttextfilter.cpp.
Referenced by BtTextFilter::processText().
rewriteLemmaOrMorphAsLink()
int anonymous_namespace{bttextfilter.cpp}::rewriteLemmaOrMorphAsLink (QStringList & parts, int i, QString const & part)
Definition at line 93 of file bttextfilter.cpp.
Referenced by BtTextFilter::processText().
rewriteTag()
int anonymous_namespace{bttextfilter.cpp}::rewriteTag (QStringList & parts, int i, QString const & tag)
Definition at line 124 of file bttextfilter.cpp.
Referenced by rewriteClass().
rewriteTitle()
int anonymous_namespace{bttextfilter.cpp}::rewriteTitle (QStringList & parts, int i, QString const & tag)
Definition at line 132 of file bttextfilter.cpp.
Referenced by rewriteClass().
splitText()
QStringList anonymous_namespace{bttextfilter.cpp}::splitText (QString const & text)
Definition at line 22 of file bttextfilter.cpp.
Referenced by BtTextFilter::processText().