BibleTime: CSwordSettingsPage Class Reference
CSwordSettingsPage Class Reference
#include <cswordsettings.h>
Public Member Functions
CSwordSettingsPage (CConfigurationDialog *parent=nullptr)
void save () const final override
Public Member Functions inherited from BtConfigDialog::Page
Page (QIcon const &icon, QWidget *const parent=nullptr)
void setHeaderText (QString const &headerText)
~Page () noexcept override
Protected Member Functions
void retranslateUi ()
Private Attributes
BtTextFiltersTab * m_filtersTab
QTabWidget * m_tabWidget
BtStandardWorksTab * m_worksTab
Detailed Description
Definition at line 26 of file cswordsettings.h.
Constructor & Destructor Documentation
CSwordSettingsPage()
CSwordSettingsPage::CSwordSettingsPage (CConfigurationDialog * parent = nullptr)
Definition at line 23 of file cswordsettings.cpp.
References m_filtersTab, m_tabWidget, m_worksTab, and retranslateUi().
Member Function Documentation
retranslateUi()
void CSwordSettingsPage::retranslateUi () protected
Definition at line 42 of file cswordsettings.cpp.
References m_filtersTab, m_tabWidget, m_worksTab, and BtConfigDialog::Page::setHeaderText().
Referenced by CSwordSettingsPage().
save()
void CSwordSettingsPage::save () const final override virtual
Implements BtConfigDialog::Page.
Definition at line 49 of file cswordsettings.cpp.
References m_filtersTab, m_worksTab, BtStandardWorksTab::save(), and BtTextFiltersTab::save().
Member Data Documentation
m_filtersTab
BtTextFiltersTab* CSwordSettingsPage::m_filtersTab private
Definition at line 44 of file cswordsettings.h.
Referenced by CSwordSettingsPage(), retranslateUi(), and save().
m_tabWidget
QTabWidget* CSwordSettingsPage::m_tabWidget private
Definition at line 42 of file cswordsettings.h.
Referenced by CSwordSettingsPage(), and retranslateUi().
m_worksTab
BtStandardWorksTab* CSwordSettingsPage::m_worksTab private
Definition at line 43 of file cswordsettings.h.
Referenced by CSwordSettingsPage(), retranslateUi(), and save().
The documentation for this class was generated from the following files:
cswordsettings.h
cswordsettings.cpp