BibleTime: CBibleKeyChooser Class Reference
CBibleKeyChooser Class Reference final
A key chooser for bibles and commentaries.
#include <cbiblekeychooser.h>
Public Slots
void updateKey (CSwordKey *key) final override
Public Slots inherited from CKeyChooser
virtual void updateKey (CSwordKey *key)=0
Public Member Functions
CBibleKeyChooser (BtConstModuleList const &modules, BTHistory *history, CSwordKey *key=nullptr, QWidget *parent=nullptr)
CSwordKey * key () final override
void refreshContent () final override
void setKey (CSwordKey *key) final override
void setModules (BtConstModuleList const &modules, bool refresh=true) final override
Public Member Functions inherited from CKeyChooser
BTHistory * history () const
Private Member Functions
void handleHistoryMoved (QString const &newKey) final override
Private Attributes
CSwordVerseKey * m_key
QList< CSwordBibleModuleInfo const * > m_modules
BtBibleKeyWidget * w_ref
Additional Inherited Members
Signals inherited from CKeyChooser
void keyChanged (CSwordKey *newKey)
Static Public Member Functions inherited from CKeyChooser
static CKeyChooser * createInstance (const BtConstModuleList &modules, BTHistory *history, CSwordKey *key, QWidget *parent)
Protected Member Functions inherited from CKeyChooser
CKeyChooser (const BtConstModuleList &info, BTHistory *history, QWidget *parent=nullptr)
Detailed Description
A key chooser for bibles and commentaries.
Definition at line 27 of file cbiblekeychooser.h.
Constructor & Destructor Documentation
CBibleKeyChooser()
CBibleKeyChooser::CBibleKeyChooser (BtConstModuleList const & modules, BTHistory * history, CSwordKey * key = nullptr, QWidget * parent = nullptr)
Definition at line 28 of file cbiblekeychooser.cpp.
References BTHistory::add(), BT_ASSERT, BT_CONNECT, BtBibleKeyWidget::changed(), CKeyChooser::history(), key(), CKeyChooser::keyChanged(), m_key, m_modules, setKey(), setModules(), and w_ref.
Member Function Documentation
handleHistoryMoved()
void CBibleKeyChooser::handleHistoryMoved (QString const & newKey) final override private virtual
Implements CKeyChooser.
Definition at line 113 of file cbiblekeychooser.cpp.
References m_key, setKey(), and CSwordVerseKey::setKey().
key()
CSwordKey * CBibleKeyChooser::key () final override virtual
Returns
the current CKey.
Implements CKeyChooser.
Definition at line 74 of file cbiblekeychooser.cpp.
References m_key.
Referenced by CBibleKeyChooser(), and setKey().
refreshContent()
void CBibleKeyChooser::refreshContent () final override virtual
Refreshes the content of the different key chooser parts.
Implements CKeyChooser.
Definition at line 105 of file cbiblekeychooser.cpp.
References m_key, and setKey().
Referenced by setModules().
setKey()
void CBibleKeyChooser::setKey (CSwordKey * key) final override virtual
Sets the CKey
Parameters
key the key which the widget should be set to.
Implements CKeyChooser.
Definition at line 78 of file cbiblekeychooser.cpp.
References BT_ASSERT, key(), CKeyChooser::keyChanged(), m_key, BtBibleKeyWidget::setKey(), and w_ref.
Referenced by CBibleKeyChooser(), handleHistoryMoved(), and refreshContent().
setModules()
void CBibleKeyChooser::setModules (BtConstModuleList const & modules, bool refresh = true) final override virtual
Sets the module of this keychooser and refreshes the comboboxes
Implements CKeyChooser.
Definition at line 87 of file cbiblekeychooser.cpp.
References CSwordModuleInfo::Bible, CSwordModuleInfo::Commentary, m_modules, refreshContent(), BtBibleKeyWidget::setModule(), and w_ref.
Referenced by CBibleKeyChooser().
updateKey
void CBibleKeyChooser::updateKey (CSwordKey * key) final override slot
Definition at line 109 of file cbiblekeychooser.cpp.
References BtBibleKeyWidget::updateText(), and w_ref.
Member Data Documentation
m_key
CSwordVerseKey* CBibleKeyChooser::m_key private
Definition at line 59 of file cbiblekeychooser.h.
Referenced by CBibleKeyChooser(), handleHistoryMoved(), key(), refreshContent(), and setKey().
m_modules
QList<CSwordBibleModuleInfo const *> CBibleKeyChooser::m_modules private
Definition at line 58 of file cbiblekeychooser.h.
Referenced by CBibleKeyChooser(), and setModules().
w_ref
BtBibleKeyWidget* CBibleKeyChooser::w_ref private
Definition at line 57 of file cbiblekeychooser.h.
Referenced by CBibleKeyChooser(), setKey(), setModules(), and updateKey().
The documentation for this class was generated from the following files:
cbiblekeychooser.h
cbiblekeychooser.cpp