BibleTime: Rendering::CTextRendering Class Reference
Rendering::CTextRendering Class Reference
Text rendering based on trees.
#include <ctextrendering.h>
Classes
class KeyTreeItem
Public Types
using KeyTree = std::list< KeyTreeItem >
Public Member Functions
CTextRendering (bool addText)
CTextRendering (bool addText, DisplayOptions const &displayOptions, FilterOptions const &filterOptions)
DisplayOptions const & displayOptions () const noexcept
FilterOptions const & filterOptions () const noexcept
QString renderKeyRange (CSwordVerseKey const &lowerBound, CSwordVerseKey const &upperBound, const BtConstModuleList &modules, const QString &hightlightKey=QString(), const KeyTreeItem::Settings &settings=KeyTreeItem::Settings())
QString renderKeyTree (KeyTree const &tree) const
QString renderSingleKey (const QString &key, const BtConstModuleList &modules, const KeyTreeItem::Settings &settings=KeyTreeItem::Settings())
void setDisplayOptions (DisplayOptions const &displayOptions) noexcept
void setFilterOptions (FilterOptions const &filterOptions) noexcept
virtual ~CTextRendering ()
Protected Member Functions
virtual QString entryLink (KeyTreeItem const &item, CSwordModuleInfo const &module) const
virtual QString finishText (QString const &text, KeyTree const &tree) const
virtual QString renderEntry (KeyTreeItem const &item, CSwordKey *key=nullptr) const
Static Protected Member Functions
static BtConstModuleList collectModules (KeyTree const &tree)
Protected Attributes
bool const m_addText
DisplayOptions m_displayOptions
FilterOptions m_filterOptions
Detailed Description
Text rendering based on trees.
CTextRendering is BibleTime's place where the actual rendering takes place. It provides several methods to convert an abstract tree of items into a string of html.
Author
The BibleTime team
Definition at line 34 of file ctextrendering.h.
Member Typedef Documentation
KeyTree
using Rendering::CTextRendering::KeyTree = std::list<KeyTreeItem>
Definition at line 40 of file ctextrendering.h.
Constructor & Destructor Documentation
CTextRendering() [1/2]
CTextRendering::CTextRendering (bool addText)
Definition at line 135 of file ctextrendering.cpp.
CTextRendering() [2/2]
CTextRendering::CTextRendering (bool addText, DisplayOptions const & displayOptions, FilterOptions const & filterOptions)
Definition at line 141 of file ctextrendering.cpp.
~CTextRendering()
CTextRendering::~CTextRendering () virtual default
Member Function Documentation
collectModules()
BtConstModuleList CTextRendering::collectModules (KeyTree const & tree) static protected
Definition at line 152 of file ctextrendering.cpp.
Referenced by finishText(), Rendering::CDisplayRendering::finishText(), BtPrinter::finishText(), renderEntry(), and renderKeyTree().
displayOptions()
DisplayOptions const & Rendering::CTextRendering::displayOptions () const inline noexcept
Definition at line 134 of file ctextrendering.h.
References m_displayOptions.
Referenced by setDisplayOptions().
entryLink()
QString CTextRendering::entryLink (KeyTreeItem const & item, CSwordModuleInfo const & module) const protected virtual
Reimplemented in Rendering::CDisplayRendering, Rendering::CrossRefRendering, and BtPrinter.
Definition at line 477 of file ctextrendering.cpp.
References Rendering::CTextRendering::KeyTreeItem::key().
Referenced by renderEntry().
filterOptions()
FilterOptions const & Rendering::CTextRendering::filterOptions () const inline noexcept
Definition at line 126 of file ctextrendering.h.
References m_filterOptions.
Referenced by setFilterOptions().
finishText()
QString CTextRendering::finishText (QString const & text, KeyTree const & tree) const protected virtual
Reimplemented in Rendering::CDisplayRendering, Rendering::CPlainTextExportRendering, Rendering::CrossRefRendering, and BtPrinter.
Definition at line 455 of file ctextrendering.cpp.
References CDisplayTemplateMgr::activeTemplateName(), collectModules(), CDisplayTemplateMgr::fillTemplate(), CDisplayTemplateMgr::instance(), CDisplayTemplateMgr::Settings::langAbbrev, CSwordModuleInfo::language(), CDisplayTemplateMgr::Settings::modules, CSwordModuleInfo::textDirection(), and CDisplayTemplateMgr::Settings::textDirection.
Referenced by renderKeyTree().
renderEntry()
QString CTextRendering::renderEntry (KeyTreeItem const & item, CSwordKey * key = nullptr) const protected virtual
Todo:
Take care of the heading type!
Reimplemented in BtPrinter, and Rendering::CPlainTextExportRendering.
Definition at line 239 of file ctextrendering.cpp.
References BT_ASSERT, Rendering::CTextRendering::KeyTreeItem::childList(), collectModules(), entryLink(), Rendering::CTextRendering::KeyTreeItem::getAlternativeContent(), Rendering::CTextRendering::KeyTreeItem::hasAlternativeContent(), FilterOptions::headings, Rendering::CTextRendering::KeyTreeItem::Settings::highlight, Rendering::CTextRendering::KeyTreeItem::key(), DisplayOptions::lineBreaks, m_addText, m_displayOptions, m_filterOptions, Rendering::CTextRendering::KeyTreeItem::modules(), CSwordKey::renderedText(), renderEntry(), CSwordVerseKey::setIndex(), CSwordVerseKey::setIntros(), Rendering::CTextRendering::KeyTreeItem::setMappedKey(), and Rendering::CTextRendering::KeyTreeItem::settings().
Referenced by renderEntry(), and renderKeyTree().
renderKeyRange()
QString CTextRendering::renderKeyRange (CSwordVerseKey const & lowerBound, CSwordVerseKey const & upperBound, const BtConstModuleList & modules, const QString & hightlightKey = QString(), const KeyTreeItem::Settings & settings = KeyTreeItem::Settings())
Todo:
We need to take care of linked verses if we render one or (esp) more modules. If the verses 2,3,4,5 are linked to 1, it should be displayed as one entry with the caption 1-5.
Todo:
Notify the user about this failure.
Definition at line 187 of file ctextrendering.cpp.
References BT_ASSERT, Rendering::CTextRendering::KeyTreeItem::Settings::highlight, CSwordVerseKey::key(), renderKeyTree(), and renderSingleKey().
Referenced by BtQmlInterface::copyVerseRange(), and Search::BtSearchResultArea::updatePreview().
renderKeyTree()
QString CTextRendering::renderKeyTree (KeyTree const & tree) const
Definition at line 163 of file ctextrendering.cpp.
References collectModules(), finishText(), CSwordBackend::instance(), m_filterOptions, renderEntry(), and CSwordBackend::setFilterOptions().
Referenced by BtPrinter::printKeyTree(), Rendering::CDisplayRendering::renderDisplayEntry(), renderKeyRange(), renderSingleKey(), and CDisplaySettingsPage::updateStylePreview().
renderSingleKey()
QString CTextRendering::renderSingleKey (const QString & key, const BtConstModuleList & modules, const KeyTreeItem::Settings & settings = KeyTreeItem::Settings())
Definition at line 229 of file ctextrendering.cpp.
References renderKeyTree().
Referenced by Search::anonymous_namespace{cmoduleresultview.cpp}::populateStrongsResultList(), renderKeyRange(), and Search::BtSearchResultArea::updatePreview().
setDisplayOptions()
void Rendering::CTextRendering::setDisplayOptions (DisplayOptions const & displayOptions) inline noexcept
Definition at line 137 of file ctextrendering.h.
References displayOptions(), and m_displayOptions.
Referenced by BtQmlInterface::copyVerseRange().
setFilterOptions()
void Rendering::CTextRendering::setFilterOptions (FilterOptions const & filterOptions) inline noexcept
Definition at line 129 of file ctextrendering.h.
References filterOptions(), and m_filterOptions.
Referenced by BtQmlInterface::copyVerseRange().
Member Data Documentation
m_addText
bool const Rendering::CTextRendering::m_addText protected
Definition at line 170 of file ctextrendering.h.
Referenced by renderEntry(), and Rendering::CPlainTextExportRendering::renderEntry().
m_displayOptions
DisplayOptions Rendering::CTextRendering::m_displayOptions protected
Definition at line 168 of file ctextrendering.h.
Referenced by displayOptions(), renderEntry(), and setDisplayOptions().
m_filterOptions
FilterOptions Rendering::CTextRendering::m_filterOptions protected
Definition at line 169 of file ctextrendering.h.
Referenced by filterOptions(), renderEntry(), renderKeyTree(), and setFilterOptions().
The documentation for this class was generated from the following files:
ctextrendering.h
ctextrendering.cpp