BibleTime: CBookTreeChooser Class Reference
CBookTreeChooser Class Reference final
#include <cbooktreechooser.h>
Public Slots
void updateKey (CSwordKey *) final override
Public Slots inherited from CKeyChooser
void handleHistoryMoved (QString const &newKey)
virtual void updateKey (CSwordKey *key)=0
Public Member Functions
CBookTreeChooser (BtConstModuleList const &modules, CSwordKey *key=nullptr, QWidget *parent=nullptr)
CSwordKey * key () final override
void refreshContent () final override
void setKey (CSwordKey *key) final override
void setModules (BtConstModuleList const &modules, bool refresh=true) final override
Protected Member Functions
void showEvent (QShowEvent *const showEvent) override
Protected Member Functions inherited from CKeyChooser
CKeyChooser (QWidget *parent=nullptr)
Private Slots
void itemActivated (QTreeWidgetItem *item)
Private Member Functions
void addKeyChildren (CSwordTreeKey *key, QTreeWidgetItem *item)
void adjustFont ()
void setupTree ()
Creates the first level of the tree structure.
Private Attributes
CSwordTreeKey * m_key
QList< CSwordBookModuleInfo const * > m_modules
QTreeWidget * m_treeView
Additional Inherited Members
Signals inherited from CKeyChooser
void keyChanged (CSwordKey *newKey)
Static Public Member Functions inherited from CKeyChooser
static CKeyChooser * createInstance (const BtConstModuleList &modules, CSwordKey *key, QWidget *parent)
Detailed Description
Definition at line 30 of file cbooktreechooser.h.
Constructor & Destructor Documentation
CBookTreeChooser()
CBookTreeChooser::CBookTreeChooser (BtConstModuleList const & modules, CSwordKey * key = nullptr, QWidget * parent = nullptr)
Definition at line 32 of file cbooktreechooser.cpp.
References adjustFont(), BT_CONNECT, itemActivated(), key(), m_key, m_modules, m_treeView, setKey(), and setModules().
Member Function Documentation
addKeyChildren()
void CBookTreeChooser::addKeyChildren (CSwordTreeKey * key, QTreeWidgetItem * item) private
Populates tree widget with items.
Definition at line 170 of file cbooktreechooser.cpp.
References addKeyChildren(), CSwordKey::key(), and key().
Referenced by addKeyChildren(), and setupTree().
adjustFont()
void CBookTreeChooser::adjustFont () private
From ckeychooser.
Definition at line 112 of file cbooktreechooser.cpp.
References btConfig(), m_modules, and m_treeView.
Referenced by CBookTreeChooser(), and setModules().
itemActivated
void CBookTreeChooser::itemActivated (QTreeWidgetItem * item) private slot
Todo:
itemActivated is called too many times. As tested in GDB, the function
Slot for signal when item is selected by user.
Definition at line 131 of file cbooktreechooser.cpp.
References CKeyChooser::keyChanged(), m_key, and CSwordTreeKey::setKey().
Referenced by CBookTreeChooser().
key()
CSwordKey * CBookTreeChooser::key () inline final override virtual
Returns
the current CKey.
Implements CKeyChooser.
Definition at line 44 of file cbooktreechooser.h.
References m_key.
Referenced by addKeyChildren(), CBookTreeChooser(), setKey(), and updateKey().
refreshContent()
void CBookTreeChooser::refreshContent () final override virtual
Refreshes the content. Inherited from ckeychooser.
Implements CKeyChooser.
Definition at line 119 of file cbooktreechooser.cpp.
References m_key, and updateKey().
setKey()
void CBookTreeChooser::setKey (CSwordKey * newKey) final override virtual
Sets a new key to this keychooser. Inherited from ckeychooser.
Implements CKeyChooser.
Definition at line 65 of file cbooktreechooser.cpp.
References CSwordTreeKey::key(), key(), m_key, and m_treeView.
Referenced by CBookTreeChooser(), setupTree(), and updateKey().
setModules()
void CBookTreeChooser::setModules (BtConstModuleList const & modules, bool refresh = true) final override virtual
Sets the module of this keychooser and refreshes the comboboxes
Implements CKeyChooser.
Definition at line 87 of file cbooktreechooser.cpp.
References adjustFont(), m_key, m_modules, CSwordTreeKey::offset(), CSwordTreeKey::setOffset(), and setupTree().
Referenced by CBookTreeChooser(), and CBookReadWindow::modulesChanged().
setupTree()
void CBookTreeChooser::setupTree () private
Creates the first level of the tree structure.
Creates the tree structure in the view.
Definition at line 157 of file cbooktreechooser.cpp.
References addKeyChildren(), m_key, m_treeView, CSwordTreeKey::offset(), CSwordTreeKey::positionToRoot(), setKey(), and CSwordTreeKey::setOffset().
Referenced by setModules(), and showEvent().
showEvent()
void CBookTreeChooser::showEvent (QShowEvent *const showEvent) override protected
Reimplementation to handle tree creation on show.
Definition at line 146 of file cbooktreechooser.cpp.
References m_treeView, setupTree(), and showEvent().
Referenced by showEvent().
updateKey
void CBookTreeChooser::updateKey (CSwordKey * key) final override slot
Inherited from ckeychooser
Definition at line 141 of file cbooktreechooser.cpp.
References key(), and setKey().
Referenced by CBookReadWindow::initConnections(), and refreshContent().
Member Data Documentation
m_key
CSwordTreeKey* CBookTreeChooser::m_key private
Definition at line 69 of file cbooktreechooser.h.
Referenced by CBookTreeChooser(), itemActivated(), key(), refreshContent(), setKey(), setModules(), and setupTree().
m_modules
QList<CSwordBookModuleInfo const *> CBookTreeChooser::m_modules private
Definition at line 68 of file cbooktreechooser.h.
Referenced by adjustFont(), CBookTreeChooser(), and setModules().
m_treeView
QTreeWidget* CBookTreeChooser::m_treeView private
Definition at line 70 of file cbooktreechooser.h.
Referenced by adjustFont(), CBookTreeChooser(), setKey(), setupTree(), and showEvent().
The documentation for this class was generated from the following files:
cbooktreechooser.h
cbooktreechooser.cpp