BibleTime: util Namespace Reference
util Namespace Reference
Namespaces
directory
tool
Functions
const QTextCodec & cp1252 ()
Function Documentation
cp1252()
const QTextCodec & util::cp1252 ()
Definition at line 31 of file cp1252.cpp.
Referenced by CSwordTreeKey::getLocalNameUnicode(), CSwordTreeKey::key(), CSwordLDKey::key(), CSwordTreeKey::setKey(), and CSwordLDKey::setKey().