BibleTime: anonymous_namespace{btbookshelfworkspage.cpp} Namespace Reference
anonymous_namespace{btbookshelfworkspage.cpp} Namespace Reference
Functions
bool filter (WizardTaskType const taskType, QStringList const &languages, CSwordModuleInfo const *const mInfo)
const QString groupingOrderKey ("GUI/BookshelfWizard/InstallPage/grouping")
const QString installPathKey ("GUI/BookshelfWizard/InstallPage/installPathIndex")
Function Documentation
filter()
bool anonymous_namespace{btbookshelfworkspage.cpp}::filter (WizardTaskType const taskType, QStringList const & languages, CSwordModuleInfo const *const mInfo) inline
Definition at line 80 of file btbookshelfworkspage.cpp.
Referenced by CDisplayTemplateMgr::CDisplayTemplateMgr(), CExportManager::getSaveFileName(), BtBookshelfWorksPage::initializePage(), Rendering::CTextRendering::renderEntry(), BtModelViewReadDisplay::save(), and BtBookshelfFilterModel::setNameFilterFixedString().
groupingOrderKey()
const QString anonymous_namespace{btbookshelfworkspage.cpp}::groupingOrderKey ("GUI/BookshelfWizard/InstallPage/grouping")
Referenced by BtBookshelfWorksPage::slotGroupingOrderChanged().
installPathKey()
const QString anonymous_namespace{btbookshelfworkspage.cpp}::installPathKey ("GUI/BookshelfWizard/InstallPage/installPathIndex")
Referenced by BtBookshelfWorksPage::slotInitPathCombo(), and BtBookshelfWorksPage::slotPathChanged().