BibleTime: util::cp1252::anonymous_namespace{cp1252.cpp}::Converter Class Reference
util::cp1252::anonymous_namespace{cp1252.cpp}::Converter Class Reference final
Public Member Functions
Converter ()
Converter (Converter &&)=delete
Converter (Converter const &)=delete
QByteArray fromUnicode (QString const &str, bool &error)
Converter & operator= (Converter &&)=delete
Converter & operator= (Converter const &)=delete
QString toUnicode (QByteArray const &data, bool &error)
~Converter ()
Private Attributes
UConverter *const m_converter
Detailed Description
Definition at line 51 of file cp1252.cpp.
Constructor & Destructor Documentation
Converter() [1/3]
util::cp1252::anonymous_namespace{cp1252.cpp}::Converter::Converter () inline
Definition at line 55 of file cp1252.cpp.
References r().
Converter() [2/3]
util::cp1252::anonymous_namespace{cp1252.cpp}::Converter::Converter (Converter &&) delete
Converter() [3/3]
util::cp1252::anonymous_namespace{cp1252.cpp}::Converter::Converter (Converter const &) delete
~Converter()
util::cp1252::anonymous_namespace{cp1252.cpp}::Converter::~Converter () inline
Definition at line 69 of file cp1252.cpp.
Member Function Documentation
fromUnicode()
QByteArray util::cp1252::anonymous_namespace{cp1252.cpp}::Converter::fromUnicode (QString const & str, bool & error) inline
Definition at line 100 of file cp1252.cpp.
Referenced by util::cp1252::fromUnicode().
operator=() [1/2]
Converter & util::cp1252::anonymous_namespace{cp1252.cpp}::Converter::operator= (Converter &&) delete
operator=() [2/2]
Converter & util::cp1252::anonymous_namespace{cp1252.cpp}::Converter::operator= (Converter const &) delete
toUnicode()
QString util::cp1252::anonymous_namespace{cp1252.cpp}::Converter::toUnicode (QByteArray const & data, bool & error) inline
Definition at line 74 of file cp1252.cpp.
Referenced by util::cp1252::toUnicode().
Member Data Documentation
m_converter
UConverter* const util::cp1252::anonymous_namespace{cp1252.cpp}::Converter::m_converter private
Definition at line 128 of file cp1252.cpp.
The documentation for this class was generated from the following file:
cp1252.cpp