BibleTime: BookmarkItem Class Reference
BookmarkItem Class Reference final
#include <BookmarkItem.h>
Public Member Functions
BookmarkItem (QString module, QString key, QString description)
QString const & description () const noexcept
QString const & key () const noexcept
QString const & module () const noexcept
Private Attributes
QString m_description
QString m_key
QString m_moduleName
Detailed Description
Class which represents a bookmark. Includes key, module name and description, all QStrings which have getter methods.
Definition at line 23 of file BookmarkItem.h.
Constructor & Destructor Documentation
BookmarkItem()
BookmarkItem::BookmarkItem (QString module, QString key, QString description) inline
Definition at line 27 of file BookmarkItem.h.
Member Function Documentation
description()
QString const& BookmarkItem::description () const inline noexcept
Returns
the bookmark description
Definition at line 40 of file BookmarkItem.h.
References m_description.
Referenced by BtBookmarksModelPrivate::saveItem(), and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::setDescription().
key()
QString BookmarkItem::key () const inline noexcept
Returns
the key
here we only translate
Parameters
key into current book name language
Definition at line 37 of file BookmarkItem.h.
References m_key.
Referenced by BtQuickWidget::dropEvent(), and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::setKey().
module()
CSwordModuleInfo * BookmarkItem::module () const inline noexcept
Returns
the module name
Definition at line 34 of file BookmarkItem.h.
References m_moduleName.
Referenced by BtBookmarksModelPrivate::saveItem().
Member Data Documentation
m_description
QString BookmarkItem::m_description private
The description of a bookmark.
Definition at line 46 of file BookmarkItem.h.
Referenced by anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::description(), description(), and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::setDescription().
m_key
QString BookmarkItem::m_key private
The key of a bookmark.
Definition at line 45 of file BookmarkItem.h.
Referenced by anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::englishKey(), key(), and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::setKey().
m_moduleName
QString BookmarkItem::m_moduleName private
The module which is used by this item.
Definition at line 44 of file BookmarkItem.h.
Referenced by module(), anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::moduleName(), and anonymous_namespace{btbookmarksmodel.cpp}::BookmarkItem::setModule().
The documentation for this class was generated from the following files:
BookmarkItem.h
btbookmarksmodel.cpp