BibleTime: ColorManager Class Reference
ColorManager Class Reference
#include <colormanager.h>
Public Member Functions
QString getBackgroundColor (QString const &style=QString())
QString getBackgroundHighlightColor (QString const &style=QString())
QString getCrossRefColor (QString const &style=QString())
QString getForegroundColor (QString const &style=QString())
void loadColorMaps ()
QString replaceColors (QString content)
Static Public Member Functions
static ColorManager & instance ()
Private Member Functions
ColorManager ()
Private Attributes
std::map< QString, std::map< QString, QString > > m_colorMaps
Detailed Description
Definition at line 19 of file colormanager.h.
Constructor & Destructor Documentation
ColorManager()
ColorManager::ColorManager () private default
Member Function Documentation
getBackgroundColor()
QString ColorManager::getBackgroundColor (QString const & style = QString())
Definition at line 136 of file colormanager.cpp.
References anonymous_namespace{colormanager.cpp}::getColorByPattern(), and m_colorMaps.
Referenced by BtQmlInterface::getBackgroundColor().
getBackgroundHighlightColor()
QString ColorManager::getBackgroundHighlightColor (QString const & style = QString())
Definition at line 139 of file colormanager.cpp.
References anonymous_namespace{colormanager.cpp}::getColorByPattern(), and m_colorMaps.
Referenced by BtQmlInterface::getBackgroundHighlightColor().
getCrossRefColor()
QString ColorManager::getCrossRefColor (QString const & style = QString())
Definition at line 145 of file colormanager.cpp.
References anonymous_namespace{colormanager.cpp}::getColorByPattern(), and m_colorMaps.
getForegroundColor()
QString ColorManager::getForegroundColor (QString const & style = QString())
Definition at line 142 of file colormanager.cpp.
References anonymous_namespace{colormanager.cpp}::getColorByPattern(), and m_colorMaps.
Referenced by BtQmlInterface::getForegroundColor().
instance()
ColorManager & ColorManager::instance () static
Definition at line 53 of file colormanager.cpp.
Referenced by BtQmlInterface::getBackgroundColor(), BtQmlInterface::getBackgroundHighlightColor(), BtQmlInterface::getForegroundColor(), BibleTimeApp::initColorManager(), BtModuleTextModel::lexiconData(), InfoDisplay::CInfoDisplay::setInfo(), InfoDisplay::CInfoDisplay::updateColors(), CDisplaySettingsPage::updateColors(), Search::BtSearchResultArea::updatePreview(), CDisplaySettingsPage::updateStylePreview(), and BtModuleTextModel::verseData().
loadColorMaps()
void ColorManager::loadColorMaps ()
Definition at line 61 of file colormanager.cpp.
References anonymous_namespace{colormanager.cpp}::darkMode(), util::directory::getDisplayTemplatesDir(), util::directory::getUserDisplayTemplatesDir(), and m_colorMaps.
Referenced by BibleTimeApp::initColorManager().
replaceColors()
QString ColorManager::replaceColors (QString content)
Definition at line 128 of file colormanager.cpp.
References CDisplayTemplateMgr::activeTemplateName(), and m_colorMaps.
Referenced by BtModuleTextModel::lexiconData(), InfoDisplay::CInfoDisplay::setInfo(), Search::BtSearchResultArea::updatePreview(), CDisplaySettingsPage::updateStylePreview(), and BtModuleTextModel::verseData().
Member Data Documentation
m_colorMaps
std::map<QString, std::map<QString, QString> > ColorManager::m_colorMaps private
Definition at line 48 of file colormanager.h.
Referenced by getBackgroundColor(), getBackgroundHighlightColor(), getCrossRefColor(), getForegroundColor(), loadColorMaps(), and replaceColors().
The documentation for this class was generated from the following files:
colormanager.h
colormanager.cpp