BibleTime: Filters::ThmlToHtml Class Reference
Filters::ThmlToHtml Class Reference
ThML to HTML conversion filter.
#include <thmltohtml.h>
Classes
class UserData
Public Member Functions
bool handleToken (sword::SWBuf &buf, const char *token, sword::BasicFilterUserData *userData) override
char processText (sword::SWBuf &buf, const sword::SWKey *key, const sword::SWModule *module=nullptr) override
ThmlToHtml ()
Protected Member Functions
sword::BasicFilterUserData * createUserData (sword::SWModule const *module, sword::SWKey const *key) override
Detailed Description
ThML to HTML conversion filter.
Definition at line 40 of file thmltohtml.h.
Constructor & Destructor Documentation
ThmlToHtml()
Filters::ThmlToHtml::ThmlToHtml ()
Definition at line 46 of file thmltohtml.cpp.
Member Function Documentation
createUserData()
sword::BasicFilterUserData* Filters::ThmlToHtml::createUserData (sword::SWModule const * module, sword::SWKey const * key) inline override protected
Definition at line 69 of file thmltohtml.h.
handleToken()
bool ThmlToHtml::handleToken (sword::SWBuf & buf, const char * token, sword::BasicFilterUserData * userData) override
Definition at line 237 of file thmltohtml.cpp.
References Filters::ThmlToHtml::UserData::absolutePath, CSwordModuleInfo::Bible, BT_ASSERT, btConfig(), ReferenceManager::encodeHyperlink(), CSwordBackend::findFirstAvailableModule(), BtConfig::getDefaultSwordModuleByType(), Filters::ThmlToHtml::UserData::inFootnoteTag, Filters::ThmlToHtml::UserData::inscriptRef, CSwordBackend::instance(), ReferenceManager::parseVerseReference(), and Filters::ThmlToHtml::UserData::swordFootnote.
processText()
char Filters::ThmlToHtml::processText (sword::SWBuf & buf, const sword::SWKey * key, const sword::SWModule * module = nullptr) override
Bug:
e.replace() instead?
Definition at line 60 of file thmltohtml.cpp.
References BT_ASSERT, CSwordBackend::instance(), CSwordModuleInfo::lemmas, anonymous_namespace{btmoduletextmodel.cpp}::processText(), and CSwordModuleInfo::strongNumbers.
The documentation for this class was generated from the following files:
thmltohtml.h
thmltohtml.cpp