BibleTime: BtQuickWidget Class Reference
BtQuickWidget Class Reference
#include <btquickwidget.h>
Signals
void referenceDropped (const QString &reference)
Public Member Functions
BtQuickWidget (BtQmlScrollView *widget)
int getFirstSelectedIndex () const
int getLastSelectedIndex () const
CSwordKey * getMouseClickedKey ()
int getSelectedColumn () const
void mouseMove (int x, int y)
void mousePressed (int x, int y)
void mouseReleased (int x, int y)
void saveContextMenuIndex (int x, int y)
void scroll (int pixels)
void updateReferenceText ()
Protected Member Functions
void dragEnterEvent (QDragEnterEvent *e) override
void dragMoveEvent (QDragMoveEvent *event) override
void dropEvent (QDropEvent *e) override
virtual bool event (QEvent *e) override
virtual void mouseDoubleClickEvent (QMouseEvent *event) override
virtual void mouseMoveEvent (QMouseEvent *event) override
virtual void mousePressEvent (QMouseEvent *event) override
virtual void mouseReleaseEvent (QMouseEvent *event) override
virtual void wheelEvent (QWheelEvent *event) override
Private Slots
void scrollTimerSlot ()
Private Member Functions
BtQmlInterface * getQmlInterface () const
void setupScrollTimer ()
void startScrollTimer ()
void stopScrollTimer ()
Private Attributes
BtQmlScrollView * m_scrollView
QTimer m_timer
Detailed Description
Definition at line 28 of file btquickwidget.h.
Constructor & Destructor Documentation
BtQuickWidget()
BtQuickWidget::BtQuickWidget (BtQmlScrollView * widget)
Definition at line 34 of file btquickwidget.cpp.
References setupScrollTimer().
Member Function Documentation
dragEnterEvent()
void BtQuickWidget::dragEnterEvent (QDragEnterEvent * e) override protected
Definition at line 53 of file btquickwidget.cpp.
References CSwordModuleInfo::Bible, BT_ASSERT, CSwordModuleInfo::Commentary, CSwordBackend::findModuleByName(), getQmlInterface(), CSwordBackend::instance(), BookmarkItem::module(), and CSwordModuleInfo::type().
dragMoveEvent()
void BtQuickWidget::dragMoveEvent (QDragMoveEvent * event) override protected
Definition at line 102 of file btquickwidget.cpp.
dropEvent()
void BtQuickWidget::dropEvent (QDropEvent * e) override protected
Definition at line 85 of file btquickwidget.cpp.
References BookmarkItem::key(), and referenceDropped().
event()
bool BtQuickWidget::event (QEvent * e) override protected virtual
Definition at line 169 of file btquickwidget.cpp.
References BtQmlInterface::cancelMagTimer(), and getQmlInterface().
Referenced by mouseMoveEvent(), mousePressEvent(), mouseReleaseEvent(), and wheelEvent().
getFirstSelectedIndex()
int BtQuickWidget::getFirstSelectedIndex () const
Definition at line 137 of file btquickwidget.cpp.
References BT_ASSERT.
Referenced by CDisplayWindow::getFirstSelectedIndex().
getLastSelectedIndex()
int BtQuickWidget::getLastSelectedIndex () const
Definition at line 146 of file btquickwidget.cpp.
References BT_ASSERT.
Referenced by CDisplayWindow::getLastSelectedIndex().
getMouseClickedKey()
CSwordKey * BtQuickWidget::getMouseClickedKey ()
Definition at line 155 of file btquickwidget.cpp.
References BtQmlInterface::getMouseClickedKey(), and getQmlInterface().
getQmlInterface()
BtQmlInterface * BtQuickWidget::getQmlInterface () const private
Definition at line 48 of file btquickwidget.cpp.
References BtQmlScrollView::getQmlInterface(), and m_scrollView.
Referenced by dragEnterEvent(), event(), and getMouseClickedKey().
getSelectedColumn()
int BtQuickWidget::getSelectedColumn () const
Definition at line 128 of file btquickwidget.cpp.
References BT_ASSERT.
Referenced by CDisplayWindow::getSelectedColumn().
mouseDoubleClickEvent()
void BtQuickWidget::mouseDoubleClickEvent (QMouseEvent * event) override protected virtual
Definition at line 175 of file btquickwidget.cpp.
mouseMove()
void BtQuickWidget::mouseMove (int x, int y)
Definition at line 226 of file btquickwidget.cpp.
References BT_ASSERT.
Referenced by mouseMoveEvent().
mouseMoveEvent()
void BtQuickWidget::mouseMoveEvent (QMouseEvent * event) override protected virtual
Definition at line 189 of file btquickwidget.cpp.
References event(), mouseMove(), startScrollTimer(), and stopScrollTimer().
mousePressed()
void BtQuickWidget::mousePressed (int x, int y)
Definition at line 216 of file btquickwidget.cpp.
References BT_ASSERT.
Referenced by mousePressEvent().
mousePressEvent()
void BtQuickWidget::mousePressEvent (QMouseEvent * event) override protected virtual
Definition at line 180 of file btquickwidget.cpp.
References event(), and mousePressed().
mouseReleased()
void BtQuickWidget::mouseReleased (int x, int y)
Definition at line 235 of file btquickwidget.cpp.
References BT_ASSERT, and stopScrollTimer().
Referenced by mouseReleaseEvent().
mouseReleaseEvent()
void BtQuickWidget::mouseReleaseEvent (QMouseEvent * event) override protected virtual
Definition at line 207 of file btquickwidget.cpp.
References event(), and mouseReleased().
referenceDropped
void BtQuickWidget::referenceDropped (const QString & reference) signal
Referenced by BtQmlScrollView::BtQmlScrollView(), and dropEvent().
saveContextMenuIndex()
void BtQuickWidget::saveContextMenuIndex (int x, int y)
Definition at line 111 of file btquickwidget.cpp.
References BT_ASSERT.
Referenced by BtQmlScrollView::contextMenuEvent().
scroll()
void BtQuickWidget::scroll (int pixels)
Definition at line 159 of file btquickwidget.cpp.
References BT_ASSERT.
Referenced by BtModelViewReadDisplay::scroll(), scrollTimerSlot(), and BtQmlScrollView::slotSliderMoved().
scrollTimerSlot
void BtQuickWidget::scrollTimerSlot () private slot
Definition at line 262 of file btquickwidget.cpp.
References m_timer, and scroll().
Referenced by setupScrollTimer().
setupScrollTimer()
void BtQuickWidget::setupScrollTimer () private
Definition at line 245 of file btquickwidget.cpp.
References m_timer, and scrollTimerSlot().
Referenced by BtQuickWidget().
startScrollTimer()
void BtQuickWidget::startScrollTimer () private
Definition at line 251 of file btquickwidget.cpp.
References m_timer.
Referenced by mouseMoveEvent().
stopScrollTimer()
void BtQuickWidget::stopScrollTimer () private
Definition at line 257 of file btquickwidget.cpp.
References m_timer.
Referenced by mouseMoveEvent(), and mouseReleased().
updateReferenceText()
void BtQuickWidget::updateReferenceText ()
Definition at line 122 of file btquickwidget.cpp.
References BT_ASSERT.
Referenced by BtQmlScrollView::slotSliderReleased(), and BtModelViewReadDisplay::updateReferenceText().
wheelEvent()
void BtQuickWidget::wheelEvent (QWheelEvent * event) override protected virtual
Definition at line 280 of file btquickwidget.cpp.
References BibleTime::autoScrollStop(), event(), and BibleTime::instance().
Member Data Documentation
m_scrollView
BtQmlScrollView* BtQuickWidget::m_scrollView private
Definition at line 69 of file btquickwidget.h.
Referenced by getQmlInterface().
m_timer
QTimer BtQuickWidget::m_timer private
Definition at line 71 of file btquickwidget.h.
Referenced by scrollTimerSlot(), setupScrollTimer(), startScrollTimer(), and stopScrollTimer().
The documentation for this class was generated from the following files:
btquickwidget.h
btquickwidget.cpp