BibleTime: CSwordBackend Class Reference
CSwordBackend Class Reference
The backend layer main class, a backend implementation of Sword.
#include <cswordbackend.h>
Classes
struct Private
Public Types
enum LoadError { NoSwordConfig = -1, NoError = 0, NoModules = 1 }
The error codes which may be returned by the Load() call.
enum SetupChangedReason {
AddedModules = 1, RemovedModules = 2, HidedModules = 4, PathChanged = 8,
OtherChange = 16
}
The reason for the sigSwordSetupChanged signal, i.e. why the module list has changed.
Signals
void sigSwordSetupChanged (CSwordBackend::SetupChangedReason reason)
Public Member Functions
std::shared_ptr< AvailableLanguagesCacheContainer const > availableLanguages () noexcept
QString booknameLanguage () const
CSwordBackend (const QString &path, const bool augmentHome=true)
void deleteOrphanedIndices ()
CSwordModuleInfo * findFirstAvailableModule (CSwordModuleInfo::ModuleType type)
CSwordModuleInfo * findModuleByDescription (const QString &description) const
Searches for a module with the given description.
CSwordModuleInfo * findModuleByName (const QString &name) const
Searches for a module with the given name.
CSwordModuleInfo * findSwordModuleByPointer (const sword::SWModule *const swmodule) const
Searches for a module with the given sword module as module().
sword::SWConfig * getConfig () const
BtConstModuleList getConstPointerList (const QStringList &names) const
QList< CSwordModuleInfo * > getPointerList (const QStringList &names) const
CSwordBackend::LoadError initModules (const SetupChangedReason reason)
Initializes the Sword modules.
std::shared_ptr< BtBookshelfModel > model ()
const QList< CSwordModuleInfo * > & moduleList () const
QString prefixPath () const
sword::SWMgr & raw ()
void reloadModules (const SetupChangedReason reason)
Reloads all Sword modules.
void setBooknameLanguage (QString const &langName)
Sets the language for the international booknames of Sword.
void setFilterOptions (const FilterOptions &options)
void setOption (const CSwordModuleInfo::FilterTypes type, const int state)
Sets the state of the given filter option.
void shutdownModules ()
Deinitializes and frees the modules.
QStringList swordDirList () const
Sword prefix list.
void uninstallModules (BtConstModuleSet const &modules)
Uninstalls the given modules.
~CSwordBackend () override
Static Public Member Functions
static QString configOptionName (const CSwordModuleInfo::FilterTypes option)
static CSwordBackend * createInstance ()
static void destroyInstance ()
Destroys the singleton instance, if one exists.
static CSwordBackend * instance ()
static QString optionName (const CSwordModuleInfo::FilterTypes option)
static QString translatedOptionName (const CSwordModuleInfo::FilterTypes option)
Protected Member Functions
CSwordBackend ()
QString getPrivateSwordConfigFile () const
QString getPrivateSwordConfigPath () const
QStringList getSharedSwordConfigFiles () const
Private Types
using AvailableLanguagesCacheContainer = std::set< std::shared_ptr< Language const > >
Private Attributes
std::shared_ptr< AvailableLanguagesCacheContainer const > m_availableLanguagesCache
Rendering::CBookDisplay m_bookDisplay
Rendering::CChapterDisplay m_chapterDisplay
const std::shared_ptr< BtBookshelfModel > m_dataModel
Rendering::CEntryDisplay m_entryDisplay
CSwordBackend::Private m_manager
Static Private Attributes
static CSwordBackend * m_instance = nullptr
Detailed Description
The backend layer main class, a backend implementation of Sword.
This is the implementation of CBackend for Sword. It's additionally derived from SWMgr to provide functions of Sword.
Note
Mostly, only one instance of this class is used. This instance is created by BibleTime::initBackends() and is destroyed by BibleTimeApp::~BibleTimeApp(). Only when managing modules separate backends are created.
Definition at line 58 of file cswordbackend.h.
Member Typedef Documentation
AvailableLanguagesCacheContainer
using CSwordBackend::AvailableLanguagesCacheContainer = std::set<std::shared_ptr<Language const> > private
Definition at line 89 of file cswordbackend.h.
Member Enumeration Documentation
LoadError
enum CSwordBackend::LoadError
The error codes which may be returned by the Load() call.
Note
These values exist to cast from the char return of SWMgr::Load().
Enumerator
NoSwordConfig
NoError
NoModules
Definition at line 80 of file cswordbackend.h.
SetupChangedReason
enum CSwordBackend::SetupChangedReason
The reason for the sigSwordSetupChanged signal, i.e. why the module list has changed.
Enumerator
AddedModules
RemovedModules
HidedModules
PathChanged
OtherChange
Definition at line 68 of file cswordbackend.h.
Constructor & Destructor Documentation
CSwordBackend() [1/2]
CSwordBackend::CSwordBackend (const QString & path, const bool augmentHome = true)
Note
Used by BtInstallBackend only.
Using augmentHome=false can mess up the system because it is true elsewhere.
Parameters
[in] path The path which is used to load modules.
[in] augmentHome Whether $HOME/.sword/ modules should be augmented with the other modules.
Definition at line 68 of file cswordbackend.cpp.
~CSwordBackend()
CSwordBackend::~CSwordBackend () override
Definition at line 75 of file cswordbackend.cpp.
References shutdownModules().
CSwordBackend() [2/2]
CSwordBackend::CSwordBackend () protected
Creates the SWModule objects using SWMgr's methods, it adds the necessary filters for the module format.
Definition at line 50 of file cswordbackend.cpp.
References BT_CONNECT, m_availableLanguagesCache, and m_dataModel.
Referenced by createInstance().
Member Function Documentation
availableLanguages()
std::shared_ptr< CSwordBackend::AvailableLanguagesCacheContainer const > CSwordBackend::availableLanguages () noexcept
Definition at line 89 of file cswordbackend.cpp.
References m_availableLanguagesCache, m_dataModel, and model().
Referenced by BtFontSettingsPage::BtFontSettingsPage(), and CDisplayTemplateMgr::fillTemplate().
booknameLanguage()
QString CSwordBackend::booknameLanguage () const
Returns
the language for the international booknames of Sword.
Definition at line 444 of file cswordbackend.cpp.
References BtLocaleMgr::defaultLocaleName().
Referenced by CSwordBibleModuleInfo::books().
configOptionName()
QString CSwordBackend::configOptionName (const CSwordModuleInfo::FilterTypes option) static
Parameters
[in] option The configuration option name to return.
Returns
the text used for the configuration option given.
Definition at line 414 of file cswordbackend.cpp.
References CSwordModuleInfo::footnotes, CSwordModuleInfo::greekAccents, CSwordModuleInfo::headings, CSwordModuleInfo::hebrewCantillation, CSwordModuleInfo::hebrewPoints, CSwordModuleInfo::lemmas, CSwordModuleInfo::morphSegmentation, CSwordModuleInfo::morphTags, CSwordModuleInfo::redLetterWords, CSwordModuleInfo::scriptureReferences, CSwordModuleInfo::strongNumbers, and CSwordModuleInfo::textualVariants.
Referenced by CSwordModuleInfo::has().
createInstance()
static CSwordBackend* CSwordBackend::createInstance () inline static
Returns
the CSwordBackend singleton instance (created if needed).
Definition at line 106 of file cswordbackend.h.
References BT_ASSERT, CSwordBackend(), and m_instance.
Referenced by BibleTime::initBackends().
deleteOrphanedIndices()
void CSwordBackend::deleteOrphanedIndices ()
Deletes all indices of modules where hasIndex() returns false (because of wrong index version etc.) and deletes all orphaned indexes (no module present) if autoDeleteOrphanedIndices is true.
Definition at line 567 of file cswordbackend.cpp.
References btConfig(), CSwordModuleInfo::deleteIndexForModule(), findModuleByName(), and CSwordModuleInfo::getGlobalBaseIndexLocation().
destroyInstance()
static void CSwordBackend::destroyInstance () inline static
Destroys the singleton instance, if one exists.
Definition at line 116 of file cswordbackend.h.
References m_instance.
Referenced by BibleTimeApp::~BibleTimeApp().
findFirstAvailableModule()
CSwordModuleInfo * CSwordBackend::findFirstAvailableModule (CSwordModuleInfo::ModuleType type)
Definition at line 79 of file cswordbackend.cpp.
References moduleList().
Referenced by anonymous_namespace{osistohtml.cpp}::renderReference().
findModuleByDescription()
CSwordModuleInfo * CSwordBackend::findModuleByDescription (const QString & description) const
Searches for a module with the given description.
Parameters
[in] description The description of the desired module.
Returns
a pointer to the desired module or NULL if not found.
Definition at line 332 of file cswordbackend.cpp.
References CSwordModuleInfo::Description, and m_dataModel.
findModuleByName()
CSwordModuleInfo * CSwordBackend::findModuleByName (const QString & name) const
Searches for a module with the given name.
Parameters
[in] name The name of the desired module.
Returns
a pointer to the desired module or NULL if not found.
Definition at line 339 of file cswordbackend.cpp.
References m_dataModel.
Referenced by BtQmlInterface::configModuleByType(), ReferenceManager::decodeHyperlink(), Rendering::decodeMorph(), deleteOrphanedIndices(), BtQuickWidget::dragEnterEvent(), CBookmarkIndex::dropEvent(), getConstPointerList(), BtConfig::getDefaultSwordModuleByType(), BtQmlInterface::getFontsFromSettings(), getPointerList(), BtQmlInterface::getRawText(), Search::BtSearchOptionsArea::initConnections(), CDisplayWindow::lookupKey(), BtQmlInterface::moduleIsWritable(), BtConfig::parseVerseListWithModules(), Filters::GbfToHtml::processText(), BtModuleTextModel::reloadModules(), BibleTime::reloadProfile(), BtInstallThread::removeModule(), Filters::TeiToHtml::renderReference(), and Filters::TeiToHtml::renderTargetReference().
findSwordModuleByPointer()
CSwordModuleInfo * CSwordBackend::findSwordModuleByPointer (const sword::SWModule *const swmodule) const
Searches for a module with the given sword module as module().
Parameters
[in] swmodule The SWModule of the desired module.
Returns
a pointer to the desired module or NULL if not found.
Definition at line 346 of file cswordbackend.cpp.
References m_dataModel.
getConfig()
sword::SWConfig* CSwordBackend::getConfig () const inline
Returns
The global config object containing the configs of all modules merged together.
Definition at line 192 of file cswordbackend.h.
References m_manager.
Referenced by CSwordModuleInfo::isEncrypted().
getConstPointerList()
BtConstModuleList CSwordBackend::getConstPointerList (const QStringList & names) const
Parameters
[in] names The names of the modules to return.
Returns
a list of pointers to const modules, created from a list of module names.
Definition at line 170 of file cswordbackend.cpp.
References findModuleByName().
Referenced by CDisplayWindow::modules().
getPointerList()
QList< CSwordModuleInfo * > CSwordBackend::getPointerList (const QStringList & names) const
Parameters
[in] names The names of the modules to return.
Returns
a list of pointers to modules, created from a list of module names.
Definition at line 162 of file cswordbackend.cpp.
References findModuleByName().
getPrivateSwordConfigFile()
QString CSwordBackend::getPrivateSwordConfigFile () const protected
Definition at line 503 of file cswordbackend.cpp.
References util::directory::convertDirSeparators(), and getPrivateSwordConfigPath().
Referenced by swordDirList().
getPrivateSwordConfigPath()
QString CSwordBackend::getPrivateSwordConfigPath () const protected
Definition at line 499 of file cswordbackend.cpp.
References util::directory::getUserHomeSwordDir().
Referenced by getPrivateSwordConfigFile(), and swordDirList().
getSharedSwordConfigFiles()
QStringList CSwordBackend::getSharedSwordConfigFiles () const protected
Reimplemented from sword::SWMgr.
Definition at line 488 of file cswordbackend.cpp.
References util::directory::convertDirSeparators(), and m_manager.
Referenced by swordDirList().
initModules()
CSwordBackend::LoadError CSwordBackend::initModules (const SetupChangedReason reason)
Initializes the Sword modules.
Returns
whether the initializiation was successful.
Todo:
Refactor data model to use shared_ptr to contain works
Definition at line 178 of file cswordbackend.cpp.
References BT_ASSERT, btConfig(), m_bookDisplay, m_chapterDisplay, m_dataModel, m_entryDisplay, m_manager, shutdownModules(), and sigSwordSetupChanged().
Referenced by BibleTime::initBackends(), and reloadModules().
instance()
static CSwordBackend* CSwordBackend::instance () inline static
Returns
the singleton instance, creating it if one does not exist.
Definition at line 113 of file cswordbackend.h.
References m_instance.
Referenced by BtBookshelfDockWidget::BtBookshelfDockWidget(), BtBookshelfWorksPage::BtBookshelfWorksPage(), BtFontSettingsPage::BtFontSettingsPage(), BtIndexDialog::BtIndexDialog(), BtOpenWorkAction::BtOpenWorkAction(), BtSearchModuleChooserDialog::BtSearchModuleChooserDialog(), BtStandardWorksTab::BtStandardWorksTab(), BtQmlInterface::configModuleByType(), BtIndexDialog::createIndices(), BtInstallPageModel::data(), ReferenceManager::decodeHyperlink(), Rendering::decodeMorph(), BtIndexDialog::deleteIndices(), BtQuickWidget::dragEnterEvent(), CBookmarkIndex::dropEvent(), CDisplayTemplateMgr::fillTemplate(), BtConfig::getDefaultSwordModuleByType(), BtQmlInterface::getFontsFromSettings(), CSwordModuleInfo::getFormattedConfigEntry(), anonymous_namespace{cdisplaywindow.cpp}::getProfileWindow(), BtQmlInterface::getRawText(), BibleTime::initBackends(), Search::BtSearchOptionsArea::initConnections(), BtBookshelfRemoveFinalPage::initializePage(), CDisplayWindow::lookupKey(), main(), BtQmlInterface::moduleIsWritable(), CDisplayWindow::modules(), BibleTime::moduleUnlock(), BtTextBrowser::mouseMoveEvent(), BtConfig::parseVerseListWithModules(), ReferenceManager::parseVerseReference(), BtIndexDialog::populateModuleList(), Filters::GbfToHtml::processText(), CCommentaryReadWindow::reload(), CBibleReadWindow::reload(), CDisplayWindow::reload(), BtModuleTextModel::reloadModules(), BibleTime::reloadProfile(), BtInstallThread::removeModule(), Rendering::CTextRendering::renderKeyTree(), anonymous_namespace{osistohtml.cpp}::renderReference(), Filters::TeiToHtml::renderReference(), Filters::TeiToHtml::renderTargetReference(), BtInstallBackend::setTargetList(), BibleTime::slotSettingsOptions(), BtBookshelfInstallFinalPage::slotThreadFinished(), BtInstallBackend::targetList(), BtModelViewReadDisplay::text(), BtBookshelfTaskPage::timeToUpdate(), BtBookmarksModelPrivate::BookmarkItem::toolTip(), BtModuleChooserButton::updateMenu(), and BtTextWindowHeaderWidget::updateWidget().
model()
std::shared_ptr<BtBookshelfModel> CSwordBackend::model () inline
Definition at line 129 of file cswordbackend.h.
References m_dataModel.
Referenced by availableLanguages().
moduleList()
const QList<CSwordModuleInfo*>& CSwordBackend::moduleList () const inline
Warning
You have to call initModules() first.
Note
This method is equivalent to model()->modules().
Returns
The list of modules managed by this backend.
Definition at line 126 of file cswordbackend.h.
References m_dataModel.
Referenced by findFirstAvailableModule(), main(), and BtIndexDialog::populateModuleList().
optionName()
QString CSwordBackend::optionName (const CSwordModuleInfo::FilterTypes option) static
Parameters
[in] option The option name to return.
Returns
The name of the option given by the parameter.
Definition at line 353 of file cswordbackend.cpp.
References CSwordModuleInfo::footnotes, CSwordModuleInfo::greekAccents, CSwordModuleInfo::headings, CSwordModuleInfo::hebrewCantillation, CSwordModuleInfo::hebrewPoints, CSwordModuleInfo::lemmas, CSwordModuleInfo::morphSegmentation, CSwordModuleInfo::morphTags, CSwordModuleInfo::redLetterWords, CSwordModuleInfo::scriptureReferences, CSwordModuleInfo::strongNumbers, and CSwordModuleInfo::textualVariants.
Referenced by setOption().
prefixPath()
QString CSwordBackend::prefixPath () const inline
Definition at line 251 of file cswordbackend.h.
References m_manager.
Referenced by CSwordBackend::Private::reloadConfig(), BtInstallThread::removeModule(), and uninstallModules().
raw()
sword::SWMgr& CSwordBackend::raw () inline
Definition at line 254 of file cswordbackend.h.
References m_manager.
Referenced by CSwordModuleInfo::unlock().
reloadModules()
void CSwordBackend::reloadModules (const SetupChangedReason reason)
Reloads all Sword modules.
Parameters
[in] reason The reason for the reload.
Definition at line 466 of file cswordbackend.cpp.
References initModules(), m_manager, CSwordBackend::Private::reloadConfig(), and shutdownModules().
Referenced by BtInstallBackend::setTargetList(), and BtBookshelfInstallFinalPage::slotThreadFinished().
setBooknameLanguage()
void CSwordBackend::setBooknameLanguage (QString const & langName)
Sets the language for the international booknames of Sword.
Parameters
[in] langName The abbreviation string which should be used for the Sword backend.
Definition at line 447 of file cswordbackend.cpp.
References CSwordModuleInfo::Bible, CSwordModuleInfo::Commentary, BtLocaleMgr::defaultLocaleName(), m_dataModel, and BtLocaleMgr::setDefaultLocaleName().
Referenced by BibleTime::slotSettingsOptions().
setFilterOptions()
void CSwordBackend::setFilterOptions (const FilterOptions & options)
Definition at line 316 of file cswordbackend.cpp.
References FilterOptions::footnotes, CSwordModuleInfo::footnotes, FilterOptions::greekAccents, CSwordModuleInfo::greekAccents, FilterOptions::headings, CSwordModuleInfo::headings, FilterOptions::hebrewCantillation, CSwordModuleInfo::hebrewCantillation, FilterOptions::hebrewPoints, CSwordModuleInfo::hebrewPoints, FilterOptions::lemmas, CSwordModuleInfo::lemmas, FilterOptions::morphSegmentation, CSwordModuleInfo::morphSegmentation, FilterOptions::morphTags, CSwordModuleInfo::morphTags, FilterOptions::redLetterWords, CSwordModuleInfo::redLetterWords, FilterOptions::scriptureReferences, CSwordModuleInfo::scriptureReferences, setOption(), FilterOptions::strongNumbers, CSwordModuleInfo::strongNumbers, FilterOptions::textualVariants, and CSwordModuleInfo::textualVariants.
Referenced by CSwordModuleInfo::buildIndex(), Rendering::CTextRendering::renderKeyTree(), BtModelViewReadDisplay::text(), and BtBookmarksModelPrivate::BookmarkItem::toolTip().
setOption()
void CSwordBackend::setOption (const CSwordModuleInfo::FilterTypes type, const int state)
Sets the state of the given filter option.
Parameters
[in] type The filter type whose state to set.
[in] state The new filter option state.
Definition at line 292 of file cswordbackend.cpp.
References m_manager, optionName(), and CSwordModuleInfo::textualVariants.
Referenced by CSwordModuleInfo::buildIndex(), setFilterOptions(), and CSwordModuleInfo::setImportantFilterOptions().
shutdownModules()
void CSwordBackend::shutdownModules ()
Deinitializes and frees the modules.
Returns
whether the method succeeded.
Definition at line 270 of file cswordbackend.cpp.
References m_dataModel, m_manager, and CSwordBackend::Private::shutdownModules().
Referenced by initModules(), reloadModules(), and ~CSwordBackend().
sigSwordSetupChanged
void CSwordBackend::sigSwordSetupChanged (CSwordBackend::SetupChangedReason reason) signal
Referenced by BtBookshelfWorksPage::BtBookshelfWorksPage(), BtIndexDialog::BtIndexDialog(), anonymous_namespace{cdisplaywindow.cpp}::getProfileWindow(), initModules(), and uninstallModules().
swordDirList()
QStringList CSwordBackend::swordDirList () const
Sword prefix list.
Returns
A list of all known Sword prefix dirs
Definition at line 508 of file cswordbackend.cpp.
References util::directory::convertDirSeparators(), getPrivateSwordConfigFile(), getPrivateSwordConfigPath(), and getSharedSwordConfigFiles().
Referenced by BtInstallBackend::targetList().
translatedOptionName()
QString CSwordBackend::translatedOptionName (const CSwordModuleInfo::FilterTypes option) static
Parameters
[in] option The translated option name.
Returns
the translated name of the option given.
Definition at line 383 of file cswordbackend.cpp.
References CSwordModuleInfo::footnotes, CSwordModuleInfo::greekAccents, CSwordModuleInfo::headings, CSwordModuleInfo::hebrewCantillation, CSwordModuleInfo::hebrewPoints, CSwordModuleInfo::lemmas, CSwordModuleInfo::morphSegmentation, CSwordModuleInfo::morphTags, CSwordModuleInfo::redLetterWords, CSwordModuleInfo::scriptureReferences, CSwordModuleInfo::strongNumbers, and CSwordModuleInfo::textualVariants.
Referenced by CSwordModuleInfo::aboutText().
uninstallModules()
void CSwordBackend::uninstallModules (BtConstModuleSet const & modules)
Uninstalls the given modules.
Parameters
[in] modules The modules to uninstall.
Definition at line 119 of file cswordbackend.cpp.
References CSwordModuleInfo::AbsoluteDataPath, CSwordModuleInfo::DataPath, m_dataModel, prefixPath(), RemovedModules, and sigSwordSetupChanged().
Referenced by BtBookshelfRemoveFinalPage::initializePage().
Member Data Documentation
m_availableLanguagesCache
std::shared_ptr<AvailableLanguagesCacheContainer const> CSwordBackend::m_availableLanguagesCache private
Definition at line 304 of file cswordbackend.h.
Referenced by availableLanguages(), and CSwordBackend().
m_bookDisplay
Rendering::CBookDisplay CSwordBackend::m_bookDisplay private
Definition at line 300 of file cswordbackend.h.
Referenced by initModules().
m_chapterDisplay
Rendering::CChapterDisplay CSwordBackend::m_chapterDisplay private
Definition at line 298 of file cswordbackend.h.
Referenced by initModules().
m_dataModel
const std::shared_ptr<BtBookshelfModel> CSwordBackend::m_dataModel private
Definition at line 302 of file cswordbackend.h.
Referenced by availableLanguages(), CSwordBackend(), findModuleByDescription(), findModuleByName(), findSwordModuleByPointer(), initModules(), model(), moduleList(), setBooknameLanguage(), shutdownModules(), and uninstallModules().
m_entryDisplay
Rendering::CEntryDisplay CSwordBackend::m_entryDisplay private
Definition at line 299 of file cswordbackend.h.
Referenced by initModules().
m_instance
CSwordBackend * CSwordBackend::m_instance = nullptr static private
Definition at line 306 of file cswordbackend.h.
Referenced by createInstance(), destroyInstance(), and instance().
m_manager
CSwordBackend::Private CSwordBackend::m_manager private
Referenced by getConfig(), getSharedSwordConfigFiles(), initModules(), prefixPath(), raw(), reloadModules(), setOption(), and shutdownModules().
The documentation for this class was generated from the following files:
cswordbackend.h
cswordbackend.cpp