BibleTime: Search::CSearchDialog Class Reference
Search::CSearchDialog Class Reference final
#include <csearchdialog.h>
Public Member Functions
CSearchDialog (QWidget *parent)
void reset (BtConstModuleList modules, QString const &searchText)
~CSearchDialog () override
Private Slots
void startSearch ()
Private Attributes
QPushButton * m_analyseButton
QPushButton * m_closeButton
QPushButton * m_manageIndexes
BtSearchOptionsArea * m_searchOptionsArea
BtSearchResultArea * m_searchResultArea
Detailed Description
Note
destroys itself on close
Definition at line 31 of file csearchdialog.h.
Constructor & Destructor Documentation
CSearchDialog()
Search::CSearchDialog::CSearchDialog (QWidget * parent)
Definition at line 43 of file csearchdialog.cpp.
References BT_CONNECT, btConfig(), m_analyseButton, m_closeButton, m_manageIndexes, m_searchOptionsArea, m_searchResultArea, Search::BtSearchResultArea::showAnalysis(), Search::BtSearchOptionsArea::sigStartSearch(), and startSearch().
~CSearchDialog()
Search::CSearchDialog::~CSearchDialog () override
Definition at line 101 of file csearchdialog.cpp.
References btConfig(), and BtConfigCore::setValue().
Member Function Documentation
reset()
void Search::CSearchDialog::reset (BtConstModuleList modules, QString const & searchText)
Resets the parts to the default.
Definition at line 211 of file csearchdialog.cpp.
References Search::BtSearchOptionsArea::chooseModules(), m_analyseButton, m_searchOptionsArea, m_searchResultArea, Search::BtSearchOptionsArea::reset(), Search::BtSearchResultArea::reset(), Search::BtSearchOptionsArea::setModules(), Search::BtSearchOptionsArea::setSearchText(), and startSearch().
startSearch
void Search::CSearchDialog::startSearch () private slot
Starts the search with the set modules and the set search text.
Warning
indexing is some kind of internal optimization, so we leave modules const, but unconst them here only
Definition at line 104 of file csearchdialog.cpp.
References Search::BtSearchOptionsArea::addToHistory(), BtModuleIndexDialog::indexAllModules(), m_analyseButton, m_searchOptionsArea, m_searchResultArea, Search::BtSearchOptionsArea::modules(), CSwordModuleSearch::prepareSearchText(), Search::BtSearchResultArea::reset(), CSwordModuleSearch::search(), Search::BtSearchOptionsArea::searchScope(), Search::BtSearchOptionsArea::searchText(), Search::BtSearchOptionsArea::searchType(), Search::BtSearchResultArea::setSearchResult(), message::showQuestion(), and message::showWarning().
Referenced by CSearchDialog(), and reset().
Member Data Documentation
m_analyseButton
QPushButton* Search::CSearchDialog::m_analyseButton private
Definition at line 50 of file csearchdialog.h.
Referenced by CSearchDialog(), reset(), and startSearch().
m_closeButton
QPushButton* Search::CSearchDialog::m_closeButton private
Definition at line 52 of file csearchdialog.h.
Referenced by CSearchDialog().
m_manageIndexes
QPushButton* Search::CSearchDialog::m_manageIndexes private
Definition at line 51 of file csearchdialog.h.
Referenced by CSearchDialog().
m_searchOptionsArea
BtSearchOptionsArea* Search::CSearchDialog::m_searchOptionsArea private
Definition at line 54 of file csearchdialog.h.
Referenced by CSearchDialog(), reset(), and startSearch().
m_searchResultArea
BtSearchResultArea* Search::CSearchDialog::m_searchResultArea private
Definition at line 53 of file csearchdialog.h.
Referenced by CSearchDialog(), reset(), and startSearch().
The documentation for this class was generated from the following files:
csearchdialog.h
csearchdialog.cpp