BibleTime: BtQmlInterface Class Reference
BtQmlInterface Class Reference
#include <btqmlinterface.h>
Signals
void activeLinkChanged ()
void backgroundColorChanged ()
void backgroundHighlightColorChanged ()
void backgroundHighlightColorIndexChanged ()
void contextMenu (int x, int y, int moduleNum)
void contextMenuColumnChanged ()
void contextMenuIndexChanged ()
void currentModelIndexChanged ()
void dragOccuring (const QString &moduleName, const QString &keyName)
void fontChanged ()
void foregroundColorChanged ()
void highlightWordsChanged ()
void newBibleReference (const QString &reference)
void numModulesChanged ()
void pageDownChanged ()
void pageUpChanged ()
void pixelsPerMMChanged ()
void positionItemOnScreen (int index)
void referenceChange ()
void textChanged ()
void textModelChanged ()
void updateReference (const QString &reference)
Public Member Functions
BtQmlInterface (QObject *parent=nullptr)
Q_INVOKABLE void cancelMagTimer ()
void changeColorTheme ()
Q_INVOKABLE void changeReference (int i)
Q_INVOKABLE void clearSelectedText ()
void copyRange (int index1, int index2) const
void copyVerseRange (const QString &ref1, const QString &ref2, const CSwordModuleInfo *module) const
int countHighlightsInItem (int index)
Q_INVOKABLE void dragHandler (int index, const QString &link)
void findText (const QString &text, bool caseSensitive, bool backward)
QString getActiveLink () const
QColor getBackgroundColor () const
QColor getBackgroundHighlightColor () const
int getBackgroundHighlightColorIndex () const
QString getBibleUrlFromLink (const QString &url)
int getContextMenuColumn () const
int getContextMenuIndex () const
int getCurrentModelIndex () const
QFont getFont0 () const
QFont getFont1 () const
QFont getFont2 () const
QFont getFont3 () const
QFont getFont4 () const
QFont getFont5 () const
QFont getFont6 () const
QFont getFont7 () const
QFont getFont8 () const
QFont getFont9 () const
QColor getForegroundColor () const
QString getHighlightWords () const
CSwordKey * getKey () const
QString getLemmaFromLink (const QString &url)
Q_INVOKABLE QStringList getModuleNames () const
CSwordKey * getMouseClickedKey () const
void getNextMatchingItem (int index)
int getNumModules () const
bool getPageDown () const
bool getPageUp () const
double getPixelsPerMM () const
void getPreviousMatchingItem (int index)
Q_INVOKABLE QString getRawText (int row, int column)
QString getSelectedText ()
QVariant getTextModel ()
Q_INVOKABLE bool hasSelectedText ()
Q_INVOKABLE int indexToVerse (int index)
bool isBibleOrCommentary ()
Q_INVOKABLE bool moduleIsWritable (int column)
Q_INVOKABLE void openContextMenu (int x, int y, int width)
Q_INVOKABLE void openEditor (int row, int column)
void pageDown ()
void pageUp ()
void referenceChoosen ()
Q_INVOKABLE void referenceChosen ()
Q_INVOKABLE void saveSelectedText (int index, const QString &text)
void scrollToSwordKey (CSwordKey *key)
void setActiveLink (const QString &link)
void setContextMenuColumn (int index)
void setContextMenuIndex (int index)
void setFilterOptions (FilterOptions filterOptions)
void setHighlightWords (const QString &words, bool caseSensitivy)
void setKey (CSwordKey *key)
Q_INVOKABLE void setKeyFromLink (const QString &link)
Q_INVOKABLE void setMagReferenceByUrl (const QString &url)
void setModules (const QStringList &modules)
Q_INVOKABLE void setRawText (int row, int column, const QString &text)
void settingsChanged ()
Q_INVOKABLE bool shiftKeyDown ()
BtModuleTextModel * textModel ()
const BtModuleTextModel * textModel () const
~BtQmlInterface ()
Properties
QString activeLink
QColor backgroundColor
QColor backgroundHighlightColor
int backgroundHighlightColorIndex
int contextMenuColumn
int contextMenuIndex
int currentModelIndex
QFont font0
QFont font1
QFont font2
QFont font3
QFont font4
QFont font5
QFont font6
QFont font7
QFont font8
QFont font9
QColor foregroundColor
QString highlightWords
int numModules
bool pageDown
bool pageUp
double pixelsPerMM
QVariant textModel
Private Types
enum Format { HTML, Text }
Private Slots
void slotSetHighlightWords ()
Private Member Functions
void configModuleByType (const QString &type, const QStringList &availableModuleNames)
bool copyKey (CSwordKey const *const key, Format const format, bool const addText) const
QString decodeLemma (const QString &value)
QString decodeMorph (const QString &value)
QFont font (int column) const
void getFontsFromSettings ()
QString getReferenceFromUrl (const QString &url)
const CSwordModuleInfo * module () const
QString stripHtml (const QString &html)
Static Private Member Functions
static std::unique_ptr< Rendering::CTextRendering > newRenderer (Format const format, bool const addText)
Private Attributes
QString m_activeLink
int m_backgroundHighlightColorIndex
bool m_caseSensitive
int m_contextMenuColumn
int m_contextMenuIndex
std::optional< FindState > m_findState
bool m_firstHref
QList< QFont > m_fonts
QString m_highlightWords
QTimer * m_linkTimer
QStringList m_moduleNames
BtModuleTextModel * m_moduleTextModel
QMap< int, QString > m_selectedText
CSwordKey * m_swordKey
BtTextFilter m_textFilter
QString m_timeoutUrl
QTimer m_timer
Detailed Description
/brief This class provides communications between QML and c++.
It is instantiated by usage within the QML files. It provides properties and functions written in c++ and usable by QML.
Definition at line 40 of file btqmlinterface.h.
Member Enumeration Documentation
Format
enum BtQmlInterface::Format private
Enumerator
HTML
Text
Definition at line 44 of file btqmlinterface.h.
Constructor & Destructor Documentation
BtQmlInterface()
BtQmlInterface::BtQmlInterface (QObject * parent = nullptr)
Definition at line 39 of file btqmlinterface.cpp.
References BT_CONNECT, Rendering::detectInfo(), getReferenceFromUrl(), BibleTime::infoDisplay(), BibleTime::instance(), m_linkTimer, m_moduleTextModel, m_textFilter, m_timeoutUrl, InfoDisplay::CInfoDisplay::setInfo(), BtTextFilter::setShowReferences(), and BtModuleTextModel::setTextFilter().
~BtQmlInterface()
BtQmlInterface::~BtQmlInterface ()
Definition at line 62 of file btqmlinterface.cpp.
Member Function Documentation
activeLinkChanged
void BtQmlInterface::activeLinkChanged () signal
Referenced by setActiveLink().
backgroundColorChanged
void BtQmlInterface::backgroundColorChanged () signal
Referenced by changeColorTheme().
backgroundHighlightColorChanged
void BtQmlInterface::backgroundHighlightColorChanged () signal
Referenced by changeColorTheme().
backgroundHighlightColorIndexChanged
void BtQmlInterface::backgroundHighlightColorIndexChanged () signal
Referenced by scrollToSwordKey().
cancelMagTimer()
void BtQmlInterface::cancelMagTimer ()
Definition at line 295 of file btqmlinterface.cpp.
References m_linkTimer.
Referenced by BtQuickWidget::event().
changeColorTheme()
void BtQmlInterface::changeColorTheme ()
Definition at line 475 of file btqmlinterface.cpp.
References backgroundColorChanged(), backgroundHighlightColorChanged(), and foregroundColorChanged().
Referenced by CDisplayWindow::setDisplayWidget(), and settingsChanged().
changeReference()
void BtQmlInterface::changeReference (int i)
Definition at line 381 of file btqmlinterface.cpp.
References BtModuleTextModel::indexToKeyName(), m_moduleTextModel, and updateReference().
clearSelectedText()
void BtQmlInterface::clearSelectedText ()
Definition at line 666 of file btqmlinterface.cpp.
References m_selectedText.
configModuleByType()
void BtQmlInterface::configModuleByType (const QString & type, const QStringList & availableModuleNames) private
Definition at line 466 of file btqmlinterface.cpp.
References btConfig(), CSwordBackend::findModuleByName(), BtConfig::getDefaultSwordModuleByType(), CSwordBackend::instance(), module(), and BtConfig::setDefaultSwordModuleByType().
contextMenu
void BtQmlInterface::contextMenu (int x, int y, int moduleNum) signal
Referenced by openContextMenu().
contextMenuColumnChanged
void BtQmlInterface::contextMenuColumnChanged () signal
Referenced by setContextMenuColumn().
contextMenuIndexChanged
void BtQmlInterface::contextMenuIndexChanged () signal
Referenced by setContextMenuIndex().
copyKey()
bool BtQmlInterface::copyKey (CSwordKey const *const key, Format const format, bool const addText) const private
Definition at line 505 of file btqmlinterface.cpp.
References CSwordVerseKey::isBoundSet(), CSwordKey::key(), CSwordVerseKey::lowerBound(), CSwordKey::module(), newRenderer(), and CSwordVerseKey::upperBound().
Referenced by copyVerseRange().
copyRange()
void BtQmlInterface::copyRange (int index1, int index2) const
Definition at line 481 of file btqmlinterface.cpp.
References CSwordKey::copy(), BtModuleTextModel::indexToKeyName(), m_moduleTextModel, and m_swordKey.
copyVerseRange()
void BtQmlInterface::copyVerseRange (const QString & ref1, const QString & ref2, const CSwordModuleInfo * module) const
Definition at line 494 of file btqmlinterface.cpp.
References copyKey(), module(), CSwordVerseKey::setKey(), CSwordVerseKey::setLowerBound(), CSwordVerseKey::setUpperBound(), and Text.
countHighlightsInItem()
int BtQmlInterface::countHighlightsInItem (int index)
Definition at line 600 of file btqmlinterface.cpp.
References BtModuleTextModel::data(), m_moduleTextModel, and ModuleEntry::Text1Role.
Referenced by getNextMatchingItem(), and getPreviousMatchingItem().
currentModelIndexChanged
void BtQmlInterface::currentModelIndexChanged () signal
Referenced by referenceChosen(), and scrollToSwordKey().
decodeLemma()
QString BtQmlInterface::decodeLemma (const QString & value) private
decodeMorph()
QString BtQmlInterface::decodeMorph (const QString & value) private
dragHandler()
void BtQmlInterface::dragHandler (int index, const QString & link)
Definition at line 386 of file btqmlinterface.cpp.
References activeLink, dragOccuring(), BtModuleTextModel::indexToKeyName(), m_moduleNames, and m_moduleTextModel.
dragOccuring
void BtQmlInterface::dragOccuring (const QString & moduleName, const QString & keyName) signal
Referenced by BtModelViewReadDisplay::BtModelViewReadDisplay(), and dragHandler().
findText()
void BtQmlInterface::findText (const QString & text, bool caseSensitive, bool backward)
Definition at line 583 of file btqmlinterface.cpp.
References getCurrentModelIndex(), getNextMatchingItem(), getPreviousMatchingItem(), highlightWordsChanged(), m_findState, m_moduleTextModel, positionItemOnScreen(), and BtModuleTextModel::setFindState().
Referenced by BtModelViewReadDisplay::findText().
font()
QFont BtQmlInterface::font (int column) const private
Definition at line 420 of file btqmlinterface.cpp.
References m_fonts.
Referenced by getFont0(), getFont1(), getFont2(), getFont3(), getFont4(), getFont5(), getFont6(), getFont7(), getFont8(), getFont9(), and getFontsFromSettings().
fontChanged
void BtQmlInterface::fontChanged () signal
Referenced by getFontsFromSettings().
foregroundColorChanged
void BtQmlInterface::foregroundColorChanged () signal
Referenced by changeColorTheme().
getActiveLink()
QString BtQmlInterface::getActiveLink () const
Definition at line 113 of file btqmlinterface.cpp.
References m_activeLink.
Referenced by BtModelViewReadDisplay::contextMenu().
getBackgroundColor()
QColor BtQmlInterface::getBackgroundColor () const
Definition at line 122 of file btqmlinterface.cpp.
References ColorManager::getBackgroundColor(), and ColorManager::instance().
getBackgroundHighlightColor()
QColor BtQmlInterface::getBackgroundHighlightColor () const
Definition at line 126 of file btqmlinterface.cpp.
References ColorManager::getBackgroundHighlightColor(), and ColorManager::instance().
getBackgroundHighlightColorIndex()
int BtQmlInterface::getBackgroundHighlightColorIndex () const
Definition at line 130 of file btqmlinterface.cpp.
References m_backgroundHighlightColorIndex.
getBibleUrlFromLink()
QString BtQmlInterface::getBibleUrlFromLink (const QString & url)
Definition at line 241 of file btqmlinterface.cpp.
Referenced by BtModelViewReadDisplay::contextMenu().
getContextMenuColumn()
int BtQmlInterface::getContextMenuColumn () const
Definition at line 104 of file btqmlinterface.cpp.
References m_contextMenuColumn.
getContextMenuIndex()
int BtQmlInterface::getContextMenuIndex () const
Definition at line 95 of file btqmlinterface.cpp.
References m_contextMenuIndex.
getCurrentModelIndex()
int BtQmlInterface::getCurrentModelIndex () const
Todo:
Check range!
Definition at line 138 of file btqmlinterface.cpp.
References CSwordLexiconModuleInfo::entries(), CSwordKey::key(), m_moduleTextModel, m_swordKey, CSwordKey::module(), module(), moduleIsBibleOrCommentary(), moduleIsBook(), moduleIsLexicon(), CSwordTreeKey::offset(), CSwordTreeKey::positionToRoot(), CSwordTreeKey::setKey(), CSwordBookModuleInfo::tree(), and BtModuleTextModel::verseKeyToIndex().
Referenced by findText().
getFont0()
QFont BtQmlInterface::getFont0 () const
Definition at line 426 of file btqmlinterface.cpp.
References font().
getFont1()
QFont BtQmlInterface::getFont1 () const
Definition at line 427 of file btqmlinterface.cpp.
References font().
getFont2()
QFont BtQmlInterface::getFont2 () const
Definition at line 428 of file btqmlinterface.cpp.
References font().
getFont3()
QFont BtQmlInterface::getFont3 () const
Definition at line 429 of file btqmlinterface.cpp.
References font().
getFont4()
QFont BtQmlInterface::getFont4 () const
Definition at line 430 of file btqmlinterface.cpp.
References font().
getFont5()
QFont BtQmlInterface::getFont5 () const
Definition at line 431 of file btqmlinterface.cpp.
References font().
getFont6()
QFont BtQmlInterface::getFont6 () const
Definition at line 432 of file btqmlinterface.cpp.
References font().
getFont7()
QFont BtQmlInterface::getFont7 () const
Definition at line 433 of file btqmlinterface.cpp.
References font().
getFont8()
QFont BtQmlInterface::getFont8 () const
Definition at line 434 of file btqmlinterface.cpp.
References font().
getFont9()
QFont BtQmlInterface::getFont9 () const
Definition at line 435 of file btqmlinterface.cpp.
References font().
getFontsFromSettings()
void BtQmlInterface::getFontsFromSettings () private
Definition at line 320 of file btqmlinterface.cpp.
References btConfig(), CSwordBackend::findModuleByName(), font(), fontChanged(), BtConfig::getDefaultFont(), BtConfig::getFontForLanguage(), CSwordBackend::instance(), CSwordModuleInfo::language(), m_fonts, and m_moduleNames.
Referenced by setModules(), and settingsChanged().
getForegroundColor()
QColor BtQmlInterface::getForegroundColor () const
Definition at line 134 of file btqmlinterface.cpp.
References ColorManager::getForegroundColor(), and ColorManager::instance().
getHighlightWords()
QString BtQmlInterface::getHighlightWords () const
Definition at line 564 of file btqmlinterface.cpp.
References m_highlightWords.
getKey()
CSwordKey * BtQmlInterface::getKey () const
Definition at line 412 of file btqmlinterface.cpp.
References m_swordKey.
getLemmaFromLink()
QString BtQmlInterface::getLemmaFromLink (const QString & url)
Definition at line 229 of file btqmlinterface.cpp.
Referenced by BtModelViewReadDisplay::contextMenu().
getModuleNames()
QStringList BtQmlInterface::getModuleNames () const
Definition at line 165 of file btqmlinterface.cpp.
References m_moduleNames.
getMouseClickedKey()
CSwordKey * BtQmlInterface::getMouseClickedKey () const
Definition at line 416 of file btqmlinterface.cpp.
References BtModuleTextModel::indexToKey(), m_contextMenuColumn, m_contextMenuIndex, and m_moduleTextModel.
Referenced by BtQuickWidget::getMouseClickedKey().
getNextMatchingItem()
void BtQmlInterface::getNextMatchingItem (int index)
Definition at line 607 of file btqmlinterface.cpp.
References countHighlightsInItem(), m_findState, m_moduleTextModel, and BtModuleTextModel::rowCount().
Referenced by findText().
getNumModules()
int BtQmlInterface::getNumModules () const
Definition at line 169 of file btqmlinterface.cpp.
References m_moduleNames.
getPageDown()
bool BtQmlInterface::getPageDown () const
Definition at line 173 of file btqmlinterface.cpp.
getPageUp()
bool BtQmlInterface::getPageUp () const
Definition at line 177 of file btqmlinterface.cpp.
getPixelsPerMM()
double BtQmlInterface::getPixelsPerMM () const
Definition at line 181 of file btqmlinterface.cpp.
getPreviousMatchingItem()
void BtQmlInterface::getPreviousMatchingItem (int index)
Definition at line 631 of file btqmlinterface.cpp.
References countHighlightsInItem(), and m_findState.
Referenced by findText().
getRawText()
QString BtQmlInterface::getRawText (int row, int column)
Definition at line 197 of file btqmlinterface.cpp.
References BT_ASSERT, CSwordBackend::findModuleByName(), BtModuleTextModel::indexToVerseKey(), CSwordBackend::instance(), CSwordVerseKey::key(), m_moduleNames, m_moduleTextModel, module(), CSwordKey::rawText(), CSwordVerseKey::setKey(), and stripHtml().
Referenced by openEditor().
getReferenceFromUrl()
QString BtQmlInterface::getReferenceFromUrl (const QString & url) private
Definition at line 253 of file btqmlinterface.cpp.
Referenced by BtQmlInterface().
getSelectedText()
QString BtQmlInterface::getSelectedText ()
Definition at line 437 of file btqmlinterface.cpp.
References m_selectedText.
getTextModel()
QVariant BtQmlInterface::getTextModel ()
Definition at line 445 of file btqmlinterface.cpp.
References m_moduleTextModel.
hasSelectedText()
bool BtQmlInterface::hasSelectedText ()
Definition at line 662 of file btqmlinterface.cpp.
References m_selectedText.
Referenced by CDisplayWindow::hasSelectedText().
highlightWordsChanged
void BtQmlInterface::highlightWordsChanged () signal
Referenced by findText(), and slotSetHighlightWords().
indexToVerse()
int BtQmlInterface::indexToVerse (int index)
Definition at line 217 of file btqmlinterface.cpp.
References BtModuleTextModel::indexToVerse(), and m_moduleTextModel.
isBibleOrCommentary()
bool BtQmlInterface::isBibleOrCommentary ()
Definition at line 87 of file btqmlinterface.cpp.
References module(), and moduleIsBibleOrCommentary().
module()
const CSwordModuleInfo * BtQmlInterface::module () const private
Definition at line 405 of file btqmlinterface.cpp.
References m_swordKey, and CSwordKey::module().
Referenced by configModuleByType(), copyVerseRange(), getCurrentModelIndex(), getRawText(), isBibleOrCommentary(), and moduleIsWritable().
moduleIsWritable()
bool BtQmlInterface::moduleIsWritable (int column)
Definition at line 458 of file btqmlinterface.cpp.
References CSwordBackend::findModuleByName(), CSwordBackend::instance(), CSwordModuleInfo::isWritable(), m_moduleNames, and module().
newBibleReference
void BtQmlInterface::newBibleReference (const QString & reference) signal
Referenced by BtQmlScrollView::BtQmlScrollView(), and setKeyFromLink().
newRenderer()
std::unique_ptr< Rendering::CTextRendering > BtQmlInterface::newRenderer (Format const format, bool const addText) static private
Definition at line 532 of file btqmlinterface.cpp.
References BT_ASSERT, FilterOptions::footnotes, FilterOptions::greekAccents, FilterOptions::headings, FilterOptions::hebrewCantillation, FilterOptions::hebrewPoints, HTML, FilterOptions::lemmas, DisplayOptions::lineBreaks, FilterOptions::morphSegmentation, FilterOptions::morphTags, FilterOptions::redLetterWords, FilterOptions::scriptureReferences, FilterOptions::strongNumbers, Text, FilterOptions::textualVariants, and DisplayOptions::verseNumbers.
Referenced by copyKey().
numModulesChanged
void BtQmlInterface::numModulesChanged () signal
Referenced by setModules().
openContextMenu()
void BtQmlInterface::openContextMenu (int x, int y, int width)
Definition at line 221 of file btqmlinterface.cpp.
References contextMenu(), and m_moduleNames.
openEditor()
void BtQmlInterface::openEditor (int row, int column)
Definition at line 208 of file btqmlinterface.cpp.
References getRawText(), BtModuleTextModel::indexToKeyName(), m_fonts, m_moduleTextModel, BtEditTextWizard::setFont(), setRawText(), BtEditTextWizard::setText(), BtEditTextWizard::setTitle(), and BtEditTextWizard::text().
pageDown()
void BtQmlInterface::pageDown ()
pageDownChanged
void BtQmlInterface::pageDownChanged () signal
pageUp()
void BtQmlInterface::pageUp ()
pageUpChanged
void BtQmlInterface::pageUpChanged () signal
pixelsPerMMChanged
void BtQmlInterface::pixelsPerMMChanged () signal
positionItemOnScreen
void BtQmlInterface::positionItemOnScreen (int index) signal
Referenced by findText().
referenceChange
void BtQmlInterface::referenceChange () signal
Referenced by referenceChosen().
referenceChoosen()
void BtQmlInterface::referenceChoosen ()
referenceChosen()
void BtQmlInterface::referenceChosen ()
Definition at line 376 of file btqmlinterface.cpp.
References currentModelIndexChanged(), and referenceChange().
Referenced by BtQmlScrollView::referenceChoosen().
saveSelectedText()
void BtQmlInterface::saveSelectedText (int index, const QString & text)
Definition at line 670 of file btqmlinterface.cpp.
References m_selectedText.
scrollToSwordKey()
void BtQmlInterface::scrollToSwordKey (CSwordKey * key)
Definition at line 358 of file btqmlinterface.cpp.
References backgroundHighlightColorIndexChanged(), currentModelIndexChanged(), BtModuleTextModel::getFirstEntryIndex(), BtModuleTextModel::keyToIndex(), m_backgroundHighlightColorIndex, m_moduleTextModel, and m_swordKey.
Referenced by BtQmlScrollView::scrollToSwordKey().
setActiveLink()
void BtQmlInterface::setActiveLink (const QString & link)
Definition at line 117 of file btqmlinterface.cpp.
References activeLinkChanged(), and m_activeLink.
setContextMenuColumn()
void BtQmlInterface::setContextMenuColumn (int index)
Definition at line 108 of file btqmlinterface.cpp.
References contextMenuColumnChanged(), and m_contextMenuColumn.
setContextMenuIndex()
void BtQmlInterface::setContextMenuIndex (int index)
Definition at line 99 of file btqmlinterface.cpp.
References contextMenuIndexChanged(), and m_contextMenuIndex.
setFilterOptions()
void BtQmlInterface::setFilterOptions (FilterOptions filterOptions)
Definition at line 91 of file btqmlinterface.cpp.
References m_moduleTextModel, and BtModuleTextModel::setFilterOptions().
Referenced by BtQmlScrollView::setFilterOptions().
setHighlightWords()
void BtQmlInterface::setHighlightWords (const QString & words, bool caseSensitivy)
Definition at line 568 of file btqmlinterface.cpp.
References m_caseSensitive, m_highlightWords, and slotSetHighlightWords().
Referenced by BtQmlScrollView::findTextHighlight(), and BtModelViewReadDisplay::highlightText().
setKey()
void BtQmlInterface::setKey (CSwordKey * key)
Sets the new sword key.
Definition at line 342 of file btqmlinterface.cpp.
References BT_ASSERT, and m_swordKey.
Referenced by BtQmlScrollView::setKey().
setKeyFromLink()
void BtQmlInterface::setKeyFromLink (const QString & link)
Definition at line 347 of file btqmlinterface.cpp.
References newBibleReference().
setMagReferenceByUrl()
void BtQmlInterface::setMagReferenceByUrl (const QString & url)
Definition at line 299 of file btqmlinterface.cpp.
References m_linkTimer, and m_timeoutUrl.
setModules()
void BtQmlInterface::setModules (const QStringList & modules)
Definition at line 369 of file btqmlinterface.cpp.
References getFontsFromSettings(), m_moduleNames, m_moduleTextModel, numModulesChanged(), and BtModuleTextModel::setModules().
Referenced by BtQmlScrollView::setModules(), and BtModelViewReadDisplay::setModules().
setRawText()
void BtQmlInterface::setRawText (int row, int column, const QString & text)
Definition at line 289 of file btqmlinterface.cpp.
References m_moduleTextModel, BtModuleTextModel::setData(), and ModuleEntry::Text0Role.
Referenced by openEditor().
settingsChanged()
void BtQmlInterface::settingsChanged ()
Definition at line 306 of file btqmlinterface.cpp.
References changeColorTheme(), getFontsFromSettings(), and textChanged().
Referenced by BtQmlScrollView::settingsChanged().
shiftKeyDown()
bool BtQmlInterface::shiftKeyDown ()
Definition at line 674 of file btqmlinterface.cpp.
slotSetHighlightWords
void BtQmlInterface::slotSetHighlightWords () private slot
Definition at line 574 of file btqmlinterface.cpp.
References highlightWordsChanged(), m_caseSensitive, m_findState, m_highlightWords, m_moduleTextModel, BtModuleTextModel::setFindState(), and BtModuleTextModel::setHighlightWords().
Referenced by setHighlightWords().
stripHtml()
QString BtQmlInterface::stripHtml (const QString & html) private
Definition at line 187 of file btqmlinterface.cpp.
Referenced by getRawText().
textChanged
void BtQmlInterface::textChanged () signal
Referenced by settingsChanged().
textModel() [1/2]
BtModuleTextModel* BtQmlInterface::textModel ()
textModel() [2/2]
const BtModuleTextModel* BtQmlInterface::textModel () const
textModelChanged
void BtQmlInterface::textModelChanged () signal
updateReference
void BtQmlInterface::updateReference (const QString & reference) signal
Referenced by BtModelViewReadDisplay::BtModelViewReadDisplay(), and changeReference().
Member Data Documentation
m_activeLink
QString BtQmlInterface::m_activeLink private
Definition at line 202 of file btqmlinterface.h.
Referenced by getActiveLink(), and setActiveLink().
m_backgroundHighlightColorIndex
int BtQmlInterface::m_backgroundHighlightColorIndex private
Definition at line 194 of file btqmlinterface.h.
Referenced by getBackgroundHighlightColorIndex(), and scrollToSwordKey().
m_caseSensitive
bool BtQmlInterface::m_caseSensitive private
Definition at line 195 of file btqmlinterface.h.
Referenced by setHighlightWords(), and slotSetHighlightWords().
m_contextMenuColumn
int BtQmlInterface::m_contextMenuColumn private
Definition at line 201 of file btqmlinterface.h.
Referenced by getContextMenuColumn(), getMouseClickedKey(), and setContextMenuColumn().
m_contextMenuIndex
int BtQmlInterface::m_contextMenuIndex private
Definition at line 200 of file btqmlinterface.h.
Referenced by getContextMenuIndex(), getMouseClickedKey(), and setContextMenuIndex().
m_findState
std::optional<FindState> BtQmlInterface::m_findState private
Definition at line 203 of file btqmlinterface.h.
Referenced by findText(), getNextMatchingItem(), getPreviousMatchingItem(), and slotSetHighlightWords().
m_firstHref
bool BtQmlInterface::m_firstHref private
Definition at line 188 of file btqmlinterface.h.
m_fonts
QList<QFont> BtQmlInterface::m_fonts private
Definition at line 193 of file btqmlinterface.h.
Referenced by font(), getFontsFromSettings(), and openEditor().
m_highlightWords
QString BtQmlInterface::m_highlightWords private
Definition at line 196 of file btqmlinterface.h.
Referenced by getHighlightWords(), setHighlightWords(), and slotSetHighlightWords().
m_linkTimer
QTimer* BtQmlInterface::m_linkTimer private
Definition at line 189 of file btqmlinterface.h.
Referenced by BtQmlInterface(), cancelMagTimer(), and setMagReferenceByUrl().
m_moduleNames
QStringList BtQmlInterface::m_moduleNames private
Definition at line 197 of file btqmlinterface.h.
Referenced by dragHandler(), getFontsFromSettings(), getModuleNames(), getNumModules(), getRawText(), moduleIsWritable(), openContextMenu(), and setModules().
m_moduleTextModel
BtModuleTextModel* BtQmlInterface::m_moduleTextModel private
Definition at line 190 of file btqmlinterface.h.
Referenced by BtQmlInterface(), changeReference(), copyRange(), countHighlightsInItem(), dragHandler(), findText(), getCurrentModelIndex(), getMouseClickedKey(), getNextMatchingItem(), getRawText(), getTextModel(), indexToVerse(), openEditor(), scrollToSwordKey(), setFilterOptions(), setModules(), setRawText(), and slotSetHighlightWords().
m_selectedText
QMap<int, QString> BtQmlInterface::m_selectedText private
Definition at line 205 of file btqmlinterface.h.
Referenced by clearSelectedText(), getSelectedText(), hasSelectedText(), and saveSelectedText().
m_swordKey
CSwordKey* BtQmlInterface::m_swordKey private
Definition at line 191 of file btqmlinterface.h.
Referenced by copyRange(), getCurrentModelIndex(), getKey(), module(), scrollToSwordKey(), and setKey().
m_textFilter
BtTextFilter BtQmlInterface::m_textFilter private
Definition at line 198 of file btqmlinterface.h.
Referenced by BtQmlInterface().
m_timeoutUrl
QString BtQmlInterface::m_timeoutUrl private
Definition at line 199 of file btqmlinterface.h.
Referenced by BtQmlInterface(), and setMagReferenceByUrl().
m_timer
QTimer BtQmlInterface::m_timer private
Definition at line 204 of file btqmlinterface.h.
Property Documentation
activeLink
QString BtQmlInterface::activeLink read write
Definition at line 48 of file btqmlinterface.h.
Referenced by dragHandler().
backgroundColor
QColor BtQmlInterface::backgroundColor read
Definition at line 49 of file btqmlinterface.h.
backgroundHighlightColor
QColor BtQmlInterface::backgroundHighlightColor read
Definition at line 50 of file btqmlinterface.h.
backgroundHighlightColorIndex
int BtQmlInterface::backgroundHighlightColorIndex read
Definition at line 51 of file btqmlinterface.h.
contextMenuColumn
int BtQmlInterface::contextMenuColumn read write
Definition at line 53 of file btqmlinterface.h.
contextMenuIndex
int BtQmlInterface::contextMenuIndex read write
Definition at line 52 of file btqmlinterface.h.
currentModelIndex
int BtQmlInterface::currentModelIndex read
Definition at line 54 of file btqmlinterface.h.
font0
QFont BtQmlInterface::font0 read
Definition at line 55 of file btqmlinterface.h.
font1
QFont BtQmlInterface::font1 read
Definition at line 56 of file btqmlinterface.h.
font2
QFont BtQmlInterface::font2 read
Definition at line 57 of file btqmlinterface.h.
font3
QFont BtQmlInterface::font3 read
Definition at line 58 of file btqmlinterface.h.
font4
QFont BtQmlInterface::font4 read
Definition at line 59 of file btqmlinterface.h.
font5
QFont BtQmlInterface::font5 read
Definition at line 60 of file btqmlinterface.h.
font6
QFont BtQmlInterface::font6 read
Definition at line 61 of file btqmlinterface.h.
font7
QFont BtQmlInterface::font7 read
Definition at line 62 of file btqmlinterface.h.
font8
QFont BtQmlInterface::font8 read
Definition at line 63 of file btqmlinterface.h.
font9
QFont BtQmlInterface::font9 read
Definition at line 64 of file btqmlinterface.h.
foregroundColor
QColor BtQmlInterface::foregroundColor read
Definition at line 65 of file btqmlinterface.h.
highlightWords
QString BtQmlInterface::highlightWords read
Definition at line 66 of file btqmlinterface.h.
numModules
int BtQmlInterface::numModules read
Definition at line 67 of file btqmlinterface.h.
pageDown
void BtQmlInterface::pageDown read
Definition at line 68 of file btqmlinterface.h.
Referenced by BtQmlScrollView::pageDown().
pageUp
void BtQmlInterface::pageUp read
Definition at line 69 of file btqmlinterface.h.
Referenced by BtQmlScrollView::pageUp().
pixelsPerMM
double BtQmlInterface::pixelsPerMM read
Definition at line 70 of file btqmlinterface.h.
textModel
const BtModuleTextModel * BtQmlInterface::textModel read
Definition at line 71 of file btqmlinterface.h.
Referenced by BtModelViewReadDisplay::reloadModules(), and BtModelViewReadDisplay::setDisplayOptions().
The documentation for this class was generated from the following files:
btqmlinterface.h
btqmlinterface.cpp