BibleTime: BtDisplaySettingsButton Class Reference
BtDisplaySettingsButton Class Reference
#include <btdisplaysettingsbutton.h>
Public Slots
void setDisplayOptions (DisplayOptions const &displaySettings)
void setFilterOptions (FilterOptions const &moduleSettings)
void setModules (const BtConstModuleList &modules)
Signals
void sigChanged ()
void sigDisplayOptionsChanged (DisplayOptions displayOptions)
void sigFilterOptionsChanged (FilterOptions filterOptions)
void sigModulesChanged (const BtConstModuleList &modules)
Public Member Functions
BtDisplaySettingsButton (QWidget *parent=nullptr)
void setDisplayOptionsNoRepopulate (DisplayOptions const &displaySettings)
void setFilterOptionsNoRepopulate (FilterOptions const &moduleSettings)
Protected Member Functions
void addMenuEntry (QAction *action, bool checked)
void initMenu ()
bool isOptionAvailable (CSwordModuleInfo::FilterOption const &option)
void repopulateMenu ()
void retranslateToolTip ()
void retranslateUi ()
Private Attributes
DisplayOptions m_displayOptions
FilterOptions m_filterOptions
QAction * m_footnotesAction
QAction * m_greekAccentsAction
QAction * m_headingsAction
QAction * m_hebrewCantillationAction
QAction * m_hebrewPointsAction
BtConstModuleList m_modules
QAction * m_morphSegmentationAction
QMenu * m_popup
QAction * m_redWordsAction
QAction * m_scriptureReferencesAction
QAction * m_variantAction
QAction * m_verseNumbersAction
Detailed Description
This class manages the display options of the selected modules.
Author
The BibleTime team
Definition at line 31 of file btdisplaysettingsbutton.h.
Constructor & Destructor Documentation
BtDisplaySettingsButton()
BtDisplaySettingsButton::BtDisplaySettingsButton (QWidget * parent = nullptr)
Definition at line 27 of file btdisplaysettingsbutton.cpp.
References BT_ASSERT, BT_CONNECT, FilterOptions::footnotes, FilterOptions::greekAccents, FilterOptions::headings, FilterOptions::hebrewCantillation, FilterOptions::hebrewPoints, initMenu(), m_displayOptions, m_filterOptions, m_footnotesAction, m_greekAccentsAction, m_headingsAction, m_hebrewCantillationAction, m_hebrewPointsAction, m_morphSegmentationAction, m_popup, m_redWordsAction, m_scriptureReferencesAction, m_variantAction, m_verseNumbersAction, FilterOptions::morphSegmentation, FilterOptions::redLetterWords, retranslateUi(), FilterOptions::scriptureReferences, sigChanged(), sigDisplayOptionsChanged(), sigFilterOptionsChanged(), FilterOptions::textualVariants, and DisplayOptions::verseNumbers.
Member Function Documentation
addMenuEntry()
void BtDisplaySettingsButton::addMenuEntry (QAction * action, bool checked) protected
Adds an entry to m_popup.
Definition at line 233 of file btdisplaysettingsbutton.cpp.
References m_popup.
Referenced by repopulateMenu().
initMenu()
void BtDisplaySettingsButton::initMenu () protected
Definition at line 111 of file btdisplaysettingsbutton.cpp.
References m_footnotesAction, m_greekAccentsAction, m_headingsAction, m_hebrewCantillationAction, m_hebrewPointsAction, m_morphSegmentationAction, m_popup, m_redWordsAction, m_scriptureReferencesAction, m_variantAction, and m_verseNumbersAction.
Referenced by BtDisplaySettingsButton().
isOptionAvailable()
bool BtDisplaySettingsButton::isOptionAvailable (CSwordModuleInfo::FilterOption const & option) protected
Definition at line 238 of file btdisplaysettingsbutton.cpp.
References m_modules.
Referenced by repopulateMenu().
repopulateMenu()
void BtDisplaySettingsButton::repopulateMenu () protected
No descriptions
Definition at line 171 of file btdisplaysettingsbutton.cpp.
References addMenuEntry(), CSwordModuleInfo::Bible, FilterOptions::footnotes, CSwordModuleInfo::footnotes, FilterOptions::greekAccents, CSwordModuleInfo::greekAccents, FilterOptions::headings, CSwordModuleInfo::headings, FilterOptions::hebrewCantillation, CSwordModuleInfo::hebrewCantillation, FilterOptions::hebrewPoints, CSwordModuleInfo::hebrewPoints, isOptionAvailable(), m_displayOptions, m_filterOptions, m_footnotesAction, m_greekAccentsAction, m_headingsAction, m_hebrewCantillationAction, m_hebrewPointsAction, m_modules, m_morphSegmentationAction, m_popup, m_redWordsAction, m_scriptureReferencesAction, m_variantAction, m_verseNumbersAction, FilterOptions::morphSegmentation, CSwordModuleInfo::morphSegmentation, FilterOptions::redLetterWords, CSwordModuleInfo::redLetterWords, retranslateToolTip(), FilterOptions::scriptureReferences, CSwordModuleInfo::scriptureReferences, FilterOptions::textualVariants, CSwordModuleInfo::textualVariants, and DisplayOptions::verseNumbers.
Referenced by setDisplayOptions(), setFilterOptions(), and setModules().
retranslateToolTip()
void BtDisplaySettingsButton::retranslateToolTip () protected
Definition at line 161 of file btdisplaysettingsbutton.cpp.
Referenced by repopulateMenu(), and retranslateUi().
retranslateUi()
void BtDisplaySettingsButton::retranslateUi () protected
Definition at line 146 of file btdisplaysettingsbutton.cpp.
References m_footnotesAction, m_greekAccentsAction, m_headingsAction, m_hebrewCantillationAction, m_hebrewPointsAction, m_morphSegmentationAction, m_redWordsAction, m_scriptureReferencesAction, m_variantAction, m_verseNumbersAction, and retranslateToolTip().
Referenced by BtDisplaySettingsButton().
setDisplayOptions
void BtDisplaySettingsButton::setDisplayOptions (DisplayOptions const & displaySettings) slot
Definition at line 90 of file btdisplaysettingsbutton.cpp.
References m_displayOptions, and repopulateMenu().
Referenced by CDisplayWindow::setDisplaySettingsButton().
setDisplayOptionsNoRepopulate()
void BtDisplaySettingsButton::setDisplayOptionsNoRepopulate (DisplayOptions const & displaySettings)
Definition at line 81 of file btdisplaysettingsbutton.cpp.
References m_displayOptions.
Referenced by CDisplayWindow::setDisplaySettingsButton().
setFilterOptions
void BtDisplaySettingsButton::setFilterOptions (FilterOptions const & moduleSettings) slot
Definition at line 97 of file btdisplaysettingsbutton.cpp.
References m_filterOptions, and repopulateMenu().
Referenced by CDisplayWindow::setDisplaySettingsButton().
setFilterOptionsNoRepopulate()
void BtDisplaySettingsButton::setFilterOptionsNoRepopulate (FilterOptions const & moduleSettings)
Definition at line 86 of file btdisplaysettingsbutton.cpp.
References m_filterOptions.
Referenced by CDisplayWindow::setDisplaySettingsButton().
setModules
void BtDisplaySettingsButton::setModules (const BtConstModuleList & modules) slot
Definition at line 104 of file btdisplaysettingsbutton.cpp.
References m_modules, and repopulateMenu().
Referenced by CDisplayWindow::setDisplaySettingsButton().
sigChanged
void BtDisplaySettingsButton::sigChanged () signal
Referenced by BtDisplaySettingsButton(), and CDisplayWindow::setDisplaySettingsButton().
sigDisplayOptionsChanged
void BtDisplaySettingsButton::sigDisplayOptionsChanged (DisplayOptions displayOptions) signal
Referenced by BtDisplaySettingsButton(), and CDisplayWindow::setDisplaySettingsButton().
sigFilterOptionsChanged
void BtDisplaySettingsButton::sigFilterOptionsChanged (FilterOptions filterOptions) signal
Referenced by BtDisplaySettingsButton(), and CDisplayWindow::setDisplaySettingsButton().
sigModulesChanged
void BtDisplaySettingsButton::sigModulesChanged (const BtConstModuleList & modules) signal
Member Data Documentation
m_displayOptions
DisplayOptions BtDisplaySettingsButton::m_displayOptions private
Definition at line 64 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), repopulateMenu(), setDisplayOptions(), and setDisplayOptionsNoRepopulate().
m_filterOptions
FilterOptions BtDisplaySettingsButton::m_filterOptions private
Definition at line 63 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), repopulateMenu(), setFilterOptions(), and setFilterOptionsNoRepopulate().
m_footnotesAction
QAction* BtDisplaySettingsButton::m_footnotesAction private
Definition at line 76 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), initMenu(), repopulateMenu(), and retranslateUi().
m_greekAccentsAction
QAction* BtDisplaySettingsButton::m_greekAccentsAction private
Definition at line 73 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), initMenu(), repopulateMenu(), and retranslateUi().
m_headingsAction
QAction* BtDisplaySettingsButton::m_headingsAction private
Definition at line 69 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), initMenu(), repopulateMenu(), and retranslateUi().
m_hebrewCantillationAction
QAction* BtDisplaySettingsButton::m_hebrewCantillationAction private
Definition at line 72 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), initMenu(), repopulateMenu(), and retranslateUi().
m_hebrewPointsAction
QAction* BtDisplaySettingsButton::m_hebrewPointsAction private
Definition at line 71 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), initMenu(), repopulateMenu(), and retranslateUi().
m_modules
BtConstModuleList BtDisplaySettingsButton::m_modules private
Definition at line 65 of file btdisplaysettingsbutton.h.
Referenced by isOptionAvailable(), repopulateMenu(), and setModules().
m_morphSegmentationAction
QAction* BtDisplaySettingsButton::m_morphSegmentationAction private
Definition at line 77 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), initMenu(), repopulateMenu(), and retranslateUi().
m_popup
QMenu* BtDisplaySettingsButton::m_popup private
Definition at line 67 of file btdisplaysettingsbutton.h.
Referenced by addMenuEntry(), BtDisplaySettingsButton(), initMenu(), and repopulateMenu().
m_redWordsAction
QAction* BtDisplaySettingsButton::m_redWordsAction private
Definition at line 70 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), initMenu(), repopulateMenu(), and retranslateUi().
m_scriptureReferencesAction
QAction* BtDisplaySettingsButton::m_scriptureReferencesAction private
Definition at line 75 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), initMenu(), repopulateMenu(), and retranslateUi().
m_variantAction
QAction* BtDisplaySettingsButton::m_variantAction private
Definition at line 74 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), initMenu(), repopulateMenu(), and retranslateUi().
m_verseNumbersAction
QAction* BtDisplaySettingsButton::m_verseNumbersAction private
Definition at line 68 of file btdisplaysettingsbutton.h.
Referenced by BtDisplaySettingsButton(), initMenu(), repopulateMenu(), and retranslateUi().
The documentation for this class was generated from the following files:
btdisplaysettingsbutton.h
btdisplaysettingsbutton.cpp