BibleTime: anonymous_namespace{btmoduletextmodel.cpp} Namespace Reference
anonymous_namespace{btmoduletextmodel.cpp} Namespace Reference
Functions
void fixDoubleBR (QStringList &parts)
QString processText (const QString &text)
return QVariant (text)
int rewriteClass (QStringList &parts, int i, QString const &part)
int rewriteFootnoteAsLink (QStringList &parts, int i, QString const &part)
void rewriteHref (QStringList &parts, int i, QString const &part)
int rewriteLemmaOrMorphAsLink (QStringList &parts, int i, QString const &part)
int rewriteTag (QStringList &parts, int i, QString const &tag)
int rewriteTitle (QStringList &parts, int i, QString const &tag)
QStringList splitText (QString const &text)
Variables
DisplayOptions const defaultDisplayOptions
FilterOptions const defaultFilterOptions
Function Documentation
fixDoubleBR()
void anonymous_namespace{btmoduletextmodel.cpp}::fixDoubleBR (QStringList & parts)
Definition at line 79 of file btmoduletextmodel.cpp.
Referenced by processText().
processText()
QString anonymous_namespace{btmoduletextmodel.cpp}::processText (const QString & text)
Definition at line 194 of file btmoduletextmodel.cpp.
References fixDoubleBR(), rewriteClass(), rewriteFootnoteAsLink(), rewriteHref(), rewriteLemmaOrMorphAsLink(), and splitText().
Referenced by Filters::GbfToHtml::processText(), and Filters::ThmlToHtml::processText().
QVariant()
return anonymous_namespace{btmoduletextmodel.cpp}::QVariant (text)
Referenced by BtFontSizeWidget::BtFontSizeWidget(), BtQuickWidget::callQml(), BtBookshelfTreeModel::data(), BtBookmarksModel::data(), BtBookshelfModel::data(), BookshelfModel::Item::data(), BtInstallPageModel::data(), BibleTime::deleteProfile(), BtConfig::getShortcuts(), BtQmlInterface::getTextModel(), BtInstallPageModel::headerData(), BtBookshelfModel::headerData(), BtBookshelfTreeModel::headerData(), BtBookmarksModel::headerData(), CBookmarkIndex::hideExtraItem(), Search::BtSearchOptionsArea::initView(), BtInstallThread::installModule(), BtBookshelfTreeModel::Grouping::loadFrom(), BibleTime::loadProfile(), BtBookshelfTreeModel::moduleDataChanged(), BtBookshelfTreeModel::moduleInserted(), BtBookshelfTreeModel::moduleRemoved(), BtMenuView::newAction(), and BtMenuView::newMenu().
rewriteClass()
int anonymous_namespace{btmoduletextmodel.cpp}::rewriteClass (QStringList & parts, int i, QString const & part)
Definition at line 176 of file btmoduletextmodel.cpp.
References rewriteFootnoteAsLink(), rewriteTag(), and rewriteTitle().
Referenced by processText().
rewriteFootnoteAsLink()
int anonymous_namespace{btmoduletextmodel.cpp}::rewriteFootnoteAsLink (QStringList & parts, int i, QString const & part)
Definition at line 90 of file btmoduletextmodel.cpp.
Referenced by processText(), and rewriteClass().
rewriteHref()
void anonymous_namespace{btmoduletextmodel.cpp}::rewriteHref (QStringList & parts, int i, QString const & part)
Definition at line 112 of file btmoduletextmodel.cpp.
Referenced by processText().
rewriteLemmaOrMorphAsLink()
int anonymous_namespace{btmoduletextmodel.cpp}::rewriteLemmaOrMorphAsLink (QStringList & parts, int i, QString const & part)
Definition at line 129 of file btmoduletextmodel.cpp.
Referenced by processText().
rewriteTag()
int anonymous_namespace{btmoduletextmodel.cpp}::rewriteTag (QStringList & parts, int i, QString const & tag)
Definition at line 160 of file btmoduletextmodel.cpp.
Referenced by rewriteClass().
rewriteTitle()
int anonymous_namespace{btmoduletextmodel.cpp}::rewriteTitle (QStringList & parts, int i, QString const & tag)
Definition at line 168 of file btmoduletextmodel.cpp.
Referenced by rewriteClass().
splitText()
QStringList anonymous_namespace{btmoduletextmodel.cpp}::splitText (QString const & text)
Definition at line 57 of file btmoduletextmodel.cpp.
Referenced by processText().
Variable Documentation
defaultDisplayOptions
DisplayOptions const anonymous_namespace{btmoduletextmodel.cpp}::defaultDisplayOptions
Initial value:
= []() noexcept {
    DisplayOptions opts;
    opts.lineBreaks = 1;
    opts.verseNumbers = 1;
    return opts;
}()
Definition at line 33 of file btmoduletextmodel.cpp.
defaultFilterOptions
FilterOptions const anonymous_namespace{btmoduletextmodel.cpp}::defaultFilterOptions
Initial value:
= []() noexcept {
    FilterOptions opts;
    opts.footnotes = 0;
    opts.greekAccents = 1;
    opts.headings = 1;
    opts.hebrewCantillation = 1;
    opts.hebrewPoints = 1;
    opts.lemmas = 0;
    opts.morphSegmentation = 1;
    opts.morphTags = 1;
    opts.redLetterWords = 1;
    opts.scriptureReferences = 0;
    opts.strongNumbers = 0;
    opts.textualVariants = 0;
    return opts;
}()
Definition at line 40 of file btmoduletextmodel.cpp.